sprite $cloud_generic [64x64/16z] {
xPMr0S10009fNlQVE7q4Y1lNmaLUiP_Gjy3y-F7ZirZx40KTyuQHqeeJiWxFfbpbWw1z2BZV8A4-38WFYqKVr_XugD_sllydVjkv_ivR_xr2SkB-rwle8VTV
_FZn7q0O
}

EntityColoring(cloud_generic)
!define cloud_generic(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, cloud_generic, cloud_generic)
!define cloud_generic(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, cloud_generic, cloud_generic)
!define cloud_genericParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, cloud_generic, cloud_generic)
!define cloud_genericParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, cloud_generic, cloud_generic)

