sprite $data_transfer [64x64/16z] {
xTG54i9G38JXr7F_2-EBlcIInI7_6FOjrbQUK5LLmxPv6wVXjtLf3e_I6XxbkU1kSW3wL6u0_6Q1vHXWEEeoRo-D9WdLmplnN3NonpjSrTM-dtKRpVq11qS6
VEqFW7SYx03UdHpe3AvciODMxMol6l7QyZ3q-uE8dV7zUuOZzjrHJtBqGNngvFFuVqro3Lt_0Xvv0tqZYUMysKi7Qa3kYU1SLRK6
}

EntityColoring(data_transfer)
!define data_transfer(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, data_transfer, data_transfer)
!define data_transfer(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, data_transfer, data_transfer)
!define data_transferParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, data_transfer, data_transfer)
!define data_transferParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, data_transfer, data_transfer)
