sprite $cloud_vision_api [64x64/16z] {
xP9RTW8n34EHF8vd_nlkktLpedcOV05pFrjBv0fkpyl51JcJXds0cVXC0Uq7tXkVA81re1wVAQ0DyCxbwYkY_qocGprUAH3Neh4IBnIeGrrRY1SBECH1Glpp
f3eyFd2S6W4sn2FM3oAWBexLFTOlmWz6q7Q8zOU0FalKovXvAijR0lVsW-tdhVtWtYaixPT5lN_pR2nkZgtzuArxPWUpWFhxOyQxzSPsgjyFknSgqix6twyf
zKJVw6w5VADs4uX3_tT8LxN78nJKrGYc_d0C-uzRbFhP4O22kXf1gHT6KEg54PHwQOHKhxC8zH8cr4jGg9U0f_hpSN7n3W
}

EntityColoring(cloud_vision_api)
!define cloud_vision_api(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, cloud_vision_api, cloud_vision_api)
!define cloud_vision_api(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, cloud_vision_api, cloud_vision_api)
!define cloud_vision_apiParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, cloud_vision_api, cloud_vision_api)
!define cloud_vision_apiParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, cloud_vision_api, cloud_vision_api)
