sprite $cloud_run_for_anthos [64x64/16z] {
xPHdbiGW38Dj6H3tl_2MA5xU5FO5vcyqlNp2I4diFzswvVuPN-j7E7h79tmZc-qBx9snpxF_YDju4LzsksFl_7tuPdViZ61dtL_UR7k0nYFxOD_g4EBaWutk
4WDtEZnponpBJdZ-y7v5ZskMvGuzznnXjjwXkbCAOSiTghkC7kiTDlOEuJ90b-5ITyZp1yep5avxkl3MPB3IOJcw4suc0tsvq5tYQN2vGsMT-330rGvHs0O-
3Avtw20J7mOblvjZyIkO6VZurvPLnfmEIGweVdnPYgV18Svm88PmVbVvemeR1YmNS1cWTHv8RnW6zDdmxX6EOS1ZptfkSHfCBWI_Y9l3BGtS2jbRXAOW2ve6
m2Gxw6hXEO2puan13XhWNOTQL7mQcFcVlHoaTnqc0VYVdJyCM3WiEE7T71XnsgEYCVdooey0qi0joeFg6C1dwui_rwzyL4-nJdW0kNyLFX4nptzyubGl7Rxs
xxOYl1n_jgRduzzjKI7ju1AmZsVf4cnJxe1VNllMhMy
}

EntityColoring(cloud_run_for_anthos)
!define cloud_run_for_anthos(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, cloud_run_for_anthos, cloud_run_for_anthos)
!define cloud_run_for_anthos(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, cloud_run_for_anthos, cloud_run_for_anthos)
!define cloud_run_for_anthosParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, cloud_run_for_anthos, cloud_run_for_anthos)
!define cloud_run_for_anthosParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, cloud_run_for_anthos, cloud_run_for_anthos)
