sprite $asset_inventory [64x64/16z] {
xTOt3iD050DHnO-z_uMTJSSH27OAR1JVrDjjSiUEZRghbl2nn5iB-5WbpW7cOpq2JG6VFtmO6EKXuF2komBYMK0y2uX3mESp15nU1G6NGy3ZKX3mE0HSJW6V
jmO1bqF0vHWmEGTixWVqsrVWw_tqnJdWSWumzmB8tG1mAy3S3Z3t0y3z070_0DmE4FS3ubb0F0k8Xm7nC20U1iJ307EU_2NmnTt0yldlsB5ZPm
}

EntityColoring(asset_inventory)
!define asset_inventory(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, asset_inventory, asset_inventory)
!define asset_inventory(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, asset_inventory, asset_inventory)
!define asset_inventoryParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, asset_inventory, asset_inventory)
!define asset_inventoryParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, asset_inventory, asset_inventory)
