sprite $healthcare_nlp_api [64x64/16z] {
xTE50OC030NHuBV_mdL7arydLq4VZftACdeDp_qpdn7fRtn6fFJ_Li6kBinxLyPrvMgkHJoxsjCGlxzJCN-tAKSz4_Ebw2l5jq3FUzwO--lNHJozCOUtqneT
kngVxwsjlJw5n2rOZxevmY7LW0aUQ0JVMyllJGjxVrcs1G
}

EntityColoring(healthcare_nlp_api)
!define healthcare_nlp_api(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, healthcare_nlp_api, healthcare_nlp_api)
!define healthcare_nlp_api(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, healthcare_nlp_api, healthcare_nlp_api)
!define healthcare_nlp_apiParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, healthcare_nlp_api, healthcare_nlp_api)
!define healthcare_nlp_apiParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, healthcare_nlp_api, healthcare_nlp_api)
