sprite $fleet_engine [64x64/16z] {
xPPLWi9050JVUDt_mkj8myis-fT2Hwh7aCI1dHq0AVrXD1LAV3512SzPLnAMz_bxYWOmBeFhRNwF24Bf_E1yvdOd6s2swlc0m2yXRC0o9s42x4aiOBg0lEbo
0jTzEP175mdWm3A-M5a0j_cIfKhJW99kst_Vv6hsBzcej3HkywTicyPbVZchH8nVdA_VzsD0AsVJbeCMqdp-a4h9olt3oZNWtB5-f3xt-wTIVT9lplVpdzRN
bPPi_xqVW4Ib0mXcUssxLaupF-Dd4-GMlsy6i9sUfbRvrKCDrVFgmY-zmvMU-qlh4S8CdmMBxORFanUCV9P-0Zc7VVK1laVUxFJ7yp6wwMDqEJMzy4hgNG1Q
u8SPDy615fmJDuDWRPymuW666znZT8_RTyzgyJPsFW4
}

EntityColoring(fleet_engine)
!define fleet_engine(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, fleet_engine, fleet_engine)
!define fleet_engine(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, fleet_engine, fleet_engine)
!define fleet_engineParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, fleet_engine, fleet_engine)
!define fleet_engineParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, fleet_engine, fleet_engine)
