sprite $database_migration_service [64x64/16z] {
xPLRTjWm24GB0yZxtt0VFawHFKGgwRiD_vV3nOFruK-izn8t-GuSOqJWhRJ6E8w8S7tRw6CS9n_Hbn0xwOkFiAxuIISVZfxuLUF26siGFyOBFGmNpMkG6hUH
jCkNJKJMF89fBPwZwwNZfO65hiI7JLqzwOcd1XOlzE5tFVkwV_MdJnRW8qVdoctK3O2pmy2hkOXdwPC7x5NQWygOXmgXAKuuyu0kn0dFKgKEBEugPtbnLO8i
gKT7VbAhB75Lha6yF06hzonpXuVuBLHfk990wu1PWiL5lrJ9GQd3NJnrfEOXZpKyHaV4Yf_39ydJxIrut2NcqIzwnLE7y4byntFu9CMptDsPv_1j0hphKDpU
_YaJxj298DyWF6cquplHONkGEv2uB1H0ySLJ7BuOW-EBe00lU8ulwFQsFA2Jn3IwRTV8yOKZ7uyzp_7b05itllK_T1y-BH-FLdmxjrTVSVruVFCDDc-F9Ngt
nnBqqPeTIl766dhYl0RwPhtI7FqFhlVw1
}

EntityColoring(database_migration_service)
!define database_migration_service(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, database_migration_service, database_migration_service)
!define database_migration_service(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, database_migration_service, database_migration_service)
!define database_migration_serviceParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, database_migration_service, database_migration_service)
!define database_migration_serviceParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, database_migration_service, database_migration_service)
