sprite $anthos [64x64/16z] {
xPFR4kCm24C36EBy_mVtggd6UBP9yUpJhbvwon6oSBU_gVyoMyAbDLaQtzfA07tokZIU0MhZ5m98WwIQ7hBoU4ZgvR72KdaYrGeDdBxU5CS_tvK283QTf7Rp
-BwmEqaV2kCB0LZUIuKA-NpokoYTyhvuhPJtOuMvheYVAiopl7V_9G3F2lmuOC1EhkpEFZWC-7-wjZlYCBYsG-O4tZiChkoGFH6d0NywtHrnLHZmj_FnnEr1
qU0i04icJWEkvcHt8qw3anqo8F5aWEETb4Sy6x32BxiZFXla7SxZDU79G7E0VFFy83uR79vkOHuV8ou8IuFuKm2r2LVl3xbE1jmXDKtNw53eb632ytG33GVB
2H8k0ovjxqbxay50fl70THCd7K47bqq_1fRB0svAehkYH2ZKO90g17xaUI-bF0SCXl4lF9yNIdqWWIb_Ra6OVLFS1os20omIhUGeJGwV6KASnyvY4JJ0Wpuc
boyQJ-6ubcNPCzHUvtTX-f9yqxuazLYIR_-uxW
}

EntityColoring(anthos)
!define anthos(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, anthos, anthos)
!define anthos(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, anthos, anthos)
!define anthosParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, anthos, anthos)
!define anthosParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, anthos, anthos)

