sprite $network_tiers [64x64/16z] {
rPPLWiOm20RvaD3xNtYbbhz6idIjypx4W40FuA60HJyGHi8LAo-OV2b6bIictNQve2i2Mxd4c5fe2L6AiTB0qEFd0sXfSZU0tGv0fp0BuoM0Ca04iFQy0kGJ
vZc0SPGKJ0TaPWeWSLBQGMTP01613i32L9OLxigDs6y7a63_Lo2u0Qm1EYiRvnjWxYeFTpr_0QO87bNtOHZAIRziTyfH7N5G0gi-KmAflb027bPVAG6gRvJ1
LvHMr5SeVwiZe0HQ_Rzv5RztgwY-KmpKz7Z6Cha-jiO87Vo3G_7gg8vOnqMx1vr5EhBFDMXjQB-pb-lEP5tLIpkw9WIzzgL39_RhDB5L3_fOySlcnQFUwACe
xX_sQPPhrOC-hiNTG6UOdluZK8k7n_WVutXeQVsZg6cHyhKiS6h_5YTMDCUCbD0FvwWHY-eocEEEXGLAONNv5B2gvs1H0Js09_8E
}

EntityColoring(network_tiers)
!define network_tiers(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, network_tiers, network_tiers)
!define network_tiers(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, network_tiers, network_tiers)
!define network_tiersParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, network_tiers, network_tiers)
!define network_tiersParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, network_tiers, network_tiers)

