#!/usr/bin/env bash

./convert.bash DaprEncryption
./convert.bash DaprSidecar

./convert.bash DaprWorkFlow02
./convert.bash DaprSubscribe
./convert.bash DaprPublish
./convert.bash DaprRedis
./convert.bash DaprPubSubTopic
./convert.bash DaprSubscriber
./convert.bash DaprNonDaprPublisher
./convert.bash DaprNonDaprSubscriber
./convert.bash DaprPublisher
./convert.bash DaprRawMessage
./convert.bash DaprKubernetes
./convert.bash DaprOperator
./convert.bash DaprServiceB
./convert.bash DaprServiceA
./convert.bash DaprApp
./convert.bash DaprYourApp
./convert.bash DaprMyApp
./convert.bash DaprDocker
./convert.bash DaprSidecar
./convert.bash DaprWorkflows
./convert.bash DaprKeySecret
./convert.bash DaprDistributedLock
./convert.bash DaprConfiguration
./convert.bash DaprSecrets
./convert.bash DaprObservability
./convert.bash DaprActors
./convert.bash DaprResourceBindingsAndTriggers
./convert.bash DaprStateManagement
./convert.bash DaprServiceInvocation
./convert.bash DaprPublishAndSubscribe
./convert.bash DaprSelfHosted
./convert.bash DaprEdge
./convert.bash DaprCloud
./convert.bash DaprApp4
./convert.bash DaprApp3
./convert.bash DaprApp2
./convert.bash DaprApp1
./convert.bash DaprUser

./convert.bash DaprBlueLogo