sprite $genomics [64x64/16z] {
xPPdeiCm28Ch14xkV-4ExBUonDkhtxyEUI0bSFftt86PBRzYE8fouusN_uvsXOgnLUUvd2sP10rZ--K1l2MpO8fdUdl3_gV5_elxcs3x_WcTgDetjdyxPlYL
kGKgnR6Zt9geJFg81Vsdr8lAHS_H_9BCBGT7ShHD_IruKFfa9yTMrVCc3rzW-LDYee2Cy3rdX5nYNvrRc31SoFc-9vM3_wZNzQlxzvN0tXdnWnjx1AKyoPFu
WjwZj6Fz03OjQKbL7-kNM89gOcBQqeSqd1mEO05lUc5Er-__Y5AJ-eMW7DltZoIWSzFtqMW5NEK0pqSwDSNDBU7IzTHdx0GjyPtzeQV8XBltfsBz761iNmCU
XEYj_uCx5m
}

EntityColoring(genomics)
!define genomics(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, genomics, genomics)
!define genomics(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, genomics, genomics)
!define genomicsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, genomics, genomics)
!define genomicsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, genomics, genomics)

