sprite $cloud_gpu [64x64/16z] {
xTO53i9G60JX7v_xNnYBe4isRBrl8b3vwbRTrkAU-Zzftpn68OUGm-GyVoLy_MY6dipZ-9AN-0Ra78udysIUSJsErwS5uStpptEXBz-ZkUzV9nn3xrx_mgVN
xxY-Cb-PtrjUdx_q-Ra-xpVNxuTJ_FsKBE2qbE_NvlDQ5m
}

EntityColoring(cloud_gpu)
!define cloud_gpu(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, cloud_gpu, cloud_gpu)
!define cloud_gpu(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, cloud_gpu, cloud_gpu)
!define cloud_gpuParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, cloud_gpu, cloud_gpu)
!define cloud_gpuParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, cloud_gpu, cloud_gpu)
