sprite $project [64x64/16z] {
xPKt0iCm30EZIl7_3qwROfdoaLEQiLDGm-7oASfjgngSdyQxfD1ucSUbHSRJP2ztvS1ytTcBzCZb6VDI0lRc0YbWRro0LF_RmGRmxUmDDF_RsHl8aSk3DoHx
U4EqjnVmt9uj6RuRNDch-bums_D3TKZriA4kx5N5nOQqi5SjApRW5ShJtii6U_UQlMmefdttiw7rZPxZclniABfNZR11TDO8iI7hh19ZGv_69Sg6_AAK4hFX
P0FqFx41-f_OGFrFRC3-1pPW_mCRkF-13Tp_m0RiVs03z_yn6xZ_3zZWwt-R3Vx-DzdWp_ZP_o3AE0WpJeACeo3ZBCWu2pAEWeop8ECeo3WBCew2Z7-qRW
}

EntityColoring(project)
!define project(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, project, project)
!define project(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, project, project)
!define projectParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, project, project)
!define projectParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, project, project)
