sprite $visual_inspection [64x64/16z] {
xPE7iiCW30Gbds7y_p-Sthbm34eFE-KLiGjkzZm60o2e0q4T2DYH02u8wa1G1phi_W0eGHq8wa309W6jJsMmwwLf3jnRvsGWDzTbhIUG4u3hnOgyx70wrlfo
GWV8Squr7rNTTzjV8Bx8OaJyIW1iafZF0_aMsp0NFbr69_JypdKM0FFpDSckADDJzVXsI-K2CbiW0XS5DcOqzvDnN0NuY1_1oPJh-XgElrDTFSVBM4wcyCon
PZuq06l7nUwQWCuVP2GmMmykDjS8NHFGvGiVPp1O0m
}

EntityColoring(visual_inspection)
!define visual_inspection(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, visual_inspection, visual_inspection)
!define visual_inspection(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, visual_inspection, visual_inspection)
!define visual_inspectionParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, visual_inspection, visual_inspection)
!define visual_inspectionParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, visual_inspection, visual_inspection)
