sprite $looker [64x64/16z] {
xPK7bXin34F19kZ-9ywR7LgkiehJax_hJe1j2XxuZtonBqy-qMFV88M_JeyzlPY7co3bYthnSkAfNfIN2x4ZHzp85SlO8NKHCK2BOPL3Riqgi8YK56KdWZKq
qn_uBz1_Ld_EJzicOcz_9ldEi4mxTcKdVJj-vUXVi87ufG317c8HdkVnCKHNRE5inAg51I2i5rYBBWsHLO1WRP2EMPIiZEErti22AL9608KdImQPbPOh50ro
mU0C9WqDyQp0CIHE-SF1f-cg6A1dei03mhaE2ZjXEbM0zAFyoRaR57Z5QItZygk-yJOqkZawlTrETYTaF01j9NQR-rJF7whFetnO__xyOdj_ol4f66y641oV
0DRViRJQnWrOT_enq7ll1FI9qwTL-MnWDLSpmjB0dcStJdyR6dhZoVg5OeAI1hMugQh5HKsVldkT74AcUbQUBJn16gOnyb5U50j8yCQ2B8P5n0eh3t8L6uYQ
cGh-3Ru1
}

EntityColoring(looker)
!define looker(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, looker, looker)
!define looker(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, looker, looker)
!define lookerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, looker, looker)
!define lookerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, looker, looker)
