sprite $private_connectivity [64x64/16z] {
xTO54eGm44JHYKrn_mkl3WvT7Tn-2KJUkY17xEafQ2ENgxNN36tDq1R7GGo7vV6HAPA3MPOxrVuypzjdLg9zzzIYULNdqynx_03mM-T7lL8-PFhOlVzKHNbj
D7DT1bl91ol71-lellWqmnU_rlLLELwibRqOfxmdthz3hmlhPIKlS4F2tBm5rhoCfqI28ZYEu3Y2up2VSmD-zUktAg3P03v8Jqzl
}

EntityColoring(private_connectivity)
!define private_connectivity(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, private_connectivity, private_connectivity)
!define private_connectivity(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, private_connectivity, private_connectivity)
!define private_connectivityParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, private_connectivity, private_connectivity)
!define private_connectivityParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, private_connectivity, private_connectivity)
