sprite $cloud_cdn [64x64/16z] {
xTQ5RiHG34JH-7a3___32xSmKi1LtfJR4HJF5Inv-CZzByBpEOR5St82UVT68F7TWOOdqCdn17fvD09ZBn-6la3WWnA1Tj8ddBLE3oVGuU4AdFRjphKyxU5Q
ud_zWkaxJRyhT3xMulNvfusfNnuMaeLIualgj_a6Ntdu35AWu2iFnrS1yPM7oojGSdcul08bbuVZYq28hpmSN_xtE3sMMp_EMx_pdXeJoxM_TsTvyVlWHm4y
d02-uWh8mmdWQww0F9o0l7WT2BW2-1Ml0W5N0B_YLI0kmYmBha1Zl6Mlza3wxi_TRMb-VfcVd_Rdjty_kFUBUJ-PzvjxFxhtgty_V_xzJW1k13m-HCNz_Uy6
}

EntityColoring(cloud_cdn)
!define cloud_cdn(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, cloud_cdn, cloud_cdn)
!define cloud_cdn(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, cloud_cdn, cloud_cdn)
!define cloud_cdnParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, cloud_cdn, cloud_cdn)
!define cloud_cdnParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, cloud_cdn, cloud_cdn)

