sprite $datapol [64x64/16z] {
xTT7ZaCn30DGYNIx_uNJgm0D62kOLTxMzJT-sRxk1tSME6xyx-6yGkp66z1opgSmCH_SKk0JieafB1-xaTdCQI-oF_2TiFkpiUR5cgIo0GPjhgl6m3yRtxNn
Njo_XLvuuflFdn-4vKCt5zwV2CNtT_Qq5y4Bm59jpZ46_Cm2lxEKptNIRLS_Zv-s2-jaqdQDy_1XgfXjRAtr2IKE8u8tBKxCAq1BlT2Dqbl3h1kajnPQwhdq
qR5zBVM6b1hEeAshsHXeutiwNjl_N3Tn__uVgGVn-MNTqfcny_w23rBLm9xC35WKmutZP55FlMYkKdmPBXCqspRccgEx5_Ax-FyOofDqIpNj_rdyVxibG8sP
Mh_SRDPVwwFwoQlr6sAIvKagNK1xa9Qlryz6gNwldX_gvvVw-QdkvmW
}

EntityColoring(datapol)
!define datapol(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, datapol, datapol)
!define datapol(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, datapol, datapol)
!define datapolParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, datapol, datapol)
!define datapolParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, datapol, datapol)

