sprite $key_management_service [64x64/16z] {
xTO5ZXn138LXywlxNpXWfQSYDza1uVx2XQ_0W_G_-qgL_nopHG0kVwR5uaThOOMECQj7jdu4m7YyzU6poJNKOxUEW33kpIogRnz2Kj_vFSlxcTK0RFuuIpjZ
LrMFXLMMy2llLH_xiAyIEbxeas3ga-y4G_zhp2oQwv1YvlqOALRa66BcvVZDMW3d0KO-IQHV-N3noFld5vz_d_lz_EKzWF--_xw_bVjFvy_J-PSBv08098Sn
yFlfAsewVlvbpaGxdZt_wmA2eS_qsDosVl0MfopN1LOfcZwV1cSEl_9wvrSDTkMvxvMkQll5bzwx7aIl0t3-6QNlNByEm2Yxz4BNUSy7tIGj3wMxl3C_q6tQ
y32wpnkU7fBouKtfUxVFR7kzcX-2dlCNp_GSFtkXj_Jm_YFUlio-zo0ACMF4wxC0XKyNcFBwDFXeAFLZBnx1D4f_zu3HDBR30yv3lByFOuLjFOtLXFvZNtq7
}

EntityColoring(key_management_service)
!define key_management_service(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, key_management_service, key_management_service)
!define key_management_service(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, key_management_service, key_management_service)
!define key_management_serviceParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, key_management_service, key_management_service)
!define key_management_serviceParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, key_management_service, key_management_service)

