sprite $stackdriver [64x64/16z] {
xT57aiCm0CH0A4tj_p-ypjaCPUX8t7iaakpQQBGKibnxpnCQJGK-0Qo9_7mYULRf8tbYlUJbWQd6rzoJdqyapofz94_w_LJmwlEV0tEDR_b8VZwHF1izbNqa
JwpVy___2fNzX1lWjQdW0p0LkFW1t03Mkm6Sdt03NFln3G7r0xW1h7S3E3_X1cZKU4D0_G1k0E7rmEwDHWS
}

EntityColoring(stackdriver)
!define stackdriver(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, stackdriver, stackdriver)
!define stackdriver(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, stackdriver, stackdriver)
!define stackdriverParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, stackdriver, stackdriver)
!define stackdriverParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, stackdriver, stackdriver)

