sprite $migrate_for_compute_engine [64x64/16z] {
xTO5ieDW00DXdDp_ma-Bi_C7rnsfVgbBTCxU9C4HgsIkVxr2tTz7t8RUkeUgAXPwBRtzxP-_Katb3Azsz_VwB-2hYeLU2trvlzSlLTKSdwZTP6z-oqboUFXc
SkHL4xv_2i40-v9MLPUxZv-UTjl3G3gCVNk00my3di_rMruL6e2RX_EC_n-PxI714-1wuBP7RlfimC5Jn3aUq28luA60-m6VkP17SuBRFcrltm
}

EntityColoring(migrate_for_compute_engine)
!define migrate_for_compute_engine(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, migrate_for_compute_engine, migrate_for_compute_engine)
!define migrate_for_compute_engine(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, migrate_for_compute_engine, migrate_for_compute_engine)
!define migrate_for_compute_engineParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, migrate_for_compute_engine, migrate_for_compute_engine)
!define migrate_for_compute_engineParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, migrate_for_compute_engine, migrate_for_compute_engine)
