sprite $automl_natural_language [64x64/16z] {
xPL73e0m4CJexFzVp1c8fL5wypdUBbZwOZ8nDskWRwgEXFg1-X6cMzRg0tT_UhZXwRSGFJozLPNUU_Sx-tfwzY7QAULYtqIVdeZwXMy-FlJFIPmlAIXsfleG
8EX2IPU7hASde7_Gi_bHFm_N_BRM_XT5zeggPq9zr5N8xul9v04
}

EntityColoring(automl_natural_language)
!define automl_natural_language(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, automl_natural_language, automl_natural_language)
!define automl_natural_language(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, automl_natural_language, automl_natural_language)
!define automl_natural_languageParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, automl_natural_language, automl_natural_language)
!define automl_natural_languageParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, automl_natural_language, automl_natural_language)
