sprite $dialogflow_insights [64x64/16z] {
xT853iD030NHfP3lVz_Yg2ie-RlSZC2YboobPxPMSaJNGxgc0AU09bsJuo1p9QB0pocWITSKu7HPbujc75izvVixVgozx_Bq1j_NFS-pwiVtU6Bz3Vurvy-6
6TNCN7u6Cl7I_nl-oywFzTh2zFc53LkVBc-YNpsPDMPznViZdLFMDTtG9Tqiy7FIDGKqoPnaJJ6Dfv92FYd9ccHDS3cq7FhJMzi2
}

EntityColoring(dialogflow_insights)
!define dialogflow_insights(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, dialogflow_insights, dialogflow_insights)
!define dialogflow_insights(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, dialogflow_insights, dialogflow_insights)
!define dialogflow_insightsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, dialogflow_insights, dialogflow_insights)
!define dialogflow_insightsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, dialogflow_insights, dialogflow_insights)

