sprite $identity_and_access_management [64x64/16z] {
xPTLWXmn34J5vVjVEDI9bgh744xs_JzPE20_atVSzLpMg0BIpcoB-iGO6ENRidhM5yOd08JkFzt-9tRAk9vkloDKw5hFYlWi2Puuzpi9d_MC-yrjBwCOmDi8
evXF7i_mI19Xw8h_jLcQRm9WnK_jod3YgpI9VJz46ZtmLPvHsFRbEV7t-KRgF-s_uM3-Hfu_sx_Ssx_6h-JhOF_x_h86ne7Fxh-1RFXOz8Ebxnw9WGC_NNly
yIg9OhwJtZV-F0AI-SfctsYXVRWmdkaiF4PZr4zwEus3j8ytG1ZQUd9VYSyAW0adswUqBpVOae-GEtB9rrlV5_n-df4BlZxmxU7ysUxn8r8I-j9B7fDt-q-o
PoW_80Ev78gn6t3Q-yT33EsS4htu6m7ABpkmeFD3T6sR9y-nQiOt6oxhQBP_WJBPmlEP3vBxOXU-sBqD-pdqVuSZrCFa9_BEHm
}

EntityColoring(identity_and_access_management)
!define identity_and_access_management(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, identity_and_access_management, identity_and_access_management)
!define identity_and_access_management(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, identity_and_access_management, identity_and_access_management)
!define identity_and_access_managementParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, identity_and_access_management, identity_and_access_management)
!define identity_and_access_managementParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, identity_and_access_management, identity_and_access_management)

