sprite $ai_platform_unified [64x64/16z] {
xTQ7SWCX40FGBTV-_uTToMZs06L9BoXnznECkIO_E3FBjhtBRxTyWtUl_K2HtrDFP1loRa6FUFLdHZd6z1A1nk-midbBRD2W-OhOauI2eXMwxK7G00vDF6RW
-j90T6eAbFC6UA9f0ppHhA3ujMXBR7XemFB5mVsG_FPJQJbkOJw-WXxts7vSc0z27ypYzWFwk5UXwMm_noFvrOj-F-3J1V17ccCtqifBEYql0r7YwQ09twY2
T-lxehbtPvulWvUqFJO2VNNFR_dKHc1UKdbe7kubaRutoUNTswyrzfzVSVqp_VJJ8-0_CZDN
}

EntityColoring(ai_platform_unified)
!define ai_platform_unified(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, ai_platform_unified, ai_platform_unified)
!define ai_platform_unified(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, ai_platform_unified, ai_platform_unified)
!define ai_platform_unifiedParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, ai_platform_unified, ai_platform_unified)
!define ai_platform_unifiedParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, ai_platform_unified, ai_platform_unified)

