sprite $onboarding [64x64/16z] {
xTRfLiKm20HW2KmcVVy7TjTn2t9mzrx-zdnjCsIx-CLrBaTONmzWaj7LWLlFwGrj0TnxSew6bjSRYje1-Vk2rKDNoPDXnT0tdenAw8ddz49iYLUG1IsVlq6X
vpvjXNJcrOeaz88d8mczujKAawvx1Jc0fYVdXxw_rhB--BcEHMldp-EQqzhzZnjEQy-_M9Hlp7-dV6FzoNVMltnl_v7lxN_oZVrtxzqA-x_5rWVStZj_Wamy
uBlpJohrmDYUlsEouFK6dV_I5OyOhti2iko1iESwo99NkUc1TDsh5JxPye1BjpmWhT8omsRngiHBH_X8VEqAuOclNM5yws7LovjyUc_8to1Vrsg5VEyAE-IR
LsY_z-qhl3ccGk-z8OljNEUw0W
}

EntityColoring(onboarding)
!define onboarding(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, onboarding, onboarding)
!define onboarding(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, onboarding, onboarding)
!define onboardingParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, onboarding, onboarding)
!define onboardingParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, onboarding, onboarding)
