sprite $cloud_security_scanner [64x64/16z] {
xPPRRkqm24LvRcV-8xwrGkHBYupSwlnb_SBQa7Veixoyy1zrLU6_-Ic1-InDH7KbY6DSmuuMk0Dq1XY0yGNu_1XKI06O-WoWCqGd07Z6OGojktYtWW6tnlK2
hBeDS23A6AFMmo_f_4OdtkmVuuLs202EyLgEfpq6mDH6ELvY-mti0CQ4Vuuto-F576xohGdp_dKkpksum6dKZNDUqbIAuPYvr-2a1qoB-c5cXEyKE1PEY_eQ
sUsl1HJ_e_av-Edxur-InWVU-VRTHuRNaPQ-Flw8haEVmX_sIr-cNvp-W3gVsDCpOKctpVch2roj7ssInNennKBR-oSgN0PezuQhazamCQwECjYNM4HuDwIf
DJEg8czrte_GbTutdCUJh7hVSAx7Wb9-Tumbjj-YnJV8xqTpLRg0l88zhuRG6zRVIdgrVc4dVmepWYVhrMH7_pk1MEDt2SjNEe3boSYVXdDa-clyEU8OZTx0
AlG1Nbx-0G
}

EntityColoring(cloud_security_scanner)
!define cloud_security_scanner(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, cloud_security_scanner, cloud_security_scanner)
!define cloud_security_scanner(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, cloud_security_scanner, cloud_security_scanner)
!define cloud_security_scannerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, cloud_security_scanner, cloud_security_scanner)
!define cloud_security_scannerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, cloud_security_scanner, cloud_security_scanner)
