sprite $data_labeling [64x64/16z] {
xTPNUiGm20HWQGPGSlyBnzj94IOYFVi_cs-mUljXxkxwhh2Q2RrIVj1cm9HYF8ln3EFR_lX6yOZhmSrY_04EmlXbBZws60-vmiBVmno-FrxCaIWUecRAi7uU
tzNEaEtVn_VfLv0hpkFL7BGC7qyx66FOWROSN8-Ly_20DcpJNTyEV3O0tGWs70UAVXu7kd6RZ9yzlFPehUaupPFO6-JZwa57ne4HsVwz_FXDobVcpmlNJmm7
wVMBD-f9BEoVmlujdH_LywjsVZBOmzK3V4Nz_ghVd_Nxku5Vz7ufDb1zlrNVZ_Ntw_Uxkti2
}

EntityColoring(data_labeling)
!define data_labeling(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, data_labeling, data_labeling)
!define data_labeling(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, data_labeling, data_labeling)
!define data_labelingParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, data_labeling, data_labeling)
!define data_labelingParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, data_labeling, data_labeling)
