sprite $security [64x64/16z] {
xTS5RWGn38NX6D_C_I_SHKlDYtPSnbzO-1Axi32-To9lqXO8VQrMZmY0J-ZhI9nBU_dW4UNFkRn8LwX2-uDN3j09VMqoyAoqzk1nlGrpBYtjPysUrrYlNPS0
lHEcjIkiozbFQnzviA-rN-LhxRTu6M_p-eFzl__tyYQV-PRxSzjt8ou9RjlOUvuAZbVoVT-sfC_6ka751e0-RtsFKpwcjErnpkW7rVMAS_nZwNh7kK5vq-UP
1tljUQtrvte-QlmvxtX1ZT_x3Iolrz4UOBLzZcLwxBEkN-L7tkdwmvy0Jr_NSyQU7mkSNVNG9qrFoGCVD7tdTp1p6u-pbQ_T4UCeNtb3ySESl0JnzWedxI3U
Fy02ztnqq-9PEdMy89jzo7XHukKNb_VVnx3k9-Q1T7tR-zVltHC
}

EntityColoring(security)
!define security(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, security, security)
!define security(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, security, security)
!define securityParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, security, security)
!define securityParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, security, security)

