sprite $cloud_deploy [64x64/16z] {
xTHNTWKn20FG0L6y_msdHocaOFmx-dhjwXt36L-_viuT3JtpkLnE_5gPTkIV6t3WdvEXHtvn34FFCGmy6m9JpmQPUXwYqI2_-EukuKgVttndbuZWjYnBGzrb
zH7l1nLVjI7rNn_SbaOjGCC7nu3CWUSXE8PDNyOmyE5b36t_VGoM8yz3wDyUx_yZ5j-3ZWVUnwrU2beUMXhsFA1yMpmw7cKCcxwCOT-3O_2P1tJVAqf3opFo
jQ7l6PbwHgQUqJFFWkebSkvvZKqzhx6fvpKszhpDszwAVuwrFH_1hq2avvy3-fAMlyGslRvxDhWtF5FyS-Ur4wKVHbJfPv66ltFd4G
}

EntityColoring(cloud_deploy)
!define cloud_deploy(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, cloud_deploy, cloud_deploy)
!define cloud_deploy(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, cloud_deploy, cloud_deploy)
!define cloud_deployParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, cloud_deploy, cloud_deploy)
!define cloud_deployParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, cloud_deploy, cloud_deploy)

