sprite $cloud_audit_logs [64x64/16z] {
xTS5SiDG30HGYtt_2vSseFmcMqsPD1Hh_DPiAzi7rd-9ghnUYpsMokivwfK1QeVIrtaxrTo8BBk_780grP7fp6TL2kMPTdl_hVQzIXZlEw2sN42l7G64fwuN
e3LgHm3Xrdkwt3xU0pZlnGCuvm6SYwZAigcu5d2DYnsweIy5-7CkwA44hSi0xvjVkMOl0zCUKBbits_ob2TqtkKallCmCu-m9zxsE8jwWNRPK8sFlBVxkFEX
5yQvxqih7_iud7BtpgSUknyFpO82dtizt34Er_dSwuQ0E777Sp3t200_TEVUqAygSAmY4ozjmI8ClsBerrMNYpBnrfVw6lRQ-nUHAQzzVi37pzzs-VmAyc9h
Vlh-KBD8b1BFtb-Ta_VNylwCIntWxFs9WBM7mhxTV7yB_twOyE_7wxzVF015EG_WV3u_S3wVNupmoVoK1VxQ-SsBSGG4cLy5yoCfVUNyokVdhvdV-V-7UO1y
mV-dOVtNFG
}

EntityColoring(cloud_audit_logs)
!define cloud_audit_logs(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, cloud_audit_logs, cloud_audit_logs)
!define cloud_audit_logs(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, cloud_audit_logs, cloud_audit_logs)
!define cloud_audit_logsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, cloud_audit_logs, cloud_audit_logs)
!define cloud_audit_logsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, cloud_audit_logs, cloud_audit_logs)

