sprite $financial_services_marketplace [64x64/16z] {
xTK5WgD048NXqlVg_YVUQc37eXt6Xp-2VX5KFgmZZGIHzgX6Hx9I7-49P9W7EvttpLsMeiXfxYltvOsCMGyCekjFn_GFCC26hnhUI9l--VBibOmzNZxT6w3F
teg-P_ld64oaAh7i08reQ6IAwTtQaQ80J9QSf0ePUkUcwrmCG9YQPv4cmHx4dRepqKJ73YREwcv-WhNPydMgECQYjaY_uykNKjSjAM9WFSMux1Elod1pJrJp
vtZPupHou1t-jClUJlFJvDiMUH9Eoe_RVdcFXtpBzk___TiFfzL9qvxT0aUtlFKWjgD4LpzcWSKnopdlTVFn_VtX3tzut-73p7Bu7lhgmxrP4JrCFdxzMaSc
FUjDt-h-TVGF
}

EntityColoring(financial_services_marketplace)
!define financial_services_marketplace(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, financial_services_marketplace, financial_services_marketplace)
!define financial_services_marketplace(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, financial_services_marketplace, financial_services_marketplace)
!define financial_services_marketplaceParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, financial_services_marketplace, financial_services_marketplace)
!define financial_services_marketplaceParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, financial_services_marketplace, financial_services_marketplace)
