sprite $active_campaign [64x7/16z] {
ZP3LWLr134DbY-Qc_uAp3tyMpp2O11pYnXeaNkYSuWj8l1dVxKvknjp3MGA4XIr0q0jQwy5AcDiOM1nA0D81CfajpQxKsKIs-GZMlNXwN-AX8yMyzc85D8Tp
FRzl859cbJpiux2GK1heHf4BX0LpC-6_H5C5UxCNJj7zu0oee2_x0wOxVSH_seD7jqLqCpK94ziIQZrD7gfwJpjiJ8xKDLQ0p-9lhF52IN1dRkj_
}

EntityColoring(active_campaign)
!define active_campaign(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, active_campaign, active_campaign)
!define active_campaign(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, active_campaign, active_campaign)
!define active_campaignParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, active_campaign, active_campaign)
!define active_campaignParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, active_campaign, active_campaign)
