sprite $adonisjs [64x20/16z] {
lPG5ZWKn3CN2YUV-1rwrNMP-7nAbikf14T6eOMSwLBwQ6BYkw_QF-2hEi-INSBsZp98J_Vhsv9F-UJAUJ-nkqe_tdDttIqUUZy1FCnT0YQZT2SmB_kKeIa_3
vaqaMqGVosXiRSrqvjGrz5ZLNSJMXElMU6FvmDlsEeKvjSLPIHbqjyMAR_Ky0jVXerm7BSgIaI6qSMSi66cq2SsyE-0vfUvvpUd11nLbRAqwvPJeuHCwb0j2
ZbSSwyCtLRp3cqJ3B7xjsrNTn-FmQznOanhRtvVn8pvI5UQwPjdARHfcDmK3PkmSmPR38uC63DtFRjY1FbrKHgfObcV8gllVz-suLhmg981M4NKt4IqWl_xy
pEp_PiN-x_bzU7_0_lyo_jFtrmq
}

EntityColoring(adonisjs)
!define adonisjs(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, adonisjs, adonisjs)
!define adonisjs(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, adonisjs, adonisjs)
!define adonisjsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, adonisjs, adonisjs)
!define adonisjsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, adonisjs, adonisjs)
