sprite $adroll [64x12/16z] {
NP470aCX24DTH87S_xnL-7Qbk_02nhBL191UhZffvUkNbiKZa_8hQ403c7FYNLMI7xT9hNo4RxRLR1lOC3u6ZLlhZryYucGjZzfcFpn4Za5BPpgoioqphE3b
D9v-KRTPFtmOx8-6ku1p9j2SeSk3x9c4j_h5btWN02MdjB9eaGF6JDxDZ3IGQu3Kp_ohookjXadDlDOdF-zApKN6Ft_tFxtkJiwdZE1rylWwaHSibwz3Zd3p
0nzvorFV_CxGOd4nyZLVaBhtPxIn1LAKFXhU-HczWaGR7kUNj9qfO9HSRPJqqSwl_AEqYZv1x3hdVYqyaXROTAlb2EwrHuElwZwYvhskOxXp6KxRBty1
}

EntityColoring(adroll)
!define adroll(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, adroll, adroll)
!define adroll(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, adroll, adroll)
!define adrollParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, adroll, adroll)
!define adrollParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, adroll, adroll)
