sprite $aerospike_icon [64x64/16z] {
xPKtTa0X30G57oNV_xwEF2ndCvK3qq-n2vBo5t4u7AnRShIBO3-qYM0_XZoXnFPB9jr9QJAvWArjocq4YBriPR4dXc8lMjo0lp9ZDv66_ieztJ9tVH_rlQOF
IXltzgvlAxP6vhCFOkUc7wELsBk-N_MRxlkZJ1ZmQtNTa5ypAF7lYL5Qg3xukfSJ_nujHH2__a95VgroEF7hTnJatwDj-P6lmEF8YmXwkZuz7tmle3zb2R7E
_LNbyd6LYiH515OhXyFX3W
}

EntityColoring(aerospike_icon)
!define aerospike_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aerospike_icon, aerospike_icon)
!define aerospike_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aerospike_icon, aerospike_icon)
!define aerospike_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aerospike_icon, aerospike_icon)
!define aerospike_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aerospike_icon, aerospike_icon)
