sprite $aerospike [64x11/16z] {
tOz5baG120FV-oIGkl-1HnXftRVK1fVm7iGmaY2I0lZFz5OCQUZWWAJXnEWOSAzlHg1UOnFeniscOqC49t9e4rrxgzeD1IXa3xNdoup1LUo4l-2NiOh_--hV
MGeW5ReyxBnyUn-81IqRfkbzurVvLWOW1WSDANku8GdBcicw0_SxduDF
}

EntityColoring(aerospike)
!define aerospike(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aerospike, aerospike)
!define aerospike(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aerospike, aerospike)
!define aerospikeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aerospike, aerospike)
!define aerospikeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aerospike, aerospike)
