sprite $airbnb [59x64/16z] {
bPTH3cCX24MBACp-LponDwcyEI7pzAiMBmS0JVlfbdbaPipnkLqpyyzUcSkkX1OIIZokbDAaq3TQAMEwhwyuNyUySWk7DlExUQaStyC_aE_jV1bkFaDSsh-1
Wl8IA-WpDoUsXpgyDLWS4_GMwuAoqJblCYNs7Yhi-jy82dg99PJOUoYnjEk6tMC99VOUIYoDX1BRGw-nX9gx3-kmVKzjfTOQcEH-Ukiph8SOsFwUMgHK-No8
4rX08uMRAnwFwInOGF6Osjx89x24MjOk2ENbSmkjOT4hiOeHFIXkZLXwCzH2KtQC3kY1PEAHz7Coeu6sKc1H6AL6QGqm07sHgymv0DKw8S4NijK8L9ksPUgZ
zafONWZkGwwuv-rN4KdXY7WneOZO5PRuqGwqDfFlYJ4UtbrU5dbxnaEI4wfkHga9PdgePFGiaJlVZAfOFyzmlKx_4L8kXKkplWzuBTMPvKrZL4ggCvPmKUF-
DwlBgkfYWOfIb66XjEHARAqHkwCAzm7tngXz9JCRhM8jWmQbDrhnrFo1YL3bHvPVv7pBT0f_LVITjEamfsshOZkMgUEZkedZsykWJ1ddzcDZRKi9qjJV31_s
CNEvcYMpRTN23CtCpgoCpieIdimXUygkr6j-HoWBnRBd_BVWhfowVvqsG_OZ_0i
}

EntityColoring(airbnb)
!define airbnb(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, airbnb, airbnb)
!define airbnb(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, airbnb, airbnb)
!define airbnbParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, airbnb, airbnb)
!define airbnbParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, airbnb, airbnb)
