sprite $airflow [64x64/16z] {
fPO5hiD030MpQ2_c_gSjoP8BVcbW1FyN9dKcjCjP_7897oxfBePh-ZK_NlE3-faDAFbjNNtVLvDH8amVrNzGLi0W1zg9Bz2Ac0nqyOKuLqJtHdhnbJ1Mn0X6
E_4Lr_0-95DN7rSKw2EzuKj5IDLssD-kA3hmTrQCmDzPCG1_PqNLaRzTiQKFFucnl-B8KI5QR4B74KZraXT0NZ5PPgTI4j33_EidBgK4MtTZGn-lXFcfixFz
jcx0Cli3aAziwLr-_4d2XnzFBpOSFstfFJzj8HzEtrdjmlvW-bdBEtGi_MWVDfFRdtws-YapPx__j1s5Y1-8olGWB0R3haQ_n0DNJVlLxJEd0v-_zMpg0SKh
txepVKO7hlAdxXUJZlol0OAjUtJIjbOPfbSYzbk5wHNQy7iZeJGFV8Od_eCf6-2vpdZGhmz_o5aqdWSqx_5dbNzcU_9yWqaE4U_mqvBV_V7wTnMg--UJFiVQ
2x2c0dvvMrXs7K2PSSllyfwhpu36058H-CEzlIi1chHJ6FapVDuKUZFsG2fQVlfQ3SW0JVA3YgpfF_6z2MeQ5LdJV-6eQW9OaJNz3pxNAXk05LdJ6xZ8jRPg
RA29mP8Uua8Yhls78hwaFmjB-Wj-MIxvVRda3tVDZsVDEm
}

EntityColoring(airflow)
!define airflow(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, airflow, airflow)
!define airflow(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, airflow, airflow)
!define airflowParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, airflow, airflow)
!define airflowParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, airflow, airflow)
