sprite $airtable [64x54/16z] {
fTG72WCn44FHTI-v_tdJpF83DWEQc4vuahBjCaw8AUSKm-Kw8QNyFIav4kBITqBKgczDWZ0Y_69v1DMdX21Mxn51g5R-HjYqDK8Tle-GXjlN4gr5XDjdftVF
vn9m-VoQswTVkr1oO4JIgcEERSvPutc4NHroVPynvcFENWuZxEfIw_BlWCSxegNzQRAhRp_cdDk8NVFZgiQl_s2C-AcEgnfFm3uYBNoknXEmZp2gyGIi4QCS
Nd3CqO-bjn7SBTEJm8ZjRXcU_q14-tA6stuF65zV1FyEe7vasNCVkGUQ7xTUMF0ahELUtpjQzvq7H_Dej-yrmZIFrZtQxVbggBwZNRvqjCTV0Uto78VFuGzV
ag4CJxNRbsWRsoUgTP-frdsXMlHKwvvgjyzWzKJpGNa1
}

EntityColoring(airtable)
!define airtable(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, airtable, airtable)
!define airtable(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, airtable, airtable)
!define airtableParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, airtable, airtable)
!define airtableParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, airtable, airtable)
