sprite $akamai [64x26/16z] {
fLG7hkKW4CCDsFjVU1cI_5vUthVAW2CNf57Q2QYFuVOaa3cdsxFGKcUDFkOOqLtv4UvvOV2sNAqVqeMRJ_4kNwf-DcUc7fQZKYkzMikni4ZVQwyL3kHitz5k
nSysLWMO1-C-VU_rouHlINOzgkz7_NoW-QY-tejK_7EO_qe_tYHJAZVmTq-8Xxw_SaxYDMN_gfSz5w2yKYbi7_sUR_Mb9rxrYRNrCHk9UaUDEkzhdTihTsml
NkCD9MXm6ct06tMs4xjyNTWJn_fUGEBjiRKncwJ618gfH4m42KW8vro0r_YmiVHEAg61ek9M5zhdkqJ6KDtvfW2sAhjY4cCp-rGNsTKGTkAasJets5VyYpwX
erRHpT6kQgiwCC7-4FDQOPxn1i14TCgjugMhwjb1nMrFexqrq4705ksQfEEYPTMzEd2RxkbtFy0_WEV_vtdGOmxTr_q7
}

EntityColoring(akamai)
!define akamai(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, akamai, akamai)
!define akamai(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, akamai, akamai)
!define akamaiParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, akamai, akamai)
!define akamaiParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, akamai, akamai)
