sprite $akka [64x46/16z] {
dPI76WCX28DT45JU_tbRkczm7_Nlk1cCSQGebG5kEQrXQe60rmeq29vmMe3mfQH_oOmVAFr9WR5ieC9ODj1me2majsOW4yue2y4l62WcNpTG8N2WMF0-EHIy
3yMIyycXv7meaDogWOO054XknK0cnA1uy7431N7QMV3No1FFGBlKzZ7cap6wc85uy7ANgZ7Vno50ZYKdtKHpWrL0YoGduoa-e1FEb0se3PtjEZbphjD7HxwM
3zLvXSAPie763PtP3LusQW_ov3qarvx8xNa0dSMHpnZQdAv7OV7akgcYga5zVxrhYuof6SIm5NGs5UaWDwbmBMb7hjpDrNO6raDqGYLv51xRNY5Z0zUShg5D
XPes1ceAm9y2shVRJaaXId-FK7sjFX41AASec7hdlVvpOsPBBKwLESLQlm4
}

EntityColoring(akka)
!define akka(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, akka, akka)
!define akka(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, akka, akka)
!define akkaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, akka, akka)
!define akkaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, akka, akka)
