sprite $alpinejs [64x10/16z] {
ZOu5jXWn30Fb61B7klzvstYX-64MWgCd0A6ua84Ri_ERk0ag_cANl8UbbsusRfrqOF6vulcFl_BLoTBMtU-0HMRx4hv2e5CG7ii0NRFl-0GYrrXih7LtwoHc
KewlP36xVx5uDhAg-nF1tDlv19ZvNS3fJh_yYQIqNp8v9cVot4d2k6F0tW2rkt-UTVxjRyJnmqF2ZoysMNW376fozC6jkYdj_sIX_Jh3uAwjf6JtFpuq3piL
WlPT0NLHXpAdzmBkFOmv1Mv80hvYu5EKyV_zgC8tq7By3-SJ_0C
}

EntityColoring(alpinejs)
!define alpinejs(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, alpinejs, alpinejs)
!define alpinejs(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, alpinejs, alpinejs)
!define alpinejsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, alpinejs, alpinejs)
!define alpinejsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, alpinejs, alpinejs)
