sprite $amazon_connect [64x59/16z] {
bPO9SdGf38FneY_tF_5iJU6YCM5-PNSXMS_e4SOli4W-K8QDFuD_k59A0Y3zVvCj0OLLnK90LLviUMD9a6zwGDfTEHxDXOhTUP3ztlm-flUABFKh_2wGv7Z3
H3pf5YbGl-czG19R06PmiXKuTQDMHgNDHRFMm8wI-YawH2EWmv9jHfvke_cxf7ljUmtzijZ8yQYPdVL2OiFSZbg3wCh61saN0mNHLpCyzhrCFZe-OJM86mnA
m8bFcYSKNtnBo4FWU-Q-yDqVfFgpcbudkFC3dzykONAyE_hsITOJV0m6bMVoFFhSDdlBhmFuF8hLpZgszyRq8tTOgNO7cmknSwyThRCZXaFEbikC4TlIf4kE
yy6_xdFnQnZrkWNTpe2DPHKTcr7r83KHA_X6h7wBObGOwda2LVR4QFW3K0Ju7aR7l_oBIaZDSe2WDkRAhuusfrU3Idnq_AHzyIqoDbT6T2TAMRwV1tdoQ_xm
EYM7hzmjrBQGzpEzLW9-gbPY7lzPpVtKLBrW2pOS55xuafbOxpZygx6WwRPWHNSAyWhQrlzVs49I_43xicc_HmMYwEr9z-RVwNieFLh-_LfZwAPM_9RUfmrT
-6hfJZuAarztfKTMapZvrj3lDmh_vj_f_gu6JbKQgu-BPN2bv-WXOkFRlSlx0kson_MvGL3g3UnvGpU1tzd4UC61i9OzcxyGW7O9JrxiOpbIHaIaE0JVi13y
_0E0z9xyDm
}

EntityColoring(amazon_connect)
!define amazon_connect(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, amazon_connect, amazon_connect)
!define amazon_connect(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, amazon_connect, amazon_connect)
!define amazon_connectParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, amazon_connect, amazon_connect)
!define amazon_connectParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, amazon_connect, amazon_connect)
