sprite $ampersand [55x64/16z] {
dTQ7jZKH38PXNRZ_-_shCUytZNMiTif-X4ZOxZfYgTPQivgZsnq-DmpBVakbrdiJk1Enzg4moe_KsXKeZlofOYVZY5_CeCmCpFQ2PNyvYhYH3mlZBw7rmUex
QmSBNC1mhyeF9ZFRmS8R2tsmh4UoOF6JnIKhJDD-D6EQm1OfmO8oChau08IBCrZPAUGoUmyPMPv0QsciyFZTDaivEb_xoS8NY-rqoQ3IVdD3hRhR8zo-qcNE
tbiXpLxRKJmykhIbc7Rs-NflP5lA5o8s-dwetUHdeFsKL5NzvORq-KFnVlPwG3AFvZsnoemgIveoLGtE1RXAnMN7eL1DIVuoHjBmqbjSWAOpwg_fL1PqkwoM
q3HB1lLyHvXtpjligF9_bicedDUqrAbwqJIczwOjKAQRC5MQpbEDhJK6qr4UM0jEMNYkL5Lpylx1l8dhlMUtPgWo9d4iShZqykmX6EhJ1djfvVBojQOCfgsb
vQjDov9y3fTXT6RVfeklAqJJFhIskb0FXIfZigPBZmjaaUN7-wU6iVHaK7IHPug7kgIKwwMaAboGP6hvgGhQj3mxEbNchqqBHqZKgnyxUKXBxe1KypE95p2l
W3aGoi9ZqmOyRu2y8dbGntpc-PoOk9gkJxJDeVKRSct_aDNq_GJ_1W
}

EntityColoring(ampersand)
!define ampersand(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, ampersand, ampersand)
!define ampersand(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, ampersand, ampersand)
!define ampersandParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, ampersand, ampersand)
!define ampersandParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, ampersand, ampersand)
