sprite $amplication [64x13/16z] {
fSo50GH13090Oi3rN_2xkx0k4m19GapycB49BUvV-RBpFnP8BmU_E7xmNCv-y2pnzEYpN_GOzvGkZyZp4Skjpwv2LKTsRDV2C1hH1LHNbcTtREn--SQdAOT5
auOyhfbIUDJjCSkJ3f4Aa-QDRo4SJkow2iEjRm5GemKZN0PS3ZXzxSlHFli9pTQNeueCAfpfT9Ppwp6-yg2fK63NjKdq935IXiJ1A8MMQlS569_zRLHud-8V
VWq
}

EntityColoring(amplication)
!define amplication(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, amplication, amplication)
!define amplication(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, amplication, amplication)
!define amplicationParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, amplication, amplication)
!define amplicationParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, amplication, amplication)
