sprite $amplitude_icon [64x64/16z] {
bPU9qkiW28NHk0E-_-FUFzuPQoX4-ytI9H4Fe2S635p85ObxPyAMeuTVyAbnVy2OBpWapi4YH7Am9r4tuRoB4AY_mWbUS9Nx3hpE9lzTGk9-HW6DqezfxcGu
sthGROTZS2wpgK3ctWKLRe8Pe3uhpqRyt2tosdUIgS_zWjs00qng5zmjzYs-Pa3EL4zZvlztjFqo86NwKT4Xe4jaaabJDeAYYAxtW3HXSSnmcIsObo6gkd0s
oRDT0Qr3G_N5yokWBS3DyA9wPL6OkabKqcC_Qx9De04qI_vP0ewrXLqUOd8t2K5j2YuP3ZKMvIisFMjQnVOIODMS8OcjqBe5JQNS_a34Mt2X6sOY9Z-SbIqx
eoLjWHl0ZVVN7o74b78kjNqIOisJzrJBpmxvRbjQvBe5-S_0juV-0TDDkBlFj9161vbMMDHlmlvhkRHN4y5lvykA6zKr8Ay_lik8Yb77PSGgXiLaMMnNPG_7
zGOKxXKKktYwABlrXk9Pbg-fXb8_6TQ70Q4ed-CkIMi10j0ZT15Ie-fICop18ttHRGuULPkTQHL8ehIuFtF4cG1V8z36tUm441m__bSBfdQW32MF-WJxuAKl
8LpQEtuT2XWk60ZzY29F8AblIOhnDB0EEVPX9R1oHh8V478oJqBIUGRDWuja6MRjMvZuvGJR-a-GXoSE-p7wq-O71NJfpvH3q8DAvdv2TOSlGB-_WRcT1AuU
Nl6Lkmq6s78L8mAt04SuvGsOCNaunuNIw3EsH6lmFm
}

EntityColoring(amplitude_icon)
!define amplitude_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, amplitude_icon, amplitude_icon)
!define amplitude_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, amplitude_icon, amplitude_icon)
!define amplitude_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, amplitude_icon, amplitude_icon)
!define amplitude_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, amplitude_icon, amplitude_icon)
