sprite $android_icon [54x64/16z] {
xPK5ZaCn30MV_QRtF_AY5Idz4BVBCAA09mnw5w9PE4DgGw85mMvBA-nD2LeIX1HfWvqXYT0Qsm2NPm3RQk0o2cXOMSeaPbEQmJsfhvM4PyES3p9UwaikIEcb
E7G0Bs5b5yGetwU2dSmBwDE5fCA6DESviauXrglUtMklBEzQbmNx5WjcAzAX9k6CMWN0dRug9iVUukMye9QP60lEUZKGOp5zitNvCElV-hV-BTnw0Ggg1x9U
Jr374epNDErKowhOGSygti7YddS-xlg_b73YaDedqdP5ONkCsNQ6pg2arzwdPVY-rh-LjraUF_OucjOQgAwgCr27j4D5sAdtuX4
}

EntityColoring(android_icon)
!define android_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, android_icon, android_icon)
!define android_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, android_icon, android_icon)
!define android_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, android_icon, android_icon)
!define android_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, android_icon, android_icon)
