sprite $angellist [44x64/16z] {
ZLQ9sXmX25iFT3nv_xTjpMgcx6pRdrvJ3H22yFslsrBNcLu_ighByfURKDiL_Zp8gZfLDJwWwH5agYOdgkCJ6XVI10cgzHtzib0tLMiUgktstbc6JcUm1TvU
SKui0YO6Phw-_ksgtd10IXkuRQA3M636aIwRmZgkoM4d2VjscB2o_XNui8OJR-AQpCQvBOGkptQEcn5XqsNxmKZTqTxVsWR4vna9fnFZOj_x_h3zp2VtnOj-
QkXMTRO62QF971HSdYJmKNTbtMQYNOT4HWPKbhvGC2czGcAn5AmDbe8CbSM22ysUfKN2JIkYDUPQC17gyg1W0ZJLshOQb8DcjH65YIdZEORYHOAV2pfvw0an
m_n68UoGXQbF2ZvbSKK_RFP2BhGySGD0hxMsFYOzgZWpsJH6SJxcEXGsabbGJFl9hU6udFyZiqWZrfW3mKHTjJbyV1V8DSxy-lBaNHzG3gVjOb_KtDUMrjqQ
ieoWNCGIGTS7CyGFzKOhEISHYNniDiD-ZzRwaGhnsyGJfLyhdHvR03SNDdI5DRCnNOZrZIoW3cnW125ZVAPrCRAxgK6aoyT1iLSP3HuwirbtSGTqc5rgZDVP
WzbAMey2xfxMfDfsryt8K5aG5yPGxHjA_p51amCPRub9W1iStOsHpotx_PelmhXUKNxPiJjoTpR0bXQnvPkMhHQCOItTLrllifwgAh7-GQ6ybwwSKY8uLBkQ
kTBmztARmYtjbx-nzdvjOpK3EwdbyixkpQRPQieMAY8vHzvDZWbRse_mmxtYsDYCNAOJbPr92YzNxfLnSHkmHRSRQl7fod1Vz9lPIOrq-kEbo4tuifT-SHtH
2BgJkhgX5gmOB6i9MhhFVOKn3EOmTLPhB2jib1JzRmkIsyI1VFsXKPysB-Qt5igqo9uCqfeJBfnHqwFKNm
}

EntityColoring(angellist)
!define angellist(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, angellist, angellist)
!define angellist(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, angellist, angellist)
!define angellistParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, angellist, angellist)
!define angellistParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, angellist, angellist)
