sprite $ansible [52x64/16z] {
vPLdmlCe38G7qLLy_-FkGdWRbaF-VqywC55XZ74dfCgYPghSCk5Co6pNBqpgGKRDhXl6wKsCeN3X29-iroFM0XpQzHOXx0Iv3jXU5UbrnFBVA8xa54ckZx3u
ldpE_Jwe0OliI1G0tuVxks8gWEICf-VCR2QXVdo0x7hAeJepvN7_8mR1_4312oC0Xgpx5UNB8GCG0gAVTd_eG9gj4s_IRNG3m3FpuYNdHJTwTJFxrJRlZtYr
cVskoaDde3_nTepz7SW_TJaBVAlLRnjdH-DRROcoQpfzidkovOVgQ3ohZL0auyBqki2UrP9EOHzTS9pIFQ_pEcFASj5Vh3WTcDdKLr7bRZf9TwkjgliigjrD
ruFTh0RTJjjjJGRVh9PkPs3RiYytg_4VImpYxq2y1TRzJEa10zwkuRvRpRc5vEqeZVRNQkeSx6bFzoUG456vTaeW-HDcAy35R3iIjpqxmC22FvKO7MvpXnlT
eQIz66Udpv8bEgPd1Jl4nreSwhlycE0I7qDfnYE9pLEKW7V4fdzbrXFEnD95RI1SKy37X07-5I9Xa04a6jMNMYC0IlD7ARIc9wdM0WXZe0sOMy4jbx6YzB5K
IfKmfWC6HNAk87vPIJGlJSMajA5fW8oeyjAq-dhFyvEZqjI4Blb7erq4Fvfet6CGhcimoR99vFQjwKIj_cXw8HeptV9hiDhGK43ILSzu2ss89KvRS0O2Hs0E
SW363tHHoQiK91NXkLX54X3bV_u3
}

EntityColoring(ansible)
!define ansible(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, ansible, ansible)
!define ansible(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, ansible, ansible)
!define ansibleParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, ansible, ansible)
!define ansibleParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, ansible, ansible)
