sprite $ant_design [64x64/16z] {
fTG7ZiGm34DHkahE_U-xRGf7G6GaNA8RU7zA2dOhmtrMg2lclwlGEGCIPq3Y3CYS0PsRkLMPssDLuzEUc_K6Nqzj1OC1XGCC5877WCA1CHcum1yZPs3Eed2W
p-UQn1der_WYZu6cS0Q6p84sHjSvLshz3n_kFelCEs-jmFqQntG610xp6DZpsdkB9yCPs77-rlXl5MDWpyjydhktD91ppFMUrpoGV_d56P90ol79bxVJm8-P
2Q_1hvcydz_S8qUFtf04D0_UxSdtRxllZ-5lvUU14dq_vzvGyylFUSauGY3x0ZtbUQ0nC5A-2rHxd7jF-Jw0DincZqU1Pu5yannAmCYJW6y3dLmBJ78jqCOe
mFt026_2sm5BmrnTHnOmtiXAmC9pl0qy5WFsEXsu6ZYy1Fxm1KA0l06t0WAF0O77WC0_0yi_kH0GE0CoPu1S2f1B0N8fG2u6oBM07OTNxFOD
}

EntityColoring(ant_design)
!define ant_design(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, ant_design, ant_design)
!define ant_design(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, ant_design, ant_design)
!define ant_designParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, ant_design, ant_design)
!define ant_designParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, ant_design, ant_design)
