sprite $apache_camel [64x64/16z] {
fPG9SiCW34MruWNkVzxMDFETiK7MkAzxawSlYGIQmQ9cVc2gGZdWcbymvQpz9vTVkedVJB8sr2_wl_Inysv3kbU8Ur3Oqmh6GJZieCAq1Od3iSp95XJsOmkM
qlC5eByk8D0pt7R0qDC5vDltClDLPmKuCxmGyTWlbXc-3_Uq0YkXJtnWamdYtJC1KJlvFiH0TmdVAepu0jpBkgAWqGJ61hwdxtPjRST_A2pm-GcwVR3tbZ3_
2FFYqjk7xSjXTshnME-YzVOHlhUJYfiY7i0lhOEzhoVETs6_XeCj2XVhegh_wGW_yOcfvWVTC-jssTgDVUH-LE27ZxN7yMnGJnIzNwWyk9xl4FlMHfJ1SOry
uhLbuctc4vL1_ylWj6S-MRt5oyNt4lWa-yFq4ll4QmtFtahWTxm6tVCitWamNaMxPEBX0obRhVkA_ytZWT85fW4wzOKoJFKoZCl7-p_ZDQFBLFTK-sMQRobz
dVak2Pthvl-9NnhyD_5QuR-AtrfR_Vtob_hhl-iU5zCor3FTow7NiP_HztRuhuQ7tlRtUcTxf-DEN_Fww3AiBpRFldzqZ9y-Tr5VAsoqZt1-QXpolNr7U82W
mcNxRh1ZsCu95jZAb8UrR3ksvoOp-GS
}

EntityColoring(apache_camel)
!define apache_camel(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, apache_camel, apache_camel)
!define apache_camel(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, apache_camel, apache_camel)
!define apache_camelParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, apache_camel, apache_camel)
!define apache_camelParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, apache_camel, apache_camel)
