sprite $apache_cloudstack [64x52/16z] {
bPOBigim34EnP4diVyMF371_9S0x_RS-OplZX2vlGTlkMfufwYEqbAphck1HLmxu8tc6ksxFVj8xIGDqKZzqDwbir8CFgOuwUZbmX059Otb9nSURZd3Yzxvz
zXD--yjhFnhjkBK6O0CWOTPBluFnB0oVba1rIyR_j0yXQuXnsv-wpmZYTWoub-5a5JQQ142VFi2vpj5zeROd_VBXEaCWSUOxO-raRd4n80sP3VhKiQ5f-buM
xz4L0LhZ3T8yknz-Jxkl1G8mXh4z_0sZJtqftUMtbztl4Uz6RthOgiEcGw1dVZIA8C0UqIRQuXbEELriyNRsIdti5xW1KFj49FSpX5RsENLu71wnjEde9Aex
cyvnmu9OhVta2DbE7ZP03UzO8QiOEpzu6dxyFE4Orr5-xuNZSTEaVXTJuyjL01CkJpZrfnmlyD3HBtHyn7IS31toyeZr-TNg7lgRWxCkOXXY82sFj2ydSK__
cBpgiiNuHVNLpk1YjkoXzzCrIxsFvqUWqefkTKS41bJyuQ-hYjADthjT6_qd5tB2YTwxVdRE_jFPkODwDdCQ-dA9pisepDR0dklzdHIEhjFtLCTFfQvNe4EW
veVuDuolOeof_qTmSBNbfkLNT7L5VU__cLgc9_waVjRKd_S_fuF9-kELxrmkKhyi0DSJh63ZxT-vwG5L3tOfUDX_KnKOEcS1YZ2ekZ1tQgcR0Zicvfpg72JM
1YVkCtJoiufwA_u3
}

EntityColoring(apache_cloudstack)
!define apache_cloudstack(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, apache_cloudstack, apache_cloudstack)
!define apache_cloudstack(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, apache_cloudstack, apache_cloudstack)
!define apache_cloudstackParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, apache_cloudstack, apache_cloudstack)
!define apache_cloudstackParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, apache_cloudstack, apache_cloudstack)
