sprite $apache [32x64/16z] {
pP9NqfWX30C1svBX_WVEHqd5aEJlUjrP8HZICLbDqmKR0BrZGEuOTk26bHE-SdNUU75tKnk9jl7X0FWayl5WqdieEvOEu9FdlNtWfTkX_QIlTgEpnqxR9mvq
J7t63jknUDh2-ejUWdT_k2rTWglNMgaJcsthh7E3zz0HwgxkXwT7NVh8jhvCdKVTVz6fyUbBfqaqtc5BPmdry-dZMZ0UJay3wCAm_N93uyg-RkWW3n_3UuGh
SRtPKRURljP3Zth-TLrmUVcr7ccB_ReknzzMJhysfrJRzxV3RekbrgfYJfEyj_FXGa9pHh2kjDPejPBUF0NnrhIs7kQ8QwlQQJKDg8WsOEXL0fxvlTvBX8rU
jRf3KfIIaq0iNVAOcY_SqpM2EqUvStxfUfDNrHVSEUJEaUxv1W
}

EntityColoring(apache)
!define apache(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, apache, apache)
!define apache(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, apache, apache)
!define apacheParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, apache, apache)
!define apacheParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, apache, apache)
