sprite $appbaseio_icon [64x64/16z] {
dLS9TkmW31kM62_I_O_xVzlCJe39g7k9Z2tpB78P81LH3v08jrRpvGoo6400Y0W01BoLJzcRWmYJMj8VSXKD42xf4tOGqM-MnK6qLOGQXDNZjQ8WPCPE2jga
pgoWZzTBCEeyl-B4DgeSrBL20khXGaCNUPIbfGCwyM67izFJd3v7SbfNUqUV1dZJe7JqEL9GNlzSIpVPKAcNazWOTmqhzjzFmTXklmRhvJGoa6-fsEKBj5lH
WV8DFmNoTFjSorGMsHDmr4Es0OXjbW2GVdM8mGdv1MRAAhVVBDgnEZjYmg_ugToFrNFkG9ugc1AETmXUCLF0K2jiSBns849h6dQW2MLGsyxNB1RXybka-Dje
Bd0TAImWkK-gL9f7g7VzI8XUlaVmi4VnQTihyZUL0iCp5kKjNjzF9uRy72yhTU-elV4P8twD5zz04v2Htxeqvei_s0Rz8MRPqdkNSSpFfPZUVhUmmIdqO_sg
0pUdp1fZItKwyg3r9EII6dmoNOA6EZfw93IypYT0e_H1xrWuQe5NQFVF9tvPc83suqVuG9TSFu0S-Mj-_70x0Ufp_dLH_lxj1UcPd-OE8aVsqHxyjaf_ju71
xA8jrBSzN-J-6lW3J7T_64_htJ-BgkJL3S3lOxnyPP_rtd4_pszFwZZbBBqygvPngeB-nYMCV8flRvehFSqPYyVjJ03jqqt-UG0zSlLaZ868_ODv47RxwFhl
UMYvbXURDr3J93OaBLxkjaNu64ROd5Wbc1N4qOsbj20wDnX5W4cvnqXbqq3tOZb4sWmW4EvcxW6GS3bpmbDj7hm2hjk8_1y
}

EntityColoring(appbaseio_icon)
!define appbaseio_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, appbaseio_icon, appbaseio_icon)
!define appbaseio_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, appbaseio_icon, appbaseio_icon)
!define appbaseio_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, appbaseio_icon, appbaseio_icon)
!define appbaseio_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, appbaseio_icon, appbaseio_icon)
