sprite $appbaseio [64x13/16z] {
dP87gfrX20L7FKV_L_Q_tg2yIqbF1h31y5MWsdQB_yIwL1ty2_7IypLeVaOdFyKS9LwaBbPiJBvYA-CrZYilyDNUekyFYtVSVWgt1yPk-l7enfaZazT3awsk
TNXxoWEwHKFDDYf3PnVCBcQhWKcOytlZhMbo_KgewPbeI4lWMhzJqzDuYgVRpvgngWpnyTctilAMYlDBqfhUzNCWR_MOv6ZMzwxq-McM6xX6yIPDw4wLJwbf
rrIDXis5QCefLO5E9o_9HJvIe9Pkh1idb0DI2fBSAd_-_ZaR9Vu6ru__Bou4VuNQ-k___mq
}

EntityColoring(appbaseio)
!define appbaseio(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, appbaseio, appbaseio)
!define appbaseio(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, appbaseio, appbaseio)
!define appbaseioParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, appbaseio, appbaseio)
!define appbaseioParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, appbaseio, appbaseio)
