sprite $appcode [64x64/16z] {
fTS5OiKm281X8118zVwtNHFgjhxsdyiNdS8_8Gd3sp28H5DyPOa77AEPoOk9CywfsQyB89Q2dUVavrLlk2azcpZun6lknLydNhWNxh5FVCrDh_4uyINt-8e7
npVyVW6uU5sAcdO9pi6csMlNtzNDXVCDQFymtdZywE6h3xBucyrVUZpwo2pzN1C94KcgSm-yzmqCLVDWCCNjgG-ozIxuP3RipZpkV8UGQvQnC6ea0B0-5s0N
Rxr1AVP3DGn9cJQ1z2Kbt7gIZIU0mEDYURMJjlSgCvM0iBJnLJwyF6yQjzBqI-vJIcOQcS3ZjVUf2O3y9gW_Ui_CbWsuTw9-27NPVZZrdeAtyZ73hil3yFNy
deNL1dIvlEcxlEtAysk_lW7t1gkqt7KSNNVm0cCOTVIqzjWb638_69ATDm8FHOUcoujrAPOhB3laL5VvJTbwXR7CtJC0ZEjiozct24lOhhtnYhjlV1AFonKs
OUQXy3vD7bVSlH9HC_cQYF8xZLodtalgFZfdzQo_hAthskTsRtxv2tV_8FTgsI_ybHVdhxpQUFdwqcjI-EIDltd5ZpvyzF6rhxJ4sTjSyQrjIXVU0MwyPL_3
9knklCd_lh_pIWVVrPkQMsznvnzMsPY6RzvqxTFltlYRrsYhgeSbjneZexqeqvmmm3lgF030A-gSOEWDTOwGUqDpxFpEnviOnjAXGYNWz4-H7B2Vd7T5lVCn
X63EbhRqQemjX_5T70WV_aih2AiM-Y0A4WKs_G4
}

EntityColoring(appcode)
!define appcode(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, appcode, appcode)
!define appcode(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, appcode, appcode)
!define appcodeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, appcode, appcode)
!define appcodeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, appcode, appcode)
