sprite $appdynamics [64x64/16z] {
xPK5RW0n40FjBFJ_BouUyvvLOKOS6eS__ejEfsEczGTIwUw0A_q9KDC3Bka1Qdh01RqI830GaXxWMxqKeCtzgUc1aFH0AtTFh0X93pHD3wIa1rfLBmKm390O
i3TwcuT2blNytRLWCS2evs1C5WFOvin4BK3kdXql1V3zXhVAGyPPjebKqCVHRVR7UZjSKpxLysHOVwZFarsXy6N5RO1HR-V7YW_ql1hRx_LvUJ1lzLwhtWhQ
tREMbnUFUJS_kyXdbZTtqsoSGAVJ-G8
}

EntityColoring(appdynamics)
!define appdynamics(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, appdynamics, appdynamics)
!define appdynamics(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, appdynamics, appdynamics)
!define appdynamicsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, appdynamics, appdynamics)
!define appdynamicsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, appdynamics, appdynamics)
