sprite $appium [64x64/16z] {
dTU74kCw20NGYnfm-V_lVMztdOd6Zb7adAafI1Yh8Y6rgpiZIBVH14-KRemJ-YZOr8nnWzvb9zeZnI5OgnvBx5WGvIgMT7ULdpgdDW7aBoGwqs2hGEdg_Ci7
xep8U0MwCzvC7eHp08rnOh8VtY4QLxRzx0tYyKdFbK_3EyIJ7oRnI2XWSOiLRne9IbuOdzb7fYsUB0PUVD65HuhbLVl8LBHOq0VTvmdaNVHPcKK2jYY-nX85
A8o40Oor1lHr-cksIh_CjZCKOIGu5zDSpLEqEJ5petyRdZ8OETD5-LwAHOgL-U1zMwIGrxzihI-jCXzRasJTkEXEVBx6367s-hSQOAdh-7K334VVYAzotu17
ACQtUD5mkLrDB286EbVnnyykDtETunYgrRFwpqdaDskL7z-ee3bFuVRAlFjgCr4vejY0Eeo7zu6jd4Tk-tY21dzd0W0YHIG_nGaqtv-ehU0WfQapFkWb0RjC
3TBDp4ccQvfVvxZ70uf-VKSz7Y0ABqkSC1weu7M96V70W9-wVvg0mIuda6SLSDZd4SgU5D0-5wZ27-8RfluWVv_PJngRJ7WvVJqhmQX7kE1CDXkeOvvyVcY0
uX7X1JTqDtsN_0Aonc8HAh_UlcAqOCF2uBfxLy5IKKQgrOglIfO31_R8pGsOrWNxf8xP1brR5lm_
}

EntityColoring(appium)
!define appium(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, appium, appium)
!define appium(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, appium, appium)
!define appiumParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, appium, appium)
!define appiumParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, appium, appium)
