sprite $appsignal_icon [64x47/16z] {
dLO7ZiCm38j7hEN_l_VGA4UODzn1h48GRKgYrHmRbE5pXhRZCvmn4re-eOy9-0S7zBd0tgQNItoe-7nWlClNItVzhYFUhA0k97dybW-kxqSYtXA0wXs3V1ns
la47WqxRWkKPASuEL4elv5EBSEqiNm-WyGZhy0YN-jEdLk6Tx1uGguVapWyXdoubAyddGFK9wAKDW4Z_sQyJWchyIFVRfpQXeB9X44aw-Rfs-BHbfEEs5PuD
A9aZvRjkMOnMKagbyha1cXgN8QDK7E1bYL43sW0TKyh9qAErGFdS04lnIooXR9Ix3OpudLm28TQPRcKOLjcMVsY6ufzj6EtOyuiZH6Wmp9v_rDZmASnyW8R4
igAym9Sij5EgPR2-mFU90uZ-IrNTr8zUyPFLv_m-0MlNvJ81t_FnKdhS-Qfs_nGimOr_iQggJyR04jpp-zsceYix-dsox_YywRg1BOMs-8PVrlVSn3nSpx9O
KFxW6vcFtYx1sO8L-uElZ-s_cl2Ju5qbw361Jg_KwelHraYK_IUHbwNLVb4iGsSy-wFsp5wkpv2Fravx_gdKxddsrZKVvEhtExA3J8By3aMucOcC1yu77Zz4
rCmzOWBGEc9-18ooYhzFvk_YseTQn4l4S9N-PvjARNs8ccUbn74tbN6sLiWVNm
}

EntityColoring(appsignal_icon)
!define appsignal_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, appsignal_icon, appsignal_icon)
!define appsignal_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, appsignal_icon, appsignal_icon)
!define appsignal_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, appsignal_icon, appsignal_icon)
!define appsignal_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, appsignal_icon, appsignal_icon)
