sprite $apptentive [64x64/16z] {
fPU7be0w24INa0Hk_lz_NtySbM0vo_RLcS18ywSmqJ7T0TnjgFnyCUa6h330HtkBLeEL3Bo_yQ8xgp0OJmmQw8AXtyOzMG-6rJeqNo-iTA6pNXbp2n-ibuPj
u9Frtam-dPxDxcB_ha5ZVJJ60Iv-T-U_blxT3jhTeNtslsoael20ApTnnZ7IOH-1rt2zIM_aINlqzYdFwlXGp2KH90cLZMAgVJWBRrMQHXBO1MvwQ0QWFzqS
_xzp21S5X6rUn6aOmC8rHq2_geUcU3bV4iw5QFUzON3DEECOWB2jYgOj4M0v05Ks6T4C8c3ZVFc8O0poyGhnvp5WMgfLcrcyHk4mcfwWUtRVBX4BPm4v4HpW
f5x2E2QuvmnQ97nFAUwdXziIlj0t8l1JPeu27_7vXLFYQMpAbPpxucS5EY5bRlH-Rcc909E_Ry5bt-jyLtnYHuA_lrVmPVk6TIG8PJPpWi5-E4yIxMvEk5BC
bS46pXK_XVL4G4z17PYz78sT8CmXHNOColL02RezVDbsz68I12blajg-aaNRRsvt2m9INVcVGCAJSWiHdaTVkxjdx2_s3C_7rmuiHbfF2XVx0u7lhy_mpswN
B2le9SMtpQJ9ynhSIm8P5BwzsrxXtG9ggx9A-ryHCAvuCJuHoESDFil_coNSjoz0V5Bm-qiC3f6-EsiJQhJfl--seM31m0uScwNe11YlNfy3tELqod3_gKrq
c0VOfyh6qR__zoS
}

EntityColoring(apptentive)
!define apptentive(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, apptentive, apptentive)
!define apptentive(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, apptentive, apptentive)
!define apptentiveParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, apptentive, apptentive)
!define apptentiveParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, apptentive, apptentive)
