sprite $arangodb [64x10/16z] {
dSu5Wbj130DGMP9b1-v_tavIRfVVXq43ZfAjmaE9U0UF-Zx-Yf7emg4Eth4FZPhP7GASbfiKZaxpPuaYK3pmUuU0PifZUDgRqjxkM-ro0PMEWKuY9GqcdO9p
c8yVQXQO0UUmTR_VhnuM1IW7K4cXx10THKYZKnrcwiGNik3iR9kzasKL3NJe48W1fv_nQF-EFozsgtQXQUtk9TdRi6X3YJefdn4vkX8-8pi1apIobvarpczt
wdhw3-HkW19bFKVGiikcN90JeCH27nRmOu1KU4z9QNmTaowyv1i
}

EntityColoring(arangodb)
!define arangodb(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, arangodb, arangodb)
!define arangodb(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, arangodb, arangodb)
!define arangodbParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, arangodb, arangodb)
!define arangodbParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, arangodb, arangodb)
