sprite $archlinux [64x64/16z] {
fPLNOi0m24FPSFyBTzEHGLpv_OC4o0dDiD8M5hH5bj06MkMqGLGb4mpN6qOmLc_aplRUKNnx7mI-lKyOtTuNJX3UzTW9EQiny7XDeiTh53nUa-3nS0DIVmXq
UuqWrySDQ3V03706asC6shoHOGOwkYcQc07l4a_406TT4S3fa0rmtH2eV2EWV1FB3myt83KGg7mZe7mJg7oZe7oJ2_Au0JsgkSL_3EI55XywsF97Kow7obLv
lNdFjYOVTsj9NlfioAqnNtctEIo65-HzY9KlH4Udm_9pScLg7i_9vPlTX7bt7vDxLr-fR7aoa7Ez_N7FP3B83_xRmY0_xg-n8RdZ_PhWyOSNTfW_XWKTftEX
2yJofW4_5JVyfuMTbnDA3uYV3CXtjT02x8Td55_6cHReCTf0HwUh5x7yVaOvL4yUla9cmzmZx5b1d5qDTL0psa3Y5G
}

EntityColoring(archlinux)
!define archlinux(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, archlinux, archlinux)
!define archlinux(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, archlinux, archlinux)
!define archlinuxParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, archlinux, archlinux)
!define archlinuxParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, archlinux, archlinux)
