sprite $arduino [64x44/16z] {
nPO7SYKX34GHIgtxNtWBpJJVs9HTUUNCevL87jj4FL6539Lni-a9B6uNBexQXfW_k2M-S5rZvavFLDCGPmnx-1bXsZjBiduObDe_-KHT3Fu7DtedHePxVEhq
Rt8Wt3s1qq7oJs6hziXNEPnDrJS4Ui0V7FApNL3MVkVvoTw9ZfmX8-eNRWmVcvmJqhRyD6sECV36kKuuEddkc6YWJnoZwhvbacF9PMVTuPVmHmHYwkU14H__
6ZH6EDVP8b2LyQw4DSnFz_nxFAsZjqa-TuDEFKuzry3l-aazyvz6EmKiMSrGvMRo9Rkd2-DcThR_x1_BDKQWtKwb_rW_PfSJr-r7lYjW2Ih7_lAHrmIO7hBk
6uGwBgDSYuSAxjntPwuJ75nw_OL3To7dVHT54ICTV3xyt7T8cmzr76sBVMbBEzSWb-y7vR7lNS-DxvmEQ1l_pU_F1sl_czDcudgvq_GNpfu2X6cN-snp86tS
R9elKnbN4srkvF_PH8GNBLBwnrDP0kWNFX3TMPk9XYE0dc130a08juVk0sS3V7wpigy1usiqydqo_CknQXYjDqD1ig2EmjpweOPArTv8Au1vLMXMUPzK59OU
ChBrsQF-qQ-OyQQQWd8i9AtBoYZC5TzZPO9NbdTz6Ihsdyk9JvGFPqNqVTKd-hEsNgjSKRdqw676Zvi-R4NPyR5FjwpwLo6jxsvUzOBMCyU1UewqBVt4Kxyw
7cyws-LS6SuvelDy6kKQLQPLzcJxzhyqULyfkgJSLrphPGKJebYghgH_iwhC_H-eTQvowiUAFVH5_m
}

EntityColoring(arduino)
!define arduino(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, arduino, arduino)
!define arduino(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, arduino, arduino)
!define arduinoParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, arduino, arduino)
!define arduinoParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, arduino, arduino)
