sprite $argo [64x29/16z] {
nP85jYin34Dbp52Y_U_s7wUJVgQ7jsptwcW0D_80B-CfYhpKbibB4cJrNmaly4NKtFKb0LAsM1O-0-G_TPJkvRVuxm9IkcP6Jkpx0X8PWa8y5R1CmqIpHOsd
RtdJVFeh80V97W2yauSS97agW8srSMZzM_osCsFwUkjaFmVfCB8VVfBdCTW5ZRngOrQ-ssoMzL45Rby6Tq1ENZXv2eB30EriGhR7fdnrx1ky1Te1rwVl7FMX
f94Ax1K7D9x1NjzgB80QCk7D4Gscp_x1QzOWWqE0W-qU9wyxUPu_d-FC-L6-u8wtcYn_UrZLcjJPPA1yTTN8p51r--RwdUpfRInV1q_tW-ouQhEH6sQ0jPoq
LleJxIpAfymc3_hQ7BZzNDZtjq-x-jMEKyu3XUwz7pilGBQhdxdkGAtkff5fVxXxPO_x_FymXsIsOpjQflvUXvCEs63xCLWpSxlsp5J1xpd9grw27v1SAFx0
y_x_0OrSXE9FM3R3JuZcIb31IuZbusN438Y8p_4rFD8pFFHblhcbXhc-p8UOEpnCy9zy0G
}

EntityColoring(argo)
!define argo(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, argo, argo)
!define argo(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, argo, argo)
!define argoParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, argo, argo)
!define argoParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, argo, argo)
