sprite $argo_icon [50x64/16z] {
bTQ7SkDG28LXEC0XNU__jfihoGpgsNzBt3w3F98dSfBYDyDlAdz80TNg6IbKfJNGdL5LENHZbcTKpymfQFleg_vcHr03T5EHSo2YnueSWDP2p-G8CDgJ1dG5
kWGFZi8A5Ua7KS2vbadhf7rs7I38AkcdGx3iL22YcHqvZXZ0dIqhKW8g-W96qjsZ4noEP3UYjggzzaEqZG2FPUm5LAGlTGnQ1100RIb_4cemGpi1Wvd9Lewi
2zi8osImp7ehur9unlnev0feuwvdN0XBboNF1QZC8Rq4keWG4Kk820TPRd5-1vm9f8dWP_gQtLXVH7AQKaJJpxP2geXDqy-uEyJOyNsQFiQak1JozaLf0f-V
s8dNb-iGa5TOjgfgAnXKNq8PyYhc8rTPipfoGDkPQ3N4acn3bB6zGEh4yhG22vcdWCHEh4C6eNkmdINX7ha0xPVh42ivEHDvk6e5HOmdnUwYhHlFGh7xchuH
7NHImdpv4INwJksBkmG47gPICwH6LElRW7Fl9gFrOtCfS2IwYfyti_ZyNdSyW5gi1B-cqLk90djI8hz_mGUN8Df13wh1jRVtv9hT_H80zah8TNegv2RZMJSJ
dETT70USbuLT3H4dWxjK7mx4xmxZMGGPZy9giVYB05bZnW-FlmahOVyfOWY_5zg51St_8B28U0cx1y5OneJD0aP2hb8BCdGTerm6U31SRuOeWZwGa3PBkGtc
uIP6gWH3CEwYqDr9xo8W0ogFmUlaHjJDtZy
}

EntityColoring(argo_icon)
!define argo_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, argo_icon, argo_icon)
!define argo_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, argo_icon, argo_icon)
!define argo_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, argo_icon, argo_icon)
!define argo_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, argo_icon, argo_icon)
