sprite $armory [53x64/16z] {
bT87ikCm281X421AzlxdNIjch1Jn8l_JKlnP5TOriV1E29iXYNf4F8x2DY1IjyWUMRXoAm4dc6ZcAYlOFDuozNSN_HjHNBa98G0ITtk1DPhpG6n74vRe11Db
9B56RI24JvJv4c7_YPpU2Md43pGoXYksEFCInRyyBq4uGl78NA12ulEu4F0YHW056h5TJ2Y9De0I9TCubSavBym76r73YJwY_cIXXp4uQynon8m5EjAXx41w
6cB9c2g4Cf0Vg0-2IPBX6hKBwVFRHusOw1lnG34GotVSLRKBbqXMzSEesgZpFkfg7cSccsWGpoBqOoDCZlhe3Lc4pqw54_MSHhYDEJrJEybKfhrp7kvdxgVo
H5CzoslqpLOeomkxKYMAWPHYsPz8C2hbNY42BvJ7Q8K2GQFeCPeiuje70AxHPEUt_540i4ONUxpL0C0gL1Hm93UH3eGt4S58Ro67PtGB2Ppv3HIOY6-W3f3v
DWgy46-Z3ZFRH84mQvj8uBM-XHpUimqKxGEr3IJm6Vz41j_r7yWH5cc1YWLbzWSAWdNeDMA0KbL8e0vjYOBXhr0dgjTJx_nYt-ha0nd2HkIlgCDUg1SAWkqa
aIBSgEc1dE1cx1sg_WC
}

EntityColoring(armory)
!define armory(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, armory, armory)
!define armory(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, armory, armory)
!define armoryParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, armory, armory)
!define armoryParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, armory, armory)
