sprite $asana [64x42/16z] {
xPI7rfqm38EzOf9OVl_NxJ7ybvFk0jsjxbJCPomMVKbixatfhiHtjITuoUxnpL_YMxoVqZiuF-JfAMyFy_EJtPUuFS5BOgOtX-UFt0L9JMulIDl55Eg7P3qF
xSQLipPpktxYQsY_U1ciXAt3k5pc6v5SvziwFr-VNzuZR1dc6sNhXS_j-bsaQrwsCetfYaI4Jh48qs-h_s9PZCYo_fcdqBeP-mIYI-z2n5i0iUqRwWXWcWqd
acuoNfLYeepsGJ9HoW2Kw31m8d9ahIDo4XaG2MHE9bgOf9bmaHPPlA6C3ouYfubko1oxmoQo8JlHoZXW-qIHK7B4A-CiR1_ZuE7bjWmc1xICLBvgM6grgCZf
KbRBdesAvnsfvPK16j5PEKBFLgMWGzl1nyvpG2aM1l2L9-s1HATs9kcVvnLunJn3LGj01B33naVyM9Zs5a0ZYzSbvDo93H_n9mE0HgARRNWxVzFLPeAhORYs
WVo8NndYNZ-9MNn3bjdRMoJsmdiyYkVnOfA8sW2camqv3X-6KKcsG0oblX7fhCX5Jg5YvXlp3W
}

EntityColoring(asana)
!define asana(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, asana, asana)
!define asana(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, asana, asana)
!define asanaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, asana, asana)
!define asanaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, asana, asana)
