sprite $asciidoctor [64x64/16z] {
fTU7iiGW20LGx73v_-zzDMM2CxYIyyhsrLoHIUYIwX3e4cJKH9FK0VqKHgQd1js2dkYMMBV9FOKi6e1oZYuQWcC6h47obq7Ni4542Hg6SWmVnSVmKSWLwW93
7Mseh_ipP54NafyGi5wXZ1Vvl2emPVfLeJ6eH3KHYSQ0YAJ6QwmJ5J1HGZWzFlu7qyiuPl5YTo6Oe1m7ZahKT5yxLpwMu37j8ySHQKu5vkw6Uz10WkQWyHl5
VkatinJRfR_VQ77wApe0TvWPkiI9Z8OhGTQbHbQ2AIQNb6pqEq62Bi5o4eniPX-CkPbuqAinfcQss30Mfefo25aPKqLxXFyLeig_CE-eZSRXxEXrrtSxohhh
EnEB5mgQUw9xnzpTZkuJPvbHt0JN6tLk8-Qjjb4iNnL_1CicY67JzuzGJ0rBLODPFJBmgBMtvwyqtZUbC9HtrmziBdzY5q0PyRFBFmNHZn-oXBAxfG7T0ixq
K0PsFbreaXlZim_tJ9Tl
}

EntityColoring(asciidoctor)
!define asciidoctor(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, asciidoctor, asciidoctor)
!define asciidoctor(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, asciidoctor, asciidoctor)
!define asciidoctorParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, asciidoctor, asciidoctor)
!define asciidoctorParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, asciidoctor, asciidoctor)
