sprite $assembla_icon [58x64/16z] {
dPTNaYj120Hfxuhx7_UPzIkfSqp-e-mI4mJOXjZcajQemIuHk_mTgLse3Kt-WrNi97dvRpIJdI0D-HFgyS93VwDgI5c-Gol3GwSSq8ZG2UPrXwhy1EifRfxo
KsZ-YXi7r57S8h-4AYHarDZe4fP6-OQLu4UpMQSqtNTCKWPwa4eb9Kd716MA95sWdDri-0w1KegMv1UfRpgIaj9Ta1ILRz9-H-ag1b9IBkufAyD6oiffLY4f
AnVylQoKjusKbDd2mfwoqZTILjfoFo_Le_9DskuetGKz1IL8MSbILhAKbM_Ie7FAyQuyBrNyySMw_vBoH59Byts4f-w_6Adpx9DsCr7otqo_YPhVP2JTL6QO
nCWqkoTLChD6fRmezEk5tTu0AnXn0-CjxF9Ef0gR9YOCiDr2tKYqKT_QgaC3hU3eWNqLhWVe45yiq26yahX3bowpD0K1cJpqNhSD-1S
}

EntityColoring(assembla_icon)
!define assembla_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, assembla_icon, assembla_icon)
!define assembla_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, assembla_icon, assembla_icon)
!define assembla_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, assembla_icon, assembla_icon)
!define assembla_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, assembla_icon, assembla_icon)
