sprite $astronomer [60x64/16z] {
xTPNWgGm34NHfsG9RFQ_tJ6OeHBHttqwXria4V08ungfOe_SICTI1knGNB8oJKNnot0fJGUj4gvmdgQHy8a4P0IXgpYbttzXPHDbT55B9dY6M4HKQvgIgGZJ
avYuvgsjALFVEYkwABCn2pe8WOp0Z1vBsytmZN2N7lochtN6JO9FP948UzGgETuw4ey8tnjnAxDCEA47oytJmd76TzDKMbiO9mGxA4-h0IS8EtpwhmYUuJ9j
Hjmd3CHIvR8iM74FgHj1riWF5tnym8QruVOQzd41KjalstpgjgvjmPa-XetmWpmKYt4xEEk2VGsJmXI_f2sqiXR8QqGA0MmHWqFsK_eOY-ApQ0Shr6CO8Z5s
S0HzJ-Di-PfhDeGhOLSA-Pd6reqrhCiqnf7OMj-okMlXcCycquTG9W1Sgfp7bgtX-O1mBDnZQD7MrV1gCicy_NkBtLJLcdmvcMtUnfpheZB_NWPAmZajUnUQ
l4tccJQDXV31TbyHz_uftxXqnS5rLSj2iI5JV2ATCNw8Le8N6mAzs1CU-cD6w4HctFsepumpYcwKq4sT-wSlKcUf7X4kXAT8aiVChQC6MIqLdL8OUeaJUf6X
dw0VOzS_
}

EntityColoring(astronomer)
!define astronomer(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, astronomer, astronomer)
!define astronomer(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, astronomer, astronomer)
!define astronomerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, astronomer, astronomer)
!define astronomerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, astronomer, astronomer)
