sprite $astro [62x64/16z] {
xPVPUkCW38Kbn8wGtlzjfmwjOjFCnFfoEwTxmuzFjB30NqH3JPp09vnw5ldeeXTr7yrNMj031zqKFNJUwUQXnqvF1uoY9d_Ka_vIlKytOom0V9ysu-7ywqsH
nUeKltoNhgSycVNXBhG847pbjWCsLN9qY9cjpaxXIw2YERbdV4kIk3fbBv3kAhTzTF9q2kvEqLDklwDaKIoE3h4C5KUdp5_LGURcZVNNG-VjJgalRBQRvRQ7
Q0yatbsAwMKIxnIQS4sNBDOXTnRceIezlJ28iScxSWl2sT1Tc5ZfNpIbDuKOuOusyqwrUlOOIl30s7ghYG8Y1agrjUYalzIMZjy8FAhzeXPSTBxI1LoYraeg
taURIddwRmHEOJ3_DRX8KpeUdFoSqPPflwZjqNQcFNr0XvRX4ppvcVzA8tv03trB8n45C0KYmfSqKjX7nBLFo6fYhAA7k20q4LNv4YF4cR2lxQ2m7XfnRP0z
nrHuxRci8yUOszI9XOVePEQEaBHEdTm1MQMNKeTgWsmRTTKEG7OURIESdIULIR2cNwPfQesP3hyOAEiyQ4a1SH5NMXzmr7awA42eF4L5H7NQxYzpLDfeXaFb
j8zEpQgZbPmYVSyQSctzCI5TwVvDTwD5nKut-K6dO4UGzg3JbIOL10k5Qlo13phhZ3zqFRu_OeHF6heoBLYqL9LMIkbJgifwtznAgQmph2Ely9pufB4V8rgV
gWKWpvzQOSR3MhVYiPlqG8XSdxM_1X307m
}

EntityColoring(astro)
!define astro(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, astro, astro)
!define astro(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, astro, astro)
!define astroParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, astro, astro)
!define astroParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, astro, astro)
