sprite $atom_icon [64x64/16z] {
fPU7hYij48Fj6PltV-E_t0tYhWKwGUTJIMDwMO8JRDdZFsnr4JUmDG8tyIMbiSNzbRJ7cRwIllT1uqT4dA37DzIjxucmeyVNw5OyyQruej-9fuBCV5UrHt9k
fVTPC-lHHMHRyzWs1KgrlkyubZciIExZZmkOtfJiJZSxl9zeAcmzYQ8UFUa0q_pKgvUHcc-pIjgQ7mNzBTxfru9fFkKRKCQL3dWdd-BB_om1noBE2L3e3MhN
kVrqZWN8Oo5wqyKUYK5rLm4WgxhbSG8OWRQBchLNKlKsNVDu4zJ_T1SvTOoaEwNPAhJzoftzF8AOKscjzvep9z14Rnz1yRMztgw91Ihg-Z6ZobsnFjGQ-3Mx
KfHU17meXVzsPKuOFn4jE-1FfPp9Qyo0r-okzm7HomHgnl6yQrJEKIAWrrZ0SxwqTj96tkzLuSTiV-o9r7JfKPvxo37E_jYABAyCYg_yAThNdrWxWmIyQu3U
9TAp19CPWBC1NRlnVRB1pLRkZh3EwuTX2TZU9Jm2GjlTmZoQHj9EWPkrceUv2tyMkYEkf8zFhzo_-xQDXP1cUcdVoYkVN-bcWLw7kR_9zK5U7eEWZ_QD1-_o
v_h_l0aw58VvT81e3yyLPWBQhmtjhp-AwsWzRplxpyI4UKC6owyYStTBMaHakyNFzFxgucxd5zSt_mm-yArueblnHByGlxc4wrT_W5p0cVRbtw-4keqyOL_R
Jahx9hwWsbwogfFmlm
}

EntityColoring(atom_icon)
!define atom_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, atom_icon, atom_icon)
!define atom_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, atom_icon, atom_icon)
!define atom_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, atom_icon, atom_icon)
!define atom_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, atom_icon, atom_icon)
