sprite $aurelia [64x62/16z] {
fPPPaiCW30NP9P7xttSAGLvKaHUSwTzOQJTu2vxOKlW7cJk7tsdIUw_1aE8Z-K1CGQ4QDeb3hZ3aZOZojXpKjro9J-Ice9BoNP1kv2Z8jCXMH5A2Oyc1L7C2
jg28TF51nVr1qYWKG3wWu21CkW96GP65tzDuMi32H6tAGV8hw0imGorDEM2hRdfsxRXW75mW1-qZ9jRrZNnOq8GWj-GmISJCxQ10UX_7H2zNE8P97VDngYpz
zLeRNLWysCI8xOtSpVI00kIUyYv8PW_4ZaioSWVRJQo4WZ6jL2_t1LZ4gWMVSJwJ-qqiFCXQOELDhY781nH7mRPSk63_b5dGj-N9ob5GzkL81wE0sf3VZ6kh
qXXWGJVa81AcHRJWJiug1vaLhCaJEGhmowsyGMuBL1xtvAbY50KFv9MF2jgcF3EU7ROWg_mAbUjRxlW5KEHMlXvnHtkGg5_3QPRsxfuTAk-NI0cXP3mWX2az
aLCCaLuzZcCPf_z8FcvhrjlzD_bWlZEe_YH_TTmuZ-LhN7YfGNqWn_rjuNsvybsGv58UP4s3xO9foZflaDi2oBC-JTSqa8q28RtLwF3_wR80SbahaFitvQe0
SfnhwmyA81_8Re5ukOxBPW5PUMHvJtUXi5S0UOYXYQnnrUyLhACJ4Ju41VTvwb-uxr-UyieYTIuVvBw0_TTlOZsQvgEnoKVk2WHoJs8PWv6b-1NoSazb7Kpk
e0hvDJ6Sm90_1WMG_q8xaFy1
}

EntityColoring(aurelia)
!define aurelia(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aurelia, aurelia)
!define aurelia(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aurelia, aurelia)
!define aureliaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aurelia, aurelia)
!define aureliaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aurelia, aurelia)
