sprite $auth0 [64x19/16z] {
dP87hkOW30O_J23qkVzjznb-xUjrqXsD9HTfu9pxrAynDjV2YVej6MUeuHHzGKZfrKVqPtzu-Si2OavIXA07zmA6AR29poyVKfYl_1j6MyoGbpCajUNSSYp6
_GZxRWg5QM7x-qzOL2akIY_X2Jd-ahiB7PXP5ol8xpO0McIb2ICgWUtQvw9j-r0WA4ncxH0ZR1-h2qQ9iEQ0SSe9ZSsyT8W3C5drb8FoxAimTlrrbswLhZXd
uP2EZcEd_ZIf7_Wc6SJAkAaUc03NyoOjINa7l_8Bh2GbA8-X1vrDRZjQS-nV-VaCkh1ixQBoAbxP3bUQ9zl-9PNZpvU-GPR2fCbJxKvsCoXdLw8Lg07cNN4h
Gux__KiDxZJsT_MXEa_FfYTi-OVdlW4gs8xrPr-XFpS-BHxSsjXTYrtvagvIOhZl85cfwRoTkt9jnPxdVlRWhnIyNFsTDBF-n3y
}

EntityColoring(auth0)
!define auth0(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, auth0, auth0)
!define auth0(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, auth0, auth0)
!define auth0Participant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, auth0, auth0)
!define auth0Participant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, auth0, auth0)
