sprite $autoit [64x64/16z] {
xPTNOiOm28D_jkz_uUwMr14stVDxJ90jGURbk_8FCOkg21EzGgiUuu5manSjmHfZ8epRQek1S6uvrnWLja_1FXQ4REGIOuskvMEBzUKOUvkyZi0nUWWUd8D-
k_jvrM2arsBUR6F6eViog3KIW2AhapdjjmzQd9HzUiQJnHsWWE7hT3pPnmdhzHNQhqSiwm1Uz8UaI12qicUfugA45_63qhKJhj5Qd-xZMAYrNl0fU-QKl7mC
A1oTJ6cufG-Uhrf3PLRvrxDT0GaglOFDCa7K_J-7TNs4SoEefm2ZWuyfcmgdO9PrMG5scXUty-Xi-P1tGaVvu3uBK083jh8ddlwA10nM3Nv0nt0kqHmJcE1h
ts7UrkRshpQWiAzjd71Vk-3PIDyzHflkBnNM3u-nlXoZ3VbRFW3rJH-WmPS6ueLQgVdnBuxLVLWz3betfbVyWgZTe2ef_cRySmq
}

EntityColoring(autoit)
!define autoit(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, autoit, autoit)
!define autoit(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, autoit, autoit)
!define autoitParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, autoit, autoit)
!define autoitParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, autoit, autoit)
