sprite $ava [64x35/16z] {
fPK7qaGX28FNBdZ_ysxp-GsZx5-PfY5Wo2lULiGcsjDSXoegBP9BJQIdjLOrAIYgOmmjxqr_hpLTkQBZjOzphQzKtkjb34XHvqR2SyDMwqkPNhoP8lB26mLM
3VNLf6pqCH308KDkjbjU6L94UkESqbP9cjCZkS0p3b00pKw3CvtrBW29J2OqGvfc-gBj2boXSQK8QOAJw5c1Ano48E7u2cgSvlsmqUr92jkuX3ap18p9c1Ir
kqpUePFR_9wuP9r6wzPu8mijDn1N2DUhWipDwUCadjMk2C2QShZYloljaCb3AU2ks_x3Oz335RT0Q7SudS3r5QPnqjCzQ6JuLAMMmexdXNjzyNfvHeS7p8VC
09bN7_cyjBI3x_m7h-OIplzUfBUk2KECWVzmdoJbDzpUiER5owfJJX7LFk5dp7j0sZmcTkLEg3BNyUAbhYhrbRcuwHdnaaU40vYykJxn2E06F4h_MqzymdsU
WqSVFtc-pE3ZFY_uZSzoVu3eDuu_g__4y-6Vyy9VwXy
}

EntityColoring(ava)
!define ava(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, ava, ava)
!define ava(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, ava, ava)
!define avaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, ava, ava)
!define avaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, ava, ava)
