sprite $aws [64x38/16z] {
rLD7eYWf29JK1l3-rns1RlxBQJUr4PN28jW2T4rLNPDp9qA-lZPH9AxXMcgs1hS7l6mdRE7PhxqLuWPqc_bHd9gwivOlj8IVsC7UIUndondPZYdv_357dcnB
xqU1sUfCI9S7waUqnT8YahCSOXuKzB0l142U-l0hHJotceBMhNa_vd1jyRoq1BJNI2V3MXhOLjq6TvApjUlSKFiKOd7DeJNMCT94Yq98PlWPEFcWcNK_N752
FWnPHHlubeVNM6jqUUJDp7fjmyDOUJAhehQkLqbqsm6pcozH052lPXP0dxeDIrUzYZvZVs3xvaDaIxQ7tngv-SmHJyiGp_nSRXCS5gR-RDpm2udhgrsPK08a
HSmQFyLNzGkI-iiOqpHTekijm6NxLeHMaQgzVcWKwKSLiEGxobNUycTDlYTWSUuoUialaDryCDSQEA8UdOTXRkTBzI7GLPG3rP1F1A2iodh2fqEPAT2c801G
jvB4SQzcH-SgJytFd09BuQpVcuubsw7USflmVAKzYsGzJLBR2LjEJs1VglDo8airMGJlwsF2Syp7rrG7jxy3eFtl0O1_JmDP4iGCVsGdW8L-6u484G0YZ7Uy
8lmMmMzq5iRVve31vvmfaL-9069_4Mf2IHnCy4Fo0GQh3baIZF0L5vCid7-5FcmAq_lHWA9MjK3aaxOcc9aSVF3gl9B6JmVZSt0fO_eWmKz3lA_EPor_4YrK
LNxnkJpjOZ9zsfN_
}

EntityColoring(aws)
!define aws(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws, aws)
!define aws(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws, aws)
!define awsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws, aws)
!define awsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws, aws)
