sprite $aws_redshift [64x64/16z] {
xT05Wjmm44JHQgvMxd_Vo9fb64COdXc-GLz-XF_-6wF9ciWUusnRhe9dwjdZS5ss6lF8AS8Ka-OubBS16XpJ2iQ6QO3KsAq71JRZ3uR3WNn__Yr5pdfyX88U
EnesFfN8lPxGyIa_qiDwV2nmg0USuvqEmQ7UKm3nPFT3sQnG09w7-j5fs8WkWer6ZphMJrtXAhTIrA9wJ7cuN_h1M0xtFTwhoFw6FW08B_U4f4FxOj-1x5Pi
VL_f4zQ4T2BwxRKtjluzXG2n-XtrOL-0H5_l7TbzhgUhisy8wSEztH818EmD0twsTtWvdDsb0EfiRs0Ji2o1AkpQ-nTZ2tYo9oQf2eMJUgRdRIktyQV037go
fo79Nf5WvMTwvafkcCK-q_FvbGlP2sVF0tq1Ad3siqzxlh7rZc11-4uW-CQFw1CmWL_k6G2Cb_fSOMNnUh_yehw0v2TAaTpZW1S_4WBZFWTWMLLyKbNf0bXn
NvLX4lF89TmKasRnaAemmIkYNiN3QjhUktXaJJodNk5dwe_s7x_HLm
}

EntityColoring(aws_redshift)
!define aws_redshift(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_redshift, aws_redshift)
!define aws_redshift(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_redshift, aws_redshift)
!define aws_redshiftParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_redshift, aws_redshift)
!define aws_redshiftParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_redshift, aws_redshift)
