sprite $aws_codebuild [64x64/16z] {
xSu7bjim34NHJw93sVzwGz0QTvNq-gROEE85zUcFxd_BxvARMNuz3upeMpmfq2iYwhFdgGRVzBBWJBxZUsPwGmSqBndGq2ndqK20RVb4NnO3vFAlqjfK_-QH
3buSq6sV0jZbAEMIZEPZyWRE-Y-vh1yRdj2ZfabjBbblxWPehWE_yvm0cjfQlv-q0Q2F0Q1yU__vxDaxMiU8jEeGVOp1z-Fh_QrqRx3nA0bF1zBgmPloBeCu
O5a-yZ65vL4EJWCqly7F1T_Yvu9lyRMWFViGo4bVdtZqnWr04p_dzS6xDA2hQw-FEFPoz_ukfIuNXtD3Ozlt8MX6qqTTEOIQQMKc7RKktdihpsWU5s_OI3Rz
aDqp23vd4dr9UDlJu94tVtymFZuD4XiUeCZLpuCtQUGdF4S--BbDQkYmY4ClLn_hmV1UMntTkyIBZrlb8L6LZtamj876m507D4O6ZhSPg45kNiUWbvME5c4D
kk_P6_ZPbv6vXT4EVDI2Ux--G8FN4kYHdmlypeS1hk1vkyL8T_rSSE_3D3g6bEvnmjS2t7nbw34xvUS2lp_8q2_nydo_szEnJJ-O2rfRFUcRUDSxencjVgCT
FxaJRCmk6_bxh-39O_NX6yMcB-xJUvpARmsFugC-_9UdarVqjLwjqg-z_zRNU6VwYFqdzB__VGO
}

EntityColoring(aws_codebuild)
!define aws_codebuild(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_codebuild, aws_codebuild)
!define aws_codebuild(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_codebuild, aws_codebuild)
!define aws_codebuildParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_codebuild, aws_codebuild)
!define aws_codebuildParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_codebuild, aws_codebuild)
