sprite $aws_elasticache [64x64/16z] {
xTC7bjim34NHJwA3sVzwGr9CB1-vJQzl2k1oNQK_NxhVsjPlIVNXo8_Uy8JuajTyCB_ihJrONFOKVKWT-PeKoTkIGTjiBUMITw14IynuJMXWostDbXNGTYm4
b8awtz-SgSDpNtXudJCLvErIMJ1z6sRCPfjlATFFcHNHBXQbFE89bXTqIe5itfTFWmMaBxpp3d2SsByCNPqySQuRnzGQtUVqgGMSX-RjqsUmvIn6kUNiowVV
yJFZMZ0hLIn7J_1I9gHUdQiyvcFp3B15hi8Oe9ZNsoFUKIFF2eBUzhhp2Zay_3HotnUFlaCZTyNsdGNTzvqEZy9g7ZqteG8CexZdKvcjxym5kmhhCCuID_rf
Zp3XxPHdzHWcShNse_THR7ilOlwB_oPyTDL7GOzZ-LtBAqPsoKStZaBC6d7D6pDLw7NFqHixzx4hvbKPFJlt4Ik5ACZSVUnWZz6wWpF0Oxh9k1_78SMArbvP
RQJpwvzUiRhWdOcOYMY-Vv6ANLLj6ADn7oQskD7q4Mx28r6RRvlYqQRVz_wU3rSzpKCyThdWQRv7ekRkPieLFV8d-EFv-pGlxkly9MOr3tk2z-xdN4NlgTvZ
rzCz--6gozulPO3uMLAW_dW2518pxwqJaFqf6U4iCdzYfkFhA-CR5FLFsM-__GK
}

EntityColoring(aws_elasticache)
!define aws_elasticache(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_elasticache, aws_elasticache)
!define aws_elasticache(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_elasticache, aws_elasticache)
!define aws_elasticacheParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_elasticache, aws_elasticache)
!define aws_elasticacheParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_elasticache, aws_elasticache)
