sprite $aws_ec2 [64x64/16z] {
xTK7Sjn034JHHkY6VVyBUvQa8mTQgEHS-ipalCtXun_kmt_SUyLjcd8qSUQ9IDvBnD3lxwZcFdUdXQY_szUvAjLZxrhclhYkQwrAh7E7dFiYiYh0AiEv5AnU
xRNtzQslNOcG72aPU2nS_aiF_rA1NQQHLomUznmUmUS-0LZT8rRnt1VP-20rUlwDprhzSa-phK-OMGuyqFWdhv-OAvNK-9JgY3il7B5KhQylNflhdYlDdh_Q
sqy0fkxvIoGJllLr93K-jC9HwlRqbrVlp-igXRj7gbglreUaqb6rNWaqVXMgizxJhF5cTlUwElpLyhUEwqq_rvED3tBW4sZyob_oeKTq1-AMEymzdtk9ZcsK
DF5Im3CTaMaubuHHOvz8CK3A81gwzwJtN_z_fDTx1gzLnhaeSk1taMeQUSBvEpoNvzkyvwwvRmfg4jEt3Rd4he7wLtjFR-mJ
}

EntityColoring(aws_ec2)
!define aws_ec2(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_ec2, aws_ec2)
!define aws_ec2(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_ec2, aws_ec2)
!define aws_ec2Participant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_ec2, aws_ec2)
!define aws_ec2Participant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_ec2, aws_ec2)
