sprite $aws_keyspaces [64x64/16z] {
xTPLWXf158NXSrqc-rzlMXbhASXBx1y5wckt7tzq_tlxtlJczj7q_LBTDTNz0YrN9cmHgsS_WNMXpA9Jiar8Oaot0gHH_U6j2YM0Ou0NdOnB1UpUy_cWOlWT
J-ZLib7V-81VBjozvxxuSC23ytXG6qOy0HBTNsod4eW6l0S391PPlLGP9WIGDJzyv-5ITi3NUNs9T5uceGrrW_gZsvlz_Ah2LNX9pAEw-ttKMsKJTzQx--Zl
4mYHGFj5xq80IPpv-mJGxfUzmXJsj4zJLSykeYvmVyzXVLOmrg8hkxCEFLSVvm2RHzY-tSu6PVL12LZrNRuU_zy6LYkaUi1xC00nZwob33VH0hA7_7gr_187
g0PzTrMwFOv_DSzoy80ltpTIVQhRdl07rRMllTaVvk0wxzu7w9Ty0ZdafOvZw927PXqLW0rva6KTf01xHBZObJS5mEgH-_6RuJeJmvPU-jmltqGyHOGfogfA
4sRMkDt-cVvuxW2ngEzcVFzbvLRb8Dxzw-MrpnpmUVufKzvuk_OuMOBSSqYU5g2yYs2ddA1vbmFiXre0oViUZnyV2bS2o78ev_suczkFGxOSBamtzNW0Ztoo
cFAfYCY_lF_z1
}

EntityColoring(aws_keyspaces)
!define aws_keyspaces(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_keyspaces, aws_keyspaces)
!define aws_keyspaces(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_keyspaces, aws_keyspaces)
!define aws_keyspacesParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_keyspaces, aws_keyspaces)
!define aws_keyspacesParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_keyspaces, aws_keyspaces)
