sprite $aws_app_mesh [64x64/16z] {
xP47ejmm24G7H1cS-zytykzMljcMdhpjEpnG-VBRyf__b7izeWk0-nji0G_uTgzEtNt9hUcmdLA65mQtsmb0izn91QnkzbFYxQl2RtF7CY_cRrvjAv3R2g5v
XHivWC7FZrCpejK7WDCvV4whcOxXqDEu1jmGdM_P-ORqxYfAWFFBBiTETmyKc42yFh53i8UvDPIYoe5HQq85Z7j-oT-A5lEztYjhFcMmjej--CntjNJaIuUY
vKk_FL-C4rxMEw41LhSJ0jX485xNulRnXs37bxn3m8_Ly82jUOSk_Z3Oajymdme8RvY_xey2Ddb3izuVwKVq_imNslrImIP_eQzlyXMcm0y56VoOEn1DWnJW
s8277u597bVqaO0bbASCXCDuIa0DSZ0EtHH3uUm6JCIIhmZuXWacWnqHQG3YVU97spA25qcJR-S7C9BN4y-xKEpllh-Ij-00B5EGQGBdpQG1442aNtdVGKTd
NsxWqUizWOdpRj9LdG-G4_vGye_cFtoGhm
}

EntityColoring(aws_app_mesh)
!define aws_app_mesh(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_app_mesh, aws_app_mesh)
!define aws_app_mesh(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_app_mesh, aws_app_mesh)
!define aws_app_meshParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_app_mesh, aws_app_mesh)
!define aws_app_meshParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_app_mesh, aws_app_mesh)
