sprite $aws_codedeploy [64x64/16z] {
xP07Ucix28I78ehUs_zwhqcE8ftFIk_bJp5Z643y_wtvuxylJCy8ZyZ-4dCeOy3gp-kHZG0G84s0Yg7nzBqL88skq8jga1xLJ_9fTWF8Bli6-4OB_FBV6MZz
QSEjLyIuNJcFFaxWVDJEeoZ0npX1ZDOKZzhrS6cjVNJI8sj0FD7U2KUqXWRA1zykep8gFD0vrSQhTlXCTeCjtxS-HzI6MvBcd2w8cLY6zgMev1sNrZLc24B5
Gz2Tw0wUOYL1g-0-4UGglEzei2a2sYUwMkgoEsWTKYUR66nHZDpOlIPcUEHmJ5dT3dbUzBoZ2mgsgebiZ4ByvZMXL8eqS_i01WCagWnmD3G2M5kvD21scnG2
Z2WtrmVOiy8G4ADilN16AR8ibGqNhls1iTMeiJifPOzvAC0tvwFigqFxb7no-Cvla3njuxlcexjTxq_WoAKarYHuiUjkVbqDBUS5BDVbPiO9x7r3McLoJ9JJ
ENmPhfbzHuPKyZOcpAeIHmM3B5VFcLeXicWj1rC4894F4SBv0DBo2GXlqNmQ3ko9p_J_-V_yrmrYmmF-3T_8xnypFzeUYpD__F4F
}

EntityColoring(aws_codedeploy)
!define aws_codedeploy(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_codedeploy, aws_codedeploy)
!define aws_codedeploy(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_codedeploy, aws_codedeploy)
!define aws_codedeployParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_codedeploy, aws_codedeploy)
!define aws_codedeployParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_codedeploy, aws_codedeploy)
