sprite $aws_rds [64x64/16z] {
xP49iXiX34GRX5Rd_kSDOgXuVXZ-EFlwlAcCNdSPV_YZ-S_Zjy7qmFShePEuq35fUrynuSkp8edj_P2aNdOeocNrWc3ZImF5hSweUkrhq7q0exXl-X_t0Qa_
jluISAdl_INWKaz_tR5cZyy38dckIkhfDtsinFmWFLHJRjHfB7Q4EFbpTKlkXhM2CwHnxSL2Vib08LRpZgba6CMoliLGDTvW17xDbMgXg1Ply8OMKjZlx09e
zu7AQXwUJsK2ki_vxh77Aj0ika-4DzJi3yzusPTZnYiaihKEYCN2kfymvh2Ydx9bAKb_3dKJu0KQztvupRqL1iT4G5VtFp5KNtMlyASFa9ZxE73JLl3qdM0N
VYaddmewfNQEYKx_N8FUzKjUVwh3RUhszBrUzZUmd-_FJqHCV__xmmhKn-JP7sTElbjPJwS5SJyc6gsJd3dzgOzfuYS489j3QJh6WN95jnBEOOVccgLVoxX-
wemHDJNZFek_mx4W49EMug0GctMVCUBVHwfrdpsnWISASYvftpFz9zD_6GNO_8H9WVZhI05g4z54MiNcrhSOLvmeJLzMMUVT2RT6r1gBsGorlMPYuwEXFhUi
Sqe6sR6gcpjFlUYsWeu01TbQ3zxh4wkejlTjqIy3hdq63ztUzKV0sRT9-aE_eu84P0kCalezX7Bj0wo9xT6E56pyP3bxTKTfmhP5Q2BsFVZFVpu2
}

EntityColoring(aws_rds)
!define aws_rds(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_rds, aws_rds)
!define aws_rds(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_rds, aws_rds)
!define aws_rdsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_rds, aws_rds)
!define aws_rdsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_rds, aws_rds)
