sprite $aws_cloudwatch [64x64/16z] {
xP9NOjj030K7m6BnuDp_l2waenAjRL7EJygebtaet1z_7__vpzCh_Vfuo7srvt338lLLnDEA130t8FHq53cMczRJOHxLOVJfquGyfBTTLvGT2mZo9h3krmjV
VDKQCUg-yhNupdd3--lfyUL6lLHnHq0jbpNYJUpnzIPpkQlk_SMilsZ_vA_eGFsfFetgpz9jV98W1zFd9nj6zpgz86hnOx-plPk6NxRG9sHaBr26cqUgTmRU
AmPZPGz-CjGRiQvZz2rbMAhLIiDgZyHM_oHMNp9QmzrJFM0FSDGtp4LNCgRYr7vYsYUj-_mWvVYKjErz4Bi_L_wuxTuLH6ye21bQ-klv1xDmdOUf9Blbg_wt
x2laAAZB3eLt5wQ-9GbT-zXLg72PIKxs0XcfQz-5wJhF97FrYeAXC-__lwdVKYzH6VY9bA6WJlkRXFYrzbL13UF4q63EJP2qhpqPkfytsK_6VlrB1t2oxFty
ELO3KWSecEM00LwvZtM0XDGCCujP0-Oquc20PxsH1bQgWm5x-sP0-1RWUEa0SxXXFaeARAgsc4DKxSAs0YaOUf01MPCeFKObk95wb9e6KNgOgZbBlutw1l_v
Zxx92m
}

EntityColoring(aws_cloudwatch)
!define aws_cloudwatch(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_cloudwatch, aws_cloudwatch)
!define aws_cloudwatch(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_cloudwatch, aws_cloudwatch)
!define aws_cloudwatchParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_cloudwatch, aws_cloudwatch)
!define aws_cloudwatchParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_cloudwatch, aws_cloudwatch)
