sprite $aws_codecommit [64x64/16z] {
xPA9Rgj034MlTtlw_lzx7pEeLgf0HNZxSjh4OC-vn56-_D7yv-qtOcJMD-YE3HdtTJ9dy4rzW6ehYhZd9soMWjxp0xxxSiylyDYApPWnUJL08P466iKJoXVz
eTZOj9o5A5x_-H1yl2q_zWN2Zl7ZxHYpds0WLYBZ13_nQvCI5a2ig3Z4qFvuX57RUy160DdJ9mB-t6m_PPk6piOTlqaLpN64N_4D4xlhEoWg27xJP-JS0NpF
Bt2txlcqAhtW5oFxHc3hIvHnrNS283Ls4X0L8A_w3gWok0CO03_eeVM9Nw2iAa6Foc3BgAXzkwXpFx3YipVeOwKh9y3bTUQNmzhlbjUeO51iTu8mIFNPZrI2
g_epjryEo1mag9BNzQDVZK0Y5SZkB5_0DLbBx07BVqQmGL4V_ToL1Eqjn9bVJh2iQXHUxm46NPrPplnYV8Z3laioPH5o9b7Kftu_FetHfx9yBI6ITSaF0S1U
3I5gSS5F8u3qKGXmNVHpV_I-UM_ZST4F0cdiefDNSy5FWZEqdsgmw_w-Di1PP_wdWpH0bM_x0OhC55XsObytfuFqjNW6v2K_tvd-He2xDOyzSJO8q2mAlUUd
WDqL50_7rEC0roC_61la-U2VOdc0YrWy9iefaT-1__pdAm
}

EntityColoring(aws_codecommit)
!define aws_codecommit(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_codecommit, aws_codecommit)
!define aws_codecommit(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_codecommit, aws_codecommit)
!define aws_codecommitParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_codecommit, aws_codecommit)
!define aws_codecommitParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_codecommit, aws_codecommit)
