sprite $aws_codepipeline [64x64/16z] {
xSi5WWGX34JHwWoGf7hlVzrrnpAkhmNzJrVjORqbcYDqRQCWHhpP2v9590WRkIAjCGcwrZ8is1loNhqZNNlFQfC7w1dhxLVFRszzo7jVYVVqJYzV4haH4MEH
fax_JSW5W36ZgTadg7yY-JqqQBClo6m8t_G5nICAu6nGH2cRB8bWOX59nYx7X3fRuZtFtFimFtdl_ypxoYNrTjp-qPThx-sOlMtTsp_pld9JVTuC9JkWXuSN
}

EntityColoring(aws_codepipeline)
!define aws_codepipeline(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_codepipeline, aws_codepipeline)
!define aws_codepipeline(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_codepipeline, aws_codepipeline)
!define aws_codepipelineParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_codepipeline, aws_codepipeline)
!define aws_codepipelineParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_codepipeline, aws_codepipeline)
