sprite $aws_codestar [64x64/16z] {
xP47Tgqu44IhS_3iVxs3G0VyV93Dn1-lGx_0BT757pyqltdxtgdC_WSsOyF-jauGDuB-JL_Ws_zcv5_IN6gV3TvdGT_wUGijWFNksPdZo6Vo40sxMP0-pYVN
9tw746abmVfQl1M3_5fNW0aRVdoGW6K8EFr9XmxExW2YPs3iQQFEhlxoUA8Qms5zVkPcUPcziR2lkXhyOholXzbURgGlTdym_8lpchSsx4Gl8Aen0jftxFMK
0xNm3L93Hzx77-AePu4Spy_xZeBCoRt26IJvOiL3VrBzYfxBrAAU1Q6x1EfwgIS9-K0t8FRXHNeab03CMDQNeZqf0SMOX2h6_BoC08x5ueQpc20SBVfGYo7N
HR6g7WIgbviVPXv3QYR3qXRdbo3dQmUYnjLIS_6SEuA0zGOQLMV0yAAxWi3NGmHvhVGDyXa0hWJN7gMdKMgrrjKLc06HfV3XlnpumQwJ16LL1P3N9_KSXzN0
u7LWi7gE8iwSwLFMUpBh4mpN-NSu0v1rnDm_2NaV3nO2hGCKP644kqz7x2bSAr8niC-sIqRKaZIrh5jaUWglXuHxtlZnjHXPbOBtVJlafjrL3sn1O5K2Pmr6
caGwGP_u0yqDWUMXCs7Uq0FVR3xe0CzTB8rPFEk97pblF8c6dmf83ke3UKDu9YW7vmpnVCnSV4EX-RS8GDq55FdtSC86UVvTmaGi_qj-yvi_0G
}

EntityColoring(aws_codestar)
!define aws_codestar(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_codestar, aws_codestar)
!define aws_codestar(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_codestar, aws_codestar)
!define aws_codestarParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_codestar, aws_codestar)
!define aws_codestarParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_codestar, aws_codestar)
