sprite $aws_shield [64x64/16z] {
xP85ejmm30MVm8Bq_lTjhEJNYrukpu9C8odmxVVaF_zPildolEq2W5ekpvKcW4q945-Mn-GgJHhBYl7Mn7Atl9TUtMqUqoQM4qRfmMXYpYXTX9ACCQg9kNvG
EdjDd2wqgH-G75S1QH2jXhvMeJTy_N4Lr699w5Sgh_sxV3iz7tLNxlOLccE-uOIytu-ZUS6F-FwydoT-dlZvSJ_VuEUfds_mywAVWtf_i_mnts7iynadVfxu
-MdVPtxK_aE-lz7dwkTfFpeP_gnlGY1kEIN0btqdWAZ_sTodykt4Dq0y8ro1DlC9qK_hyAC2R8tzQu1FV87NLSJmQxLLsbO9EAxxhPyCXX_wNagKFpOlKaUh
nl3tfDsFckca0OPN0nh3LrWqPW8nQzJQeN94WqI44pHwxBFo5HjIQnC8lYNWjllLVuNAQMkOqC1LMG0mWvYQWsEa4LZCu3s_2Q5eGLtPwnje8ezhxxYR-UQi
mSrhjyND1E9nX6At6a7Y5iw0-j6A0iGYD3QcA01Myuur8N4JTCJYBbm91t1Tlfbxt8qrOIPYqJRHPgnQhnj_D_uI_uaN-Gu
}

EntityColoring(aws_shield)
!define aws_shield(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_shield, aws_shield)
!define aws_shield(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_shield, aws_shield)
!define aws_shieldParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_shield, aws_shield)
!define aws_shieldParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_shield, aws_shield)
