sprite $aws_documentdb [64x64/16z] {
xTM7hgnM38NXvUssxEJzdpURQJ17m31N9Ut-4chcevS__zNzxez_P5qaCydghss52jPaMFPbt2vtunupDnsOAQ_n061Pxvka3q3h0ZT8zDw02k65lMiVpwG_
y9QpLHpvoUFC1-AZXnzkW7B5Ox3t9kN01Iy6Z63tkf7khZH0x88VJGKWQf5Sod0T02GwztslBRxx-VYk3MTtSsGVj_gbOhgxpIMoUksgtwPZBRxtnBOyuxNl
hPuHu2_u3dia4EFNll1M7dkfFTyGFZ8ea8SUWxj-z2C30yX33pZhfw-j7ogGEl0Z11YULLszL3-yuzQXh_A1cGmpTpVrkty1piQ9xog63ZpJbo-oAnTvuEkv
dvgHkSHw-OHMGTWrVPtvMLNNKlVJby5hqgntNvimwcTFNwLWbp_zshclVFY4L5N0ViqJy9e9T7hMNeGSUvsmYkSUoWC_vQ9YyZCFYGDVYgmon9aN0yI2UzvW
HK6U-S5Kp4Jl_t-tI2XlFaMdrphrLSMmWLSZ0SEefQd8Jtv6CYDyAP8s7AFMJltEW2I4swxvDGAo3TzwbVVqm0kulu6bvARjRCqmaWSfWXzJY7ClbtNJPna0
zUIs31L0UQd7ypVKVCbq26QQl5pOOjQ61RziVVuYUTplVlSN
}

EntityColoring(aws_documentdb)
!define aws_documentdb(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_documentdb, aws_documentdb)
!define aws_documentdb(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_documentdb, aws_documentdb)
!define aws_documentdbParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_documentdb, aws_documentdb)
!define aws_documentdbParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_documentdb, aws_documentdb)
