sprite $aws_lambda [64x64/16z] {
xO-7Tjj030JtK1R9_tzm2Wi4ddLFH7hnk1jQpV3ZR-R3FyOxVe7jEQvuSszGynCpZFQ-9eTs0-mw84P_Nn7uT-q9YUR-yleGi36FDtk7H7E_S_vdWD7PZmtn
k1CGCuw34GTRG1SA_F6M6ctudG5H0kol3738ewKNGF6jEWCK5WqKyZq11B07i1cGUWWZ3C9yoy66djkpyn70-m5KAFq8q5P0wkDjWC3kwsCFO0bm3DxMnnc0
6k2CLwIIjWLe1l1MmEPb_a82PBrCS6BJrjyKMaylsQmR9M2-hQaEWMy1LeuDlMFaZt9jw2r_bdDJFmUCB-XQFsRz7F2LiTRRGuzBIUA-t3j6vYjqIacMUxde
lJwMNonBFQi-yG5xlVULlWRK_VhfNI7EAQ2-Rg7tgY-uGVpL7h2JrDU0PDfdSiN9AQ3mT6zIK9_FMgxsjFy2PnPN_wjvXz_9Pm
}

EntityColoring(aws_lambda)
!define aws_lambda(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_lambda, aws_lambda)
!define aws_lambda(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_lambda, aws_lambda)
!define aws_lambdaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_lambda, aws_lambda)
!define aws_lambdaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_lambda, aws_lambda)
