sprite $aws_systems_manager [64x64/16z] {
xT3RkkCw20DWOGCIsU__llkBcvuzMUwQkUn_5MA43__zUrzVsoQIjVqopOx1_1SZDZMWUMHq0tpxD9w0Qxj8GpizmlQ60BSxXzNs0G7Q7WNQ9_c6t9uvV3rE
zEr56SHkrhcGxz1a9W0pB9oZffSrDDN6XlWfpsbBzZekKjkv04zNypnUvtd2wpIUThg3WCwJvGOqdSrtE-cWeRFExrVi0EThXfYdAmTT9YIW-TDvrVk6OsNe
DUgAyNMe6qDDi6eFHEofAgcg6ZHfHAzt7IutH9M0peHfdnVr9X6p-D2rVnjsfY9yBT_HQHOwocp8W4de2_aH7pU-KvN3c5ovFu59dmnH4p9JFNCy_MBkRGrT
DUDlSmL8VWDqTpLaJUdrkDed4iz8DDLK0AbxEiAWKjuOCbDg2EUV1lJ82oNmk9Eg-YWL0EPFe3JWm4GFZh-xS5ti0tpa9oJ6GOdOczW6e5rG9JxazUYnZ2EF
PodLdlzHm7ahQ7WeSYqFz7lbauLJR0rsV7Nghg6rr09sXDxkJvWM4IOsCy1knj150V0OSsTmhKaSMqNeBctr01nRKGyu3fLQ7y3MaaV9RXdZKEi3341pIee6
x6LGozBGzbn82PZxPt6HJjBXcO6sVoRr2LAYOsWSzJCko3u4NtnzwI_z3m
}

EntityColoring(aws_systems_manager)
!define aws_systems_manager(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_systems_manager, aws_systems_manager)
!define aws_systems_manager(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_systems_manager, aws_systems_manager)
!define aws_systems_managerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_systems_manager, aws_systems_manager)
!define aws_systems_managerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_systems_manager, aws_systems_manager)
