sprite $aws_ses [64x64/16z] {
xP5Nbkme40KZWNJC_jVR1XMSKZVbnZyJ7y9S8Z7wuv_XDx_f6U7kaVrFkDsRS46glLQZHmEaD3LJhG9Kxq_RMK4qUX_AHvDMe3nPeUjOsy_NYGgjzwSs5viB
JnKA4flvCodKx7iKlDzZw7exDV0_gmySubvUXtu7H_9sgjJHvfRJaXrnALxPiKBRsojAGCeN1F2roPQWzENxUL6MwVU6tjhUBtvHpgSCeRKLxmwmveUV1feh
ST2S_kXiCBHFltSNsYnmd6PfFfCJMOdbV-HHg7dP3y-hRLDavu_PvO-29VApaSW-_5mxRL__4a-_W7WKllcAvTfsuhGS33yp2bL1njVpy0yCpMyuUksFzqlZ
ywjWkVorrHax-SunT3yoz2L_25Suw0i-O75AG-2EVveCeBGlr2lVTdvGPrVOidp5ThwihazCCFF9p2kUtod4avD2R7n5d_ETcXkS4a_v3TtvKV1v_uLWFedr
AsFh6tK4SVVzGsaxVtWUcH5G9rTTmUAoAhU48OTVObA8IHj-rFFsSKqLZm-GdL-nCIDn7nKezjNt0hJHUw13AN0KC44FNP0ADHuYdwfIZYi3nKUlZY8U3_33
72iLKIrZqp9CHL_mnsTyfzyU-p5kt2WHZgntLug7WSSZ34IGjRCVtm82BHvZPVw_XgWTzm-lWcWyWtyGWmfGVCt7YxZLgXv_0VVuV-D_YT_4N-GT
}

EntityColoring(aws_ses)
!define aws_ses(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_ses, aws_ses)
!define aws_ses(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_ses, aws_ses)
!define aws_sesParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_ses, aws_ses)
!define aws_sesParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_ses, aws_ses)
