sprite $aws_appsync [64x64/16z] {
xTA7qXiX30JWbGJIwlB-xvi33mxtvyTpPLhAvmfeQVQFlzD__srDjhTRsVIY0eXQZJR7zdtXWYlGmYfeZDiLBe1MPcza507iV9eAbEE2eUVp3fJSRgj0R4_Y
mWTn_nXtwvUwHe3RcW8GgykIDFZShghpLIO05S1MUuZ3K1RiDATXGKbwh9RNm-u9PHhgD5zC5Slb1qVDZR_wKf6zRw7DFs-_JPUECle8pOIiyo8vvrDX1l2T
jvffOCwP2M5vK07ytkUvuAWvey13m9m5IXwifowehVDOJsWk5CHn9M7RXF1Utk1Z5nEAdCixD1j2U3RlxwfI136whVYPV7tlrB4JJWtZn_CVVneAgYigcz5u
5naNUKAP3BvgYA4tTFgJB50HxH1iUGOWtQkXp8Q6MEPRjerJK5p6_aTZN1zp9I1zdFELVMqSZy-XVpEKlb56BSxNwDpeH-Jt75egC7QzBE925NJ13mJEfQWc
47vWC7uMmRK2uGC52DvdWFCsLyZfk5jyxG0iU58Oe3M2qU_JYm9IWwT54G2YjbD1durNHFH5Ez7YmSjYvxlOyPuORslnm7__yQ6V
}

EntityColoring(aws_appsync)
!define aws_appsync(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_appsync, aws_appsync)
!define aws_appsync(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_appsync, aws_appsync)
!define aws_appsyncParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_appsync, aws_appsync)
!define aws_appsyncParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_appsync, aws_appsync)
