sprite $aws_msk [64x64/16z] {
xP67hkim34EfBVd-__--9cxIQJXDCTuwc4Se7OBz-MlvptzQQz-adI7vHHmWK4qQZlXfZ6m6QoSfejOIsiuYi1345_a5FnjtYAa1UIwUe5fVuNFhCNnRuKpU
8DlVW3pNljHRQ0QuJhIFbj3-3EpJk49hoGloOeJuB1_hzWd0QzVZ526kUQkjpgVjM-yVjJ_uZdeXqy6rqFVBkX2Wo3g2uaBqF5iP-tuchoa6afv_HBVx14AM
W_WPq7BNUPwg0c-WEfHNi18ydn68qe7-oG1qV9_Z7lM6ZEq-9qrOBE-Skn_3i4B-x3d9QLPbAg2HeS3krjsw-w0rWTIKG96BEe4V75VdGOyGB4XspOc_a1bk
7dcbQlNCkdfk_f1v9PG0jZqOqlqW1e2MHEmEtdsCasVskTUFOk0Sm--IC86ykwwELuzH0GP04faP4nyGiVvOcOZjpkd1J-n7H_RZRI-D26UGn-wvUGptKu15
2B1uTEykku-ACow8FtbSDNOV4U4UCVM_YVYZ-Kz-oIy
}

EntityColoring(aws_msk)
!define aws_msk(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_msk, aws_msk)
!define aws_msk(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_msk, aws_msk)
!define aws_mskParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_msk, aws_msk)
!define aws_mskParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_msk, aws_msk)
