sprite $aws_secrets_manager [64x64/16z] {
xPO5UYGx38HBBFdT_xmBuuuQFcyyZsd_a3fILHa2yykVnqz-al7sgClekc6CD-L3S3SOep887ZN6-mOj3Y5y85vdf_O6evG04dE2s_SQaaVBa3k3OG1PZcym
nZVA6T2QBSfnrTmGoEip-PX45mogyLrUOyrf4BgQCHipVMmDrhHyPx2Hls-GogpH7TtB9Kw34hpWLjL8-TJ2e2-Tr1X5uAWA1Q8773n-J87g5JnlKG_DzSwa
pHOe_5Zd60c-VtkIu5ty961dgUVC9mjmsFN1pqoz-lP3qzQvrnVHGj-TZRvJ5YIaUYeC6ZbnI9mTWzTewYHWNGiUK8qUqrhYyAuPebU0RYMa5WGJYBtrrToU
anbWMwL_n-xppg_H24Al7i1o1scmFFFoOzZcbwn91YHhXSFghbTuWYjL25cxyml8GszG0_Vp6RCaGGzz4e2O-s-z8cfDXtIPXAZU_sHQhJ3OLTzVK-JK1xXM
p5O-z3uTivUMkjx-CUMjzxX2hGTb_GW7vuVJawoSyRhM7pBBL-7om3A_2xtZLsIGPhvocaR1cNu4D8ivpJKCpZqAYet1NhunsCZ3Su5x6spI6H8vYIuKY6cm
awSp87wiU6OhGBRRGlJUxNZv50Ht4mAWiJy3yxDaN62B3c5mv9u8Ls60HIrQyAP1Un1QsmHJv9kenCesz_JeFvluNVmaVoTV0G
}

EntityColoring(aws_secrets_manager)
!define aws_secrets_manager(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_secrets_manager, aws_secrets_manager)
!define aws_secrets_manager(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_secrets_manager, aws_secrets_manager)
!define aws_secrets_managerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_secrets_manager, aws_secrets_manager)
!define aws_secrets_managerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_secrets_manager, aws_secrets_manager)
