sprite $aws_glue [64x64/16z] {
xT45WXin44JHKcErSl_xHYilasVQuUmpmn_Hjp_NbozqzvZzNh2mdKy13PmtzAcVzlDpYeMpGKKa9YCYEpcno6mZh6xhnNRlPjPOGM7H6zPH9EkkruISZyFT
L2G9ZTKpwtWTWWTHMAG443zu2GF4F99LgyY8u0mJG0vTe1JGoDhMnpjasC2eWqTtCOPiO-0YvY7ba31zweQ8kK9h7bE2h5SumFcEUazYFApzuLNXTPp1weM0
r1dZvGguFvyGa4_cSy2BzIO6wvINCnw8EiiXJs-rJgCy39e0wxo7Z0Al1XgKbuMmjjOAzaRs19GC6AidBxttUuYCptj-nWO0JVusIMQopU49_KrzxBtVPs2z
mPV8VGJiK8mWKo39ZbICfEwyVG7PUVy2EszBstbV9d-k_AjzuOs-0m
}

EntityColoring(aws_glue)
!define aws_glue(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_glue, aws_glue)
!define aws_glue(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_glue, aws_glue)
!define aws_glueParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_glue, aws_glue)
!define aws_glueParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_glue, aws_glue)
