sprite $aws_kinesis [64x64/16z] {
xPC7Zbin34I7dVov_ttpLR1maJUsd9uy0EvFd07bBz-N__pdY7pF1n-_r2SwjjtJF1ZrWd25s_cWY6CJHXr7G7TzGPwFXDhq3TvQG3Rz72PlDs34-LW4URL2
PNiCK1EBGVvYzR4r1VS3561_9OEFpYMWVb0A0F6iP_C3USp9sgnA9G0a5bbrrBS3q3WW691eIeKnEiIYvj78p7K01Ot6vGoGUbOZNOLm2Q-pb07SvhR15za7
6U5cfYUszaToic7SPy-ioOLoGmWkelViJBY1wnFI62FwE6HcRyb5kAFrEUcwYfxjyMdIJQ-Z4z5pymSPTujRzryNc2OnYywhyro1K1vYip8hipsSkhjfnnxB
QGI0vmARP_SRf8UsDjao7vHmZqwjSG8qXcmoItZae7AKS5_xQO2CHN_Sme6Ry6K7okLqmBkTqkGnzhg3w8cPByVJr1qWwt5TBXSngSobxf2kAw3zLqRp3poe
9Vc1ejSrZ6SdG3oVnwqznjG5aCZNOTZGoNE300sT8tSmQAi2sjDJUdjgZrimeetdt4HQRuNbP3_4Fa5l-g1Vwuk-vMUyeCSVpN_oJRu2
}

EntityColoring(aws_kinesis)
!define aws_kinesis(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_kinesis, aws_kinesis)
!define aws_kinesis(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_kinesis, aws_kinesis)
!define aws_kinesisParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_kinesis, aws_kinesis)
!define aws_kinesisParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_kinesis, aws_kinesis)
