sprite $aws_open_search [64x64/16z] {
xT45jkCm38NXArbmbTd_VkSuiGiF6hV3y1TCvoiaNtxZ_lU_BNnKB_d2pBPNFD7OYvUzRRtwn6-FctwEJzVT75r7yPh7JCzKpkwzrjwfJyooRlnqfpxGecS8
llUru6CVyrkzvbOrVJtbP-C3okB4fuvQNNsbDssMDTsdlWopdBvCC39MGMluMl4L0h5aCKs0ABLrNrivu5MLcLLZiQrwhmf8LZRqD2i5lhEwypMxzOae0jdt
rDmKi6EZr_srZtnVDaGPv22fQ1NGTKze1OHrH4MK8fUz8qgGDIEa0dPC5xo2YNPt71skUX4wegu5Z08kUa9eoBgMQDGdVTnvM_MT2HZmkkPmYdpkUUVPa8Im
PbHaejMI7vUhmJbF7Kg33yzJJm4JS4wE9C0rpoGTZG6q81cjRpQWiOgdFWDEAeof00I09WsgVRptdDtus7qA6XbDH5gG3PB76o6yzgbdAiHvv08Ozqy9UYpu
kQNDJ04qWHrRKvzxfWbwqdBy7phWPzxXd6L4v34xBfy3iUX3dRDnGP8CwA9tUA9nBvBZ9YI47zGU-jZ7DC0KzfJFuVDoI_83ddVUiZTyRtgc1tdgPnuOJVzf
hdAa6PTffCh8-RYyH7uqJVw8ye_kV_p6lW8
}

EntityColoring(aws_open_search)
!define aws_open_search(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_open_search, aws_open_search)
!define aws_open_search(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_open_search, aws_open_search)
!define aws_open_searchParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_open_search, aws_open_search)
!define aws_open_searchParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_open_search, aws_open_search)
