sprite $aws_kms [64x64/16z] {
xP47hkiu40HxcAQRU__xhXY4voGh0H_9XL2sf6Byxu4VFtxKMYNLUh5M3bYmn7ebpm12Ii60L8y4pqHOKMruG50zIKJyQzBf0Gf2VI0XdSfbK7qaWEUcpzqv
XDG7SgHpk-VGWgaloCxqrYD7aERM8tGy5q9JWZ_yvgbUYp9AhRpGp-CdK8gXZ0lGgVFpfW9WR5ymLRsnrJkYMiMSNMEaf88tWZOtC3ff_S_guHLWgoymwkzl
HFwq_827BUY1gWJpzJSZugAF_IO9IDG2io4kFjch6C35Yx8kz6A4Bu9H9MLAcZxOAuq-A08mr_HZJsr3QpqH2a9929e-sDEGrFi4R_yqpKCz0o97dv586ASF
zX5hJuC1MQiFzNE0tdk0PKhJHyylpFCJ6zBmr84-elIUEJLKkkXTljSpmRZkly7KvQKhIvpzPkwBMk-biOf3e-Utw-ViDtZk-K81SlFS_oSC_481VFI63OpV
Y2YjDthPm8_r5ya8Jh_UCo9cG-9b0d0dfniox-3EVyCFlyKFtkH_
}

EntityColoring(aws_kms)
!define aws_kms(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_kms, aws_kms)
!define aws_kms(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_kms, aws_kms)
!define aws_kmsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_kms, aws_kms)
!define aws_kmsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_kms, aws_kms)
