sprite $aws_step_functions [64x64/16z] {
xTH7ciCW44JXWgRZtF--WtF0O8G-x_IlwzdAVpzpEBYgnt8TZAh4UfwOCoZMSaVoY21e35Pz2exAK6B1_jwGeogGM4CWjOBaiSO9LR9OfWdYiKD6R6NFCjIU
JDsr0Owl1Bbq48fFzE8TDkpjWb5w9plgNV5EcZvplvUcluszzTHTVUmdZNj9QF26lg15Cxtq--8juJC2yPdujjxEb57KpYRwrUEdcPv_sDjypvYw_zmTMSiR
DlFyclSPlzr_RjQQsPhiokrAm7RnVkIk8FkAmTOnsMSgdz5CBnWezfqyIv1djf7MtjOLLAJhUIeb8TiQHL8ppM1RSlsI26XlhxP2BiTFgyTVoyn2I6fhDADA
CkfrY8bOjJSw76odVm
}

EntityColoring(aws_step_functions)
!define aws_step_functions(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_step_functions, aws_step_functions)
!define aws_step_functions(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_step_functions, aws_step_functions)
!define aws_step_functionsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_step_functions, aws_step_functions)
!define aws_step_functionsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_step_functions, aws_step_functions)
