sprite $aws_backup [64x64/16z] {
xP5Pbg8X34Q_pC7Q_twxm1mvA3Rstw_U6cJ8JMBuUS-NBxVRCU0zFxSMaRyVLp40a7PLTv0PGwxwZ1p_BpRGmFr3aHTzebvPhjOFG5jpm2zLLu00N7o2P53q
799Z-Uylhxz56wF_hzt7f81y2FLuGU3yD4DpGCQRbL_JiFQPBfYXohLgJf0yc9srrJPNzoyrM9qwQw4ifkFHRtLKrCO0TM7nkbbn32ZQ9DpCSsuP0zte2NYc
m6hlsOmmO6z5W2A34BloEh9mHO8P47DNdWKDFkvqvu_AqmSaQqsGDb34EpyWTysoV50hak_9dOTfO_SCGqm9LJU5cRCLISXMbwP0RlmOrnPAcsk39a5Y196t
BQxGNZfshqCPUUzaFkWkgktXQYh0-v2QKzJggKYMdmflRqchwTU8DtuDPy_ipg6v-EKvPE_FiDqaiX8d8t8rLXJUFreAB1-NtHld0PgdEnoIMP4nZmrSwIt_
3kZH2VdK4MD1Y8Cly4S2o8XsHXqwE0yOzB4aW9W0SCpa1m8qDzPj4b_k3Z16iOSJzL6z7L7Oww0TNAcFE3Z2iOO6GoF0UIO88WHxFUqvFl81K3oToZZriyuG
CuR4WWDg2iJH1_Lum1OO5X42Y-Fu94ONpqHasEi4uecgJz05WbVz4_llRo1p1UA8r_oV47GiFa15Dd4ceXuBNxxaV_87
}

EntityColoring(aws_backup)
!define aws_backup(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_backup, aws_backup)
!define aws_backup(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_backup, aws_backup)
!define aws_backupParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_backup, aws_backup)
!define aws_backupParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_backup, aws_backup)
