sprite $aws_cloudfront [64x64/16z] {
xPQ7jlGs28G7qGRd_TytYexliNpPbjx-Rok2OLIs-AS_Xn_yu2WoCrd7Rz0UQO8JqVXrFGxQqfb7kAi0q3m-LfS2uWhuCQD9nG36XnqENxLp1G8x3YRdsu69
rT6hlrCAYMCoKrwvvbuEzHmG7kyeWTOL0UO3Mcl8WNmlzoqqn7mUE7q3oC_bIrbB5cUS05_f5NQFLxbThWcfvtA7ti9C35OiJIlfyDxSCKe1t1Sz4CzdlwTY
7LUCOMHsamunhc3VgX9i4eC_b9SYjqYso65Rfa-WZvV2jqZ0kq-d0dOgQXAwcrovIUx1WxRbOrXT9Mq2qXTmRL9nO2AiFUdmsfnu1LyGenOA8mrQavPTEA8Q
YU4sXXUa9WEiYtiSy6e45bPOJWhU6lYcITWZ_OWagmHPHGY7E3UDljFxrnin4tWf06ETG3xKbmDO5NI1n7q3khuFCeBdEmEKvx7aPRNf-mc5xsq7P0aDyVBy
267TdHOqhFAqhBeA6XpdA0Mi7GTOp6JLLT2WmxyMmdicd0P0eXRvlU0-dD3lQHf45SWpSDRZ1R3MxZOz94c7yff-Wu6LZ-RFrR8emhNEFSyDGP1CAE-ipXC8
YnGa7nEGLJPQHk1CXP5SpuyvSoAzCo20N1wFIO6J0zaRg8YjnI6uqNrYdKyZawcv35xXW0UKZQ5q3EcBxmqCqkqXfA39Eo50NwF1Kvly8Jc0aVbzOqqWmOzm
0JIk5fc6YIK_94q03FEOk9qNaCcFoNGLN0nlwhSTyXVdYNbaKt_OukHDqR-N7_1tyZC
}

EntityColoring(aws_cloudfront)
!define aws_cloudfront(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_cloudfront, aws_cloudfront)
!define aws_cloudfront(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_cloudfront, aws_cloudfront)
!define aws_cloudfrontParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_cloudfront, aws_cloudfront)
!define aws_cloudfrontParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_cloudfront, aws_cloudfront)
