sprite $aws_eks [64x64/16z] {
xTE5akGm30JG5hNt_l-35-IKIZVbdJWvXXvmm4zHwCilpijVdF_Xns_SrI68bu34BKq5uEyUK5xMmm3rzAQ0ZSkjIuo0Zq2C4C3tAmmUHvpUtxSue1pxhUVa
ybLoR6W7979Y-O_idSHWpXe7cVvOgyfFTBN-wFlkazPh-l3qrhR4RA-P5irz5HeGWtd8Ijw9iGwaJpoQcLU-bnLywjkirinikg8RtglhtikCdFX-mDwESjFN
9NFcQd3Mb6slFCOF2CJXMEE9jne_k8yjpuKd9Vab7-bpfC1umtEEgda9Rdj0UCNpy5hUliaBuFm6Rm44wxqXZt795rxfLO0ASLxrD0Yh03IOVJppd7wEf49d
tsG8O5zxLj9dfgjHvX16qW41cbbxY9EanLmFCXI0PJkdFYThshP1390WG-JCaovPeMblPSzzLIXT6-s93pvMyAahyoJM4S0UAwHkSG0BNyKVsZCnBaxgiqHL
MEJa-lLhlRLddPZpOj6P67SI_PhtAnFSJCnR5-ohiSixkQeh4PQiNuxB5G1yQ8lYDogKlbCWpdJyqVaVVcFU
}

EntityColoring(aws_eks)
!define aws_eks(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_eks, aws_eks)
!define aws_eks(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_eks, aws_eks)
!define aws_eksParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_eks, aws_eks)
!define aws_eksParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_eks, aws_eks)
