sprite $aws_config [64x64/16z] {
xT5LWkD038JXKejAtllVTzKEWoVEm5l-W9k-uBzVwjEdPKVRkdnFtEABOqzZsVR1L-M3Nyuv-hDLPlPbLjajXqEdORNVglso37Irp0mTZrjTzE0hRqT_Geek
Bzx_tESVUH_eHdpJ5uxLIqz15tNdbTruwPauf5ETFJ4y8kIr3wYv6SRqRtx-MdrK5U_yaWftQ2xJrxRFmDgrhpbqCE7BIqyzyAXRRyZsFUJNVgc1ZfFlz7Ng
nbTnO2PMtT7NwhSoPAr-NYlRTf3gN3AbVL5qjpTs8dMC6spJYtOuUjVEt_A7Hiqec76_BohIu2mEfKCo1umckTENWZ6oEMOw3ymaz_lYv3fWMHrTn22votFw
bRDOnqWwXCyu7tskpuDzIJVpd2FxolFU5m7ElJLZKX2ruUF1azw81l5C5pGEABdJimcI2Jb-T20f4EE5dLkzYSXWiRD62b4o95YaDn-a2OJdxlnTYkIvTDEO
rqtFvpxKWkUslUTjqulDPy3PXVJ5nvQ_By-_63H9va2G0Wm-AVI-R6Bm14x_dvA1aTnVGZB2C9kS0y4tqlOaqtJO2iTRxvy2IqwGnoS7aliBWQduWSGOpPtl
589EZ7J1p9Dl5IAkG8HW-7YNTvbChEMCtoXLkl74vgvukjpqwHD_s7y
}

EntityColoring(aws_config)
!define aws_config(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, aws_config, aws_config)
!define aws_config(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, aws_config, aws_config)
!define aws_configParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, aws_config, aws_config)
!define aws_configParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, aws_config, aws_config)
