sprite $babel [64x25/16z] {
fP85ZWGn30JTrORx_uSFacWqnrHBMO_AfCHlqJD0nbl4vWiL382dMn_AKBvYrlKa5I43cTrJkFJExcSgWTYGX7OyxGYWfn95I1Kty1YlqAwrJoKgAKiO1rJ5
1ku-FORcj58x25LJq2lg3DoNaRviTMS8UkktmwI2ylepYEQQj-D2tWrnh8TzAE-PUrL_S43g6OZOizxXj8cN7bHJYi0frcnil9ejtkgvPY179ntKxWSRLeSz
NNMQUkkRXRU-c9MtfzAag59iA7zqzRBIi4PqzUweLwUuRpNrKVcSIMmMDGcjioV1cCmuu7nRtfESHDDu8aH5qDhRvpuonTR4jNoT0oCnU_6xFDGeJEx1Kf0I
c_8kNvTkqLv553IGiv8SSgRiN9-UpbjviQz9rjaHPDOC4KhNFDDT2bMNgzAAXRQ1LwDYpexqufnHFONYOs1fMLCHqYo3bhk9E5HyXd09Pu-NboleZkYuKCPd
W5qraoVR3bR6pr1w7jQOTpoAdz4rxNY3kkE7wADEvVWfwlWNJm
}

EntityColoring(babel)
!define babel(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, babel, babel)
!define babel(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, babel, babel)
!define babelParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, babel, babel)
!define babelParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, babel, babel)
