sprite $backerkit [64x62/16z] {
fPO7hWCX44Ff2wpd_jVzQd4AQy47gwKv3qRs96vHtIZa5OFsTtVaHpppN-x8Vxj3lp_pMptq8stwZsxGhRUNqfO_kXDrdFaR3lcMJ-o5Oz_JRMPbtvwndroc
Pty22QpUbXgJlwM8_sok40L-RNKbeFry8LYzDlVt0LEDGfZVzHVZYLzPFct0N6Rh1mZunVZRgFdshWEc63LVNW43vWi_Qz4rO3ACceQOToM6UnTO-FKj0oQz
R3NRFCJ44qDyv9kwHKGGm-OqpaQ7c30Zfl49SwXRnBiI4xwAM_dE14zCvJ0O3XbYtfMgFF7DRkWMyLqAdM7u8S1Fy2BptNIBgadnqmcoHK7ZuSSHbx4vKjLH
MRN8G-F3Gy6Gb_7jiM5zAAuGud3EiKLb2Qz3hF3aKE6fHHccr1sbGzmrFikM8eZYgcqfGznCgeZ_CWpnl3bwIvOblDxIzxGvhJweqP2PY3rr9d9FI6pEdZgR
itk0OaVgjvsfsP7m1m
}

EntityColoring(backerkit)
!define backerkit(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, backerkit, backerkit)
!define backerkit(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, backerkit, backerkit)
!define backerkitParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, backerkit, backerkit)
!define backerkitParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, backerkit, backerkit)
