sprite $backbone_icon [52x64/16z] {
bTK7SiKW30HGqq6WV__Znfh9fYpe5wMNDyw6jIpf-d12VMWF7v4ovF7GLTyNkOlSvbQpl2UY2JCs-awiq0p0c1hnXIX3oDogXMT1J90njDnOoOAGWPhv61r1
oFYnGXtY6Ox5GNo3CwOWlk5O7CGtEEDGXORC7FfVzK91McCZLnBz6shg-YjwkifchEPJGQQ8slll6NRQzM0imO8mWyz63TVHeEsAlqaVDcjAisDsZGsI8fsE
SBc6pr3nerLSmsUeTCOdmsLKhcxbdyXMHkNg5lx9tCgeN5tgZauMBSQkMtTXIA0fzoGvAxieYv5nM7ageNKhU_Ttq1HCNNkkGn1Q1tkiGn2UE4Zz4uC5Oebh
bZWcjAb7Oz_M7hrDlNGtwcrjT6egcybRUrzmwsIW9DEcTWrLdpRrSuDO2E8RhkFUsp7Pj33qFr4mTAfj1jN7HKHnCNJgOB18SNFWKzmS9uFgu-PGL7-KS3a6
TUH_Yk8HvfXGXGmUHgwnCku6rTqDodZUYTh2mQ2Ckq5rEvbz-k1cw1E34yb2oZLu5DgKfU-Q6duNWRvbMgH5vHf_mUrRUu_EW-gouKtDKnUPSv0dMziFmh66
ag4WDFGm-Zv32kB6KXYAxWxE-7dqyyF83-B7-W8
}

EntityColoring(backbone_icon)
!define backbone_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, backbone_icon, backbone_icon)
!define backbone_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, backbone_icon, backbone_icon)
!define backbone_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, backbone_icon, backbone_icon)
!define backbone_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, backbone_icon, backbone_icon)
