sprite $basecamp [64x53/16z] {
nPPNaiCm34F3PStz3xmLGmqJcsDns_lDF01Icc_d4BryGdJR1dAo6P7oWkOseBaEQ6m3ckjWheEv3kOwcEjWhFVlGkimbu1TtSAb3UZN-zrLbRihwDl3j0JG
fkwgJK2_NYD2mGguN2-1zJM0BjPpvFeQS5ZFQb9zN_KrW0xgHSt3kDuTwfFd0Qb_5FdTkTmTwXCf0r2Vkbf41aZK-XhmK2zuEH00FVG9n5EfPmKU2D1Owoje
BFMgmA1POFqpKloo7WCIFOJN0QYinu34z9WrWB8-yKO7d7wjhm6kf-00yFK1xzjLJU1JrXVCtQ5t0x9-7ra-wmJ-F03g1yZChpT0cFy_FX0Rs2ReVsTUdn_V
RHWVG0JOtdZewqbJT0T9FGDuQplqyWl6Sjs63kXwWd3_1yWiZGkvs3K18ImVG7k7Kwts_Fbh645qQo4Qk5r8hxu1
}

EntityColoring(basecamp)
!define basecamp(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, basecamp, basecamp)
!define basecamp(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, basecamp, basecamp)
!define basecampParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, basecamp, basecamp)
!define basecampParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, basecamp, basecamp)
