sprite $bash [64x27/16z] {
dPG9rkGW28H5453g_kUTODlZY_-Uoixp8uLRUQkwkr9vA5AhfOZB8tg3pVdlD7lRPTXVYo0pEhFzMiln6Qg_n-qpIxzFu9zxqkpKrfgiHDIMowhQwFeMcL7v
XES1N64Af9moPeZoUbwALWHnnNasFBq3RtvuNoq6a0OKS1r0vQ_u5jYy915bDaHsL9_j0_O5NpjmvmsnRCVaHqvJ4yxFaoS3Rlpe0sZpZnfP00VW6H2Wzpvk
F7KSV2fDf5k7hRv5IE7TS9SE86wyidG4PH4sC4gABG1cX8ZeZSyl7aVz171PMRbuZYOD-Ah_v4NYu6KE5amrOFGQXHTF7_dEYH_ZtujVrsia3UZM0Vc2ByMJ
FkPVp36e0LxpJylYu_0Vei00e5bTYkPBIR5ayTBcunLZ5jiymdb4Zkf8BA_tW_v_xXUYjNLj_wI8UA-P9gfIghTBraovLXLHblodDbNXoclhNFv7UXyhOIKM
pfKx9LA9X2z6QevBnl9jxtcALEYp_NVnNiiZDQi2T2vFLSt70-l_
}

EntityColoring(bash)
!define bash(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, bash, bash)
!define bash(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, bash, bash)
!define bashParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, bash, bash)
!define bashParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, bash, bash)
