sprite $bash_icon [56x64/16z] {
dPS73hCX34CJ-20Xzlsl-uyEf8w8Whl7eqyCoPKasWE45TbB0yDz0AORL0sEAlzIZ6Y_Kkh4DOSOzo7MwK3N5sNuMlOAZY8lKSDAjap5bvJ1g0l5H0DqpHMz
f9DbSynFbm_5vHVqLJ6NBVaxUURe-NJb4pvbUx8ywUpTPzPlZnlf21NfxBAP2qCANBRJs0nbbofNZN_PfPm4kAlPmNjiXwf1xdFgv07Nm0Ek37AVqmuUS5UG
-rnnye1hu05N1xdFgO47t0NoW3FoXEiyuWhEkCuppfxVi3tEUKj80uuubNR0zQcynRb8w_kUK0aUpCkGYoTSb-839vmSpKlSdkh7ByPOp6VqLaG-E8Vct2EO
N3nvLFOb5rBlNtPxSbqSTS6XtfvYcCTp91KDj9mZsgMt9OJP0ET88ZeuQihvym27OthNsHHD4ywqt7VCf62QDyN94V5oYcRBJ6hjv0Zdp2mzIQsTt6jUYl27
RCfvoPjYJRYfkAwr_ghuSrFqH75LQprHNDNQdYYk_deKt1LrguJ1sY2JhRjg4D4aoLy
}

EntityColoring(bash_icon)
!define bash_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, bash_icon, bash_icon)
!define bash_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, bash_icon, bash_icon)
!define bash_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, bash_icon, bash_icon)
!define bash_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, bash_icon, bash_icon)
