sprite $batch [64x64/16z] {
xTHLOi0W30RWj11Fxd_SkR6-8FFnFLNuSG3qd1OCc4l4ixLjcztnd5S0WBuxl_FEjPJAFfNd97Y2CTD-XHSbXlEjEfKlOgO8zsGYJ_b0uSuPmtdC9mHtT3H_
H3vnk4EZ-Tg-beNzX_SJi92dWGbSRtzz_ElptoHmPltlS3xWf_qtj_-bpkt_LltwyqyBzu-fgZVtt__Yvk-Ovm362ye1WdJnbUsRN6Z-ETiMkOPpYO4inOzR
}

EntityColoring(batch)
!define batch(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, batch, batch)
!define batch(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, batch, batch)
!define batchParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, batch, batch)
!define batchParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, batch, batch)
