sprite $beats [50x64/16z] {
rT9NWWGX28HXIWGQfkz_tKrEZjRc-P_zp7MzNCAQNEs66Ch0Y84SZ1YciwBI6J4AiAA25kMqoCwAIh2YWXRPM55EYmGjb1Nbj5XeaRm0BTel2D3YyxUxFcgp
6S9dnL1LsGdnOHAaM5DOqLcHmWfbHSX77uxPKtET58KXB09Jeje06X4s8n838DvhZqN8DlyGzaYaoZQB4TPxBIhd8FJs7ryCSWd2slK0EGeU-rmcqZXE7jOi
23764mBgSH5krRHxF4r62wK5M632YiOA4rQ05Lr8OK8A5r8uI64YdEZ22ODGmfh8lF2kaEDU0G
}

EntityColoring(beats)
!define beats(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, beats, beats)
!define beats(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, beats, beats)
!define beatsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, beats, beats)
!define beatsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, beats, beats)
