sprite $behance [64x12/16z] {
bP07akGm30EXd4ZY_xyzAjo6YZkOO0hkBblYYQq482QFNumPVysMZQG6e9kPna_z6MCSF4g8CNpy_04W7JylrN6UNuPgzxwAcJI4EVEypRwkyeOPGQwKyk9o
c5IZ1lVDZ6pev5e-XDTqP9-Kh2XsuCWRAt2e0elT_HM2S46q0TDNhn48Py2W1cKzjqWTOmWj5rgjTLAIiG3TQOIOgxfxckQtoEHjtd2hTP1t_q4v6qaZgUxd
wnSnp_7pyLsBs2aFVZw4KcafnfXI_E_xC5AO_FRpVNwhXPOFVC-l6QVJ1QZIl_nydYRVlWRTZnjKP-g69ryqka4Hsg_dInT-xrzH3-EhTk6YjYCZmW7pCYEg
fhrOAERoiELDteq0HKcj3jSz5Fm3
}

EntityColoring(behance)
!define behance(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, behance, behance)
!define behance(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, behance, behance)
!define behanceParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, behance, behance)
!define behanceParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, behance, behance)
