sprite $bem [64x53/16z] {
vT57WkH024JHWFGExd_QcVO-AKbishpzbmdqlO2JVdhVtcFyCVETmN_W_lR__p7Tq6eE1_OthKgU_euaLtydOsyPHFI1C2uXubIdgZOuXA4BBaK8EzLIKcJS
INHvVrajUE_NdBrMR8dfgHTiaOKvn9ZhM0GNRnwnbKovrDgd2FdsN_3rsTMlXAkzo6m9bcW9JBXN2GxKnT5p4Ml_O8WnjocgMdptM-Jg9S3J3yRrVlK8W2DX
8njIP3o8AhBcbt38q1qSa_gIB-68M03GbuxrEZF3OQYghElxqNJkXpn4l_8V
}

EntityColoring(bem)
!define bem(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, bem, bem)
!define bem(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, bem, bem)
!define bemParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, bem, bem)
!define bemParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, bem, bem)
