sprite $bing [51x64/16z] {
xTDBUW9H24HXuB3_BUT9h3okqZMEDVR_3cetbM6kmLNTFSeXeqY3YAL31jca_prvalH9KUbM02eT4g0Nw299-dsAxIJehqaj9CT8RKGPAN8XoXnY1wBCITqb
DUQWE11bZZiJPVQ913ufS4aaO9111GQP2Qr4IsmIXK4439BGo_20YC0-oWGDDr3t0ST6yK3mI-mWuuVOGKM4n0BcCoBa3iWOSXEvWTa8WGStYS209I52HTOL
859PbsuIeVfIGbDW0Lg2STEiC18AxM0FwQOzfCGwCC2ik7gJbc0a57B0X2hslG8
}

EntityColoring(bing)
!define bing(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, bing, bing)
!define bing(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, bing, bing)
!define bingParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, bing, bing)
!define bingParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, bing, bing)
