sprite $bitbucket [64x58/16z] {
nP5NOkmm3CIWIabx__E-NcAFkP735Fn3PP1j1B1YuskneDzYkjMOttFCRodc5s83Pdh8JuG269JG_10AK275vWSBpKyaW2MWXUQ76fe_5A31TO1smLGgN0T8
27af6Qu358Ig-anm7Q0Yj0iVd00TmTGtS08Omb2_WmJm1anJ_GfUW2ppgpyBU06gp3-z-Q5j3DZK7-06C9b_2iOVoiQ0G_qEVe1ydb-fu0Uev_cLyinlv_cL
17u0Eyyl3DWDuC_l1yXRy_i1oc7-uSpl3sZj1LtrKPxxynKE7-mtT9qVwewkysk0VJeloFVz2ZBW7OhlJy6VNmFCnmuh8G5KzvaSA8xkCk0omDhqEmUItTDN
vOWvkkTdZdJly_xy4c2knzhZCK42pBNF00cmRj0vO-iELVmqtdJzTm
}

EntityColoring(bitbucket)
!define bitbucket(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, bitbucket, bitbucket)
!define bitbucket(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, bitbucket, bitbucket)
!define bitbucketParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, bitbucket, bitbucket)
!define bitbucketParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, bitbucket, bitbucket)
