sprite $bitcoin [64x64/16z] {
fPG74gmm34EZmlsF_0jCOC6nGz6KRNbUoGvkcK1AjYs9QCz4-Q87DI0F9NwXL_4JFQz0JoMy__FQ0drJ_8RR-eRR-eRRYlYN0YYEGVCcbgsMJJa81ovdmbPy
P55JznrSZp9FC3G7QWSvFbJqlgq2Lh2dI19CfWCfouWiFU_TBuNq-RAXafYtdp8Cpt32enNtHE6xSBzEgrSnWBsCj8_mTnxXj04lGtM4Nelr0hhmPCRp1FGq
lF1InlVuvtBqDUOorX5_EuReVzKaFdI-3BxBitK1mFu-7Y_YHqKyZny5Hzxrz8NMIlCkuzjUpAg0vzEtcHTGFVt3JZ9-HlZOV_J53mEFM97IOVzi0C5-Sp4v
N_i1Xpw7RyuBwpJEuD-jiReueFIxItKr6ooPQBcYsVZTOcKrDEhLS88AxBZxXwbeZC8PZyFlheAmrlMAxPiaUqYZ0MzkjOtCjgiT4JkWxLjUt8L3YO4Eebev
hZeZmZr58hP3JBS0v-vRdj9oxhukKCl9rVwmtlq9hoFKvkifr9qldv1wxgyogDM2ferxNK61JaGbA-MMuhgmKlWl
}

EntityColoring(bitcoin)
!define bitcoin(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, bitcoin, bitcoin)
!define bitcoin(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, bitcoin, bitcoin)
!define bitcoinParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, bitcoin, bitcoin)
!define bitcoinParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, bitcoin, bitcoin)
