sprite $bitrise_icon [64x53/16z] {
vPQ7hiCm24KDdk3__zxNriNfZHHIsTL-HoFJCLn62BSaqHBsYVeaXssgFf6mJVbnFOkgfh0FbnB3Fu4ufPnBgRMs5mAC6_L9oJcdI1TALPrqlGGVr7WHwIKg
dHCDw620Vx_11x8QeY9o-7fGdvWaAZ8j21D-hqrCH5zL9kBuDZUThAzXWJmy28QiLedfpMR-HfKpE93jMql8n-MwKUIuI42BDGLfH4IVbAtM6E5i3TiLB5cb
cTTRyba624HYbMHc4sOFfNIh1AV4yzHaYvX90eNfPMq50RFPmLZ6pLy-g921fWFDEuFavRp1HmOsb9_LA9vYHiO02BWqyNB6m02Gm8OR6Op5lzC2BFit69Rd
v3MFSeAT5bAywY5HXBqAil1VFGM4hbjGRsxr9GMAMu5MnlS62Fa_WQxzUZqrDIJwBV2c-gbQFV6NV2v-kTUQsKz0NB_PWQHlD7_i9h_bhmmdXCCg5fvYOIwH
BmhVxGBCMImnM2VlwQGDJkFBPwPhCj19cZ8YtHcWy3O6BehkaQP7MN0RP_z-VY05HUTei-lXf9uGEGQxCcPODgqV
}

EntityColoring(bitrise_icon)
!define bitrise_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, bitrise_icon, bitrise_icon)
!define bitrise_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, bitrise_icon, bitrise_icon)
!define bitrise_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, bitrise_icon, bitrise_icon)
!define bitrise_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, bitrise_icon, bitrise_icon)
