sprite $bitrise [64x19/16z] {
nT45eYL124FH12aW-r_mj8vzz_DSRfVXjnp3-_pfVuJdgZzM6jwaT9YT3e4t22qZSIDjHBnU3VxZScmuXT-l94unZdzCupzKdY_zf-z-eZSb_ZTzzqPWV-8C
0OA40J3dqTersJ3SmkybKJDIWYfA6hf6AnHOaWm-KZDbA0rnoXb7YaUlYf53ZPAABfM7d9f8SiPJNIBC31UQ4I4x-W5SQ-znlYyWzrxB49grf1wSV6D_7m3L
__Uvzm4hAKBJNNrlFxMfl_UKKbWhhjx-zC5KKMrCknkaD8O3xtvJvpnAihitRGAfJLxzTIXtlywZy8phI9X9XW4MX6KwiByOPeZ_XGAlvL9tRTPcV-qUDLxF
MwE_pIpYrNu1
}

EntityColoring(bitrise)
!define bitrise(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, bitrise, bitrise)
!define bitrise(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, bitrise, bitrise)
!define bitriseParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, bitrise, bitrise)
!define bitriseParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, bitrise, bitrise)
