sprite $blitzjs [64x25/16z] {
fPC5Wa8n34IhqRd_URVD8YqVv-7o8bD8WVJq2mLUVl45i1_qYW5_xoictqV0c7ZzSG3BN-VlcCYQYGScBGt8HppiD9xcTkUe6WBQtZ5LzV-gZE4BA4fHEa88
wkgNsOs1TlQzH2bw787dtHyu-EJNU4Fk-ramqODle9FVjISoXvlMh3PGjKw3DjkMpeDoutTuEVaoxaWTGojP9e0t1-R3dKHLH0nQz_mKVJcZEXe4xUZ3tG79
jpvTJxr781Cl1x-LKfh2wmDV8P6SOMABlEUdzts6RRy-lkyp_AxVhYDt1Fskhx0x-PsMt_-0PVThphaAG9il_rlRDgzXqkxb3pv99x_Fzmi15YmHQ5ee4d0l
KKtQCAN6SnREJKuixMhw0OAcdz3lsly1
}

EntityColoring(blitzjs)
!define blitzjs(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, blitzjs, blitzjs)
!define blitzjs(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, blitzjs, blitzjs)
!define blitzjsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, blitzjs, blitzjs)
!define blitzjsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, blitzjs, blitzjs)
