sprite $blossom [64x64/16z] {
bLU7jgim3BlPo_p_vxvXi8fZVDlgB0w9v9druo6MDXPZj9B2ppS8PQn3WKRvM28D0az9v4_OUHukLdbhMx69eHH-zw6zgBFb51Wfjrj4tSz3dAzGjraXTv5O
oQ4NkjWjFXQbodXzfDUt3ePsAJIVFjax3t5SDXow6VXqNZaOvOF-E6FGEKZyazpYshd7VMvOdzDXx5QaxZllXp1UWYYAHV2J27kJ2_T87-jHWCieGmNX67H7
Dz3Du-LwNvsM49liG9PFW-Gq1OnMH5-zEQpjER3-jpHvKogMl2kU4AEN8o-tu4tMyVSYjCg6o06SLiWtxpl0XcDcVSS_e7d-5PvM_UJx9M3BVJZXfqCXsnbS
kBKSzQRvmqaGUVobwFuKTi9nxexa543QCCyIT7jgL7qyrpj_Ca4Ti5sHzMxJYGkwsJ-_Qe1l2eYnd2EmB-sNz15DcesrBcajmfVyHyoSwSd_YTC7_S1K_fLq
krTR_twUhq2y6AlTl056CFslNKB4euYwydX54H1wc7iqF5uZgG88A460wN6PRhWYNmZ74J1qpEVCDwMd1NXi6Beq78ybZXSTe3UTmQTC07slVf5bb6tFCPCe
QS-KDGgInma7TD5BuoYi-O5jEv0uqEr4AmjRMDHDV0hBHc33eYW_ntwO9Zeqcjq9sDEgTlMA_vdChh7xL66dwvs8uYR0-Ss6Bd6k07uY_50XZ3rwAZ1tP7FO
p71Uee4Y-wYwEWzpA4lfLcGnGgPLzgXnjYUAQ3TZOWEnqocdMcAmU5oeB01PxDEnJc8Rrr-QDUAEh-X6O2Qy62gt1grUehv-B-Uo1aU1aXERGbZ8ysz7_iXs
HXw4PUKXhzjxCRuqOX7Jk6NxBnI0vkp_C2RHySdp2odoCPBFtD9aGORjFv_9a6Urdli8kKrwSNlno7y1
}

EntityColoring(blossom)
!define blossom(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, blossom, blossom)
!define blossom(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, blossom, blossom)
!define blossomParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, blossom, blossom)
!define blossomParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, blossom, blossom)
