sprite $bluetooth [47x64/16z] {
fTO7hlGW30HW2DNZ-v_tBrlCIoP5e-VjooT4nsaVkRHXWBl3RBIIqqsKyP8hW5dp1Qu6FmcqCxnDlmehN3Ly1GuU_Q3RJlJkX-XKzwxmrcyubf57NToSEFiS
3NVcxCT7Pp0_yTXI_CsS2sPw1KvuUAg-dl7mzFVmSyxUegFCsRzQKwxuoEJRpvyOEmuZFrEQeSkhry7DP_ZLU5iwlVpYvB5jMEtw-E3iQrbj2RyujlsYQksu
9Yg2XqOiinvy5NuuQv_3oLUyE5YxJMVVNjmAQOVvYS-lDzRkvkGZM3kSF6dYv4DJi1Tq-D0grnkZTrKVI7sQn4KWBh7T0YwF2xYpljiUukOJjxPuS8Z7adRe
YKUgU62Bru5ssOXNcNXHQjUmTiaNBOKG4nGj_T6IApbrqnD3FUsCg7QAqV8lKcPEo0qlQRENe_qB
}

EntityColoring(bluetooth)
!define bluetooth(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, bluetooth, bluetooth)
!define bluetooth(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, bluetooth, bluetooth)
!define bluetoothParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, bluetooth, bluetooth)
!define bluetoothParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, bluetooth, bluetooth)
