sprite $blueprint [55x64/16z] {
bTP9akim38DX3n91KVS_xnlQg6Q52HphttybOgTDTjgvBRTtW_LZKJK3O6PjNq276IvcTgxSXrzMBhs_BzcpIqyp5FRzqeFtLPQNwlig8zprKsQ2oKltRZzf
PdQyeMQ_LQOlFVaKayoilOog2SQ9ULzDCbwQzrLeihPtfGmt3Z3X4A4WF23Wc3FSwOgAEV7ZAaJC7_O1OimP0LomFaLMdNdC-1TO9uIPpvaiOJwLZ9V2kiLC
nifJPAmti-uqP0mSJ4N6h25cPSoCzoLBDwPY3gfrHhZ8w9OPuJeZh2mqyvcjCwOPbMPP91e0iCg60wzkV6T1HFY8yRxi6ICgy9xnljetDY2wOmwPXsB-BmN7
VAseuUAfKgAB3KA5M28oGdrVCazMdLT0HfICq00OOWhcNbd2CLKTbQKBgSPs63unTuT4xUURW7VcceNjsrL3CYB50XVY5uYGI38lFoXEf4fMHvKuyKAieEX5
r8bCZQhjlJ0zgauiJ8-g4miJe_H4CKfFH38_dg6Sg4RTJnmSjLRpcr5_0G
}

EntityColoring(blueprint)
!define blueprint(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, blueprint, blueprint)
!define blueprint(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, blueprint, blueprint)
!define blueprintParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, blueprint, blueprint)
!define blueprintParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, blueprint, blueprint)
