sprite $bosun [64x64/16z] {
rTQ7bZGh20HW5Ib3l__xNkcjCrDz3t_ER5xy2cSZrSUhO1tZMMuOpq9xV83n8tvW_9WVVvVt7_10p4VgzL03a75lfPHgREOULkDGHtBtmc8pyV3ACmq9h_qZ
nV4fNsyP5wruSZ-TTPqQx2KUno7Ex5wAvjwjUZW3EbBlftFTjIFfuQF5NYqjzUYbn0mESJpzk5XMQkvFO_FCuYN5uojy4V-SNukzxq-Jt7_o48uVwktLwn6j
NY_PziVuoZjghunzxTtvmo5UXzZQUyzspr2E--VIMYsVyRr4ruwcLzxvisdswUzVYuIeNYD0ETQ2rTh7Mfq1zCBd6hqLyxac0uIVwdp307hXfwQjA0O8fvS0
Uk5HuIM0N3q3w8NJIm2vUWsW9rVF07Bn4a1FBbu2oCLhG7XoyHf0Bbu3mfEBru2nSiy0DtBrKkoerm1p8rUlbNWDg3NuztW6a7-dHobzVR_tk7__7a_UXhi4
97xcddnFtvq1kQypzUJNz8i1kRV20F72mpCWzQrC1eWN7fu1ueNZOe1uuU4P85xvnG1wvVGQGA-S0VJAwJM0Nha6z25SlGQOSWsOtWoJNBq6Z5vzF3W3k01L
LnvU0r2v_XZvE-1TmSLhmBkKSoDf3lHQ2eburZYk0_TDrzE36n7Gs4lcHpQuRTd_nrUyjYJF_NmjBR0OefxZkOha7gNWlUvDuReFePMMUwVNVUl7v-lZPmkv
dwyXQ5p5z5lJ02uoA_VxA0S6qBbkIk_UdzsjSBnw_I4pztj_vWmDPr68brkoAX-z1dYDJXjNvbdBRjvbkYHCyxMln6l2Q5FEFClbMkgrTiya_VZd_Fv1t_SF
UVm7
}

EntityColoring(bosun)
!define bosun(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, bosun, bosun)
!define bosun(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, bosun, bosun)
!define bosunParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, bosun, bosun)
!define bosunParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, bosun, bosun)
