sprite $bower [64x56/16z] {
bPO5OkGm34LZ47xT_xmRsKE9TzpsbU6939bZfNPHSpUbUloPoWR41B3sDxiPffd42RGS2wMsMhxQSDF9-D7RMk29hZfZol8c8w1zseg0U_YIlrecKxcY7k7b
CqKcSBIbTe-0oOf7wBDl3MG22rvqt9AhoYGBxbEtS1LJ0Sh_z4zxVXfeX1-9XalgkWol-4LNeTvQvqS4doFaeLkMJpVVRdflWou3Yz1wL435N6IT7YFdyY9r
KUNMI4Vzc6jcMRce-AtzUjLJr7DY91b61EYT93jKSyds_RYW4IPlb1fbXegU1LXmFMazwz3qGtVfHNkJ70U2qtUqsavgxHQkOtoxz9cVOq3fmquzy-TK0ggt
rI-tzAD_JzrQOrMSNpgnmSnobdxRV8HmkT9RDq370gPF9nQQU8GjqrEveD8cVOpVQoN3Q59jENd50p9ODX2bBXvi4SQ00m4foyvtkQCg_3n26X7PiW0mNcv4
GfYigEh70KOlHocPUK6o_IqM4O2RS6zh20liVKKymGX3hIp-LWTpJXvuHn5w3iBJt-lK1dcAr818CaRxsRVCtYvq5dEC64vRF-rCiz99HmXOiI--PiTkkPLU
vHEVoCdxwIBwpRUn1PG_idOMTS3TpUPP24Y4RSOdQ-tYOoam9qa8s-ghhoVcZaZM_RzUn6-8M5-C2JwlZnLLRdT4NzZ8huTz3a07yoltHNybzvXOEJZ2-ILI
PndGpQRSVfVI0yxZcewWlE6Oqbdfhw7f9JteUGB2smOIkRHz4Wdgz3aYk6ruck_AFzFd1Hxe6z_SLCq3xeuqJrpgvnKKllFJ65uauEDwbUK4mxxg7KxcS2bD
7Qxzk2En2o21KvaPyyjAmGZmPGRp5TWM6W6S_gS_x_yj5WbqrIKIbBrV4GENlkg_AQ0Z9b1gByZYWI_6Ee8dC64YOl5uWVBx08vOi8rvQm5L5Xtz-9cgEB5s
DDprTloAIlHuA5tHus_mDRkMF_h5twxmflZTA1JpajZp3m
}

EntityColoring(bower)
!define bower(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, bower, bower)
!define bower(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, bower, bower)
!define bowerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, bower, bower)
!define bowerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, bower, bower)
