sprite $brainjs [64x64/16z] {
xTC5gkr040HGgBPfgVqlz-jr5nwQWoRZBVWPcyrcizbiDgAAoAfol4qYgxdG_2iLxz1G94aMalzC25uaNcGRWkH8SASDhz3LkmDXGvhn80NFM0xt5hGPCZmO
nqFUF5KYbT8yKOhxT7Xk38ww_7MFDAy4i7Z6S4_oXaJmr2ZkSDwanbCjhpp-QCHvgd2R55zQlruAtj6eyrJW3kDDBVPY-8FNoWMmUYNyGF5SBuLufPxKPGAl
rS-KxRjXbY1crrEF6FSw11hDdGb8agruBAQxgj94l8Odsc5By8m8_j4SNYZ5EyHNpvt2VvLwDlSIdn2DNI0Cdz8cMVYSaNHyONK9ZZQ_0G
}

EntityColoring(brainjs)
!define brainjs(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, brainjs, brainjs)
!define brainjs(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, brainjs, brainjs)
!define brainjsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, brainjs, brainjs)
!define brainjsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, brainjs, brainjs)
