sprite $brandfolder_icon [64x60/16z] {
xTO7RWD134DHIVnp_oEd4t3tIfkU4CMDpvWAUyr3HSJlyFy-OtlqotrcoQdiU-1WbQ6w_dodXjv1O-zktoC9_0LjJvwKPzvjJNs-lPpwsEtVPVmxruyS-lBo
T_sgp2nvzVf-0NwM0-zuy7EFSkWTD9i_kA2sh_06l4JJy-jw3ht7ew7t4MJgauj-ZJphCEgFdqFUMJ_yye1lyUNswVbIRF39-Ky8vXlEBsvms33VUdyy70SK
BU_HEnKjJyP9RdaEfFz1D7oMXACotk0R-MMUHkhG3_9z_Bz_1
}

EntityColoring(brandfolder_icon)
!define brandfolder_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, brandfolder_icon, brandfolder_icon)
!define brandfolder_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, brandfolder_icon, brandfolder_icon)
!define brandfolder_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, brandfolder_icon, brandfolder_icon)
!define brandfolder_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, brandfolder_icon, brandfolder_icon)
