sprite $brave [54x64/16z] {
XPK9ZkKu34Errzp_mjFTDa8meL5-sFxY1ucoaDYN-H76xKB__7VNL3eolqgb0hIxfBGTy0Ytv6EgUMIm4xEw-4tQVqydf5hdQNRAFZ3TNRR9MVnSwKMH9DvK
5V-o2a7B6H2H-sIdxo7bJbFXsI0jM7hckPNFjoADhBBVAIhMZzHsmM4vShNRZK0fSuIwaziApB1syiYiT6CyCoDy_OXQJQ6YPj65SUuHLATJZ-Rl_Znx5ibZ
gtZt64b3Pp6UGwIWnpgE8cVycPeVBmqMqsCBfq9ivV66gn_TJpTTWV0CWdOTIzaSj9p0ALUftKerdt5CkdGt6hl14waPMZqNgR27fFbCK_eY2Nje_TMIB6iK
WxH-g06E3YlyMSDyUWNhwu1UslDJhGmkKkqO-X3mcfbrCzGfnq8mZ1_bK0WtXLYlOBmxA2InA8KkIEikeMaEviTQUbllOC7IG8D5iIXOiJJzqYZMDvZpBtnT
bXnhyxdcw9cfiAXkF9me5eA1s0xUATlB1fGK4jy0FAOCn338ejvxh2_f_0hYM0X6f4eQIuCrjnWI2xYEW-z9Ot4m3LVzneqfrI19B9qzQBo82HcKQj62VV0H
MWZx4dShJV6-M66APjEXdqcnjBjRbwVkxkLEstSlnuNk95buuDo9XYM5hkLEXUxbZeNkvL18-0C
}

EntityColoring(brave)
!define brave(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, brave, brave)
!define brave(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, brave, brave)
!define braveParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, brave, brave)
!define braveParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, brave, brave)
