sprite $browserslist [64x64/16z] {
fPS7skGW240Lx0NlVzefcSKl6pN4tVVNAKyHow1QeZKmMgiz_gXu-grtvH6zRU-t06UCq8BGUIpm0xs3ZjWvanhX4KMYvkKGUkTuM11RQmO0lt-RbSV0EgG8
7y9Nys1h-sB497JT7k-sXvPzEo04j3wcb1mSh7L8hHM0qiwGJ_Hh4E77KZVVDmRVfiJL4A3Zsvgqoi5fdQUrNX5E3D6RR02mhlq2Vt7HmJPoODfZNry6xxuZ
z6iz5vW6eBj_ZoMSDW3FVDBLpNpzqAygvjbc1iOA_IiWEma062F5hqB58O0ZV7G80FNUHwNATGIyz8XoS4N8VpQw9fpva9kCAqNfaWs0YJdmgNxQDI9PAPsg
nzhtajPzrufGFF9jw-n8Ih9VUBq6EXs9o9CdGehHDlVDZ8y38AqwOLXAM9i4ikrgkUg0KVJD8OElnIESSQbKQYBs8xjC-M9pyaHogbI2WH7_oA_HZNB_i9E9
i2Rzew_vd_YVFdZQz7d_CLRo_QtlgkGx6E3Z5srk8cRcApwxHSgy6XEZPm8Cd6lLI89lvtxF88Qo6VvGD9gRHU1NldgqaGWd-ZK0kvSzfkiar3vNdP6FG7zN
YVCYD2wcyY6Lgvv7_UxMa2ywcS6_AzsHnALpL_lpRYYkh0P_VtduQfGSG1BqUGvCIS4X7sha17re087v-CLkNA7WGgA0ihwUHsi4MsX16Fbk2titO1GYtuX2
B-Kt
}

EntityColoring(browserslist)
!define browserslist(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, browserslist, browserslist)
!define browserslist(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, browserslist, browserslist)
!define browserslistParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, browserslist, browserslist)
!define browserslistParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, browserslist, browserslist)
