sprite $browsersync [42x64/16z] {
xTQv0WCW20DG5Gty_m_tJkyQjbvcVWARAG-fXb4IQSCZ85djEnPILiFEKOgj3CHM8RbLIsxLaaxB-32vfBMiT1yrAIFSiZ82BIk39sYvipqhUOAMF45Bdg0b
RTEI51EfikIIIow9f8ILuGdfnd8nbzwl2WicykwtQTtl9Tsqku0IxGun1h-MRjDc1ygfunKx-TWijm
}

EntityColoring(browsersync)
!define browsersync(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, browsersync, browsersync)
!define browsersync(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, browsersync, browsersync)
!define browsersyncParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, browsersync, browsersync)
!define browsersyncParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, browsersync, browsersync)
