sprite $browserling [64x57/16z] {
pPK7ajqm34EN5Rh_XLCSZg4VnlEfT4pRuYSIBDB7eyG2M0iPzd4k3QnRS3cZfUZjXAFWDyrZKavnf9kP1t1sW82UzrhaaC-ArZBo4MuLg-S4cORlNnf62LGa
-_6nEKmVuxzt1UEql20pFfvywNlx-HI_PYhTz24DjS3ZfEYw1Q3jf5W2gnIFGqqXjYmqwxyJdYViz8I7cKK2UDb9n-qhNPDprldogbuHysfOLTRadhFM9xc2
eDrFNZYtDMlrTOFhuuLM42Y-kvsIPkBR_P5WmVgYBgxBdbWNw6hVQPPxz_fCKxvAVLjh40bNURf_nk_3dFYgS9F76zuk__wphqlKMAREMQ4vZWyG9cz9uMl0
hWTUEwuYiZCYgkR1kUV-yMhT163XrW8n2l0zXWDhB72uAVK41YZ2bP5Rnwlbs9bBcU6c8fF-Y7wHNL9LblFN5F23RuFPtCy2R8WxTo80Etd--2qllVjCo8pd
KsqtBwFtcq5rYpytm5ItexRtMq_iawUhkNtoxE32cNto_FlSFddc5MFxVFIB7nXeTPBYcOmDxHVFNsXWRfyyzs8IFpf_AP7olluP_8ZyaVuhtdw1pr-ChtZJ
iSy
}

EntityColoring(browserling)
!define browserling(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, browserling, browserling)
!define browserling(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, browserling, browserling)
!define browserlingParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, browserling, browserling)
!define browserlingParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, browserling, browserling)
