sprite $buddy [57x64/16z] {
dTK7SiGm34DHLL3o_GySCmqfq58ofgQyuVojQRaAeANZbGu33FMCvPkPGqCl1wx1tC6beULDLc56U0zrBuxE9MaSHqZPInX7HnYaLZ92y3Tr7ISXXxAEevEo
Pn4NG9LQ8PoKJ6LS39dAE06rP2f2HycXDDWJQB25wv5Sm9hQ8rXJEfDqZoHoeZo0U2g1OK9kk8SI3oMWv3wah9iIBsJWACk1n4iPECgUFjOZESOlslEdCr1A
D-TDxPyR8DJkciDdmb5ADrqwjI-NuOvRkCkXRogdvOrydmuhXuMxPk0ewRuWdVcZ_5AEsr62pcSc81sXqNtD_aa-eDn0ebDMEZyvyTyvDL3ISUEMTEgiTfVB
GQVEqls1TCgw11r7jQ9cLJ0_6QsbEiJD3PTIxiSdlxvRYXr1A-bxTMnBQmwuvl-z0NjEVvQnyVYW4735WfDM_ncHAf-2zVhaHqWG9r89WxX5QX0dKtbIn8Mf
SPnETScu_TNXS1tt1W
}

EntityColoring(buddy)
!define buddy(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, buddy, buddy)
!define buddy(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, buddy, buddy)
!define buddyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, buddy, buddy)
!define buddyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, buddy, buddy)
