sprite $bugsnag [64x18/16z] {
fPC55kue5CQ25BWN-DZ_RkTGc-VsfvOZgG6jyH4oFc9zteV89dnvZd1BUAyNbxostAJP8Cp6FbU8Biq2O98gK2KrW38bZzlgPMl9MvSJPBjN8qvv6sexgzag
DFNQrRQCvfeHxBQb0sWwKBjxLmPCYJxO13dW2kcKB2VBBbkTpVJmzZA0g4PHBn6o3k1GQee09bwJiHdzxOFgEx97bofP6VRPnAOgFhRcuCoCwK1IHPrjzsiq
fQJZx5DLulgIs_egQe7eIfXAY5s9fWfnB2D6ICfFduD6X2h5UDl2fA5TX25TqZMt6owtEKD-UWvfJ4cHSjc2em_F0A6udKBfm_8qGXlJ8wadkCx9HY-bXzlQ
-cnbr9_tKOtVulfHwGS4L-8NL0CE-O_wARUfogze6kOQWHyGNMiMVasPInxu3m
}

EntityColoring(bugsnag)
!define bugsnag(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, bugsnag, bugsnag)
!define bugsnag(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, bugsnag, bugsnag)
!define bugsnagParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, bugsnag, bugsnag)
!define bugsnagParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, bugsnag, bugsnag)
