sprite $bugsnag_icon [44x64/16z] {
xPP7rlCu30IPCxhlVzlv99l0SvAzdxysJWMg2OPdToCCI7K_KOGayWzcdE31_6hwTfW0kRwfQP6afFRTBI29vjqFhf2OqRbVN93TkTzSakN_vlvpOpb8qNzt
8uWJcJLySGiDpFouVv4UN3_a3m1tEvaRUt7cAZwaEd7QpJrZhX6g7FOC5wxXAqXAl7ADk0uvNBc67o35Nxf61pdS7tdT0Obbz6BF7IJgUUO_0FHjUxb5vWMe
Tpc1xASxwi4afIfzuP2xfK2m_L2VvXOxJ0uWszN-JKAYwC3hodLHjBC9HBfoNGRPj1NjqdMJ50qnhzq4slQMTswUgzWgL8tpnesm-K-owtAOY-qsafmQSwYB
xLPrAxcDHrS35UnU-WNiex38fkxQWQ9EsVbIWgujoXuAWvmwvUwC7GotiavArMNi989QMZyrpB1kHv1JDItFpiBOepk9XnJLgiiPfjFcJs9g3DzXftsTLH5w
LeAGH4_-JunDIErCnYtCjEgmU0XOIq2IafmEAxlBmvvB1MFdQI2ApgdOCHFW436EGMtDh8j8rjHOQYt9FnmbHAqpsNXGwqCZKTwhIQpj9dV_wK-MgYfJohET
5tHK8mj9I8jE2VKmBQiH1dZgevQSInsdICneZf4dU09Wlrl5VI0D0HLWPdU1ptt9AUhDRlm7
}

EntityColoring(bugsnag_icon)
!define bugsnag_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, bugsnag_icon, bugsnag_icon)
!define bugsnag_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, bugsnag_icon, bugsnag_icon)
!define bugsnag_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, bugsnag_icon, bugsnag_icon)
!define bugsnag_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, bugsnag_icon, bugsnag_icon)
