sprite $bugsee [64x33/16z] {
hPC5iWCn34Dbadh_2tyiBCVDz0qisfAI66UOPv7wWQnqWpFGnPFQG4beOKaTax2iKNNf6hlMreZ0EQ4nj4dhB5uwS0vztzFb-zxledU7rIzVBhl1TT8WD010
tCfrtC0rme6yCHTdQO6njMqU9-U0Qf2H9mSnDGCRuLidcUfIuMOUjJZ9VNd6Tipo7Vayc1NhopisvBrdpPJV6n2m_b9lAIaGQb0umYJsx1iEYIfmKlwEpQQ_
4zFs-wD3d5EBtxYy9rlrox_-caNeVbPT4hrTN_zXt5VrDgZNHl_ZzOFr_mO
}

EntityColoring(bugsee)
!define bugsee(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, bugsee, bugsee)
!define bugsee(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, bugsee, bugsee)
!define bugseeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, bugsee, bugsee)
!define bugseeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, bugsee, bugsee)
