sprite $buildkite [64x11/16z] {
fSzLWjmm40JGQXRt_MyRzyYRdU-a3C8d8Fo46M_wN3FmPcrQeogopJTN9GD_eyfNcvkyY-sSEnjkngIpy64UALNPZj5nOrehY7l4hPRVm5aa19PwoulQzIAa
9BaOK6EOFSmydbJ5fFonoD0qzAIrwV4pCyjpoouPCtFJoZnMKO-AcOT_V3wH7t_eJC_6e_p8ZiTpBkvfie-gNkzrXTTlvhtzT_yvakxzCwKypi3ASqw2LH_l
BlJbWPMUWVdwbeeeFtE1oq_C58u0m6eVzklpdEnqykGz_thg-zxVw_uDAwVcMJbG8U1wjwfwQyq0wTs3t14ERiD290WU7Fgq0zAduolknlYFcFm3-WC
}

EntityColoring(buildkite)
!define buildkite(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, buildkite, buildkite)
!define buildkite(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, buildkite, buildkite)
!define buildkiteParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, buildkite, buildkite)
!define buildkiteParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, buildkite, buildkite)
