sprite $c [57x64/16z] {
bTPNSlGm30HXOX3s_YV-eqfTLYr4ef_zMPmDj5UR8bDhdENdRrDgKP-hj87p-b35ATF5e7usxk6OkXj7L6cdusW_LTaWfXwDEvmQiBuAQyRjgPftRkSYt1Wt
SN5JX-tTbVwux7ue8oAp7kxAbtzLoH2Bmf7guEtokXqTVK0iSIqi0r1UZjuTUGTnJHlegqkliDOYasoHlq4zFxy9rGki7-uv-WK6a7krEMjpKl_orLKFZGVU
BbnNta8c6gwfWS8D8Mu67JU3misWuMPmDMx_FWR9_iJRkFdaMDpPxBFAxrzxo4WUoJrfBUG2u9cufTqDG8PgRm1MTjdcUbG7_HrMpEvLN7oNYcVrT15wUHvb
ytUpUHnPuO9SrudDF8YqLBZZNFnBEtB6hJrnOhxNx9IBD3mbcG_Ob6erQSh8VNRA_NbXRUfEEQU-ZlF1k6wghM7QZFiD
}

EntityColoring(c)
!define c(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, c, c)
!define c(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, c, c)
!define cParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, c, c)
!define cParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, c, c)
