sprite $caffe2 [56x64/16z] {
lPO7jjmW34KHY2AUzh_U-0maYZy9Hawvfqwv5ZoP4XveQE45hAeS_EJBAo-z_9_grGxWyW3qwed4y0ms-xrKywTrFyQ9HWSQOJwVPYuKZaYgMb_qWSspFlZg
yNaahOggzbfhFd-l8xw6Jo-QVRw4gAk15Cv9pELo9357XsPv-c7ptjJpqoqI5-IDn0yTi5f9S8B4PQ6UqPVW3xaNPAVdhvTMhySj2Ne1IAOltlCcDm3xlK5v
wMb-wO6S7dF_YDNfqTo1O1uETaZGzsRVljjWpoPCxsACVUiLlP1F4VDap7M3_QMeUULnWX7pzMJC4EtRlF7gsFYhw0V-UHIWVJb3xYkmRcTdm9PX7-KtOHhT
j32NLtg-ag3GEd7mxwkrUb6ObYdyUexKflPmPFPRIIguHxWIkmvwJJIaLA43eSrIiRJHHQHRqzggBU6ie8G7KjSLYU4P5hq1IU6CM0GO3YJ7u80YNwH8uHz0
FgRKuENJIr4_RUnaRZ3MgvUn6xf4M-xV
}

EntityColoring(caffe2)
!define caffe2(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, caffe2, caffe2)
!define caffe2(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, caffe2, caffe2)
!define caffe2Participant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, caffe2, caffe2)
!define caffe2Participant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, caffe2, caffe2)
