sprite $cakephp_icon [64x50/16z] {
xPI5giKm50HxVC__V_1r2OHq7yzjq3QP8TXkCw8UaLK0-WI0gifmKzdMtCmie1S0bM6oS2qkAWD0pWtBmUMWV4Y8Jp87SI_uGkQ5YvxzQagthVeDGAFVHA5_
Bl_y0tBklhzAINozhEAo0G7rxyiApBfjMjo_CJLWvtI0-Oj6tGurmVovWR9XWGFW_eXE3ui2Y4yGyom0n2SHDO-imXNcoyxH2QqqsVETzD6DdOP2cNzYsP1g
AFLl0BV6g7V3gRzesEqGplsvOJNy2YN-r01w10WJuZDGuIh49m2e33TLaLDAc8zLfd71FT-wVxVDUDF-RSlzao_RFwIyt_xLc_VFtxv_wbaWFezOH1LUw1y1
}

EntityColoring(cakephp_icon)
!define cakephp_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, cakephp_icon, cakephp_icon)
!define cakephp_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, cakephp_icon, cakephp_icon)
!define cakephp_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, cakephp_icon, cakephp_icon)
!define cakephp_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, cakephp_icon, cakephp_icon)
