sprite $campaignmonitor_icon [64x44/16z] {
fT9LWaKn20JH005g_niUztb6khwldeuLvUieIzeB8DP1tdnLjgPjVjQ-Hbdnfro3Wl-r3-0kjeTm7mqPa-lTNzAQc-LaDKQC_rSRCaRpK6LZkFkCtWnA6yBz
Pnp0tLioEAdz6qwutvkZwXlkf3o4-oW4EC2bbxSfS9Io6cpfvOIo6kqVS89SD8fS8iW9S8G2Hxi2Hvbmt24bEBO4rw70qQx0KQR0aTBBsGeS-4gKh96oGgZz
6G
}

EntityColoring(campaignmonitor_icon)
!define campaignmonitor_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, campaignmonitor_icon, campaignmonitor_icon)
!define campaignmonitor_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, campaignmonitor_icon, campaignmonitor_icon)
!define campaignmonitor_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, campaignmonitor_icon, campaignmonitor_icon)
!define campaignmonitor_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, campaignmonitor_icon, campaignmonitor_icon)
