sprite $capacitorjs [64x12/16z] {
dOm7efWX28E3YBWmzxzjvUzktuwJm1S0Of9tnTSapPj0p3uMyD-Oc7TNCzEdwX6pl8uBetNvawvYlV_2D_VYAP2gKkxIciFtBdAz2lGsQO-3fsqPOFT6okc0
7TT37ZRcerXPk0OP6ckGVL_7wdLH4zLCINxnUIHeDVbGut9sdPSvrSuwbxTDqqrd67u5cFpYYt82_V8ExBElMJZJWoIlPm7jEYs7Bzea0v1c1vpZxCngYKHC
AkpnfFl3HsJyI3vnxnbGW8GY6D8PcvVd3hgIY-oUHJzxihHiJsDxS6tkNWIFsbfT05-p3UESgm7rtiEoPUZUXi3MSfIXq8i3Tddyhqh7UrBDEqF-LndrFVmR
}

EntityColoring(capacitorjs)
!define capacitorjs(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, capacitorjs, capacitorjs)
!define capacitorjs(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, capacitorjs, capacitorjs)
!define capacitorjsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, capacitorjs, capacitorjs)
!define capacitorjsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, capacitorjs, capacitorjs)
