sprite $capacitorjs_icon [64x64/16z] {
xTOvbiKm20LHeH7jVy4zPLHZ8UBlb_hKDSvS_0qfXzLMCEOw3u2CqO9S0I07uEG0a1DW3e0v0UO0c1DW3e0v0UO0c1DWJe0v0UO4JCvrUzvK1q2E7i1o0EQy
dm3t1qXtynZOM-NYxRsB3-nV8Cx7y87zktMH6m3zZ7C3vFCd897_0GL0AYUGpmcaSWBvd42O5pa2GHvTC9n9kGVyHvy4lC0Bo3qWu__MkWQgbs-Tpy2uoFK0
r33VUW04t-xc07BvLW3ft0BIK_bM7yZdkYnGWtnkqmC8yrRLz032l1HHanj0ulmFq0SWpFycIqEWUldfVtPPeBlv0LYrcBL33W0v0EG4c1DWJe0v0UO4c1DW
Je0v0UO4c1DWJe0v0UO4c7Ez5pC23_et
}

EntityColoring(capacitorjs_icon)
!define capacitorjs_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, capacitorjs_icon, capacitorjs_icon)
!define capacitorjs_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, capacitorjs_icon, capacitorjs_icon)
!define capacitorjs_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, capacitorjs_icon, capacitorjs_icon)
!define capacitorjs_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, capacitorjs_icon, capacitorjs_icon)
