sprite $capistrano [61x64/16z] {
nTVhagiW40JWS9df6NZ_zpqQeSKAahFt_hlrLJk8X7tS9SGige02ckFZ0ua2M4_PuiZXVwKDyTA2z9ugwOdhmIqlQM3hnRFT5kqPDa-fdIFSrAhTfPpnQNd4
hVLQ1owlDeqMK0mnBsNWEhSug8e89Vt9CUr5epksLpxlZW3Ci4VbY18pLkfaxi0_DwjubG3KgJEnZdPUgyT36NLeDjFkaCsgadCM1M2RKnKPj75WMcfDWKCb
WJ3K-VBGKEd9bFICD-rXB3vjf692vaELfdKeBgwidOKQfLKFnQKMFEq0vjfh_xYbsrAghMoK7cqVDlU7rr9TjeI5fKvzKxEuW6krjETBb04x92yiATE-YESQ
r6ftXmpfw-V4SyQMAzqEVoPTyVtPIZf43jktNBZ5aVICNh0zFXIzdClu6CO5o-Tm-JDSluxrmwlz-LSbn7Np_Z6ShtU7z24ShGVsuQ43kWLABHu-fFN4xeRy
qQ6fzuIF3qsBvTGfpfvRHRlEYw9-335fhnrl0kdEXidF2VRcNR_fZhCVijogbNfwy2TXmgHQZJnDhgJQg5x-d1eMd5fJ65lLpD2j0JAUWfkbDci-nnX2ZBbV
PfKMq3Wk8tLxwmt0Uj1iJ-14r1rHqVAPZyXiATNcmM6d6p6V6dEjGoqqK5AlE32trE-vJIpdPioz8tS7hm16Ez-yAbl6otqjnZjFuJfFBseefgBb4eFPBfTd
P6gTxbVitkZof0dfsRdvQoh_hLecQha9bfIZmtiPQqt2EqUVn9m3c-Qf_0S
}

EntityColoring(capistrano)
!define capistrano(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, capistrano, capistrano)
!define capistrano(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, capistrano, capistrano)
!define capistranoParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, capistrano, capistrano)
!define capistranoParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, capistrano, capistrano)
