sprite $carbide [52x64/16z] {
dPPfpYGn24CX2s3kVz_PIb5RDUc8VE__av6podV2PvDB8e6mVkdy1J6qxdW-0BFi679PKPrmvWTOqG5BhlADDipZBpujaubjyTeT0F81-GB_Ipg1V76Mr9Pn
89IL0MG1fn17bi1OIeki0brpPHsxLn9whIGcALKWCkC-HsIKBJuKtL5KJ7aR54C8lmtXqyNWBxbu7U-6dM5TLRk1GeZO6Du-XuJsvga0uyatTy562M5Mv346
NSx4AOOvbsQrcu_1BDpabuuYhsTho8iEkEbprzft5Po33364iDm1Uus267fs-BdHjRCnbPmjc4rL6pqMWEdPIJma0LYZ3gh06tTTlw-GjuJUv_HrV82BryJm
pEWNZqd7SnCDr5z7HKRVdV7JfZBJ-ftjGfI2y5QaepHOvImjW5wuJmWw2YyqlWcnZ8e40FHdhaZHMvC3k-_IJxwXBZKQHOLK6G5swXRMpg_JBK1EbJOzTat_
1W
}

EntityColoring(carbide)
!define carbide(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, carbide, carbide)
!define carbide(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, carbide, carbide)
!define carbideParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, carbide, carbide)
!define carbideParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, carbide, carbide)
