sprite $cassandra [64x42/16z] {
fP07RkjA34KlUzN-j_izWk0OmN_z96v37iwby4iO3mG8_W02WrWOJ8211AguPp3kmr_WP4XjZoH9GP06dLEuYCBn2sHcUcTVp8wtMwd25PPS205-d86jPhyn
smLFM4kh1m3r_vUZzp1z4lHvFzzthwucdvYm1k05CBwZTTJfYgYAZAn3c_Y9L7LoH1EacY7spRQxsY_3O6Nk6dvFI83LQwvx4zVQORX_kxktZRWE6XQcJAhf
eLaC8XRBsOVmDdp2jUqC73zDFOJnGZYCZWzY_ffmRGa-yPqG9jn-IJuw8AfLZ_z2D7gcK_49rQOo7v-oAiLCyC3d07Xy8d_9z6tp6IEwgq1MXPOH7iIp0g37
rxqwlcSl1l7Zs_5T-TFNjy-zkwNu82VUyVXUm2ZU2v971BtZnxMx4L_ng5hn-4-01DYV3eXyN4-sBty2H6yz2VWO0C13FDc801RBT03qw1MruOu7VkVy280e
TpCJOqq_-dEzxnQWAV9EHtX3z1vWBY_HKZDIdn99xMu70O97P0B-Tm1JP6QzRC9T88wvTjP96GTw7gwRcddaYp3bqqeui8WGdhbox9p81eZnXRpKGrNjNZjf
maI4BuZ5Qm_AIUdu4N5DpdNDL9Y8y0jHyvgzhcirji2A4Fm_rCceTitJlZFJioVJNcqn3frRTSB_4WPmCa3RlNrDNHspEpu9Q0DMU46A_qCOW9stI8wAosaK
EZ5wNBZUhnV4-5-UYWJ1jUjkfn4hc00S01o_X9G0an501DIC52Y0uvFWz_2dcueW3g9dDoRy5ddtCIZVgLNmsuW1Dt9Se-VX_3PAmDUbolX369-3X7136VX3
w7cxaIty2xhn_-VXTDx3219Epu54ECCSvWoGHQsH2Jk3FLmUcsgd2JKzAphTPDD5Y7DWcAdPXCpqhiZM3DjERpv-h0F8DTHIhGAz0jW6OeLtKpVHm-WXEpzb
2tQicna2Q1eq0zir-8wUPlIIx43NPHEy0zy6SWMvYiDz2fnwR06sGsS0RyDk8U2hvxhSkcDY1hBBkA5PZvJjd4rscL7N6Tw9sRxlgMNRhjb27sqsPeVU-zzn
jss3PqVblA5sTFfUevPeJZqnVHjZVVl_0G
}

EntityColoring(cassandra)
!define cassandra(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, cassandra, cassandra)
!define cassandra(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, cassandra, cassandra)
!define cassandraParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, cassandra, cassandra)
!define cassandraParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, cassandra, cassandra)
