sprite $centos_icon [64x64/16z] {
pTO7SkGW48NXJiWxWEv_tQLbeTT36QqBRNhEuVlBXJo1_kynF-Dc_8mduqSycV4JZi0INm-m-LpRKe2bJSrKVEj7y7rgVUBEnuT_jUMNahNtd_kwsOzBFPNQ
Jf-BBokbN8xbkGSVFGBtNd7XedTcP-3EcpIVllORoQ-yUK3itOE_IiuttbII8G1_yjpUfpprfjGe0l3WH2dFl18p0l2HYrAQ-EF22GBmWMU_Z79pTu40FBYt
bEOynK3tRtmUE7WCT1-vB_Fi-W-1Jv_0v___OfT7W0uFVdcnaRyIF0BkmU6rsi0pF09C8aIlYyFl7WYykCVw-PEldp_Ml0S2Tpzxx18_28aZsJq0thR9k51I
UPkc7G7dlZpEEjTIn-q8Q9xuhVjK9tuZ17waOKRNR1ls0Nu6S7uOqsmIkGVSXojSwqPIYfAlFo1Wf2T7eFcoNwiVZUzLYSMzCSdWdOSfFFY7st2FrDVyoJ4p
U71sITm3yE1O6RdAuV4NTCz4SmzUbDmvHM3khRxpkfz-29WGJGEHr-v3OCuvjK3ay0a1VyT0SNKZ2ppw46XyTduj01vzl4TgVEARt2AF7W6sgM-YWaUFGBBR
wmy-UZorkFSRsGEFmEZ1xpq2yE2tlfxpWE_oFkVd9bwkzS_xyrSc5toDlZLcbcGAiVBqtsScj1201ry8W2y4mDS2u8i1yAKn-F-vdm
}

EntityColoring(centos_icon)
!define centos_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, centos_icon, centos_icon)
!define centos_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, centos_icon, centos_icon)
!define centos_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, centos_icon, centos_icon)
!define centos_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, centos_icon, centos_icon)
