sprite $centos [64x18/16z] {
nP9LWY0X44CfnQdxttRJm8vyZhysB2Gqf6z2v4jo4kNFMpFKKhAMyXczAgknz6wrlRIPcRnFQFoyDUTJC736C0l3ltasInkU0TfxbyY8kZjGqXMR9x10p2oM
hTty8vgx2roOAJ58oQ8mhMWYDK96J1M03WKin8xurGXoYPKs1GxLTXR5Q-MOP_eoewT3gGhWfPwprqQmkfqEcR97zHwMKIbdJJLgmMnppafKgWE5guFMh_xu
r9pLmj1Y4Zdb5ttAVOmHCH9P6zqB4pDY6E_yS-jdhBNA6xt5pPzVreTt7RcuxbtGT8NFehY64oMFgqVO5LKOAYO5DlQFCY_UZVSk7Bsi08rcN7yFVzBSRLkE
XeDXT6i-9lHw_G6TyqFchcIKs1WLItYTyyEssNwrU-qGx_oVX4KuVGLO_md_
}

EntityColoring(centos)
!define centos(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, centos, centos)
!define centos(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, centos, centos)
!define centosParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, centos, centos)
!define centosParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, centos, centos)
