sprite $certbot [64x22/16z] {
bT85biCm303HaKcM3Bh_RTVfM-PCqV0BISWPFfVLhV2lYhRAfqJL_P--2psNdDDB9TVSktlzfmVrvTPVyh7EmApd__b45ny2f2n0MOqRPTL2Be2kjQxNngr4
e5J8EzCMeDokD50Nqif8b_jUBz-apUFjlcyTTFhqdKWztVTMayLLJThkUwfvn3gFRPRv8VrbhOnZpoEwy5svL_9ddqhYfNhiyVjxJei1-ibNgxma--4TfC_P
1VIyG7UlG-kAxQXNrGBafYrHklVsuGV44cJ5zL5Od5UdnwctnvgwcLkXs9NKC-Yy93vyAkYnEMQABR8ZuU426Wxgnth7B5DDF_n-agcOWaU3acjizuZ2Oqnx
-EF4BBbnlNxq-V8THZGU8EQS8t_ZyxTUdh-_Xo73oikf-EIJsQ52_lpxo-KjaI9yXZDYsPYK5ID1ZMsYRgrxetflPfbonZoNzXnjhWbrHxWWZwi9ttitu8no
i-Qk0itS2aXtUm8
}

EntityColoring(certbot)
!define certbot(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, certbot, certbot)
!define certbot(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, certbot, certbot)
!define certbotParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, certbot, certbot)
!define certbotParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, certbot, certbot)
