sprite $chef [60x64/16z] {
xPO75lGg24OL0G7tlzyNFp7vcoSpfxvsfpjUmPgK4zH4L5MaKVaAOeWB4QRFpLjyzC_ioikK2REiXeJh9q5JxEOXiorYWVogDe7PFSQ5hZ9cLVbGLHyWNL7X
zvG9gi4BDvEw2_bDhL0Hz1BD8y9DqDtNd6yrp68a4Lrao_NSsKmukcznlMkcpIxdiDAXGd7hAjqVkVKONizXOwkk8jAkKB13i-6Gqo96MAY6FbwkXQ4Regjb
FuqpMGotwQ-nROLYh1BRWUcyEFeCwqjbAeea_0aSKixqNQyX5TqZq6LDe9KpZh1GWKQ4MOIp2C_Fiqexn5DoKUThGaHdjrskOeW_fp8pNSXoXRvmAMAeN8pb
dkEU-ucueiBVv1mv__WK-ccvSNUt-PhVptCZbck7sxEd9MAOP-D_S7jWJOXURYz58dghUGZjPTxbpnF0wEXQEy7pLuGMokQmgD4s_Rd3ePmr8tSU3hfSbeUK
WNPQONgUEZ4kbwJVs-7bqECyA65t8OOvxDw6zUsex0Fs15-WUePzazN7WtU_JuxwoLL57K4Zl5lS9nQzg0oPIcsitSnNseACNwFoFHKIOs4lAk1rKEKsKhZX
AlgcGbxLQBdehw18KdtB6bKR4Qk8vE_spKs3fdMuPJZReWy2ytE8PSC4ypjmi9P_ElzJMRlkfSFCTL_Ric3JykPoWussK3WUWJeKuREWUcnibblSb6euMUQR
mHtR7G4tncQvumQN4fCc5j4ERkY2qpLTjFbNcGYNWujF03VakQlnadph-WxxkCF1U5ph4qrt-Fev_-5VtEHn4qytYPcP_Ee6UDmikDrOq1osNznWkk2utMWq
gUb6Rw38dJIrRySAEKgj976UNpguXFxux9-VtCGUDo6FCGchFxa_ZZFKuSiTS1Enk4mkeBiHN7DBTmDNtJYzlm
}

EntityColoring(chef)
!define chef(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, chef, chef)
!define chef(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, chef, chef)
!define chefParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, chef, chef)
!define chefParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, chef, chef)
