sprite $chrome [64x64/16z] {
fPO7bkCm34FD1ZBtl_3APP-U5LXA9dzw-G2POcLxGioHMLMPuRfzXqNMZOJ9fx96KQ0VLQCUILjsewRaV8Qe9I7FvLbpvYCOqIbETQ-FyVdgQsAkhudPyD-l
eFKrjdKawsjIfjElGQz7JLZV18vyrH-uDj00wY4Wy_YOtec1nkiz02QjGKJKp0bcr_OxEGQuR1qP4sn7zTp-e6u1aDtIPfaUGMft-K2lyQy1NhURLXqNhZt0
h7D4Aowg1_WvLiVF01lH_d_8L-F_xIg16x4tAVFxFzOLaCTjcZUE0EABeFCw0wo5vWZYk3r7HD798w3L6_8D61t0SD8tQ4L80jW0wXW6ADsK-ye620m3b6oU
55_xUQmVIOcrZznz90NDruMFQdx-uEUF_KZvPV-6Fjt-ndmdlcGHKjZZnp3Y3uTPiFLLyORG0LBO-BA13U3ql5Bbp_yHRG7vVbY86l4DRuIC0NbUm9Wlu06A
-oi_CL8lBJOU0ZQDhCpAqEC7O_KD0-CwMnhN4Ub4r-lyOeH9FtsGlFxAVY3SLCq1PDgpBu4PsPZKDspfOrBVy5MzJtIwmRfUPUletFUvth2P7_Ikl-FFEkZo
8pwlv_ew81DiU8PntudEKLfFRtcEEAldvHoDmO_1bcs1tHDczZeXlSlKveW7JYRo756FW9_gnFq7
}

EntityColoring(chrome)
!define chrome(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, chrome, chrome)
!define chrome(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, chrome, chrome)
!define chromeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, chrome, chrome)
!define chromeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, chrome, chrome)
