sprite $chromatic [64x13/16z] {
dP45eXWn24I7mKBW_kTjDlNs-wn47mg0dfac-A8ilulu9RMt4HU0V-02_Sj0xZTnQOMstZapI1MePdoO7mKCLtxTglB7x0nsU0i5pK8aWg1Rak40dwNFKfWy
2yaapzG8Eo2mkbfZQe_uxDBUkscpztIDOwrgoTdEfaxjdUboBV3C01r2a0sqUPzPuJ0sWWci0ir7SLuEAu77FmYAylhN_f7_vHyMYB8p6pkyzbgZyftV_YD_
mlXz1kbbIt_pDk5Zb_V3-_3w3nu-scCnWmegVzIVrKiyWL9R07ntGEjP8r9MhoAYKqhEi1sM6R_x_mNvGMDbAhueHcQwV0t-1W
}

EntityColoring(chromatic)
!define chromatic(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, chromatic, chromatic)
!define chromatic(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, chromatic, chromatic)
!define chromaticParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, chromatic, chromatic)
!define chromaticParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, chromatic, chromatic)
