sprite $cirrus [64x50/16z] {
nPPNqXuX30I7e0ptlwxhJr_SPIdBeTzxo4XuefAOHxW9LJnG6ecegd2lEAFGX_k3Qx-biZuWL0vjzdZ1wDCMVUKWeLiSOBMm7Y3zHMUFGrnFO3mYSOARwJ5I
DdJxu3A05wD_SB64vWjzuIlXWs8BVHrGbxF_iTShAClPNq-08k4pi5hzTK2fdl8xHShdzTMx3bWl_zhtf1__sVUaRqbVa-UNlJ_P-vjzFydtc_y_rh_lskVi
_vdylxFr8r-_ylKpNx_N_GFf4NsdVt42W2PlDfUD_kdUvRIN_gdYZ4gYRcOg_RL_O_c0UyM_eI25Z5n05_mkXPLH6KpQY9Gw0Lp1AdLBZ-5HU9GnhVhqhW5C
ig5Es80_L_xX4n0Ag0E3FAXjxXo-_Gw4_FX5Op8sQ5CQFVeyEir6hOPZ1vvp5Bhxy3aLDkTeUECN
}

EntityColoring(cirrus)
!define cirrus(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, cirrus, cirrus)
!define cirrus(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, cirrus, cirrus)
!define cirrusParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, cirrus, cirrus)
!define cirrusParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, cirrus, cirrus)
