sprite $close [64x64/16z] {
dPO7ikiW34MjSYdP_uA_4IB2Xc7-ovcMudCHJSbrW1KtodJzWgGl-aC2qWp_qIRNLVo5_AAhhGB-7l1KyBzJ85_nq2C0AiPXDmIm9vE1UIDTFYMGoHFWKPMy
M0DycO0v193RbWsyNN50HLHJ0Boy6mzOTQ-NkvaCopHKuKj2coaeNFVTWiH4MW2BlNHBRjRX_UNOEqPoq1xs0sNmUmO2-owkZJsaemRSushVqvZ1ktoDydDM
v59gpQE24KMhxvBxb4lz17KiPFbObePFgq-QNGvo3q0slrGxrXi_GV9dHqaJsMgIdPzMDUOGlb7mt01T_5fBJZ0I405rLAMFyH5VcQZwg4yHlbCrJa-fja8c
9uqxjWcO5XXV_VFfUmGMIEYx092M273TTicEgRpqDQ2zB7D0xWlQJsVe2pewEOl04-uHrLxaVayuz1Nu1AIHJ2lNPKawRcrdTUDc-leILoj0JEytq7LrVw7x
OmWBoAsEvDLfrzFHrs__ig7lykjetc8azrSGK-nvtOUlhnWu-J5yWxiVJScgF_dFmqdL_DpVk7xquJNQaBRrxVH838-JFzPUhLVthKUxD1J3dtpu1dcpJKrb
smIQXq-wrobMk7LaD3Frur_5S1-qzLawzeZs0ynsZ6wot8mZYeFEVXFDIhwAlIlok6JGLIVfZ3ytrQvF0wCZWIv94R3J5Vu3Yt8BxEkwTbheVdGJlTkPRcWq
jUH0wQshfZ8zLAO7egVbv01Cr6KIJJb-rxpRyHM8f1g-WrATvITfzSMBAodmSbTA_rCGz8rjHLGJlGhaZLp1XAqVVxghbu5KtvLp_5jQ_8R_ocGyvb1lIib-
jHQVmpSFH8nHGWQK_6HIVxpvo_7mgF5dcU8iiUSEIV0-OEv7bsqbOJfCF7S6ZVAd0ZX-fw9JTE0lA8RVtKwc6uPsUoG4Q5yBVFPhm0hH8m6DkSES0-mfzeG0
ePy2A1hVKzTh3x4ugfXhx3uwojS1Qd2qqJZKO1RXe_mUa9Ot2yU0f7GnVj2jPkS7tUz88DSFY2T03eF_0m
}

EntityColoring(close)
!define close(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, close, close)
!define close(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, close, close)
!define closeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, close, close)
!define closeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, close, close)
