sprite $cloud9 [64x59/16z] {
tLQ9RlOW32FaCE__nBy8QHTDARJJ_NiNPJ5sZg-YRT35C0PCUli311W167zbSx03iFvHVFm2lbXG1CaHQ_b81xGJKMV5DmUCNteK1xwh0HN1wqXxvzxfL7Xw
bG7LaVhM0ACC91mgG2ogmcIvTjsa1MpRGp40g-5P1mESVUbvMdFr23-fz5KNLPikgt6h-Q347oiIq7I2OJpm6oANu2T0aleZtwRbaZ-WgIuPkNwCck-mIB50
CWUgFzBH3IdOUNuwnK9hcuLyFMXMolI2NquwePGfxLUJAgMGsdXvG1s8Hxw_zpi7-pdFiG40tiWV-G_3cw5xlXta1sD7l-m_Hz6MhvlUXpzxuLutJUxOgk_T
Wzh6W1ngFw3RvC1x-i39dlN6E0t7DWGuDNTlSPpe3b9yPHkrZ6xumWONjpK0hxYFrp5YDSCEPYgTsly5LbEcg00VWgbprJa0qWG0-fQj7fZfkAOKVBhYnAIA
6nMPHWXE8PrykQyBHFx75-cH_029o_bqejThnkP0pysfebWsnG1ppzQS17Dz5ve_whzM6RG5V-QnzcSqQFrk7kl-FOuZpFNJTSDJaiWBrmRSEHhV_tIruJ-K
-17YYMcx0q5he-FMTtTw6o0E_pAt_HJxnOS4VxAmqbePC0j0mR_iGhD_mOy-0TShMdo5dq3otw9pkIow6lispmsZHg9B_huO0BtPIaPmRKIZt6rQ-m3AjI0n
G7kBTilglmbvb9cGhISsQ3VJ-xLkxSzmEhM_G-3qVm
}

EntityColoring(cloud9)
!define cloud9(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, cloud9, cloud9)
!define cloud9(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, cloud9, cloud9)
!define cloud9Participant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, cloud9, cloud9)
!define cloud9Participant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, cloud9, cloud9)
