sprite $cloudlinux [64x64/16z] {
dPU9bkCw24GBa5ZA__-_xmLPiVl4cUtEFjqb8Geu15_H4LKyMEb3yDUOPv57GuRX7n3psaVK-7FLz8ZmQG9Wv3uX5Rz7P_8LzlfLKm6hOy7VXc3dPHSC1No7
C071LoHuVC8Gs3x0CIQ-C7WyGuDU4KGfdfXSLctk1-XrWA4Uy-1idwUflB3XTPrHrnDAb1nFjpCDFv3vJgTVpml4fnF6JhIOPwKFlHcoNm3VZn4UDDmHbW4M
PyHaJW5aZBVx0I1t0DulkX4Ew0_loTd5DqvNATWvf2ZNWHiTkqPkT4XQ8UqCvsNHHBOHDoIF3reZLTgwX0hMMnApVx_GkaTUuVyJIGOWHMjt81DpVKURINkG
izpazYvhQmn-K15GlXsuPK2sd6bBDjrzRXSdgKWQmb2x1ZkCaxofPKHLiQaOPsaMb1Cn4Ul-bj3s-JjR7N7Nhuuv11ihntHuOfvUzfLpHR_aPJWHbS_ELXYy
LXTKXxmJ4CkJriZeh2i-K01UAu5nwlEwlkMMv9fIWYUIa3Rkr5U__knFMB6JAD1urXT5k6IrzSi9tREB3imoF24abAigkVIYkYBMEhOyEF5CjVxgf8BEsQqa
bpmxh4UYOBmrKi8oEleuccYvufds_qY88izldwpN7yOzvOA1huo9fC15k6VnKRiQsvV1YU-OeWnZOYozeWuUkUTAGchYbwZ1Qe-1QY4dV8_8S8ZzveJQrn_-
gXrs56Ss0qZ3-AKyWTEiZgDg3uK15mIXlyeWI_Qaz4vxvfwA4CDaOYI-uQIswjt4T8UVuNTPERpmXNdGtgMsqf0sbtkSgvKdaef7bALlUQmUcAAdtlfwZfvq
ZrJ8xVQMzLLBBtqznzVxVG1Qxq7fN8--Pe7mrECH0GRt9dOEmd7NswalF0yWpPx9TitSMe5r-iy_9w8Wa90FkVimkIzA7DVyplTCdGMRFuUG3XDfeHckXIxH
x9bSPnLNzqZIznxBHLMv0VBUvXIDBFtPr285PKBgdEzYm-D_rbOYan_RPEnkMFyR8kJ4MfDq2Dx8k3P4Jcp66kfxA0r3zKmbs-TAzpcdHv77Wtoz_3q618he
0xMes_Gj_GX-Ev2xiVoAI6BjC9VsMiLDVWP0kUO2X6U8bcjSywwk2NZWeg_kxMG7u7jpnkXDRXPvKskMu8wtWsS0TgrgBSOBdL5LwTeLyD6ZyGhtzBQa3spe
-b77lB9_aMiYDG78uqebsYin7Py4uwtobP8DoNnHRUEp772EhQAtgSzmu1bBnJWFYAlDFht_XenhpKy5vcVbrC1ls0y_5_3j-vz_39NaxIuPdaLMnZJ1dp6A
R-lmJzm_YlXryH_JSHUl-ld6Vm
}

EntityColoring(cloudlinux)
!define cloudlinux(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, cloudlinux, cloudlinux)
!define cloudlinux(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, cloudlinux, cloudlinux)
!define cloudlinuxParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, cloudlinux, cloudlinux)
!define cloudlinuxParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, cloudlinux, cloudlinux)
