sprite $cloudacademy [64x9/16z] {
dOj50YrG249HGUJkVy6_S_YE7G0b4XzJemqvFwOn_eAB__7WNsJsbJL0SvXl6LFrDT67xoF8-bb3S3337jQWHkTTXKJ7LYQEmWwVSu3yw3FfQEEdy-boxzvc
5FLiRyrW3s1keMGwv--RtTphR_Nk3UAtlbC_U7KddRKR4NoKel3sxBTX3lruFbDVwtsjJrdD3xth1TgXQqc0tX5aORmBMSBNl2nxP7sjkzrsQsf1LXPDwOQ3
3rZNrrmQucE-
}

EntityColoring(cloudacademy)
!define cloudacademy(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, cloudacademy, cloudacademy)
!define cloudacademy(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, cloudacademy, cloudacademy)
!define cloudacademyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, cloudacademy, cloudacademy)
!define cloudacademyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, cloudacademy, cloudacademy)
