sprite $cloudacademy_icon [59x64/16z] {
bLU7UiGy20iO6r3V_td_ORn2EdBgheyF8Gl8NJ-Xg0FmLguFKHqJBfy4iW6m9YAj_qQl8mi0vIl02ZY_pGduMQ6yZYK7EBEmLw4Dw3cfjbPfvgrlaWBQDKP7
X1ZyXLGLuFXnn1P0Vir7r1DOI1KOTJlqeY8YJ8ym2VDO0reK78W_BmKC0Iq_cIUe6HOij3jWV3SFjDMg_aEe0Dw4kOW2kt1sm8McUPI2u4GBNh9gQqjuyZZE
BfWeJwFwo6lF-pxJwlTM1VKg-YatCotFM5f4gyCjU4idwd3Q5ZZwAmJnbSbF5WPG2Rfrwxb1UcJrMmK5gAqV4XRaZDr_ruUzpB_yTd3tULlYMxejWmEMpEAL
JoajyGt64Q4fDEOWKJKhbmBqUwZWMpZnB5QJ6Wf4hUHOC7VVpMfZcDOaXdzvC8gq-sA9nIE1Xs6Fh6M8e6NOKCuBvyBT0XejxuUdlUm1veC1LRKMsahFH596
Y8TAMcijwyAz5v7xnW_lMh_8tMVhl_9Tvz3oJ92HgoINwMmPfBoJv0BxhMl9bkUA0vPET3kgMkftFzogjxRq1xbKaUwTLCzAk8yRhfLMuIbf19J78kDElXmT
v5EpjFleM6maKcgypePLYUcgooWahSNW73VQeXBIOybO_9HU50yVo7r_WIx7tVy-NqMZpCZpt5zrUDXm7pqEtolBtTGV0yPR_vNJdhXAs3iXxwyqczPKi8lD
jSGEF663lt_5RCgXUbvcQPv39QR4KkymhwIHR6asrKcOqa5Kpx_ihmQ4J0TZtYOt-db_6NmE6Ct3tzBodvvH6gJQvQCwiVruTmnUFVUNkyhYmCU08Je8ogbd
njoiqPy9svZvyDImV7SisLxF1uBvihQuSk-hbbUVj2a3ntWyKhJ2H2pws5y-2x0g8jNk0uSjUpGJvlp8jI5sfddAL03pEDNoqBJKrcgXclPNcAV_bxWmNJ-3
v_xoqzB-wZdSuNDbQECbfBm85Q0z3UBN6zWZXRvB-bmTPC7Z3TXt3uLU-k4Rirh-GtEyplbyehToVGIgbjybPFmB
}

EntityColoring(cloudacademy_icon)
!define cloudacademy_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, cloudacademy_icon, cloudacademy_icon)
!define cloudacademy_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, cloudacademy_icon, cloudacademy_icon)
!define cloudacademy_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, cloudacademy_icon, cloudacademy_icon)
!define cloudacademy_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, cloudacademy_icon, cloudacademy_icon)
