sprite $cloudcraft [41x64/16z] {
xTRBbYiX28LXhQYmWRp_u_Q5jZgaT8KpElSz_jRwPsZ9TWFLagyIjyuzTH-cVOpuU5tbqUQONbU_nvPLVIIClDewX0RoAWiJ4V8gw7F8givsi38krJti0k79
XbUty0OmiqYFrHLM4lP1ALGnOQpoELMSJ7J2M9s3tdNGvrZH4Q5NpucPVK6HqK-uLF6Xr254UW_mKlrqQZ9O-i41BbNzd2cubee0X-327Cgjb6TurrYTJ7if
LsXgSFTWHhLi8CHagUwWYAZQjRg7qAMwXpAXuN2GGHiJfB3zMlWV3g4VWOr71r9u47rTFNeDn_U9P7i1cxDmqlRme17Fjs-ii0xQ75AXAspGzP22R-KP7Wnc
2CKgCNefJx0FOP-WnqDQomKQU4xlPvNFzp92UHnI2zKzd8VKGdKFvo6rKDt3ZwhwnMKq1rluEAI6uTKz3BSAeRh2-yaqLbSuPqQbvD2hAPpL77erXrxDOApk
Tx3w3JSR-NTErRoQhfkr5Bq3
}

EntityColoring(cloudcraft)
!define cloudcraft(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, cloudcraft, cloudcraft)
!define cloudcraft(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, cloudcraft, cloudcraft)
!define cloudcraftParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, cloudcraft, cloudcraft)
!define cloudcraftParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, cloudcraft, cloudcraft)
