sprite $cobalt [56x64/16z] {
ZPPPmi8W38IpXuhtl-w_k0OSYj-ZPR9CWYsjO36F_2TSXRv3BDf0XZBjq6o8K3h3igr8s-V29Cx9qNO4WsJj6vGc74Ht87GQG3Ko_3LWQtjT2vWji2wo-0fa
IePqILI4m19x7KWdqiXdECuvdqrDQMjXGWzOutOoPaVbe-kRgC0cvPJHdHnrAOI8UV3MHemWacDK1dkqtjxWnNe9hV5qeZcTU97jyRUt4h0tJ5OxcBv5Joup
gxl9kanifRP-uu2rvyhBwDS7lJ7DoEe-jclX-13Qeiou3XndxPLof5z7ugIz_AoozqU0pcjTpARq5BRBNUSqKDFLHtByAMy5w3rZWxhWFoR7Bltkqu6SAHT_
GYvTjheMVzHjuUmF4wNKkVN5xxuuannb4Div7CynN9vp41e8F7UTvzw-tBCSPLtWzGEk7eFCQ8AhBha-U9TwiStzKohOqU_Ub72uGPyEg6U6CI44_xtloMAA
naOB2asIADPiuNmAwx9XD7Jv-H5yMfhD2VV--BGSrYhB7kEZe9Xqu3t19VpgpQd4cLQb6kbrjHHjTpmAI3SbOlLxEL9F6V2q74YccCFT0Is69lpEikeVllXG
Ln42mhrEvh7Ec6Jx80Li-9vWy4Mqn_3cxfD1s4zLGalOSw_2A926CNs1MBoq6Qwpw1S
}

EntityColoring(cobalt)
!define cobalt(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, cobalt, cobalt)
!define cobalt(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, cobalt, cobalt)
!define cobaltParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, cobalt, cobalt)
!define cobaltParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, cobalt, cobalt)
