sprite $cockpit [64x64/16z] {
fPS5icCn30GjFp1hxd_QvLN5bh7I1H-I7ZEP0NJxM0e0S4d-iUQ4ooL6JVRthlrcT2cETko28UnN2K_157OpcoAMv6ketumTHbLms2HqTOzj4cazu81CklGZ
achx8R7kUHpZFtHYd7CR8GBd5Ed31msPZrfGLETUJG0dxq96mzNl-qoc3k3tRrMjvzuO5ArBG3FRRD8LUBKk0NgsUxKGCZufrfWg84pcEVzkQQiBjzRRyjwc
z_X3DqdfQgwcEewljLuPJCH7UjlXp_sXtnETNWc_025u23FzAi3LMMqvogz-fhDyeVQvo6-qqALyYm_4zolzwIvNGRg79hh42xhwSQ5VwFgon1QwoPYMJmL-
fiV6mp-ijD-kTDN_pNSET2Hr81pfxELNkzO3Ml8ZlwQkpg9tPqwm4BpILUgDXjTa24xhG9W6s6f3ZTP8LHbO1-Jc7-mlymjw4Y24yIN9wUEZfDGUVs6uVTdL
rK47s08XxHx-eQlZthxwX9wU3suVGUkuJovFGUb9RGbJWkZghBkmGwnql5zS_zHwZr2StM0JZYZMr5360NoP5afVw6TzaErN3v18Pi1Ti8HVCuRyid1hfbmH
4_9jbbo1qIU9FOVUf2EoisOVUdoM3CxX7Sa_0G
}

EntityColoring(cockpit)
!define cockpit(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, cockpit, cockpit)
!define cockpit(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, cockpit, cockpit)
!define cockpitParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, cockpit, cockpit)
!define cockpitParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, cockpit, cockpit)
