sprite $cocoapods [64x64/16z] {
xPH5eeOm38JZ3VS_yA-3ItYoxBS36fb9m_3FT3gTJdDx4UrtmSe4s7BvteQQL5hXutiXegoBCsrGn2DP4KvWdq3VUghcP-KYl9I0r35SOeYmzec05P3zDa2k
o-Dy6u0ZtV0cyAaiZpCGFSjcf3g5KMtdPvkxoSBypGdbDr6F40BFBQf7w6Z_X7A4LiHN3jgj-krl-kMk_o3Vt5iXpD_thmBwYXNMNGE-U9DmhnJ0kNQ4fBn-
G970lmMDliIqVtft_qLL26WnlEB_mtddye8u2yVmIfhG2ar8KxXN4hA8NWXEG_cIT9CN5iVrEfrEf_C4
}

EntityColoring(cocoapods)
!define cocoapods(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, cocoapods, cocoapods)
!define cocoapods(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, cocoapods, cocoapods)
!define cocoapodsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, cocoapods, cocoapods)
!define cocoapodsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, cocoapods, cocoapods)
