sprite $codeclimate [64x7/16z] {
dOs5OG0X300lyeJOxxzjVO8Un8rVf8p_8exqEyOF9noD8po_AfIVs0qvc2069X8HTY90Qa_ilci0rVVQLBTCLKjNA3QPNe4j6KJ27BcRllSYzRuRORdhO2jm
4-Pf-rPz8HEeWutqsZRFD8pevlaQdxjx83T0rv4eTBnTrli-S5laTrwdjaUwzf5HtUDVuyhvkUq0CPDICvV-KLsEz8pdzDCsrjOnaQtVyrrM2fo4FzG5t41D
mVmh_8dLN5GK_Ik8WRj_0W
}

EntityColoring(codeclimate)
!define codeclimate(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, codeclimate, codeclimate)
!define codeclimate(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, codeclimate, codeclimate)
!define codeclimateParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, codeclimate, codeclimate)
!define codeclimateParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, codeclimate, codeclimate)
