sprite $codebase [64x12/16z] {
nP5NWg0n289Hes3kV-3LR6_pEjzVqe0q_0sly0CdFkJp_QbM0cO6M4dd-NrgzFKxgGCWA1M08kc0VIjvXoxlba5Rl-Fttah7LChXEXi4Ow5omu7D35cDEgap
ugcCARb-tJvU6oGCtdYu8CEIXU5mV0P4tp9UiT-Av9DnJdQx4uiSNdLSICKcA33OB7C5t9GD4Pu_TX-z6p1YOOJ2WzevHOVuq6W0k2xdatwR_sJQZ_aPJuVb
oEHur2gfqEoVkOTH_Nt_aTyTrg1lAJpeMNYOxb8kyctdpjU8taeVUAV1b4W2bW9ZGmqwW5NCDxeoF5otiqGWz6uLNY5r0YYHXmWD0HWb9Ru
}

EntityColoring(codebase)
!define codebase(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, codebase, codebase)
!define codebase(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, codebase, codebase)
!define codebaseParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, codebase, codebase)
!define codebaseParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, codebase, codebase)
