sprite $codeception [64x48/16z] {
bLQBiYiX2AkeGFh_7toxnkxWwZrCSvxLYII1SVVrHAbgZZVWrkNr8qepu7q3KFc5tKcEWDS_618t6zbFmEI_zGAzs6G3flq3TNnN-f7UBD0hfjmkCKfC2GVf
PYLg9xjDfaZvHd8KK9HdhlG-bAXZmBfCNxf9nt8anRjSzJpsRpZijaa7QXGpA9UTHZO6Zk7JaY-hDkYVVqPSS6qYKkSeeJsaEqizpFjdoJ0aXsbqyXVfRp2E
HJs4CfxJrjVeEvZoQKr1OIianknNfUSyNujE5pjzbSucFLj9ZyuC0dQPUuNfUcnFPVrqIXsDPN9xUdsKjwdJwr5wJ6uTFSZr1rzdUagOax2ZNniVpZ1nIxBo
aCuM4vjz6_9xZ1GrIb-Isxkdhq96M8G6wSVa2COdMEG9Eys1YSdjUD_yg4y7YTBtv79--JBtv7BzCyA9VIpp_BYU9BVsxnbHHP9SIChN-I4qIMwTtpO3sA-L
1ENYz_57drFFv1BODB0NSylfx1Jg4F18WEpSGBY_zkty59qns_4vASXSCEZoAhvTZvkg8peTy01el3eCsG3UishVLmXOa_91xOuvWFAt1I7jlYv0tAy_WcGG
sdst5oMFWBSveYvf16CC-0f7k8xFtFCim_Yq5wbrUcuUhf340iCBLeKHKdu2yUaPhhtLshgHp9xcA8exjmlR6sWAuGaBW9uNtmqJO1m_GRhvrAqj9_y3
}

EntityColoring(codeception)
!define codeception(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, codeception, codeception)
!define codeception(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, codeception, codeception)
!define codeceptionParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, codeception, codeception)
!define codeceptionParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, codeception, codeception)
