sprite $codepush [64x30/16z] {
nTJLOU0m54JHUJ3gl-FTH4mn1iwNwPebDHq8PXGS4EF8C18Ar710dJrRUsSzXQfW9MgLOfHwPrnnqh4bNt0AI7ZCZFlUc8N0IUXxVb38zBA5uG15Ik_y0B12
n73SQ-gjDf8Xid2jP-GnyIYjyQoNjMVqk6zkzmIKXIpFVz1hQSIBs8FN-dnXHNFd-n__VqreuYeLjOSF_KeMbdlM0x2ZrhYXGuN7wnyn3j085UOuSJ07kM1r
V7d1JHmu5ZzxUNztUVtRfrSEz6-VNj_rXdl-0m
}

EntityColoring(codepush)
!define codepush(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, codepush, codepush)
!define codepush(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, codepush, codepush)
!define codepushParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, codepush, codepush)
!define codepushParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, codepush, codepush)
