sprite $codefactor [64x10/16z] {
dOy5iYKW30Gx0W4cx_xNtMBzktH9N6PEObsSRr55halmBSp0Bxp4Fht3_hfRap_eLphFESvVhFYFMLpzWr-idUru016owzrS6d5pDymE--MPXStvP5v1scXj
gjKsf4KjWxhUQ2tNu-QwYoNfsVzoG6aT2c_J6ctLAZA7qB192EZmvfGzpFWV1U5ob3BaEllt_NsEJ06uI9VHjWTPPVp7llftPRlcUDYfMAm2wwncLnwyVrN5
6J0d_-EdYr1FihLnTJ46K7tM3UTr5wbEAk07
}

EntityColoring(codefactor)
!define codefactor(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, codefactor, codefactor)
!define codefactor(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, codefactor, codefactor)
!define codefactorParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, codefactor, codefactor)
!define codefactorParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, codefactor, codefactor)
