sprite $codesandbox [55x64/16z] {
rPPNskiW34GDc1RQ_bTxor_7aK_QM-Or77z2CuhOK6cKxMc5jjRg-tEGA-jJ5_y4bURwKN4FGdjVgf4UWNnTrshXBfNdEb6zNMdK-bGpC-GlYyHckC8Ccv46
0sX6Q3-tQBQ-SMw6grf9E88ZQdzRq50Sxns75lRRBJ53GZ7JRtkcjE7wM3QV4JEawQQeo0dQMxvlaHvXHOaUv1oyvVJmG75wEB1Ff4STCQf3hBDI_uTqSvVq
w1LjO8jpWcdfUaKRsCqBPjC3WRMOdXZnD8a6C-bfmUGUiFyASj0VFmAOpOAM31Z_LKx9063QShK3C31OpMTCbMGA4QDVtKsiUVZLyz3PRZ7cAtW366-n5X3J
eUFbfvXwGfe1CJyNAo8MrXjWxuZb-G8sot6KTxRR37ne4Y_2oib2Yx8w36QU1RzokZeC5k1Pi9dL8PWhC5kcaEn-CRiOUAEF-8cveAi3fFMCpweEbRDyU-OD
Ygl3D9sL9pmVGBWwMBmwdb8Sjo_5Pjogxoy
}

EntityColoring(codesandbox)
!define codesandbox(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, codesandbox, codesandbox)
!define codesandbox(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, codesandbox, codesandbox)
!define codesandboxParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, codesandbox, codesandbox)
!define codesandboxParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, codesandbox, codesandbox)
