sprite $codio [55x64/16z] {
xT87aeH028LX7dIWxt_XhOcubBnHAsxuAqxu56ob3d8Xg2gk83qDDSAPMn77484SSSXLn54TBY022QWXz4WWY4E2E2IAHX0DqlLAS6_daOYlDGi8ifgxBn-s
Wugz8KzsWxrwoiNt_YWcPOSQN_kpjORjeAUBxnEB5I4v1ChikM96pu3uFjXcKY5b5lqIzi_-cNVPIqqvyscIWxLcXiHo8rtPhDqopIpNiPtlPZBq_LhCjyrG
irWHzbt5YbusL3EAIPsu5cKuIxLcgpBO9AnCHHfX5Rg5Ve9jNnSTXzaDHJOFCLD9TSe2vJ0eYwLoEWdRebohcAcmqFUOcNnAHx2q5Czci3GVhmLBY8TnOtI-
yZ1cAn2j3JBV5m
}

EntityColoring(codio)
!define codio(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, codio, codio)
!define codio(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, codio, codio)
!define codioParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, codio, codio)
!define codioParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, codio, codio)
