sprite $commitizen [64x64/16z] {
rPQ9ThOs44CbNOpx_Y_SXS7ukFwJaEwzMJz0isZc-A1l4FIdIFGT7F_9TD6VOiYjbPTrMMiT_jA7UDK7fW_9btfh_SH1jgnl8GhODc01UetlNxOb00JOUaUg
Qd2IM-_OV2y_sB5owMM_4WRPgsCXaY5VLLqz2woDV6cWKxzAlm6MvUWp35L_OTkRhyad6yYJFCVPByuZAXnRBeTsB5l39Sx-qqFlg20kZnRgS_JWSoX7b3EQ
Hn1a2U7WM1vjqKjpa71K9VruEdImWoP9Y4RlHx-UdouULuGA0AGacbHBWP6zjxN5SrHG3qs8fMKrqaUk2TK2se1Rx_X9rNyl7sv-l7aUVHs_FjU6hfrduwge
MEBQcci5TnFzIKCltVqxlnLcxSUxWTBVfQ8nXKcFiliozQF-DjApobtEdDfmQgtjAh-wTya7PKt5SJ8jkFHMa8QCUdQXHd-riUX7b5Xm3pyrnOM-19yn9gLd
UDmtVLqyAf_9Bdwf3qYMjUhjktv_M7_f3G952wx-XzTjrTTCdjrGh1KBPWefgpwQpGKF_SRSaRRFxxpw273feutQaMXte5LjhVHp-9EC1iQIjcK6fzeTEkp5
s-OWLVTZKhkERwgLVWNvW630Tm4zC-xqegu7ignCCK_VenwSJ2zgUI2htZNzGTkFElMoG08uI3Hn8eC5vCdMh0UtIswD_CvIkAMaRir--raVJEkFl0fGfdxk
KkcNiwltFluxfgNL-uO1L7WTVZzpPx2KIhdZn1gaFQbxYsO21ybwWJb-1Mj-1ibMG1y3Q2THXZyXdwRTzFEjnlxoFJn41gGnM87UOCcLgcOPEJXnzcom9uwV
qmsOh-sE35_gdSUgtQ94Bx2TvOtgspWYcpIkeA-8jL9In_gdiRv9je__Knozu1S
}

EntityColoring(commitizen)
!define commitizen(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, commitizen, commitizen)
!define commitizen(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, commitizen, commitizen)
!define commitizenParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, commitizen, commitizen)
!define commitizenParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, commitizen, commitizen)
