sprite $composer [48x64/16z] {
ZPK7bWGh3WGb8M-u_t7tGLUR_Jx6yYgKdS0O-0SgV070AeV_GhGkDmHMLVWFD8il3W6dHFXB2E4Brrh9gARCVzbeIIeSC0H0H8lG3RW2dDxEIs0WSLb-yxNa
xD8oab0DO_3p0XrtQraXo5TV6JVCTSKK0YyIma2uXF5vXBb04m30JlX577KINuZ0nPV32eILVkAv6-4D1r8ONiZXeYoQ2navK3J6pU1t00XVFFuoB0DAnwKw
iS0TlbYGC5wCu18eWaJishKGzAEZHcQcqUEl9sAX8095AI5Am1i_wo_AS665CrsAWFXxyIHcZ1_iyJ4GfUALvGA_i3lXGovuuP8jU5a9Vq1ItlqDNkHsV0Y6
Fq9UULjHllEBtXKB_WBINZViNSWC3nIzu2_HGaHWHuu-0KLtFX3-Xc10qfdsuyFrAU1lqT3iiYLMi60PFEVxbvmMaqfthbPdEo7WjmrxLgM-rpRE22-en65f
f6d2YvNJbLaz-kGtlHzPg5uJsR92RbfbN6eSBbOtsgexmIG6uK3I23uPRtAEmG0jUFPRcHsXjE05nblFl5zwJgy0cLFnq6dLbQvC2Aew6QVveJDgpjGTUEbL
3T1LtKTecypUJrPDvNHtvQZtI-yfmCbBZNJLdeg7xDldH1t_SlAhyZBUjJk-v4naLVNEhiVV0DgFFxthA-VTRvpCtlEJRu_V-rS_lRexxqNiTv-nR_utFUia
HirzXLli7OyV_tJFMtVsdigelS_C2Qdz7By3W4mUUl8U_7xPfvvrHSrPpNF4w-lFvHv-H7RbTj1Jl6Twxa0NVFpQ-yWFgPAAY3BxkSvpHArV_nJfwL3XHOZ0
j5w_r2TdTizqtZh0S-FlFHB2CXKc3lGp02Zvf5SD7dzTVtBsDTGiieQHgo9C4CczNmDmM7tyojbv1fQAgDpHD65PY2npJhGT3ZpLp_tAIMCF9h5JNZpbVAt9
wcUxW37Nhzb5-C0Ez5vutsFDPhYyRw2wsl556CN20yXS_sxt8URpyohmogzYm8Dspvp03lYWqtcPqLEOpLIK4KaxQzVnPy6NrNFpJnGX6wlBtG1LrcGV7-47
l9tkiULf4Qz_Hc2LpszNipuJtqvrdkn0JiBBwp9FKlSm_1zhRavr23DUwCckJXPU1F_7yomX5bwaRCsndO0YFtrMffc9p_KBm8nPlKS1UjeGfFOOBtWWCreQ
FLtL3EgzfwOpbDeHzInj8NoXExiiPn18SZAYqaCIRIQLu1TMZrizF8SmJWK0xCdOKs_v2rqMiqQDTtSA04QWZo_uI_3pQQdNxDOA2gVVnZ_41AoQ15H00vxP
uRE5iXPefkJ_tLVa8cgrmHYiGJSTBowFb6Lf8iC__Xe4Y00ksHtJsDdQ1ANS2DE1EXtmmNk55aDPzoxBDKwhWRkM9qyOPCwlloUeiZpTctIo07YYbdPrx6uP
vac41sG2u61kG0JIU_Fk2FTx8KH5u420_m4
}

EntityColoring(composer)
!define composer(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, composer, composer)
!define composer(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, composer, composer)
!define composerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, composer, composer)
!define composerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, composer, composer)
