sprite $componentkit [64x64/16z] {
xPG7rXmn28DbGE3xdpZFiqpRRZl9NxzNjae83nWeHX-30a3euoWAVGOrdu8JvN_vvL-DrRQJjC44DXc4bZ66ePlFG9dIMq7HcQi9fK27iwCq8CFP5yRkHzta
ygwSlYEh6XeTuvBma3sYsy3sx5wZqRKpYbMkKMkV0KdPibjjz1cuxgtN-jY0VD10neUOMBroeEXJEOsNuqDHBO34oS0ASXgCZyy_WgMOOkd13mOANAQHzkp6
YsWEsCum2Tc-ulFvYrfRhMt-5hcdO-gViGYECtJ--32_R_6l2hBgOHtYnQKOZMmuHPRbSntUDAYs3x8LRElW3RvZmBrh4-Gw-4v73yNKSWvw3FO7AJNbH_tR
FK1YtuC-0nS0sga-zr3i81ymy1YHfq5JvrllfMdOYZjJtWkRHyjE7y4OYTF7IFa4AHyd_Flo2oVrCYStw5Hw0Cg9wlW3
}

EntityColoring(componentkit)
!define componentkit(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, componentkit, componentkit)
!define componentkit(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, componentkit, componentkit)
!define componentkitParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, componentkit, componentkit)
!define componentkitParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, componentkit, componentkit)
