sprite $compose [64x37/16z] {
dPI7Rkum24QpmPFtVzkA1Ab7ZZkvemEE6Hy_2qpQjKnDyhRyQ4SrixA_7Nirw_83lMMpAiqihOCZcRLirivlw5MV5F4L9jswU76iRRJJyswVTHnqHEzNDzDr
Hky5RtigPyBXRx76wrrwOcz8zOxdU-nFrycRdVKE_S3CJ2Sz9JCpcGpQHUQpHj4vWjgHYXqqxnTy6GlT7xLTYIxZAlIBytPUjPgr2xqx5cKmbKGYwksyI6h-
OWJThh3hqt761d7VWbVHxDXwFrptOJ7TSJT-Zlj-1gygtaHd8mpisLugHq71HnDM8uXstHfD7EgEuBs4_jOoPi1DP07aLPhrUmpZXz_nr-RwH5vyrUgfgFXZ
ESSwOQuptiSGgKBCu4KBDlToHrWYxrf6gbjCy9927jyhMCyYu4DBqsn6_fQek-XqsBsZISY7bZRogjx4O4ylHGMylr16FXmwl1opz2R0gwGvhv9VV1mcv4VO
JpmEK-d_vaFhh_dq4nyVj2Go3MigF_5nzbGG1YjJHoLFBJE3zkS8oE3WHU5XIY88UoxA6Ni6HvVtJGWj4QOh1bpWoDk8KikC85xc70vS0nXICOYrzUZfMziI
WeRQU4f7evQ9GHnmOUCV
}

EntityColoring(compose)
!define compose(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, compose, compose)
!define compose(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, compose, compose)
!define composeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, compose, compose)
!define composeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, compose, compose)
