sprite $compass [64x64/16z] {
dPO7bYCX30M_0A70_S-xazeuW6IyzUA44ZoK6ly3bL8RSnVLpxmVJKJj1_zcZ5EpjdvvbtfnScZhrudJFVMfianpbNEVcjWZli5osIFvOkZPoI4xl_H53kcB
NSNC4pltgmP71_2B7HmTKX_i8f4TKp1f5ienDFLk7janHbCF3i_HLVTFaAa7zbdwMw0Vfh-O1_PP-YNGvInzDRfxIztP_Uh1vOkTfAzPe1lqvFabq5qWdjC0
b5Tz7ihWsqqixXv-FLsRtQAtss-IwjSbU2UzeXV_GKZZvwFDtHhuBpgPkpDwydnrcpXKSmDWRXKrUpxs3KeWLG2g15XMVHBsPG5G0VIq-lJTN6rvzLWGkrmw
MTvy_iZuCRLpBVJupS1TpLTeyQLTuWeLrjViBxwR2gyng3IMvGhyw2zXoiszn6XrsBkzBFderdGlqDiCIvIz9W24WP9kFWuAkr_rBm37rzz7xoWw-qyBDEYT
u04L_DJ_ZInUl6jxMBtUP7OkSxZui7QtsZB_r9Bl1ekNQp_vREFudpIPFEylO57lZlbw-OIeWJuOJ-ZmBJtG3SyKtmUmhJsyuGKE0cpr8LYGCOvr8wpe6EF8
7bwmWMnySw9NR24TUOGnzG0PVvphQnPkRENXIiYeDZASyOxkiIu5xw4WWYzs13NrLrcPy06bYVbqUylaBm
}

EntityColoring(compass)
!define compass(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, compass, compass)
!define compass(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, compass, compass)
!define compassParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, compass, compass)
!define compassParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, compass, compass)
