sprite $concrete5 [64x64/16z] {
dTS7Zkqm20LGN5FWCllVxO-VaINh9wJSQQyTsq2cKKjX_NiPvKAMB7-V8fbQglxMmwjqKm-Usaq8luoWhP29sk6xbiVXbX-ashb0NmNI5wZSMYdw8S972Mrm
8lefSXpWuEfoNZPSBl2R0k3nGBJeHO3crKiXedYzmON7BdOZ7ZwyzKWKk5T8D_vqWVL0UVBMoHD-vcjJCldUoUs5toRVErcV-RMfEdi48YhF_DvKdZtJq_rD
HKotDZgo-XxRthy6Q-3mrfFTzvNiXAc_s7mwF58hH1nls_8Om3Byk07Vcx9YQr-o-vsi_Vx-e-t6njGMkoGyhsKCE_QszHlLdY9nlSsOfvMIJItPWewtLra3
pDS-20GxX-ztAriHp6_zgzZ9N6zJbbx0kEopLHPnxpShLzaEebiMyukwVXoWuEVIhaSmlYEYkDwoZtC24DxtdGLGbBZZYKVj3O1i9GRw9UPLODht_T9X1PTk
HweyzCf9KEc_97de5Hpf9DjJpu7EijlgkF4IJtd2Js-rhF0y2et4MckEdNFlpTGAd7WUEcm0x2hWjYTMwhdoy_PsmOoQiL1FXUCZpQ-o6BTEN7i9PE4B7bWz
JvOWCrzFhWDtVpddAroFH9O5Ee9jUjJp2vtKkKvDzRmAZGLMcniNiXJZZaUbaLZMRLqoJTppre6J67Uy_mrajVlU8gSdMA3Fl0rXJjYWZxr2QfXuPjNdVlxv
6zB2q1VU0eZmpYA0NgJXuntwAMYMZpM--eDARMV0r-t_Aec_WCz1b7iByJAgzlyZLPl2gtHJgINZxrEGoLA__F_UD_y7
}

EntityColoring(concrete5)
!define concrete5(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, concrete5, concrete5)
!define concrete5(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, concrete5, concrete5)
!define concrete5Participant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, concrete5, concrete5)
!define concrete5Participant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, concrete5, concrete5)
