sprite $confluence [64x62/16z] {
dTPNhlGm20LWYik1sVzw_tA3RYPoIE5xpN2C64kOtXaEeLDgrfbkDFzylDCP-_V5ntK2syVzuwPdoPiXbzs7kPm3zp3J1F5VrkX0VPScmBySvpZzO2gjkXyD
NZhRGRC9xKptmQpGw9kQhsAER7x6kgJD1yJ7XA6hC4itJ-o3pPYxUGOncIAJEBweqpzYNeIuEqMcyUVLsDWlHWNYyi3SAfGsFAoYKwWb3Fh67VRAf51Bc4mB
RYYNXuPoUT3vSFBb13Iw8GDvzM2wnstYj7eAFSHj0CTYTA4tM5eV4p_cQC-FrZ6njJjx4sQcvxZ1Zp3qUVKmFs7pMKGtpzZzy0H-QLudDFCxKoar_063bii3
j5mUq9BoSaBtj_R7Od65M2JKDvWX0cPvVyQzgPAj-wgvTMzLkis-2lGVhAhHFzsgm5V7OwY8jW7BzAlfxLj2auXul_DfGBlVosFTkVc6Qyifq3r_u7w_waJ-
_f2PV4eJqDA70uGMooYHx-pnOBEZdwG3-xMuIa3o8-vuzBheo7ua4uFkVU_Zlm
}

EntityColoring(confluence)
!define confluence(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, confluence, confluence)
!define confluence(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, confluence, confluence)
!define confluenceParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, confluence, confluence)
!define confluenceParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, confluence, confluence)
