sprite $contentful [57x64/16z] {
rTO5hkKm341HSs3_2nvr7BcSfFry1G-FN6xXBcHHLJDJ5IQ4gP1aCMkgocCRQj_8KgXp7OhEElJQiTeWLHgDcnzAbdDE4rBsJdAfjPOoGn7MjDJYvKTIIbHd
Pa8BSorh3xQGX7isacm7srfgwrAwexI7SL8iaOGzGAJZnEC1WdAawWFfi8xEUbHy877UIha-ROuxafPqu_Jkp5aT-y0bQqTE3NUMidL0BJzMQsQuZ_L_10w3
cfaGT4CYZ7UxOBQ3mxSGfdix4DyEn4zQqc-7y8VWRzwgxu-Sdrv9UW7VdrVlHugg2Wt6CEC1IYfBYJjCqfBnTbcrjBBSERBKqdMakEf9SjHat7JAI7BQHZwo
3GnfT6Ie3euZRG_R1eWeM0GkZt19_LPEB7P00U44nu4dJw4rI7aBqpXU7m4V3LI8B3zmXh2csTdq2aQISWxMIpi7Oo-1KwXZPjGzS-R7HToZWX3DKtFM2rdF
Yc0k4ZLpeyBdMVy
}

EntityColoring(contentful)
!define contentful(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, contentful, contentful)
!define contentful(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, contentful, contentful)
!define contentfulParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, contentful, contentful)
!define contentfulParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, contentful, contentful)
