sprite $copyleft_pirate [64x64/16z] {
xPPLWcKf38PZE8JzxtQ6OzmSAtljhwKaoX_amWF_G7OXfXI35uAV8h5gdxJa4BuDXTOlQE9lzXsrtvE_ay5hVoOXl4Eblz84td3QloAyzTujDOKGyadC14y4
AtWaM95iPVnMzKm0A25u7XdQrnqu4nu1AEkgMG2WQerNI4q9qqvbGDE1Wml52BUAqQ8JFmpA84ORUb-yWCnHSUsz8QGt3L5FvLll_Z3MiMGwLJ0aO_JWLfKf
9WSmGXMXcX9NyIOCkNS2aBtLF2IBniUzx1o4rZN6g5itevru6d213vgD1r2h5O__fHlc25PBUufFYqC2UJn8SGJD2IvQgJ3NNMe_tAT3iWgkoieKGI0jOLH6
tjL1ven2MAlOuUVf486t_2ou7eqsHSfGxHRWNP3SLnf0-JXcecC8SanUJWBuFI_MGnlISMoMxi8wWytMSFykdQSlGEqu7wp3EUSolXRSdPGF7SkKVqzz9AWu
n9jwx3shJ1tgPVDdc0a8mEMbXyJpSl6pcecVPjQjaXyc8XmI96ktyJFZM1rmtUsUrdSqwhpyHtyctfwUHW2Ovu-rp7UqaBq7ovoVIJ0J6YBCwkOEiWUZyRPZ
BEe0WDljBKpMKsxUmOpNhExf-8yXSJ2_ORJBj1T0kYmLa-D3gYGn3LKjxUxfcLB7n5v7xII-k9kNETxUtisNfUC0d2Fxfavo7CKlyEtrNP6sH0xSo90rObZp
PwaF5pX_B6izn5fYOf0KXMFTB6RtUFXaxMyf4rYB8oHNQnBWc1oH7wSuG3Dt_AK1HoM4M8bpZ3a7Hj-gH_Gf2d8fwohRjVmWBIaB0RW6t3oJIukhPaSIgmPm
DNXNoLzMFnZlUtQrLTNEhbNxdgRG1DKXK0Ooub_VaBbGW-FULRMwCZnUFpsfe3VxHPkcJU9gJkxJ6vuacFwHA7t-2BVa_aIhdp_OSDl1rzZgbjY_fE2VFW07
U8VoQ-yCNoBrKKKFtyALszeUuRjGg6g38yFFG0cfrFyfEJY2U_xn7m
}

EntityColoring(copyleft_pirate)
!define copyleft_pirate(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, copyleft_pirate, copyleft_pirate)
!define copyleft_pirate(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, copyleft_pirate, copyleft_pirate)
!define copyleft_pirateParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, copyleft_pirate, copyleft_pirate)
!define copyleft_pirateParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, copyleft_pirate, copyleft_pirate)
