sprite $copyleft [64x64/16z] {
fLQ7rgum2Fkx5-3xF-sTMfksV3DdUQfX1AZyA30-L-RZ3uHR3lRd7RZKv41Gzg-o8nrRS3AliFbG8VcPXG3i5P8UiKqzdeASIlSoEMEYHZHBgOMGGAmIh3cZ
iY63f6LBpuFZiXJBvK6Pjf6n71tPRiKPAaD6zrwjAk_zKTDob_YmCRbxGUMxR0u9UeNpU2fgNhfEWyHrHxUn435Joy7i370_3N1odeqJA7LCgyuPyFcLk_LO
Hd2qSBrqg7t44FN9iG8ruAcaHfd_2jNk0SJJlhsigoDSvmpAy9p1ksO05PS_Whl9VGM6DhhK9KjeEeoIjHmJZkxb9NRD2Bk91y7DASXGZeOTA-PyuEKE8JkC
nstLOPh1uvN2iwEv9XKJA1bwn_NWfq7oymjxHbbxM72BH7Ni0aGgZ5RTVwnNa9tdlfqpr-Lx0a9XS4ReEJzFd-QN-LXPtl7RX_pluvTN-Msl7zHF0LpH1Uqr
cAj49vpwSutOFncwAcY2MEaJ3F7GoSXmsWyWUqZ_cZkxgheQCAqV1vGlNdtf84vSL0AlXUOhcmpke2rQyixvpCEHn_2fFx61EL5G9ZtI7Kb4fH5pz6ueHfe2
y2gTxUI-ZJNBoXe7DogsYGV9N8zkgq4rlPmCwHXPVlzv2O4ZB01GZBJkHBQ8kdgdvTAWpM9fGg6_DaIcrJyU_OzvmIcRgR7E6ODdSNV59n190tu9nnMwNeMf
sWRROCzH47XjfNNjeA0ihzrvNzLmnZiehZBuUgZqTNEH6knWsnU6HjQq1N0h-GzA8vaR6O5xXexd2xx9p-WLObT4La7-vobS4ONTWAt3nBQQeBH6hiE4VAik
LA96_Wq
}

EntityColoring(copyleft)
!define copyleft(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, copyleft, copyleft)
!define copyleft(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, copyleft, copyleft)
!define copyleftParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, copyleft, copyleft)
!define copyleftParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, copyleft, copyleft)
