sprite $cordova [64x61/16z] {
dPTPOYmX24K5sm7O_thV_5AnEAQjdByCDCAze5qMHhp5ofuQ1_IonU84BHjw734Bet58AyYCGrmAqEAO0U7YSKujYH4FC9R-dCxIdwCxwNt-mu9-nnKejAR2
QSNP10RcUf5U7KtGblJPpKOgJ_mbsj6fKLUgYSOGlK2RkQH2PtbBlxTL7DBl4R-Pe9-cvxugZCNn0Lef1kcF3-3QAVtv0QQ3InWUTGENCBpeHbn8EUDppbJ_
0Pzhhd7nEknVN0p5fQGj1HajXcZYDERJDOa-O354HV-8HqizDxhcf4mmWEOhmi8bo--h6-MgSAQUksJvvrhDb_4XMVu1yxVFZ_CddWn0yHOEyjVLJVtgNz_s
lzvkeGa6yEJ55kEIVsdu00ECz4IGgPjxeT46qC90llfm0ynRl_JX1h2xNj_V_vK-y7pwNR2WFTok3WOWuBPCXXXliPHDuvkqrD5drAJeCpGvwWcmq9vXyFoo
-eiUoAo_e6cjC550l-NgyFgqAvxbwcHsNosfWRosRprRUog-btkcziClluYtDuzItHjAru-UE5CLuhcqiN_-Jup7Bm0_0G
}

EntityColoring(cordova)
!define cordova(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, cordova, cordova)
!define cordova(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, cordova, cordova)
!define cordovaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, cordova, cordova)
!define cordovaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, cordova, cordova)
