sprite $coreos [64x19/16z] {
dP05OWKX44F7qRd_TRkGjjyrA-WRGcXBFI9SwJlf0PT34V8DRWk7mhx3etnTG7_nto9dLn2c-sB6ocu2V8Wu2X1KPcQvYwkfsJAkQgBWGxULau6QpMk_Yoj-
ibfsyA0y_XAGRBysnd2oghrI7NqXZjH8DnBW2szg6TZhaGYoPUtfdhDxdwLF9iR2GPlSusFp9GKsAj6OaOKqdJZZnEyWDW__p1hbnEjscRwYgAaKESR8Sk8H
fOC_k88c363Pwndh3gkQPuWA4u4tHgDnBUJVCyIxp26QpG-UipFfN_vYXCJvXgSjwPa7OJDpyEB9CtFoFbFKLWaH4xeseE2H3X6R4R4GkZ3D0eyYl2nSu4uV
ox_78Rin_w4O5Om_Hty
}

EntityColoring(coreos)
!define coreos(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, coreos, coreos)
!define coreos(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, coreos, coreos)
!define coreosParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, coreos, coreos)
!define coreosParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, coreos, coreos)
