sprite $coreos_icon [64x64/16z] {
fTO5biCm40DG3sXo_nClb6jPUPrQo_1bQ6YeU2HG_q66s-Z4uYAFu_aPyN65evP1jFNnI5qIRTrho9euLy2aDX1VDRZWNZLvKP1B7iHbGmfENXMWoNa6cckl
2qnmbVb0WFIwm9uyg-kFrptq5kSLG7jkunL4ILzX7ebbnUCrWFJtALgMde1BVk3rr58JWFJbuvaizlNVNDfFXoXx7oEqntnnMIq0qjEr2gi5bFO-UUC9k9zu
uylZx2FEjc-EaKTs_9ZzKJW-s7wrWAgc3_8dsxVmlkbjqqVJCoV_-Vu55XpQrvEQyqNe2hDA5-2Ibz_nsaFoIoOuwmFw_D6fPzAwljxY0xMAO1GRKHl16BRZ
WwxVlTWOEml8yP_llLzyREpU9Hl3xqmWwV6d5tjusvZzjoj8Ud3lxlrE0MnCGNFlADaRdPCzpedUpdCCpTUzFuMqSHhBCmqdq6X8qYAUV6T4s6Z40oysNU5V
}

EntityColoring(coreos_icon)
!define coreos_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, coreos_icon, coreos_icon)
!define coreos_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, coreos_icon, coreos_icon)
!define coreos_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, coreos_icon, coreos_icon)
!define coreos_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, coreos_icon, coreos_icon)
