sprite $couchbase [64x64/16z] {
nPU5OYiW34KXVld__vrlTqPBqoUdBWT9GmfZmrIFAW2eIjSvRc5Q0bWV02YNKrkJBW7Ave5jXRK1y6ijA6r20Bjapw2z0IbRNOhwdkqG3Ei8nA-wOns2xEaa
Uph9xTnRCH3gXy07cRLk1a8_LeDYqgBZSmQrMc0ozYs2tRU0z6VF94Y-0G05R1fy-n1V8p3nyQfCvjm799y_cw91m_XbfYIRtAnxjfyS_iAaVoLZWmw_6-FK
PyYXVEhdlb3ok_oLiUxogpg-yWld_lhLnw_-6rKljpUE_I7pXO_sNf1vvk_v6txzPpzxFYtSvPU2o_yO5e2OREhSvwILrHTnU_UOm_aYJUP5aVMFzKlmhVvc
XhkRFY4lw1Dcxf7vlVuQ_pu8jgnlWDMwHNArTu1owzCXMMxwtVSZm7p9vlRX7K53jzRsRvFjWTxkgnk2ckCRsTiyaiInNjGRCK3EUmuWY7iEGFpTMuSOn1mN
cG7ixTHn5Tcq0Det79yfsnpdJFLaPQ_GdVm8
}

EntityColoring(couchbase)
!define couchbase(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, couchbase, couchbase)
!define couchbase(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, couchbase, couchbase)
!define couchbaseParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, couchbase, couchbase)
!define couchbaseParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, couchbase, couchbase)
