sprite $coveralls [64x11/16z] {
JL47kYOn258pzjp_l0lPzl8NbGyOp8Y8zvI8rKo8TQUSxeZ6SUL_64XQ64K0coX9Jz4VXjtRScPnt7PBQlVh1OoHPs3meKBK76mlMXimWcJQ3Gg-rEkWpawL
GTM0dK8wWzRFAuJ2ck-0eQ8EYEQ8KT_V72A194uzvW7ou8UAKcXMx9_P-QklEteOEoJV9cDekc_9UKiaoJf_0eq9IojxxUt1LixrcOZ7GRvPjmc_NKQPWcRp
UgxymZt5Uzvc71dAustiS2Py_bm23L27ZaSP8zdMZtkcOvFy9qThOKEYfUBA-lZ3mi204_KJsiuSh1kGc3qv6iBjRBCNW_zzYopRnb2t-62WQxxNyGicixdx
4Uwu-4-C32eQbGUAh52C9_8Zc9cX9y8imWEzU0JcIFyIvNWLYF8B
}

EntityColoring(coveralls)
!define coveralls(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, coveralls, coveralls)
!define coveralls(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, coveralls, coveralls)
!define coverallsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, coveralls, coveralls)
!define coverallsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, coveralls, coveralls)
