sprite $craftcms [64x16/16z] {
lPDLec0n24FnvEv_mvCopztvm4-znOS2jqyABpwK_Yn_yGEyn-lpVu1FublyZ6M-oIEZSC_NJ4RFUCvq1j74gIWixqQhMF_R5X_BYhdZ1weK9-KqMzxHPjAD
eaeda_9x8KOzN7_I_o_QZyEK2IhZ3Ed2rWm5LDXIDbBNBT-GKjtoK0kljyfwMUN3QzZBXq_dW_ah9vaMh1YU6NV8O4SNMcoQiphoXaTuz1qlW1tZ6WcOFZDs
dNo24oDMDTaX-oFtDqg-T__N5z_li_d_-lyK7qbybly7
}

EntityColoring(craftcms)
!define craftcms(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, craftcms, craftcms)
!define craftcms(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, craftcms, craftcms)
!define craftcmsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, craftcms, craftcms)
!define craftcmsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, craftcms, craftcms)
