sprite $crashlytics [59x64/16z] {
jTTdLiGm30HW5xcetF-wT8Byb0dnxjlvpGVk6H8CiVncKjf9L_kBjWrPT8dadJ-wPcF8OvN_ZZXJeyTe5LNbyW2jQgfgKhPfFLQp88gbipkKr4Kge51ws-_I
gcjCnMvILWtu7YqQSvFMnsaM9CpicgO6f32pNDFKDMPI-Lw9DW45TXI_ZYDGQBccZNWxyuxqTgRTZCqtB7UMt_pGUbEAglrcRxX3GweV4ND7mnSB9sYvnAOg
O08QqkEbg8YYTvwF0V5DMavkOhb7yybjeYVeomTSmp8PxsuEnT_Mw-MHuEIigVcPYZex7GqJAvt57qHITRP8e2DTlVJYx3omeFNqaxTbf_9F-Z5RT3-33MTW
eE42s-86-UJfJrUK-4ai36iKwHffwmEcfi2IXaW_JdCNVAqh-bgDCTcxUDPPjsFYlkgxUPOcDbH3S0GiKoW_79S9R4weN4HHdbewANe4v3fcEgsN56Iq14ej
0NbKQILOfSdBME25BWeyYO8lNswZvGIf_mcSI5_uBn8kgsMh2Paxq3tjfCb1-NIcxm
}

EntityColoring(crashlytics)
!define crashlytics(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, crashlytics, crashlytics)
!define crashlytics(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, crashlytics, crashlytics)
!define crashlyticsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, crashlytics, crashlytics)
!define crashlyticsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, crashlytics, crashlytics)
