sprite $crystal [64x64/16z] {
fPHNikWW34Ff7Nl_kttlrZHqbHdETuud60cpnCsUd7a1qlK_emIxeNyWFViD_PFPajlGbHo5wUWeMCVC6js63eu2T8oqv8ZEc4Idk3rTqvwkRKzN8Jh5lzC5
-VcYZtLaIuZ87-R03fYpZ7on5ntbV2WY73gkknNerwSkBNbp8IfaNFMFVZ-BLLc4tOSki9HJCV7hWr4ZBBIZ4HvQ32RH3kUF944wZR3Nnm1mUo32K_60e7_I
FxvfYWSKg1uHJee73FsRS5nHMkXEYFzvTGCEY4eOvuWc45wsWAXem5H6F2xvES0hfHuBU0x8t1-tMquWl11tIra4uKMa-uSHX1VG7pyQGNW1ZqL91E75ljV5
0FTAJukWI01F3z9DM_IglTTDMXHpljF1MOD_fwDTI-SwQIhNyKl1oVoXvlh1sDDDsTDDsD3X0hX-qFTq4-MbNWp0vouR-WSsb254PzXO1z4fBjP9T8fFJJRq
nKeh5y1AcSxN8ThCady
}

EntityColoring(crystal)
!define crystal(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, crystal, crystal)
!define crystal(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, crystal, crystal)
!define crystalParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, crystal, crystal)
!define crystalParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, crystal, crystal)
