sprite $css_3_official [64x58/16z] {
xPHNWiCW30LD1t7_ysv_c_PS9DAJ-VOO6Ce4SZSnWJheYqblq7qtaU57cny7y_cnV3AOhq9tW_c2pG_masndptUJ7YSadm9Fycc899-6JF9fgCPyWEKBsqaa
dvURNDxm99VNc_HtFf2tqsvyUTlxxJlE5tBv8mVBsrSKMqBoyIrPpyUsH9EF_LEJZ_opQ4yVye6MvWkuMAJJVFj82UiopmSa-sEvuYEMZr2ZepB9bvYFTNp9
dK3o4LgkSeMtJopw_YR5gdAbdXmIdvjL1g781Zb29hZKx3BM8NOPCSKkOnq6cSGqofW4UGmOdm
}

EntityColoring(css_3_official)
!define css_3_official(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, css_3_official, css_3_official)
!define css_3_official(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, css_3_official, css_3_official)
!define css_3_officialParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, css_3_official, css_3_official)
!define css_3_officialParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, css_3_official, css_3_official)
