sprite $cucumber [56x64/16z] {
pPT9mkim28CD613tF_2Rqe4_q8PszRJ9-CMIWqcxEf6e0n41c0gjaLWzVihtDIeUdOndL9M_9idYZQ2hrqOK3ORKk1IaOXOJ5T1Z9laE2_1hap33yvrlZonG
cid8qhKM-Ns_p9W_C48zVvppBiNkmsdo8EaL5QSI7KSHWHI_te5e_IFlDWDAdCGFzvOCPMbALmP4dgAimp-dGnnts97lRiZRgj4VyyjwBtozdUA27K_63zFt
-rnnh3cFJY3Aqp6lLP7A4QuvrUnvleBTeu9ypG7vu5-V99a4nEdG4V-_OBhLczERvNGUvscfRLlN8K7BWVjs4xlhUjPVpi9gNkokTIQr-kzAvjAQoXXo32tZ
sRE8FOKpFeeKn7OSdmBirAjSc3VkKUc-mpZwjcpa7YHHj1yFvnVh2hN9FGpReyDAuRHRRNpcbdUtKFMGVFxJRXrPQvDJBKYTW9eRwPk0biERUkHKq-JbXZQt
CZrgtuGtsk6gq_bF0_u0j9KaOmoq2ZXt-R5LNMUHVnfk_btmrOfzXbM9px0gDiooLObwLErrhLfuuFKDPxI-u5m6JE5GaWsuGiquImwd7Ch_gG7dAc-Xtm
}

EntityColoring(cucumber)
!define cucumber(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, cucumber, cucumber)
!define cucumber(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, cucumber, cucumber)
!define cucumberParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, cucumber, cucumber)
!define cucumberParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, cucumber, cucumber)
