sprite $customerio_icon [64x45/16z] {
dT9PcWCX20JW0YnjS__xpYwX1ysd-L-o5eijNX2rBofuYvfJ71ExqVFcTteOJ_Hu-FSBs9ISJV_-0BPmjdqcH-DdUfRFaCcVmxmCTBQVLzQ1_ePbDrzgSwoE
jdT-6kAjr2VArlEhBIYJ0MnXqhvQp9UT-rjQG65U0ClsUNpSylRY1ijiVCNj08XVihwyR445R3O09CUzVK10M0FAl81Wjdqrm1VmHv0hA8RIekgNEMxWHFIR
m5bjqMypCkP9B9LsKmK-WCUlHyC27xr5enCPuu_7fPYGzlLJJ-t701x_qYbvzlxxKzn-ABp5SmKfpr_2uJjon5s_QFgJjT9w_C6lxfFIur7_aRxrgnCBX7YM
2n1tvl6j0fmyt0CDMTsFNu89zgFkcMqLwCIAj8tP3I-KVjByz1Hw5Qp4kzuNlGLxbFzBzAiQJeYnNNraYsBX4m
}

EntityColoring(customerio_icon)
!define customerio_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, customerio_icon, customerio_icon)
!define customerio_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, customerio_icon, customerio_icon)
!define customerio_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, customerio_icon, customerio_icon)
!define customerio_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, customerio_icon, customerio_icon)
