sprite $cyclejs [64x64/16z] {
dT9PckGm20DW2R1p_nFFz4fCjaRvttgHfOygd93s9nAf4LSUO5SZhkTfVJXZZBPmdFWG175W8UK31o4POSTwbLvVEHOUEY8ntgZrkllZkLsvpVlJQN1RS_Tx
9wvTv-bH6T0PuEtrwLnphdS3EWES_Vhaf_ypRnmlsMb-wtY9NdlEzNYsv-NZPM39krAVYIoYTBmSaF_fHRZZMMQ-XveVi96dVrdgaw4Z__LKZnR-BXNNfpfV
puVxvVaCBJRoqtyrOCpX1DuUqEQSdfUeh5K_P-H7KLdZ-pi_Z1mZ3uZvoV2D9Wp8UdL0hIy380p8-ZB0X05P_p30y62cWHSdzBbZ3h3sWBc8PO0j7WRut7RB
WAFR-cqrSFS0d-hJn2_s7XXpAv2inzqZnloG-Jf0UYUminUmCXcnebvVwVKLzNX5CIuyeEJrkFu0R_AKwoigyVSFuCT_
}

EntityColoring(cyclejs)
!define cyclejs(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, cyclejs, cyclejs)
!define cyclejs(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, cyclejs, cyclejs)
!define cyclejsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, cyclejs, cyclejs)
!define cyclejsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, cyclejs, cyclejs)
