sprite $cypress [64x64/16z] {
jLVRTYqX22keGER___VSPoEcxevdhUQf5qC2eZ8VtmdvW_-Zjk61FmYthaTa7G5SCn3sE4Jpv9OGNPwm0zSEw5ywhzhieRsbzsHl07j3DwOpGZPiYUiHe4Tq
1jgNz7C7H3yBODSHGcZZpc25haTqRaM_ZW59UflbyGy76SH4jgQ_8ejsHmb6uI4iZoxbB45eXRuARfIzhxjohvONFtA_8KlndPhABJEiMIEtO6mFLaFArTPl
IBrOJuLeK_dh6ZeN83rR_Y9Ot0y0WCcVkenQW4ZxTm8DLTvkAPy9aUadnwRqGQrCXbF49ZTU2skVztd776skHfHrT0_uN83WQafDNy3d9EDQzGXDldBwnPXD
8Z5rWw38wBN2im2Gr7Z8BwJ8XYM-RldjLVEHzdTymUwYy3jIbWZA-yTyt0M0tFQJJ_tZkyjUuNHRIUd5pKr-fusHzYTENvuKnpsneDuvtXRxbytnB5znN8XU
skoFaAmDtilzeNb_g9OdTT1JCpEisgIr-P_RVYMq_Vrf_DO4rJMFWykY7_JO2VWHx-ceJsmnNEHi9Dy_Ymbhyf7l5psMGVBPC_lt4vshxoV3YwTzaiyjs096
cOxdumymQ5ay7Ry07v8ssJqvezk7rw1jUZN1GX8yF54Dz_ejwOF8EmVv01ir0q5ZCsP9Sx0ZXXXRW7dvc78bsaaZrTGPCl26NSJt4N32PaXt2e4OUlJvQe4N
8ZzW3o2YxHTKvUFxy1C
}

EntityColoring(cypress)
!define cypress(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, cypress, cypress)
!define cypress(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, cypress, cypress)
!define cypressParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, cypress, cypress)
!define cypressParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, cypress, cypress)
