sprite $d3 [64x61/16z] {
dPHPsYiX24G5ghIp_mNVAGETXchlzv-t3ASKHESBCjn6WkDnDAp566Vc6KP6-3e4YrRzZCYVZaVFSMJ2h7mIc04b8RG_wQ89oUDW-XLy0ZHClqBR1p1zNGCF
3T9lU0LCxIzBN-x0rY6PwUi0rm7BqzTDvDq6vXtSLR0ide2ad0F76wvLZ-25W_8KarZN3YOMx2lG0MjyOTXkO72TAV7SRq3x6Q0tuAsVH7S4Upz1DqG9Thwn
FcY9JU6h5k1EdvrlR8Ru3swERtrXT82b0V4SyFNDzDPtdl7dLvD5NnmzF1CPUGcO8Npm19uzoG3PlRtFkMRYoW_fKvpipX-i0VOZdsBzRVqrm7_cKpuE-loD
NK3qkdNprmLmtpw-vXzT06s__Rn_PdvArWLuQLzY-PigmC0p8NlJ-BLKs6rpThidxX-7dKw_Bs-dO_CuYThryWFQTrnr_F_XMhK9ttNNNmIgJSGhETxWsbsy
OGEouXuORu1bJtjYtEcUvoqNsEe3bCGOMprmMzzETzol87w2xVKOoaVOzQwW44FuW3V3DallUlyPN7JERtnqFW1NT_5ivwFqBOTzR2iZtTZf0-6cxba6b2lv
6m
}

EntityColoring(d3)
!define d3(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, d3, d3)
!define d3(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, d3, d3)
!define d3Participant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, d3, d3)
!define d3Participant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, d3, d3)
