sprite $DaprCloud [1404x784/16z] {
xTrfrg9C5eNH7uG8mbqn_z5MNqLzVIhf2Pkzf-1QJvwyu6j_2W00000000000000sXIblm3Jg-W01ky87K1utxg_0C8hlm3J2EeB2A_y0hWro2zWyhvdVW5C
NlK5c8PINy3abLy0vLLVmB51VG6Kzz01b7TyVG6SUUKNO3geBu3ogY-WlE8BuD2hle3ogY-0ygeleBpg2p1zdzP_7u3ochw0SuFw0XYz3W-0qMlw0XYzwWiO
lU8BOFIgBw2yuWiuDwWlWD4hle3qgY-0UuFu0aQlhxa1IA_f2xWtY2zWzAA-WFIAB-3U8Bu0Hg_t7G3fDNq1t1l45v1UyGLGKl45f5Tz0Ub5V07f5L_0KpRn
1P1UyGNS6yGNG7h55v1UVzq1a5vCNq1wnHUGNiGNa5xn1QIN3Y2zuWj8h_W2J8Wl8BtY2qWluWj8h_W2qelu0j8hle3qqlfPWFHY-0BIAxw0tsP3V07f5Lz0
UiKNO0gY0qYl-0BIAxw0zAAzWFIAB-0L1yGNC7l55v1Un1UGNd_J391UtkZwtrh_UO0cWEBRKeiTC7l5jxbOW_Gw-GwhxjSb6AIN0TNrrWOuzZBWu_RQ79Yz
vBChm22zj7ntzHUabm7TrLzmx6N0Fwxo2sOl-NzPzHUabm7XbLzmSM309ok_OFQI3w_yWlGo8Bpo2ouE3FZdL7x1x2N_ZwdwWlJoFk6LNt1n45zVfJu3p5xo
dwNn2zBBWF_0g2-uE33WWrHVC7l9Vupo2zBBW4zHVK5xoN-6wWlIou2FK7r1Uyb_WEeBqalBVtxg2zulOq1vrHVCNl8Vdlg2z3BWlopY2zfBlhpg2zBBW4zE
VK5xoNzkwWlIou1pW_Y2zyl8Vshg2sOl0puqzGMpbm6VcVY2sKl-8rDVC7iPy8c9BvYzz0drnUm5FoSFPY-cBvYz8BvWzgA-OFQ2-6BsWlg2zeBu8hqWlg2z
eBv8BuWlQ2_Y2z8Blc8Cself2xvN0UABsGlY2zeBuelqWlg2zeBuuaaRY2-OlOWlQ2-8Bqnf8BwWlVY2CNZI1kABsGlk3g2z8Bv8BuWlQ2-8BzeBuWlIY_Y2
zeBuehqWlY2z8BveBuWlQ2-8Bz8BuWlQ2-ABzeBuWZyV2Qs3sGk6BzeBuWjE3Y2-cBqWlg2z8BveBuWlEFU2-6BsWlQ2za87xGNnnRaNn1VCNX1Vj1Uq5xGN
n1VdNX1VC7j1VD5U45-q5-ZWt0lYYzaBuWlQ2zgBzeBuWlQ2-AAz8BuWlQ2zQ2-8BzeBTD1Uq5wq5yGNVACOn1Up5xGNj1V45-q5yGNj1Ur5Uq5yaLxGNj1U
45-q5yGNj1Uq5-q5yGNj1Ur5Uq5yONe4Y2zeBsWlqWlY2zeBselsWlZ216WlsWlYY_O2FGRj1SGNxGNjHNj1V45xGNlHNX1Vq5xGNhGNn1VQD0XeBsOl8Bve
BsWlsWlCFGtj1IxLqz1UO8_75-q5hj_GNhGN35-q5rWg7L-q5sWLZo_Q2wpn-AAzGAixuei_oF1psWki-xvVV0LESE-NQYyWmwBxMvds0X8ikh-LR2_GX4ns
4m0RM7O10KPtGN_HNK1_THVGNuGNa5_T1VGNuGNaLtW1-KLu0VaLNa1-cJuRu6y_cBo0ySi4eBucBo2_9Y-0-Yel8B_A2wWlpho0-YeleBueBw2-oWkeh_82
gA_o0kghl03ggxo0-lec1Q2-A2yWliuDWFeQlG3ggxo0-3et0AYlqGkeh_82YAzp0w2-HY-0qJi2WD4x083HEmA0qJi0WFIE0E3UC020qJi0G3Dw1m0mUWS0
aDuH0AHt002dtW40ZDu10AHt103tXW40f7S00FU60G2aTm209hq304Zl002UiWq08Bq30BWt300WlGC0IEy00D8x083q3W0WlGC0IEy004rw0SHNUW7nbLu0
yPLUG7pVAhq0uYkz0D8x083q3W0WlGC0IEy00D8x080V21e0G7e7071n6010UWS0aDuyW2QzUG3IEm20Lnm6093U0G1S70O0aDuyW2QzUG2ElGC0cBq304Zl
003IcmSWlGC0UCus083PEm20zEO1k3WC063s3W0WlNa0JNhp01nx1m0mUmS0aDuy01U70G3CtW40f3SFmCLX002pTm20hqWlWFO2a4yl00CUj04mOFO2y1Nf
1T1U0FBf1Q3b7xG1C63s0Y2z0DeB8BwVabu0xGKWdru01hnV1a1-zWBGyhCNW06p5u3yx0LWmEm583zx0HWmUm78pru01inU0FAp5u01inU0_Em5mEm5q5u0
yPLU0Eq54DytIY-0zW8GVy4CW1QVlG2q5cyl04iylG2qYhSNWBNIJze0cAlIinU0FTvU0DQgS7e1Q5KLRYy0UrLbdxG1SAsg_Em5S7IeR7i1MEiVeka5OAv_
YhONW7rCUm4S7IgPNW1Q_KkolG3izI_nzW8uEbG-lG2E3fLlBu2ZGyNR2-3eKBdq0d2f_yYt5y3HeUBj1N1qg5Xw0PZhl_Bj1N1qg7Xx0HmTAlMB5G1Swtz2
inU0DhAz00w-5Mel06iTCkTU0EOwP6Ol0Atga6al05kylG0iLOTyUW4S7IhINW3sU7i1MEl_nTiBuE1RYVG2CDSl1DeBGCkt5u2zVY7GNW3MU7i1kDOlFJ-z
0BJXxGLmyAtdjnU0BTvU0DQwBxvjEWk0-SxsJgS1qEhNdjvU0FPuUm7OwjUUtLu0rdXx0LZgDvwSNW3cU7i1QFLRJsul07kylG1izLlFRIy0Qxoz02prMx7q
0dZHuV3KzWBGXhONG7iFJsql07kylG1izNi-gxq0sWl06cyl04lzhjIFjG5umVUGdxq0sblFQoy0xHlQ2w2z0Epr-vxNNW2sBsWlWFO2SAi_yBJs0h1-GNi1
j1U0fVx8wFO2QE_qqm1mZRSNWBd-qCUq5q1x0RZ4smj0gp_s6Uq5q5u0j1T0Um6qjvxJNW2-lRq0sWkWlVLWUm7GNW3j1M1_hVO2Q6-zIti1j1S0xGNGNW3g
ptr2Um6q5u1MsWkWlG3QMp-zlG1Slg2z0DeBmFm5xGNGNW2kzMFnRTFx0j1U09Rw_AC3WFO2iCRR2y0jtbu0jlfBFxcz0EpnzW9GwVO2qEBj1U0IRoy0Sxoz
05ph1_pKBnK3iDJd3ry0xGNW5cyl05kylG3iwVO2q2hTNW0kTSZySWK0rqeFNm2MU7i1kCNR2y0MRoy0Uxgz0BHAjnU0IrNu9JC0bZfaVgeOW3NUNW1kyVO2
iAVR2y2bAlom3O1hLNZu0h36sml0BTvU0FPqUm6urBtjRTCv0CntjxTFvm2mnDiBm2tTNW3QVdzxsnG2uDnR_QSCNm2MU7i1kANR2q3Rq-q5OAv7sjkc303d
tke_O_W2S8kt5u3ziVQswL40NEeU_J0z2e0btbu0jdHx0MXrbvu--08uELG_Ftm1kANR2q3R7szlcnu1m5ptwQU7Bm1BlBq0xEds0d2fE_MpyGLWYRSNWEqD
sWlWv70olW0iyVO2iANR2y2bxjLFnXU09TvU0FRpxMtJFG2OwsxztF05O4st5u2sdsXlwkW0uEHG_TJm1U3s3kq5S7AeVYQ-02mdqtj_Um4uCNjpJzi0F6ch
VcRu0d1BjnU0IpsYduWl04kwlG2q_S7sPfws0NZITkYF3ry0jXFf3RONm9Eswe_75u3rJTeBu4bRzNHy0SpUV7i1pDxgZyONWELKUlFj1J1xWz-l031xgwU7
Bu3PM_t1uGl0jHxL7no-06odsfiVlW1cx_t35u1sPlPcXY-0bnmEFJHy0RpaSEZn-0AOlVds0fYzwVW2cBtvzWAOlTKVYIy0QtrEUm7Ctdny0SpUGviE0Cnr
Hhz_-0BGjanxZ-4Bm999xp5y0MXxfhr7V05OAznU0ERAjFU8Bm1R9ht7upO0biJiFKmJ06tFjhTF0ApXz7PN1u2vmkqrV07Qbcwl-0AifRrX07CwlU8BqBPq
UyKNO2dj3GEOzt1wnHUWRUdPAxu0Isbl6C2yXzChlW1jJyzUyGMuLRYz_gu3m99Eh-4BSDd3xHLVWBPLkBtY2x2cqwkz0DSAjrTy0TeUJg_u0hGjFNl55s2j
S7kzvGkmfDDh-0BCUxYzuWlGqkaLNu2sLRYzuWkmLhYzdhS1BEdq6hu0ynvkh_W2NDBf5L-0jbUslU8BqBRAjbTy0TejdLvlEm2izUBjNSGNy7PPAhs7JNm1
wOstjxRfam1SztnwnHVmOkzRj3SGNm3f5Lz0UiUtDnXV0EazuhjE0DARRMyolW3IUyHtcG2aDzfUyGNywR90UiKNaDxnxSt65q1wZ_Yk4u1RRxQzF_gUBu3q
YY_0l5UslU8BS7tRzFPwq_W2B7izGG_7jqrl162fP-ZXzjP-cG2aDnxVUNeF06sjTs_luJgz0u1s2wGt5zzb-Zg0rteFFQaEj-dL0So1z8RQ-wtlcW7UBJlq
WV5jqmi3M2kGtc1xN_zr1u0MI6yolb_vn0tmWiEXZuxlDdq7m5EsGn_Utjekqwi1Q6islVdurZnzFi2zuT1V8xxhzEa0zuP37zdULttP3629fJSVtwzxsGpm
QjduzhxctG7WiYVJcu_lzxpl07Y_uT17gj-nJ6C1N6wLJE_u-8v_v0PmtVFfpRVtAnwv0LxgFVJXwl3HZzm0B_KU-gl6TvkdF82sLZwzuzjxMDiK1Z3lWzCx
FhxxTGe3ZDw4_ghnpR_m0D2kUpwzu-CxybrVW7chYFwYxSr_pGsWhVlWz8wFR_vrCy0pjf3-Bl7D7nu0pzZ6ftTyVBVhb0OuD-JJcrU7u1iF06tPAwQ_d3ea
pxw0jnjo-WkgG-pi2oXlKd_L-4RFle13h_JsNk7w0iehlVzGwVe2oYkzlIfNNq1vfVS_AbLVG7cbzr3n-WBAgxszVj2-JFS3c8_oIk_zyJt_mnQ0ztcbzr0_
xZPFFmgWBLj9xm_4DtJu1PnvfRVNNVR7Jm-0Cw_q7kfEjxFZ5t1iaDuZlgUVkm6q-RQNzDuJtvENNu1vsMke_bRg4Uiy7G3QTQkItcV7zyWlGFlFupNj3SJt
o2_Wo2kzoVZABpWrx5NIcullORrEtmXeon5UwSt5zx1zsVm5sdoyo2kz-VWURijb-XQWktkLz8wDxs5VvpPzDE2oh4TtfNTmV0_xRPcdJmNsxbO7wNsD-1vk
7pQ0WSky7dS6vGt4zym0Vly00-rod7UbDnFVyxRrdGiCgdixiYkz-VYUB_3rdH8CedjTjlzKLteJwgcssxhCy-KLAmoqrkRhiXxDbTwWojYtssrT_k5wlSx_
TCa1vl-vNfTbNRTjs_TwExsBBu3qYYyWlU8B8BsduWkWlEeBIA_u0aYl-0BIAxu0qgk-WFAABu3qYYyWlU8BqCzGNm3f5Lz0UiKNG7dL5v1UyGMaLtq1b5Ty
0UbLNm3b5Lz0UjKNG7d55v1UzGNe1mf0UjKNK5xr1L1UyGMaLtq1b5Tz0ULLNu2Ufhu07V45b5Tz0UL5VG7bLLz0UTKNG7dL5r1U-GKGNlK5b5Tz0UL5VG7b
bLz0U55VG7db5n1U2a1vvHSGNla5X1Vv1OHNVW7XHNy1uPLVG7VHNq1tzHVGNVGNT1Vz1NGN1GRLHO41sPLWG7CHOQ1_ihy3
}

