sprite $DaprActors [116x128/16z] {
xPg9ZlCg34PJ_2MLLC9v_wUzMrjPYVyWTKXyjvxPnv9F3PHO0ZwcDUhwea8bXJzbw-jRadJT00ykfhBkeAKf7IgNyWZEwgERK6PIeUkldRJaEklVvEG_vbp_
0NNcx0fhf5AJ2wsNbzbWf_GoBvJkbAihatRS52LKS2DKidWRqvIrybOdAHzFx_horHJbTZvvS3tjJrVzYwUrPQpPwdNMopk_1xZHhIvDsFWIcfDweAnhuWFR
kQpAUkoi2MNcz7wLjKj2cHdEzd1drk1MwjgbqRA6rlatEKkPpdTEfN34R0jWLivq5ZDWiHaYqb_QEo2TvXGmQGRAmfu2UWFb7ESoOPvKR6Wt9DaJbmuw3UH9
jPLgGJAzCOdxk7CEIMSSlQ8U1uqw1Rkame9o8os3pYPYKcuycV2empJaz95rpATqeSWKmsFEJPbXokx8yV1zo2dS6MTK3Lbq6ct0wKEx1NMcKs8ws-apfYEd
HfpMhPE963KNkhEUvop4i8abj61zsB1qrn35mvrDeV4PXXIJpi8B3T58wu9pl4mG71Hg4YKwQHyMki-A4L-JAnT6QTf8pRTRbyhi7HJtnZ3BialA71-lUZrS
HRbp0Yh8iuB1NegUWBboY6AUr9MEhrM9i_1Siuce37-COuPZYa7f3Q29OIR1v5btBs5-6hr5CpGpY6cNL22FOfAPNjXxOG_WZQPdbGmTjc0o4uW1PkHbk1K5
fMEweK6bzhobnQExE4py4EFcIODqmZowbngV4lVlABKfHiUbCt9YGubwOUbdohbJY0_2cONUKB-I3ZsdjmPHsI_a-TK9S_krq7zstYTTxp7O-D16eNN3g7iw
215Do4vqkl7u263Y0gStz7_-4YRrVhhpqJaNlCf9NQFq4cV_d9TBdQrpz-C2P_VkHxQpNkoi_tDdorv35piVdVTAyfxGFdFs2KuuAFCZPx5ZYZ3wXSO7Im7r
a_Q9plWispE1-j2d7Hmmr_hyMacXXTxaKqgFPJhk-cezxlocfPVqpkUqfyx5rrEtOvjZtH-UjoobGyArjzY4PLxNT2ajI-dGqfLhlKhQE5Ik2LTSaaQtqNKc
b9bJQCs_-m7vTrpgl-pknzVvTNwTN-SuN-VN-NN-3W
}

