sprite $DaprCloud [459x256/16z] {
xDnNUjjA44JXHbU1k95d_wjr9fqZaJIi_yMMz7Y-7kGXjXEB3Q0F-WrzwfEV0QhD2KN9mAsPVg3xOqwPSmdhrh7rI_fMSr5n5b4gyAVJ-1ivWOivWoW3dypZ
dzIKEOE4z2ST_wmcUE98KGswUJ2cPWuJ0aczMipY434RRY5NYjaS8FeUSiMODREpSA6rzG636GQfDubPnMwYV0ivm63cn7KhBUDY3z58lMLBKUO0MLmt069Z
KGlQNCiqcue9j8EMcDbG2DJQ1yrcmaYjlI0s4iPgwSMtZ4OtBxfb22ijK_8yvpvXPhNsnyogea4jlVYvZEk2MiVWmdh2zv8dNcDhAKlo6rNBFCbwmrrNRgBH
OLfG_CmYk_YEllqnX0xKelc1ibIyfM-RUQikoSb2wLYOxvdyUSL-v_wVrWS6S5SEbATiMHQ_ylNOlIYmo3bGdcs9RGEbj_gtlXqh5K-faCxNqlgJZuwwFzIK
ixoUOuajrMzt_7Gu_PGnZNIoiIppqBSg7qRJvgaiw1JwurWQMb8__eNAv2olXs01KB7yGSTyEpOXdMaiPu7KQtuxLXdA_J4Pj9xRPEQEtH5dFfjyekA5uHNe
J91wavZAKEwjjGdJbIkH4RJ4KXdAGK0F_XB84FAzaT7pQ8ak1YNKUYRqaeTRWu0vDtg6q08pdhgYPzE2AISzGsXTSTRNhB4vwqdBhA-RjLmOoGNrqxQioasx
KLgASInOJumvXyfHu5oA3CBZj9pHCsjHpaNbA2qxhx-UIhP044bfAa-TXz23Z6KbvHjeX998KLJUVyrPRAv5SWClj-roN_t7AGCFSGSs-kMli7rB6JWfCvRd
Mc33BBmKhfuzsTFaghf-VjykPbZAasLxhZ8dL6L9vWkBfAdlAUCVFZTV95Tn4hR51zQTvOdtRYdZSfrqv-O3syN1offuIp_muvHXthAcuZ2-V5gnktNpWzzz
8hhxqvxIbGDOzuuFzefklLM0NEogLC3w6PCJhdl6hCkjezOKU-yLN5gXOno_lUmiyDOTKnEcYKqjXXK6CWxVNdQ3a774zhAktKDcChSxssdjA3512sixAcHY
Dgigqpf4e68zamyToQoohAL1nuccMONxy97COBfut5B7bmogUDG4Ebw0U8n0hQD5gp6FECjXCbfc7gLaC8zICj039KUGkJGQGbfUqFa4FSY-IM74xva7kPxC
HvfLWvJC5juwSScqz1Fk-faTW8I6aDFOnZgre9xhG9abrcW8QJcZymkcGVPc2UffbjSiiGjw6O9vYEKrMapFiRpcdOBNxTrNikiu40HHpIFekphtlzen_BX6
8--1gBE5310Dog2lPr4QkzB86pjZQ6JeiJza8ulIAEtSFU2xIneVNpt4_bNR-6gCZInAAmnjV4nfXKDsbAusjZ2sSHAn4RA9auZrh0I_5KfN7vlPaIqCFJOG
H0lFLokfG2syIBS5YMpWrvGs4Y8Qs2gj9oI-ZRNEhrOYfIP-usmJ8Q4sdg_UB2Mo-fJM8_rSbdGrysQf5ahQydjPTdNpt2EHRLpywhb7g8cKVaaWGLR-WBK-
jI40Tbsrh8GsrKyzLjRKflgKDXFw3seZfKyZWcmZfLEgaRE83vOIqKXAfmpgJca38Mt8Lb8wfJuhfNbLEgNuj9Jcb4uPdvFIl2fzhjmqbD8fAsRJXwKqfxIv
iPJ-5i66lgkRlvxUpBBqD-vQE8rOJxIHqeQzbDMogPMKjg06Ktg0LRt_wciz-gbh9AMd7XMw9dZgqH-wwlcrtOP6DajlbQBKdzAVEs_OqLN9PlGBbRQqeZtG
n774Hn6frWjZRDvFMUd_D5j9xG661fwmdbybwfnxR45xeFh1nryWs6GZD-Lvw54hLuruw56T5wpPH1nEIT9Ln8h-ZzgNfKyY-wkoWMNfHTd4ilHEgKPkMVFu
AX5jtCBkHIco-clM_A9d4sJrDvBwxUk6d_vKkonz49689bfwvf60oku_j9auKxBcPUd7gmX-An_Uqdfq4FjwkazcPKM7aEmhT7Nnou4D0Vlw-XwntYWbDjLl
bzueHN30o8UsjA9Z-5B9wT8ZJrnUSjCpTX_7oaBeC98ZTinT5VoMPyCf5RLqIT5AIvTCZWjMbj9Lm2NFf6GXgcZfYKVYj2I3jOAMBYdE40hKT-zdVPmiUNvP
XY8PkdUpdZnLakGC8KcCtNlPY4B74PmLI0hcqhsFbHcTWhY4jfOnT9_8s-I6YuYjfPXAznOsacTAnZKj5QnzzthMBuHEGbmcGV-9VFt2j39njYJ9XH99Rzan
RLZHELn1NosJfUzUoC_M39t1RIqLCBycflKpX1vR4XAzDgRrqoKXnGs-MmRCG-cUp2jIbvJClAUbGh2EpuffPLWk2obkevyYoMSiJIlz90XT0l81BHM2c1vT
qnrNKEWot4ZejuY4cCV-8Jcj7wOLCa8N8hXH81sgoNfdJYlzC2rSrL717KJeG4qbe6KUXxwKQv9QAQKVnca904NeSjnDXqH8RBGkopnF5x1vMTPW8qNeAf3S
9K77H8Iav0gMKaJeQZo4JelBcMv4yW12RsO86cXf81uaG6zZF9ZUn0WUIg2g-U7w9HEzd46oySBqaZmiGH_0uqvTewn1S8QViWwvIG5wAWEKW6CwvCKo4lGK
1Xd9bqgNfW6Hl5paGsiQaC6R21wIqxxshNSAxkffR8BR_GC
}

