sprite $DaprApp2 [576x672/16z] {
xTq7ajis043HE5ibaSlxdpO5wN77JmQc_FuPtg0H0nx_QPBU3JmpWgGV1vqPGT9GKmG9dov8z7H1ecVqS4maUi8G97g28D4J18cU8aZqT46YfmiIFLsGwEc2
H0z0zEGEqRD0aEWXY9x5WaGFGVJq7WxHapf4pm90eeSWUfO94Zq4qRDUaEWXY9xU8NeSADAphfT3z9GEqKCGFMSI97e8eeSWUiulIFGGH4_ltI5wIeVe8OYU
4mWIFGJHGn0z9nGaUWYYn_qoUiu_18aUWkWXY1w2zF0O8yZOGv3e8OWUnq7qhEyGFGJHGn0zvnSaUWYYXo1wRERfCGQ97e3e8OWUWkWXIFGGH0z1z3WESZEL
87fa4gE787e8eeSWUouHH0z1PYw2w74SH8z-E4J1V2QnPmIc8-ZbSJOHzFOudGXw5447FGJHGn0zUgOd9NfQegSbUbgYfoLwMgAd9NfIUg0d9NfQegSbUbgY
foLwMgAd9NfIUg8d9NfQegSbUbgYfoLwMgAd9NfIUg0d9NfQegSbUbgYfoLwMgAd9NfIUg0d9NfQegSbUbgYfoLwMgAd9NfQMgX7_ar7Z-XfYPwMcXwfwP6Q
7gdfaP8UwJdfaPeUgV6H-14_uaVyt4lYH_o87_4ZyID-n8_uaVWHF-97_8WVViIF-14_uaVYPoBn8tx4Z_YH-14_uaVyI0_5ZnJyIDjU_8YVVGz-nCylJViH
FwCPFzB-PzD-nCzese_u6HK_ucUVzYD-HjD-nCzese_u6Ktx4J-ZQJ_YPpJjH_oCFkT7Uje_LV4ZVdP-n8_u4J_Yvxj9_8WVyID-97x4Z_WHFz8pFoFn8tx4
Z_ZXH_o87_4ZVYH-n8_u4J_I2p_YH_miJVo87_4ZVlWHF-97_8WVYH_n8tx4Z_JAZ_WHF-BdZX8_uaVyY1-97_4ZViIFTE57_EJ4Z_WHF-A77_4ZViIF-97u
4J_YH_n8Ltx4JqxyY1_n8txu4J_YH_o87uaVyID-n8zquqVyvCIF-14_ueSVyID-n8_uaVWHF-97_4WRFoFn8tx4Z_ZXH_o87_4ZVYH-n8_u4J_I7ln8_8WV
yID-pfxu4J_YH_ni_vSV6N-af-97_7oRyvVu4JzlY_o87_5pVBz-n8_u4J_YH-97_8WVyICzyoD-Sk97_8WVySEF-14_uaVyIFo87_4ZVgGNViHFJlo87_4Z
VlWHF-97_8WVYH_n8tx4Z_JAZ_WHF-BdZX8_uaVyY1-97_4ZViIFTE57_EJ4Z_WHF-A77_4ZViIF-97u4J_YH_n8Ltx4JqxyY1_n8txu4J_YH_o87uaVyID-
n8zquqVyvCIF-14_ueSVyID-n8_uaVWHF-97_4WRFoFn8tx4Z_ZXH_o87_4ZVYH-n8_u4J_Ipe_u4J_VLk97_8WVyIFn8tx4Z_YHdlPFjWK_ucS_eH_n8_EN
-Ba5F-BdEBSVyID-n8_4Z_WHF-97UkPd97x4Z_WHF_o87_4ZViIFn8_u4J_YHthXH_o8dwM97_4ZViGFF-97_8WVyIFn8tx4Z_YHNlaHF-97_DnHuaVyY1_n
8_4ZViIF-94katuaViIF-14_ueSVyID-n8_uIO34Jn4aVZukI7gwVPcVzmL9pvTj_voVIK6YP_YP52HwXfz9GQ9d-9aL97g67uBUZvxWXo1wWX-2w0b-2A9d
qWz1z4pv8KWlGq_qytwNrwT7qJFhPzzl1D4J_114J_5ptuBekNvIJ_T343t53q7q53y4qLFy44HFzaCGFTtFwFf243tJVeQWHz4puOSWUe8VWkW9VWYY9_Wv
ko1wzb3mGn0zmGz1z0G_1D5J_114J_9343tT3q7qT3y4qTFz44HFz_D-s-MqWkXPxsS8Udwye-ZfVWYYf_WXY9xYXo1wYX-2w2b-2AAd-268dkA787gA7uBe
cVTpl154J_1343t5puWWUegVOzjRjxC9egVpwKCGGVHqGPxke6Uq4JIYPpicCWQ5w26eHWz1rZqXWah67eACFGIjY1w2w25eHVGGH0z1AwE787hM2_Bm0Zq4
qKFG-kWXY1w2raSFGVJq2AA787e8EbVq44GFGVGGTAxe8OWUWjoAlqz1szqAeiVZB_GGH0z19ueUWkWXY9vpHH0z1D5343tdYY1w2AA787fEaPyY-CPE43qB
yrC4UdeU9AV7uo_q44JFMJABqMCCeeSWUiuLGVGGH0z1z9mpWkWXY1w2w5aPGVGGHC_2FDtXRY51zAoC87e8ecTb1D5343qh8uWUWkXP6K7q44JFoWYYXo1w
LaOGFGITLi_jE46U3w8dHb3NuteFGVJq25glv-quGGJH4oA8dX11z8G8iceE4KHFYI1wMWJHqoB8ghb543qfFqLu-bNFZPxP25ghvrYSjdrTz114Z-XfYPwM
DdfIegSbUbgYfoLwMgAd9NfQegSbUbgYfoLwMgAd9NfQegSbUbgYfoLwMgAd9NfQegSbUbgYfoLwMgAd9NfQegSbUbgYfwMcHsfwfAP7QdgafaTgUgIcHsfw
fAP7IdgajwP712KzqfRqI5lJ8xsdHpy3
}

