sprite $DaprApp4 [152x166/16z] {
xTo5SSG00CH0VvxH_LSRL9XPuv4gs0RknYbMLKUdQZcSxOogov39LCY4AcH25JAX2fbFXMmhL24Jgf09LSXqAffj_qwr6aWaGoMJePB9KCbag6GoL3RP2TMt
PJuLierGXKoeGYPK8HEga0bLo8GgP5zKsMIdzK0Y6IgP39LCXaeW4wYG-LIqFhsZyiXGwMIe5BA7ha7KD5ovSkNAbIjNhbovSkNAbIjNhbovSkNAbIjNhbov
SkNAbIjNhbovSkNAbIjNhbovSkNAbIjNhfM7jNgoavEeJe08cKs5JAX2fbFHSMNQW14oeGgPJuLi-GygamoLJ8PA9aCbaw6IoL39PAXaCbGo6IgPRBOUIIHZ
EowJePB9K9bag7wxmqAeGYPK8HEga0bLo8GgP48LidTKCXagcOnND9aCbKo6IYP39PEXyid6ILPL5m
}

