sprite $DaprApp2 [110x128/16z] {
xTM7akCm30DGEwJYp5ea_lzhhpYwXXapPuNUAcpDj3U0N70iam2YFmB8XAJ4beXidkg9rbMQfVTVCo3BYRrAixHv0EGCI__grTAyUKxVi82jvkKVto9iiLVI
F6UBFTsyASEwAA21rJm1okLfIu2PhFr-yfnNgDTZhvjQ5BWyilXocNJgFQzbnugzZduIRXXxinwYfWjPHpsz7heE4LbnZhqT19Z8wl9aUKXfeLvFULFoXlst
k-PPpIkxjxjhZiMNvw80vrB8IlGkT7rEGbQoDnVy2Llvtf_BPKwpujlTcnTOgLvWfNk22S0cdy-9eWHQUg13IucywhbT0VYhQI-u0UkhQLuDU4tDxBMqrQlL
LzNiosf36rgrZwaDpTwJDhIXbInjQFRgMatGXkP3UvoXrTVHXZQqeScdrl0HjQ5TFxjcGnlQq78oD5MHqp6z-QO1swTJhRBKEsQB0FEPdkXIONVCWEi2rEKa
JyfcDSm0h7Wnyd8jQscQM_LyJyhjRf5cPfMyBAiQQHLccsTOoKkmM0EizQtUl1pBA7NJ7DPIKppgnTqSpQCzEtjPO6sfpQCz4pOagt4L2NjklVQi-e_dv5rL
yZRq2ivAUnxn9EorDe6utdvaxVLYptkyU4F7VfokbvVOYpUaHFtOwxyEurG4NiA67F-lVXqRTkpPks7_dl66E1x7RhzuGqTVLW3inPQlU2BLsIitppilZbC_
3zvVTCrdxBcx8JB2rsVUXl7z5rWhDKlSaoqdAd_FUCDyBxuEyyyFG43bzUjx7du7
}

