sprite $DaprUser [368x640/16z] {
xDsv4Tj050L12Xyicim_MvaoAMiAkziJGjVZYUihIP8aIP8aIP8aIP8aIP8Uq8Ts7Euut76uut37uOx37OSx3dSSxZZSSRZZSCVXZiCTXpkETnpkDjnnkEES
8HXdtcsuut37UVEEC-yst76ysmPtsr7Sm7dZ1lw-Tygyst03vxqgDt3Uk87pNfKRE6_Sm7alomsSTnfltC1vjtrszXxpRkFTXZkED--Tmnt7c_VEEQcgRSox
ZNSIRzvpdv1vH_7cpRj_-mPkthnvy-RDc_U5kuqtxsNYpPitRzx7DBZRUFDU9jwyUVFcpPitRzwyUVFcpPitRzwyUVFcpPitRzwyUVFcpPitR-33s_c3l7dp
visRDs_NNrRn_lBcpPitRzuPE6xUl7dptWySDs_UlCUnopRpvisRTmcEcpTlti0zRvJtou-TDlCEuzs7kujtt_YqR3Fl8DvBW-Fc3HmtxuN1SVC6Zfjt7-ws
uTs6Emvt6Ey-t74ECxIPTnpkjk7TXZiETnpkjl5LiCsyut37uOxZtOOx3dSSxZZSSRZZSCVXZiCTnpkETXpkEDnnkEDmn-6Emrs7EuvstCdSnD_V0pBkEDnr
jEDmrz6Emrr7kuvs7EwwMbklMbkrjcfivTggjPLZAyTMZwtUMhsr7c2DlOJM0umbIP8aIP8aIP8aIP8aIP8aIN9z0-OA7dJFZhf_B2vgItS_3jRzUmliVtrr
ny7Eks3NmSw3dKUx3dOUxJhQTRJhQDVHhgDTH_kvuhI9pxrYnXr7kyvRITmOTnpjEjfnWpkETXtkEDnnjEjmn-6Eers7Emvtt4Kx3dSSxhZ3k87_kK_BkEDm
n-6Emns7Emvt7Euut74njs9knToAkHLpA-PMpAsOMp6tuejo57EhVJVHrN8hvbRChPXRCRTQRyNSMfKR-8lbVzNEMp6tOcx5tcgv5NChvbRhhPXRCRTQRyNS
QhqLSolcLkkjc5kjjwwMMostflLMpAtMMp6tMczDowtude9gvwtugZ_jF6_UYhdLUYlcLkkjc5kjjs9kjTwAVyfhvtdpLiojdRrvQrfkjTwAltnhvtdpLlns
eftdpLinjtRsvgtusuc2UHyIRzxwjDmwn9itxpUDe3NdpLkyUMjQRWNUfyIRjtvpYpTlyUQjc5k_lSMRjtZpLduc6t06l7cBDs_nvirRqj_su4G001W80132
_6r7SNzr500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000y5Bn0G
}

