sprite $DaprMyApp [200x216/16z] {
xC-5TK8100J119Sl_LUB75i1phwR3cP-ll5Y_ddZZM01mGA21GGB61On21OmB4AmW601mGA21GGB21PVE1d6HnWMSJGiulEDyKa42nWMCGWMC2nY42nWM8HW
0S42WWK42mWM42nWMCHWMCHaM8HW0S42WWKCYnW42nWM8LX0i81W0Vt3_-YZZpxwwAEFtR_ZiLaibuh7yihmYBNX4Gl18_heeuy--kYZZpErPO9i9mW5KK1c
UFlVRafQ3wR8d51b-e_evTa7-uh_AqVuEuxgfQPXyrAbu6TJmpiuaf6IXfdXp-LLsbx5uJKClyxHZHHVnM4rTB_EaPdv6WxYqSslSnntRNqLHpv7vTSvchaL
NiE1cpWvwdoCwV-mJfHi_yogqfCpneMYOt5CRDuQUyJ-esxxLnnEMO6ZFEvBMFj0dQHsAe-62Sv8eLD59vND7CF-ULqDvD-EmIYowtEfYc2SyN0yvU2OAdiv
_6cdo9pr5qSmDrrRzmabq584nqDvvR1zByVfFMhWRuxA2YQMTyggfogE9yVXxMKQ3kUlnAQz74aHEX6IEB0wkcPn0EGZVHdtdRvnk4zYtCinRCbKXIDUtTtN
M94d_e6ZJinqSVZv6cFtSlJXe0qQEEhbgwmBARJ0ZfFWuBr0INKpTWNYVHpZUYcVVk70J5XZLSHHIia6oZnvDSTV7r4V6sVTon7Ets7OdXnH_UsMTLJDKutz
WuB9qRY7kpc61tjUjC312dulLa_5cyC_EE9oFtwGA_zFE7XRwZS7s_j1n55UEDpN_T4jVSxanEcD71-B7pZ6IV3Gu5jKRxh4H9wxheFczdAGU0y7-T5XH4AE
8ibpv2wbrZFmxYhzDB77lHmiVOA3XLzZnMe_O2qSAAxl9QRlvgZ4uqjxzw7cfWw4OLWDrH6v_xiz1WN_UEtCOIq4o8-_zDd66z6shnt-vOjNZpDJM4yEWWEq
rWuIS_dHGQztAyo07NuuP5Z8o50pXt-uYTBB9Sp_-BzUvp5ROLMP6o_5b4vOke2Rn6OEFfmi-U0pcO9pWNA68-NehOyvd-VGot9jTo0uq1cEu8sOIeSwpDuE
4YMTUruFEC9dE4pktQ6aLCRdhKLpoptEx3IZ4nnd1OVfsf4-pg6_ZXFwxbSdz7Ly7L_7rq63eyMXktMGKqBe04TdrmyevapiU3t8At5lY1qwe43IfWuTK20v
T71yS0gaUbeFybhyCzM10mecgNfmK822aJ2E3XIGo4ixWX6R-wUabxL0btH0iJrrEKSqugqau-X1WTHb774GLPtlm5hiAEb7mHyc_UnHlEG4XHGx9izn92Xs
avpWy5BidphUOSN_PeAV2wk63XqkqrHUDGR19Q_ieBN3y-lHjmDzXaDH_XH7fWzmw2C1NyVNWRwEhyDswf3gbiJReZqj3XJrbBoq8sIYx2PGfANyii0v_fpk
67CUPqVY7MDa7NyWET5HlnvJbt08fVaawvWRJtUy7Hn5uaFlZfBIDdw2Gz-2f2E7UN90SeH3QgCb7EiPmlZ5b750qjWXNIhlCLyvbATfvgIB8KGZX9t-j78U
9rUsUtxO8BHFP1a794qTEetpO4mfBuw1_iuYJJOhX9_-Z75vL2LknTazv77HFpcQI-1GXDdYCFcneJXAW8HyAr6-nJfABZLrnF798HFdmDlZmlAFaLaFP5ng
vp1vBWo3lpjisMO_3E6d8zndvkv8taVxqg5QI-3mutsti8iZu9EwtQF3tcUZNnuloDjCCklHK097N7srbbWSCk6B1SW4np8JoyDd1nN2awEr10viayVQJ8xL
aIl2tO5hY_zh3-L0GGCSlAIH8_nqO9lZsW4R7EwrWvVur6I_8YLkBTjVR4cMip8SZxF8E0wJm57EJV46KN4vplqy2xUPZhauCCFZyOxs4ZXm6QGOwNxUrHap
E1vdf1Z7LWdjvn3k-JeeF6PmF3qQupXA0iTw2-_7juoOlNICGN2E0oLm29V7QOEoY_TpalH_PpQjxXDpMCOUhw_mZlOIE8HoCKQlXHvkgJBJqynfOUPPSOnU
Q1_JD9vQ7XzPE7uX6JpLEhON9aSGJBo3bmJgne4S8sdgm1Tegd0qMfDasZlQIvBJ-Wr7gdOWMoE1udSEt7DLE7O-JfBL-bG7qWYIk74jZ7x38MS7xURW9RHf
ZthBGViwa67MX5cBfWu7H-MQsCWhAXsgmb4jWQB2aUSg7BKIA2eS-09c5OuQ2HIL3c4I6T7CmKkWg7S8gKH31o-1uZabnSwP10UgFWkx1CK14XDpXcFFDJ7M
Q3RZpTuAEEhNP7if1xsR0ex39PGp9BKAEEhx7SFcELybqG44E8wK_A5SelSb1Weu3fNWOq0WgL2q-7RyMnIbl9AesZqAoz5U0iMpnAdBA12lM3SoalCKQ8lY
UKtaPHI8KJ0ITHa5UgtW9SdAooWGe-0abr6WbQ9MeZqTha02YYg93kSfK8Ma0mKl6MI3FUeCIHmwKl0I8nMZw4YI64LFabuLg7S5wbs1UbUWtXK8YiwZtoZ-
0m
}

