sprite $DaprEdge [63x64/16z] {
pPU7sgCW44LTd082Sz__RTTHIRv86cuzVxbf9ubS2-24eTOAvp7pdeOFr5hgzYfFF6P5kQYRPxccsw7NVw8lo8jdGSOdxbhVm1icSYOjfO0fX3Mdm8GrPHBn
L73mrpopqR0F2VI-OjwX66Fm6slEMwOrQGun9Lfp9M3gxH70U80mXw_bC2Dq-WYWVwhFCEVgqD7HfBKcn_IE4LkHwmC5Eg17AxKujHnO7D5HXZ-TD7AxYOXD
-txRoLyhRUYcWTvPLIM1QG6TTnjRoSRlT8MJvw0tNGxvcqyNC94Y2fRZcFckTnAXJVV_4SWyqZjNm7WEWarZfgxt-hntbfK5p5Y48_XZx_7q0YUr6oUTa6pJ
3CL119q6MvWJH93OF_tRGuQOzq_tsnd8r6rxVxoRe7M4RJFsXedl8qy9gDnqHYwbv5RyeLFD7A7CoOs6G9WLoZM_xvqXWGfM2htPw-H5xuH4WYYIZ4uj9WWj
bMx5UUjTxmfW8K_QHBwNbG78fzvPnSNOHYlHpHVbzdMmD6tFfUkTYI9K4GTEbVrUbyhdouHr1on7LSsPg2nFR0AZE401aBtt7kvtzvUzXsT-ZBtzl7SPFr5t
lLy_pu_eWjoyFJ9uG0-_Teaa28fZC3ZwDsSN_z_KA5pKszmcx7WnhzDvr4z3ByAdb2tPSmVJByse5Jtp3o9YH3-CYQR9CxHvlAfdWav4DECfPZR1pv_G2V34
efuPEHy9imjBeM9jBVFl5cBbklxF5g6UvVEdzmjmksNUikCd
}

