sprite $DaprWorkflows [130x116/16z] {
xTbNOlGg38PXplz928Gdslzk3qvJYadnOCW5xrNgpEDkQ-okLe0tw_rd6l0vdWq0Q1h0ir4n6gaD2isc0q3J1LW28FmWkpVwsmBxfYu2-mk29Q3f0aCp6oJW
9c2Km70S3HAq2JPGO8HFHJiX67odweB-1Z8RA_3UlzuIBC4IBC4IB05-_hTUJm5mWc3z0d22q1LmYj0JS8emUQ9v0C2NMRiJV_YvUmHuZ9YPi3TSW3qMrQ9P
I0WOBC1UB2MB9Dtq5W5SA0WDm2Q4FRK7HkqoGGYjVG1FnHW9HuJGHH1gnviWmylnY112k5yGzWutWJr4k41nG0YrUmNX83p6jonuJJOyzb_uN7S1dg8RmvFI
_eVUMu7mt2RmD1yTlYxek2Sw8Ms4b_Z6hVqWz3uQdK1R9kmng2WkEnRsWXqIUDC8W4iifN4-29USbPr0kPI4pOeq_ZZODG8dW2KYtHIFZRuoUHnHembNv_Vr
cKE7S7gUT_ecxRp06e210eDdSmJcW5a28mTC4XZz0uBD55Zu5sOBmcp14Yp14Yp14Ym1lkvo0RwDhXNW1rqgm8yQ9LW2oJaHl5Xah21d9b52ZMG7QSnff82L
02IXM5EbfBIhQA0WeoOfvbgvSH40iLme21y4f0AmCcgK6QG9eeGB1U6z09GrQuINIwR6_AkJuDDKYXZlsZak2Fq5tqxc4k22S5RmJLy9g90BGgjB1Ug2S4BW
dTqAf8rfT9zyJsp5hCnuxifF-Tk2SYli0kili8y2ghqZA3VcuNtpzzihWfTYpZcwmBjA49LgaY3y_7qaLXafUBuofKrYZPG1i4uGw9Pgmey2KXelG6BiIIPG
JXWdu99h9U4bKTM4WG8GrmWUCM6GeDqWmHB4QG2lFs3rFm
}

