sprite $DaprEncryption [111x128/16z] {
jTg9TkEu3WHGImMGMa3K_t_jUpCEVIQR8D1IgdUth7ie0kXEGWwdWYH4G3uW_Di8wWS62CZvRpt81oRo_0aa_WwSG4h7Fe5_OlayVSKwE9CgTsEFwT4VuzS0
8YId-LOClsCT14dKspJe9-m8hBW7cn5Y7HHIv0PCUe74WOYGU5ooPFxKP-SWIAtl5uXK4kXO5fpaFKs2nnY2U0D4WCKrW_6-bxWQpuiKpEVHiHCjR4ETHweH
0PRQmdwZaxYKn9ubmLCF-JvBzRtEjnT83CeHM0SA1CY108chrGWfHP3kYddwRH3dIx-ixgiETCL37fymqH5CLtfhWw3W1SuWPGIZMMjcpZ5GIBAChMnnchLd
pEYBZenk9SWvYq6NnlR4EjZO5iK0I22F6PjrhNlMQ3aGJp3VGlKxra6dLKc2k8Hri6N1DBQpMJkCDUuPC8ULdMujZ3dt8hW3s-WMQtqFjmIOn_uUB9jtB0Ms
9_XkT6N7SWadMnoyXkDWpFWlY55iyM4i6gNvuPXFF4fZx50pi-QjMN3527Y6aRHzRwJ7e5NvbbzyjGXhvjogFY_iaoq0TptbnCBfoBtW5Qd6w5hVvPpRQ86s
2ZxbxE84jz226m38UiObmLNQuVitwOhgwtVcnvTNd78eXroZFWbTZMxB4umkztBEYNgpeuVJ0JxjZgy7dhMc6SxyYDE-7Ekpu_Ndk31ZJZQtexS3aDtjI-58
QmVNRobkfGLbMMXVbolRuVKfhjA2hQkVkH9idh4YmQ4Slnt0akKQIuhhfNcPSmsvk3J7ELC9kRWqNpVFShv9nCMbQVRVpLzvlU9clxp1rv2BXpJ9ZvllVENr
oaQIlnPoYaFzmVbUL8i0W1Rj-VnAsTs2FWYvuWVJCiZ27rn9SchDhd0zcjmxsVqoPxvBbblluDOqj_0wnoNBeTx1LMIvukqwLzASjXDEL2NcccjwxyHYJdTo
ru3hXPdbDhU0aqOpceJSDi2jZBZ2lPcnH1oNF8SQSi-_DTQGgmDS2JcbDMlKa2l8S-eHXuNMNphWh1TcZXCzQVELlYBYtD9S7z8Hjv1Bp6qomgqyuJpck0vn
Iyojv1fpTOH3YRcoB2Nc2WOuKTg54MtDTOnhpKQvi31ZJZQ_nAqonA7o2iUA8KxKt0Qv-5d6d2nyd-E2GGxVYgMUnDhdg0HSfjDvaczj4t2ftJlDfwOpaO1B
5MS-ne8nhcTDUy5qpdFQMjOBcY3DeT1iK6iio7BNjyzOSU4hN0lDXhH5WaJQk6TT2xY4roofjK3BSbBfbjBSgrpdK8oMq6W5Dt02NTdiz46k2abpSMfpim0p
RpNvnNEa5nWlBSK5O7A1PamjxUdapzJfncR1qX8O26H1I7MtNyiVAMmc9n9J1COBjCPDSvYGa9z7I-DK_xI3rZixWIafmfv7cKb0a5nWUcaTmuy3LTc3c935
tVgkBO8a9cyV4aFPQMR6lMIm-V1CgchoNEj2Tow2rCfqua4UIXA9lY-sbrmrgZB8FAT0gE0CGz-pE8-IQeiKDZEJIK8mtzJPe90Ym0MiSY0FvLiWtZqxF6CS
10J1ETuuHGwgD6xgCl7DF0R0ZasLLm897cbwp_AHn77AZkdC6rBwx4RSr2gyAOBWOFO79k2DaOcSE_ZBOooJyDuyj1yS_Od9Wt-HRtlOCIInySpQz_3JR9pu
Xv6-meu9-CUPvGaAo6aS-py
}

