sprite $DaprWorkFlow02 [270x276/16z] {
xDhbclKi3uRX7tS29H2o_rlxoJBe24lwl5B8DMuvfkUIglrxyl385e_m9V9xnJwts4MEiSinTZd6BiVOvHYx7AEFNAFFCVh8DVfiXSGrkl1gv1fTekythqPo
ZQxDDLpZ3wrKrj5m3Lf1W_1YjeA6VQ3X6lI9Xk_H3pHSmuy4DetfZnAxXgsaONGOOwpXPnwRXf-LRXf-nKBJcCh3R56D1XB-LwDOL6Ey7AxX6gxX6gxX6gxX
6gxX6gxX6gxX6gxX6gxX6XEa4bpZaG0X78LepN0zxI6EgJ2ESqo5SPnZ5em_op47nd6ElnC3R_JfrECSTcODV4iESTYPDO3FEV1Yfz70ZycQ6lWbML43lxQW
1WOjfu5xjELIIjuO28HRKsgeFfj6KZMdbBBM56l0lGarLFN9i5WrqfKbLhFmT25KJwgX_syyYwiGRacr6WPBqO3FgA6NdepYxjCGmd0n6l7fDFJMQ1AbY7qX
ZfQZ6PzCGmSQ3ujgnjYLAWqNf2cVIKC7RNUDdAqMGb-e0LrnCEPizusVItWKQqnx3QuHNLm675CyRw3NO62WCSIOP9s2HsmHhURp4iR9DAoEdqK1AXdxig95
WtNAHDkYk1Sje2zO760qZRdsKmYtSdja4C0rTnZpR8k-EejAZRWK2yL-VKipxQUyp26rR4pWgiMamrZh-0RkiQWbY9am7j6oHtj0p63PRPOkVoIGOzFmeyGj
yZC80uoZ6cUvMkiDZ0F_pLaqR82ne8ODC5RG67EmhQrXUupLDQp7S0rh6AvnvmXihd49XA3c6hToLDVe9ishuHgkuHgkuHgkuHgkuHgkuHgkuHgkuHgkuHgk
uHgkGNWdcbg3y6uJQn3URruDj5m37-KQhl5Zhi4BQd3AMGA-b-gsd4PKYI6LX4TqVIybbhIOHj0005os1uyG0Cg5m4LeAOsSxYe4kiGbCpZdgudmIXeQS8ag
iTooJANWcifA6lT722jHk9Or8jw-dqfOIICguVzbmQru0GYQ04XXJAgXFsb0IYGAkH1kyHM0Yr3EX6yQEec6_gI1c4ifYV0roYg4RnewZOOsZJuY_1H5xBhD
c4T33swPwrmQ-eO6AtQPwXaqtkjZ3NsfasdePneaSsheHngSvzIOw95oNEtui-W4lRjE2O4LWNeDcqt3NjSeeb9ufs4saqQrrpKGr3BZYuRDe_7cKMBU27rj
p5oXbUGUOLz8adYdCMbegMpNAWDe8fnBsaI5rjBWzWcbY5jKXAuVrj88k4JArAr2Oi4bLbvK8rk-bP0JhfMug4Qi4kAb097LDH0ru5PGRWUHLzAWQvM1mBYN
D1BHfX4hQPIIBvNAs1LBoIK7BAN1uTvF-st02XflvXgkuHgkOGSnN8F-swvzu3WNmb0KNi7bxd-rVvc6OjaCwJpUEMgfZlZI4_mJ7juc8Y8Y8Y8Y8Y8Y8Y9T
XaO8ZP833Q5n4HfmT8r0WyP7YZhf-Jzd9AVkgg5Uy2bEtKoZ7wyMhXWQ5vr3Gp4q-cBZklkX4sauQgGd1ubjNpVibZmdd6juOuqEKMWuQ7Xh3VNG41hjvxZG
oDyd2Wtjhg5aXMVLq4-9W1HXTjM8vQ-c-SMzkqOuOre33M-kKJETK2Cvnq6ZaFFUwQFq9FwcVFUZ00qqq4033JI8Y8Y8YAr-uQpvCVLqVNH83JrAGsZqT5GD
bHe-auPB3PrSGpyzLCFUKKEwJcFyjvAqCaUXuPcDv77RGYngv1kkYuDBQAXQOFD7rMerqYYczTjgOT226WhL6lrabnfJknxUho7rmlqrhT5FgJJQaXgHuvh7
VgdHJxXkMgtXL_VBOpiXQCLgoy-ousdhQjZ5tWCFjumd64EDOkT-Yxxoowir_Ak67wgXk1N4AsZKUxMA1tA2KMWKqrRJqACqjAb6Uvr6dlrMZd3iDWrDQwGt
UXmDJMbeKgEuqVKrDANH9ZMqiePpZSk53hUCnuKK6iMqIiFhQLYzgRUQMgEUPY-euOyUeA6RDVn-ZJRIi48UQ7YaKKqhdZQB_ScKStX6GwL6d7OKZPp3OmqF
DAff7osZCS-brqyZ8Y8Y8Y8Y8YBw2m
}

