sprite $DaprResourceBindingsAndTriggers [160x128/16z] {
xTm7Skj834NH5l6Qd2-2kFjVxGHADeekoj8aDIRSduFjKqyv0k0Em7QI0uG7mmhtjBb_ol8F0RWp9eyxxbEMvLy3lZAWW5HybuCpeEtrgl8oyC8-J-4Wt_c_
UWhV3am00AlltNy1uAxBtWgydylT8CwnmBS0lXp8n9i71DpZkxDlZWkoyixYoJ_7rn71I-YoWz2tm2cM7u1U3yW6jO4E2OILSla1I75Wb0J6zX5U4aXrOFg8
ua2dE13KMb2hbStlliiigNSJjTfrxdncHfsSksxLFODfBWNquCSisPuaWQZJbMkNwQEToBnGemjqCnqoYMMkmiljCXFBnFZQEMy7IWnFoJi1ChhBGvvCOc9q
wQiue2NlDAOAnxwo0nfw4iR0UivNSa1xwXETORNfYKycUZ2gYUS-qGlxPEB2g9Rf1L-d5JXzr1oml-AhUlwSG6DGJIyDE5SyWBEH0zAV0Ss4rRi2apfT65T3
Zu7xlp2s6TctkkaI34myr2rNM2wChRMp0StwiX9EC3hZH6UB4rxYmQLbEHcGNVThUB41JVqd0FTjhzI0Pff_WEDizrWh36WVkkk-7930O70XP3AJskVHRgis
e4c2wurt6z2Bx0UO16Z9rJPolXgf0Vc8Ph3pYZIR3W_NEBU2IgKFO4qcG9XA0FtqLD54aKvuJJCW6SCBW2ElcI2lwO_EYO0iTIOMQfMwl2rSA4sfk_ccHfKc
0RiggpEWEf3JvO0B1P91Jrsn0Rk1JdKcbiRObBeJdn0Zar9NwUwiB7KF1coCgqc57xFfv7GFVKOhVeTlBtb_OFfQA-MhT1uTo2eVm9SNVPNlCHTJApoW2IP6
rP6ii2ywptrpe-w09gpsinBe_znddVp_h1qcoXxzSi2Qy-M0zeUVaF3_inRH8w095iOtBSZEUHSgD9yySctMeLEZPMOdfKxzoagT1BjhJvf_4BxXb4a2VRI2
UxNNiPZuB1_wgjHaNVEa-P8FBQtKIgq9ohzIgJWm_aalbgiEZA87yUQb3sAA0zS3iA3GyGJ2LXHOU48d3a225ufu_ukQKnZnH0Sm2hZn_3qrtdoz9zWs_phY
vWJ7V7FkEdyhq3bzyofyRrrllq3YDj_UVXXxwXw_9qx6cu7fUYqO82pfouhp7Fmfp0U-lSBglFgUQep97OWx9f4fTc0T-wvv0GyEQCWBbry
}

