sprite $DaprApp [110x128/16z] {
xTQ7ckms20LW9EGgp7d_jutnohSCsMd1IfkpZMtpVs1Sy5fK06nx055Sd6PPrBnErkdXggXPlwUdrJpLAsVeFUbaDK-wMH9vEgXPZzFHQfvUDqCV1QIJPH50
9TgA7wSsAzABjomTPkZwwsGrJmAiQ6-BYjxrLCEintUZsgneh-g5nyjxAdqiYxyRDQkBfrTQ_dJVEaGwMXRzqgGJrthxRshQKLkxzWQC_JIPW4peOsajlAAK
NXfdPdJipT9Jo_z93NsrzR-iyNzV-sWYLJhs1g2N9YhpD4idhM8aeWdLHYh7nvvMFQKjpsiYoBl6fW6mZrtHiuhMiD2UL27REgzOfWLxmwrIYTO6eamqee8f
youNGQ5a5OjAf2ORCgMPY24mm59-gM8r75AYjC8ChYDHGjchTTgv5HAg5QB9FescfNgOQp7d-5MWPab4cUtJeMtLZkDITjUgM4qmqPd5D3bxIr-zpR4QMsji
pGrM5ztvT5JRdCoCqqGb7VrWtb4pAFtOoHIxa-sgnQXrgubePKfv9tZ3MSaMg8dMPQcRlUQwB6ReRDSI54eIVoqHHNj506rB869QVVewERzoLJw_og7P3woY
5VMq0ZGVZ3n8Eo_sIgsEr_mzN5frgIOYhWhGulBHFjf7c_wTsaVxQ1_je_6_JVjeu_z0amxOZ-FsXScr5jQ1Zm3hRa7aIcla5WY0TONpmYqBe3E81-S5p_3K
CA5mvZ7O4syT6e4jpOkVeTU2FREMPhb9CWTwpHhuZEyjSqiPArJa4Yip6cTUor_nv9x5fXa7lkaF8W4xxotBnBVUQbxGRfnM8hIaxFjJYJfUPb76BodilKqa
oCe3uRSGa_TKv1bgks-12Iv4muqtUU_rupKLPxbzSTwRCnmAxgGaxstohfKO3yAkFzazUMiF5Gz3QVAUYhou6rG8JuNAGo_CQk2TUJwSOHdmOeZ_p7l6ue8t
ajr-RhiNtrSBPVBzFTf3mjkXSklD0RlnmhxSlQS4X9jtts92K9XkF6zbn6NAS9xRZKWlaVFSFIKoG_DkTYF39VpuDIiNN1Tb1ToppNN91fW7b1Ttumy
}

