sprite $DaprPublisher [214x236/16z] {
xD793G9H3CRWE-H_qt-rxE0xsqHMtC4dRpyiIMsoSizb8fU9N2PocKXbebAPg5GcMYeJkKpaCf7BH2uJkKoaCb7rD5K-pFM9N9_8zObS9cfYihbMoEBA3okL
YLmcSfd8PIALYKfbedAPw9Uc2bbO8Oth6BAuAYrocUW79f4hxNAPI6MYKfd8PIANYLmcSfd8PI8ZQbJKlpMl-ZUgKOrgLACwdDkv4-L4SYKAmzhN5Ft-Rti5
XopBo8pSYgu2rUMV3MHv-Jf5sM68KMTK1QtrALMrywdG-LJed2gzWyfhphX0Br2fFLH6DCbmZbcnYlEdL8bu7bMeMNrJwVEe21UE6okNMd96AMrm-OZEkL22
KTh6Wfrr9MUhPNf_5MxRKiXzEv3sEaAD--QwbKJjjcS5LHGr3GQNS7TBiKgieY9ysRbLU5PnVZLL4TTA43LBTFklOPK9NegQ_599dSji_d2LhDMbl1r8wB0W
22eyn1PGPSoYHj5P9LfLBZMDKqUyRmaLNot82DIeoZKdQW4gkuhAuwYH5frAuI7UgDmYAfAunbbmN5HVAlcbYckfZC3jAqRckY1_V5pbLLGvv-HnxWokXFhn
cxAc-wX4MKJLbZ0Y4PEJhKf8WwrsGPNdSyOfLd5vFLN01RujiOhPAwYiuAHo6Mj1tkvxZw_UtkvWJohNm7kDQZwA8UHlS5dN8jQufLHzK0qwh-gZSX_L7daf
fJcR2gsZ-gW-ge_ge_geIDTIQJ9rmTV_QYcbArtHrDvTbKKjb2PP5-pstoulQhIxwgFwg68jxwIocZCJAd8robOhu_EsaFWvHC-gx0rsD2fVDyHI8s-KLDgc
HXMiKiOpBbejbGsvUofohD8pAb6p0WLUSDklBEugq-peJc2KufvX5Nz8XJyfq_-oHjJsLMs5PwgjqAko55kELPoi2wJwpo0EL4aQgIHrAekfm4Qiuc8fJZJH
SIhfWxsVa5x5Et2CGgTI60dsHrPvoWeVYl1-51JU_pTFHTBuQZ5M9VwYx3DLtfx3xrGuUgbaKyjGuV666v7l9r7JtLEHUwbiQJvdh-8T6JlwMI6DIoHKQRii
uBvsDN6jUofoBvNVRiaVLTY1gSXEvSIM8LOHxxVuE1ohx5Z5pQe2VnjwgWh_eIBRNanwbVck8do6_LL-K-b6fJTLkqCzgch9Id7FTIhCqconQlSJQBR7bMaM
PAFIpOu75OKQ9O-Hw5uLSBNPEaQ5wp7f-oVZW-H4en9Xs_6e2fZbVQFgLUckBHcduQ0JMDFtCvJl8r9MYqPLCmRNEdfKuUq-HPoqNaNuY0wVmXwduYmk4eXL
tOxkojuKUbM9eYaVTW8vHVYfxRbAKwzgDvZIgzfhlupbC9NJc0FTbZBk-T2yrYhevWS2rQhm3aXwwbIkr9B21frvsH_n_Ig5cEXhCJNt-hM-7Btt0Mz_lYDs
RzzPzHQTNsLEhZ9i-CnAIIdZonNPUffGlNNPAo5CcZY1xsoIeWRNEMQ5EN4sdqB5S-AaomkVm7vEdFHvQLLsKloKyhIUgfzJxmfvFLN_UEfTUikkeSASHacr
rZMGs3HqZKxWMdFYvE04hZOdJgg1Qh4vSL8ELEkPq5FNYgQnQx77KvyQg9QPqtXUIy-9ivrgGTDuN2SmeKwrkgbthNYD6BlECITElapbnQ-IFoL6lKpbVeKo
ETtARUGNLzb2g3HTmkegEhVgexANCwf2tNHALUt_M_LHVLGVrKVrvvIg6hs1ojYQ4JLftRNOeshPrRoJ0nLwkKhITHAf_M6TINsNeeSgz4OgwbHTPgZYia-l
LV6BaiUguQoQbFRv3LH2ZnFFYeygKNSRbr-fYcAYeQfcV3wV2gxpgU0wdmgkywdWEaAbR4Wn6FbTfNrCqMiXZQx9YjOr8uLsCKQd-PtD_NgehTDZ5RjsLpcw
N4hzEzb6fMB1Qd3y_zInkE7hQgr42SAbBfBKgIxxWQfpxQSAbz86bSxRwerwsLIProzPVQdm1zAfEDrdGjvB1LIlaa0rGOKsbeIAwSzLHl_eehrKfdjBxAcz
2gm05TUTm2PzY8jLyKunsgHDfV39o6ljw555JckFLL9VgkXSl7_GrAaEcXUhL7jq0giizXZiQ5IGr0nM7Ql82DIfZfmNgpIk0B8XHl1mlcfkKxNlw6-Om2el
1geTNRtA541GRbN5RF1MfH_U4Ihz7wgnomOwJ6Lx5QozYjH0DNH5-kSda5Hp9mhXMwl_hWhjLIOCL0UxM2Kp0BBULeanfddk61PMyGWTtnwe3dQvxz-4iz_E
TeILhzQbKJskaXoeZdQnIb7_NPW1m-_2JWnKHxkW0g1NYNWPgovH35H7kw02YtWjqVQroi2B5B__T9k--F9dbMJLuIwea8wbN2w5l4fK2tTiBfUwcgsXQuPL
bj_Wi2zGBGzK1xcWufHrpaX-9On0Kc-hM7JteKdjy8PQ-pwSp4FLs9LeJlNNGJLunqurxpf8TPbHpRlSNxl8_htAtrH-KhM_YuBLaweofzhVHT5gFQ4ADrMO
KEtkWkb0rVukcD3iBo_ZBrMNFpEv2HTChrFDpyldWMbQbQ3QyGGYySGrDishqZwgiSl0rPcMK24zS7McQHK-PDvVDNRrflbPNV0K__ugP9wwUjEyIiLIIbI7
g91xug80quogpsKdnEwgyJc4QLBL9t-rYGQg-NCuJebzqh50zQ_IhtV1nAgNpCiv-MzD1YPMlSOLIdPoZpb1zI9NAcNWcfmJLAzncLBhNFDpsb65b1w7roDs
hjavxQn2epbzVvLbjlAVpGdH3gRHEUnVF9hWcZJrvJzxDJ2nQ_uSigdlpvuDJ8DvJPf0Ej9bi3hhUlsSk6vE8zVRcr0tfu5BZ3ElDQ67EOrSPcvEzEVbZUUr
_voETvcXgISjvnhFQK7NU4whkipW6h6MQpod9LtFJHViNj8LxGdcrBlEOaBdCw7pcT3vJEXy9dG-4pgV2VsjwNy
}

