sprite $DaprSelfHosted [636x572/16z] {
xDf7iXiv48R1HQCT6WZU_xQpbQMPuC-Iz3BFy4N1tjuDRe_5keF2yA2mFAWh3-hAWxBoeAuyg4iFojA3ilIWh3meIm_gqeEoz41wQ0_nVIezA4iFojA3ilIW
gZqeIm--N7fe3yhIWwhse2mzg6eFlbnwQ0-gseEozE2hjOVsuCkbX_RWC-s1zj0UF4WFWD6F_ITmz1dMs_9hSCwWiI-_1NimlNMv0zfCEPQxOAlQwq6V4TjI
0glkM1w2QmRqfGOMtNDv20xj1Q0zj0VQGtkWlG2qX_P0UsWFj1U0zj0UQ0_jWVO2q1xQ0-sXFT1U0Df3Uw0zj0VQ2q1xQ0-qX_P0Um5e3-s1zj0UQ2y0xQ4z
q1xQ0-q5e3sq1zf3Uw2z0BI7za1xQ0-q5u3sq1ve3-s1zWBG7je3xQ4zq5u0saDxe3sq1zeBG7je3xI7za1x0MWFxO7sq1veBm3jeJtG7je3xIMWFRG7saDx
eBq4j8VsG7je3xINWFRG7cWFxO7s4j0UsWFjeJtGNWBQGtkWFRG7saj0UsWFj8VsG7i9Q0_jWVRG7cWl0UsXFT0UsWFj9Q0zj0VQGtkWlGIqX_P0UsWFj9U0
zj0UQ0_jWVOIq1xQ0-sXFT1U0jf3Uw0zj0VQIq1xQ0-qX_P0Umbe3-s1zj0UQ2y1xQ4zq1xQ0-qbe3sq1zf3Uw2z1BI7za1xQ0-qbu3sq1ve3-s1zXBG7je3
xQ4zq5u2saDxe3sq1zfBG7je3xI7za1x2MWFxO7sq1veBm7jeJtG7je3xIMWFRG7saDxeBq4j8VsG7je3xINWFRG7cWFxO7s4j0UsWFjeJtGNWBQGtkWFRG7
saj0UsWFj8VsG7i9Q0_jWVRG7cWl0UsXFT0UsWFj9Q0zj0VQGtkWlGIqX_P0UsWFj9U0zj0UQ0_jWVOIq1xQ0-sXFT1U0jf3Uw0zj0VQIq1xQ0-qX_P0Umbe
3-s1zj0UQ2y1xQ4zq1xQ0-qbe3sq1zf3Uw2z1BI7za1xQ0-qbu3sq1ve3-s1zXBG7je3xQ4zq5u2saDxe3sq1zfBG7je3xI7za1x2MWFxO7sq1veBmFjeJtG
NXxQGtjzUGZEelQWpu2nF0JNJDYN1s2R4TTo7xG-C_fo5nmpPLlkW6tCc6Fv7MZ7c47NllmAjEsQQVqyVWHzp2y000000000000000000000001Wz6FVjjRM
RJ_w_1Y4jxVlxEVCWt6kxMVn-g1lxPUsQ7qmzlPR-qn2UdTiOsR0jRRxhfa0epqqPW3Iszf3wtm_sDiJjlbkSBIdd3C9cxtwBH_6NlwQ3sElQl1Xx9KCFbZR
y-RxmDLUC6OObjpyDGjixGNh3CDsBx_XW_QICQDmkvV_IWMzlQJFlnpQWwkeFHXLPmreBvarqDuwm_1VFl-H1SwYzrmOVy5H0m-wswo1HVUO9J3urZ7V2NhL
IGEsD-_skCtdSBttBPVRq-tHgrPSxR7_iMTSxTdoxMD6Q8-ZtNMya1wtb-BZVDTUZzkBxT7NF-o4gpsZxnppDTfxFJxsD-tqfFTwU_JZk_3w1ylJ7gEVnt6S
Px_-VtZQ-wzTEg01081X4ERVzMMGxCK23V09lSYUs8lm2RtAdjYBy0czofxOg_09lMVun9xGY_09lGYVq8lm2Jtun9xG2_09lG2Vq0lm2Rr0dz0hy0cz29_8
Y_09lKQVqAlmYRn6dz2Bz8cyI9_8o_W9l9wVoElzYJjXKgcJJM9lBx4dzE0JUs9lAh4dzjWJUq8FFh4dzeJUeZsn1v_O4thiiGUVs1Dwy8azeRTZJ-p1Xnvy
Oa_e3UCJUkon1v_GWm-zONn2Zptqu1DwyA6tYq_emOSUV48FFlJe4tdmeRU0J-JHXnvy8ey-ykWJUVIHjwDFuD477du2Zp_ky1Ds0597eCZ3ZppwX1vywC4d
zk133pxqs1DxyB77djXZ3ptsn1vyxB4dzjXZZpsnnnvxx8azzjXZJ-pDn1vxOeyzzjWJU-Z1nvxOOuyzzk13J-on1nzwWWyz-j0JVEGT
}

