sprite $DaprConfiguration [54x48/16z] {
fTG7RiHG28HXIP0UClS_RJeMeuLvAFbLjfZFtSQ_iyym5I6KsVs09cQ_zUYh7MEqPumqcv1cFgl8kTF6WiivfQ9bhbL4CbBtD6I_5NJhha4miiiqh4vMOqQ8
6A-VAuWP85aY40CqinoEme0JSqP1H6vjk7Er4qXXWNOCCcVcQNJnqh0Z-iou3MhO3WMMZ172RlCZYd1hkXzHVdcqBes-Mh0W99b6WHDB51MXPGT42jTFPyMX
ghjwQmi5KlGWdH0OVQKK_g8mAxZrwAsCaE8OeMOpcn7kaoaqltpk1uM-vr_MAAYSrJwbzdq
}

