sprite $DaprSidecar [576x672/16z] {
xD814G00006n2FgtrUDlQm030000000006y00000000000000F0W00000000000000000C23000000000000000000150W00000000000000000000000000
000000000000000bPzSkR3M7WG0C1Xos-s_tB7hCUmhzynLW7F4-9tx4Z_WHFn8_xJ0UMMhvkNBTbdzL-T_bAmFYPyu7-oaZFnTkFTpFpCz7ySCFF_pmmmy_
_F333p_yyCCFF_pmmmy__F333p_yyCCFF_pmmmy__F333p_yyCCFF_pmmmy__F333p_yyCCFFxb4_F33Joa1F_pmKmluuOUVMi0FF_pK-E7dzvKN1Vpmmqyj
ueSVVah03p_yr09--E6d5l333p-rW1z--Aa5_F33JotWXnz-Qlpmyrrj-Qg87txuAVpmmmy__F333p_yN3n--E677txuuOUVZXz-FeaVVlZXXnz--E677txu
uOSVVlZXXnz-Udxu-IH--E677txuuOSVVlZXXnz--E677txuIVpmyqdyyCCFF_pmmmy__F333p_yyCCFF_pmCpoW7txuuOSVVlZXXnz--E677txuuOSVVlZX
XvyqpZze2qA9jytVDgMsEMNZQVsi-RjIyrNzbaELSvKJFx_pKxvh-9BFccELHmR4pvHlvgUi_EpePxsTdzpoiv-VV3i_XHz--E677txuuOUVuvkkw8SVVlZX
Xnz--E677txuuOSVVlZXXnz-bjlvoSq9cw_Yn_pFmi-EVhhbPdwsdfyT_JJzV2i_IsfsZ9zQbo8DfwfhTeYV7HC_ucV_n8_uIStHQU57_EoS-14_ruaVViIF
-E677txuuKShF-9dvyIF-3agyID-zatyY1z--E677twqyID-TaxyY9_hn0y_uaVyyCCFF_pmeypFvUAdIyCmZECu37qVz1FV_onrNQhrVSlF5wLntShhbYdj
vwVkdykh_h5t9rYkipWKWCKWC4AtU_-hxRbppXiJP57my7yNO5pYOwWasBsLnOWIrszlIYx3BPtl9nNvLNjIudm_gGX-aLO2hKbklwZ9bxEEcV-RdC9-Va9v
8qBAL3-fzZVjyxVLV1lwCI6-oxSzavhYDz4wgdgi_LVoTnCWmcP-aYZUfuPPVf9Wi7srF3-FXvuYpuAt4QQ1PBoBl9cLj_IJ11-cslpujp_VJ-xuA9rd-NaP
tjjFQXW8k_j9Wi-Z_3L-ua1HEi_oKnMuvGVp_LJ5K2Ju-hambleLVbWn4eap_B02k_j97QFHxEY75QEHEDrFnMYgkv_GWEtzL8KXxERdWYLvify665Jx-acA
_Vqqs59z_CGEMtYgdmPJsDCFAxRt4pki4Gy_MM5DcUYdmPZgvwS0s_j92dlalXzMs5Ec-MamHxpy5EplXnKEiVifS8Y_du8R4Hy_ZFtzCB3KJy6MVXItej71
3-EB_AZT3sEjdu8T_FX7usq_IR7z_CDOwuTng1_eRJyADpzXaX_MjNuOn_f1l-cdmTcF__eL5KlzH3tO3-IM7yR-VWHh_NISx0VN3JzTlz3Ftsn-6jRwQJZR
3xBT3x2z7yRQAZ9EzwFXp_3pTukVe6lz13tU3-HWFuArVWJd-m4VwuUnra_64_neEDLFN-n77k47RGi_qTrFmLe_1S_mWtYc7rtiHv_YHuxqKx3MJy5J_22V
w4SN5x0_nuySwATWBDeAfvGobqiy_EJXzgkXVKy_SXNEAJDNCVJnQNu40-abVbjyiVYnjw-6zdtz27_R-nT6SZdwKTt1JxRLxfLutVCJH_GQslVr8_7U1TJ3
ZxQI_dyVAHTPwkVpyYk_ER9XybFSsf_lH-BT6eBl-kdbnvj8fI_pqmVEAFygzOOVSJYCLx_6JtNuyPAyyMDzj4UwFlMJNFraoyfjxuDiNhx4qBwh7sMNNMIu
uKUP39dgf_YSWqjMF-p1XoXDzwEPo0CGs_tqHDlvwVTcdrUIqKzpuKEKx7uiVEo0cjcF46td9xZTUh7vwRQlheqCx7xOQoYgrO_GXdwowG2JVVnbs_Odq_kq
cNxgxOvv9TZyQDpHJxa_-5wnG6371-deF3_g-548s_naMkp7FcZ5psAs-5NwA3pF3pjk9el9JwFLVkn_SVAxMBRuBORsNVrqyXECPl6ZSKy_hXktEkwd-qq_
H3pB3tl-b44jVYxQqa_q7Fv4S_nKG_kkVfGSHn1WyHF9BTdHJtBvNS0hVTYFxyxnckEd-Ox7CEv7Q4C__lTUHYq4p-MBYEVuOT_VuiNnFYYR-c7NvOFog9_e
_9_773_1zzSCQTnF-8FzPFeyC_pKrNxK-VCq7lQZjAiVP_iwmG_Jv-ap_8YXStpzjAVuwGO_dlEVhFQJflYfVx8V6eXCy9DM-xdeyyGfVZAPyvUVkDfFM-ud
a6DuOp_zWFddBpyRxt_I7xX_RgltFqhR-d4U_wCN2tlwiNSVp_3Jz_NZstzn6AFlvuS1C_p0-JHK7lKZs_h9llt7C_oeuS_nzHFfuyYp_2JV_ci6FvuRiBBy
-ozya7Y87__-qs4_tNK1xNFyTDVz0CB3_5oEgs4opFTgQD_L3uBdyWKwo4ztE3ppYepxgN2SWDeiFvVdpwda93_YE05bZFif-23Tq7kkVX0SgzaM-ocUVYhW
LZun-CcEvuTadf_cU9YkdkGd-nrzB33u8S1h1MNCyuFiTnOyd-I7u3K193NvwLw0erhzU0bk-2ZXA3_TwVHZL9ZyL3WTdnDO_JW9PWnSw1W_rUVqTUYm-SbE
xr5lcEi7uiC7zIm_6Hw0OeVH3-7350CVJpyGdxT_vhFya3gykZGfp7ukV9XguElf1n9lJ-E0qc5-AcvtO5NO_J1kFu2H5Hv-xFz6n6OeuY5-ujt7xoK1RlWX
nSUfXlOz_K3YpV63jDnFzVL3_TRZFrc0Utuk3AG6Wnu_Fq1Z-ZQXw4W1wJW_ZC42lWma5WNk-WaOYfJNDI9Vkk3z1HV7LmNAO0NAUNu8mz4kqXM699-tntMH
KRe6F_uLK3hGJuKjNdxYSzw_KqxqGulza3p5ZuOZ_PJ5Vk9J_1GwqW_rjNweFSEFqg5-yc8_z0m_VAeVaiL-oXFy26tXvvhWXnRx8JdVZyQ3_UJ5ViBvVWeT
x8VQMZ_4f_iHEjeFzRL-g9tjfzFXVi9YFoGd-z5ykXzAY_sG7ko7wNW_b1VxYUVwgVG0FyHh_L0yrK-bH_YXWblHctuedkcdqav-cfiVxreMlUc7ek96gcpf
fz9Z_52wLQVRVYXsc2CqoOy8x56c4_tupm123dw8nDx-B3-Dx80qqub-_3jGoCSFLMFxOPuVksg9z3G_L6rylFmG6_bCz6C594Gd-l7VX5JoyqDHB1qrrmzL
dwtF-NuCnL8cJpz4RE0xsGybDKo93_L3iHaMUJy_H9U1xpG_Xdk2PABd-Y7AVQ3t_FrGl0R7-Nm_5Fi8wKtzYC6FAVd2-sW9PF3Z9aWb4attymftmp7lX_eX
2gKF5OhV9j1GMDxfZTzq1RzBlEc7A5qVY1v9uBTPxiUUL7xPdjP8qnD-JKWRJwtdA_gvQXMchMFtOq_-qP2qOi1ZRrz_w2UtzlkedrT93FTqW1zRGivSIlrN
2gSLPKh_Rx--Lg5LVbubuN9TxL-vlE_fd-tT2Kw5I1I6KTx4MFZslziEwSoDBQbVhI3dMu8v3wZ8lPp7Zye1F-UB7txuuOSVVjRkBxLygn-jE_7JF7xuuOSV
vNEtDtw2-E57oSpPdPyVY1z-z3W-TSsF-2dVwKVF7_R33pzFVXIC2l6JnC-B7mKxZ_X9ugVdHy6eDZz9_0py_9luMIlyA5hKCF8Jn0y_IhwxCV4Jn0y_IjQ5
plm4ySEFak-UBVmqY1z-Z2_payPFkSAyKkx7-2a_9VB3ptwkFwhxS_AJny_D_Uj0na_vMNx03p_to_XvftwCd_BppV7pu6StFQ_cv_xxVlXvybELyLD-ylXv
yLELyLD-ylZf-QdA-20_UVmC_EocyRWVViJFu_Vzy3FoKvNnKtxo-9dugShuAJzv_CpyL6Nyb9yyVXP-TbE9_F33pyK6K9-_wSVuAJzv_Apyr6Nyb9yyVcxy
L6Nyb9yyVkxyL6Nyb9yyVXxyxAJdvVoyJkI77twCdsuz-MaGF_mOFsqrmCmFF_mOFztg-MaKF_pmC_1JbV5JVlBu6V_WYI7teyTuZC-3dxrqwylwLKlVVH8_
UavVy9aUtQVnezjGriyhmwtxl_ZHSru_QtvsNyIFxkEwtt3lleuVlVO6uPTNToX-z1YJKpi_wajmQZzDmw_uSPAVdbr5_3Z91wTsVfpaarCxFqxooQcT7psN
PtUc-14_uaVUc7j7WCHFAaZyx0kIxlC1Fxk2fCTOrWD-gWI9dirFhI3Hi_cf5IHwDZ-LWaJFvcUlJlG4VWYY9_1343s17uBeYVqGHCznFmJfkUb9_EpNzxTE
zDJwMTUP87e2FmJHa_WXY9xCpzRy8eYU6Zy4qPFu8OYUn0z1zEH-2A8dzxCr4KHFu6SJr8cU2Zy4qHFu8OYUm0z1zCH-JhtpZvu6VWYY9_1343sv7uBeoVti
Drv043s17uBe2VoSM10zQrRkXo1w0Z_7AvSGH4_kXo1wSZ_xWXxT1Q8dy4CGFO4VWkW9_114J-3dO6Nu4uBeoVqGH4_YXo1w4Zy4qHFuoLhEB8YUtC_x8nPq
xquOFRaVWkZ9_MmHH4_Yvrq8egUQpzOQjlJN4KGFGNdqxD_52AAdxEXm3KgZv-S5pHSMH0z1ddloSa6txeAvzX3asaDGY-WXY9x6WYm3feSWUWXg4Jq4qTDU
a9Nsz114JpD1radJGn0z1BMF7eBeQI_8Ecbw2AA787fEAyWouET43q7q4FJpqKCGFGJHKnh820HPQKzF8CWoO7e8YgA787e8ekTKWYm3fYU887e8eeSWUawG
bVRq44HFWomafoV8Hn7yZvqWUXhbemZq15b8Ja-GXUJq44JFUIhdNaXEJvwLzlG4MGPCJnn1z1143q7qd3FBWEaXY1w2w3b11D4JPI4vFGHvjx1zbW6_w268
dWOHH0z1z3J8Ecbw2AAdGGJHGn0z3R8Cc1w2w6aGGVGGH4-BhBHlhsTvdo3BWEa98oZNu_KUWkZ98wYzde_t2IA8dY3hfEa98eYU888yDGTPI4vF4a7qH15q
foUB84_DMGJH4-IZ26NOXfwVCpsr4HJeyTnZdNGKFGJH8tgoH4-M2ZrHeYTBz6I9dYpHaoLwiaHFbkZ94ZrPeYTBz6I9dYpHaoLwiaHFbkZ94ZrPeYTBz6I9
dYpHaoLwiaHFbkZ94ZrPeYTBz6I9dYnbUgHCZvJfaJ8zKgP7olH8cHufqoDbUgH8Z_IHwH51aHwfH7gaakcH_gD7_m
}

