sprite $DaprRawMessage [384x384/16z] {
xTat5GH130L117hYp_R2pS_rcce4e_hXx2EI94cI94cI94cI94cI94cI94bpnlZ7yO_ZNyS_ZdyS_pZ-SVpZ-CVnh-CVnp-EVnp_EFvn_EFur_6Fun_7Fuv_
7FzR3S3V0EMXzG3yqmNujmFmRmVWtmx0Fn-0Vpy0_tu0_lq2_Fi1-FS3yDzs0Fxj0FpR0VZd0_3VoHRWtmx0lns0Vpi0_tO0_la0_Fi1-FS3yDy95k1V3i2_
7e1_Fm3_VW3-_G3y-m7uxmGByEy6uDyFmByVW7y_0Fz-0Fxz0FntWWNuHmFmxmVWtm_0ln-0Vpy0_tu0_lq0_7U21VXt0_3l1-3V3y2_7u1_Fm3_VW3-Ey42
_Bi1-FS3yEy7uDyFmByVW7y_0F-TjnRWNzLnyp-kuzyEmDy0_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-VFt_-_Fdpvy-V_oNY_txy-VFdpvy_V_xy-SyRyJ_Y
pvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xylOy_V_xyk_Zpvy-VFt_-_Fdpvy-VFt_-_Fdpz__In_-D-FFdpvy_V_xy-VFdpvy_V_xy-VFdpvy__vF7dpz__lpv
y-VFdx_x-FDt7t_-xkFFttty-RlF_mj__lpvy-VFdpz__lpvy-VFdpz__lpvy-VF_mBnvy-VFt_-_Fdpv-y-_lpTnv-_-_ZpTnz__kxp_yAVFt_-_Fdpvy-V
Ft_-_Fdpvy-VFt_-_FdpFtty-VFdpvy_V_xy-RkFFt_tyUVlFlxytSUVl_lyl_3dpvy_V_xy-VFdpvy_V_xy-VFdpvy_V_xy_R_mvy-VFt_-_Fdpvy-VFt_-
_Fdpvy-VFt_-_Fdpv-y-_lpVZZz__lpvy-VFdpz__lpvy-VFdpz__lpvytyt_ZUFVnL__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdpz__lpvy-VFdp__woT9
aYH9aYH9aYH9aYH9aYH9abu
}

