sprite $DaprApp [262x306/16z] {
xDd7SK0n30FHkpyfzL-j0p4-mJdBs5V23aTn_wRgUpjRFwA1q63KpbFjCWV1qK1e83GG6lp_xMBrsmNiZMz20ubS3bn5hWSkSn0S3OG6esWWD1WtD1Xhd-Rg
xr0qEAp3wk-KkHuu6WWDHj7WJnyVgdzMvXmu6iYYmQ21q41eC8e6GeEn0iv8Rv4v1ovo3bnbpe7xXNUap0vzXiZrm5Na7BYYmQ21PAu7ZWP20ubS3nmDf6WW
D1YLk2Qseu7GG6WWPpoY_FwVVsUWWMIk1-xQhWCjduEcGuSgAZouOyS-bEHMWG2A8ZKYlzN__-sh2LWCfMc7ZGptLbgtuno318i22YYWW08AAA200WeeS8_u
gyfbAR0MqhRlA0GHGI789HIkMO_2DO_2DHIkMHHa5H4KH5OKBg600Weee8022YYWS9v70GKKK4011HHGG04555100GKKK43X_HNt7Geee532hJIrGZ2txDGA
rjmh4oiKK_CJAtXJauaLnFmgJwkGpP6RLi6Re_Nitv9ZpChyDHHMqvIEVR9SAiMPQvAK-VWAwRuN-Ysnt5GMKtFAV7Y5-ySlgxcqT0gBEH9bFhP2_LHIDL8p
xmlAV6o5UFyWTMTiYi9IbFdG2bizEzUbNZe5yJ58VGGeyv4Loh6rxriYFYf8UzCGPJwoGZWk4AczM7PBezn_fCm_eR9zaO9jBfDB_RfHSDsRvDbyQ8Mw8Tf7
H6WLukD3D3sVVxx2-iaROd6Nf98q2ldniX6VpOTU2s9EAfCfP7EMxtV4yUZCp-OZAtXprjee-CUjeyp7LLZDQVbGi0-_Sb7cdwzWF-iwUPux54neNmMYp8TL
gBVfKeltBT4ec7YiU-EL-R0AI_zeA-PMQczDo_5LKUQZFXUE__d-ABdzZ9jr_Wg5xLZE_Icg_xILIvaFgb2NV-vdxUd8cL_PKXNw-SWA-UpvRklwgAUZk7PF
m9Fvo0fwnnanUkT2LkPJAEZpIHLGG04555108OPBHPb_jOBzRvvq1HJMIHMi20h9gZi21HHGG6550OKQ2YYWqBIXW0Bl21HGG045RbCed1KV5HmA9oTe5510
0GMB0WeeD2qJAw0WJtO42YYWiCfs7wE0WfbN0OLmhe022Xu55EwXW4BDe8022YYWW08AAA200WfQ_lnxq2YWy8Q2YEme_4u11HHGG045550eA8Zi-uIheKJR
ALnwcynWawxzbfdLe2hK9Z5m8fh2_ZQhGLMe3YNd5pP8rK1Ns8tOM5xJ88TDZbG5Awjih-XGJWnK1RauJF1U-9s2M1VB10QwmgNgC861eY2ofJA5WQuWubAP
m41HK1n6FIFzku9Odygh6kWAYiFWvyH_Lr3E3oEU4_zTGQnBPUXpuhyhz0wZlXV-NK5t6Dz0LrX4oVeql86kK5j5oxeyle6kKDCTV1xVG4UesU4Sz3EIdjsV
9Lesv1aC_c_FJ6mS284WQ4FlZpJvHtiF2RJEFIVJNYg4ufaIK0zBz-3IYVmi-7jevmR5WUO1s-dOYTo1C2-Svm87gWT_1nsmUM7e0F5tdcG_D2y7PGd2Y_EY
-JX04CIvwNyVw1wEDa8dwWvq3uQTcEzXFTgudOX8P6FtWqKdwe3D2uixKQTo3_uET0z76yS14Fz7OHuiMbbd4pmOET3xmRELy_l1i1FppyLwDkTErFk1V_Do
1p1nqAdiN3XsOlv-E9fD8-dxeGWUJ1tezqE-0opnVa3cXKSZwLHXRgeE7Z4E43n8Vww3KSYtNhFeH9tAF5XqeWw81zDEp9-R5fseKuc7x4RoFHVT0RmTwD_-
xNnz7onXmuCKBwH0CFA0ciyMVYHxAA7Yxm5XJ4qYpC5qq1dWBDXxYCzXcmuwGCOxaZybvKBmPydP1_u8dNWx3t43fWFg0I7Zxo7knNCww60wwEGCHt_oBaN_
hiRxEl4R
}

