sprite $DaprSelfHosted [142x128/16z] {
xTk5okOm58HXeDxEdBd_grq9-_rkgPsmp8iLAqzTenBJqxyWa61g824Kp9CbsICKJ2CL3jj9OZCSK6mhF4sazOPIKbfydzOfft5vnu7Mlijg5TvgfYw9qtVJ
HvgihB7cXrbZZJNMM6EDDTPOOuqrrbXZZJNMM6EDDTPOOuqrrbXZZJNMM6EDDTPOOuqrrbWJMv-5wTS0NmTjSrARmBSXb5I07uIa-7y7j6I9QCO3nRQ56k74
FFJzC4SRcB7h_zIDoPodNyXBvGIVtj0_OdQ8jNzg3IHhjFHFBShMnDO_jGMO6pG-zk9HgPYd6wE26SvODJZEAKTLmIHIdZYnplCQ0HvEnqLWI776V2IUq5dt
J9BOJAsDrrJX4CYs54pXYEaLHccJga4uyyJnG3mALHRy8bKNEX35BnEZ4dEjHlUrwJkDGhT5yPl414m-1q-OcXtv_EhEbHAkz8HALIUrk1J3ka8NYQAQGbnv
j1FS4QXhCVcS47Udk4zZZOvehkW6p6y
}

