sprite $DaprKubernetes [378x60/16z] {
xPlfsgCW38K9Mm8glV-xdQ4rBSTArNxRB9vVOb3a9OQ0ZvU_HAV6b4u8Fw1qKpv9_0Xt-NRs9tT9ZKuYtylzvzcVtEMhsP_AmFtJs9yo6t9H97Ka4gnvGwUs
oJj6VnVdi2pnizYVv97xGi6Oc52VpluaxpazAHh3p_4-ElDArWK9vg3qGl_VaRSiwLby9uzYCXt5OIerFJ97nRSBvNyZJ-lpgXXQFzz5Frwg3W242_z3yYur
0f-NjAPkL1YE0Jp9XrN7hW7TXjKu5FzjyaJVHPwVqJfI8xcObXBwLycxm6cOyZUHrsZk_NomJ1tjF3Ji_4pU_gFavNBLy4tatJsiMwbOdNcIbpcd4GZq_npv
zBtam-pgxegUxHnZwe7ZK8it0ptculWPv4_oCIbFCkJexkFsHffTFKFM67klAPz0_YJV9EtYchWkTn-FPAfSKz5-dFn9tYwJ5X8zLXl325MvBo5Vsx7MKdU3
mNktRYJtMnPjLEjxtxiTrRlP8-IjxxLFhfhiGVA-8Shgyq0-qZBvbB27l6_6arAkXzcQAYqc2-HJo7KNeOp9FtURnrBhb86nX-IvNbLLnZpt84YkrQ-QSg0d
L26Ncp7vP_8bfwjoqqqduyqsH5e-sV1etXqW7zD3sgSmnt9g4ncN7k8Tv7qzrhATZ-lDiAZaKOD3Kb8UjYADtym4LONcvm1DmO32r1YpQyYZv4utjtU318Fn
0Vn-yenhKszl8wpa-LRsM5DeaxmhxUFRWkJdeWFoWB25PHSL1b9Blg36-jJAjH6uIkeqrINlWIxi2UOBokucRmMYDytJB0LtRTBFSKFcwA5oM-Jj14zvWBnA
UUYz031rEfuQyg20i53-DNaF9m6zF8tyRl8E7Rd66R-siUDmBWuRv4dV-6pU9L_KVMZ5d3eKOu_yH01htOZayUr5nNi_K6a_-I0Gl7a5Qz18n13e--GRy0CT
8r-c0hq0L6DAzvfkGRxyLZtTaf-cSG9MuC1JJWD4n1xvGOj3IXEE5L-QENcOj9LTv37CapHhL6kRALXmCXPwIJv3LDXBVegM3Fa1dTwMTfeCSoa1-T5P8kkZ
a9BNsEwoOiE7l30r4qYXblmO_5N1Nbji9trIrX4ki9fcsTtaII22s6QD6cxEJnYALEuL-QIUOSrUyeggZLInTVdYm6SdQibdwDC4NZx21KxT6Uk6VZu_e1D9
MoV3pGxbymvZToqAUz8LrlKWy7pe8QFlasS0VuWyqCcumCLM_5xo4R8EmSYkrjGbRmjEqLIQjoH1Hm-H3uBa9JXwl0sYnpuoaa_S9ry0_37ow6PO5Ld5RV8u
ZdvrdMqLTezyc3kpJ8qSn7cce-HZFr_npAx_yKgeI_u2mUyuUNHC3RD9PcLbjvCyQTEjRP1PwhLTyXhiH3Ksxu2xg4hoXyYJA4XcRxP4xST1kqNUcxV9nsQA
vSkwqb7o0TD0LA4U-TnfFpvPntY0lCweZeoAh0-HxsN77Fp3JEJWwyZN-7pOGJw_HTvTFeiyhwmrHh-Rl7zaaUJgn6f5C7LfFW2I3_OUSoHsoQj6-ahowPl8
3ozztb32imV9Y_THseHUgf6QUCJp88XNdm-RC-nbe3V9ymxoydC-ZupzyCwEcPNKI4Xzt5-PysCElZ98hLoNV6A82D3zk8jyVfvXIrp8VIZE9qR5pHcM5x9j
QZxXnasVF3ezPZTH4vTu6m2h1W-355-jfAHnJAGXUyXJQGYu2rG57ITl9cmAbO0UplRqElU0ROqEULG4z3MQyotkMns1kKnGaL_l7gHcYn3W3dl8wy1nMpL_
3ldSMVk0VxT6NFJs5J4ARPCdNW8brjYYlXuWyzS9jq--cPUAGtUw-6tole3xg3V9fv2Fa7brw37S3P1s19qu_WLSzyeg7VTu2PokeWvy0IVbDH9sgh0bed1P
8o-rhcK5F-2Lbp7gnfIC_btoL1uFCcVH8IVrxyP6v3Z2LkaGQ6wVTTny2hJuY22xoHltXBvAe8ZWapTRvF5R82vXYXu2-Qff7CU7qIF8gd4OnwdMu7V96sdl
beTnqi0EJPMfDZCkdtp8mp2MnxDnFPUICATo9DfWoeuHt8N87CCD3M6e2MQRl140g6KGaEz_z_4Tutla2Hl3mCvhNqnYTnrbSlzMIBwZ803MRUIUqMoGHvmZ
AOy3v64nm2lMDyX3M40vk7HvFdL7_lbMSknldRZCBQdfXyPy5TC-ygvSiBpIOzybdzjMOkbyltk7F7vFRwh2GtSY5ARjjkCl-yaJOshfXBspHDO55cz8jcPN
09YMhkgU5zgOsmrFXcX0BdUkpF0A0EekUKCCV24XSUFQYFXnIPvMus0YSuWynfEef5NMU8X5NSburPrQ6cvwUDJyGrGfqv0us3kA8DKmg-H8Atd0TBUFEUgb
CQVVoZXGB5SvBC86NXoqkJ8DkFiNyZGtqvxtgMa_tREiD3RUaDmRVsKwQOA9V_5xfZSV4zagMhKu7u9kZAx8-j2r7nUvsztiMalEEKkTzXS6woFpDHcXz_w7
zGrQVlfXoiBisj6fe-Hnbetaqq9UJmcRmph9RoadcV4c49wwVBvEfRw-5lofFnJyYLv-1lo9NhxGvK_vz4BvvFELoYbtTBBvwtJg5m
}

