sprite $DaprDocker [405x104/16z] {
xPlDjkiW28KdMM7Jh2Nl_xPtU7weRcbiIivb3nE2bYyeHcjd9RzaLwl4eJHBfu9oMAcWb0fAGIaLb89IAYW5fLHGIWMbFhEK_ie7oTBsNVPsbVIxfgwyMQKc
FmKtMkdLmrT9VilWhcISw0lA_KlYWY9goLHGL0IMIWMb9Qa62eht24kZWe8ybND1yGvXELHGZbIhp8BY_QabK47PyYqp2ufxDgwIGu09A076Uhv_i7Uh0Llg
L7bsfRqEHLQyCfT4u7yQ3R5YNq6lw7AQqGeJcTBiuMpsJZuqSLg2-0eepJwbcMcTNkcFKd9ZACYopoYlLL_k2lfG93aKqj6_2GLD0P5TZYq1b8BYXKS2A0N5
wKW0fQ1uNGgbeDXTeHGKAIW5fQ1CQByKIa7HV7DAGR4bK0fA_4eRG46KIK5nqNIO3ZCAPRJ1g9n9GRbM42aeiv8yckdZFW65RgJrpLi0YdPkWJN_ypcu3qrD
agWVFtLsOoW4DSrW0iKz66x-nmqV1OEaqHv9v2uKn5FGozyTiToOF-qysUdj9cbqZ4f2hmwKuC18EYDpwHXitls6hDfF5WVSF3YRZg6eioNDmpMRNeZN8F6I
E-Xz1CMPSdytWtAsBfms3sQXWz9zSAfYmZsWQBEXWb1R3F-CzToBFkylFnGZWimfO4wPS2Yz310klJyKSG84ujMpVsOzS0zW0eeuTTsHdlQRrxo9qgi4sYWg
tlanCOIeC_TGV3RsORNnhnX50d06MHDbk7JnuMhKatBppKEHkVsxVl6yFNEJwCENpaDfuqxphrqk0ixSXn6k91xy19N8CfEld_8d2aYlNLHuM9G6nQte3y_a
QGC7Vx_e2Yt_ZA9cFCpCS_zTdUp5FbbU4pTmdRyJ56RPXT9YKC8h9TyCPupO6vGV2ZYr2NCbbMuGYlRCg9-0UUA5urGgISmS9w6S2M9UACOaBqA1TNIionIS
2I9ccaToA6eT8HZbyr38TtoYq2kKPFCaVYfY1PHz2HHv5SgH20hiRL30pHltpeEp1eecWc8VXQ9ve6na1hnGM0AbyNVl_F2rVdiN3agELB48b1QRw163WW2K
m_Z90AwM4ug5e63HEaNFLb-3Ry4QIPGxGrc-U8n3OVifpenBRH8A4Z7XLFnKkCza5duOm1Mbl1TTAX78vg2aI9KMXiBkBpBtejl1C8_gZb3Kmb0mSvkaefp-
T3_U4LqFfIMeXgC7rtzZFeRcEjZaqY2KHiwdTDoq81HBDg7uJf5xpFpmOPG1HFQHtNymCani1mUX8Dc4uZl5prJ8CdCmA4hyQQVv61HBboU-K_GwtENXTI7c
qyTMTNmWIYGt55X8vC2k-rbFxtIxi7NDEHJRoR4pDwm5e5nBnQ8AEBtksAfl2m5_zuTYGPy8ciUWq7bgEHHBY6JzVnkSTsezLm1kK_xGXO9EV18i6kFTUgzv
-EzrssppVYBx21LxLNkCyoDOPZ1pp1sxd0XYw-zBz6FKSZ7XGz8Z_C_I24JbcstQhykz1YiN5JYJzrE1dP86bw4BpE7kcbFd9XWIJteqm6iI9bv1bnepdwgp
HraCydAhV_27qmyS0RCbQWBordSYWobpxUUKlyXlxY0v-lWryqElh8jtEwcIB1QQ9LDHKSkcecAhLCg8fFGdaHIMPkjL0Z9MN2La7BPAYfn4IfgJH-dgURtq
3m
}

