sprite $DaprNonDaprPublisher [576x672/16z] {
xTq7KhP8541HHp2ZlV_LJkWA4_xCdHB1SzTmwdL_WSVuNvFqDl7i4YHDEa6Gp9uWI6PF5YHwkY3HCzl6ZaHF646Y9mWIFK6Gw2c2H4yN97gw8D7J1OcUBaZq
04HFReYUr10zgI5wKaFqf8ReIGtHangYfpH4Jsg8djGGFQaXUb93zAI6w4aDqLFQXkWf3T5343rd4YHw2AA787hEBqZq44HFRnkYf_GsH4zfY1w2w3cb8D53
43sz8Ne8eeSWUixQDaHFQOWUWkWXY9xJDaGFGVGGHCz51OaUNmVHOmJHGn0z18aUWkWXY1w2wF5XNlIOGVG0H0z1z114ZyRbeuSWUWYYXo1ji2H1z0WWUWXo
xo687eBe4K7q4EJMJ10z_bz6Zzx640QxSuYz8H0pUrgYfoLwMgAd9NfIskX9wOsUbEXfYPwMw6c9dfReQOcUbkX9QQCd9NfQegSbUbgYfoLwMgAd9NfIskX9
YPwMw6c9dfReQOcUbkXfYPwMw4c9dfReQOcUbkXfYPwMw6c9dfReIOcUbkXfYPwMw6c9dfReQOcUb3PwKdgZ9oLwMgAdfQP7QdgafaTAUgGjwP7UaXwfwP4Q
7uaVyID-n8_uuKVyY1_n8tuaViIF-3b1uaVyY1_n8_4ZViIF-97u4J_YH_nSBV4ZViIF-97u4J_YH_n8wrByY9zbsUj7McQx_OYVsMu_ucUssu_ucUts8tvc
nO_uMNx5ZxGj_sst7_4ps-r7_Cns-n4_izr-nCzijn_nCoj-nC-oxlKZVcR_y2Fn8tx4Z_YHNlWHF-97_5meyID-n8_uaVWHF-97_4ZF_8YVdFWHF-97_F0Z
ViIF-14_4Z_YH_o87-c97_4ZViJFXH8_uaVyY1-97_4ZViIFzCZFJFo87_4ZVlWHF-97_8WVYH_n8tx4Z_J0pqpyY1_n8txu4J_YH_o87uaVyID-n8zqpu_u
4J_YvqA97_4ZViIFn8_u4J_YHxhZH_o87_5peSIF-14_uaVYH_o87_4ZhVpCn8_u4J_YXn_n8tx4Z_YH-14_uaVyICjx-14_4Z_YH_o87scxdX_n8tx4p_h9
_CZyaVaZyqVyt9xGZ_YH-u_ukGb-nC_udX_fXP-P-14_uaVyy2D-n8_u4JyIF-97_8WVwPcVcVWHF-97_F0ZViIF-14_4Z_YH_o87-c9dvdu4J_YH_pm8tx4
Z_WHFn8_uaVyY1_faH_n8tx4puKIF-97_8WVYH_n8tx4Z_J0Z_WHF-BdGeaVyID-n8_4Z_WHF-97kkTd9dx4Z_WHF_o87_4ZViIFn8_u4J_YHxhZH_o87_5p
eSIF-14_uaVYH_o87_4ZhVpCn8_u4J_YXn_n8tx4Z_YH-14_uaVyICjx-14_4Z_YH_o87sdZH_o8du-G-14_uaVyh2Vq8_D7ve_ukVs8ViIFt7-ab-MxtGG_
ucVm8tx4Z_WvK-97_8WVyIFn8tx4Z_YHdlcPYH_n8tx43p_YH_o87_4ZyID-n8_uaPxu4J_YH_nSAF4ZViIF-97u4J_YH_n8Z_pCn8_u4J_YXn_n8tx4Z_YH
-14_uaVyI0_yY1_nyo4IF-97_8YV14ZypBRNNOcVRmkINkv-pi-NfvZq_B0kF-5dZo3HC_ti52Hwff-TWaJFzBDNaEYPVWZwCdfs-Y68dcKM_114J_1343tD
3q7qT3zJqFOgUdRvcJq-lhoAdhr-bkME87g27uBeINwceErLzEpnGn0znGz1z7G_Kz0JGVJiy4CGFSqFGVHqFxDxWkW9VWYY9_WXY9xWXo1wWX-2w6b-2AAd
-o68dkvd2dgzVlHqFmJHq_qGH4_tywMWvzTBHa_tSsP1zDmlgUxdftkujY1wkX-2wEb-27BlwNu8egVx-RBrIeASNDqFGVGKFmJHK_mGH4_nGn0znGz1z1G_
1D5J_4H1Bw-dZPxkPzmGHCzUFxEL87fs-vbLGOyd5aHFzpDk2Q9d1vy-WWYYfmlwV6iKwI6eHmz1FNe8wj5343thI15azX1qHFGGHC-74hGXyIdkFGJrw278
oNMy80l9wNbFGNgwX9uko1f5UWZgqKCGFGGT7pq4qKFGyT5343q4qREEsGa4MKXE3q5EhaC5MKXE3q7q44JFkGHP9qqFGVGGHC-v15cZI0z1lYqaoEmXwAnj
zFny1D5343q4qNCxGWIPFUVDIn4sdzW9ekVmRWvT9-taEd_h9GNHq_DI12VN-xHUOGaUFJrh59rSPX0znsS6qKCGFGIvDPyczo2pnmoYnmpQpg677Wl9wJ63
w3ak2ydf8OYUuxC4p_Sz1FbNV8yWUde4ERbw1D7J8yZ9HP1Fx0T643q4NKxFtJXF1Bdt4FHCpv4HH0z1lkyvBeBe8UZXsIVs5a7qj0YY9sQDedjFYg3JwFbj
d222p9uOGVJq2F8hQO-Wu_NSZBD543qz2ycFr_CmJXL1zBG8SdAL27fy-THwT9EFZR_-QFzyzrdrQCs2dkW9UQr6oK_iPX0zegUbbPwKw6c9dfReQMcb9oLw
MbhfIOcUbkXfYPwMw6c9dfReQOcUbkXfYPwMw6c9dfReQOcUbkXfYPwMw6c9dfReQOcUbkXfYPwMw6cfwP6Q7gdfaPeUgUcHcXwfwP6Q7gdfaP8UwIRfaTQa
HxfDUgIrwP6-qAC_
}

