sprite $DaprActors [964x1060/16z] {
xDsxZSD040N115RS_BCzawQimQ1FLJaq7l-y000000000000mFyg63YVLxbYCC8Y1YFyEdS1665J319UcM9Gi2a62Uz7318MCKZuzTnfu9QIAGOZl1ynI5Z4
u41w_aOnM65B35Ou436OOH63X0SQ1WcB62ISY1WaB6AGi8X1mo3XduuO92nYqF2v2q32XXWaB6BGC4XOn21X4OE64q328WODWuH531hMC4XOnA3XCI1X4OE6
0Gs3XETTGCEWOH_q00aF336WOT2mWscGi2463IU1Xe7p-KR4O8Or31e6D0mQ5Z58MCEWOK33yq33W8P1mne62OiOD0ne63IiOT2mXa73W8Q7WOO13OE6DGmQ
rZ1e6D3m1j0me67Gi8P1mne63GCQdWSYFXVmJJpGi8P1mne63GCQ1X5h63GiOT1m3sWOq328MCAWOGs3Xe7JVca9CCDBGCDze66Wbp2WOH2ngzAWOJCC6WOa
l0Wq34Xu4MWOaF0Yq30WuKMWOQ2TCF2qdvG6uZCCI7WHQ1Y89moq4mPEks4WdZ0GJnYGy2BGC11F68Wd3CGJ1k890_64WNZ2G3nX89um44yOEF7FPm7nX87u
SJHGJnY85mp44mPE_68MK1zXe5um42yOg2SCv0i6wW43zOA1_FrWuFnMm23Z6m0wBWumy5_M5pY_iBi0000000000000000000000000003ymlyTmBzQdXi5
ydsTkmxe_a8SU3vVr0wimG3tvnW4d3ax1WKROn1m86CGSE2O6XHiZ471unM3WbKC2jwl61IiOb3mVCNWdIGHWn4EL0mALZ4uZ1wF68omYi48pqSCHbZ5864H
Wu87tae42PjYaF1ynA1WnzCWOH63X5_t2v2mY4728WO93qGC4XOnA7WjOf2mUqmWOKiC4dv_FGwSJz9zWHaMCKXOn23X-OX1mY862OiO92nY-FIT2n9Ekw1X
4OE4HGmI7eyOF2NjzGSmmuOO92nY92nYaB26GSCY1WcB60rh62GiOf2mY4739I1X4QDX3OE4HGmI5Z5e62GiOj2mXa728WODWuH531hMC4XOnA1Xa732kQ1X
Gmn-xA1XCCCY1Wql00cB63GC6jOmI5Z4e64DmwDXCCCX5pIiOP2m5nz0muOOD9m36WO9YnWqh67Gi8P1m-D0mY863MiO3MiODAnXaB28GSDjeE4sq70SQFW5
_hEaOJ338WOD_x5t7yYD94aKHB7CODDat_-sEtfgj0QolFFv3SBiFmh8Xc69OOObXYM66POOPbX2668npB34CCCImmnB33CiXXcM66POOfXXYM66nJ334iCC
ImmpB37Ci1XcM6AOOObXXYM69OOPbXXcM6AOOJ7CiCGmmnB334iCCoo66POOPbXYc669OOR5CCCImmnB33CiCSom66POOfXXYM669OQ_p3G_Zs66ZJZI_74C
tp-6t-UFMiVwlMAOOIEkddx5CCD67BtzYc66ZJXw-nN331jny_OhXXcsujstKynmDIkU_wW7mzq83YjUyn_6S3M0VwnvFCGCHxFYkQAOuLn6F5SKCznipLFA
2OQOuLvMFC-COOQD-ANNGymmmh-kT3p43BUoudb533Din2-x7cA6Gndnl2o66SwlU4MEXvZXJ5Oy0t7OCCDMF2-EOOQj-1N7KynmftNqYATic666hNYsn333
Llpquo5cE90LpxOOPjYAdtiyn0mZ_6UjmFKGCtpdZ7ZsnZ33Hfo-VXR3_pQ6rvoCUBR7CCDMtBv-66ROYDFNpp3Ci16dhv_5y8tpp_2z4K_vV8OPDkAvImmp
RCJTwnbcs8hxrm_331lnSww7cE7RPiIBOOOPJZ_1ClUAOOQDk7izmmnRSV_wOPXX8-vUpp33Ljo_VXXcs8XJrpFCi1K__tg86KQOOOOPDkBGzGmpRCK7NpyC
Csp4eUiPPjYAdtyzn0mZp33331jnytg66RRY_TT3p33233FCi16VSpt3LmnRiUiPPfXXY1b6c6666JRYsFKCCsp51r__OFZFO_Z1y8rZc64ZTZx336-8OOOP
DkBqzGmpRCMkPvZX_J7ycU4_Y-7F38VEPvXX8tO-mmmpp33333FCCCD6x7o66JRYnJ3333yzrs-BOOOPPfXXXXV333DinQvdc6666MQOOOOP3iGmmmmpp333
33DinQvdc6666MQOOOOPPfZXyWVpCimmmu_q-GmppB3pzyGmmmmpp33332-6_oo65yCCCymmmnkkPvXXAsQOOOOPPfXXXdrf6iCC6x7p6MQOuUZ3qWmpl1YE
NiymmrRCSDymmrRCSCCmmqRiV8OPPXXXXc-O5S--66ROY9qlCOnmEbdn6yFFIWo_RJY_PbWoOeJZoOePRYSZRh_VGM8uVhranGotan4Z74zMp70x6J72yMJ5
3BUJ4ICSJrRCS3iPCSBnPCKCjvCH8nnFLinmF1anmkran0Z7anKp74z6Z70x6V52M12tLynmF1anml5an0Z_kmJnn-RpuuGbAqOudgoOuNWoOeJpQHq-OeJZ
oOWHZYSZHZYUZ1ZXU39YXEF9Y16E9oD6E9wCcE1uikA5i22EhnZXU39YXFFfu_0H4rnFLenmF1anmR-JA5udt_yflmfHNBe_Vhnan8lWdoQAL-_-HR0elWGd
Un0iYkih9hYUZ7WHN4z6dFy7Gl9RA7-xPCJyzfCLyoih_YAYzxoCM98aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aILBoKpqbdqsR_tnyQHswuhVybqr9
wzmLpnN7CkBmwSblC9NM_EiEyEltiOmuS3l5ikBuwHZBYlEdOomhhj-EiOouUJp58lYgVpl5ikBwxHJBYkktKomh3jnESIDzp9RwWYcM5GTlfrW4NxqVJPXY
6N7pU8XbnVtZAPOHzu-dM4RSFnvYMN7_-9atUrHznBFX-kRzaX7F3CJTPCLpq_vdbwgFUFBN-rKi8wuV3x6iUCFneR-dfJKtRmFXoFsI4Sz074v6F0En4Ewk
U4tzV6aozO-7M5OSFnvYMN7yU8XbnV7Z8POLnu-7M5OSFnvYMN7yU8XbnV7Z8POLTu-7M0ZFAbyFiH2UMKTV3x6CUCf1B2EUSX3BYASSmxBYIGUnh7WW5iAt
wFtewsSPCiBvphpUBsAjerSywI2M5G_4GlX6VJhgUeXbnCEm42wlUD91B2kUSX3BYASSmxBYju5O29TVhpG7d2-4YnrnlL_4ik8f1x6CUEenhCVHAvvq4CkA
fnp4Ck99nx2iUCf1B2EUT0pBYgSSn3BYISUmh7ZAGImZddGCougd7CGouad7iAnuoa4i8vvq3CkAvv3U3HtXVCuNm_5SVwl4CCCGouWNms8ubEjlb11c668P
yQHZM5OyeI0MmWoBuNoktvKOPXXY8Som6Cxd-cvYcE4FaqSud_E_c6J4Ys4n7CprtSGmmyle4Sxd_7fYk7yzmx9YXiKmmpxUKWXloVdjn73_UePbnGpt4iCC
Cymmmn0BOOOP5iCCComZNWoBuMok_xQlsBiBurQ2802YXHyFyi_MnMQBjTlIwmWCUZM7e-ibXXbcM0mppF2oVj62yFmn3F5wC8OPPhZgzpM66MOuwlUrXU77
wBb_-oS5_1h333FS5FmQmmmpd0NSPymmmmIt5JFCCC5jnGmpJ71RCSCC4znMp333RS8GCynmMp3523FSVg41OeOP_cq8VufXXbEr2KFCCCDjmHGpp72RCCGC
Czmc33733BS9Gymmmtd243FCCC9Vzv_XGWpN7-mmYXbcs1JkBznYE133_xz21Z7339l2FyPm88RBX25ccE4sOOWPPhXD66A66MuJXfXXXkk48MQOuJvXY1ck
nZ3333DS9mmnmmpt2KFCS3M66MQOuJfXY1bck4yOOeQxCSmmmmpt2KFCS3M68MQOOOGPRiTmUu4Mn0mpR0mpN8_XFc686Qx6CCCCCzm-6uQOOOQDOORRCHmW
337333FCS3w66MQOOOOHVaNCCCCCCymmmmmpp3330S8GCymmmmpdOvXXXXbc6E5Nn0mpp33333FCCCCCCzn-PGbYXXasXXcEn3333FTZc6666MQOuOLXXXa-
HDWWPfXXXXbcc6666MQOOOOPPfXXXXbcc6666MPuOi8GCymmmmmpp33333FCCCCCCymmmmmpp33333FCCCCCCymmmmmpp33333FCCCCCCymmmmmpp33333FC
CCCCCymmmmmpp33333FCCCCCCymmmmmpp33333DidnR3uHXc6666yp7CS3w66MQOOOOPPfXXXXbcc666bxHXXXbcU4UOOOOPPdYo66QOOOOPPfXXXXc6U6UO
OOOPPfXXXXbcc6666MQOuLk5CCCCCynm88OPPfXXXkSCOOOPPfXXXXdsxXB3WHYUCuGPPfXXXXbcU608CymmmmmppF3046QOOOOPPfZXWI7CCCCCCymmmmD3
c6666MQOOOO7XZ3333FCCCCCJumOOOOPdZo46MQOOOOPPdXQn0WppF3q8Smmmmmpp333ao96c666suWHPfZXGq6yC7op66RO66QOuJPYX1bck8qOOOOPRYD6
c666suWHPfZXDcA46MQuZHXXXXbk8qQOOORRY15ccE4sOeGPPhYD66666SuZHfZXLeeBbXGdBAbEM59SiAGwOKbnmPBgMtSarOUmfBfWINN1akg29UK5Iye3
bfG7BAaFM5BVhwJbCHx6acJqIf8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8aIP8zyQNzqfBby27AalhVUYZnstKiyPjrB04SPYm1ZB44y0Z64i0OImIN
54i01vu0aGYcM2BuDeVK4i4KImG754i4GomXV3t54i4KImG7RZH921l54i5NKomX3B54CCKImYSYbhIjAyII8KonXF29Y2NzFw0eYrZoXIkUsf8SHmyOnHB2
44i8GomXV12nX3344i8GImXV7x7ajZ34aYaCiOJmOSGImX1B24Ci8NmOiOGmn1B29SGImX1Bdksm540oXWrY8GonX3344i8GImnB24Ci8GonX3344iFNJa8O
OWbXY2M69OGXbX3s1fF4i44iX26M66POGXXY2M6NjSHmlrr266A9OOObX26M69OGXbXYc649OOWbXYM44ssxnB11B27CiCGmn1B34i8GImmpB37Ci126M6AO
OObXXYM48HR334i8Comn3B74CCDYc649OOWbXXcM66PO33Ci8Gonn3334iEL98OP5i8GImmpB37CiCImn3334i8CImn3B8OPbXXcM6AOOObXXiKmmnB244iC
ComnpB0OPbXYc669OOObXXaMmmnB33CiCSomn70WYM66nJ334iCCImmpB37Ci1XcM6AOOObXXYM69OOPbXXcM6AOOJ7CiCGmmnB334iCCoo66POOPbXYc669
OOR5CCCImmnB33CiCSom66POOfXXYM669OObXXcM66POOfXXCSomn3334iCCImmpB8OPbXXcM6AOOObXXiKmmnB334iCComnpB0OPbXYc669OOObXYM66Qxs
qZuTo000000CyhU-nrSEuR33uB33uB33EEmmEEmmEEmmEEmm3ZiC3ZiC3ZiC3ZkCmmw3mmw3mmw3mmxZiCFWiCFWiCFWC3ZiC3ZiC3ZiC0ux30ux30ux30ux
ZCCEWyCEWyCEWyCEux33uB33uB33uB33EEmmEEmmEEmmE0mEEmmEEmmEEup33eF33eF33eF33kEmm-2mm-2mm-2mmpZiC3ZiC3ZiC3ZiC0ux30ux30ux30u_
uB33uB33uB33uB33EEmmEEmmEEmmEEmm3ZiC3ZiC3ZiC3ZkCmmw3mmw3mmw3m-2mm-2mm-2mmpZiC3ZiC3ZiC3ZiC0ux30uxJ
}

