sprite $DaprDocker [249x64/16z] {
xPZPajku4WLVodMAUAZy_w-z6nb21G8GsQtcdHcfqnlCOn1Ax1QN47f0utFOghZu7FGh_Yl-Z-TN_5VS3l9Hb2FVjLquduGUOBmdJP8K8S7-f_QYvAxuWDMy
B3BIMl9FfwxcLP410xOt4F_gY0i9_EF4ZP0aujF4TMJuPudt2FzGyS2uGheRtyRSyuxhseLTtUq08D43CZd701hVn02C7yCuQESZlb6eYH2d6F72zS_usSjZ
eZYcQy6OK_-jemx66SahNs0PfQ7xhslheX6eG9WroUra3_5lYiSFdo1Hbd3q8gT5Iw4278ITR9xeRoB-8AwFU14V0RstE8xcOEyj7cW1zjRYMelhhSNpZX7_
--_gpRRWqe1RsvgjnAt9Z3bPmeLuCofcpH8gkUNOLCfUEiS1pI1Bin8xJL75nv0HEvwHhfMu4eonWddZmGPijIc9rx3G0dgx0aAI0b0Lhw406LG4g8GpSQyQ
Vhmj0l2izpsiDsKWT0k80nFKe8gJO-XqhA4X7CLnw7FFZ9ZS9JOUVTUvoxjn8D0CD0rnbZM3RH0t1-sWrTkIJIuNkXqG1oAq51SvUxwkYLF57KgzXcOLAC_l
fImk32r0D1O1WEPX4JUd9i6wcRi103SuI5YBhq8SCFn4tA46ZT0CtD3D12wNqH5QWPnQTp0NUYek4KCtQWun934q-3eumDHxOqSFIfX3w6H31nmCukDXe4K5
2Q-jTcuvmiOL3cvcjlsPVHvo38bUjF-52hPQ2NK2DuW-azfUGGV5aRQ_pTtpnW5lNSJOSMByEFpfeOspeU-J0h108-2rAONl28tYoEuOSRR5_oW2gyz6yISX
BNdW8KPnEKheCu6ATfX-2NpVH1yEtN7sJy8qrY70A1xG08pG6gPJyhu1JxRQuDWRKUzuOxZgp63QsmqjMB_jjXMEJHkCbLiL8Cx5QxEwAdw3ENPDt2-9dsmR
1Vn4tEyLnnanecHhyLUckXGuR3pnZZl5sO0HpVQlVBP_-TND3QZht0WjuLPn0rWUPrdKXe-p3U5QN9vTNFL6OBsF9_XSl77FH0VKxoWSF9HYCWwRiGwjrGiC
tds4PP5hEme7tDriBkxSvGrisY44aCMe57qIHWt10gJ0kpZHpVMG2rGg2A3DnI5kcETZfm9c1lGwOmYfdPY4ayLVpLsrGckzWfRYZbu3Z0L6sNrh5zD0r91n
0aa7xV4NB-93nqQjNvl2gZXcmwdp0eWpyH7iMQZbLrQ3UDfWFZAAvqyEEHjhX2Q0VJkiuXXyuQiddD1F7MaWdk4ir4v3pSAWYaFh-sURlYqfukPrXeAupHkS
RQn3w-7I6vmOGqPnwYNFURwaG4NyfScEZ3C4Ae3okw6Jn70bSeumPnLgv-1Gn5ynnxb0EkNQaerAnhLGO08IEoofOywE1LYji9D8mW0K9Bnc3iurcdDW_hLm
6qCC82bOVQ0sUvk08y2W8lGr0XdNIPDaJyEyM5C2Agb68UK-DcMo8sJ4-SPmlmKEkeY39s-309qJW1llHFgvEc1kl1qkWBKqXF4U_1i
}

