sprite $DaprServiceInvocation [82x62/16z] {
xPVN0iCW24L9eNlm_r_RcKK6YgNDl8yUFIyEX1Ep1lDiJVEhQ1DSZ99x61LgDuA_4TeKlpI2Yn54nccio4-Cx6ratetoFAfyX2-5d47iOCnpoiSj0M1pnc_4
LqxzECiGRRuyfEFeVTEtyYHmb35qWir6HCkQ12EA_MrXKkfClfWKerAQSjv5KNtsMtW38dOZU1Xtd2TKcgADOWKd67VwNfDcD9-Um7c4_vrmERfrk8NCcb3Y
-9gX5pFAATcg4Etygy9gDFq0AhBC3eccq27Hw7xs08likTZRs2vifqLqI9Bld3iaPBy8dtiU
}

