sprite $DaprSidecar [110x128/16z] {
xTNPUgGw30HWp0wMLE__jYUMINqD4pEX0pxRr1MR-5i2tBYMfW6Q5DzyDBJeLRBerR38eQbWFThUGEjnZtrLy6XLy6XLy6XLyMXzswlG5-C5TInwRy-mWiU-
dlLeELR3OryLFFPLmQDrImAznotsLydYE2jPz9eALg4_MXKyMhKyvbcFLerSdc8ev15jj2Wv-XBH69xG9coQsYvuLXFTvr7jYDdtjBQYbYohfiqOWLXBMqmK
gAOXbTNKHF-RlQr_j3_QRnFFj6v8wNsxdSOfPLLA-qmvxTlQY9HrspQag1Gqv8nlQmEYHCnvszR8o1U97Wodcfts9YQV6hwLdsdwgOM-O_gJX1kq6r9VavfQ
-4zh-dThxJ3Dqz3zeeL-dESnlUEjnu_vriUXRfpyd8V7VQlhorgx86S90oArP6_fMdWIfm0CNLYHCsxUW9JuKQL-PK7h0Sc1B51gOOMA1rXIZVWzegMjAK8y
2cqtpSSI5fX4Qgh9QvWE8feY8WPLQYkYdt1FXLhUDDdAujP87ikoG99Qq0AyLr70MMeJOjv3leAQvHtvB12iMKixviU4cgc-QXDo1PPvXGcr5fb0d6T0ZfeN
BDYAXwpnrw6W1MpjX3HKDMhZzbFxTD44sMk2DMstAyHtg0bY7qBe0s__gdNvyiLtlA5Ds-xJDPuPijDC0jUAxSImmPlpfJRmffohQu5TUjgzvhFpzApddVQQ
KDi69gRXivWQL7bJ6jJGxdz6xnhlL4d3sXIqyqdg-IJxBoSfM4urlYNSsuo5F_h2M_AxteAzVW5cx6Z87_U5B-2yDpuu7mtctTVjrpct5h_kwUNhBcZjGGjc
Ob-jNCFholMhnfNBScld6jD1kVW2GgsPD-uZYgC6FvwFelsEHWwIWuNlPCe44mymobx3h2nInxwf-KkGCpK35E1xtqVaT040Z9gy_9jE_3Sr6DQonhJzE4r3
-m6t8OKdkc6QnkvZFwGaB8Xh_NQkvxKiBMlN4rIpLiZDcbNKk81Mq5YFyIRjZpRLqRhhclvOc-je_T-XBHScyQ_H1g_7MbFJM4qJ5LJIcXuGJA6IrhGB_s-U
r9ZGNDNgPCmQy3mL1acOzmOquMdB7FFUUY3sprgEkOQ8nUZTR-bcKOD4qBkvhwXRg8cg2BrRBT639l0j4SFQFpL3Qe2gk1T1xmOhwY7Yca4zzEwU8OFCWPxG
UzjIg9GiZzpYyNbfmI8dsC-pUxElyWnbvntdsTqvGwF5nBstT1UjyWmZc1ttXaShVhSlUdR9esKdCpIKOtBYNN_dcHlwumprz3qyZ-3etJl3OyoEtaLhb-lp
dEdH6kto3CiHd7bXmDaxVps6KdzkbMTeU2yHNtbXH77Ti8WVH8xzjMwLrzwVnOxzdSnG33_FtYlE47T5w34tpx3y_HsJJz-R2A0mmntru3mvmmfUuJryvla1
8FLqVzVNmxy
}

