sprite $DaprKubernetes [403x64/16z] {
xPpXcgCg341928I0wlk_xLsfSI6jjNRkzDlTyVoQ0WfoX0YsC_yBNEGy_qbSo8tvp-0YIoNz8L8kfE7Fa789IN-Kb4k8AlbcAnVkPI792555UVv_kNouGu1I
BoJtKYAw_ukB-IKbFlG394PkHqgA7jpdk9GWSPQEX43IaINWPwnSIW13ocA8plaaLifBGmNW2-O0tAK4Wpo0mNcvvq0A0Fh0ERvf0oaceH-lXEGni9FpBCxx
CbV4lK4OvuKn_7GbcFULx6GnxEgTArDoRy1pPVZfIY38OnBiZfz4twdaKiBo26Po3YYcXqhYZr827rQ2oImCJGIl3sCMXf-X17nWoIL-LedFgmRYdUWDf5A2
badu8vIGb66Svfa_guIoHWxaB9BPFuetIw7iGGKc_mEKw2FWfvL0b1le7CPIrY62Fk0oFcXThdifUT4GLYNX6vHSIameOO950TJ4m6anW2mSF5GdX4lwLlhx
b5nAxbU0K2F6eWHYbfpQT2N1Tocvb50M9TUWNJqieFwPryX1xKEP_suby7pRvaasFCg56-x4KKR9sNR0mbab6hYLKliPMPLeM5zNXh4fciABIj2lmEyFQ3BH
A8deASGOgEPOm5FWNmJoOBFGBqSowy5T8YUEmIEuUz3N0j7Kg4f4hmBxoamxshnQOpsZntDAa6KZntfgZHYWIdJYejGeuTUKK9w6XR70xpxFVcsuViPEoPXb
NX62Eo4yQkuGVTz5KMgUPkEIIb66kQ543_VRhhEjKPNq23W5Oz7KaSqfVMog71B1AIMfKU9rfUhvfiI58ki9GH_EJ31vhiGNRHSjvqXhhwYIf8eQ9GOpGsBi
imCu9Gop0PVK-Oufc0xCfaQZn5YkW3ale-c4bendb7Yp9CU8wq1Xg0CZ-biBWjqozYyeGPcxy617IRAZnA8o5HIRpQ1vCblWeH8R6y9zZRjA2hOjjpdMYAtE
AZaC9PcMpuNzpHNMV0zQ3FjPJkX0YJ7ojfAva36ouoHD9YVlAXc3CM9hF5023rewQ3lyR8cdb4JPo7WBxSdVbyfLc0kDadYe19BsG7JlAj49tDwRqpGhOKy9
cnwtjYhKd78oDUug2O_QaRIpx1d7S4O9SXyT_AEjT-2yBWx919FdIfAsZDr99UDGSXacUvV5SJtX82bjGJkXAjaEBcKOnfdQtXjBphcCvYPncBRyn5Bq5AnA
jCAnCjrQYbixSzEE6VlmMIIb9BdCsPzGOaE9hb9kMj53-mG0vbqy7YX9PYfzNKckcpbUr8c0JbljyPHrcFHA6040VRof2gq3P7KYPjeQ6Te9AKEdHEX6yDsq
DTAj3xlhzEP904E0CqeeTu_06bfuVUQDKBLl2h1LGi-LR5VFS5992QvND8JkaKgmVrBYNWavnIXf5HJG5dJ3maMD9a-MYjWF2uTblMXeb4pfZTMxZUvn3Hh2
XEkhhKorafWaIxRnFJvL4WTZv8GIwgEvpdp9ncPMHQyhyRaB2bHCRF6bKMIKsF0JRGAQKN9UYUrYS11JyF0xWcmB22GsIammiQqRp1XvIucBRUI4t1XeExJG
wqgq2OEtkNs-x2lH8ZDiAMi2TR4aHpYjf8yDPUayW3QpEodSaWw22Uqk6quhQUVozbeBXvKqwBpsiXArF51RuoHX9QxUyxuIp3fAmWglDSVEs3mA4vnLGZff
PH56cmi8DYL8_eKkze-LCBgtbTXvHKF9D0vZHKVY64ye2Qga3zJRAIUjSL_9P0vgPWJR1IK5EAK4WbGI8G8qUqNKs4KYZrrcb1lXM4dnNrBYSrDWYqwMwGqb
8sa37bFsbVXvZmJDmaIz9O8JIZ0sVGjOwwCGEJMJ4iGYYMCWq76phIyPZYUkxB-aH5ebu_-k1Bz1IUD4guOJIdXL0e0KkQxFIyvTw8PGwioMSVaxHK90Vbt9
BFvUIJazIg0R9PO_Q9HKWAHl7xoiH6_t5AFad6yhZxmzuAxlE7wF9B-KMWhVY4-KbB8vmNibz6eiqPL86qi6wSc9lgfaAhcd97SSIxAXX6QsJysO7i9xuNrT
XL3MBw1WAhIzP6Ie1hLmnJzRb_XixXtpsl3yGx36Ul7eEn3ULQ8rZkmD-4I9tcta3TtJ9KMPbNHcgIWj2LS3jVrnVVFhy-g8ahI4vwjtN-xtfgFsm3jBHJJh
4iDRIgB9DOJHTcaxstdt70moQV0yKc83l983t9pGkcQv3PEKgn5WQOb7suwaJiPWxtfvJKcSsWGGg_ZhIiBOHJUBtS8ncpBe3a3HQU6z5xqwTK5ag8D4T7Im
TvgmmSTl5SDW7uLfr2OUxt4rJWMQRBiZ05zHWgfvzF3W1qi-coqmwE9xHjiEBQJ4aqhi0bxZ0rGFpRYfDT_DSOTANBIl9xneIlA86F939KE4Ns1g7d9LaS8U
5f1u4lo24XVRb-xWwZbbPllAR684GCy9TMT7BsCzA8ZEOy2PuArHOaEytT_bnf4nyl8NK37DpKVj0SlnAwoQRVCdCmJVKg8HJvVZDdR4sO3DHPg3GdF6eMH9
QLDNw4k_BmatnPxYBy8g769l9BpsOmOQpEji6iuh6KEtShHCzBuI_MmHS6PWAa-MCxo_R4bmIea3FlpP6oRxyv939UQ2ozgeU5w9LhPdD7n92SGd3TBssigW
F3gexG5xKvrJuY0TJKgKUsdmgXBWRJ9k4YpPFr4Ix4yXBV4hIgmJEz5WUhYp3Vb1nyFUwVYDN_HA2wFp70Xh_FGK8zuNs8NCYrG_p2iQ_SAfKMAVJf5tlwAI
ZCD-d5ebMahRs1FtAiouVncW3WqHpYjnNXge3fl4p94vfRfmZAqHxuwLS9DWhX93xhUlFMmvClOTGE0io5DNP9jdOzqhdqmefLmHJQLo-znSXDsJcb9RBJGH
R6Yk7OAEs3xB6oV9l_VV8QYRbIZRcGnI--aPWERxqA0qPS3JWaVKz2q7r-_lzb_VDMLeA_6W8blySNji8Hzu8PB71vaK0jtb058zQ9rIclO5Jh9uPxs6DvH0
R6SbbfxGZYDotmvKZajyibRBlbzxUvnMeeIqAV7IODBIcqOktbUI8h5O8aKpRNsTIucR3n0bouPDIoBpvxZ-PPqyGusK-NDSo2lCd-JYRpDoEVby8BcOvZzm
Z5paN1wJy_nlSt7n7m
}

