sprite $DaprCloud [230x128/16z] {
vDh7ckew50NXpQfjFEjw_wUzcS-Tayz5BPr_f245E2ZuQ-nSrEQvLksBAzYZye-4c_mxvgB5_8reZi1d0Z1_PnGWl2c0riLfzIuGFgOfvnI5y3dQJcXl8NoQ
nkcWV4N0QpcNk16-oDgTIUJhaK4tvx79TmGjPn5X-Kpaku9Lpk1YSoQpVQQQxakLkZVDlyEnTYMdCZSzL2xUj4VtWqCXuHJxg2drmdEgrow7YOIJB5KRzPYe
FHrjMltW62rd1L4lhG39srCsKwCgmscoenzFsLgPDfBUtcyyGhKtxwmCd1UEnazqPhPRpo5ycbtUKTdtRmneJt1LdXGKxwPaYD36EsaP960ckFUSPxo7KaOI
xw1bB7kHE-puTOPDma31wu1NWXNlG2N3jUN_2najs0i_BG_oMrJwS8TLhS62-8jLTIVTtGajOJpTk7RINULfEvHF4ORBrKDWz_iAL7cY-GcwuKOLoczfZiBS
y5Cy_K2jqjzh123yU07Wwvr19qWy981IVjf350XJ2Q2f4-TtvkciFd5-PvfEtVnO7uspTbxxn26bUJAhVC-cJ2ze-xPMidJc4RbsvZv1vEcLljebB2BODMX-
F7wYlKbOI30-rx8SyQbIbgCrO6bkzANPiYGlpoh3SeBj0LcKw4t9ejozQLcMrsMloaDR_ckJTVtPhdsWnXA3GH1UGAD9tN_T_xGlMkpWR9DMZUi67ptQg8qU
FEMeGm6m9c_PECORINBxvL-it5PE5AzS41N_n3PRU21ZEn34ApTaD8vbQYiof2ixigbmvO9i7A-q3Sd4eNIIyaUPVovjnolbV6N_KSQqFIcpsr6-iftb_3VC
Xft_XjcHyxVSBihuO-bnEIIo1NaeynzOtrXYaKr-QboTIAmpcAoqr2tFybFZlxteAGqtmjz6R23rPAxegYn8dDBtSc_yxCYZs8ju_OeK03VIc0k-btgrgPrS
aSLWnXvAOqQDdlOfVKHnQGj5cdi5MoBIN2jkx75dqiPS4oT7cztOZcV8vmcL-zp8RkHh52-IsTh4Gsxu6T8yJvI5-hH3diWVBecnLUpBZCPbfvuZNq_O5iCv
bn7vMRoPRGcEtkOXjdw0NoBVPre2xxtDGTmDah-21FzB1iwjBwsr1-MrjlJjOCpu9UHWMZ90wJoE_T4wZkDK0LZorv5Ls2D9Tl6GLLb3-5KaO3nv83xCu9dZ
qyriD9-h3F530WKa3pbIGR9n940J4J7VgWmm1x74M_q6
}

