sprite $DaprRedis [224x224/16z] {
xC610000080WXFrj5wa20000082viO_io64O2A08914Kxd_SwKHhCnaI2VaxUrUlr03iNtAfXQbZBbMMRn5iROKGVW6fo7hVR588_W8LlLysAmZ_08lVA9mo
_0U-HutEyDyuUujxGGZ1kkTDjp2SW9Dk3YCu2Ld2cO8Ga3sX8voCFD6HGd01tfB4At2Halk55uSsVU4HN8edbmS1-Ija24Z_AbmGXi1rIZo1OJJRLhZ_Cqem
58rDjo4CXYEl6OVnS1aMps0ApxtKuoptNeZJxEtbRz1WAiyzEUEkdQ8hJ7Vb7jmHfiFSHraSvVnpB_-ntI09oJqwuzPqioN_Z658X7DTdValqGsIsLDllZZA
ytJcVq9to0Tppywuacwp4pDJmYrFfuIhQazIATc8KGZ38dPeZ9d-Mu7nS6fcxcuFhy_QECs8QQSybwvL_C54tHvK2aAKpguFMUp36QXf8nItDwsKe429LVVX
xlBvfRjzYPQey-f3RlR5JIf_yedrXF5nYhE69pMrWsiXX0whze3X4dt2xklRm3jxq8U605nR4tDxE7hKnfDsuFh_0zFDL4HKZwGLo7fWTr_MnQCbRcClpxx8
tRKo8JmWbKzXRbJThATRbcth2Nk9ew_G7zISuPRhA0Z71KKmdNt_rzrcR88RQYQc8sVd_sNQnjoJtqK1enY657NK4OH6o1MmWbQubU_hIVX4t1WpE7iO7iFJ
S72y4SkUl5Iu5z_NrpzFnDs6DonO_BnBBYTyUaq1dspVzjklf74-z9lNvjqEfdzASqbDMCUV_dY7Btp0Hs58_6XCmOGL4J3cecvbMTI8bKwHR_6nM_3ZnrFB
ZbBa5HzMfgMYSIOgoyxQqYcVMmSDutmjOHlWHJ8b1Et5ZIgSydbrq7o7hn8U4h2ewLaiUarDftoE7HHly2cY4hGJ8R2UHbNGzMLz61GzMhMZIzEll1mxfahG
THBn2AEYvN50L48XrDwffcl4uBiaJs5OQNbq2PUI4KM_svOSx_5bfwaHvFVFlKa_zLgXvsePX47HPgakujA5gqgt-C1fqI6VcMVNMHTEuPQSNYpnOpadFAVJ
-ESoXqZZV8VdDIYMkZIjx_EHpviNFbZ4u1ZUXaxvd1mCtE6pPkd9m2cVZuC9j_Yio_oHJdMxDjbdpJOR0eDmQjyb1p--4eQ5vOVnTJu-b-Ivr9d3k83xaNqn
TCQe71tN8T8Dl2pzlhXKdSP7mPjyvBAdW7fnhnpK_Kz8VdiDCDpEppg4VTDzcf-5wCB7-gWTn5Ew3pmCEeHtpSzwXAjEmk0Vu3FFRDIb-uWFlFW628sb_mpV
MJSzRn3z-CBd-LaNSUdWv_2_viDonKPAVW2NCUlvzyy0P0aLyHnQKWZEVFS8btvNxDEnqldoZGkv4-Iw6KmX3C6VxxQGoa1-9Wb2yEV3y860nFYK2SDk5thn
gI8lF-Pd2-E4UW-lFTSnbyUPIev1vSsNmkU2r1fnODWvp6yf_8gGtX4k71qgvZpgm3Kasc47k9aGSK9PjL_5KPI6iEGNJ98YrOnPjsRvBR24tnHklaOt_g2K
KWHMqF8KUVD1-5K1iGWdKAEMLRYzjs67yEvHCZQ33-_mHHy-xP_EfKZPZGzoAGpU1TLVJdohC89_CQSNd-_iGOL_XG-ddd06i7-0zbS4UDyU4Ovy0CSMCC17
Cu-o8P5SK-bQuR0AKfPLzWHp9Fw-GDZoaGYrrMQhSfn-9ipbNfR2Lcb4hyHhqqgiGYwxCkryKUD3Uo_7oHj0yUgQ6FF-JDNRDn8q--jL9hvJQKKmTGClNULJ
vG0Rgm5CfPppsIPvmlOwrTSmNuODJp9bQG4jdkM3eu45fXvb02DyGWctx_BTio19sKq3iZTB9E_vqjOYfgnyyofOqdK-IQ1r78mwjrsLj251TPAMR_iWgBw8
PaG7rUCodyJcgy3XEk_cIutVjNnSFxoKSffTGGQN-DI7L8fa6c0WnQjAFViLGhS2Axh8HwrL14pbKGnyl09ou5EZ2kTqcJ7FFLX3exH-arRLeY36tMVB1pnU
jJglF5M96FIPtuh0Rcz9bY-W59KGJ2zGbMjyuIS-rFA-q_SJaKiZXka5nl0RV09glnC-Ur85JoyGf-jywctYGH10p3iMidnLcBJCDKq_wcs8BtOVYerdPSFt
xZILIUPJfH4-w3sKZN-nlEC3VVIQpC2at4LrdKyZj9tUesYQetEb0rzYoVYVm2auAJYeqWWV7YPkc4LIGov9yGmVYhQuP3-QUtYMyjbyb60VHO9jQ6D2h3xI
y4Lj4QaspzFCfw8HFft2CMyVexPKzVbQnGcfcH4Cy6dFCr4w_yHdMx3B2MWymgSlaSoX2sdq_KG6dnFiC7JqTcq4g36Xf8vjERrR_yFSvfzZcUUSUMuMqJHH
2KLAqVK-9UJNXTYitq8MJJNn-ruH8HYOrqwC4J52C0ACdSFg8CRj3eoe_yRXNlotlRimiXW6OW3g_QQm-k_sXlUOOz3eTI3JKAAryBcC_sHXC7PxxJnN4NtY
B8zqndew_GtbBi0k8N0Nc4VEo-TijEfaoX9ikt2NZVDjSJLqj-9EXVFfT3bqLN2t53hA07F0X1OIv-wvp7dtNE6CvohdR3otTPXEIJnXr2uq5pkD0-9xPIhw
sAp3rMCxemazBSOv_jr5pirpctMuUGGFgLKC8t4UJNV6VqvtOJ1Nv4pdhcJX7rZ6iEgV4puM3EtuooPQEZ6-DTglmiKDizX-6j7IZidKxsQqM36fDNt-dOSz
yeRPNMj9yV7gvywOodhXVI8Y8Y8Y8Y8Y8Y8YJm
}

