sprite $DaprEncryption [522x600/16z] {
xDq9agiw38LXOntR6G3jVxLlIbUfxYDtoAIsvVEluQiqRZYWgcnFMLK0g6hRTT8O4bG5496RXQGJnb9MLG0Y0BuivEaii5Jrw_S0jxx-HjIfBB2qsE_1BRDG
fh704kuuC0ixe1F4aYJxk_2_v6OXPuqUW-JZxy7H0g2XOy3HmNqBKZHiJEIt3c17ob8rP4oANH_yAZj686d8w03cuCyie6YicE0X1tQvK4HZHGTY3XwpW60M
U5w0uD4aqDy8ja0rcuCdB8WgieuTor3LfntOaJ9Zrt5ZxMK7TemGqK5Za6GEvhN09AlQUU4j5Wfqj9XKS_162v9qf1YoENYp1UWmiTBCmRmMM8Kv-8G5rRrg
xp4qDGUVI6I0SGHBwU3WOnPIqavZsHnyjgw7CgnwEG1i7D6qinYoXuFUnn6ir8C3Dmk0TX833WuyBUIYFSGWTh_HBuuZwE1eGUOTHz31yKWfLRyhLZfm0Bjq
bARV4GFwS60MbgBkiIesV7Ueqt44oqWE3df_89ubL0S7lHyf6G071zsF8rYHNXtOaR81wXLVWD1hxbjA3j-xji1Z11sO1Ldq0p78uVz8_LjeEdLqO1QAlZEM
uU2W-t44Q-CvC0jDjUeROaZ9mq7_umZk5nmSz3wEOArvEEXz7C5o3k30BBYD8_X-fFwF4ReadIywUFtrlonBD0Tc8KCVZGu43lNwL1FB9Po3upW2-fjOanJL
WLdGtrbWgLG71nn7yFd4Jd9wy9NF9_QVUBxobSyZ-VVwboDO2U30OHp13_F4jf1rvkZ0ZfG9IPLXNWVy01qT72q8TEQoc8E9c_xRnUr71xHGcivOeWC0_A8C
oj41BSXqumWizp_eIWlBJEE8FMKw0CSHIA03S1oHilBw01n7f4e70CSHQQ631ySH8IqaW0x0SGIaFNETI0iD6gbTAdyFddwr8tY_4G0jb3WMH5xwkq0BBSOj
QodlSC0Z9VBSzvcOxMe5Op-VMEPsmDV_seu5WfdZKAP0TPdU0SSHW6gYWu_ixIjVZ0E05hBkI3f62UbZ3cXXd3yHaFn11soOIqS17G0SoWZSFlXE2oLhhvLA
1m374Kkc0u1VZiZmTq0Bqjiu0atf01n7f4G70CSHkGC7jD0Q7ToYXVoj5f13EAYjS1pnIWj2E2XdrUrKE8vuDjmS8823TTrqRH4iDDdLEKW01u9oslzri0Mm
8Az_r9mE_crTTxqsHB00VJ0ws7Jx3u9Pk3J8-1PaKO-MA0vMtSs1MQZ3Mr1LoRnE_4C7xUZWPa7DmjYNZl1vFd5i2ALTpS7Hmdx-jGM-vhD9Y-00vk1kw_PB
2_noHC8Imy757DnlZMEXSFZ-SmUxEPZ0We0VQ3ecg9TzttxZm8uHsxa4i8343_FSTs0G_i32QN0Bx_sl8sGw1sPXFHK9DOwWWxCvUC325iK2tdLzWB4hvk1n
2_jwWam-ZgY176pcu8dVXHR00f8-MKOC1wT_7RoONaDOq6TADO83AQTTjtLxjJM2XVB4E08fXN20qsOENclTzLh7jl3uE28bZR5tRgivU8k5Ivrf7D4Q7Tnl
DGiJZ2DoZkBWQWxUQk5SPnX7P0HnKEt6yxijg9vBb754V0Tsu_aZ5lPJYJoEoFBbGEPmG0j94DU1eDwMB9zjtGPVJSdDmYA7yqAXWmUofOoCRa5AlESJ8IZd
tS617IE2MKW5GHoSTjsS8DXggeZ464V078HPD3bRW8p_jO2avY3CeidTmYM0XLn2E11d1yVLL1lzSY640riqkMTBcKiTsu8v2BHiys-DO65q1_1n47yf8yCx
i2NBh1QOeDcYgHiBXHPwNBBuMzYtSy7KqO5PS5_AqC7MOUj62yvBbdwZ1Jgm7mQNrHGTsEN1f1QOlKhput4rHGTljL3n_bZRl1p4NyfmqKGB8HPD7X2wNaqn
k-4uf0Njtu9moU9ZuULRKvGW0piuhgQ44bvne8CxiDLKnnQ4YoRBOpNLhGNfsu7ReechAUdQWT-YYQifuQBfcopqAO6B9YxeX8icgwy57IK4Ts2hgRuiI8SE
hh4Ts9ElNQsc15ooq899e0DQaBuSg3cOniAF2pfA4DJ97DWwOZyNIlZXXkCsPsQ14ip1l1PEHIZXNmVhDcrsorhcbb3EN_y_e8NMgmGkclnNKzyiWKiMMf2U
7B3rjg2RJ48vRNHm_vPrdKb2wMlHnDMKVAS3GlZvKiRzTeHmqTJnQaf2In0w-EFLL8KuI-2IXQifwTO1MsqrvIQ1YoPQ4FSboyOUNKsvM90n5asq83Au17FG
zwA9gobn-dRVrld1aQifSLaqqS7Vx9q9ZiGs30G1YA8bgyd-_sjptucFtT5aMe3h2rEmM3Qr-og82nVqJIYr8QTuyBYGxtIX_1yUw0V3uyAxZvu6plFWuU2c
ZBe9nRPrF7XSA6--qIGF_a78yoONoZizWBm4aVm74G2MkIcZRuBhUn11CiVUskQ_iRMsupSTn1q-S47DXBhBUv0a-kRLoZ-mwjiEClNVDJLv4uehpub093cQ
Mpd4l0qo0mXPaBk-2NKaT3qWHwjMBh3QG0gx0BO5veITqFLWToktCD-5NG2t1KpecYOWoExb2tWd0w8c-08cD49rNxXy4TbrEsJLDw5iWYCZaiFBrp4VYey5
16m14pmIWel2Lhw5DHBGImT14_JZ0S6zbc_ZGqu5iEkPe1yFI3OhBs2DQcvpapD1Fnx0yF8Y6yNafgkPe1yFuAZbPIe8hNGGCq4_7i3ToWJg89JIOGqJF1D2
erMPWks4M3hecr2H41PXVHN0liZEqaW8Yx2-2c1Rn8HEoCm84x51IAM3lWcDK15XAeR4Oy8Nu-7pWAXbCfKQwH1LnWJzjIK4lKp72OLq6APYWduy0DpA6sY4
JZhepma2tw30NkvWrNtx2VTggqoDO5l51DiJ2mm9vcqF_a7ipQzjg0ecRCkOqFdn8M6xrA07cH7uZGYIk5vttGYLTD0teMmfVZRODlwzhmeWoE6c_O89aLN3
1FruG6OjPpWOmF7Vq9O-7v33HD1VO6Ch9zH-jhuE9Bi9zmFOJGBzZ4J2oZ5-jPY8Y-MMIa0a7VJP4wAF16i4Nfmu6o6I3lhqZCznzaYmJY0k0Svs7oi34kcW
Jscf-KYmdMF25-r62AI30E8PcVNaYJ1UA569IG4vD4pGpyYJNx1pV6aoEp4Ad_pOVeid7kZbW8qZxWFGZ_i3Jph8Bx0Dc_HCHqGzsLdHJeSd7ewVwJOIqxQU
6g6T3ayyW7NQZmTmKpiU4Ed5Rl340spUvm8GLUnuGA8kPOAdsbV8JamyQwmJJphSeDJFdQ8plo22mxJM5C1kQp5IO4nuVSGxd1ISm1EHTzXJQammJBuqOI2U
YBn3om-TedDdVGJhyUhIamxNb8rIRnCw4J7rU6Y4RZeyyG3wqLkb5oOqeP4H7BOMfKgPK3bzNzw99ntkKA6K3axClbNd3EYcmnCFQSU7-jn1eKRYIOSxz1IA
oCxfGsW5eP0E-lyQhl4pLm7AVx6_OaBNkI69ZBgS2IvWma4wJ8c77zcxipJPLHm8mBTR8S2saFQ_sXxFF53tP5RQOPLY0VdqVq00YI-ISDnFWdf9kClvaoGg
3-ijHjZxFzA3FInBTP3xdK6LX7v32PjRINZ1aq6tao0ZBf2mvPRWyuuIEf64cKN2eJUKq9n6WdeI2R7ZXki49JYKJYTXkwC474uZ8R9861GI-1zHiEZdIJZ2
hdX8x8uIHh18Q5aaUAEGm5yUB5fg2MvwImcDHa9F8Y5st7ATe3vBmWdLWLy2x7m9-W896u-4SO84_l9G4XRLWLp25YGIHWe9DhtTKu9q5WbR3WbkoY61lpoO
upm95iPn_iGl0UfszWUI22NmLmS8afK7c_R0rUO79UW54iPj9Unk3190886vEa10K1wOhpQlxpnO64jru9SmmWYkCMQHu5DV9a7Jb8Ur1FCNt7amDvBgm2y1
UhQ4ZL42_wjhylepA99hZ7FQ-qkORabA9EJUppVRpudnMmaFvA4VVUrtAmWay9K7c_5JVdkDyO4y-ADchwiE_NKI-dtBWtbie_-GqUHNmUWFv94V7KTCu_pN
orf2uCNfBnmJcX068ym8pf_e9BIm4sudKMMBLqdOWVjAK7zPjnRIQ4mZgmwFI-0l3nQR4EJKlSSOjvQmbGIowh2Mm5yUIe9xkxM4NXBOgiDQ0dzvA0a7S884
_Wji9M6xjmIOMqaueJhmIzXBmll4kznRmeYIG71rZK12BmbSLzVM4lZBGqau52T8u2yF9M77tINOj9BmV7mZaC1G7ah2408911VOIaAxlOHU4jwbHEe94lZB
GqbmKznTWfQ4TuZlkB-4EQqaq5I7jGJ-2smbOGY118BoK19w0WcZ912KI0O9lIGy7rFSNq8h2K_73n1882WF9M4ZaC1G7ah2a1Cay9U7aX0zXOHH4WYg0uE4
NXAUZYA3X5OI2Ae3WGHHVx8yb8GzXGJei-MX98mS4h17INZsuuSv98oIy5oY9P7GIy9pSKqYeJ5BG6kzzwOWbc00cuJ7omEd1FGzFcLk3QGIV4yZmPnI0aP4
sAVC26kK4iot91A0FHWbj1bczlKtRSQkZ19YI1O96wE4yTF3YNQ4AwE4baR289JmosTrRKRZa-2QHa8daR26y8c2ydK7HH89qdmQbuJskpTrpGra4ln06Wbg
JYHX_IdW8mQN1FCjZGHW3ou9guMBXN99Y25v96nS4jIM4ZOo2JsHXC4bORs2DGUNX9P8GgUIW6qj8HfNTr0mIdYyF119EDwGC9Wa-8544jISI8AkNPhlH1BC
zrGI3YO9BTOIfe58Gen44e0jg2JON8TAGfTC4WQP19khE9M4baf2lvK4OvBWYWGI5kM1U9tW1v64QKWbGQVpI50BE-772Qe3euI3I0BsDoHq8WanKaa0zk2H
8ECD2SeaeIUJi159M7_nr-80auIMJC9Wah1qQT64I89hBWdIOng9X7Lxi3Z08y6c8Pc4vauYORrIC8icH19ypoP1ZKe2Zh15SU2H45io2S0UJ194xPUttD_d
XszM7O1J9MnS4aGjVdN7VGEPX9PEmY2J8Bh_IC4yXWYP14qWOL4U62G8-eyGZYPS4cpEV1AQiqaGENonMAIGu0VIIL1pDWdOWrr2R0ab77mI3gUNCD990BQW
ax3pI-W99OoIG5iY4JYtF9I4F_zWQ489pQUL1CxgW01rUIW9iQMKS9G4rkg00AZFe4f29v30K2DBGiieGKPKTo2e3WGIkayh2ITK1te9RNf9-9DOx0GI66fa
IHWf9G1xII2j3WWGbuSwbRPeEIN82BhkO5z39y7CDQc4xjEe91mn_Mle9BWHI23uzqkD2RuZgGGrBWa2nRTHS4c8BQa4u22Gi0oPX9vMmbOI2Ae3WuG_AWyb
mTDAaEubuM_7fcbQ2SsdbGI2wh2GmFS2Mqc8BQq4w54I2C-V118uERlFaa1N8WKuNS9M4WXA9844wIM1uDI1GO9EBma42yQ51BxfeIIqKoMGJWybmVnGIIm1
QYM1e4Ck971D3oN1B9gabY2j911C3WGIWCDBmWcJ0xy46M4buQsOJnKWyMup0AqnWM0pOJ4c45rSAWaseqbw2TAY9BmHYqC9912i6Kl20F9Ba1vM4bOnDvLJ
9MZWYcYj60dMYmop0vP5iYIOUvEF8K6z910D2H3yzLK2pT_dIu9DRtAoXBXAGdjUmauhORgnt6xdbu3TdwQWmfd-_93GXKa2_w00OKnxVaWu02O9_2k5lIbV
-dIg8O5VGdk78iaNZvX6-WRZMeBZleF2D9jyCPjFnhjS804W7nJMCRxmFikwbl0No0Q5YdVvQ1BKxISA5T-1AoHqV0h9wKF5crmYuP-uC3hd3nGglW4VJm9-
seshkCer4XgkZ1vU51PNbJ9BM0yA5TEh9E1J69fanQBBLHB-WKiZwhCeB4wZpvEWE3dL9DS7xVYeiuFeSGA5MYxoIu2qJuTt1S4Dg_3l9zIYaUovRlunOVtD
XuAmuKe9Ga2XnxI2uARi4lZdXveR-5ia__nGlM6zJk1wwpz_p0y5FlpiKFjBPj5G4bPV2kCFvwFj_Ek4zVb35SYI0EbX7xb02dBE3bKb7t-CjIJWSAi2MRC3
8EgrI2W9gyVvykyaI4ceNGNpsQJ6X5ersemk-F0IQjLelrajbWHHc_RHLeibeVOQBNQKX2eG_wyD9Q7-5hNubaU2-mdL9RbUvEMNK1HiBY3abL3R2kkdzah2
caBjA9K4x645uLm9maoX89G4mHvc1Q4aVA9G44e215kO5OIi4eg2JUz0IVYpZ32hdKMW9634jBgY19G4z5mKB4m59U6HT7TBu-29ZqMN1BGPbWR2lzav3pJh
JI088gOHBupe-v_MWO_zSrZMmazjJvsXlb9gT5yWWjhRvlWvMzyi6iA43sDbF4tglqO042OiU9gKUsX0c73IVMFSAuO9qBvPy0LhTa4JujMpDrQ42V6IoUax
hc-2GORTwOhF36U_HGWJ37UzB7Xh5GjGCo6U8VWefc42fB3ouE5AGLZpMZ5CWFKikCeTmdCtB43fN6HamHS78Ko0uTRQuGf1010chCJs9vj74C84z2ouHn1E
X0MQx4yUVjqWt8j12ne0rIpG_R91CFo_JOWik3Vs8AX1CwXYvNft2-xq2eCUDEYwO9VBWcWGXWc0cN0Ms3o2S08iP7T1EGlk4OGJlaLQEiE5o88x3zaWM6z2
BfHsmVg4nQymI86i1qZycsp31Tail7h2uivMOR8Ua0J_4owyE0lkV1H8Uv3uHeQs2pqBiL3xc0VRni_ekr0RtIC8ynvay5jobdQXJrWY29CUrCmVKUkK2p5u
xSVSX3r8bJyZfVUx4CisRxp1T3r8_1L8wJqkH1Pw47RP7gG4_fQQLLteMOWW_Dw3NFa-yZPS45ssnKBjbnwKpFUpGTQ5ykJXSQZbvnvid0C_So5sy7xGTz4U
MEOyPgekV3jXYScg3GyAFuRbuKBiu1S4GSM3JhCoN8WiB0Y2YWUTXD65oC88GeK9UW0q_bEgwhrZpyA23RkW1niIps07XmlwEtZzoUgy1ncLPx61J0jSKDh1
zo08Uf2GUIO0MG2OuE3L5mH1nGFQphE1ZUchwWvUFmZp7W1SWHbfSYwKEvilsB0hz63ZAWeckY2wWzVViBzvKFWruG9w5axSi8S77OFWDQ8UTFze41ubUl13
O7cY2-8x-3vPDJ4FKFWlaP3qNAYDBhvXdp-_i9wqKSw5SgVxz49D_Vp2Uj9EkVk5sffFRjZLFCXy0QdAkL0UT9yDWlxvXVKWOS85hIpq3RlQ-OKNqb2rFbDQ
pyB4Xbte_C9ovgUl-Zju-YvsVk4If0aN57RmtdY7wNYmPLw6LDvSq5-s-T5yL-h1nakHbRvPZy6hz6HrU63WvTWmN53EGW-2_5xvClUEfZDuFJy8uK77tboG
pCBOi8S72rnGoi88WinUkV7gM1akQEtWHn0qF2X8LA3OS45c1pyEjOXuiADI1OEC2-NUceyDkypv1I4IL5peMUX14DcjPufHTLmezyi7uS_spkj0SXY6OWgK
-MVsN-t5kNSvM-lb4AW16-T1b0SM2HapShWmRTNk5_PZAqbQEzahxwQdS04FS04FS85-uGvwnuKD_K9AR4J4F_mPWGU7nPCn71Ssz0ifyOOB6_g5b3HSsD0l
vCHmuK_xXJEUdM6uiA5VI4btNDZGBwHa3LpOq2-aPEB2XduX9UTqNDYmLyv8iuOBUF01dn5DBk11PGuznL7SWsLd5AVBXS8UcBK8iAekg5-urGFo2Fe5Cclw
1N9A-WLoobJz0YmhuSBlFO2cP-BPhUD2amkrFG1NJbczNm0tkL2yNm1NAbEzNm0VSg5ulm0w7r6yNm3b4JRBzmjWpUL2xNu1T3A0VW5SBXJl5q0d0-WNe6zq
WNw1pwptxrHNN0zO5XVmW5qJ_OBWPyJazmEsh_GBF1D_ZmVWsZMzHW_SF5uA69-sBENx1UXoeNg_02ONglSBO5CkbEuNG6TbvcItZWjBpx8Kzm2iHxXSkCM3
yJey01joeNQ_06Tt_OoetI-07NeQl7Y_0EOc5sht2s0w7q6_W0p-S85-0Ow72_GBO7B1w1VuF6B8XShz0ZHDNo_l5qQaWuHkNUX2tjqw79exNhPFJEe1TBaW
w5YOn1Vl5s1EdGpuhzrw0H4u6K2_G49Nhb-0AHUAzmjmwfdul_JWY2S3sZg-TO7TEZab7Z29bmlirabbVfbDuG4kq2-GtDClu0Bz0YuCkL2yNm3NoG3wXGUS
ZoZVBu0zJWPOq2-y1G
}

