sprite $dapr [206x206/16z] {
xTXNigGm34PXJwG6wo_jVxMJ0ybzBKfCkwdplIB0vqQtVGC00000000000000000KAgjwG4VNRKxrHWr_nCrr5133JNKK4CDDTHGGmqrr5133JNKK4ED5in_
AsMs0mfwRet-rbJBgD4ODP_iJZMML5E7g9c7_TxmUrEcb9ewI4qfN-gUOjm7gJdcJqJD0AYXXXfggA5cvFM_NHFCZDyncQLzAsIFQamhHwDQsjvXljAysSyo
RJLhfevHsrrVcrklNiNvINfBS5Hd7-ZpQkQQ60L7TVQ9HGjNnIWugfH7NXMZuAXwfDS4trnIQ-p9DKgjKN9DyCLAhX4rWPZO4iUlQJIU75tFJhtbnQUKcjPE
9sVKUshylD9wacabDkhDzGNAJz1A-qfaD64slSRxQ_pn2kqvDNPDpHoeyT6_D-jPkrMDXgofuzUeUIKo6fXDhZ6js8DCqrgWfl7Oz1hNHloVTktSsJGgqslM
YfVUhMHrxnrLOvkMK3Fk7jfRnlzyuzICUYxWTwhnIshS-bzjUJLpe6RyiquFr8n-3cr-NOtFsd4j1KSxYWCr6JiSBKH76xKzdmhpU-pCQ3iuyF1SKqqPRPnL
-SXYDMtKK4CDDTHGGmqrr513JRrLZT-uflfhCotPhMhahqtKZ8eQQgXXB-15Vqn-1_h5Ry8acT-7F0C00000000000000000V0C
}

