sprite $DaprRawMessage [128x128/16z] {
xTU7hSCm34NH0VJA_jF-YcR8AL8O4Z5u5pWIOJEn3tLTrsci5ijxFKNou7A6eneck1P88z3VoQZrQTJwTB7FQf_sAFLfezGdZK3VZuezmEp3kXsyCO70-yiy
pLAKhnsVJlVDGyxsvmCWsJUF6Rc-vWCa-_C1KlsJ0mobtdy-W5FzUGAv_ka4HgO_Ju16wlqt3X3cRqmWsZ-Vm4ZmCVupC7s_ME_s7_mjilKU_zdiKX-aLUWJ
zAZqUKs_VHJwphg_h4EMdot0lwV9kfCHuSkSIxp_CB6vJXNaJrtJZvz_yVEdjxr_QVxvMvxhsrejrA-UFxWSudoO6ncXx_zYe4UWlr6zVvNvQ-_vL-t-LUJ-
7Sl9vNxr_AkVlzv_lVygVt-lyVzZf_h_dx6-rlrBxLzkrFktz-y5dh-2zwz-_zJlt_x-x-__th_z_T_V_xjzljz--w_sgW_hXOnFlNzyRl-vscyV30uBlWo6
1ylF9Zi--VaqmfCFTLtNVGC
}

