sprite $DarpBlueLogo [128x128/16z] {
xTQ5Skmm34RXooZzv_sVzi8wst7YQ5OkkQ1leA2npq88OgMKKaeffPHIVjllZHtn3loqEpxWwTcBxkkrzwjV_UfNl_hLLyF5z_R8SwFlJ_KSf0Nt_svNyTC6
7kBXHF-jYcIwmNYuliyxxsjv_yltpW-xqUUH-_21fnVtZsJ4z0Jz1PRr5VULM1cGoB1hVUZBQLoeQStjDwDnccw4AV_Mj-ZGluw8jB70JdR5d9lwghFhspXf
e_6VFXn0v2uBZe-sVZ12qVL711k538_wyIXwoVDzuUU8yd7ViUa-OSJnsRvZatsB8yPy7u9-wktZ7V0ESHz5gngI-SFVmsZefrP1ie_lluxZoEdxuMZtgsGY
jkzjnfsCvhI_YLurfFi2qCbEOXFsTThNN7yJx-IJ_VdlNnvy_zgFHEQeIOWFyeSV_-HuO3-orFLdlc_uKrr_oOctMjmN3xl_aMF4aN2aQCby7oD-_y484iy_
Y3I_EbnPh1lHXPHv_fiIBD7vo7pJZOq741S6s8NOau4rwEGcqosm2-P8KdhKzQsDdrpSRrRr_HtsLVsrnz_YldLz5lUreEzTdtVUrzB--kDl4T-WbI-0PHov
iv00PoM7M2cbb59AAQMKlm
}

