sprite $DaprUser [74x128/16z] {
xPS7ZlCw30ObSMIZxjp_jA_6C8ByN8ZRYmSbrODF3HHDYKs54tKBop1lcZW0qDujyOJ-R-76yK71TNeJ21u8mDPT9VJqFBeqbaL1a1BCHHLde4p5aYeIKLd5
_T1o5JvFmrEK4sZpMHv4kGgVOvDbf1Wf3xMPCnDHUNnGCurcGaW98pSHB1EvQLWrEVmZNMecxBMLorNE95FTr6lRihwZHjcKpVXUD-srJ7NJzcQZesxYxVPJ
QYhYh9MdUbdOdyedUBSoKVLfga-K50j2FP8EgKUg7PXwwTo5M1FXhkLG-PdBOKeiYJgUf0McKbPo-fqg5Kqjg0gYN9MxObsalUMg09ckicE321xpWEmMG3dR
ZVDjADO07OVY4A8qon2gS73uNmAptt_4bzFshGFqRMz-5TgWpzaPpLVGOyRmneWP_OMQpV_OY83R-x9ifwayeBR25WSEJTnno01NO3oSbFiJWmvMssaYI8XW
gQccdPwCMEZrIVhxfDV7Z86FUV9SCXBHbWNAOv7SL4mynSf08YgNlH228a4OMP6hf-ftedQAwggMNERgAXOQu78x7F8gZ58dlR8NPY8gzrH3NeqZNpVgwuUy
0PBkW7gea3V188rKRZzv6nFA6w44Rq2yfGc2DoBUIBDekao_XOkBYukBYukBYujuCtWp_WO
}

