sprite $DaprStateManagement [78x128/16z] {
xTQ7hfn038NXZQR0pjW-x_-saI7UDc4aWjFzgsm1FXrkNNoKKoxOAlcWn_6ICIsbl95M6ihM3YOSTIlf8TcbGtR4n5IMxrfARMSDpe7v06y3zctM2Ct9tIju
wmkGPjGSJ1jWtQhkCkeygFlgpOPTiSopUHamwuAdYc8wB5ykvOJiXIcY67mmvM2O4vTzIuwKi_P7bpofugcLkwTsHqrkM8LGSVlDwaBIl7xhcn0JciUwL1g8
cGczNjTgLqmvaIMdQtUvY13l4QFLmJjXrGOcjeXayz8FK6g9a64sJ_fIDl0KLPOcDkmP4GluFe9pwauGteUDde3RMbLCKqYbkZOMURC6a0L2RLrA6J_VsEjI
bhMHGDYeQG88zxQkIwtbfLgNTRtt_VYqSQH0ast1y0QVZVR6D_xleYYAeYYAeYYAeYYAeYYAeYW24pj532ZdXu6OV33LEhoseUisW1tQ8EDyC8q8T1NhX4Uy
ppjhsYKAl4PsktIQultgzqXWu3aAK6ke2mmSo14oIhhW817ieaL41o-UvqyJUy87FKyS-We
}

