sprite $DaprYourApp [200x234/16z] {
xTsBSgog4WPWbJiqhlT_snF5-Gj9gayPZ3EzYtzVCiKIuKi3cdtzTt_qL_w9ZovPn2kKqbgX988LMo2HhT37P_4Ar4Iy0XBvYbUp78Lk54r9Z7G595Qw0X8H
2j4I0uLaYRwYmDabNe6QI5UW9EPJ5Egt2l05A8Hi4mU5P8bX578sF1IY9GuAiP9-nOUyqzioQ5_U_qxVr4Bcue92jWGhIh84jH0jWKAq18hd94Qq0X2bj1Ml
mED4q1d5IxJOMhGIyGf8n2iW4Q-0HBm2x_JY5JY4fIiW4Q_0wkfG2Am95D8bK7omH8fZE8PZE8P33SSVP3Zy-jzmn9ppVyEnHRn3nrmYtt64v3jAf3g6OpY6
OpY6OpY68mt79sGut1vznBWjLlS5ztdAWGulYCzRV1y2zw477JPlIRg4ck4xf-6USk2ajjMtqNKpR2w93pfCLH32nxw4N48FEdH0GHm-TORo4VUWmz1h2QIg
7Cx7H2auKvrh5cVHtcpBIUTYyj-MLRkmIXyJOdpT4jr3YjvsEx0hhBOPvJ0n7o5N1iMiIjNyiRDe7p7yiAnAcKqbSxw-PUbk4i3T3dqK9EA6bd960kk8kAIv
NvcXhnnbRcYDfpOodGxiY_9dWuaWZd60sjukbJ8dE4unw8x4BaVRAs2XvUYSn_FaYYEM2mnc30V5ICUaqJs5uuFjTxXpTQdC3MU0vnpahVbfMHrpyUtJDhvu
4SLs6B3JeUEtlK3LbesCWu1ebjLHLZeSkDJGySslTbQ0ii-1kcCYELHFIM8SNhT16GoMIzszT7F7LrkDqkV0pJ6fKCylRs4SLZUfPa_d4eVgc0z7TrEFKeL-
wR37dU1mfyL-mU7pEOJR--yEmYWtEKpby4qzcdNbUKVAJMnT3vJxw5wFShV3lUQC1nY-Recim-GsaTqVrIXtEsp6oiKpljg9YNM4t8QQy-fqxePgb7iTU5yq
fnz8SZLxpb7sjYrnfNjnb5kQL6ou4KRnzpfG48eXPHJy-9WeimwRJurKFtxG7ztBC8IotUb0dH7R74ES8vod571idqBdGL1qnFGxMWZPfYboZhAicl8ulE_M
juneGv_R7TfHBebuxmXxKxBcv33CiiB2Akt1uIKH3XFn8qc7WujnFZZRD5cZVnCyFwptzbJpVHo7ktOudWWS21o8SCTm3CTmcFYLvcprMvim1v_X-9mCnt0C
nt3GSDoMuR3txu_X60vbysSwXeE6umqPZh7FXsCuXcESLyEnBDyTgpZ7CatJhAJlZsMUjXI9SWr3X0CAI4Gwe40MQGuesYYIjS-XQBCu4k3W591uahAkr3nn
KK600mekEl8E4OeYcJc710KoCmuP2eHnY50W2-CGeK1cnY52WIoCGuG2OHmo54ZZaAd0De53YLIq4hFTMA824kH9YLecHB14JN-GXVaVVBpFeOFV4wgO_-j0
jBTQVOB3PTgIgwpXmjCzvmZ91pYeTdY-7eq34Y4Ef7508iknK3ux817doDGuK1D13fMtL0w4eXNkW2HOyGxKHBm3DP7eGCTQOWGvaCn8ddFO3WSlKN_gc9Ul
pENlT6pn10SIrPQPTtH9-XqX4sMtWM81mD0cy8u-IRzZpNdT7Obth95tz4lw7RVMWvTuHjBlmFvWClEEvoIyutfu1o-Hu-0bMabny984oQSuD1mN9GwIBiUi
j9hXgDlgeFc7riRnYAHrp2xjwtHvEV1tbydDBeOGzJJPxQkTz-RaohptNpEJyebiutX8ehGrMDHfpLlMbFBBOUXeYxJPx3JvxMkChqkNwIjnTvkyllHmF2Mn
WMprCpLoE7G-nnJ74K32FlhU_ugZX7eaKEJySiJrcsDEZADa3RkZP5slrwE_9ZPIpd3el2SOu-6mPSxUcD0w0jeq7CdxQAyuaFGx2MfHEVoAPM5VZd1C_Ylk
xB1eM_thkZ3Zm8AZeoIjX5V04VUU-BmvohAAvInBSA1jAhz-EAWG6CVD4YZWm9myQhCxgfqxXGm7dYt-i8TZeo06Zbv9j90mYjOHlZamvtXsm0Q7unptIqoj
QDSLRQSevbziQIwdCXnDMxpkw9TOA5f7EPlY5sI9npu_zdJuQbCH-nnjkEuM1q8_IlXQm8778CL8E7TLhjhWEBVHmZhkgmclW6DoxNCGXp42HtCPuxXL0WNZ
g6U8_Jt7kgrru9Iwpy7_9KWB1UUON5wt2MKNSIRD_cYpgNfFpE7LxF7p2kEuhIOKeU0Sq-9YZ5vDodnbAMrgQtDgqgMjdBj-KZwchNaBhaSi73TBCkUubB0v
miG5Zkw8To1_ui3pClwz0v7bw9VeNpXIh-D-oJzrHO5thaSTlAGC9S1HmYekE-RTGKyw44PntK7lSa3IAlxGuUvs8DyKVOxbSGVIA7xho7lUuK2Ww72KARhf
7GvanSslEn2TI4zlSo3TZcbUfazqJFT79pYUZBvP4R4HdquE-ax5snnhpa7TftXVFRP0qgLuhwF4TqbKoFdD3iebz7k9XkAz-wEHz2io_Nj3SYLPUbSKol5c
YLiaAf2raSXKj3MPnIfQoI9KqKgIdJiK0YIyGf94UM8KKYGgC0e14dcALc9cCIkAbqGZLj5AzBp8LBII95JHIiGg4F4AHBm24Qz0n2iGAAI7hYZ-1m
}

