sprite $DaprApp4 [117x128/16z] {
xPfdRiCm64FblV3HzxzjNIZDJjX1gui4_3SFUWQTnVL7na6WF3DVXObzCvVandODLKhf5Lj6Cc93rYcddJPi6R4PUSAkA23sCisoKL52RCx-ad4XzXQBVSIU
aBTfPgta_6hZCsJI5oZ8AVMISHBBqqWA54oiNZAeM5OWlLYzv5YPM7c141J9JnlugDcXILzBCtx4COXO-RtDOYU2L1SehiKA90SNIv1YoG4cLb-Wq9xoja2t
Oi6GYWBXwf14h23rbAjn23OaEQLCCjwOHAnMCWvkXrGkmnePsXM4ThyEQgYXXXfggA666cgeeOOQQgYXXXfggA666cgeeOOQQgYXXfR_ApDdAFQdxR2UPQmB
8ElnTWPK0XdNauEXtbaimATTwWKBw8XDlt0WgpBzALVmOQ9Qh7efoCK6FZ0s5PK4WbcjSjWcBr13n1B9-fBmKRY-97h96HdoFJeN2ytoNYsMOv6nQh7yAOKi
MLmIVc_xIZ0s5KWcJnyDDh9akd_SNJAVIeiAn4kYbznNl2HwoTYmVAUibzpnakWbPsBXX4QiFiuB
}

