sprite $dart [64x64/16z] {
fSzfZkOW38HX8Dvgxd_VsTgYhSZv2dNg__iO1jbKqpL-lCl-JSR3-74Z03kUqnV72K2E4u0S9m0xpW5-d0FyU4xEZ_SxFzvllJdEFo0Ud-VhKxuYVf65NS-z
mnY027yI530AH8JhxF85m2WG_sOTuFzw2k09K6HFWEY1XUmPW1xmx2c0w015zXo81bWeFG7G07xlBLXV0K7fAH1tOA7q7C0TyBQtu7rulhxq78YoCIPkFGKG
jVVdteBtWgOdGEaNcfu1Y3rhUWx4dhFUucElJSy1x7v6qtDWz-DgUWvWzqDudq3VLy2EWT8Nm8u1xBu2He2khu2T0xklW9q3s7q1Z03F_RWCWDivaFttffIS
0yY-JlGSYAPV8gfd0Bf-Y4WI38YslqII803wViZUen2bzti_HIWH-NmtcUE-9NMgFG1tkp9k04QKk0K8eT9a3T0JAh860peYQn6PWm8zeV9_VSM1t1hlW3dU
0IHbm3LE0VxyFm
}

EntityColoring(dart)
!define dart(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, dart, dart)
!define dart(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, dart, dart)
!define dartParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, dart, dart)
!define dartParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, dart, dart)
