sprite $dashlane [64x17/16z] {
fT85eYOn20FW83K8zx_kqb_M_MMSyet7b1q3_vsgiulwGJzpouTyrVYeT_rFxt7z91T-YCYVFQ3Ecddtu95vh4knxufSYAxlCzBG6J615OOPjpMlxzXoFlP6
dKtsS55nQ9kU2KHEFdnK7vqAhEhMEP--8ozFW_8WaxFxXgfaYhozCgXTfo-E6i2Ftj7OE4v0Wvp8wiJJzveBXoTsUvBjHU2vz2lFMEMRAcfH8pX6vjC7BREz
aUstU_kTQrJDbwzffsOKsUiKh_bw_ffkoblNJQngFrM_VF_5XsTd6fSeunwallpTNnpYNEs5VBH-ySzlBMOga5wW1XqkK4KlFM3Q9S3qIyK--l_ouTMt_P-t
lUrGyB_v1
}

EntityColoring(dashlane)
!define dashlane(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, dashlane, dashlane)
!define dashlane(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, dashlane, dashlane)
!define dashlaneParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, dashlane, dashlane)
!define dashlaneParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, dashlane, dashlane)
