sprite $datadog [64x64/16z] {
vPLBUkGg38NrHZhQ_txlPqpAJiL5TsTwDGBCZru7GtzjBEgH1VbxP67caGdqQVeFxaOMJl0o-wExdzXzui_SYlBYBeCB-siv7ld0exD5i9DXpSOZxxsid3dN
GGLqum36jICVULk8pnhaCKmHCVTPxnIYN0uUUS4L71jvZglFJ3J6QmiUUSOjjtZxPghGhm30z6G7ZwKDVzT8120hnmy2h5jfv4UDeni-JbuV-Rorbkj7Z9FT
2JZkfIrzLoNZ3mBq-wVoTtMDwBq0xPuRvXwEojVXazy8K6_5YUc3wofsuH9uRWJG29Ln7gEutLQH5ryxlhk0ihM2v9yT03rQhQ_CNumvlstO2J0tNwS9jZj6
x-Gfgd_OuHjv3A2Bj7S2ji_jOSnrsVv15P_RemNeY_Tz0uEVyfShGkI6lpBWa5i4V7MemHy5C6sfHl8LYfLee54P9l7CvyytOjGyWGD03TUJSyX60BSCHEjm
cK08twG0tGZWwe6ZCXBpFbocBl2D0AuhOfZ1Yz3TCWIn4S3rYv2dEWcICJRtur8uVyzJxAnIyXy405ihiE_z7NmuAKRj_W0NLVvMNkZe1XSsVm0eCQ-5yHuT
-k0J_5409SJgf_8Y7zKX0_Bn2U4rBY7ocfvh6D-Q0mde1m5S7wAO55zf0NsP-ZElk5_-6gS0hD_DhVs30EAQ6OHAYF56eqmH7mHm5nQ6G-zr-xg3R3q-203w
lU8cM6Y62HEBHUBJ6vPzFy1X5RgSCej65hPls3ZxlyoBHjBXL7qKi5B84QRoo5kOydLQaPT5ObfbkAam_RKXI6jo3zZE-7GFcSD_DnskNWZwhMa2QVH_i3ZC
POubd8ZZD2RocEiwvwSksMAieNYCi6u0ZJZb1oKvveqvEcKU3G3pps9ee36ckizb28i1IiIO0BDtC9_S4S2SQdOIevrPgvqKS6QsywcP5zBRSWBdxu5HSvby
Jgd0FkUaNPJd8fqyeuuDf8Z5p-CEviKFIC3EtU3vnTmltX2i02_-O2NQx_nOjtlnWkwJrqvAw37tnMk7exk-n-_BFsKhiTJYiqqwsJsw5fyG2w-scSYnMAGe
dWqP59sJQqH4TT5eFK_IoGloAp3lZ4YqpGw7PqE8gsi6E2sPKUiDoCb7svmNn6-lOXp3EZnnpjN_
}

EntityColoring(datadog)
!define datadog(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, datadog, datadog)
!define datadog(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, datadog, datadog)
!define datadogParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, datadog, datadog)
!define datadogParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, datadog, datadog)
