sprite $datocms_icon [63x64/16z] {
nPVNSIWn30CPmVuhVj7Pa8ytSDXlxK1P8Yxf2hSJim8LQvs3SghlQPVqcN997uIapvIc3rpI1o7fCw7f24cVSKs7I_gqfazf-hYczwMExWRcG7wez-Cb4uLX
WEZyQEOfVdSkpPl7SvlSIqKd_s0JI7vHtOq2qdiw8nmdGMn267puISFNyRqDvxE7mqdavFOWSk9QJplZwrkKWv_K_RF7BYwSl6tsWtTSRzhf6qUcsDolmoTk
Z9uTh_ta9skuFZP9XxdzmHKVvN2Gh-J0-PdW8Fr9xej7YeFwIs-UoFl093qalKtHyPCVixJ_QBPfjccsQTzvque9qqeP4pf-LqSAPM2p6rYeO7SwKEbsu3S
}

EntityColoring(datocms_icon)
!define datocms_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, datocms_icon, datocms_icon)
!define datocms_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, datocms_icon, datocms_icon)
!define datocms_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, datocms_icon, datocms_icon)
!define datocms_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, datocms_icon, datocms_icon)
