sprite $dbt_icon [64x64/16z] {
lPS5hWGn34D3zlrl_76fLQscMdYYmIHsam7xnGj4M1iliiAk57zfH_3hzVw_2rufjpt96su_W0za--vhWE98c6a2780vPn1QE6UoEA5jI2u0LwGeNQD5p8ka
ysiHIKLGadQbg2X3HqHHu3OL84I8B3d5bYASAw1FpGsPtLCprpaJwOTJYbhBl9eJt98MgwYpkngaIDyfO3iZnMCmZ0UF2J7RJSf6m3FSHkBKl9awD6_63yrh
5W2Tlk40rc7JLeWyUd1sImWbp9QKKbcVkH-YHvFT-vS1ikcVhwSak-kNN81gzm-UwzzyRdxyoVcjvvuVmKEgOLw_WEGn4EQr2MqU2vq2TFhiA4fj7ioykXQ6
E1NehI7agUnOcBAshGZejKFhipTqurUdjs2-SMSZ8glp1UxWAVdKV9PtdqybIf-GDeGilVKBamPHUY_2t3_me__76AmLmhKDCQvkdly__vDGmdK4_6Vx1W
}

EntityColoring(dbt_icon)
!define dbt_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, dbt_icon, dbt_icon)
!define dbt_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, dbt_icon, dbt_icon)
!define dbt_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, dbt_icon, dbt_icon)
!define dbt_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, dbt_icon, dbt_icon)
