sprite $dcos [64x15/16z] {
fP85WiKm24GdHYXXmlrlksJTxRyQzkeQxvauYBilUOZe6Hni5rGZhG9eYrIam2dFMAOuJ1ucCCWSx4ZAlW2ZEoqJFu6clxtXaHbFlb1ASmSitKvxw5Qq4neR
1XNL6HwomYgIwfdvVlJ7cIjOkHKL97IWSmAQlb00qRGTWw6PX3UQVE8_q6EyyXjT2X2Zngbihb1ebA_zjV7AnoHz8YIbcba4wpdLbtuDVUEZgbFJ1rUvuXeU
T7pkrzmqwck_P5QTn--nzm1WiUN5xy1wzAiRi7CxlZxuPuFT-ngHCSgsAzRrv5-YNC35sJMb4Hr9fVVkh11Q5p96zT2j0AvTq3pyvV_nbeAVe8B4IsC2nPYC
ME4D4Wqj14clE3GH6HL95PM2SdKyqETy28VEXXsAn1rq_8FwUBdmgBW13SL_k0C
}

EntityColoring(dcos)
!define dcos(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, dcos, dcos)
!define dcos(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, dcos, dcos)
!define dcosParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, dcos, dcos)
!define dcosParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, dcos, dcos)
