sprite $delighted_icon [64x64/16z] {
bLTfegOm27jq0-BzppjhloSDxOpoKnkW8I1-7KngLtTS5-0sgdoziT8Dk881FifJT3DS6uDtUO9sN2V3-9-7wWGXG_yNMfHZPxFoCZWRsW7UGGS1TtS0pC8M
Fh1WhLUvfR3wCDd08zeQdwWASd24GxSKbUZ1pdVtUfIbtGvqpGvtS0BbC5a8uaTzY9m2XJHrLzlIrG4dBigt0yzEqRaD9hnfoGw-PU29bEOpnf_inQPeADhq
sR-p_mZ644-8hyBl5CufeU8hHSQCwP90k_EXOlIWhEX041EmI6WiXb75yeqXp6UcP-bf9yPROEFgQ_WHioUA-fsY4Tv3Rk6gn14-XmJasoaRCbr8GWtqMAmM
I6oaaVQ9sSEhUE4HmqHhomLCBoflmVdsMNJmYuUAPlAfX54rdYQpEDUU2OYkaT-9pqnQUCaL3BobkIeQ6kSvdWUpu06UpuHvrQ_dUAeYft_cpy-VwA9R_jOk
jss6qwHxSc6hViP9OTFA81TZuTRhgKEaRBSfrAL_L71O3mQybsMR0p2ztzTlIQCQYW-RBcP6hMkd-S4zua8psdVBOxl9BDXnNx0kZotaGKCgTM3MpjnYMwNm
49Bf-1pOIxzJUACsKTe73l2nrdAaBxfkuOq_m4PzYfh9ouqfJiVp1xpOBdUcLlCZ5zhXy-Pk58oMcgXw1m2tNeC6RtXxi9S9hL_53mkW7XRqyvP9huptrspL
KflGnMuFTOFcHIGxY9HhMC6b3WTf8HkFIxZfw7se0TJZHteU65JU_W1n6vnju7tmyry66wm--FaTU8bcawP00Z_v-uqLDzo57Eq4_Wa
}

EntityColoring(delighted_icon)
!define delighted_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, delighted_icon, delighted_icon)
!define delighted_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, delighted_icon, delighted_icon)
!define delighted_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, delighted_icon, delighted_icon)
!define delighted_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, delighted_icon, delighted_icon)
