sprite $delighted [64x22/16z] {
dP454bWv34FbW6Duzp_lJh9bRjz7awoPIDBSUvf-YGMzzKDs0RJhLoHT3Fs0WFG6olIPMVxfzpwaDaFvLLFKq267d6r9VhLlsZPTeizAt8adyvb1IRHfucza
VrKw73tcAUZSKh1iBZyHSNoUEt0Lgp_9VU2MPavzmF4d15KPxdjlZuOfPR_rbsH8wxX9ZTbwqRhVxkNR4iwmvUjA-Tp0rkXCJ9TWAe3G8fu51vgvk4nhJ0du
nqAoD8hI8nXE3kevwTQ0wI-CqTWa59n9J7eUKaRViIgVrtHFMfDp9HP7-Ipi6mxowa_gPfBr_2dHeZKyAvDEoccxfMGyzUQ5XsMKWlXWKTscszKiNJQSflAO
FUlvB2p2Q5EtDbjDfclZhoZhNZ3k-6fSXIGhpjsdwxBOIMXoRj7ery2qPahEre8yfy2buApJHHpmX2fecDf4q3l1r-cc6apEkNAdeMFStuISLXshsqTraQjJ
6jLnklSiEiVetgkxUqiFCtt0Fh-lCctwglOvqXZwDQkQetycsC7uz_4UHkfViGy7-E_pcQJ-dGrX-Yt_0G
}

EntityColoring(delighted)
!define delighted(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, delighted, delighted)
!define delighted(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, delighted, delighted)
!define delightedParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, delighted, delighted)
!define delightedParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, delighted, delighted)
