sprite $deno [64x64/16z] {
bLS7qguw2FrIJANiVxVFaOae4vx_FTCiW9G3n9-3aDj0v1E4intnzoz8THA_0It_LRi0Ru4r_4KRb_XeNQu8YEMYVLaua1VYQKkkwYyK5b3zF-qm-0QUzrCk
arWIG7BLCx6Yd-RadivNWnMU2vMVE4vxSaLXMLBJ6pH-8UWJQAOYSvF6RkfzFe9T4HCmCmJdwq0iQ6VulC7uXSdCqyP-LmhbAf-rP0jHFCIEufcfbUakrLDG
4MxCJil16v9UyGfP0CWlL2N1yl36K9d83fBLnt2JrfLHe27HCm8qCXOhNsHTChmpCfQEQMTJFZyljyjJ1dh9wKIk0-LRztTwriQIYDD5ltZBO7qDhDI9ocyg
DGDf8y1LjoxLdrBgdqNi3CoMcXJ4uqDos5EvmWfkSrjgbijZV9MzUSC5zADTsGnN6CMP3h7Lbm53KWg1BlV7VZO4V7PA9BOaFR8uH9QKWYJZIubgITeRCuZS
IiZ--u9XIGhZ4gYikTd7BqYMf8HNmk5cv0ScWuIn6XoPQO1ntyV1Z7EDAdXtGzEPu28Gsr6bhXTE7-eQwPHhio--TtJRZYhnfodvN6GpgkYrB-Qdljs9g5qJ
nUm7nbre6UVlflnseF1pL54pJVcH0V5IHnKSPdDy6q1-ZAeUJJdGZ1zdKVUque2LlYfvo4GrV51O4HSXMbjv2C0qZlYH004e8MmUSFPMQyqEXGNr5lSsQ7Sf
BEwlkDqjwr9uiIMGFVIz4DqUNktUd2thZHHTP6hFsR80tFs3OjPxVTBUoHkR12IDtbG4qa4scvPCAqIArg25D5LoUhZOY1IpaPAfx5jW68k6bThaRKiWC65D
Gq8bqzofOtIs-z9JCk7c7uFIpoA81peRvG_2xiG4HjtcOCr6_OD8Dj4G_H-GbJRHR-z27M3EHmPPLceDboKy2ZqEHA607iuS164laJrcXjn9Repl5ccm1POs
IIuX_pwHEl4UyrDxHJg9BQ2gvzy8HuFR1a4ldl9_
}

EntityColoring(deno)
!define deno(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, deno, deno)
!define deno(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, deno, deno)
!define denoParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, deno, deno)
!define denoParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, deno, deno)
