sprite $deployhq [64x18/16z] {
lSu5WkGm30NHRqWaGrJtFss3lTZBCFF2K8dqbDrDtpZTgxxXMT-e44cl1lZxzEKV-jJZQX3ICUDoQGn_d8sYtTkCQJh7CAaydbdEPbKFXrd9QRA4ZAUUs2Aj
Vl0qAeJaOEPUIgjIirnyEZ03eaBq2KS04_0ETdwyc50q8RjBoarcUl0BcWwuEdYgq0CEDPXZPow3QU0AfYpheQdhoO135MAoZO2olZYX1LILFTwiOFBTv_Pj
JppqbRpsf44qo9zwtts0g-xvcvHINiaNyvjEk7H0CFNw_yuUEGwWMNS5N0CusvvXJUHI0FwfLqzwy18ieSRoySQb4sYJfvcqdfVF_TaarKjr4jQlATa5qt90
3qQMMk2f1T6If0gNf7Fr9bcpThgadBJiinHGqhwLyjgbvxuCC7rXFJ2zM7tLDmo8f1U_tm-8gj_eLMfD-iPXPzAtx0u
}

EntityColoring(deployhq)
!define deployhq(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, deployhq, deployhq)
!define deployhq(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, deployhq, deployhq)
!define deployhqParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, deployhq, deployhq)
!define deployhqParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, deployhq, deployhq)
