sprite $derby [64x42/16z] {
dPC5OiKm3CKIazxzBppmk2j67ueo1CP_xEiOOudAqHHhFke03dD5duZeCDYAR-ZT34c-uZiT04cnuWSf2KcgDTzRNlKTTxJkXnYXXhNfKrck-eP-aVQuUVs1
idMzeVo9Zlv3-hpPUvNsWBmH0H4w8Y_r55uwWXlDXsjB5Q1tObvk-ucsnFkZq3l4HVNcqcw0b1hyTEn7QGUAReJJvLHY6ZeRla3ImKGwob4wXlGnyp12YJdH
6H1pPf_5t4iVke8qoy-JxSgR0rr3kdSNLCpVwMiOkWKPoT-zNS96wZ74pzmFz1oyqqin32t0ryfVAByaQOmHsYsVqZcUj8_mlVAzT4fv-uxe8hPWoOt-Iyh-
_qTDIzuHFsntzqJOJljV2tr-OXuPMLM_WzGOtaKOUpP0LRPJ6MvpD1P5w_Eh_DZlpJfZYnjcPFeON-NNldzDI8pzzkkEJxzdo_uh
}

EntityColoring(derby)
!define derby(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, derby, derby)
!define derby(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, derby, derby)
!define derbyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, derby, derby)
!define derbyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, derby, derby)
