sprite $dgraph [64x19/16z] {
dP07aiGm20G74239GV__xI6eotbxmyYusc3mJ1j3yIZ4qfcwF6QtFkPqmFIXtZutWsGq51pyOUQAFXFHEOVKF2iuvHTV5-_mqWqZXoZVczqt_SMNqZj8Trhv
il_YJ6uImIOUeTqeQb6A3B-vPllgQtaelm6q77IjW67nVy7NlIu2ho1ITnuZVGMaJlpMZnbeXg-H131aQVYJRBKiZZKJ1xWcaRU-hTs6Cm7kyrWMlkPFyy7P
TN18ytr_NXOUbv-hkgunF_dzUVpI1wMln35txd0y-zkHz2To_lGrjqyyokz8FyZrNx6oPn_7kkxqQu_bqnQD-Ym40RkxCG8oyqLHeBpewXn-t2PaaJttpZuB
mtjSvRpmZdoFjtHbcuNZFNJ4hErdd_hpxaV39wJHvzhxKXToDxCeFuICONYO9m
}

EntityColoring(dgraph)
!define dgraph(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, dgraph, dgraph)
!define dgraph(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, dgraph, dgraph)
!define dgraphParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, dgraph, dgraph)
!define dgraphParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, dgraph, dgraph)
