sprite $dialogflow [50x64/16z] {
xT95ZaGn48FXujp_nCFaflTdDTJVsfRAKUoox2utBlf56kJLRofGFli3EatouBIeFXTaWAfW1ntEYRufqG0LP80gbm58EXbmFgTwIya2Pgtf3RDU3C-_6rwG
3iYB8NbU6Ic0ZkJLeBmQabU32ceapupaaHd9myxwqUxkUcqQdzs2MUvqofvvuGbkRnojcR0lOWxpQQRoO83R6MyoG1Ku21rMPgYX1_56XzsIO81AC40b7Q0D
_HAyaOQaVWdUw30gvKLfeso7JuC1Zm
}

EntityColoring(dialogflow)
!define dialogflow(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, dialogflow, dialogflow)
!define dialogflow(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, dialogflow, dialogflow)
!define dialogflowParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, dialogflow, dialogflow)
!define dialogflowParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, dialogflow, dialogflow)
