sprite $discord_icon [64x50/16z] {
nPQ7qkmW28L1XNDu_mU-9UjiHd6BsRzyqmaTeagcD4TDGdWhaaXK0yc0J5W4IQygJoX6yb3ab80oIDvSo1fjE3GE0iqS8032lJaxGT9KClKqFbNZ7ojvamJu
Fi7KIkCMc3l7u0Qflyuz0bFuRImrRukW3hFRnrBrLnCel4HBuQ-DGDFiztQWyIAUXdUbWyhBj7NwaHko5leY_QuMIRWk8AUFgg8LasPJqUApdvftrpKlHQ2i
JmcRHG6L6ufO73UUZX7FBKrhuNUXfWOmqaZJMjQ7VtefAQ65gZuy9rkT9tg2b5JU5ciVnGyO-K7z0SHM_mid4C_cdnBmn_QTxa1zTLyP4v4yDXLjc9HCLQip
U8tOKuwry3k8NxNFyukFxE5FF0G9dqJ66FT4RP545taHmQ0FQNd_g-4ifJy8-zknOjmg4HbErUYlEwtcfohizdPj65HnNe23-Fo5opzKfJEjh-bTpwOI4ldd
zJ9yklSz80-nSmurERVkeSX3b74eUNtuWAR94-hHuCSHYaFb6Jw7_Wi
}

EntityColoring(discord_icon)
!define discord_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, discord_icon, discord_icon)
!define discord_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, discord_icon, discord_icon)
!define discord_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, discord_icon, discord_icon)
!define discord_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, discord_icon, discord_icon)
