sprite $discord [64x13/16z] {
dSlLeLWn30JH5UxS_XjEx30yF1z6ZQHQvrVUqcSiF72jFYxXbzA7BVnYNJMxqw5Yz9gmap-aZkPmf5krtbACFLBRawgf7fMte06VXLvWTFHjsSX8sBKCaCCH
Tokk1K85BG7-tgyqkDc0xKmenLsN7kXQLWKy8DqV6VZLcprx3RWWf3ZhCiFgx4gkoGLd0yJjmK0sM-w11EnSl933I0tBdnw-zsNZIRKd5cYbmH4BBhLRqiBO
frekyu3-5RfhV5__V8-5ZUgk6DZKXzMEhdRfmxu
}

EntityColoring(discord)
!define discord(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, discord, discord)
!define discord(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, discord, discord)
!define discordParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, discord, discord)
!define discordParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, discord, discord)
