sprite $disqus [64x62/16z] {
tPT7hiKm24Mfb_sl-FVwyBMmF7jdd9DG12X2KOy4gWh8C9KZB53_oT2fh1zo1pwoizadRmZK3jZMjcOtGZX1d648MJESwZSlGCrnylKnFYhTl8XUXq3_weew
9KdoOvn6d_yXiO6sJkK_Qe7g12kUIiUIbn3DN-4W0NYDVD5SLo27Vd_IMkztVdyqM_XxNsoHG5BV0I33Q0OV2O3xVLYqTK1tVj-x-LW0gvtV8l370lZ4Bv0A
JltITGj5OkltQNqc_xv-z_spaU_hEm4HdVX1LcNEviVP04URYEOZNVdyNkuFRIDzjhykzwUVxM-G2tPvFnGNzsiKlpggaoJy2lz3i0CERJqz8aXJXYJfoX1e
6yWHVHzT9IzsfqlUwLhVe81ZNQ8AG8QRjc0cFq5kfcH62AcoGNFsSOxbnXxzH5foUuPwDZbDJb0BuCTr9hy2
}

EntityColoring(disqus)
!define disqus(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, disqus, disqus)
!define disqus(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, disqus, disqus)
!define disqusParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, disqus, disqus)
!define disqusParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, disqus, disqus)
