sprite $docker_icon [64x46/16z] {
xTH5aWCn44JHujJzBsme3KcDAc_dRNB0Fnh3TC9Q4ghvxv7AFMkYkzYIV2tBrzxkaKoGTFNy6UtD91UoU__4Fki3mH_qXjRYjCTlttVeyqz-q0TUGgMlQEvm
kf8zT0hJzVRJVm4Da7nwVc98x3dPU4kGiSy_nlxrD-bHxz6IgvdAs3kt-VuVzWt9UB4tj04MUvdwo3xoTEBe_G-yz9wYTSDzbEvh-Mk9fttXeOUH-ejrqxfD
wnuOSi_pAGACY51i4SfKxP4fbNkZgIyVdg9--EJrmoV5SgxJTzQYe47KppuP2cTVlW0OpNmbTzfWrFDagESfbgwzUWLGEYAuhftf6CT57KBd76UrqYK9xCTm
eLl4WRc5AzDjh1xuFUixxHC
}

EntityColoring(docker_icon)
!define docker_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, docker_icon, docker_icon)
!define docker_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, docker_icon, docker_icon)
!define docker_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, docker_icon, docker_icon)
!define docker_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, docker_icon, docker_icon)
