sprite $dojo_toolkit [64x30/16z] {
fPG9ckKW28GVui9Izp_lV8XfexFFLE-L-WL29vzB0-YNbIg5VcJ_dAVKG_dj_uQdkaGN__Zbr_mjnxYSl-DRvvz2LCNSj9UZ_w5c4juKy_gjD34pgRIFTYoD
Bxv_UKBl_acmv6tXuRYA622B9zqUdFVzupZMH3H-AYtSs_ojQ5-yRIykb-GJLyur6A3HV5vFKV83iFGoO0zlU6r1iAnotlz6-yXG1rhoBKkc4grnuiMt08wS
9QzdBGQ6X7Nn0gTZzP49tcVvBON7sHVVzOeLe0PFLrynMHnvymOvlE22d-UyLN_6wytNvA_wiHhupJUzPcA0L__Z3e_h_WdGUkIFc5FmkOXZCSeuXYK7MZdN
N3mYmVTpWBbd1VZeAFPyv2AHF3cylC-rEPppNiZaY-y3YiRKoN_QArmTuCLq2eSLoSTYe9M8UFWQqD1NVy94L0L0sqKr7qbJp1nRcExvKjXyXZ5zhs7ikZCg
o1nrJqlvV7yMoGi-wBNX-QwA9xxi5okttkiJuls_HxNrnlJvA-KpzS-gGFy_t3x_eUAnwlzG-rdttm
}

EntityColoring(dojo_toolkit)
!define dojo_toolkit(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, dojo_toolkit, dojo_toolkit)
!define dojo_toolkit(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, dojo_toolkit, dojo_toolkit)
!define dojo_toolkitParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, dojo_toolkit, dojo_toolkit)
!define dojo_toolkitParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, dojo_toolkit, dojo_toolkit)
