sprite $dojo [64x18/16z] {
fPC7ekCm24Gb45Kbzx_j6c7jxtrIAGyDYLrIhVn5GCf_uP7LxGyMAelQEmFgfIUJ3UzilcE3ixmQKoEjTwIS5HfcxfmMtTJszzOZ5jShXWsO6p7nfi3dT2Q9
MTNZJItmZZl1TrPransks5nhgUaBnnonXu_aGx6OtzvxtLdq3CclrxFDQQx969DNdfJ-2dX92U-iq1sF1knMxuZNcaBRnxB31uns3f2TDRpZ3iIkoLTRZqMy
I_ICHtlYENbjXo_Gt22zFnxppFKboISJUsSUTvOqG-Ynat45OE_7IAcwPZqy1ijfW8whZZcEzXI0HaJjwWDin3RNf2074QllLhK6g7wcGXT4SixZAW0YN4sz
ZnbA1ldIsGZ5D8QUhKXD8F-VqzCmnWD0BH_gyCzrscNlKhwGs4SLnm94Nzvh7xe3mhofVg1_
}

EntityColoring(dojo)
!define dojo(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, dojo, dojo)
!define dojo(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, dojo, dojo)
!define dojoParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, dojo, dojo)
!define dojoParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, dojo, dojo)
