sprite $dojo_icon [64x46/16z] {
fTG7ikCs44NHrxdHegZzxzPW5Af8sqFD-K7n8YdWWXb_nGs_4q8sne-8D3Nhvm7OfJAhck8d56uUrRanVk0PvhL88pnd4P6rQkw_R23F0SgP7lVcgsZLkJoj
MmlhL5IYgcvx8i8jRJrP1d0t5UetyzAAhLJeadkhrlfV-ZO0Qol1YDHyPoQtUQjA5O-83DFc68WFp9Gmi3rlHfAkwf4P7fUZxKoOI5ewuyHxdWA4CG74OgRV
t3tS8zpsogQfCGwnpowunnuh5npQD1MDq_S__R-SST9fckBS_Q82z-J8YHcdcgRNVZFhlrQliIF991ooBy2ntAQszad_dJEb3plmtZVnO71RbEEEHQwMF8c1
iN-HXH-zuOeyltaJ36Bgm17CQzvkUeun3unowpLis_zDBz-SesKm1ZMzNXC0TsJTxj_op46gYf7EtHk0EBokBpzfd3dXwlNf9goarVxcFubdswJZXdqMWKtM
U804iMoxDDoGUSbdEcvcTIbWC9DwjaCARcZFkyI1ryP5P8Wx9rn9-wpU-2Bc7fDN6-cb9OdNPpCB1hmYQrMNoOb5pIBRwpr_3hC28sBfc2rhqOAnaAXftglH
-teml8-mJAPRJUrpQqu2Hg9ydW8JTfIVzwjbH6HDx_VS5zB_fkkn-ldjD2AjuKvQLwPCk21nZt32TL5_YDZbSYBg-6B2Kr7VMfNnL4t3tadnr3GBLkpkPdYg
xHzmyeNYAQgNepCtTsSyHhqJ8X5n5_n2FNfA8eGx_m
}

EntityColoring(dojo_icon)
!define dojo_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, dojo_icon, dojo_icon)
!define dojo_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, dojo_icon, dojo_icon)
!define dojo_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, dojo_icon, dojo_icon)
!define dojo_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, dojo_icon, dojo_icon)
