sprite $dotnet [64x61/16z] {
v5G9ckuW2AiODkV-ztrJ59L-xmQJMNyr90JRvmC2AD0xW4xj-Q9r5lCNoeowrpNMmQm-VeQP2dygGDHyGXXbiucFW8d_1FmjGFSPraqtHYzqNVJXOzANWmyz
-HhobPxolWsO2Ax-r7pRHozqMtGLLhVbe4OWbxpLyCHylCj3MOZSRWEfGnVT5LGQIphuzxYbWP80RhxSyhHI7OQmfSK0jsC_wLR2s-iCX99R6ZWDj29_XuTS
5yoovAxZIZ3J_xzyI_UAd8bj0vxyObzAU4lUWBnjMXg8rLRaQtYxUScIxkebW69VMXczhOaYd6O0LmEOTtVBbvjtv5af5yrDnnr0aoEVAgLx0LJFH4i3t5xx
LtXLFfuQGEmKXfy9H02iLjmdi6G4hBcJ3QG15RH3Jv5CRuJ8Aw_jMhyJ58RD1snuVIFHEiHWAvN9BmEYB_r5Df-0nHa3DEMFWJE2CIO_xdsrxoclTQlPxY2O
IM-TddQ_TaAUDUaRP6wnFHB657LLZ_tWC_8XBmvORRxmvY-U2ipd-dU0Vq7q_6NaFFxLGXyuauCm68O_qt71zx_jPXeRfXVzhoIm5JrJGWW9JseLTmlZ-A0R
CkDnNH8I0BhrDi_zSvhdyT2CE0YLCzQYQWQQAb87iMceNNDIquIisr7DcEgm9YwbzdBZYuAi6BPREWLY2z4o5QFjf6o1cA65qZRLbg-zaSNAqP25Z01mGrO0
bhgcmuPeq8nW00Wt7bKqxdszU1JBYvyjdeOUhgBGJf4sJwVVdy0zMoJkHpy2RWiCj7ouKaSGqr0BaDGaWaq2gcedz0HqZNWLBGFXpmkYadRRSOcYvuIGH7Vr
Q-_kDhVedW5admKKtsTtlBTRp-rO9SJZeEx7kzpwuHvlVCHQzO7PwjjmVUcR3thWSt6lF_W2zH5-yHkJNppQvbQVFl8m7xJuOSVAcpwvzyMVQszwTFUqzxqS
Y-zwChVltz_9j5yyU4E_U1gkF_YZuazyIgl7fZ_mtJslFep_NlbKUUZLlQqUPVfPV-ZJiB1vveHP5uu08i_co-6EjNy
}

EntityColoring(dotnet)
!define dotnet(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, dotnet, dotnet)
!define dotnet(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, dotnet, dotnet)
!define dotnetParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, dotnet, dotnet)
!define dotnetParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, dotnet, dotnet)
