sprite $dreamhost [64x63/16z] {
fPU7bgqW34M1b8CG_lzttzBCS8iwalNszB99aNRJD_drNM5He0AgJ3cjG3N_oAG0wYy0bCkZ3jEqKsIwBm2bF-tIHZ--gjjd0BxNgG-J8ujwptqERCF3C-fV
G6xrWQVmdaAvqMt_0w4-WTC0jEkZxTzgVGPVJSXzxEZUVDJu0DkX6ytknKeGE_oUFVqby3RH3ztBprZrPVfrE7MM7se1sN1qbX-gO7FR9w-u7wYWsA_FthvW
0XW_64LzcLCdxCy4sFx39tzuqVedcfAd7-w_WrniJE3FFm18t9_pZsA-OBneFdyZwFRcM_RTAm3Qky_X1jO-ta2u0TNU_UuRG8JnZf4N48z_ta7Y_jm14UxV
HAC9j75A8BG7rV49Oez0zLqE784EX6nyigN0AWJb_fs0flKM8FlkVPf4ILVt7ndVz98MPm78j_ylMbui0NxydDZoKXF1y-PocK5Hh1o0VPnf9Jsc09ctXpET
qquMuCRUTQUD2mpf83E0impEdtUtCusJKmG7FoQWKj8xTLnYTVvR9XOz42vvYbJczUrc14hty5RlAfXOatmf5stMvv_KnXrcczBd69dGR0mhZosOOxGDAimi
YgsPpUDcRG37TZwE--00pbbtO16TqmbP7w3JpIkW9QpcT4bUgg5BkeMQXOAVuMP_sYKzGTNiMkueQOKiMxSlrthbj4uchREItgfSH_u7
}

EntityColoring(dreamhost)
!define dreamhost(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, dreamhost, dreamhost)
!define dreamhost(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, dreamhost, dreamhost)
!define dreamhostParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, dreamhost, dreamhost)
!define dreamhostParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, dreamhost, dreamhost)
