sprite $dribbble [64x16/16z] {
PP075Yit30EXNicv_stpA3l5-N0VFIp6gqXrB_fDSQ-AJ8uY-Nv0EfoadoI7gz-SBof0Yo_x2oR6q4yQO_8ha9dNuijYq6E3VJs07_dMJoQvqlzLJrAbs9kx
jxxzIZtsV7fSuYUB5FYR5PwTmdfpguTQW5Thb3_s5_fFVsEXrBxQQtbIWCfuryc9-N__LAaQHP7KipHzaJzzUxQJ-VN8ZVPpzyiY3tA6KTFt_q_ylaCyF1um
VVgRf3Jlpdh0WNvS6S2IQkXDwDexoN7rKm9CxHwdRAMBymOQjoykMuNJdA8H_O4hmSaUDJnFF1KOiLBKcJg4h7cI39eQGqRMZFxYI0SSgYeON2M30qElUwCf
jiBMeb9a9AteU_1isAN6EHQwrO6OlMYmf7PZHoKEtK8aNaiTJDBnL6CkisIkjp7eqkPWAOGE9J1jVhpg0YjkcwuQ4cxfgKswifkIUtv2MVaoYhCl5q8XTZa6
zEGOdWEviHLRrwa1C81xYSboOMhupPAqVIjVdy7zra33VKa1yAuOSKvkn_rKwIy
}

EntityColoring(dribbble)
!define dribbble(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, dribbble, dribbble)
!define dribbble(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, dribbble, dribbble)
!define dribbbleParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, dribbble, dribbble)
!define dribbbleParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, dribbble, dribbble)
