sprite $drip [64x23/16z] {
tPDNOcGX30HRWCYext_RNR2S6OTVryGdgSZWq2ikA1dnXcwAAvNCt_j23jme_8_-fF_yO9XQoFYj3y6DDgf_mKcb5fKdNpGVL12Z01BsLr9DWZjvSMFv-85E
mEBkY0l5Ja6JKvw0h82g3uVa76EHqtrR6_SxRP1Sjh_2MJpP7ILIVJ7dcRKQtLSSlF_jgK1Y8vUy-95C0CHsy13fVlhWUm4gTo35fqyyPUdDKUWFVCLBm2vd
8S39Tzy4pXxBV2bFgmFrZQztVxqzjplh58xznVYZ_jqVx70cwy_c7ryDggTVPhvUbZVnWT_nKj1t9qK0gMJrGQ-q0vcFV3Rn0s81CaYRqyZca-8EB2F7tJUZ
ZTQdNre_pIj_EFyhfG---Vh7mSFqXAIS8zuGSyax5m8WfGGFvn9z_r9jhIJy7lUTF-3_0m
}

EntityColoring(drip)
!define drip(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, drip, drip)
!define drip(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, drip, drip)
!define dripParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, drip, drip)
!define dripParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, drip, drip)
