sprite $drone [64x17/16z] {
dPD7WjWm30D15OAo-F_tXd1BihVrkC5bh0xHdK4VXeyqHa7sJ_AiWwJNCJ_ePHgQ0JR8WTzoDbtoC0pIS6BsCxp9T9mdqTNqibWqF1M8lNE70LHO5TfAFT4h
X-tTpbUPBjsXtt32AufLKkO2uWaxyyWClSfcTO3rQgto9BR7v-qxUcP7L9YvCMJCEia_skM7cOLmoAI1GNjyspdANsFbWkS1M6QNd-lobIYV3UZTO2Jn-ddw
nMwOyjjLFe-y_1qnFPuVYFQsFpepJUKpzwbwNxcjNirs-z5Q6mn1dvDkQFtsXQDyOkS4c8N2aGwN7ociV44oz8EBuKLJuAXZdYcedq-lixlf6vBeZ1SwVi_W
Nt_W0vsCp-jFsFY-_ly
}

EntityColoring(drone)
!define drone(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, drone, drone)
!define drone(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, drone, drone)
!define droneParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, drone, drone)
!define droneParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, drone, drone)
