sprite $dropzone [64x64/16z] {
dPTNmkD028CDGr7kV-1jBXeId7_MUadZmnJ5vVMJW0mVijse8Veafazvff1dF5EOFEIPOPK74E5cxf40lqvTu84oSb5FNB_PJpnYR1zIFwk0jpnftLg9uune
-DfVBuaZGtOyQsFVVrHMPaU2w7cmSRN0eNJMf5cFK_4hpXAe-v2pfYnRQ74ZF7KcJC3W1jT4xubH4YJvqliWZN_w6Aw0dyXxdV0BwKF_QD1xYFaGa9dFYiDr
sgC19O5VIsJpS_48kV6Upnqe-JsnWikXoazZAjDtdeVdQehAteIHa9CFPfrmDNSRT4u9tOifkyDSl3Y0uZqzqdC2SVBJuQyTxGqpPGs8lG6MpvuOMfnJ8yRU
m5I-CZjDo0I4Z0tuD5F7rDs1PPxEKKueMKjExIT_Srn_EJawIHeFmW5Clu7-0hkYsTZ0lxV6xc8FuoIOYf2Ne39Xlo0epS6_G7Am7E0WRs-yiodkcaqo_eD_
jRpZES_w7_8SPvtVMEQJsopxM-CrF_t3j_Sy_9-od7Uoys_FLqKxYPSlyYaqmkpaiSGZX4Qka-Xv53fvuU8aZbGjRqc5AssyCopVUhvNuFrC3rddvS1zcaHi
YppTchCbTPNNGDcZdOjOu6M_W1FdXQJXqOYB55Q_MxBotmKlUuGiy_N6qdcPNEJfGUAnBV9lDv01xh7mOhs6ohJ8v28AloO3RrV-dnzvu7dYvDTfsc2Tb-50
iK7XGxzec9S7gD4yF-6RkZCP-KNHWqzvj0zMpvz-rtda_GFyRm
}

EntityColoring(dropzone)
!define dropzone(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, dropzone, dropzone)
!define dropzone(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, dropzone, dropzone)
!define dropzoneParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, dropzone, dropzone)
!define dropzoneParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, dropzone, dropzone)
