sprite $dropbox [64x55/16z] {
fPPNiWCn20H14l7-ztqv6gFPqBzTPQWLZA7_g3DrO3yzCzPLpveV-BZaP-GN8USzswThIY2_8l-ZP_omBCGyx2No6Sg7_F1iY8KzIsumPjtweRd5W7TQqTiG
Wfxw3dqGzX-JrVuuzbq96tJGrqSgMmPy6H9ZEk1BYJgQsDSbKQR3lYwfJoBaUyGs4liP8TSzMyqMx6l6w1K_h6OBzbq6AIFVZMSjWRqypvw3VdeVRzYpxk8D
-XMv8GHu1LwGlzd_lUzNXgEyprmR3-U3zQF7rlT_qCe_kHq2vhSU23x_3OQFuhVxAQKXARu_a7pyszRIaG-SJwkv5Zxy3kRsOeZvwI7INnE4gDDM9muNxp42
i6K1F7ozKpk4Zi3QRkj1feDl1n7mTf3Xe3X4ccqzpB0I5PYwqKBNOKF5Nm4
}

EntityColoring(dropbox)
!define dropbox(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, dropbox, dropbox)
!define dropbox(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, dropbox, dropbox)
!define dropboxParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, dropbox, dropbox)
!define dropboxParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, dropbox, dropbox)
