sprite $duckduckgo [64x64/16z] {
bPVPWhGg38JDMhEy__iUIJbEiA7F_7NJ2tv9AABWiPDQP08VG8Qh7FyYiJZ99Y1T_qehOGnbraV5IFiBRKaux2vQr7F40Fn_SoUl4u8bVhtYlg_11vrA2nAN
Ccm4aQXHsTkMFxJbv1zBOeHz2NODYXD-2756rf72jtWAvx0MuXgEDOvWWhrWp1DBt2iwCeAjjr2bM0HGukMF2nSzbY5IAe3FpXDdxQa79R7qiGBCgv1LKTHu
zBBM0MgsChLDLl536KF6OKcifa2YLwyZvYsujhlfoGyqxpQekhsN2dksvQo1wkyC50pOodleDO0mAKT7GiCIfmIlCv2V0gJIumwjw-QasbL-5H0ZlTyZmOmJ
d9Bh0iPmVVp6jmgPVkCIPcvF7ZeIQxaNXqxbEoVsti8WoIWncU_h9zCiN9KdlpN-LQg7O3a1AVUryKh2jTN-bRgQWE73JjJfVkVjwoj-0tn-8pd59gOD_u3r
CHIMtvyHBV-NRmp8iY-VV7nzVtcV_zr2E7NtC3wG_FoL2PigLa_d33SpbiAypNxAvLZACzqkvHi-z9KL4RLRdgpVbdm-U99FUizZvcVQ0_r2yaA-6xZ6Wwad
FlYvCL0kBaxbdQMldx_meG_UPsxk7sF_xWpK5nxJ4oHu_-mCfFl1OHx5BFhzutKJoni3lQRW4UvModlvohkjWPHNpjNoIwLc4RRhG5g3T7ykVrxFBy7R3dAE
j1klbsz7Um0kUSERrSEzVGas1kgQvux5UpovcsmCNFDPwUKgaJ_N7HGBkX8o_M83NHk0pWUtptPuafv8nuZqlHT8JDL7F-ZmHqu6Eiymd03oLA_FQ7u_VhLp
HfnW3CHvT2yyc_UAUP8ya0cQWP5FuSQPhyihe6JRXCayUE9P5amALXIu3DZnq2NE05Q5i8DinIE4k1pB07wT6AFp8Gnp7xyNE3sWSveuFtGW9gf2Uu6A7jY_
mjZFwLj33ucmUoI1jFkAOoT9HdWTC1bqxbz_UhTZkGSwBWFVIhmYWCtRNo2hZNlWVGI6G7BVIU2AgV_q1jm590lwgrWnXVGj_1y
}

EntityColoring(duckduckgo)
!define duckduckgo(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, duckduckgo, duckduckgo)
!define duckduckgo(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, duckduckgo, duckduckgo)
!define duckduckgoParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, duckduckgo, duckduckgo)
!define duckduckgoParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, duckduckgo, duckduckgo)
