sprite $dynatrace [64x11/16z] {
ZP85bi1024F3e0FT-rztuLNM9RM4lZyEO8amBy8fTtoL1NvKuwErCABun1CDlmdZvpv53yudBWfmPXuU0Y1aWe7w7T0Z1Lufsb6nTkOcRyzY9jJgB-YG1bqI
e5eTLWdQH-W6ra4TvijfRIq9SaG40o1hdlES_x7WSGSGISxyfp29jXS1sDR-MpuSjQwWbLbfk_aQQ6Puyb7jooFMnTE9n0mxSOLYjBL0Lm6f0U_-qV8m5fvb
q7F-su4y558dBu2c9e67Rv8wtVFljyaCOpT-hlzKzQNzFl_EA7d6hLE8Jllz-hDcjKB-Urpe_QVVOZ6DuxsAyL-z0W
}

EntityColoring(dynatrace)
!define dynatrace(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, dynatrace, dynatrace)
!define dynatrace(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, dynatrace, dynatrace)
!define dynatraceParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, dynatrace, dynatrace)
!define dynatraceParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, dynatrace, dynatrace)
