sprite $eclipse_icon [64x60/16z] {
nPS7jXqX2405SMom_-qcvl2-JZ85IRkdl7f7n8RX6i1851621umffGZZpP5BhRNayT4639am09NECk5U2CmsbkbEUiPdVTX9xKkuF3m1Q3GE8RFSmyUTZkax
CSGkppHyYZsnlC7fNf-nx_L1zI8cE5_fKNKBnrNgijX9OG939qsT4OxJf-43ikpGuQVEDzcZhD6da6GJfYLwX2wxzBNvG_P9I--xY2y0J-yL9fqw59fug7FY
Lmz5muVWHQUk6tJxvxdRFpGByzyw-LWKjY4VVlWG-Kll5gQV1W3f0zb89o2u-KD-zBBapvz_1BUlowUpqcsmqdNd1oTp_Vol0IGzTrqS5_lNJlRhrVvfrsKa
BiuPe9ZrlknWsUh_KWJGNW3d4tW6SCZanLRIkVPfic3GwtaE16HPUDKPltoyh5yURM5wBxzuuRa497Fvf-IhPG2XsckVwmSKJ_cvTk7mrSypYSJoJ8_FPp4K
VemTNkyliV6TNRNnboiCLNROymO60O_AlBfSZTiau0W2OJmgrzfQgrKla6Om4f55-GO
}

EntityColoring(eclipse_icon)
!define eclipse_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, eclipse_icon, eclipse_icon)
!define eclipse_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, eclipse_icon, eclipse_icon)
!define eclipse_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, eclipse_icon, eclipse_icon)
!define eclipse_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, eclipse_icon, eclipse_icon)
