sprite $editorconfig [64x62/16z] {
dTQ9hhCw30JWSLOdiJtl_xPN5KNby9Ust4_RMPfaS6q0LyeCqbNmlrGB6pg3dd5Vij0akTPSFHBkAhG43OPx5nkuAOSYUVGa8bQQuIRho3453qshuPun7Wds
BBVN5vCK3K-rtyrlLQnXDykSkACPPZ-4IT5l7by7TkAzCD_hd3G5EwKinnrTMyKkKJFlnLzLZoCavhX3N1i04Ta2B5RSKHcgopp2RIqBHhaNdoJ37e8Rwu9V
PT9RmaPIwTD9XgQVZrzotbATf0f-e3IyKGRfzQVYNGHDarGyfJRDRFIC4sVx48rr2xCOjkPS5ju51us6QuFsM6rSLI0FgOUdGyPWnZK9zchqWgHcSmpjERiB
TlDBftUId2B3jGW0oJhAQxZhA_rb05RKOpkLeVugNiLdar7dIZZeBRPzbf5Lldszv3XbIhuLlWVTOzKl5x1maWA0csI688_jAxrYh3Wf12GQnjPUKkt33ig6
aq40KIGehmTllop0ECUd0rYbScBJN6kCg-cU-6koFjReOja_iYOQ1U_8kNxz6SWPsAZBH6T5ggstMXAEt73KkFOO--2keGFkReoXEirzZPRnjEplwKlstZCR
DGbWmRwMOByWusZJVMo_ZSDw6HpOP2v8qMLc9Bq3w240CCB6TWEo0a0Dksniho1jspBNMhQmpRUDozHzk3NBS6pIY9cmin2Sb100BIRJNYiFaZsdbDlqcOzD
iF0Fxzl4x24JinIB84ahf_jMmpyA2u2SNeCYWAaKDLh1qPRnhBFZHMm1XVLvyGC7uNYdCJHlGNCFIu3j1yN2I-PLku-8C5lBRDRZ-BGfVu9MN4cvbF8C8U62
DnOJVh5Oy4uuVg7Kww7-hjFmLcN_QRdBLQw2RsJG4dQtorUSGt317P-boMYu55vRnYLHSYLSuyFLJJzfV7jp8IEN4T7VDZ131HynGjy-M_8Yemk-22yUQvwx
KmRfJV2Liw2lfGa7MOFUy8l1UBrnIigr3mlIAduZHZBS7YB81ny5lwiwp8FSzfbQ4sxu3m
}

EntityColoring(editorconfig)
!define editorconfig(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, editorconfig, editorconfig)
!define editorconfig(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, editorconfig, editorconfig)
!define editorconfigParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, editorconfig, editorconfig)
!define editorconfigParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, editorconfig, editorconfig)
