sprite $elasticsearch [57x64/16z] {
vTHNSiGW381Xgu6suFlVDfM9jWXXEJtvtx-Xium2H29-YWWHbeqXFI6BdjfWWKnPKujTEKKKsLY20ejm7A4td8ZC9TqvajwCmi0PZAMvd3INbkRo4aMoyiM1
fA2Do9AHvb2yDjmU2M3qIeXzI6xOsRy8niNms4QTjLvL11SBsphig3TLiLbm6xQUzAxw9ciEcZokOtXM9-dm5C2cmP3dB5H-XIqDIuVjA-7-gUxVdFt7iVy2
r9Q35VPUyhtFAdZ8LlIGuw_ZxmI9hY2hNv6xIX4o37hmqZB8JeLSMSimWIvBC60uAAWtO1YD9gjbKf-iQDBXuY-ppft9f3EfDj64itLEdNHdaMvou5ptebD7
YnkhfeQpW2HSNTI8ih74i4mG4hD8B2zSn4MF
}

EntityColoring(elasticsearch)
!define elasticsearch(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, elasticsearch, elasticsearch)
!define elasticsearch(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, elasticsearch, elasticsearch)
!define elasticsearchParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, elasticsearch, elasticsearch)
!define elasticsearchParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, elasticsearch, elasticsearch)
