sprite $element [56x64/16z] {
jPS5SiL034DZqjx_n6MI9-jLoKEbro-PubpRI23j-cuurbCWlaaLrai0hbEMM1-1KiK65WLICyQOPjFgamA-Y7NL6CBesw4cmN_MFpwctBCijWi_67DMCTGa
1ptDvcYCmydcO6nC6PnLpFLDjcbG-uapXs_qhzSdICRKZcTZqiSnvl9GCgTBr3akiSxrsX6dIeGRDAwF875oUucSWuibSiNDgt9vrxn-vd3NJqCTI17FbzKI
EPHHAKKEmTdLE9Q89N9TeiYHH7sE1eaInvi-874i4Q7EWnK_0qIkxtUDOudoF1ZFhCmLpUmTvzCSyJRFusbZ88cReyWt7Fnstu2TTmwvkJYCoieS_oz-C0-d
X25sJUgjbG2N5sc_AEoqwxUdcN3tx5oFnZZiVDV5RcWmtP4fROH-jvRzxaxMJm0s9eWbhqgCxnsIJS3_yxrAVuzx1
}

EntityColoring(element)
!define element(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, element, element)
!define element(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, element, element)
!define elementParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, element, element)
!define elementParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, element, element)
