sprite $elementary [64x64/16z] {
bLO9OcmX21iGLtZtl-wlEaiSiNq_tIl1W8Wy3g2GIbFxWRQQXH__0qwrKw_BtjzR2dVPKcr2LLjhgZRH4jrWHvt6EGQQziIIstIO__8WRUwqnKjngDBu6vjA
joc7I3dtrNfEPT2-3cmA4YNGnyFmVv8GXpvKh5lYGki2NNfNLsaLgxME8j2qcNdq_FuhgLcBF7H8iGieefw3Z85HDLDP4rFTlp3sY0PbsO7QY1hNrymFEloH
lizEpG8uM2r88NPO1AH5inYwUnHOPFIrRi6BkuRUb23I-d1GriAfi4k3fMAcxF5bpHdhsox2ZX5ojo9ywKflVv1QKeXh1ICV4o9z0Qf8Rl1HGBsnFUX70Kh3
RrkBs8Tinvg7SOA4AHma0AntHVLJ5s9EwS0Xy_Ol9TAF_89LUGuVNKemAoZ_GCVomrh9wVD_DjnZ1JkPqMvVp0A4dqxRxqjfFcwN4Vn3ZeVNd8xGFw-thdnC
7obuXWjOXmHCFv_KvprvEXZhyP57JxxwE1IlrSj-yCgx-ZeOe3_vyGSdhNaUPrdo5zty1_KhHwQAzk47BFzZCyTxqip-kFsYGD_U7pNDeBbk2KpcqwTcjgj1
Mu3c2UD4zEZXtPAn_T3qZDfLN3gq5EmB-8PJ_wEnDrq9jXJiIpHMFuQ5jae4IKFwsbYIJNNIl5cBndq9O9o-6zlWfOQ35kPZUaVv-13D20Rsn74rc7pWtS6N
cUFWWqUStDRoRAzGyZGVK-eR9G0vLjG4h-vRSwdwOghQWDOKHM8gBw-PlbfIWAo_KECGjAFmTqigIzPnRkQYArap_zPJU6mG-U4ChwOjXuVRljPkk1i54GaC
KQ_Z8AA0WoEGtcXhY1hkqvMysfOxT6wOkzL1-fikYdH4WKjp0XMlAs0T9JfniIlu2FFw-klG5OwWDAijE6bB2cKCS2-g5e72eTVLh3UEcBE-2hUM7zHHoRVO
MFo8gvCJtw22OkW8BSk9_0y
}

EntityColoring(elementary)
!define elementary(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, elementary, elementary)
!define elementary(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, elementary, elementary)
!define elementaryParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, elementary, elementary)
!define elementaryParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, elementary, elementary)
