sprite $emacs [64x54/16z] {
vPHPcZQf2eIT8HZC_U_sF9ZZNyUU-wwveVBJ5uCeDFsxKObgv5BBxsuQURlI0Q2bD01m5FhDJRmhCB2YqPdx5hyMHteZtxWelZ4sU5E8X83qH1dbqYN7b03L
zBSAg8WV_ai32beubzJc8G33ej2kG7CkcGu57huPm8E1K57dH8jgyz1FWNPR3mjRpJ_dtqsNS-V1AnS_NWNSB-i9jBxdft-VBnvRLdeBKAt4UNbSKEhfz0Gz
_3XSvCQfh_Gji4Gqhhdok17_EZFSA5-dFxA-1JXr-MLeoD7I9jhhQgghW0PMakBCLy2uRF3oLiqKdcKzfab9tOD_1rgLqoQUfagv7MtSJujKNZovz0rEj_es
I7uT7ZAKhp7OoA_IRXFhz7l4Tp5ijoHyhN99VFXgO1-Y6_dzxAdmklXyw6_pjbd9Yh7ykcns_qs--aR-K8297uWdaFSyxUIhu9cHN79gXt3QXqhzV_bpyPHJ
xXpMrKF67i-ElE6dIX0T416XF7-sVqFTQFUgcgEcoX1p4UzvZX_uVSUWBVr6TAXFLPsKoi_kcVR_lUy9ufDB4-zdjQ_D3VKUNjxZXMroZfkNps_zy1atDOos
U8DRZPstEf6Fpl5SRMZVj-vodhixfxp3O5Atk4da_BcZdts4zlwUT-8by3BeNbIbx_BpqNTtDqDab4umpJyVZC8rVwuITEoF1o1krxxwFD0LOCPhcKdRFJqH
EXy7JJbVoYBeE_nrezy4wlQSmi_xFEvBUJ-DZdnzbF8P7V59PwcUrdETKXwKiy0GzsBqSZzzTV0efHEDSkFGYKilIsakaDeXKWdTh5LMvNDtb3C7YohLMpsh
jzijqUuAKOY8TQ5K-n1NWfsyY5jd4Ucrv0SlznI9YLkmxY8oK5CcdToXVCwHkAHixcO2BCE6MBjTY4CT49WEaI6qUXiPedbj5KDawfrK1Nb9vjCuc0fqoi8J
1TyQn5lyZP9p3M7f2Lul2P_th758XXtA9AQfGA02Y8tLjG3WIBtLj-ySeuTMEyV133iCZSroI1Kt3QCM3x69bGLZj5mQRBQKQ9MErL5WnyIeWSVlKKnqSWoz
shHMBB8FLeq5g-daWzQIXfaf9rfMzJbj99dhBMlc6dcOXPoXfdhTYUZ9fiM7M8_fxbTxaMfFVn3TvzHp5sM9l_vYr5OYtK_hFuc1ye_uKjD_BVu7
}

EntityColoring(emacs)
!define emacs(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, emacs, emacs)
!define emacs(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, emacs, emacs)
!define emacsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, emacs, emacs)
!define emacsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, emacs, emacs)
