sprite $ember_tomster [64x61/16z] {
lPK7ckGe38LHbWEzzx_j8k4uDZLvNdzD1VYV0fWg_ro0y5iq8U9mzfkbBC9qZGVGw446A6QcGh1zSBTTGfqEF0tUy2QINCsYzgquy88fe1SyCqk7ZFmKHKcR
dZpjSwHkht8wSFZ0GzQWcsu6lAsXGVc9qy4-FH06uTC0KXJ8m49XK7tougRcyvfQviaVBeuGsRyBvpeljTPrKtitJzCqBqlOBStGJ22Y3-HhMxhqg3OjQN7w
vLidPXWRr3hJaOukmKGbUHwyETQr_Kz37jQgkPSzHwthDDVLO9j5cTTMuLA6MfA7hnx2geiibJkzjQYkCkQjMXlvlpc9fPggzvHmfLxX36KiokBmAqD8dQEH
yLLuUhnCbSedpIk6mHO-jsBjNoKFor8-Ygjl-mjJNLH4TAwMsM0CVNeiyAzbswowcZ2p-Danc1VLJtJBqzVwrVvgNKnLM5IRq-pAH39LKyCndaE_GKn5Tqrv
zjhmDQcPbXyG9YrTBEfpFb0MWd7u502qWULGFWozcTizzbcaAaHHUgvVCdsd9h4c_kxTZrCyT5E__65k7-g2cxMPVkPJpU0ugSaVMwW_r41QcwYRJhKshzqU
JSVXxmbm_nPrgN9sLt-8bxegnZw4qE2S_Z4ULmT4WCSF1gZy20yJmOO245mc3CkFYF30yKgG3G1u_Y0HFNzhH8Rykr1k1qwX0E6F6uYxytqLje8GVio0lSck
Qm0e2tlBuEbWBkGE-m8iZntzw41kSF20Qb0wJWC3fDltwbh4BPrHr5oAy7Qk1krIFgt1dOgv1Xwy-kHkmZG87u2Q87ILI9ts_WEAfQAAWMHoLOnmeKpTtE2u
rBGRb97CLEdSINKcTpdJOrNB06DTArCdSxjDiy0hnOmP8AB77X3bxgixxm2fDHXoYl1nIeqYe1MCNUBeF9Y7Z8yrhWqroyRSSNEt0BG5TGcI2_ecwYTPivVY
IdxZ8Np9BG1XRwYs0PDNjboCOSt1cvi5S0iFCHSnCiiSSlkraSaVQy1JLpwiCRBKgCCyPPaovhHjQwmLHKd7Lo0ngv6nIPuo2qvYo0KvT1JwXAIfAxghMY2m
XyFjlGJF6Wdca9c1xXkHxwWafP2xkdUOyalGFcZOIU-EUaZsDV4KgoaTLtAqNPBk-wVH2Ka4s4E9xMlaxPBQXC5p14sPUP90bo_mvPBCHPamM-HdReBQ6uhb
g4w0tnu_e7xlu769zHiEhXSTOfykVr3_0m
}

EntityColoring(ember_tomster)
!define ember_tomster(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, ember_tomster, ember_tomster)
!define ember_tomster(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, ember_tomster, ember_tomster)
!define ember_tomsterParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, ember_tomster, ember_tomster)
!define ember_tomsterParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, ember_tomster, ember_tomster)
