sprite $ember [64x27/16z] {
jP87ZkLG20IR1pHr_nElaEsTg32fVWGNycja_JqHFves4pyO7w3rRSmqe-zo80_ekpIZ-i7yK3BpW-D7_61_nQZXV3z-1rZVnMJzuFOQydNwEA7FYRPp0qz9
wIErGm93vUqOvknlArmVdb9A6go2bY4LNFZ5iLGurdl5G9bHG0TG1pWwtDGwp5b7nisR-LpZCDe_1dA0s9ACIqv8vSx3y7RUsovQ3GsC0RP5IG5pEqq_Xsgz
SAMUa04CC9TEt9S3MWMnNqmpzvurRfXDjoPiYOtlUogkT8_JG5qbASMyd2S1SeNZRSpJFJci4zAzcddMgbDNHz408rzVhRoChLdoSRn_NF6I7xTXgQrQ1WC-
nom6nWDBwYt9XP-Z7JMlySkpu5dd7JMNvCbDQAq-6TkVplLr33XLb3voGale8UBrp_q_RkVt-0S
}

EntityColoring(ember)
!define ember(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, ember, ember)
!define ember(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, ember, ember)
!define emberParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, ember, ember)
!define emberParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, ember, ember)
