sprite $envoy [64x21/16z] {
dTE5Oi0m20JGmuuaiF__tQKozrrTNXNmBieq_3l6CKPI_eN5SyUDU_OF7HlJiEDxHV_g8ySp4cQ6_DNxAs6PgN_Ggjl7gtiACtwjBUZR6_dox_psQWf0O7hC
prMeoSi6u6H8P423eM_zw6g2jRffhS2OcDqTqWwmBgzFvnjfhprBi1aVGjXQYSr6gKJRN40DYCVsyNG_PLpUaW3MYeWc2z1MDgAq7S0QrgAjCIUtNtbxUUTh
p36Sw_JIlbBQ0Co9OYwiQTXUmvEdU-l7Xd3avJ6hTPDZ8y0gnypx_VMk7_ArbwfHXQpB-yC2j6hs0AGRBrxkkYTlFdYNTGZC0RW0eTS-nqwDonkfy25dqLdS
dVHZ7slhzkFwQwvfPm-5QfnQljSoQWB8bGA8amQesfRZxiCVVEPLV7FwbaO6kPrdXk8FaLnZBegJBW14yCVOd2x_WJkF
}

EntityColoring(envoy)
!define envoy(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, envoy, envoy)
!define envoy(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, envoy, envoy)
!define envoyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, envoy, envoy)
!define envoyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, envoy, envoy)
