sprite $envoyer [54x64/16z] {
bPHXrguW28Hb1hpxt_4zzhqsU3BD-LCbZm22vKsCS9GpeTRwhrO_XYx50MGTEiAYIlmAiMRPHweEyXDNqabM4WyAACL9W98T12ZXOmNFgcXAombNOhPWt4j1
YigYrnwEzzbWBmQ7Ubgn2CuTnRNYwMJx5neLRdEeKJ4S4HCLWIUqeFYZ74z8b0usH3sz_Q2mRkT3dp1PF20tjKPRDjx7B9iRWlR93QKtZabSKioYHldJh31j
Oe8U67ECfWz1qndpv8pfFKEZNFbx2bVzCnS7Pr1Mg2jPTkQg-XBAXvPhmIMKdG6gHMmetaKWxrwokb7S8Rex2JC5k0xH3AHxQk4jXTKz6ADNVgAGt8wVVAKq
BgbliQ5ykD7q7Ikg6G6jLdxl3ZHipCiirJ2Q4Sbh0RoiZCGlIEiCF2Ay_xVBcAHfL_8FutMrmZqQeP6ix5P4ny1EbKZjIxKyoqsnfv2-0CszfKjZJJNTlQvH
pfHDAGqZExwb5A3UjfHSGQ-SKiWKv43tzPRI_lhm7IMxx8nhYZ7MpOMzKmovKa6Ry4h9HYsALugY59-mZnHB5kUKYHAKiJqbICAUGddAV4svbQcuebWMCaof
dIOK5DlI7-n-coB_0G
}

EntityColoring(envoyer)
!define envoyer(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, envoyer, envoyer)
!define envoyer(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, envoyer, envoyer)
!define envoyerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, envoyer, envoyer)
!define envoyerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, envoyer, envoyer)
