sprite $enyo [38x64/16z] {
pP870XiX30H1T2JW_x-DCEPWqtkoxlPuK3bZC2unPsVDbsDzPf5QM3ZxpuCKYWYN5Bpp8LUb8troJbKan-1ddCQdgKpUuZbf4PkQO9pA4bGPfwGi2L0h8LLM
GzDpBW2ehIpICW18RU5le_ntK7wx73caWB5sKuGSC1U5tCK0XTnYI06aa0C6AE0E0nHmo5ZQyq8EcNkgNw9cYPj27OfmzeT3vb14j-zXF58QTxZ3u8bqk4Kj
nbgaW9kYlUXFgLtU5Y7blxGXfBn3RZD0VJfxeFmtPm_NFUeka_VNTOyhUaJpAxY-RXs8WBfrbmWfu8u8ASH011HmImJNVTbLmuPWiB4LAS6Z3aNEHQuc2CSl
heZq-2B964DLpiOHcjjXTkQL9FK-zJujIxRc7S-Ipgcdx50bc1DxD_68z0moaAi9B1jpcbXbnras19iuPMEm2IWRWarWsPyc2iTJDWQROFRccqd5clyaSumq
NzVpywHVdnhhqB0XqHSXsxj-fq-kwUSUzun6hxKcmqEg3B5ZKRODOHc3jYgadCFyOVvAqwL2Dvh-oCC_rEl4_dR8oyaqPFwugJ9YYD4Rg4V8ZgPksPIQMclb
SSt_vTTXlVNHTvUfmud6v37NJQnVjvVg0m
}

EntityColoring(enyo)
!define enyo(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, enyo, enyo)
!define enyo(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, enyo, enyo)
!define enyoParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, enyo, enyo)
!define enyoParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, enyo, enyo)
