sprite $esbuild [64x64/16z] {
pPVNLiKm30IrkxSNy_zVImUTerm7nDBcVKRfiMC6GEePaeWUe0g48MUYQLVGilk5jAVG6Bv-2D0duKnt0fIS0DI2dYxHqkjTaAm0bMoqOFF16K39uRfJONSz
h0UerCSOkwgFSJkGuvLw1bAV19ZZKyz0whF0SlmYi1jZ7c2E_rgWtFjs016G4M04vGGY92S0o0eGiWAap83CWFvxO9-1QoDmOzhcpJzfpdpMzl83EZrTz7J1
qmbB5yFIXQ2ZAmAEpeWmT24YsDQJyl_ewYm__-DTrRLVqONw0pjLNJhCTIvN7wVKCp3HXVo1Po3r31IzZ2-tG0js6zt2NZybaBm580qz0otT2fWBy0WdG6y3
Gcy3X5W1lU7pgs1iGTcsAs1RhW1KkdFv0G
}

EntityColoring(esbuild)
!define esbuild(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, esbuild, esbuild)
!define esbuild(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, esbuild, esbuild)
!define esbuildParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, esbuild, esbuild)
!define esbuildParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, esbuild, esbuild)
