sprite $esdoc [64x64/16z] {
bPU9ceCm28GXOPY-_nFlf-n1fiQriwTDVguWjhRJ22JvUf6966wVo2TuiByYCyPJUcPZkudva7vjH8RRlORIQk4-1b095TFtpl-Zp_Lj2BFmtAL0elx69Hw5
4NybPAak2FVVBLky5YSF9I8YW3mlHaimB_5ctACVbG_CjK2uobs26nEPcOZfRmKcjFAoCl6JEabck6wBplFL-Aic9E7h0NEqjkaxfpcuQRriBsIFliVb5Bmj
bG7989VeNUZj8brhVmJbrCQfAvRBlXdlxeU1F_Vfg38mnpbIo5gN0CJYv8levytPgqnp2K3SvulP-u9pkRiP_HwdsM8lJ_VUsnhMb180vn8-mrBlJkropXum
rl3TkFILodaWiIJ0njkGy5MiJQrWOqa_U9YyvxsxZ1uC3FV-lSwpkyJIq7ckRpLOknhJ_w_Ivfu7YsU35fxrvsw-4xUy6b2y-ozrVjOMZ0iQFxYbW6qYUTck
sGtusSAe4LvxshJJ-EtGykn8C_3GSiUcy6sWwMe49K9vogRmLIQnBnElsqJd9G0LhHJTv3i_kHsVR_vpyCsySty-cZ-yyMubvNKzfUNLVjwdRzrbIuRnZ6yf
frmzYX_iy_CYWUHj_QHYazi3qkUl7c_jftW8jm5Iw30Rxzkr7NwVEHviokCLd17Whbwi1yAvttm60CGSNlRwSVNpdjq0UFaMh_B9qAUd7ZZPOcjYMvLsb8xV
yLqw9IS_v3L1y4DUrw7sNMQtu6wYL0CHWJ8T0UwixrCWMK6IlCNLWDQ8Jp_2pCiYETNguqzV33S7zTnl5B9PKoVSxgJkDFDX_yg3l8G9eRUQ81NEwVQ1HYH_
uSGM_W8
}

EntityColoring(esdoc)
!define esdoc(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, esdoc, esdoc)
!define esdoc(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, esdoc, esdoc)
!define esdocParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, esdoc, esdoc)
!define esdocParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, esdoc, esdoc)
