sprite $eslint [64x56/16z] {
fPS7TZGX38CfnWPp__F-lQ0Lws63NalxNc9fnbOIAlSPQjGKQim7UOdmDX_L0ppxC-_113OFDDxYrUU9sZkUlHzI-OkUzxZG3_xwJPKoiIFpNFFVLFmaGtt9
QVcXRFwOON4SF84AsY2nURwnM0Pa66JdHWQJ3KeF_dvmqKesx39isy55pRILdGr6sT7WLUsNj6MsmUicktNmqjJ-IeLj69JT6cjkQgkqqgn2sTdwfuF01dcr
K1pveceibRpmQuO3FMrgUsa1tilVUP17d4qGV0soVvMV5PRMv_o01_-OXrNMvmNlMUODFytl-7dBzplUYr_nalI6xx3sJtay1F8Ppq3_cCSbMltZznSFiSql
xOy1snVsbnpihrbVDw8-x4_aErsVaTF1_ax6Hxp-CLHIU3_MEg5qVQaVylrAnHooe-llLXBOKDTFrTyr0ANUmXBd1e8PaWqmU5WY9Qx9XJPLK6301XYSpUC6
mpR8e0OQjb-i8bH1nsdxxfMw7zaRjdyt79opun9syH-8dF3A76V8uko24Xn8KYHn0kBk_nq
}

EntityColoring(eslint)
!define eslint(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, eslint, eslint)
!define eslint(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, eslint, eslint)
!define eslintParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, eslint, eslint)
!define eslintParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, eslint, eslint)
