sprite $eslint_old [62x64/16z] {
dPPf5jmm28CJhnZV_xpTKd2VR6RKwFyNyK04Nz-LgfIB5g9pJYslqA7pKNs7cjh_e6rCK7-18iwZABa_enbGqFY0vwxpYpHzGpNKd5FpWRrNmIgXHf2RF5r3
OlqfRySR1Siunqw8kiryZvqorcQEkKcKjPbZRWfQnvextj6w5r23skT8JW_xecbFPFVQCNQtGjtra0WqzzWbh1kip-QMcmhMvRYvc_dKjfgshA-ZsW7tfYth
TAPlCJajtZItRbUWifbNNp2S5jEuR4sBfnLFJNyR2RQCDH-sO6wT0OYcPfkQ5ArZLSSjBOMO5axjgJqzVwMnJOkOsfCLWORJj6nDuol_spG86j-r_3JjtSJq
PXSCrqmjAmENcqrgzmLpStvBreB1cd0RciyNB34vMmi6jJScutEiFo8njNIyPKKty_vrMkkCPztC2t4DajMaOCvS8htNgmNDMmPLj9P_Xq5VO3qzMuMx_cQD
RvzEcO_esTSOStLwonBpuZ89m9ORoXeVNPwRmLXhlY8ybA5IpskOnenbw1v4Y1sD8YunMW0zgLCeZsidKCYDenbG4kTHZDs3Nk-KEVGd
}

EntityColoring(eslint_old)
!define eslint_old(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, eslint_old, eslint_old)
!define eslint_old(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, eslint_old, eslint_old)
!define eslint_oldParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, eslint_old, eslint_old)
!define eslint_oldParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, eslint_old, eslint_old)
