sprite $etcd [64x62/16z] {
lLRdmciX29EH-FvFV5UNL7FANL_-MGX4XZrZWy7BMHcKqvnvDlcS7oCavvmys_3J11iQplaB_ZWd-KnfDoD3qkDElmcmu9sHltBcl0DA-tmYXoLVHy97y7Kq
TRqdm5d0OgK9UXUq5hqVmFYR_FW7-YkoJuUOhoOupk3cY73ilxhWuvtzoz6IlVIfqXWwry-B1Za_1WWM3xkCdcfrgrt7Zr5X5DfB1jq329lEOKLSjGWOL0rJ
PwyADB_IBJAMgsVwUm2SzTzOoVKYu9n4AQBYqvTUyKvVUohuBFcv1ZCkTRLzHAgiN9F4QgDlZZUKi2ZyBN-82MJXvoptNosYpQpBZTN5-1ehdARC0k_z3o3j
QS_dYSkI_F8aIRrPrpjKkNjVEsyq3a-x1ZV-7Z6kzwU2lYlw7VbfKroW9zy7zfYA7gTSsHV0qrsDNG4nZxLcIu1sZER_Soe_FgPnCRXLilbA9rUTSMla-t03
4U4U4GcIfJuMN6HoeYndpIG-7_9L9i_UHrGTyCXEYNQWiryQzCxxe962shm1npN0IpPiV80vo2EN2CdUfkrD1r9m9LBqh8iG_A_A3z6rBjXvqjfFVVmkFzbO
ciu8aCXmgVyx
}

EntityColoring(etcd)
!define etcd(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, etcd, etcd)
!define etcd(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, etcd, etcd)
!define etcdParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, etcd, etcd)
!define etcdParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, etcd, etcd)
