sprite $ethereum [39x64/16z] {
dTK9SiCW30LGG20sEVS_RgaLcXypCfwgU_Co-e0jkxMIUrAXy1F6LVnUqM1bgppdAa8xbl8lQxlyV3BXJVwihFlR_9D9kSy_cT1T_WzhD_c1IRBp8-lUp8zC
YfqVcP2T7rcpyoEJPEMVp5e5hGnNWVbN9cJalx1cv0UshW8LAuDLG7weTg0ha1zRzkC53bOH4OaShnV2jkHl8g9im0DM0VcB8cKgSHN44o53M6R-qbK0GqWZ
Fv-v3QQmkg38P0fPszbCItn-m6fmBjGDw_5z2ks67NmUWHwgoUe9A2H_wWBisY-Kv8WZTbQ6_JptCduaPZeXzszM_VljpUjfyUmChDFyLwU_2udZVEjWs0y6
R1mEEWzM_2Tk_RvZE0LjertcjlTmkV-qyzpAtE7QXRPPEskbjeu7kEkrCtrcbpTc2CUG-rGzcXE9uTooEInnXZHpz2BhmPogo7WnSrUGrNy_FZ1UNVTYtPN9
YhChAOFjjzegw-JkYXuzwtNom5wOnLnX-yqAWoMtBoh5FIdsRgaV
}

EntityColoring(ethereum)
!define ethereum(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, ethereum, ethereum)
!define ethereum(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, ethereum, ethereum)
!define ethereumParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, ethereum, ethereum)
!define ethereumParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, ethereum, ethereum)
