sprite $ethnio [64x64/16z] {
nTDRekiW20LG15I8CF_ftlEgXeQqzkkkl_FOMxG5RXIgJKI_YFHA1Jw1tFM9L8HDr3Kbl3C5YzwhxnfefLF2y49f-bP7k8EYEtZ_vha6cQhRMXxVr_VY-mMi
6P7UHJQkG4csCI6MKX2f9XqLbYAN-HZB6JLzXZ2rvpIL2smQoUtqjQHORcuWiPVA3Upf3JY9RnNqTNo8RnVWzVZVE3wR1NBv4eJAUieISVt2JASEqhC2W76v
5wuJqngZFQrorUaOl0wl0SsBeCGNx3DihY4UhEPsw5BA8_p5Qupd1JJ6QY2QQVE13tLAhg1kiw6o3llZaZnTCa1p-_BRqBjDNfFfam7OVWrLbSDjuYIV3J1y
DOoPzq5h_1J-EPqvRF9ZlLwErWCczlFoN_Dn_c6Vlb_C7svJciy_lqa___wGBQEVyXrV3Z2VvtmyPmz8-V79ytUq4zxRtrEUuR1fBI1o4b_hDuq2FHq0EOad
hmz0jhZYH1pkFdMtfGB04Nw1rmOcNDZSbW80pHOVX04HOH1E4_XIHbW2mbIwEWJVkiM2tRWhm1fWfs35r_5Vgftvg9ZY8yO57evOO9ADq2t6HvbvjCX79moe
3NSB69PgaRjfEss3pFJKuQpRj2h6eIAgmtoc9uL8xCh_s8KV1PwexVC3OVcyOCO3iKrQ85NDRKE7EtJOMuFXXMPlI86NK8RTKuAti0_B2S6MmZz3-5eeiw6r
mBv2JUSOGplVXVy1
}

EntityColoring(ethnio)
!define ethnio(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, ethnio, ethnio)
!define ethnio(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, ethnio, ethnio)
!define ethnioParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, ethnio, ethnio)
!define ethnioParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, ethnio, ethnio)
