sprite $eventbrite [64x12/16z] {
dOy5ZjW030J7j9F_lxZ2AX4KpYBJ4d-lkdjDh-6Vi4lxWfGsE_-A7--BPu_Id-FXYw_Jgya0INNCG79wh9enPnOsUtFfQ9gDLvIg6OKse-gXghi-EgeQegwE
waRLFfUA5vjpjMdjEBJMUDKwL9mpNLgjjHwiqJqruw5ZDkf6G5_vspiRb5BEFLKVlMdGTKlrfig_upNRTLunMvpQwC3k1__R_ni_fkZjqgX5-mH6eySN_wY6
DvvejEbe2aW667KX0IATfPFe5PU6X4gWJjFy0W
}

EntityColoring(eventbrite)
!define eventbrite(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, eventbrite, eventbrite)
!define eventbrite(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, eventbrite, eventbrite)
!define eventbriteParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, eventbrite, eventbrite)
!define eventbriteParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, eventbrite, eventbrite)
