sprite $eventbrite_icon [64x64/16z] {
bLU7clCW38kNuFrV-9-v3uXGMdJxMdaAx5mA7WMqlq2bstK2Y_fBxBtVtrf3-hTihx_SDd3_YVY67HXaif4VVMCXiuNt68hOP07svlmpT0X1phVeeWf9T6cW
pkWCV4K7wY_G6FKnzngQDK-y6_077S6YV2iY-jBYhTIjLWC-osQ25cai1Z15FyCl2SFgXwENykH8UxDDM9hEgHQvf-0PU0OGucW8sBC2qAeoZt2JNUZjdxqk
ae_RCj8eWn5lYCQ7b8Gl0MDV-tovTJ0dCC8lqQQX2mxDVTkx87hDdPqIon4BzUW6qas8g6C4Ybto5Nun9gVecnhVRiE8IHr0P-qvYcGZDTYrz3NejZlYsuZ_
c6ynxjBJ-3rgK8WVHswv_ldcLg6NEFmqETGi7NzGoFNWTkPZVtuigLB8QeoqjYq0-FnkAn4NzWaKqKTQomsSap5vVvNjrO_rBAtrI_omNOsGMCT7icgIBW1_
390uEmCyBrhdCcaKkKjQZ0JupNmRr4SwRo31dTPqSaLgyxVrWzU7QOQoMlJwq-9b_KjZDcW1vCG6AcOJJg-3saf0PKH45ZRdteIiDAXsPyyUeiVd1ZhHHHSK
lGwUlawVmB992wmjjQLtwPitUuRbxghlV8zfHFrbt3Rktn1s7S2pfeQb9Fy6
}

EntityColoring(eventbrite_icon)
!define eventbrite_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, eventbrite_icon, eventbrite_icon)
!define eventbrite_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, eventbrite_icon, eventbrite_icon)
!define eventbrite_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, eventbrite_icon, eventbrite_icon)
!define eventbrite_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, eventbrite_icon, eventbrite_icon)
