sprite $evergreen [64x13/16z] {
nL95bXr02Ao2RZJtFsy6lgsZKmkSXmBWzN1J_2QEnyBu--aBnsz0Dbrjw1q3LHL2G22gGsIjCaI9iNA3EChTrg73d01EPuZd5qTL6Zep8PKLyCvI7Vy4qOhi
BI_0S9V9BnBQ24SPYHQsH80sfZHf8Uu4MOVqbWUWEyQpFb6d55LnqLCvBoBfbILJdnC4YuojFsLX4Qwl-h0ge2x1Fkdmv6bwt88sN_M3_MFJL5JlU_vAWRG1
MUKeqIApok2EF59LUhu8pN5QOWStV-qV98TYo5BmBRxzIpxtN-ByZly3v7g47_mMVW8
}

EntityColoring(evergreen)
!define evergreen(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, evergreen, evergreen)
!define evergreen(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, evergreen, evergreen)
!define evergreenParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, evergreen, evergreen)
!define evergreenParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, evergreen, evergreen)
