sprite $evergreen_icon [64x64/16z] {
dPTNWiKW30C1svBlV-7jVOD4dduJCPCAZ4tcoWBPJQ9opN4dCq3spn2vJji1zaM8E6gJlGlJNST2or0x5Di5SmzNRQyGxAEmBkl9FitL0DKtWl_qlXNeQ_Sf
UUTzc3_xxDlXEhbtt1_2WJrZxjM-hW1xl7IRx_MGh-gaUmPKU2yGL7Wl08dN0g_3Qxmz8pLU2zIhliPh0NdClvzSYmBl1J8LtWkW5DuB41Bl1QZnNa3YlO36
Um6DzmAKU2z0YVS2a7WlK0hl1PWAxmMm5DuBrAJ0Uu4Oq7WjmFd___MDzmAucBmWSZM5eVVXQrfF8AcEw_7hPFw2MmAaxUiLmAJksnL8wBvVGk6HFgVxDyW-
Got_VBzE_cu0G7Nl_VzPN_nty7ZT3-3hVlFYjp398tYTxxxip_sk0ciEcLaKRQnXCvCxzXfdYU9_TCnn8ol1xsvjoyy
}

EntityColoring(evergreen_icon)
!define evergreen_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, evergreen_icon, evergreen_icon)
!define evergreen_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, evergreen_icon, evergreen_icon)
!define evergreen_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, evergreen_icon, evergreen_icon)
!define evergreen_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, evergreen_icon, evergreen_icon)
