sprite $fabric [64x49/16z] {
dLPP6hGW36jQn9Rxt_TVS9mfSJUla10awQSGe0hP1wpw91Um_zYJi1eHBSevNQs39L3yFpcY-OtZMG5J9o-mCphCjWgbirTCv_mHskc9pNo6CI2Y_cEtqEiF
o1PGeotay28NW1e1_Gx_5MQJEu1kB5Z4N22teIm08ZzKW3m6zBr0yGfAWnwUixrQVw-9Bg7Cqs8zSjmMpCjZknuBeFHDLOJ2FiIjq1rMjjOrZGR-HkOjrjMv
R-OTEdyBrMOzR4kBoY-fwEmVckj8hua-SIlHgp2W9V5qTHuKFtVH1dg83Yr9nYYDsgstWHnkdw3nweoTK0MHQxOuvRMwPIFBD-woUVA-DwDiFBlgi3XUp4IK
qZeDXy__Lv5dUrv4Vt8zyDwMZwPheDVPdhth67Tu99GKALq3axL1dLTletMapFb0hzqx5I8Q7vvGwN0HRfId3IhCj-_YzzL0atFUF6iElRSF6sFSkLGjR6Ss
VgxdcRtjV8bOlBC2UdYgdKxltesTGc2OUkS2pm5Bm6Cs2UWpTl7UWdSMC3bD_oSAMjT2sUx_q3dGsIblPayymAFH65CRSSgt21upWWSEDB6ZK9Pkd8-V_GeA
-ns-r7KwAmdV31AyqMmd3v1pg7lL0stTeVy5
}

EntityColoring(fabric)
!define fabric(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, fabric, fabric)
!define fabric(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, fabric, fabric)
!define fabricParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, fabric, fabric)
!define fabricParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, fabric, fabric)
