sprite $facebook [64x64/16z] {
xTD50WCW34JHe4c6-v-txbwcNlx-uKWojCxWMH8Q4OerAg2zh17czLitLJDp1-xNDGNPPBYJrmtkyKWYX9znngC8us72-Snvb-FqTW_Tas6HeUlqWZgMTLrU
SBIxGzpuZ4RvIdeT_XwuQjVVyNfGLuMDptMLeklRR8gaJwJFfA-aLz9RuxnpFe3p4TpxK_hzV___7txuuOS7wPtpo60yL0fw_8PF0G
}

EntityColoring(facebook)
!define facebook(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, facebook, facebook)
!define facebook(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, facebook, facebook)
!define facebookParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, facebook, facebook)
!define facebookParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, facebook, facebook)
