sprite $falcor [55x64/16z] {
dTPhpkiW38JXSB4DTF_xFQYZQ8G-MwPd_bPFUNjDdc15olDOUtvRKzriVgpyWAggWNsMtA8YQcPWU_EkjAiQsTvDQGKwM5fQ1UXWMMdf2aB6ZHgeFeO53AN5
wxCv1w73rkn_-dJCBmDqsPwTfNqZCBY8hQaiRRO961OpbXRTW0pp6JRQHZ90mBY8eHJ8Opj47GR8dP4DhtgwR0QiyprUP4Jd-BAuecHGFhFwdAi3ZCXX_JGi
1VAP54UX5CeR-jpL4Q4rYqym6ovQ2TCnF9Kp8oJAsG0akcN3R51TCnm8TCy8rwyC-_mFC-LNEsL4kXdSDJDJCC1BjX4OTi60oB2S0O5n2JDJdra0i2OUM-ar
kdGXutKsNnKvsDA2vsiXg4Vf5utwHKrKf4It75BUKh3PyKGeaFu7lfVqpbBqlTbOE_lKtcbx3p3qzQqugMSVXqSA-pYMie_38-p3ZjAcvWobx3idJSoV5Xxc
p4Su3Y_jdl75yOtCcLJdsvOnRIGipLW_X5FgCIcE0eoPrYTSZPYoprttcB8lMX4oJD6NhRwGR_hT6fbszgKh7Kp5wSjAtRwyLEA-Vm
}

EntityColoring(falcor)
!define falcor(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, falcor, falcor)
!define falcor(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, falcor, falcor)
!define falcorParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, falcor, falcor)
!define falcorParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, falcor, falcor)
