sprite $fastly [64x25/16z] {
fP87jYCn20Ix0QMz_u6N0Pdl7CjHeKPg7W3xMciA7a9VLm3clxXb-lI_nMzzMGSJl_YAnCpuZKzKb5zycMiAh9d4o5epbHT-7qVwqG0PMGd_-8W-oh4YTepq
TGJcOh2I0LsRz7iDt0_Ijnnqp2tEF9_hqe-UeDWOSdL-M8QUuYd_CTr9jlGPtxVrspy2eAMOFWyT1wtENqruwzVMUQG--PeFbKQcttOylV7Hoz0hdrEm_IfW
k_R3i2Fmn9KFedn8pnBpsWzLQblb7vNVaD12lVPjjmdBp-js4UbvPn31tBwT-rp123sEOCuLuiDXgZrYHHlEy8MesYYS5SoyHw6iloFoEjHiF4VIkV31_jUG
YZwtJa3Ylrhv6DLU5cZcKbD2VCmO-L1E2oRWtbczzpKI5_aEYhRrm_6w0iMNMEY6N_mXDVmF
}

EntityColoring(fastly)
!define fastly(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, fastly, fastly)
!define fastly(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, fastly, fastly)
!define fastlyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, fastly, fastly)
!define fastlyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, fastly, fastly)
