sprite $fastlane [64x62/16z] {
dLO7bWKX21iwtl_2Enf_rtrgjfT02F27wn-8PodXV1r1eW0P9n4ionEf-_JA2rErF0aWUPC4tslzVhE43mfN6pVJ8pkRrI-wAy2H42PGasERylLMKHgynzi0
v3luIPTc7l2Z0FlZ4wrUBm2Ql-yVPm6SziSd5LDKseViyj5n4cLgPMorJnDz__YH_yjdVgFxr1BcUqAEznqYLXL-PtiqWCAZWkrf8tj-xRG6u0AnGyC5KH48
I7xHJPW5sYVRJj4uxTEDyX0fDJE_iioTifxMg3OckWAFS7epEYV3yXDTwmyjVMsqPLftUG9KbpKvCtKzOirsWgU8_XzKQhFDLB0buH6AJLcTChO6xXL4IDtN
XbmQJl3lhFpWqmxVFlZG7-3xVdwDy3wppTlT-ZcQ0FPCJD6YW8V_by712xaN-K9zWEGYhmeQcvPYa9czvgzARmjavcuhV85tZ_b7063LVyRmfdH56XsyB9-H
lODOpJp25kNV2FqzMC8NvO_GEi5ByYUm25sL3-mN0Fc71K0-NUS5GFvv0P1_N00P-AS525Rtk01Hiua35BBI0Pufi58C1T2qUYPOQ3Gy-Rm_3NLYBXxCD1J0
xKwh-cFYOU011HD_6rjAFay19qJwG05aF8FMGbi0jv8oWOs7oDxp1ytvEkRBpN-gDjpEfa-8Q05kvIFzXD3YAF_odwUX8Zr6O6GlRWDHGJj-7kRiE7HqE87o
VZ9oGkaJ8gzl9plaprTqqg-hczHCtkXwJGSam-FdMKvM8Kmi1lfiG86VuadjXVc2I4pFA7dIvV_rz73baRgs-ofVoVy
}

EntityColoring(fastlane)
!define fastlane(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, fastlane, fastlane)
!define fastlane(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, fastlane, fastlane)
!define fastlaneParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, fastlane, fastlane)
!define fastlaneParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, fastlane, fastlane)
