sprite $figma [43x64/16z] {
pTDhpkim28JXmS2G_M-uznPPcXvnlllx-scJs81RvgoZAtQPRkYYNLDsZaV6HfeoxIxha7HlNMbBJVj_unXH1go6b1R7b0R7D6jCUNmBhJdDCSrLK-hWa2Qm
QaONW1ZH48EjQU2Ubw1w3M1H_w2zN0BJxyLLnWPNrbRYckVhy5yo6ZMr55-L9UZYLZwaeDQghPUYIN5U53IMMaClKQQWdefILhA_ILF0WxBvOGKaTK5jVB7n
RboM6XSO1OLppt0h1Tt_DmsFd5N7JW6B5tIvNKq1Mv4Plh1BLiU0gE68UaD1XHnGOqrfrfGQnpHgJFajjEQKoiufVNu2DZxN18P_ouNX333nhaNn-8bbIvK5
jtEQOBhXVMS
}

EntityColoring(figma)
!define figma(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, figma, figma)
!define figma(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, figma, figma)
!define figmaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, figma, figma)
!define figmaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, figma, figma)
