sprite $firebase [47x64/16z] {
bTM7ZiGm20JG62Uuc___sgjan9L5PDIkl8m8OhM7XYSV3x9aKrpJ5cbnVeeygMVvI0_p9f_9KJw--8WlvYjdJAVzpMUCPz5S-kRZylYbMkjf-rkjSeVlFJM7
T_2Llif5jhFLAKYv7-vs5PH-BqQpKzRVij4v6qvYKk_9XjMMNvOFJ7OQJOONoql5Wz0VIRyFJ0qpwY_Ll_YqvSoedz0_fbc2T6PJpz26quRUvPFZNGgquQSj
_yfG3MmvGs_-Ja4tGkdlOXfh1ZG2Fcmvwg5_JxDikQPNQF1V1xQOaHCC-Vt9gwwcNmUsN8tLL9Hx6glH-vw-nZHJonqDZiLCNuEJtWUqmt5WmzDsDNfEdjOa
7DY0TaBtOdQ1ThaUM8Tsev-y7TEaY-a1hQjXBOVsLrD5MaJhD4CMT80lQQe3ET9Uq06UfLrXdHClT4TuhVb1g9oFU7wM8_e0JfBY65zMaVj2KkIwR58G8-GF
xJxWO-UTq-4a1J6IWXWX31qClSJl
}

EntityColoring(firebase)
!define firebase(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, firebase, firebase)
!define firebase(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, firebase, firebase)
!define firebaseParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, firebase, firebase)
!define firebaseParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, firebase, firebase)
