sprite $flask [50x64/16z] {
nTL7bYCv34LH67gOl__TTZ8KPLDgIgDw4zbx2CZIRhH1d-Nk7mhDJmK7FEoJ8m8xVLyq0Aw6iFAcA43uc968IcyaBG3uh6G0lF1HE814PbItcAFsULY8FR6D
snJgZMa2a-bruW1yjAOYsvVPkyUarrckZaMpizO-pSs9QEENeHlNnJ8TI5UYTjey9dfB3o0QCL7f9z7nQ8rh4dQNW-04CdqrUco-bjAX1I01ezwte5fEecsG
LUhSGgZLaz3Co4xLLgLTQtGg0CHqk-Sl_IXM0AvMf2h9a3cEeYz3TEyoGoXAiwFGcC0Qqom7zLec7ual88V3TJ-NXnv5ym1iP7jxTTuYsdAXgqd7kWCON5if
GgJhF1ORy5Wbbn3RkuSWLo0NqKXvun03qCaGIiHzqh5c0JXFOEubQZyJcmaiSG2DI4Ox2d43a0wBFLAnSYJrciipSy_Lgfst7zLXfRgPhstYJ6Pp8840K8ai
wqdm6W5i4MEJaKkEf7TSkUyrP5Xdkklj-IwM6oHmZpHpwlqvclIqcaXS-MGfLPjvpAgEO7gUJBUuJS3NgjeDS3EBDTochMz6bysPYPsPPzgwXECUcBwdlVUn
BF6zNBtGirZRMEvcmzmCkunPH9d-BnOjfRNUHwygJFykgIzdR7HNL4MlX6HaldX-p-JV_t2-0ZfL89wBahZ4rOJpLmsLgC1VZVkRgF27B4ICe1VbDx7xJF2d
egu_1AlI8odAFmJpBQArvkCt8JCIplkQPsJAGx1bPYXL82BHVmbEL38q8h9aAjdkCnHM-CTK_hjOZQXT8bA9Ybw2DFhlUzHVOiVp4WDOXNQ9WNZvwd8ppoqk
WhKt2cIYln0IMQ-fTZA0SGbHG9-BXMkFkfzEH0LsRzuHijT45hv51IhJWfVg26F54BvEq_kHg6BnbJ-8PaOiaW2iPdPY1p8daIGoxBeT_m4
}

EntityColoring(flask)
!define flask(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, flask, flask)
!define flask(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, flask, flask)
!define flaskParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, flask, flask)
!define flaskParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, flask, flask)
