sprite $fleep [64x21/16z] {
fP07biKW30FbAjt_n4lydEtzJveWRm0Rtdf56_w6Ks_W7nTelIDng1ja9RvZ7FP07Hg7amQYrJ_xlWFUVbBChD_w2PZxA_ze1ApgzkVt1fktmyFNfoF92Btn
X_6j9J7ka4XAlA9fy9dH6pypRfzIKpBq2IsvjpHJVViUoJV-WUk7502LDgMswfhQUjS_lFEhSlsKAfCgdx1B6b0lljSEtjM_liZZnePF_9G-z_VyTe1BEM7z
NeVl_Q0OwzDCOfYvWPhWiwINLEC4OFdQvtPlZjYxE1F12NtyeUsvVV7QxmiCrGbudN4wO7b2pVxiZcqwBzOl_8Aj_v1w2_rNUalzsG8C_8RaoqxcSL5IkXj-
XLsyNzBn2F4__Ga
}

EntityColoring(fleep)
!define fleep(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, fleep, fleep)
!define fleep(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, fleep, fleep)
!define fleepParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, fleep, fleep)
!define fleepParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, fleep, fleep)
