sprite $flowxo [64x46/16z] {
bPO7ikGW30MLdV3zhxkbJOoUlqjCJwZOZID0FIngdfWA4z3BwKRaNpPClhBLd-YoFksABDbi_eQjw7dMht0zIY54ZsjSHxG1ZYrnhhfVznZZlhOka7hYLHz9
1feZiEqV_jGpiB_wDeU7W8_fds31Wv0Y1cnyaBxoV9hW3082gDz7kJUA1-0R1cmKd0eC1y010T1tGgmUWDJ0NlMJmOOZo5Fw31oDdWWy0ngDZXYyongD3WY-
Y1gD3lY4Pc1P9qC_0-iwwSCdtHkzyGM6F-WhNnx7lw_xVn_2zO1LF_NaN0tuPEhh0Qu-fxuQmEUtw7q0XvUYhrt4-lvMFJX6OMlc3mET20Bsr2TCWJe4xjsO
9e8hG82UR31_c_opxJb_Wuw1-_34JEt7zSDGnq2pVb603e5k_IIEgPV0dKS_DaTm4yCQ4Se4U3wAPtJwEn8RsA1toBjjJ2lOYwwq25ip-DeED7oYOFU8sb_N
dl8l
}

EntityColoring(flowxo)
!define flowxo(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, flowxo, flowxo)
!define flowxo(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, flowxo, flowxo)
!define flowxoParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, flowxo, flowxo)
!define flowxoParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, flowxo, flowxo)
