sprite $floydhub [64x64/16z] {
jPU7alGm28DDaz__YVyg7vF1YSCLJRlRtK-0KXbtKWjW_X4GhZ8w4WlCg-2lBJJcLh0tj241n1zX8fiuriR7JtDcKOjtFVZyfp2fpemav5Gyz2PLkjlJv9Mk
3lxGkxt99-vmo3WfzWQU7qlWJX4oR6TWETVG-I1RlwrZ-KWUTn8MkmO5jhJucd3jLg-POBpdXoyW1vOEFpXl_cEZnKiUx64SliCF9yJoskD9oPe-HfktbK2m
V8Td0rX9ZD7dFSz6Q_Ci7F_RbpQV0x3zBiy1L5UCVVuVQfb-bnVC6Ho_ppE0Vo4K7bLXsrlPbjyAjq-B3OygE_3z-Ut7U4JLflzUVjBWKV7O7h-WyPLtARgx
YNREtyf3o-NVktvu5-Zpwyx30FiyxpmCeClpykNjky-pVQOeRPuF4FfubsVVQTJZIMa-2hky4Kgh5Y-BMLxeyR7AvtyTtgxNiyn9vXsl-SQIVjFUye9opZaD
-BKTSPH0qi0USTtVp88Pd6GWNWogRvKy_ChdiGN3qmfZXnL9SQYWkDyLnL3ignnrVUCoEsVsVboHkFUwcNk0R2vNHuUgfC-oG8LDHaFgwP5fLFq6
}

EntityColoring(floydhub)
!define floydhub(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, floydhub, floydhub)
!define floydhub(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, floydhub, floydhub)
!define floydhubParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, floydhub, floydhub)
!define floydhubParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, floydhub, floydhub)
