sprite $flutter [52x64/16z] {
xS_LWSGm303HCDlklziBqzn6oZ9u_fyWE2vAMVpvn1DFF8bUJZo9NxybZ5bql2LCMHB6fmcUqH0WcH39X4Wc4oA9Bf05aUJPVsI3GF8MWG1j2L1BW40cj10Y
a1Q1i8a0oGH8876-BLCH8864MKuK22KWPPqA1iTLjgwpSwXohT6YYJZJ6kLv4-cCTjD4NDCAzQQMJ4QDEc9DI_Iece0U9Sq2z0X4WT9hKFA5AArPzWS
}

EntityColoring(flutter)
!define flutter(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, flutter, flutter)
!define flutter(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, flutter, flutter)
!define flutterParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, flutter, flutter)
!define flutterParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, flutter, flutter)
