sprite $fomo [64x22/16z] {
dPC5Sa0X44D9ilU_SWNU_8KwpGYs4MoymQcgM8F1k4FgGMPV_wI3Z2jKLJI6ZD1bV6qCfQfypzS0r_PmKa6BZZwO7CrPu9emHobcikgSo6j8mpPxdrq-MnLW
1cGrwWlBcKyyewdjPQ3w22swYRgX6YOAjQfkbgHcOynjDjN1u5FRJGRwXZyz8ZgbxGX3qMfONo4O47lhiSm1KzjD45QeuxYMFNiqLqhjK5-VyAr2B7qF3qNm
JJAYujZvaih07VlcWu_nrIgSCFxUYb7_SD94wYKBMqiKhshwv3wVeeAr-lk1d7-OgEfNZqEgukF_udX2jlKqtqFfFFTu1G
}

EntityColoring(fomo)
!define fomo(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, fomo, fomo)
!define fomo(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, fomo, fomo)
!define fomoParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, fomo, fomo)
!define fomoParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, fomo, fomo)
