sprite $font_awesome [64x64/16z] {
xTT5OiGm44JHQggw_ua3mposEXozjRybRGHu4wK136nOQH3zFQV61K1rMAYbIXzhOYjs0CxX71j6ZN5iUMFu3Mf4DNisUrbl_Qh6y1kvoKiRh3VK6TQodk7O
yQHsoe5QqAVXZ2N52iERVDm_z2lwsSz-zhCtpwmCnnddejwJsc4QTYoeX_BsPqntZ-JYysF03-XdpqtFrei2gGOMjTX4zQHQ2Ah3uMh8rcj5sNg0bmDu1G
}

EntityColoring(font_awesome)
!define font_awesome(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, font_awesome, font_awesome)
!define font_awesome(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, font_awesome, font_awesome)
!define font_awesomeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, font_awesome, font_awesome)
!define font_awesomeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, font_awesome, font_awesome)
