sprite $forever [64x32/16z] {
XPK7akmm24IHR655kFzfVzW9QigOVPMSkaKQXhuaxajKPRQIoEEiSwdg6fpfHcwYNwJU7NZ2-twGfQf5c0pdKal34zBG6pqvzi3Q8UIb3dCRD7MGaruaaBi6
JLta7S7G1sO6kODaoCrZPIBg-iWWeYmQ6dGDA3QwrPYRyPDXxlh55PzCIl0vlyhvc51_rUE0IJhBlHzKrANIcxGDUiVJmI2GOytMsga09PHZqSHzJwUevRAl
lLP41ao6_Ai-I_WMudS3F4Gj_10_rC-H0-olYxv78PHZW31qmZ3hA0yD1cmPsGRl20h8lPsL1zQrwsPSfLnJ0Ldchd7X3lQBwD00EHBQkKMjaTpVhRPdCv27
-qsoDshtXdJrAT0lVtk61hpdPRhRUzFSzRz9BVYvkpCnCXcEhj7_8wMA3hFGZNmDUQtSAvD3Adszn1NS_m8
}

EntityColoring(forever)
!define forever(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, forever, forever)
!define forever(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, forever, forever)
!define foreverParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, forever, forever)
!define foreverParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, forever, forever)
