sprite $forestadmin_icon [64x64/16z] {
xTD5WiHG24NHXtm1il_jjf1sXvgqtKbLvCGPSL4h_b3__UVcRUfkKyXgABEzrrGX0CCBsfOA4vvKEVrclAemy8hNJR-8hw_p_LfBvT7B2qowlS3zAMKPspqg
hPJCOvlV5iK6GC94AHinH02CwEMK7okiwUtaz6GEjbLyScZ4EJvJcRpWPtAUUoWp0TN1Ou1468zHyUiHxWrUjY3qjS4xtYh6YvFJYYXvmjFKekOLZr7galS7
AtD7LlBhn9gsxaFprBnl_hSy0Io0DVtTrqFHz7TVZpHzZ7DYHjThSkoZwvDJDBrJUktwXSoEdWzDBj7rbDwFflV7Xz_o2m3jwFeO92jNDy-VAzi--o7-t__x
VPdtQm
}

EntityColoring(forestadmin_icon)
!define forestadmin_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, forestadmin_icon, forestadmin_icon)
!define forestadmin_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, forestadmin_icon, forestadmin_icon)
!define forestadmin_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, forestadmin_icon, forestadmin_icon)
!define forestadmin_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, forestadmin_icon, forestadmin_icon)
