sprite $forestadmin [64x16/16z] {
nSu5ZiGm44JHSdErS__phZh3mkNvGSEJl5_hXQ_rYxv_uBioFR_jQvZsjxt0ecxdBzBmcc6Ydl-1CwsxxoNTt5TF0R3MlCwFBE49UuHuOWa4Im6v-9fzSVUL
4gHhfnSj6B4DG2a5P4UmoPAqPXzJ09BxRBoRDj1UwCnowY80sT5X1Oyq9QZb2GxV2ewzUG5QbBDiPk9RnsUvqxaoKhL0Au-hNsi_-Lo0agf-VeA9rCjqQB3C
HG8XeOuOt_0d_xN6b-_Z9_xOny_yyJx_0G
}

EntityColoring(forestadmin)
!define forestadmin(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, forestadmin, forestadmin)
!define forestadmin(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, forestadmin, forestadmin)
!define forestadminParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, forestadmin, forestadmin)
!define forestadminParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, forestadmin, forestadmin)
