sprite $formkeep [58x64/16z] {
pPQ7SiCm34DDBPBG_tzlXzGXbr53klFTo7o-GmHVSEp8h81oEO9aGHz0GsvYz3SWoUjHHJ-1HYwnQ3UWEWDQeFbpZzXulhZLUBwuHOteYfjCG5zSQkWkm2aG
S1ytQq1S2zdGWu27o33NLCLynFBIg3RYkA1qfAS7dGyPzdp8YBtE23elC1xijv3gnaobZ1zlFbYpD-ctp9MD2RrgTWHCmtymnPePWMwj57GdGbVl91GJykVD
VAnem4mdKm8cdKpsctgSQ74pVYeo3Q98WmPj20rW2fhrhNAZY0cn8l1ROaAi23BCM1MGFfWIAi9gSkXGLhF0AT9YHheWnqG037EZOjlsL9x8-_j5xtHsRyfL
4mKNJIQzPYAPim9vJF2DVtkLMy0UtL23GCZCDXTePe45LfZPtu7b5nnYgFjr6rguDcvyLIV1_PqO6jOse3Skc0u7n0W4D7430KrS4z3j2dg7jct0Hm
}

EntityColoring(formkeep)
!define formkeep(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, formkeep, formkeep)
!define formkeep(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, formkeep, formkeep)
!define formkeepParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, formkeep, formkeep)
!define formkeepParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, formkeep, formkeep)
