sprite $fortran [64x64/16z] {
xTPLOWCn34LHY_Nsl-1owt79KLHkxlyPDE5FT2b6AMjw_NEURw9nZFWnegr_oCOiS2p3UE_1gr_plTVtFBpfeKsVJGyvmnlTDhz0rVEuBN5RDZsexiVHSzd7
ugNiRV5QzhHugtePY_UJlJzCkjKdt-PxFvj-tyK_nKmj7m3IkEDlawO7DRqsVJHzDZsewVdx_1m1XBCzyYOq_EmhlN-7b-cjUOobBC1KLM4UIyoYgj4yFyl5
dr2yMUB7TkaQ
}

EntityColoring(fortran)
!define fortran(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, fortran, fortran)
!define fortran(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, fortran, fortran)
!define fortranParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, fortran, fortran)
!define fortranParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, fortran, fortran)
