sprite $foundation [43x64/16z] {
lTG7ikCm30DG0oHLS__pheedIXnwecqVlnBptAqSjm5mV0ls8RRWGFiI0_vRUO3OW8Dkd-QnbIL_UAUG3QhJ9CEKjvenpNzoZiOMWF3EIqBAOKvMScg9nAUK
55DAkV2SSnbO7Me3bl0ybLnwr3dHK7hYAc2vr2BUNcijITyxZTbxJvYDdwNXS6BUmw9BuNMZX5oFTqznAUxfwo8WliaJm9F-uO1x2h4GGp2LXY2geOsc7cKg
qHf8ARV455GjbYpk_GkzbaBDsOwOUnjlRlKycXvc4WwExHh5LH8DXVb_8j84PXyN37AO58A559eP_yN4AyMWBLGrvVC_mSSD1eJ-XyAL0hnIgj6X61HVNgJd
yMKThuqUNSTVbD8qD-WOHxxJbiu8XtOvw0hkNiT5_O3xT5toTthyESN-2M1lhyfzAZiKdOgYPM-ldH8EEt-MLO5hWSk31KWCotT8JdhfffMNca8uBy-Wm_9L
ukQ9JFk-kIkn_hoKhiHpiKWFMnoBrR4-wfb7NlNuov2hdLtxaSTAuRENMgAKrkbvtI3jXLOzxnQ1saPeAhdK82sfpKlseOGGbBdcd6nUZAZ5b4kjKovRIyxH
T1xq5m
}

EntityColoring(foundation)
!define foundation(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, foundation, foundation)
!define foundation(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, foundation, foundation)
!define foundationParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, foundation, foundation)
!define foundationParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, foundation, foundation)
