sprite $framer [43x64/16z] {
ZTChWW814CJGy8U2cRh_RLUjwXQ9VZQVwl0MtffwYxTuYxTuYxTuYxTuox2AyX9KMRp5Mxp5Mxo5sNEdsJhVh_UiQu5PzxuRzRRULjX1fxqCQcs5DRI_ow3A
rjjwMs_hRRsjj_MstjRRsevhrtwp8mzz8TnNgctGDcWRX1rqsdDGQOEsGTkWRH1MKcx_DcWRj0tQ1cs3ja7ReAsct3zi_G4
}

EntityColoring(framer)
!define framer(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, framer, framer)
!define framer(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, framer, framer)
!define framerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, framer, framer)
!define framerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, framer, framer)
