sprite $framework7_icon [64x64/16z] {
tPVNjkim24G55Z3y_mVVaZ9B9qKsF9xzceKrOdRQ-8Bez00o4-5soAWWCv0_G9YEYnotuJSGyqgAYVmAJ4xFpYsOOuCuyepGxuTpkXL1_2B7-7M8LXahYaGD
6mk2B19ZnRC8fExDoaqXhY2oYD_6do5cBtsaZnlbz3T_BHDwktqvFQUiS_jWumcfTmzT6Z_gsxDrvSxunVHiGj2gZbLeGpnBOhCZNfBmLdg2Q8YtWePuAwXN
HthYaRPux_JJerSTYPvun5lY4LWhFOdZkdYUxvYW9nuV7BtgU2_hYSSdAthYiTNefMSjirSTzogeYaTqyCMQUBmP0zJIivSRiouUezs8idYCTaDHgewB9RCc
7gCHgud7tHElfUVbINIgM_6DUBjnubV52zdyzJfFx-CR6kVYuHWR37lnu3AsY6DJNUWuHGsVnOFhk8GenIl--rrnS3Q-_u7_2m
}

EntityColoring(framework7_icon)
!define framework7_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, framework7_icon, framework7_icon)
!define framework7_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, framework7_icon, framework7_icon)
!define framework7_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, framework7_icon, framework7_icon)
!define framework7_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, framework7_icon, framework7_icon)
