sprite $freedcamp_icon [64x57/16z] {
vLQ7qjuW3CDBVlytBX2iv7w-tTtgbYvOJ27ITaHc8gGpZOItWtHC-XoH0z6Qu2Hlwo7D3wBDyWEzBdrQaRVqb47FBoz1iJP09a5hg1Mz1aF765S321dBHoVQ
te16GjcTItiJbAdFZkuX1cQxU7YH3btJHgOsYOZLgXukYqIii_ArQx1fbiMGT1A_sIpJLL_0BTVms9QUHy5w0aBNdAJvVRqiag2UvDGNesmZoJ7iYrbe95my
MPwESqPHHOv4p89Ee8S9i3PR0eckMsLpbfECDZLa329ZJ8Hsia547Uchp19-BLic4SSZimZo636son29ShtHAysSvFY6AfFjqj4iKPPgAC9FblUkCdXOF4aZ
ONx9dQjCbJx9dsTwkURFHgXl6-WVfcNvHovhetzsE82GOclT7JRx6OHbpu9KL1qPWyZSCvXszXugTmoFWbTDLQL6vV2gCYqLWRblEh0KAfUomtUs5WOj0cy2
XejW86Inc1x6H1sReWZD4ld5Db7VWk6ocyMekfy_98bxPl7NyelL1kPVPIsNTCggbPjpzXoT8MR39DSjFM-Ge9vq9hexPh3elEoHY4acH8gCiY4KCvFfgN2h
LYrFIcJ8eoTDgzw-Nd-uMKpNteVECiTkIJrV4eyEgvUGf5CUoJRArIpx_rFRyaStFGzxoozjzZn_gFymlpZOu_oYVtPC__Zf5Lf9heCgwdNReBRyO9LVYexr
8r8YKTFs328Q2U7HXafx5vOmuPFu0Rp-dwnz1Zw9du47-Nlr-5wz_gzwvxNv4F5y-xy1
}

EntityColoring(freedcamp_icon)
!define freedcamp_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, freedcamp_icon, freedcamp_icon)
!define freedcamp_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, freedcamp_icon, freedcamp_icon)
!define freedcamp_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, freedcamp_icon, freedcamp_icon)
!define freedcamp_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, freedcamp_icon, freedcamp_icon)
