sprite $fsharp [64x61/16z] {
dTPBSWGX30JH0WdrtF_2_jiLCqI6rTJ-9R134c-4vjJnHYt56kVyaPfLuvX_-vgd_CUlUSX_VDKyulOr3xWz1vZRSu3vxYjkStiECBVd07Dx2307Zm7cZwKe
2Z3tGkFPLzxXAMdU2EmS0jtJRmM0Gw338o7Gv1S-eSNzXYsmMjn-3tIuFGUOstE0kJq6XfXldWBCxJa0VFCOUE4bQLpe5VMoUJtvQqfAz6EzSWqEs3CN13PF
d0Fsp3bW3zmV4mvaYqiJ0ecypEa6onvEXniua2tEWSMy5HZ8Um7a_S3EGKC0U3C0l1j81V1U83M9Su1zIfq0UEGSi6VE0Nlc7B1dpW5xu9s0VVIf0_RCnG5x
yvk1r0JU2wGcy5uWDTSnbo8r_-7l
}

EntityColoring(fsharp)
!define fsharp(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, fsharp, fsharp)
!define fsharp(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, fsharp, fsharp)
!define fsharpParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, fsharp, fsharp)
!define fsharpParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, fsharp, fsharp)
