sprite $fuchsia [64x57/16z] {
hLTNWgKm3CDTkV-1jxqOXpM4BQEVAOaKkG4vRi7gm1W321Cw_Whqamj4k9a7ViBuZzdi0FBCyXBoX-pRmqW2q7Uw3HWzA0UY2RSjlicLl5XGG2wcV-9gRwTl
8sgHBV31fNw2e4Uw5nbZ1PpF9O0Uw9Qs7QCXU2-Wv-c6SGix1QAnwvyKnNYm8F36JrECyOoiZivV2WRvdOum5HQrM2GdBq1NzzCHuMHhxI0j1PxxhX7ur8kJ
tJehLsZwvSlnDalumKsBS4fx6kZ7SsrfgBheD42r15_TnnszbZ4vLi5zWf6Ay1Q4rK2WXB7go_Dufe4yjEoNlDzpsmbqraYWYpfl-BBc5t4E7fTu73jW2S1H
rQirs_9zoR1cel5BYDxjNsCKyB44mYcz0oyLvEIFgDpWs8Bm9NpxclFbl-8dk-IV_oJ_SjVY0LgjxM1vYBlnqVfls_wr1n-p8MbAInlq7duSkZwdQFYoQA_j
EpH_6U1b_l5cW787OPH09Y1D-TluU-xCXc5uVpvrw7cacaSAMBrEKbPsmv_-6FMub65byDv1VxnID0EfETf72bdclCnnFOrakjBs-fji-BGVlPoVNsNsOW8k
7maMnnXsytoJuXD0AL00W2mAzTHmyZE2UjCsA67BhyydlX4e_zuRuio6RJwW8cUF-ZGs0MeAiCnC6R1qbl1Q976ifQXeXvNxD5IAu2KzecQcmYcVSif44dSV
6mBORdmJoszqtUERJtGT3Uct804OzSDLIg1zK3Q5KARYiWNWlRd0JtUt081mo_jN6C_uBZLz1ab-jzRzuN8rY7D2lmC
}

EntityColoring(fuchsia)
!define fuchsia(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, fuchsia, fuchsia)
!define fuchsia(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, fuchsia, fuchsia)
!define fuchsiaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, fuchsia, fuchsia)
!define fuchsiaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, fuchsia, fuchsia)
