sprite $galliumos [64x64/16z] {
fP9PbWCX30EXCSQw_u5dNtX9JKQFwBzK5jsrpbDLgMVmbLDwGZxdbEfS_i7h49_pYzUP_9Ul4_d6w-JXTbudyfsl0_dEgsnvJkBbovalKmwyLr3Rmn4lNyvy
sNBcLRQSUVbovkL-DUPv0SkP5yijdWioPnWyBiZHstkky7bjTFj93vlNDtwrFM7pjU56WRXWj9jqczUxljrbs7o1dWzWNfMztSVdbGqIQVEB-F4qdovVn5yp
q-Kx-SFcDOWVT83S1xW65Z1V0_I35eXJ7VHqWCHP7N0eq5zP5-0ZR5wLrmrD1NgGgXmRYmlqC1aHDtpuVCqTvuB7yXtd1OOS3iX_-GKuBV3blC2NymAI9zAy
m9Vp0b_E1RwS5x3SFu2_cb_0_wk_WEL-0J-Slu3b_W4izmlug_aBMEuVW78_yGe
}

EntityColoring(galliumos)
!define galliumos(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, galliumos, galliumos)
!define galliumos(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, galliumos, galliumos)
!define galliumosParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, galliumos, galliumos)
!define galliumosParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, galliumos, galliumos)
