sprite $gatsby [64x64/16z] {
fPS7eY8n243f9VU_xtQKk1Enl5_LuK52CWKE88b5v2yYN1dX7L0yVx7M_RShmOkmvoKX23CIUKOd0qUkV488F06jea-iT88J5FaAfn8aEs7AXByW5eliXHbS
eJtuiLkalJP_7XuojTNnIRYSctEiGAxKI28gJ5TP33gKXTwIMSic9UNjm0BZeNRKo1sZwd4refLb-G--w6HXk0bMGC5xTZhj7svZxIEeahHi1nuFmBrQhrU3
02kVLVgcuro302CBwkL86zmPfdZO29v_2AWN0xq-1C2UNlDbAaXQDp7Vn6yLso7z06ARIioLRyBSPWyztqMruZyJkBLMlYzO4MiG35Jy81ZuMh2-5CGe4Dg9
xF0e8DY9dZWH1y4Gpp09UdnRwruRSH8mN5unj7et2k8V6G3tRT_spo1O_qXlbmnh-tSI5DocZ-iVXHS5A_hm4RJUVLKWhNo_ctWIzFJON56gGT3pQBk2IVjW
5cXFx_MY2Xi4LQLjAQiOcmNUBy3Bs-6bUogmw-EbxP6pODtMoCrM-3zXF1C4Gx_4hiJ_DjCw2qAWkQhtXPJWD0VtvhQvQ5WMUYKe-7W3wbaudGHezrMCS1Ia
qPK0DOkQfyw-JlXHG9P5xrF7icD2M3URRf4DHxX4SkLEH3woqjvu05hZuy-Eve0X7AaUdN664R8XUWJ5zh6lUWPv6MJroCADJy4_0G
}

EntityColoring(gatsby)
!define gatsby(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gatsby, gatsby)
!define gatsby(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gatsby, gatsby)
!define gatsbyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gatsby, gatsby)
!define gatsbyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gatsby, gatsby)
