sprite $geekbot [58x64/16z] {
dTU9ZgiW5CPnpiRE-x_kXNwfvNWrjVEVVUGNb4XDmqriAPTMIvJmKvpAgirgvXyWvGBvgj1pAMMNLPvBzf9_aDb9eQUEEUuogpwon3FPP3MToPC9bzL3rgWA
-XqkoPfAgTEL1H5zdn69Mee6z8qIu2SznJTGpb0SkxzOLS0xYUW2cZ1zbGRg8QRy9a4TD77AIKyT53FbPz9JDZDvB4qEIFfOWj9saMRCz5ZgTgwclqXZI8L4
pwGUK_ugCQd-HIeM5iMKSiufHbFnUmM7IYauR8RbbOLgwtqSzLwB2IQrL4x7MbrOSB9jz5b9SPRo73f7j1XcgQtHhUIKNeVwRDJNwPBDwfHDZXk39BOvFCpQ
71S5hp4qlnHoHcoprFieKnm5Rf1rL2RUMfEaPLYmEdqao3UDeq561pcFZZN2AglKixItD3x9QawcYpaf4BSHppBRbehrGguoCh7g_E5bxT5BRSr1xbrPL6Dl
3aglvgHA7XgsaqqZu-uxBP6DV9OsSlX0xKqWhNVTQEdnG90gPQIrrLzVshinfARHZ65PyYZsdvoq9LkpnB86GowwxakRnTn6rMrLGOKvrewRkcNPTvcLFd2W
9lr8VaiCZSScWqGMOqfui1rIo43b-Sv670pfhvA2_arg2EmbtKaH9zTktYLXQx_v6-60xFBrZqs6BIBYIMO1yIOLJnKtvrr-JWmKo2-KnB_6hyXMpEZ6iNiY
KK1YxYb8_p4uG2oiVmnk4Msh99SFGKHwVI-epvyhukjxznhwfM35jRhamk4Yz-HYoyWJY1C6_kYT8VNGKrDJbLSWM_uQ_GhFL2n6kyYjwjN52hFebPDm7maa
bkV1XDv2WYCMU_w-mqTmJp1zL_y
}

EntityColoring(geekbot)
!define geekbot(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, geekbot, geekbot)
!define geekbot(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, geekbot, geekbot)
!define geekbotParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, geekbot, geekbot)
!define geekbotParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, geekbot, geekbot)
