sprite $getyourguide [64x51/16z] {
jPO7cYKX28GjalU_yRPeZNo-iJVNHfJVHa37zaYZzt1jAQUicHVZAea-5JBCw3J7Voc_utrBhdpSy7Ho4OtqIZjiI9kEln-bSP4-s9oqtXt9MmrFLTgBOiUc
M0Dspbz5zmFm8Vm6ZvZoahyPjZxwEIyxpGSlZtw13_8x_xyKF-S18Vzx-JFMpxxdbRM_20Cp4V-8Nz_tJscdOl4q6R-tNrf0vS97UnSi8WmD6RFQakxz_qVX
qUT_HVPW_H-z0FA-ExNFocau8iyYyyT2n_8Iwr_p-CZKMCOpeUJveLXuitf0bgSLGfFl-ixtsk7ewQYkCXAETC79Sm70-RackMzFTp0ifkFaynzmc-K8f4b-
ntNonh2nUSJkD-LDJzU3HmmCeb6-f5_PKcMtSQTd_CBwvNYzmzaDbSTPVwHj5UUYP1YLt_TltFp1ivkub1DZ8wJjQGHEdXi8QGsP4x2CR2z6A9Vur_6Fc1db
GEG0qwVhEtRoB6QAynAqfIQ8zQDFq61p1mVWQJiucpF2J9MpJOcgLXlLHhq7_et48y9a6cOc--RZ_IUM4Yp2g98WB-UgdfzWKeOCBKqg4q6Xyix-wKA0UQry
zhwgiS87dyiZ0NVF1J1vJsdr3nmyxpVUdXDiDDFhUB-yyyqPJbpUBvVu2GYNwpOaauT7ogxv8u-St-KutY__dB_7FzF_tVl5wuLXx_apdaDBdcNaZuKp_thM
3mDJyFqokL3X_LFwnzHYMjDC7U-NZ92oPMa2rD6_JUajoIT2F8seWACTV9DrQS9ZPaxdctxc9y9oQCXvo3Me7m
}

EntityColoring(getyourguide)
!define getyourguide(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, getyourguide, getyourguide)
!define getyourguide(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, getyourguide, getyourguide)
!define getyourguideParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, getyourguide, getyourguide)
!define getyourguideParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, getyourguide, getyourguide)
