sprite $ghost [64x21/16z] {
fPC7ikGm20KVADE-_tct9CRxS-v95AZ7zYj97pDMrnymhl75YYzyFlU3yXVVsRubkz0jdjBIlzjlgtByE0nvHCvz0glESAxH0eQTRkok9FM06DONh3K2OFka
xzi6MCx5OKg5f4kJJJmwuGUJtBKPXCaMQ-TFCr_WYYkA-OJYqCrAiJgWrpS9Bhga2YU_B4k5bedEacKENEhZfZ_yAQaJjr-WTl0SxbHOpRQV-N6Jpz-WbmRZ
kJ_W32UeicctFrvU_yvdsNl-8YHhaukI_biMO_GgFVShd4wmfEprXv_fs_x9L7B9Iz-umgK1LSKatyNvKmiYcce4SU-gM6lsykJdMbR0t6h42Mid6IlYuKVw
MYJTuibNtUteaf_vT4dzv7JlTajzCDozJE9kFGPUN0VpOdVbxnmwpnZGR_0yBoKO-XMJ36YPVaSFO3Lzaty
}

EntityColoring(ghost)
!define ghost(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, ghost, ghost)
!define ghost(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, ghost, ghost)
!define ghostParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, ghost, ghost)
!define ghostParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, ghost, ghost)
