sprite $giantswarm [64x57/16z] {
ZPVPmgmW38Ffcdd_9pw_78CmMiRlneMcJPZLjYBkqaeaqzgM0AAL992wapk0zDqgSkFF4gX7Q5-blxe0MOG7G7zbGUUn8hXQxM6Whc0sr04zCKWfp76vwi-C
qJNc7cvwL0TNaiihaYicdeFGSH7zxBw7qHVPfaQQvO4-o9qd9TsudeqcR7Yot6BCkco1ZgLz04wLMBP0va3no_veO5FuEEKMkSULxvRCwpI4s_2Rq5LbFD78
Dp2vyTKOVTx2UKSdYT7kDPDXYxITVDz08ipQd3rUD-WokLvrlZPYKMfSPHHOcx3nkjGlH9YmmECqG8A9M52yxCHN0nOPl2pUXsm_3IokQB6ICsB8f0zlN_Yp
UJ8xblbYkacukkfpZ3Hym7UHNvkC3q6x4VZagFmhCPw1NkNI-uEUNHUz7XgaiUG_aDzwP-e-DNepwlEuy47lbfFUq6kcRbW2-B8RwFaeeMis4yU7Iw3WhbUS
9ba8e_rh0tAABpQGCxuraXnfd-a5Q8bo-x3SDXfmm6LgM-cTyQTA7B7eQSb_Vs-2spWRY7jLv_vt93b-a0zrJZtQId3yCWjO6mW6_jKNTq-AWv3Pv60U9i4_
SKyDOCj_kNi3oxjyLOIfMk2BC15HptkUsTahKbk1nWkrjGrYiP4YNTjF9F68jvSK5lIjtfxTjzSy1h3tUiMTUAtcV_7mo3-YVcofiRmcUZszHeA99Qltp1wD
FBFirFy
}

EntityColoring(giantswarm)
!define giantswarm(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, giantswarm, giantswarm)
!define giantswarm(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, giantswarm, giantswarm)
!define giantswarmParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, giantswarm, giantswarm)
!define giantswarmParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, giantswarm, giantswarm)
