sprite $gitboard [64x62/16z] {
lPVf5YCh28JZXaBL-x_klJDPK7kpCnk_-XW-AS1uy75Y8Kip0mcp9Za-lh4a2ZuDU7t09Ds4Gtc6XJOfEQLSf2hmt2BSeENfMjFi6uk2H5tbKPvUXrAZ68bB
3KclFRAHTbu70L73IX_goM_DDx-ms4WzYX6KR66x-DFsAYtkSTi8YwKgdcOwzpxx1dFqCfu1nNX-CFKaxJTeH9dF0A6rv9HIBjL0egMk3RGfhKhAr2Le2RlU
rp0eQ7D6hUy5eiL5xmieO-rSJb1tEpZPA5qnul3z8QAtuS2I4HxLg3sPsfMm7A4k3jAfuhN_g5TNUBv1zfRPUoClXP0o0rN3ReFeJImUVkwAMm3pjE2K2mWz
UwM55Vz84hm2FyjUlFZPjvxvKpFMfueU_l4LBxH1VWJpRTuJIEuXjF0T_m15l1_gnR_DAxNHkkktVANvCOv0_9Olf7rKPo1yooVGor-yUr_nVkA5-kzvhlMR
xgqbZz_hHnpoXsREB_kdRHSTDE_VylpKiZE_9eGGlpsKzHvVsMy-JK3__zpZ-nLcbF7_Yto75z2SICEjeTGxV1kE3C9uVv5vpGk6YhNf_ZHQMF8zV0Bpzlwk
AxxIywsqDoM-mdBD2ppT-E6K29u1yXKlnY4OmbPsDA8SyOwxwo2x4Qclefxn5UnthD92zx97Lq1DHxmesUihOwOPh8wepyaZBmqaoa2qi_cfW4JBJtLWTPeQ
pmQmUN285IIXKZBOQbCZIIlJi1ddHi-5ZzN0qQ1v-DMyu8SR-1lcfn6mLk9ZnlFL0EmMOaefXdanm_7P-TRy7YfElGHNhm-VGZLS38YqidhVh5vV9l4ujlfa
V6pUUsZPk8NyMb_KnsTrmfgKzBGirS3-0bXRUW44IBo_MWatwVxy8VcMaixW_m4
}

EntityColoring(gitboard)
!define gitboard(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gitboard, gitboard)
!define gitboard(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gitboard, gitboard)
!define gitboardParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gitboard, gitboard)
!define gitboardParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gitboard, gitboard)
