sprite $github_copilot [64x52/16z] {
xPRPmgCW34O9X1tolV_JpjB1fXhzjVTpxWmS4jRMNK0Xjp45WCnMcDmtK6o27TAJVshx8ZX1MdYKMsr3kwyXJlo0v1kzuePExXhgk6M6Qtq0c3Nn7_BOIIKo
Soe3W5mEq87ERYEftdHlAZ3zvTppVhZ5_8ooO9pglENHmABimaa3EmQmBuna-T7jc11lzGXJr-O7Cyzg_MwZS_dUP18oXnv0Ddvavddq0u1qzBCDae1UwyBM
xwPywtiWnHWdalM5J2vJVzBZO_Srs35HRKc0JHQXjUvYmuHaJf7ZUQadkOhPwBXvV9pPjBbSEznDghhn0q3NbjNL7DuNBNgYi9xFydaFUWf4dekSh0c5YJUo
UkWKaxOeaTp2Du5bHXq_35Xay3zTSm_c9kkvF-pPYeyOgex0kitlDQN07CWPD5vq0AzVkajt13MwOoZfcU-Xb04bFlG5vx1JF9D-40Udq0C_2-Jz6IPGllBz
xeWERNpeytP4jN_wxszywRkVyjTJdoQ0_ldWYJ_rfsjdllDjLDBNSVJWplpXdKkY_Ytgwmlbk_xEFu6tsbS-BQ7u1zdVdUaZMF12QhZxRphNp0yTGyDgoFuw
TTV7rH0w5gCmsURSPREJEoNeGowZ9WxqmdCiBtUpwNPw2tc1Jtfy_DVVCajmzr2i4mOPMULRGgf3D6zVAshv3G
}

EntityColoring(github_copilot)
!define github_copilot(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, github_copilot, github_copilot)
!define github_copilot(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, github_copilot, github_copilot)
!define github_copilotParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, github_copilot, github_copilot)
!define github_copilotParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, github_copilot, github_copilot)
