sprite $github_octocat [63x64/16z] {
xPK7akGW3011WOpr_z-UvC5pR09VZZt956e915lhNa9o57RlGhaVxDPaKLfmR-0cIjdeJKuQEk2OQskjviY0LKxwslQ73BfC7Cy7lzEN7F0ZTTSt-hRpI_gs
yslojlWQNjWeM_f2BxA7LyUsPdrlQQNjLnzbq7AAAULIQwirwo2ctBSt9us006_m075i3TVwGV0-lD6Z65RR-ZY9OvnkwCsMweZSR7i66tTHODdvPE6SqkHx
5rFo7Y0l_-JXMhjFASL9n_H8bzRNhYzq7dfzNHE8Y8FHhiL73PzqIuTZyIKOh8vrb9bGvvtt7Z1OTjCXHXrVM2-2PQjsvz7osImIytaaH8434vFE7sZnYdaO
yT4xxop-qEn85ir4O3r4y-pf13GWcp1gOp3z6gVfodgup1bIFy854X32XSq5D-F1lGAxIC5B3o4yzJ3iDJuTSXIpPZ1Ks_TAP7xi198TO6ybfvDSMXTDIMv9
RYN0Q678LJxJSaJlTaGfwHd5avxS3S25eyHh83FazcZXslDeRfAPwcw1KcsRtaxffC__cFTKQIMNLB8rp0vQFtOESBEyXlV3QfewFlTrHrqkQAJWVbztFjJU
UrtfU_pnE-Zyo_IWUXo7Xr_Y0h1CUjTV0EzloQ1W4sccawb5f1Ce_ewCo8S9MQI2VLao2O2uJQ2oGgL4vBEcgH53AG4DWArjlf9w8Hjc_LNmmR8-u81OEHqY
Dd00iArkcCrCbiSWt5OV_gmpqlZTszUPpphHupFaOMyIm7iwJF8k0rglrIFzdC_3lOk_Tl6sx7_-yma
}

EntityColoring(github_octocat)
!define github_octocat(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, github_octocat, github_octocat)
!define github_octocat(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, github_octocat, github_octocat)
!define github_octocatParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, github_octocat, github_octocat)
!define github_octocatParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, github_octocat, github_octocat)
