sprite $github_actions [64x64/16z] {
fLQ7TXmn20oT___YXDES7aOkAmTNSHg6llldBMAHcM62yvrev5j2wHRDiP29lt99NY2NeYNnEkWjt7aVsUyCS6RQOL0UumDmvcuWwBdtNe57PcmBdcdFwGjc
MM9WfSnu1fTC1sEqqldJ31WkUWP9MN22MNlgFW7_psrxkq3nC834FLz_-Pt6N-4HkVuMZmZ0Vnq_nj0G_st-L-U7xFnVrj_HGTliJVyL66C8z-cY_r4u7Vr_
Ct-aIdVp1v7R-P-Yw7e8-MyMM1hsdmNW5oA5oIXf-rSi8jnuN8PUgQcextyZs8Gu3Iw8VTHxONs5WPZWK3GN3FeS-hMpw4DEXU1PS8Sxl_I9-mSUErrRFMBg
iN6zu_7PsN-nso5wQGZwXa-TwrTSYjL1t_MOlOx7qrStlHHYBmdTz1BGVyIZ3ruxY8tVlMsh5D3hrll0Etb2k3QOOJGqjr2HAlG3Nz6mENYMANjNBUBKd_Wb
2kzmRSJVz2U-vzzZNPlvTy2F_FlOF_H5_MdMV-Bl-m_uH_qle_ydlizVtinVTuTlvd_YR_VFnD_B_-DvuadCtUGaOb4H-e6V38aA7LRLIbHdOY9Zflai0EiB
gsgcmpNFv0uFOwArbgd3bOc8NnQELu7UcmH8DBsQoIV_p-reW6m338eE8JMbuK3gNELuHTW8w8Qr_dGuttu2vdW0rDQrCHss1fkbA8NUcHM1mnFVDR7t9saL
wEMnhREPZMScyEUJkFYqo4Ibuq_-KuWDUHmlcIIc_2CUUt8UP_xFuza94DydXGERlfrc9qWhIX0ywHKGE-aR1lk97ROsXk7ypERP2UuU2JXaZP-i0UIVNkho
NBEY1lcSVIwGqAaNAm7vNm
}

EntityColoring(github_actions)
!define github_actions(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, github_actions, github_actions)
!define github_actions(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, github_actions, github_actions)
!define github_actionsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, github_actions, github_actions)
!define github_actionsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, github_actions, github_actions)
