sprite $gitlab [64x59/16z] {
ZPHPakn020F7DaBK_G_y5fi8JHEK6xuHbQbUVZJmusSmkxqpmbvpsaDxDXOdUTliSQru5z3UsM6jDH4uj5Vnr_8H_bfiiGO2sclm9m97xdLOhK2_nmPh9C1e
zyx8_3N0bq31wWJwlM23Fn1mxJLOlK2_Pot-2X_WIrIj2co0hprX3GIQFM4D1AvO6gzOEV62hxm4XFKcqEy9Vo9mTNl2by04Nm97bB6pdoYJ0YTO9lefMvxv
ovp-UnYhcxBaiApFK0wq-Q1_3CoE6zzG3x3Db-SDTZtuW85V1LZe0RF41qe5iSMNF83_0eS1g0PymLSSTjtuEY21LtmYGtRZvu6jWF3LNOQE1n-r0cxnHNyB
tFWvphq0kpYGzAf00ZjynTyEiC5NTqeVdmUu4Q3eeJ4x_t-0XgR3AFYT_9K_06iCMF4Lr-FF75SzK0KeUKZzIIU23aYWujDDx9z_hMQr0bPyqOjT8mTd5Q3Y
bRqwg096nS-uYRrnq07brLtFBWU3laOKlhg3NMBl7DGXG_WfltzSNmKPAA-u7dz1o0CK_YFV5TVNQ900KrxixwD_z4Zycxvdtpiu7u6uuoRscOF1oNZmOMDs
EHXkWI1XvKEVEZZlBz_uyVfLSCQYDyLD4Jp2qHGthf61Xdq-XY_iVm4
}

EntityColoring(gitlab)
!define gitlab(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gitlab, gitlab)
!define gitlab(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gitlab, gitlab)
!define gitlabParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gitlab, gitlab)
!define gitlabParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gitlab, gitlab)
