sprite $gitup [64x64/16z] {
xTT50iDG20HGtlqFNPTTXQacpFv5la8z7TKC730DsVi6D7-2vY10DHBAPqKueJ9-LIhrNuqKVjkBVPBl--z_-Cedm4p0J43cPm9c1yq4JX7mlyM7K0dVAUnJ
F25xkGE5lP7qOyM_YGOCimK
}

EntityColoring(gitup)
!define gitup(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gitup, gitup)
!define gitup(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gitup, gitup)
!define gitupParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gitup, gitup)
!define gitupParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gitup, gitup)
