sprite $gleam [64x64/16z] {
ZT9PUiCm3CHWI-Gmzpznr-p-q4BlFpHMSfnE3Pvzu7dmHXx54_AbE7l7CT2Air-6iu_Y7DY6iu_Y72Z5sI_3ET2Aiz-6iu_Y72Z3sMSPpe5MdFqod7tKzHpO
W5TFLJSa_hj-zrmkzNsWyEVhLRxqrSC8VhtLywtl7aR0_9qhldegNFs6gq_-kz0d7xhwuN74wrz_rVLgz8yH3xyUmxy1U1Wnqoy_5tWSCRCVRuQUHqnERmOU
2drwC_1m0jhw7da_3_W-xCK0A4YVkHxmvWCuKUe3k51g02TA3O22z9dp0KyVW8Lo7u25SWFeED_eSsmrWFWwLA2Pgq0Zbu40ju46hWC1RWCDt0Owm6qWm6sW
WUj0WDj00xU13d0T06u33Lm70jm66hWEvCm_0G
}

EntityColoring(gleam)
!define gleam(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gleam, gleam)
!define gleam(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gleam, gleam)
!define gleamParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gleam, gleam)
!define gleamParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gleam, gleam)
