sprite $glitch [64x20/16z] {
tP855jWW343ZWT2I-zzsX9Uvx_b-Y_Dn-3z0f08H_XwR04V_E0p25uXPDR0WC5U7ppCATqxNYOxVuESH-CtChG1F2cKYlYz18_d25xHF1nRkLRovR6PI-UW6
aFcjZomNLVb4PSlNssMzSltX69bh08vdIVcobcBtLnEzLA7zaHEANl-cdRdNAPnKEI-r0YriNbm908dBdpa0nfpQFk1E1ii7U1r_2r_VuoDhnT4BqJj_b7BY
zc4ddThH-wyoy8mPCQQwcVau9HERCUx-Dm96pkzzBl-k9oAcnnXUcUccFkCWnySt7nlvbU_CkTbpS5u_LlZq4tciImmxsQ1Fz__b_7K1C3BpfPvVPynHI_0J
6ZKtWWBL69Y0kD-Vo8d9502hV89eOUPzSmt27y9IgFNz_xNVB_2JodZh2FwACllL_niaya_o1m
}

EntityColoring(glitch)
!define glitch(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, glitch, glitch)
!define glitch(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, glitch, glitch)
!define glitchParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, glitch, glitch)
!define glitchParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, glitch, glitch)
