sprite $gnome_icon [52x64/16z] {
bTM9pgmm20LWGDlQZVF-RtjZ_cQ6Nh6ENpQt4oXkzBEGkm8zo--9Xa5tyd7CEPZTWYybrwu0SD303HPvDloHiL-npjXhuj_kWUUCO3Z6xgnDwqv2fttE5CmY
VKG5TADp2qCwzrWnwMPKewxD1BFdbHdZF0i5sBbbJ2fzi7xRsQR5DbWg9eC_-TpfjeiEQoTZr2dVTfIlcKXMDHaPRTgCFKHxj0FET4eZVIhNAdbiizh3iHuq
XCjBS7o66iUiZRbheK7dbJUwugpGOWO6CwAaRICF2piZtkc5R8Ouusq_2T-zaWTP4dBh6BJbm3Gv_iz8QlXVJyue8msXmjM4hFnzMcF7dSPaRMcZqzQmS93Z
m5Ad2wvOKxv46bvdtCYwju97XMO1ppQQSCUZJBE8HutV3q1e9izLXDwsLlZjGuD4Lnah_ZSYlosoxgqA-H9kz41tTlWoqorMjyXEAzKliXIVniNCpyr5SpAM
hj1sy7hQnPnI38qcefY8kzHzLKZDv_m-Gzsl8wiFpmOhUuVhmmCKdRiGwAB0IfUFItz-6cfWtfjJPltvLUUMlVdCTrxyaNqgT2kgNsMZ1Qd-vsqjDF-lk1Qg
wL2pq4yabevJIqxY7m
}

EntityColoring(gnome_icon)
!define gnome_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gnome_icon, gnome_icon)
!define gnome_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gnome_icon, gnome_icon)
!define gnome_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gnome_icon, gnome_icon)
!define gnome_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gnome_icon, gnome_icon)
