sprite $gnu [64x63/16z] {
dTG5WlCw4WJWQf0Q17t_ssvinncUdVzzGKD9LWLm8_KSXtJ1ZwIPMnF29sHfoamagYs2yQqUtbIrUtoQmqOdPjzpxjeZUXgpu1C9QpspDIE81-F6mm6lgZco
jP1kt7mutkDq5y-nSfzJG8RUXsQ3ZTep8Dt3kx1mJyO7sK4CRjf5TvKBJyM1fiAgIj57T66roF1E-8Zy8Rot7gwygXfDnaCOl6eP3oVyYKHlkxR80203N5LC
G_3HBwDvfrKBPa0ej6fJVeYhHsH4kxSUJF0cTDOc3E84hzhI3MyuZCzNIm4eZCuD9zmeP5V2kdLmrQ8alCXWaEKOBfoDfwFb286yEybarWH7C6ZNxlO-JkIx
JexSjTQvbSnl0uYl6a0EGbQPAsuyI5RTWhLFkmROAe4dCgjgoCIHLsSyqM3PzIQ1tcbU0qWpNCXRRK4ae5KZNlbKtlKnBmxTTTZiUXSuQZCyWL5bBhX4frNl
3O1V-HftqUozTeCdWLQ5TvpSCUjo96O_AoED67Lo2HpKHYNEl5UL3Xmia4TqPMFYnW0q6H84PFJSLLqD3o7xx2yKRTP6Jm9vKbQ541weDm04ZSWZqZl0ewer
PtBZNGQCRZWMFBMDp2wpfk2WkKi1-6mW7uAm45nbgRlAMGqFJh2VDHEBLmLElAmsFPT4aHJLAO5pigNenp85PaY1dtKDMSUGbn6o6xGxema8sAiX283Mmzdn
wXW4JUYifyquzO0ADMK9803mDhho6FUv3ZC0qM1P5yT96YxCan02y1JjZaEhqpB8U7vXqQCEc_141BIvZsB13S0wratdeNsSEPKnvFLxenoxAd1J0JAZIWbW
03Phk-3WjTAFunsNDWGaBRVWrXdGq3L5SHbxTC9fJGPaTDnaE0DjuIMU_pZMLN3YEGSkiblFOBmX6yCotWs89xedHJTJNFhiZ4-ahuPR3dmLjXmdJdmZ5K-w
lZj1X_VHSCXKV3455rxgX1SMmMbCiASBWMV7Pvwuq3IeljAPaTUqkXc45W-6BnRZ9EVOhtocCIZEkjkS8_0zdLSwTkAzjRi2q7F5nF26xvpjjvZBusD-JkHq
WBmH7jJn3Pu27diheKrSs1Y0AksT2O2lVE0RVOwrl1zHsOHJQuIJA4BnPD_F7oeAE_CBDpAXAqWT5rcC7_a0mBlZHj4P9yQfJSNl-O-_epxmZeuf-8MTPzF4
cq6uKUi-y9j-9ccduDOJJ_VcBtJXqCR4o-XuXoRXP_Gib_RGjuGpGD9phJcMuJUpuyJJS2EV3yFDB9VWLpO-BEH6J3ZGmEze4Gwy6pxwMnxXEFMvyaDIMhT-
7FqTJRwlf08Nih5srHvkXF-d9PviW-tCQwxUTiEVkDqNuBeJBvFnDz5mQDL6lViczi0VXU8mzgnQk2XeuAzCSOYglHa7TlR0d-cLQZjg2G0USoNXxmYd5LxL
uRlAyCzuJSOgytfm_BCMGA_AMGTZ8lmR0-QeMdNQqV7FGbVT4l-EH7RjcgjgCFuJ7Xd3pBlW6_y3
}

EntityColoring(gnu)
!define gnu(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gnu, gnu)
!define gnu(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gnu, gnu)
!define gnuParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gnu, gnu)
!define gnuParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gnu, gnu)
