sprite $gnu_net [64x54/16z] {
bClNOTWw44N1SyCk-g_uHJhR4Z7_mrVQy8ws_4oUYxyHy8qJhtXBuzOyb4Qql1S_Yvb4G2ek380xkoS0JhcH06YNIOKTSMM0f28chSgTn9K2AdGstD448g2q
imqFbqybZQ40tGtW6W3lYjz9dQITcJqBWmCmPzh4xYIUxOJVsRCxqrWPkux3VvHQTj9pMaLZVgMcGdPc9qbdXuSI03f59X6_gAq2f22dUvQlL4F64B33pno2
2gsSnaA2RzpPG0Q8mayA0UtPnk8tj9DsppIxCJ-88Kft-9WcpPn4y8s2Ev7APrAKsPPligqLYFZKWDhE61xT047bSoaAdLDuP2i84IyC2amCZrbLHEMDH47Z
y517LAbuPHnA8_uNrwWjxwI9KSF_gWHwmalR01x-ewXDTyLBimBOiUrCvgmRyrPN0BELf6gQaSLhKu0q0RLeGdZF4w2ouWwqTr-fKGdCYIgFnOLgP1FHpLQQ
SYEc5J9jXNEM6mhTG9mnu0rNYYPHfWguvKvCm7j4SMFkA0IO4Mqfjqh0KTX5uLOKABG94RUK4E5MeTnh56gSn7-NLXO83eKm44qW2VmbCzp_j5jtRmUNXyiN
V7NRlbZRzVj29QBk8z_olbLynqlHwuZARuAzqwkARhhKRN_RnARhjLTcw2iw0HW6K60oUdH7SaWZqdBorGZ-KeCsMs5mpI_cFhtEcDqm2b_sdrqgdIhOyBc8
E4MvJ12fV3d_3kjRdi5MPw--vTiwqKpORCYB2H0qgAGrPcxdBueQ04o2wAz-ZjgXXwLVk-C-hDtMVoxdfCi7MW4
}

EntityColoring(gnu_net)
!define gnu_net(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gnu_net, gnu_net)
!define gnu_net(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gnu_net, gnu_net)
!define gnu_netParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gnu_net, gnu_net)
!define gnu_netParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gnu_net, gnu_net)
