sprite $gocd [64x32/16z] {
fLI7hiGW33l2dld_ltrDQZtGqTlMGWRNpb1DuP5ktwFmWMg_rlE9-Ar-y8dsPOJ8_5i4F_Yt2AOyZK0XvUJbO2qeumygq3iHJ3xlkfT9aL89pxDv6S7sUG4z
jN-gsnSHw617j6IZ75Hlkb1aI2cwwi9SnyhSz0bSIVSDb3ceUWomLVSWWbiSp52zdPH6yKa4xYu2dkIr7K7qGgMLgYme81mYGDOryHA0RksUKjHDZ-j-cr3f
uB5IYtxFl-lDf3Rzthyximv_irBGx_F3v-So4AD-jr83_RlSdwYT1RBeDogVchoRexyUPy-YLog0Si90jfiZ05u7LhqSC1sSXDxDrz0jnTIOX_GFLCynztDl
7fa3wV-IgkWHQjhnY_-NBKCC8_P7GEhTizfjvZl84hR1BDId_s_Bt2xeyiGyv3oN9M_j1J_wbJacr6cPlvm_GcFkNegcX7P_1fBUZrRRkUIVW-eoxA_Wgyu_
Fwhz3m
}

EntityColoring(gocd)
!define gocd(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gocd, gocd)
!define gocd(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gocd, gocd)
!define gocdParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gocd, gocd)
!define gocdParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gocd, gocd)
