sprite $gohorse [50x64/16z] {
bTPN3kiw303H8TNOvEn_jQyaHWmdjvvVOLJWoiyPVqMHv6-qf0M_90fSPZASAEDdj1PqwvpSMDDDgm4nVnGCwBNsu2NAAXDiW7i125oaEX2DbW0YKgFbJF21
-KZ072xB0BAzAi-qKa9CfAGTaGsh44QwyXAAMei5uHaTQ8W1DkY7GjiDUZKRF4dHocfardP5faTafgykO9K2CI0xRoMzazBAXHPfGqL4s_GqRJfhq1BT4OEJ
Xug5PGEF1eW8068L3NNhXGrKuMILMGiqVNca_o_S6j0ZEzEcbd2ZsO6zVQYSy-jmxq3FKEZRXt1fUu1cAZVYnhCnHVhglEbUq6lnPOK2h9hSfCEenbCBuT9h
04WON5R1IE4b7da_eG7WoPiU3Na7P6u1BXOAu07mhjVW985P7qqulJSSyLv2aQjl0NCjSszSX-a0ENaAWxwkqJpBjQz4Sm9I0f05h7OL0O3iok1DQWBB0Ja6
4DV1HvmN8Wyty_z4k9aT4zWDsY6WXttjYhbu4X4rDpy4Pi8iO1p2MtM-nAEH0UnE9135PIw-o8H-2FXaEr36PKv-g1yDfklZMGpUnEihqIgR_kZGS_vVoD5u
wYjoFoPVPEvSDK0g7W7j_nea8hFgpBdeZ9YG0wXw5NPUl2gRMzyJcuUPLvh2MUJnB2hFYsTcLPmYLkzZTEKbdiNZS6Zf3M1QP5Rm8bkvyMTH6Q0v5i3SUzUv
GsYV1ue1nAW4hUQ0v56rz-Hq63VPGLqg5TdTWPcHiRDpokGc5RgnQeAR0ReghuSSh1fSf80vqOT1AnVePfuFlRz6Bfg0DoW7CXg8nzp9cnmEbn500FCGM64W
GsCFBbLmiGLz0N8ia5s0HglEPHxwSV0G0DkSWp4ZuIVRcWvh0Q2l9tZIps_A9RPmqYre2az-2FJTmjIvMUzDjXeGuxPuxWx2JIlZUiKDlr-gEapub0xGCXLQ
NUCQANG_CjnNW_jnUzG491kNi0vuj34iqyriZJwccH-HtW68_dKvGG4G7VC_osoEqLK0a1ZSk0k_qdBmeOx1pwrKxcOd7ZzBn7BoeU-S-ACBtvh54Zv8TKgP
n-xVBohhV7E3tNflxbDvqnK-cpS-jJhSobPjq6LkQyqvbySpdy6NNdsCDYiNJzB7jDN7e2zeM_Wq5P2Z5Z0wO0hCj5OTcCcFo0u12Qj6Ei2HIWs0x3-vH6aI
az2Lxx_JLWBOuCUqZzsMKGg8L5E8JlFavvPDf0IMuncY8KWNViFBoeMV-nS
}

EntityColoring(gohorse)
!define gohorse(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gohorse, gohorse)
!define gohorse(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gohorse, gohorse)
!define gohorseParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gohorse, gohorse)
!define gohorseParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gohorse, gohorse)
