sprite $google_data_studio [64x60/16z] {
xLT5TWKn34lCll-1ozn6pwzQVT1UCm4BiX34FFv0LdTNoC8GZpzH_GQ7T0r0VqMYln_esLyGPxuV-FqDIgmUxi1c_2QM3_anulF_P_TFN3yUGPyieFQHltsm
05sB-43PWb0em5S1OspHls3chb-sViS-G6GFoERXVo2hkZiDK4TIIHdGaL9B29l6HhrdEZNI9vBqgTgaJmhBPzTFdXz_Vym2Sb51NSBevvMEQvB_NeK7qE_G
FmJvnnt_pIyrjzVy8lApGNxI-Stt1vlr5xO_aRvSrzfVdUololhozFr2BI0MDO39oA_RHmB6xzT7
}

EntityColoring(google_data_studio)
!define google_data_studio(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_data_studio, google_data_studio)
!define google_data_studio(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_data_studio, google_data_studio)
!define google_data_studioParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_data_studio, google_data_studio)
!define google_data_studioParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_data_studio, google_data_studio)
