sprite $google_cloud_run [64x58/16z] {
jLU7ekCW37kUul-_-8wItWYHwovr5no41CRvES4IWm9fFpK2emHIMk4SMOGhnaF0UNoE1a1dO1WT18l7Q05w7UualYcXO3G1k_Hkj86kTzn3xbtRmzgx6a75
Qtl8nGEEpz93FdmQbas1feTniaSIK-LA5N3lvkGSjov2AS2fTuX52LeP0w4B7pFkFeGaQWy5L-x84jaMXSh3k9vRtYXwAgMGTE7F5l_zQPE6hoao3vDeSqm0
Op0AIoTwvTaWamQdu6luQWBwHojDx3mTr5nTrqbCf5rIY2oMDxPCir40w0PVnkg39Bl5RmBy3plrg_ZFjbEQoMqDSlraInEsJxFmpqxq9Q-64R3DFRjBbM5N
jsZHbsGRIC3f-pxudWCTbDT1NwBCmRd5wz_LL-OFqZxZz4vVuk4Pb7pnrlcJvs-RdtJm2I_FZqMZStxi7iOHPZ4uZ6zBl503vNWE-cRzyAdwXNbOmpzPlprV
0jatwjU-XFfc_Vwb-mVk8VVkUGdphVktaHjxSi8s2_TV
}

EntityColoring(google_cloud_run)
!define google_cloud_run(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_cloud_run, google_cloud_run)
!define google_cloud_run(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_cloud_run, google_cloud_run)
!define google_cloud_runParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_cloud_run, google_cloud_run)
!define google_cloud_runParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_cloud_run, google_cloud_run)
