sprite $google_tag_manager [64x64/16z] {
fTPLSiH040JHcLMJxdzWOviw8ksoLFyl5uJhjptiPSTUygRsbxqKBl73l0S1WLyFMFEB0G_p6m5FDuU0nAlP2CWy7G8QhtA3WCOhp24WyKft20XyV04ECAzq
20ZyQi2RgW7cUe0v1uZB0UHpOH0G-Lu714I-A21oAH38fG1pAS1S2Z2N0fR4fS16BWMs4nS32Hm2Ye_LKm897w_wkFVztMx-Vt3yLFwWyqVZzdNF7dE1k-sb
1HxCEI1n3gHhd0Ecy0uK191_rnpGE0SEv68W34uR_Ga6N0y0LmBdsG7c73XxeR-A--GTGCw1jXq03e71pr9uBuRlBm0S0eEVQS0XC7q1ny3qm34mFN0C39_0
rO3fifVVUQn_RzSNptLXEyzUx7LfLd__TSy
}

EntityColoring(google_tag_manager)
!define google_tag_manager(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_tag_manager, google_tag_manager)
!define google_tag_manager(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_tag_manager, google_tag_manager)
!define google_tag_managerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_tag_manager, google_tag_manager)
!define google_tag_managerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_tag_manager, google_tag_manager)
