sprite $google_adsense [64x57/16z] {
fPO7pkim38EjIT__mczcXn1-nHzcmLAqnNIC0ZLpCntVKFF_V9eWvYScN-mh0yplMDk-Ca28NzhnTxJHd1Ei4R_cLr_oYwtvpIcs5k-w62-DvH5iFRvlvxSN
DTFUykoIaFX7w9Tu1UO6ehyymxoGqboUOTv84b-SNZ0VU6jvCPz06ijJp1VHYC_v1gtb4NxU7IRZn_7E_OtkA8tk66XqnuX6TmHeepiQNo-lxcv2wlXHTmVV
xP7u-nhHwYut-J8UqUZEsEdojJmjujcNIgCxUhaW3pxlZbyEdUw4o46_SdbtphHhV5RBupAs-EBuq4eE4-9dyMDo_wZza5BsGVpyQplvvKwoZ1zEBtV1mH_y
3U4oUmEV7qmk3m0byvdCDm2_omOYNv6ywV7K3UJoDm9y_8OSEb87GmFR5vnmFVx9eVNVMYB_1W
}

EntityColoring(google_adsense)
!define google_adsense(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_adsense, google_adsense)
!define google_adsense(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_adsense, google_adsense)
!define google_adsenseParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_adsense, google_adsense)
!define google_adsenseParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_adsense, google_adsense)
