sprite $google_gmail [64x48/16z] {
xS_Nbi0W28JXGKH6z_sVTtlp60pRwt-RV1m7G6bzT5Uy82bQjGXkgkCkbpI_rZTf0M3ZeQv9VgVl3fJnBCjeqVgOYj_9_0RL-YpjOyhBNajhTMhCaNN7rNdc
sU8DbJptZ3P8Oye76zIPyySRZ4pxTOCqvlswGSd0ioz-tM0Cl3dPLpzlaCR0ttzO_BH1oS0xx-kJdpSO0s_EnthWwSx0Dqu5dWpyShU_n9jpgUTzus7Z8kUT
GJtZpHdcVkwvoT3ssgLkZmDrVnzd7YNUe4XuY0LlBqZuy1y3SlvuWoBlrmqkoFlrFmFoVjsWIFldsVJsbtlezFQidpQuuWqU8dYJ1xwr__V-Hb_zJRx1_0s-
2L3zjTvDS0K
}

EntityColoring(google_gmail)
!define google_gmail(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_gmail, google_gmail)
!define google_gmail(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_gmail, google_gmail)
!define google_gmailParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_gmail, google_gmail)
!define google_gmailParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_gmail, google_gmail)
