sprite $google_photos [64x64/16z] {
fTHN5gim34NHgsQ9-G_ubVIuo12TnUy6NB598xmfuzSyRZNvqSSpvvgFqA8FA_gmeWyj-g2YRqKVNFHMz5xqmKMlIAB_vTwMLbxnTSyY-axucYVHBg7CZtn8
UEvrmSTuwlaiL-6Pfy6BBX8QVKlua8nUahyVuzvxzlaneSxpHS--MNpMDDdTFg9vNvmAViwXfxq21M-4QImfjnjkIbX6iq2i7ezydM4UjpXknQQfffl-sSi_
NV0QnplFkITVlzLotmREN_nGpxZBuFtuYblggUTwT9uzyOQ-w3tQbS_BCNZs9LVqjT53_VJV8oOUvYVN3ZppynVuz3QQUuXdOzzxaFcNRenPkl80cxl7xN4R
TFRzLongfig4LPpwVLJqyABNegUeULZHKzGy96eULlImeeT5pKEYvW6DcWUanJ_ksFGN
}

EntityColoring(google_photos)
!define google_photos(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_photos, google_photos)
!define google_photos(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_photos, google_photos)
!define google_photosParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_photos, google_photos)
!define google_photosParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_photos, google_photos)
