sprite $google_currents [63x64/16z] {
dPTdWlGm24CdRhZS_xnVoHHU8gRgprRsnI3axEKpfMhTMjaklsYhrdTP_g4wMR_BwlTih_wbldNew-VFrW-oorCLwzrA27-FBsFj6bdwHhKdPrntpIfmo5B8
Nb0H-1lyDba-x_wgNHJYRHtKPEQ25xZW2JTuRmlxHjKJt1B-L0tXrBZvm1yuFSTN5ABvHhDmXYTh3IqV1xyQx2luiW9bu6p7eRo4SAhBOOk5YvDNA9EpMhWu
dIK--dw20q_h94mj9U-TpdcBy8RpUXzcPF9Avoey-nH6v77Ya_XrO0o4X-lVu5UiULMuAvtnbV1T4t09jtPgAE3LJpF3Q5Nd5esORG9EVogUVcq-ION7U8Nl
enpYLnUz33Wm9dw52l3zr3ZDLyqr3iMVtJdCrzaarmQw-i2ZnHNbQCbzh1DTBRuX5i5vgBkfnWDEYrkHtdJt8a9reglr1dTp7-5hQQxTNEChCzpT-G0_uOl3
R3jRl9q6SpkOvXeYQ4Cpql5AzWowAQFHIItU8lYQIK8LAP3MS8kUfaO_CzS68gYxQWLSjicmdd42uLC4IPXht09LHOREA5GP0I9BXDKJl4OHG3MXLOcMvtZB
Se5ehZt7crnVacjGyKBaQrh0nxd67PU8wo3YKtqlh0hN5mViWE8LZdPH-SbhlrvhvIsS-QttqdmALxxjnSw6LzIlgbnRg_dDwsgvVACcyA-qZU_XL9wijikt
AlE7Ql87_iNwHQNFjKQJo_el
}

EntityColoring(google_currents)
!define google_currents(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_currents, google_currents)
!define google_currents(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_currents, google_currents)
!define google_currentsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_currents, google_currents)
!define google_currentsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_currents, google_currents)
