sprite $google_maps [45x64/16z] {
XPRThZGX20HLa6RU_u6_7tDC5gVSKxTRwJGE8TiEXeVoUPvK-6ZVwAxd4tc_glEfP4gJTS_JNSWXTXK0EHLdzv7WRcJ5jPiBLIwvcDt9hMXiEJB1hQZlDyl3
Jc3-b5Y034LcddOYiOEBdbfGj6Unz_Pq2xrRAwizsyOEMxrdfNmhLTaC7kYMFUSnSINghyAFoj5IATnVMvutfhKJNLr_ov5CkF-Mh0_N3JgJBF_FE6IlyYxb
2_lUmlTmP7iMvYZkBiARv7qFjx6hgz7YlriOQv-7AojgpL9-OFzn9MnlE19u38PTNLXVaYUU0ewUV6GuMacD5ztOvJCwm8KIL2IIIf3DxjZUKNk2wwqohBXG
68e8RotRmk7O5Wv7T0iSZZ7nSCmxMUrA5nTcJ5oOeTj-H_p2Z8bBC9DBC5ty_uMP7CmCSJ0J_1IC2vU2wU8MJF06CIvkmSHblBy
}

EntityColoring(google_maps)
!define google_maps(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_maps, google_maps)
!define google_maps(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_maps, google_maps)
!define google_mapsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_maps, google_maps)
!define google_mapsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_maps, google_maps)
