sprite $google_keep [47x64/16z] {
xT1LeaDH24DHICZyX_oatciqTTlVwmX4W3KVOX1hAGqyQfaFF1i-yDLomUE2nmMF2nuNFIvwNFIuw77HuwB7HO-BzUcHFDrc_9Smy7_9NiTXxBNZSy3JkZm2
pUNEzJ7Ev9pNz7YPFBs_mziChRzKeRcy-JtByCbgmxvwUDpNoC6iwV6u0KVkgYVlspTOca57PmGS_Gi
}

EntityColoring(google_keep)
!define google_keep(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_keep, google_keep)
!define google_keep(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_keep, google_keep)
!define google_keepParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_keep, google_keep)
!define google_keepParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_keep, google_keep)
