sprite $google_marketing_platform [64x64/16z] {
nPTNWfin28HD7Np_0wSdBXg1_hJzthOC7IpVDeXw9505PBZAxGfYtwGFW7GzLLkY24WxKWEr0pxbeOdgWBLv1se0ANlddNeEmL178AZSKQSm0u4w9rVlTOdi
Sv-9ll8p_gn7NKSVygZV00VHuojZ1hdHXkaNp1D5-J79HjNnb9yucXw0gULaEcNJUjZPSWNF7agNc_XXl-PoRi38uCFFxqEIy7CdPxxMe21Sorkb2jfK0XqL
zwvuSm0PIqOjoxzd6_wS09QEjWZLz-dt7VXWFVwo_chzaXor1ftqUMr-ojlrcTDND0dCuOVWoWBaUe2opWCmSe6z7w7-02OxQf3JwClfRrCEvINqvS4D1Fc_
tKh5Oa2SFm5u032J5xLPtgbx_hbIxcRwmuIecJkuUzxM2l-2_S2_qht1akaVS3sa6GoVzTOy_-0Bu8UUDpTz8VerYy6zE-uaUJwTuGooOpG2X7FGRvX_2m7f
MmAFxmy4zGWVY71jlZVwn6CnA6g3d3hd5hZp6Ttw7jMFTRSsyXdHXmbhF7y6
}

EntityColoring(google_marketing_platform)
!define google_marketing_platform(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_marketing_platform, google_marketing_platform)
!define google_marketing_platform(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_marketing_platform, google_marketing_platform)
!define google_marketing_platformParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_marketing_platform, google_marketing_platform)
!define google_marketing_platformParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_marketing_platform, google_marketing_platform)
