sprite $google_home [62x64/16z] {
xSvBRiL020LHhAQ1_Qyu7Z4p9LqdUT-Q7wbioZFtOM8xgof4layB731mmC010mSC731mmC010mSC731pnimPLpO731mmSCJC6UV02UVsWICs6pXZu8210mOE
c3XZipNm0GC73FE0WGEc-G4ZhyW1CmUCd35pnim7p3mCYxp4wuOEbtHZNOTBkh6kmoNTMDVXacwiwt19DzPrkAORwzhlwowmh6kTbL1ziFxgzJYTnz9rRZkv
gDFj1m
}

EntityColoring(google_home)
!define google_home(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_home, google_home)
!define google_home(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_home, google_home)
!define google_homeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_home, google_home)
!define google_homeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_home, google_home)
