sprite $google_optimize [62x64/16z] {
xTPLaiKm34HHIsefiF_z3bDSwenSZ-7-dw2fyHJE0hJj9l3T89KRSwwbEuzpU24Gh5xAsArBuI3jkVOBQXoaxI0jE4ItmtJ3GLfGqZGhQPvQLqcNtkQf1TDR
uLamsTKIo_hHCaz94TZHEgy_BLFgNPYMNqpvv4nFwwOvrO5SwxB1xEOXgOwDvJUtLCyrFNcgEyiV_J1zq9D7kip7YAxyCQwjmvQC5ghx5uVGaThhP5_NHcO9
qSswlNypG-CxffkYFxLyhWxX-Cs9_l3uxxmcGNGfFQb-wgT-Qkcrjv5wZI7jMnpQ3dXnRsCXkkrxB0_otBKiDeUUqGJnRhNHNW4
}

EntityColoring(google_optimize)
!define google_optimize(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_optimize, google_optimize)
!define google_optimize(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_optimize, google_optimize)
!define google_optimizeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_optimize, google_optimize)
!define google_optimizeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_optimize, google_optimize)
