sprite $google_pay_icon [64x55/16z] {
fPPfje9G38FfcEv_nKyy3jmdWSBzVfkJaAXqEKOyKOLqNMwWYNg1jAjg2TG6f5upH_q38HFo5NWxF6eND6l88lHgC1I5ro3c9YJzUGqIM5dpHPq0vOt15NLA
AcyCrS59OsrYgoVoRWAlE-XGtWd8tnAN5r7df7kI09t1u0y2knLcfsr_Wjg2zdRm5pNGtYxyHVxe7QtoTWDqjtEYxsv7z6Xlzs6my_vsk_r9SpiIF-Ri8Qsd
puEdzulfCPQ_v8IzFVIuNruk3oQsKw9lRxU2YUrMScAx5P_ORaLnTxiNUMyx-jx2vYyMT3kXbqQuvo2dsmqDZ8aJG8RJyeI-UU43RBi1nr3u7cOvR3TYEDFh
vaCGSgfolMroXXoToc3sJzHKZay-4Fi6yimNEtAvSB63sFUmH11v4mT9tqM8l8-QVTIwt47ifJur_mC
}

EntityColoring(google_pay_icon)
!define google_pay_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_pay_icon, google_pay_icon)
!define google_pay_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_pay_icon, google_pay_icon)
!define google_pay_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_pay_icon, google_pay_icon)
!define google_pay_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_pay_icon, google_pay_icon)
