sprite $google_cloud [64x52/16z] {
hPTNWiCm24G3WnZkV-7jXH1Xcys-_qUBaE9RXy2SyGPzGMup11vtq6HWhzYmzA9kqR2krA2C5cAQl68d-eeJrg7kSSeQP1y6iBW2hT4rha7T-um2bm5O7WLU
Qlxtn0fuFWBPdBLkD9Ipz3W-bgjBJxgJnAO-7XPW7ujkNq2bMOpkDoINPO3752c0r-gItKRm_Wp0DjG0O1D0O5kW_GaZEhqFi68ReEXz2-1k3s0zEBhRs5JV
wJVPxS6ftlkKcXu034alFbaBmEEu1AXwiygKErz_1eMizujAwBvT1IvTqevcMbgaPefCVgCSTz1lIm_udA__wEF9-ilyn_FJvCkyV8fD2n2_Mm2pMGMQTQAi
xu8U0cSaMFQNmHCU_meWwpCe-VwQw_Qpx2EzFcAOwlKHnbIlBnZ-f2UcFhs-hSw1JKlgD0AxZmarls0lpSuh
}

EntityColoring(google_cloud)
!define google_cloud(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_cloud, google_cloud)
!define google_cloud(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_cloud, google_cloud)
!define google_cloudParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_cloud, google_cloud)
!define google_cloudParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_cloud, google_cloud)
