sprite $google_one [32x64/16z] {
xTL7UaKn24DXGBf1R_yBJc_6_Y1bc9pfxpAKdV8hfQJREUYbn96fzz3SViwhEku--xKnjRHoW5Vnmfs3RDp1pftiFD0wmCv1DkvWvm4sNhXwvUfEjXw3Ot2E
NclVXyVgWPMjkE6Jmcnpmpk7dTo0PuNRisTrym0GPaSl_RjkdzlzzalFoQN9DRacboRNv9fScboJQtBzEVV5qxRAlhKVfDiUKyC0P-5QVEpx0m
}

EntityColoring(google_one)
!define google_one(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_one, google_one)
!define google_one(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_one, google_one)
!define google_oneParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_one, google_one)
!define google_oneParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_one, google_one)
