sprite $google_icon [63x64/16z] {
vPS7pZCn24GD30ptl_1VKxoDDKfKlwUMzjmqQqt65GedymzakCbe88ZSGTT5sI9FeSk2pBpcRW1brdXbUzv2RK-z1UUsvI8X9pPo6Nna-xTj-yZMF8FX03pk
RE7HZUanKR2mXnVft6OPOs7feHTpO9p0jLmhiP8sZ0javVcsqK8CNivTOm2S-I16M__BmwSqRSL_ejXuEVa3pqoEllw2YQujamwNhgwOi770em8RNOzwP4NO
FBbqTMxqqTKJFrYtB-hIrZ-BJTw5DhXdjYc62JdeiaTdFyQa1z7iFZxfiNHT-2RoGn-oy__x6uIpBkCnlIzUbTXk_Q57Fl3Ev7XSLznyL137ZcQ-6T9Mbvvn
LaDfYpRjD9Z4aftSjCcxtYV1YrdyldiBc5jOLIFE_o34dBc3LfTXCXm0F4ZUr3jZzeZgLFkj7cpQRRzEbh4xznPTyqF7EUAybUdZ6WtMCdMKMB2GKQdr00nR
xKj1RbK6PAmZ2W_ocNszS7y3
}

EntityColoring(google_icon)
!define google_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_icon, google_icon)
!define google_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_icon, google_icon)
!define google_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_icon, google_icon)
!define google_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_icon, google_icon)
