sprite $google_admob [64x64/16z] {
nPTfsciX28EF4edV_XTyXyvjn0DtpDy-BmPgQJmYTGmd9tsOzNQKrCmv7oA0IWtp-QQl2LnBf6XE4N7LUONEkT2N8rMXZHa83rbB72uQmAa5cx4SBreNmCpo
i0K-Pfw7fK_N_Y-o6avWMw3Fml4wnCPPw5xlmQZZWENSqs5ld7R0W1pMU_kXRePD1xQanzk0bXKiFjwxh9J8W4qL3fK54t35xLZ9bWsq25VPgW48FWIC2opi
SxUNXLVxNRdOG9ExvmBj37G4mqiQiF61istv_ibJxPSQe7vvfGOIDxV4st_cKUJvXtalylx1iyZh06kyVV9Uusk_N-Lr-tgDXnX0YUzJr2lymL81vQ4yBSyl
3SpHyZpcIcXP_c0K6tflBS7RZ4MY2UyawUF2or-eYFREErzoJIe_sIllRx4kbzzQyBWWSldH7pouNlT86XZHkXcP2UYean4OKTQJbrEHJxvV-jR_wH0OpP-v
9nI2g4xate-l5dcsAystcSJFmqe7PPUe0thR1PNXl8JuhkKld_ZbJdq7
}

EntityColoring(google_admob)
!define google_admob(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_admob, google_admob)
!define google_admob(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_admob, google_admob)
!define google_admobParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_admob, google_admob)
!define google_admobParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_admob, google_admob)
