sprite $google_pay [64x12/16z] {
dT85bjX030DGcIJD_I_SUjfbtXzsdY60bHGJlnKXsvfuYk07AFbIuHhRWzVw8HJTXISjBz4s5frHR_D73maUyMbK-MBHZWsS1AxQawoDLSHm3_y7SMH5193Z
IzsoRfQ18cSB4tixoZeQfkK4cb4gZOROq3KzTk4f_r08zmcGQhI6cdRl_5AYMwsOrglsctIha81fOBPhQcZFm_mObggfs3ogjtrYRMhDgJmzJa-vHYKDnyNw
dwzEDyvW9-k_aetrz3VLZXaxF4PKzHxYuOsIaz2spEckn2UwWyHRALoHWS-aZmDlJG5_
}

EntityColoring(google_pay)
!define google_pay(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_pay, google_pay)
!define google_pay(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_pay, google_pay)
!define google_payParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_pay, google_pay)
!define google_payParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_pay, google_pay)
