sprite $gopher [47x64/16z] {
pPQ9agjA34DfMx9aCXd-_szVbfuKt9My_TIgueIsHRRb6m9bznCBiVo2B5j5J4ZP73-HOHC7CXFLl1-wEsQ0kGmRYGDbkm2vscvEkrhoseJQSjUKPSG8ciaB
Cw5ws59cLeFz67DKuuuvZpR1rGLqtc8uQQr0ZzSE07Itfm_KzabGjrJ4nosaS_d21Bn4pbW4UYl0jo3WSsl0Yo_pZX1Os3RFUWLmnUlkkXAishRFvppXBApR
zJ9r0_0yVpJO04lRnJ5raBUeULWzIwtvuXO0n_LpTxs7Erwht5XpcVGzAvUOsG2gbWcDErw-c7dCgFBr-h7gaKSP3noxOc_G7BS0KzkDQrbLTk59OUhXtNl4
1Qrt_SC4YHUigQUmfohAPi343kfBB-nnnhWHWy8UJnr7NPMK2w4weqCDQdGB1tmOvZ0bk1paWwxlBh0MyMUwSKJghWQEzAxt8mGAFzE7SOPU9lyBVKnTR-hy
1tG_TTHwIk-kMCALFgKRQNR6q4bzvBhMmEMKBWVNjChdTCcvZ76ozy9RJxNubivwJzVJ7l-e7l-eddghcTHRlSURkd46vLj5Elx1BmvgcHJFRJg1Jdvld9-6
dkwvQPpBY-6JYqwWavDFwjV-6ik1l1W_XIqTR2ggwoUsdODxFnKHkJP_jADT8zAnBx8YfAHTFBhA--LXSJVBcc7CFzZo5-8iMwnrNurqU0mF3hlLZ7y
}

EntityColoring(gopher)
!define gopher(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gopher, gopher)
!define gopher(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gopher, gopher)
!define gopherParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gopher, gopher)
!define gopherParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gopher, gopher)
