sprite $grafana [59x64/16z] {
dPU9Tkim24I10Rtt_p_S9ROFmaEiHhVDpjKWxvPdu2fxU8omFNFy4BPdlbpzsBGOf_kn6kC2duOUsaRB6cCYt7vryrYEOp48n_agZEev88f8t6Cyhiuinhyd
HkaOOrpb-UwjQhCQpxM3KbbbAS8TS8_qg-gzvoQ9-IN7IWrhLXcxu4X81uxawKUbI9Ktn7qXZvifJ7Ru_yUjksPIJ09Hzt-rH7kb5lUgBDKw_aEelhYvsiLo
0e_PTwmaLfbZsr0ZjCIooYQvceLgU54d122bMc38CbBrC3EcL6IguS2cqAohZPsVv0GNjL9bfhYMPGTMGwMWED0o6gjPGwwHoQhSmG6Pf1gfLZes51xLsh7Y
0xLs3FZCMdNtGrLu0PhJSZHg1gJ9iGvxKWsiPYols5GRrzBbN2j5UdTbTjrXPa3s--JYtbzk0qe1nYtt1quq0Gfs6QLvfRrmt_UsolM2tgvYBXpQT1idxlGx
qYNP9X6cSWSnCLKeF4sJ5e-PSwMwUoIGjThZqcFRfjYsALYOa6rLzzK_tMG4Sll8g_Zr1N-4wtKgSayLya2t3UhYVeSkBzWDo0RubLssKF2Q-GO
}

EntityColoring(grafana)
!define grafana(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, grafana, grafana)
!define grafana(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, grafana, grafana)
!define grafanaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, grafana, grafana)
!define grafanaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, grafana, grafana)
