sprite $graphql [57x64/16z] {
lLS74kGW35lROFd_Bxv9E0NcD4oMQzgM9ZTvW_FPmJeAtJ-dSDG5n27F1k-SsOl06H7rm4yZ9UASMESUlIRQWRzUA_9RduqC0js-e0LkzR8kS0klyVhFo_pw
RYsh6asz9vTswnYZkZ0UTl7ICvjToTscVQIPxA1a87MbQYsp3-yZ6xGb8iCZ7xS2l8X1fPRlyjDPg-6IyH2mKC7koZm2v9MjojjHsYB9RLhXTjG29SQyb75F
8mgUfXG3b4Gzfln_A0Mn7B2QY28m7L1g2I6Ny3fv8IaHiLgTNZh84ocqpCu6kCrSnqsk8MXjSUypUvUe28cVfI9nQKt1shmcHAcCIB8dKcj29L6YLaObsH9T
AgEIA97XRC0qX2XDkf54Y2pv5fHAYIg5rYULg4sgoAeGuaOAQLbfEP5YKv_s2p5KYbtBuY5QLa6asBKiM8ldHclVpmRewshe9qjyVlneBiaYMjRSzZT4FG3g
VmFBPdz3raGxc6Xy8UOirDjmOUkLi6U_j_qmn3v1tDt2Mt8aq9qhRhVDz3CMUkz0DjjCEPeSBMwn3aCUOLpx9GS5KxspGMToNy-EcAsrZr9JEXuxYQZ_Dreh
CVxBuyFImJX_j6AaPmYSF3net-xz_G
}

EntityColoring(graphql)
!define graphql(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, graphql, graphql)
!define graphql(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, graphql, graphql)
!define graphqlParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, graphql, graphql)
!define graphqlParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, graphql, graphql)
