sprite $gravatar [64x64/16z] {
bPO74kmu24H543JtF_3kprEuBG_kYWwFAB3Naom0P8QRhFUIG1LG1G3f-fPFTAM_YcA3zSO2Yl02V8ehxbG8dV66UnNiwD9TcMS3-zvX0a0Qyvp3Oks_zTh4
i-AC5xpnCmF-wLRbWB_KG5kpRS2tWo3P7mtuWj9HFV8LdYWqLNuwXm8u_fwjdqkG3I-iEtv9N3EG-qxxFSyXH7VVmsAU3GYxHwmplnpiggULwubVGHKGDEap
l_BQAQU87dcx9XlKaYUUtXTsV-Ov05Lko9dd2cpd8ttcULWYJg_Pv45bji6VyDAchV52-vzuEW8VlXelDD4yhhGHs0qRNZ7W-qxqDUAncfoo9vxgrwJjYqI9
CK-VLZ5hzwX_5RIvtdpO2zx7SQ1-uetdvonk_nQyJ40RO9TgVkVZ4l3c0ERkizsOL238NU952vozEUOP6DYPeAO655tQ5XeROE_idWF07kKEwEb16jCQA79_
t0XX5thpjf0saXJ3DldpL3t1CagDb1aH2P1vAj86M8MggWOV9oNmHfMotXdWsh61mb3DE_s23t6MJmnKgpmj_Ff6mvxd-uk5aFKesKyMGazSju1wGRCisfz1
5O1mMNE9UkHV_3DBhFy1
}

EntityColoring(gravatar)
!define gravatar(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gravatar, gravatar)
!define gravatar(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gravatar, gravatar)
!define gravatarParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gravatar, gravatar)
!define gravatarParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gravatar, gravatar)
