sprite $grav [64x64/16z] {
bLTPbYCn2FE-WNp_uywhD24fnyGP_MIpG0WNT3i3FjLE301Ce-RW_WUX362-0Q0QVsLd8Iy05U_EA8Hf05nF4TBANgHm-SRsVStTO-ptU2FQoNaku2leyYqi
2GLpnRY-7wiDRKklc5k-7vzVRsnic5j-POZvn806E6GNaCib5boQm-DUiGRUrhw27tbuKjGEFHjpTnvp2yJ7ZnnS6jJJcvkeIbvRjFQg8r_bYV416bhHzsof
aqdBwzwvzlJ6s-eL22wW1cYyjzDQ0KqRrKMayhGJixa8ZQtUs-2Bto7g2n1UOlevFKNdkVoLZEGS8qb-jJ2RwSKZ6g9_n0o4EXLD6cg1mr-2J3eCoFFzUWKp
lRQuKu5-rTuFP77FlZpncXTjoDF5ITu8XYrVxCr_KNBkpAFulZuVdhzv5tiC_ctuhzcGpBk7z7YgioSWEUkgjMhGPKX5JsBadZ-wmGxneLhQenClBdAPjkph
sWYdItv3mCO-6JOjIu2t-bDTpsDQqpcJl95AcdCXvSeMVvrBaSDjGihUy6JmrxaOHROQXx0PTlWSk88a2LyaylA3wH_AXs0LBG6MLKFhk5ECb_v0pzD1jhmo
nbP-oBLXRFOoPmckTdy-yQ4IS4sxtMf3VqXuqaYcrqrVO5dzachjS7WLr08-o-zuZ1Pjt0emNWE8bcqZAvAEkqaIrZjVl4LQqkynxWVGwi0yfrSKOtrezGa7
-Vi1pFwy6jKlDaQljDa6ad48vMYUf1S1-y2UJkdt2vmv7hnVHWKjSMlIi8VbkgaJrOLqR9rujAbWI4m-gt-XhRB2WIwZI35KrctYd8iN-25y_ujuQT0IG6zk
nf6-GOVyaJGET0hV_W71WOtkdO5uS4qci0rVZyc3-uhGyOKzaZiYD8QHMzWd-DpN4C0emVqEd-fW9LFB5laV
}

EntityColoring(grav)
!define grav(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, grav, grav)
!define grav(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, grav, grav)
!define gravParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, grav, grav)
!define gravParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, grav, grav)
