sprite $graylog_icon [64x62/16z] {
bPS9Ogn024IbA6Zd_WVEedOIHihVlx9dvh49Icz2vimnzY-DaU6s_OyG1_dw-fe_HlWYR1nxhy027Vk34ckqLje3xYLo8KfSE5yCmSQ-g846HuU_ljHPy3k-
DsyS-QMX33m7dyJC4vut0wZyEnxMD9Ksa2rTnRVSv4i3ehcgb_XzeIQ-IKLVmxoPLMAN0JJ-R835lGnUfs0tzzQufAahpNVtViUDH6tKMW7xH_HWkCm0jI9e
U6Um1bIhdSgzNNm4JGKmDbFPEyy_6K5igWA0AZw3FxpBOID5-BXuOp0eUo1Jt1Xds21n5k0tElzbndYrwTiCsycp0vpUja1_zPpq8spIZw-DGJHNy5O-SnmO
m9F7vkGPqBJUyrVTI8V7Dq4xkn-aUP0__D2ynvTuv4vY6WcGGE55_Cu8ahIpObSImQ1jcFnJ_NpEwy7wmVjClk5V-fb0cjElPaBVm2aVh3FjmrAP8V_3Y_wz
UFBa61G3w6f-hhHF7ev-Vi9sdG1AsThm_Q-nSIjWosS9EHvkdvoZhs-WzSyxZqVtR6xeTGfDPZyhJhqMWCNWRNRpzfzH_G5jzDLRF3-zDPxYyR-w0A1VFqpH
bi9JYkLCRuYrtKrlNtgrTd5HnVvsUuVOIwQIzWDxtbzUsRqp8pBRLzQNzvV6TGfQUadpLPowFnOqi700MdI-NWNTMUin31PQ2fp7rtA05Ndhu_FadmxGdm
}

EntityColoring(graylog_icon)
!define graylog_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, graylog_icon, graylog_icon)
!define graylog_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, graylog_icon, graylog_icon)
!define graylog_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, graylog_icon, graylog_icon)
!define graylog_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, graylog_icon, graylog_icon)
