sprite $graylog [64x19/16z] {
tP5NWeGn289ZIxp_YHTOixs-3jD8-NvbN7-HTtvtz02yPuPRnC87tZoumPNXbBy1Nguo1hAizEK1SuK7KJ5Bh7IPLdmsTNn19L-xLrQ6HrQ1fm_3MYtWeqBf
uhDFc04qukCRbrotnAVHkxjnNqSmocy23O_PM1zuTPGgCjVabKBzw2mpn0S-PaXq6fmWUeKKDRmHZRpzy2E-sZqyOkrsU47mj_xbRuYOsdo--6oOS0DZHI_-
O_u1ruklDF7uR1Zw8qzPDqE6UzRbDLZ3nisYUvkr2jOH-Otlb_aFpwAZcVtp_zHc-DgxHSgVFgVXdRU2-IEcTGQdvovbjH4ZIUaA_Jc5Fd15QzRxh9dEj-hs
oSz6FsbcyLdxQBzQeIN_J_b4aAgZCLY0Zg_gs3Vb8T_TVH3v2G
}

EntityColoring(graylog)
!define graylog(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, graylog, graylog)
!define graylog(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, graylog, graylog)
!define graylogParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, graylog, graylog)
!define graylogParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, graylog, graylog)
