sprite $gridsome [64x13/16z] {
dP05hXXH201nl_zv2rjllvCDcicyB02Wg19yELZr7nu_YGlX7t3qb7plzTbJle6Jk_pbhXRsuMUef_2ymQlhNxFrEMa_KcG4L97UV4yXbLsmA98ot9B0x3f6
O1KwfMz2HCXfRgQkwiRAAf2fBjJDknp2Ett_zMg2vizB-b8icxa3nsPl6WR3De1qRRYnz4usZvyKGJpi_75-6SwTMbe0kC4dcGRNL5RB4snTVutvKHUHfxQz
dHBgUBwiWqJUFBo7r1-yPX2nKCHXTqcyccEQmmy_h2FIJICw62qs_8kNKIa7otHcYKo19wmwpxHZq4vb0LgbzweI40TClBFMyxCrCY8F_sAmHuRHr-1l
}

EntityColoring(gridsome)
!define gridsome(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gridsome, gridsome)
!define gridsome(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gridsome, gridsome)
!define gridsomeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gridsome, gridsome)
!define gridsomeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gridsome, gridsome)
