sprite $gridsome_icon [64x64/16z] {
fTG5SiCm48NXjxph-z-t70iSfTRa6oZ-ef625H8rStSJx6CrF-aRyVu0REOJOzn5_Tpx2n3pPtH_yfxTwzbM-BtStikLx-IwgfNsPc-X2ZFHpPEVOo7SftFD
s27wJWtsw1bXZsSd39iaUefTliptfpTiisWSsyYxdF7MyWtxxBtfoLjksCVU2FQ9DuGPNzu2SOClvYTRl0lfnnlmqEkSH_u87Tzfem9RRzyp_j3YKyRqnV79
vLvON7XZKw-NQnrvjUujcaSV5_PmOtwFAsiK0ugJF4RCIQIx_N5VlGm_HynPMJpoZCNJQlUI8o8pJbc7PhfzYSmWJ6I-LgGU4O-rV-N9aPb_lnBSejL4loV7
BNwSok1v2i8DL4UT69gDuGQl9W6ElGLmTHo0vzO9nD4KJxSg1F-mQewOxcbaC5xIwWc-MVOOBqZr4ZyegvFyQlQZK_9qKQdhlH_LSJn43Ppm14SDal30MODK
kjHU4nasDabZD2HHnwWCFQzPfgimiwX7rLSm2eoYdiXlrQnpKDI686mDS0nQFh1SzyFtZkSqwmx52aVMVuBnWkRB_RV9LyWod-__kpP2Ppr2LcMpkDLhuZzP
dwSnTh1w_EKPBeI5Jm
}

EntityColoring(gridsome_icon)
!define gridsome_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gridsome_icon, gridsome_icon)
!define gridsome_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gridsome_icon, gridsome_icon)
!define gridsome_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gridsome_icon, gridsome_icon)
!define gridsome_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gridsome_icon, gridsome_icon)
