sprite $grommet [64x19/16z] {
lLG5bWPX238Hxt_XdQwjltcyc521BsI4Ph5PeV8GaZs38VT3gpSGzzUFvKmtdsJatUA78kYcX7wdUdRZgANkguzkoWPZq-vrVxICknBGkWwCrOq16Pe1YIeN
Jy01bGo48qIoKfFexcEzhm6mab0odGagcEJq1XYfO1I2-6M-qGHGkg1465c2aKgRwAoiDjel_iVwWj9-hOT762rF-IlN3L0iJlMB_akzeHnG3ZmAgAsRPHGa
LCG14u-5eGCrTSfF0fBxfbNi-wyGZDltVzYo_o7hVFWzvu_i4VZu-HzXKuU7xfyl
}

EntityColoring(grommet)
!define grommet(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, grommet, grommet)
!define grommet(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, grommet, grommet)
!define grommetParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, grommet, grommet)
!define grommetParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, grommet, grommet)
