sprite $groovehq [64x17/16z] {
fP29jMGX20L1VQvevP_j31nDe7_rZdM1LYIDmvb95rNDsYQ9L0Eh4fG5kwiaiyz_PxCiKZTiDyh1EHjgmaao2QRhdS1KZEM5mT5d34a7PlEVDaloz-cHtVls
O_dWZExhICLNayDmewRKu1lWMtqX9yZnlbH4blkRdM8eHQ65cHMgH7KVbZYJy_8rtaMo3mdpJbsOY-OzMltFXEWf4TARxnovcPQZ4iiiZwLOei4ZzfO8lNm3
zP96dYAEiQ9Xp6amBiO9UMDl_t9tQiH_dYAlDjZHfuGNV61PyuBwycBGL1jiZp2IVWTIt4XSzxrLjPrTu11ZNZuJn0_TzxnAv3Xt7MoTgFRpRk7b9HiknFUq
04x4fLrHlWsmlp2-LfC4sIDEgQt89TTML9wWyemQnbzHVH-_KNijfTJUVXpV-YNzsA1uX_Rz6Fy7
}

EntityColoring(groovehq)
!define groovehq(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, groovehq, groovehq)
!define groovehq(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, groovehq, groovehq)
!define groovehqParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, groovehq, groovehq)
!define groovehqParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, groovehq, groovehq)
