sprite $grpc [64x26/16z] {
fP470jiW34L14-dd_kUjSUJYXdGbByEiXpNQ0RUl43NwHZV0Mz7_-QhUdmynF8PApKRwlC1yOhMgQrQk1e3pg6W-41739v6FjDOwYfHsCDRiH80SxWdOw_lz
lBGZ-W4PmATFjrcpwo99w6l-IktqdrF5EFrUCvyMyag4x5d0bwALNuFbqvpr1BN5wd-dllcq-HN4XYQ0O0gv-mQx-JxL0BSTHofhm54-7SX0zjFdvsn6dkYx
hXZrBBy8klSlU6vbsychfAFyDFDfrwAPgSpPUv_WDHAi_2lJohzu6pz3hz7D9-JcLuIRRs_yvj3T5yJchwJyxlT4t_mMq9LuFGrUbo-_shBv1CWrpFYPLGYn
8sv-bR3y1GE3UsjTiK8nJ9H_zHcpiL7-1Gq0cK3ohGOitAj-JQuDbZx_jeRhY71k6m9k7z2fhLP_G5Gc2c-V842OMc2qp-YEWzJ_5dy
}

EntityColoring(grpc)
!define grpc(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, grpc, grpc)
!define grpc(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, grpc, grpc)
!define grpcParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, grpc, grpc)
!define grpcParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, grpc, grpc)
