sprite $grunt [48x64/16z] {
ZPO7ThGw38MDiVhL_hVxHgQP9FFEVzECz45K3zE-YRJzgxRFj-5_-9s8zks-Yhuv89zZt_u0E50AwQtK0xi0i4OUPTfkO2kt0svgZWGLRu1Em31Z6W64gJeG
esqEG4Lui6V5qB5ej4R8uC4Y6a3qreSY4naoj1v8MDGBTs97CKP7Fhl35Qbr0oiMqK3w4C2iWhdK4SoHEYA1pCIXuq0C23ceFN88A-18m5MOYPX5BP28I6CE
R3zuBgSBZKN4XaGviV0x0yQ6XruaNdO5P6m7xSWZPcV-nHEJ0fCuCjuYNTKya33ctxn69lnesDxQW3-XXj1Ft9-aDANwPvUJ3P0tpv7EToer7pk2w76_Rw3b
ciX0ivR63s112-vEYmjH5Hf8NUjd3wAhWm5k9KjxnK3hwP5aj2bDdyxRJGl-U3JzuSNTbEb0MFaZvPDcCNUbukzu69a8EniiyP6Uj4Rvv8cd1baIS6G8qyJq
Uhfume7vICnjLe270DXs1_Gzdn89QWxOe4ZlSt-T1YdGvxrAAmvuFrj41aGNX1L2djKy0Oo92sPYHTfM8u0Yn3pTyqnIqlTPB01Ul098_-1TKyzH1Ogdgzt2
uW22fy61mvHEDo-0C55TJjRzcJ16M9cK3vmZRVECkT_J8CoA9-4mAXFJe79wnb4Wava3bLLjtDBAxNmK6n2LOUDZ4wyO-U59Bojh97HhKrrHLJeyxtxnawdj
xTQuigwVbsZYS_PNILhnVujOqzfBEuBv6yzie3VVRvxerwenEyOtNdZXvKz-E_W3D5huQn1cFDjsu28p_eFd68jCJxxAGtQbMWNrWtTRUGrwUBtVXpJvSZ5a
vOzBOeMqZemA7X6n4QnuCl3AKpWTl3R7p7f094spUEA8yP91Q0nMcC88qXedRmwapfLBVVDosW547z39jys0C6Rsv3TF267McBCyUShwM421gHW_P0aW4Hze
e-9tM9zbPNEaomyfu7Qywheap_hi_Phg_4FN9FVkg1MmbDwd8U3wImwC0oV4qLzGht-n56ULm3zHz3xY76e6PEzzh-9Ok8TpSUJpJ8GeByMzCunq7hkb4190
Il5Svqmc-3xO07tMry_F5SEA2RfBcJuq4SWCQei80194dWcvtxqPF281e9gqojBPqWQftUzuLkKXvK0KlceBA0527otxInnWmIpyMtkaUmONl-2UCHVajxe3
oE2FQAfEVWnL-rCSG8RoBOd47BLlsic1K9cmrfdtINyN1HA805wF_gvjg4V1Id_G_m4
}

EntityColoring(grunt)
!define grunt(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, grunt, grunt)
!define grunt(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, grunt, grunt)
!define gruntParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, grunt, grunt)
!define gruntParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, grunt, grunt)
