sprite $gunicorn [64x39/16z] {
fLK50iGm36gK_F_39xDqrauulmq2jPGVnAICO2vFGEOwC3NSJ5MPxYeueFpZJu3VTSAE0681RaTXH0rGkGkB6dwRhx62lEI3tl737l5nbe0kyPbI038IMStn
XqkJFtgMIC3TWKYq5XPZM3OKBK1FsBcJ42tq5mRYdO171_QI7zpp_oO18TuOe9vzf84drPLRUulHj-uv1VVfmSC2nmNpZXcROmNZnzdCmmIhZ5JlR1yFEZyh
3vctSfQWqVaeeuLmF8AoL9LSfhcaQFG76WpeyG4WMH0xVi6aQpWQGScLvUi0ytZGykMeLtAQPepVg_o-_2-jjSUP1RKmQ17sriw5v7UfWcbsAJJt3kemoQ7K
0hLw86SOf2_FBCtjgrAD6LBA-lpzP5fAwNwI-zsS3qhok9AwK63sJ2AS514v9D0MJ8UeELy
}

EntityColoring(gunicorn)
!define gunicorn(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gunicorn, gunicorn)
!define gunicorn(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gunicorn, gunicorn)
!define gunicornParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gunicorn, gunicorn)
!define gunicornParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gunicorn, gunicorn)
