sprite $gunjs [64x35/16z] {
bPM9hYKX24GBrzxG___RiLy39ZepJy_T3CK5aq8RnbCQrIYfHTu54z8NZxwyz9Gc6RuEU8aymFsjN3RH96FK6CUtoA0YsS-GSy2Oj5CZ7acogGu46AuCMYJT
1ouf58UKGZ14u_DIJRgUklsYTUxpaGL2XY1QGb3jbdrev8BMmId9hJ84qPngMIEaaMXrmD-AOjN_QrVJt1GXhGCpzgoCZqEoeonOkzxfq6pM3Kdam5tpFztZ
8PATrkd6kgJkJSvE4PUaZYOpEcbq5lCutiCudJ1KC-ufSb8PnYd24AsJC4HA24L7dgVXW_l1Uqcg3cu0rEJt5ofXfZiBX1XZm1hvVCdepj8ZXHRGhcpEXdTw
hfJIwPRQQrUdxe7hZGOH5h2koKv8gG6ha9qqEyIugyCgKMT62pd0SS8QyzNnu2NWnUDtR6RimlKDvnl7mYvwLxQBNrdn_nZSOutKSj6EUrdFfVC_EC82DZFz
mjqYoQvJdXuAE-uPDxQOhmvi4Ug0mnRdz4ZVWwT7-Xv_
}

EntityColoring(gunjs)
!define gunjs(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gunjs, gunjs)
!define gunjs(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gunjs, gunjs)
!define gunjsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gunjs, gunjs)
!define gunjsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gunjs, gunjs)
