sprite $gusto [64x63/16z] {
bLO7plGu579x3Uv_tzMWwFljJ5qafSFhTjfRZELHLPLXixV_Xxu2t83oyJjxY8nATpFpI81asMzUp0HPFllXJuA4VrVe0J9cQsCiipMdZkCXKIJM5_eIUtg1
1r2nnYeoFxhW869B7O1DA3r0pFVq9AdK_PdilKzFy08-nT2J92y7i1UiMybyKR3trWcRIUAfLZF9MaiAM6-TzpxnfauFhYl1v0i19rcZkOulqPtCreCadZwP
8AEr8FrZTQit0rbtxH8n2FlOsHAOUB8Iogf_RR1HB3bxHh0aQAJeNpn82UJJmu7ds7j_aIXJ9hP0KrrPpDEK9m1Kh4F4v7ji4HYP2hxVnrYu3swoBfSl7q6k
Dh07tuC7iB-Jx_cNB2VnS2YFD8k5ockIOKS4Shh-p4SRvDppASgurfxxr1HDj7MPvshEF9hfw925CmHxcAxBWL8xxz77zlKM3_gMWTbSl3P9eYtY60KUT37s
08FHbdoK-wa7k_auwVUMdKGR91K660sSkocvUcBQEDmP-cvq8EbzOooP_uAaDP2qoKeT3_VNDxxBPp2C6JJRBARo-WMBrS1a1JreiLMx5FuN3AA3JYJDwKbx
o_VC2p6s16A0HXRDcCdrpd_ZFzJ6vmGcM5oBLKTla7FFr8Lx1nenn1y4n7XPlnuGdlZ1x61TXLpjS__OdOzaT3BfhSxfp1SDj7Zo1mckGJgZ-Jcjytc7chZn
f-ucOIpTvBaP4FEat_YcQXXp4YevxiCAEvUFofqV2Zdfsr9mjrUhRtzZtSK_cWnS3mqPj5VnLcQ1b7nS_7tDH6_6aZjvt-Tsr6W7twJeJ4cDn-5USlkdWEZA
0h6LEBGCwzebwEs65OK7ObwAVxz4G-Oc8LsTIk9tz34EjuxTFXbNBltSV7_Tmw-QBHNFYFKZFub-cHUIAJUuVgHpNbQ5Q-kT-4qWbUg-n-lISZNj5_GYIofr
Q9PgG6R_-dz-_du87G_Y0FanYpsk3_mUwf30DJVp3Tl1lptJdlV76XAu9k-E8VRxlym1Oaa0896sTLwVNXJWRUHX_HWvLtvJNmELuUwX4IOoPM7XROeSnEf1
rfgMu3yWraeonz2nlS4iiioApDNRMEOHuJPxdq72Ltvh4LFiaCdv5vafdYmICRxqrxvkb9jv0XHEzdlCABu07Z7zY65H40awLlfyJVuF
}

EntityColoring(gusto)
!define gusto(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, gusto, gusto)
!define gusto(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, gusto, gusto)
!define gustoParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, gusto, gusto)
!define gustoParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, gusto, gusto)
