sprite $hacker_one [34x64/16z] {
xT150WCW34JHu3OmzpzjtTl0jlRN3qaaW1pDYLhYiQ0Adi9Iz8yKV_4Njg2ZUbqa7ikAyE1TZy8KSYf2vrJOIav56fmA1t8g8haGVId6Kc0f0izbABCK7eAJ
feZ3EaOKqOMO4AteujJtYB_u2_0XF8hAKv67XdyKRl1G4W-IrSfJjf64boq
}

EntityColoring(hacker_one)
!define hacker_one(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, hacker_one, hacker_one)
!define hacker_one(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, hacker_one, hacker_one)
!define hacker_oneParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, hacker_one, hacker_one)
!define hacker_oneParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, hacker_one, hacker_one)
