sprite $hadoop [64x48/16z] {
bTK5Sk0m38LXeLbwzx_jhWDD6Vw1uXTDB4zBtoIb53u-ZeZLZVvOcuM8om9YpHK8_nFdFR4cLbLXPl69oN_mKaWMXX7VUOR-tYj9f14zddN1wDTnf5pyJYVg
RxbDL3Dv-m2RcF8RhO4OhPZmQozgTR_KJkMxuGWxnIs5hsHYds87-bUQ7I5iVOncSfXMvDKf1bD17sYVhcr4Rkv0Dxb6LdwIYbRGguzyIw_RbWkfB6iDlOIF
rpeoaRqDAU-tMOxRHWt6N7ftkOpvXcPo-0giEhgmPN-jUMBPVWeACNSloYnw7vu76k_K9ehg_lQAVTH4tiwDrVFeAp5hLnLchTSM741MOsRlFQ_l3f0rveb1
f7dkLVPQcBqSKwtV5szwhhs4CjPQ_VGTTHZ7oaKSgPlpMfkpAUzyNbxDgspJT4fhBulejAOZPS2svWBPN5HE7y9dfLnlRvLRkRsvfbL4GQF3HJy-NfmzzVBN
Hs4tRdfxKKthisRmPY_ZvLRf_2uLRd9xObeZ8_VATdFIuVbAilA7nAwF3NlTqTT8FlsQ1t-6hY7yLJgtvnXjZPDpmQPL-MxEhxt5el_f3FZbUQPohVpIcFeL
buf2HmRbAylfItxbTILVFkNLGxFmqnotbrhrtVX67pnhB7wIR7PVXU72Jr8owFRGnxyUhnN5v6H5vgfwQwsPSdk5yTtpB2ahCSsa-7dp9e3erSrBMrX2Tupo
olThbP6pkfcoZkd2B0bWuMmLUjBJN0v3MNnXR7pz5SWmjkrQkhaRq-iQWfyy4O5PRDiZjK2w0XWZw4EEbVxcQ7ih6z-POmtKDdg7VyPr3NwJl5cLDK0xremi
7xXX2TTdWn__vQZDcPrip2RqeGfdrkWltFdCNxnd6KbVfAZCKf-rj_E3zikBjRG6eI-AL6PRy_QZxXMLDk_n5aChz2jlMAPMu9UVE5lFUBTlF1LaitfxNTCy
aDNauEhPpIgClim22UWrBWOvXjxJROQPUJRwfj8HSk_Qw7aPiv6kPfQ3lalGpxFo_Ok2mSogQhuGlVSsKB_r5MLxEyOJ3VYURIKm0lc_Jj_cYA8YfkquQCcm
_pM44l7_wATA035QY-Hp9yEq89X-dRMLmFsU7J4pbVuKgmbTrSJyaVy3
}

EntityColoring(hadoop)
!define hadoop(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, hadoop, hadoop)
!define hadoop(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, hadoop, hadoop)
!define hadoopParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, hadoop, hadoop)
!define hadoopParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, hadoop, hadoop)
