sprite $haiku_icon [56x64/16z] {
xTO5iiCm34LHeUtkVy5bZrJFQvJFU0SDfnYYMsnZEDDMsaOJUaZQE5oA-JMssuvkd5GVzpgMx7tCfXHTcZAKh3juOL0Asi9xe8A8Y5NLSggPnOxSdCSkf2nm
pZz20YboL3jvLsVO_JkFe6Fp77AkwCtynOurr7x74zNEu0VSxrY1A9sOU-bySU2jQkVmhR1hANTlHS3X_XtEiBDj94GA7Qatd5yG0JSJA9NkGHUoFzOalabF
1PhogUlGOLcxYAszmarPkaAMRfNQQeUxIYuSGsb2syx6C4YJ6wavUtdy6iwlSHVPvBaRsDq3idPOrcxALxh-div_ZCjRy7qJkWDocfCVuhXomyCXXLqtfjK9
L76-j-v2gVnME84lAsaEnv9td
}

EntityColoring(haiku_icon)
!define haiku_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, haiku_icon, haiku_icon)
!define haiku_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, haiku_icon, haiku_icon)
!define haiku_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, haiku_icon, haiku_icon)
!define haiku_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, haiku_icon, haiku_icon)
