sprite $haml [52x64/16z] {
ZPM7SiGs44E9xIt__xiPdLL6PpaHfhazutO1aciJsAAwURqMUxXPzVXxfDCzmZWQxmY0N9a8MDHlZK1XQXwPDPDunzWSwcbwPoGxaCPH_-73SlsIQgRSvJEH
_Kd4J1cTtsefo0XONiy4jCTptFHSdHL15LXeVIAofnLavN9OWLf1_gSHzqmI2EJfphkHjnn6yXkfwPaI484jSpVYJg5uDf8UevpfpyHhOMSGwMpoPAJRAA2O
cUIrhjz2nemTcr7UnlSf1X6HRnbgsFKhL1e5qMR45uAOe0y2ZfwPkWKm1cS2biKLTuxHHr23pjmo1rN01PjHqRcm5lmmPekhmhwhoYRu6FcniEGTSLtQlqeF
Qj-OZn5-5kRqWy0CyNIuuEq2sY2ppxUASnQgvr9nb_umAu4eFX0nwNakFE8V0tqWjGW2xV8j6dbcP79dfEqaODKvZVKCPJDjaf0BaIwAoRN-ClhvzyeNeXDO
ER7-Wge-Ku1En3_9F_gS1NAcIw1ethlDVnkDuq8uZ-XpskaFnhPrdqZPxKOenVE74no89DyUWWtJnstJYGJMNUGzITyCTM97bkbZ9tyjGyPE9dGzIBg_d7pa
P8h_Ugr-PRg9YK0jwr5wNmHF_7I723A5PwZgVfNfna05i3yVi9ZRTtklsO7edeUHQAtispZxfk6C2gffntU0HEstSMndn6XiI-EiMPGI5cTQ9MxZdEV6-NEO
ENewP2tDw4qMVPyowZhFlaS7pUxsN8lKZBtzAvth770rhWj9A-a8HxuIbfF1FGHRkxBn5J2T27NSgdbS-T_bYBXilXvz3pUrxE_pWr8S1CdN7KYMLMdqgx2y
8oAaG-k5DB4Z2dZZ3UE6lMoaclK6GV8UfwXonnk6Wuv-Ed7Rgt4CHzKSEl9g73aPWxrQ6vnsEHddgxMnNSU0jVBLEB8pC05Ll66CQHShkFNTE3WW8sb-5Oyp
TefP6-kDo5m8F_9UxmJsS1KMiShrMgHHFTFnF-Fy2m
}

EntityColoring(haml)
!define haml(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, haml, haml)
!define haml(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, haml, haml)
!define hamlParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, haml, haml)
!define hamlParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, haml, haml)
