sprite $hanami [63x64/16z] {
dPKBicCh24NvWyv_mEzeI7AQ8ddUhExxTycsi0I-mavmWV0JEkOG857wGQQux3d2p1G1y6yPv58NSxYvwmMSWxxiz4V4oi37Deyxy-7hONoqCOi_bYydBcji
kn1kIlzZYggzvHBWyh-QQbRaulVbKUs1Nt9lPmlRylIKI-d6vqRdfrpipc-Q9yjTTk7GjuWiVK1GxVEfdG7qt-IhU97F3y1cMVgSu9lklJoF3a3syPAgiAX_
Fu1szXmX20dxwE3Rir1Hk2Dj00E8-N5d834ttTzYz0UmLgTxv92FFj6dsZRUE09GeqURtj9-4zYUN_Uw6Wa1jFpI0I2wCt9N7BlpoAXr69hq_8Za-4HNV02i
UYWrwN7d38GNwsvGJPzFPqqV0BJln1l9J2NxdZjOhftdZfnkzamRNNUqV_IP-egRHDKJfzIRyE_J-rX8qUS8tmkif0U0nsyS5lhgiHVTf9k7xsvepjg-SO-P
HrOwh-yBBhVlW6lnFR59brxIMwxXU1MlsNtRzQtBp96BveVRFUDXWrHzjmozJ0QCKZodhLvwORTCnnF3Z5xlU-fHqWzV0ef7H5QfLyO8YjxDWOHAm1aCBzrY
96Nx1FNpGuncre-uK2OY5X_TWvHGqK-O3cVwx7yly8It7kECcXrGrFmmVSsU6vpgDNl2o_yXUq9MxlrXzWJryi_JIwFRJzdJ9z6Onzaxv3nx1uvvcht5dmlU
tBN5-kpGmtuHBqPF29o0OdRVpIuOB-0GP5sE-zCM-2Eize15LH7-3AqDjbXYdqBVolu7
}

EntityColoring(hanami)
!define hanami(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, hanami, hanami)
!define hanami(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, hanami, hanami)
!define hanamiParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, hanami, hanami)
!define hanamiParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, hanami, hanami)
