sprite $hapi [64x44/16z] {
hTG7jgCm30LG5J_PeFtlTn0YIYU7yN-_wi1rToWZQ3GJ66JA0ppZMPlIN21pNXhJL5gRyup6CZC61M26lkL_jfCtt4UbwqNV3bt1DMyRcMX0ntjoHrZvEiz8
7kvsdMSwX1N0BoulIbMnhwO1aD_Zx-EUsdf4KuPhQmT-tX73bQqpVctMsczUmtzvbwl5y_2NyyAlJPxxpc_ZkkID_iYpMNavSG9zz9sEm5sFVUbqaiNzw2Ul
BbF6t5jsO7Bkr_hai5h_yhzI5xDP90TGdbMvtbCz1g8SfL3c-8lWCGKh3wpkAtRTVKiMy9NjLj3m9PVHRWtWvZSTqLobTInPTFSb7qPNQwuVt_qmJk_6FDm7
KSjtuTutdq-m_P7oXAE1F8JX0v9uZ4_MXQhe-IJ-MdfcqlHuz8Xn1TaZhQ_fZvtHQ2Uy0CZFgCOa3H1wzJfYlkMrHXC--bMgtFUll6wuG-Ij__9owfViidm_
tkYxZu7JYSz9vegjkVvA925h_KvyagMruLjazpwY69J-FNd_gdzUF09pr_1OerouxjzRwlwtBb6XTyIk6eNdg7FEsfKk9RnS0d_lUSQtFFxt_0C
}

EntityColoring(hapi)
!define hapi(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, hapi, hapi)
!define hapi(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, hapi, hapi)
!define hapiParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, hapi, hapi)
!define hapiParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, hapi, hapi)
