sprite $hardhat [64x13/16z] {
dOy7iYD124CHT0R-_O-xqEkSRKrYLFrKYFuBAVfLEEX7d1aV9ZIIUezByDpvAg3CU8sRmt3kUXdNDfvyztgrGVLuwOYXLv1m0rehoPTUY10sGIrUmGFoPqCk
0webtqbrwABfIzIcEJTVq-ksfvXDOac-cFMoSJxmVwhgdOO4Whb87F5mZzmvq-vEOn79Nbz6gtB5kp1hyBQMOmqgVkeVs0pxaaUtGt_6HV_ENcALvCKbp0EV
F-sAH-Dh_j1_cQfYZg0yfWDFkktY2iQjDhzxC3AVGDja0RQFWnsJW5dE4J47yvKoGFYWcF0T_my
}

EntityColoring(hardhat)
!define hardhat(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, hardhat, hardhat)
!define hardhat(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, hardhat, hardhat)
!define hardhatParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, hardhat, hardhat)
!define hardhatParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, hardhat, hardhat)
