sprite $hasura [54x64/16z] {
ZPRP6fqW38HLThAy_-FM8-437TeoLpdBxv208STFaVEnfIZZZqcKposggXGBlOXiKYGYQOHoRL4i_QzHVd8xqFbGfVFxb9a5UUHtg4iUvRiiBOexb9D7V5xS
-Gq5QV8ze1qgYrbOi5TwwXOMO6BdhUCjBrqikCGhv4fyYsgEqvOKGIMhKoPvYRFlLY3RQ5zb8GgsnLsi8tIkCyZvasJ8OfJUaaaia_AQ46OYPdbG44L4X4iA
tjto8HOMv8e3faRlPiKAN3pu3L5meF0jqdNabr5oIqMUxUYrTyfcXFAax_D0OtKZ8SIgodpGOuSOeBLRcS__Ptc8MMvypUzQUly7ZOCygbFZqUfcPUO2N5Rp
6ddvz-ygMfPhj1PJHUJxbvOv99gQsUXn0IcjQDPxPsnR1GzTcXMrNIuFbI63fLbKgoADfw9P_2xHUc-h-tGiC3CiaxjwMdjcLTikpLkCPhGiH_10WHbIyM-K
DKQb9ULUl-5xeN51XL4DW8OPL6DK7Y33qgBoOvSHKZF3NHud2frgDyCJXQUt6fHRfEm_nSYBDyLBX_ex7_1DQObf-L9vs8PF2vWwG9YMeTeW5-IEoySghxjD
9aeMXb8jx5PzMaZGsTOAeubE5-vE5pKhoso_OwUZgsxS3WRH65qk_jzD50mIXxEE5HoLsA2mdE6Kuhzks0IJ-iPjtY5q4rMkAVWVwaEQ9uTue1p904NubinJ
2llr19s_0ywiSYqXcDXWQZFjSSYWN8AfqXqxkc8cVW0gSOdy0G
}

EntityColoring(hasura)
!define hasura(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, hasura, hasura)
!define hasura(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, hasura, hasura)
!define hasuraParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, hasura, hasura)
!define hasuraParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, hasura, hasura)
