sprite $haxe [64x64/16z] {
fTO7Sjqm38HX4eNY_KyS62uRQA0TQjwVs5E_5PwxHVf_Sx145Pdvql1rGoRNiEkwBZM41Q9XCx4Q5deDcsrur2p8pSAhjPK5APPxb0kfOMihlDXpgdDgjRND
VUI9cLUgru5dd0sizC8u7zZfAS-uLyepxWbd0-l72-5qO4SJlkFemOyOKC9HwmsUywXv-TSONmEKe-Rny1td0_du753EqSqRFEMelFnyV0uKJYkFX-yu7y3Z
Oq1RpWUs5TzmDX3l1vAMymjieDboFX0CQSFvW1Kl3MTTQvIchNVfgFbdNlop-zNzvSTFwyltw0tVLpq_E-RHLl2f_jqfnm4uFplbuN70b3__wliNtj4fnm5p
gfyEt7zyudp4UF5Rl_dDl_pv7TvlSLuF2Av-ZtFu2-VNA8VVEgNrpZaEaCYx68VVmTNRAYVUl8_m8t_wzvi_1awy-dELzzwS14uy2xphorEkihWN9QVhYCGN
y_PujPPVBiGt5XeBtSQMnaBNXUpcjTfUO-6-iUt7eWNTBc0ZVTeDReCaFmFO-0S
}

EntityColoring(haxe)
!define haxe(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, haxe, haxe)
!define haxe(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, haxe, haxe)
!define haxeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, haxe, haxe)
!define haxeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, haxe, haxe)
