sprite $heap [55x64/16z] {
xPS7aiGm20Gj2O7-_-5BAc-l4mMNqrJOO1hDuBnSggaiQPK-nj2QfCJ6iwoN1DHihBAmqwhZNjPYeMpSAnPHRf0fO2_HK7sHWKn2eRGi4mEiJYYc04QhItyO
0aFzt1zx6CpP6KLqLST9K-Hlx-JUOKWcMBkkmi8vHbdfkpOUXgaJVs2Uy9V0y9V0M2gCIGQZicGmijGCngmdPa-wn0pTUjVvRmXZrXcC0pY1APUW64QeB4Qe
1CO1di7OaC64xmaClIjctnYpxuBzOvB4yiirDKF1XxBQRQV0GraHx6auORFxKeb5h0fKvdEC7v4Qqj39YoXsVYLm8leRnMpOamODGrPuL9iH2SM_LyEQ5VIL
5NB7t3PLz1bpwCXnslXEg2knWj5WGRvJP99vvt3yUH4PUaPLUSPDIJn_Zm
}

EntityColoring(heap)
!define heap(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, heap, heap)
!define heap(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, heap, heap)
!define heapParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, heap, heap)
!define heapParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, heap, heap)
