sprite $helm [55x64/16z] {
vPS75k8m34JZNgIP-nztST1RKXpAzZ9qoz_FCW9DbcibpSldSafrdsC9GFeSgm3hvrWds3_7XA0ihrIAVucvKWvK03M-s6HK8Emn3t9_S9LWsrFa4LkKs0uw
Fx2oNLW9wYat09QBYxKhLcaluP4hKCv5OSEXAZW4Z5T0ryFA06Pbaq1GOmE9bRDd4gZkdiIiI1k6RAAqMafjOWCwWcppkW1045gZMqmkDM200BkxB5v2yo7g
2uXhAe8WwYJe6mYgdr511vMMgV8LvvMaXYba9K8vxwIggjXoKqvK9_yIxgOvC9dnJqj4oaYttrz3brKzZCFjObKu0lLnDar8zl4Ev9WIUHVYM9AKJU5rPvIG
LjTE3ODfnR3382ldXS04g-4cDy4e_bw3G-nMMePPMKumK4Cq2eJU11W6IgqrBwVSXWWG9Wx1CFlSfnX1WbSOW2bMbG2bSQKWDssmNaf9Conv8RlBZoDnfoEP
OOkJvfOonxAxoJ2qcygkISunEzauCCjRHc2FaORDYsk3yIj6KbNRm4IrZgYQ1jRjVRU0OLbLBOtbyJgq-x2VO6__1uMSS_BNSPzookUuLm1woKNOp_keSE-c
Brl7l56LoOgkWRZiAmcSjKMNbOHvc-lc3ItXmSIgreGnv-gcvMkl9UTIkzf01u1sjKMD7IJCbi1i1ffVhDTUsvc6BKPe7NikSpkJ0L2ScGg1ISniN9adELar
WCKTlzVb7MDO3yaJuLmZwQKDFM5BhQzDhw_rFOlzYmozUULVTR5YbqQVAoDVnhu
}

EntityColoring(helm)
!define helm(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, helm, helm)
!define helm(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, helm, helm)
!define helmParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, helm, helm)
!define helmParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, helm, helm)
