sprite $heroku [64x18/16z] {
fSu7YWGm20NGh-cM-rztDSlqFlF1HdYGOHTP-31MY03APDVogGzTDkBigtxXpN9JurzyzOLV_5XyyCI7Ykn1o53X777HBaGTVERWnNZNTFTSOmW1tTmNWLsW
LZ2iGlpVjoao20Vl59L-j9PhYmt5DUPClxm1mmzUVKTEVYtRVWxAarkuaSWCvEuBvzviLcO9SV1cdZvcoTDTyufTjz_gv6iKzll1SrIA_IAMtqQBLbp0hZtl
xXsQFdBVBxVyW3ffND7KlOONw9vkBkaNN_e-Q5UR4OuLPLQ0-febnknnDqHRdTARNlYFabu21ltQ4pAbqZUUBqxvr4_JymW-p1y
}

EntityColoring(heroku)
!define heroku(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, heroku, heroku)
!define heroku(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, heroku, heroku)
!define herokuParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, heroku, heroku)
!define herokuParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, heroku, heroku)
