sprite $hhvm [43x64/16z] {
ZTGxibj134D1QYu7sF-A_O-ajlqGdkfYoC6UqGxQlPI1p4gsdx9Toa9sAGlPfIna5_ATfgAd7_IL_g6KXUnI5h9BMSWkPI6xb8NiKXQoIrd8BcKXkvI5x58M
ilUd_Cmd5NtbSyLsECWxtjVb2_8yaYUGTxyix_DLcGygkJybg6y6r3S3Uae9Ua89QXbGou1Q1jGoe9O1jGoePK1FAK4jtxUKdTUpRtiEPOTxYjsyxvwPGA8z
Gtg7SW8vb1F8ePn0ZhzL88To0ZcK4yYXd40EvKIPSg9CEL6cd2XJJfGf9ygK4sNAYJBbH9boeapf0nxbTm
}

EntityColoring(hhvm)
!define hhvm(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, hhvm, hhvm)
!define hhvm(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, hhvm, hhvm)
!define hhvmParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, hhvm, hhvm)
!define hhvmParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, hhvm, hhvm)
