sprite $hibernate [61x64/16z] {
dPHPjYCn348ZMxP5xN-_tM_AR8HI_2Ow95pCvQusVAz-qLenzdAJjnt7PDVQ600xRkBM0Hphf7K0t5faDl2jurHcXZ-ToMnUZ-Fpp1fkufbnJ5Tzdbd7LHak
op2fp3hfnrMVuxAhyHbS0rTfN1oJpepteuABOQhX8lquaPbZgnXUo2omrsXzf-PMSAQlOEZ_dBm2OvYlMibOJS9P6llhXqQCwIjOEQsMZvLdkAOOgyWQQcgi
4bn3ZXN75OMLd6mFd65YB2sqSL2OBlin0B3VjrG_yAomJPIY7uJ9rFtWRR1QFpWktW_vvWDX4XF7fVl1SKrZc8YUljHzBrHMie-zhf3ppN1o7GSugwkQKslQ
4csz3h1-QkiXqfBMUjgDPbQPziuoIp5fN1oJnaLsf9ePnwHnPPYqDS5KnSKnwTULOjAuE2QT6S5KnkNqI5jpJDfwFcBw3m
}

EntityColoring(hibernate)
!define hibernate(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, hibernate, hibernate)
!define hibernate(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, hibernate, hibernate)
!define hibernateParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, hibernate, hibernate)
!define hibernateParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, hibernate, hibernate)
