sprite $hipercard [64x28/16z] {
dPG7ckKe30Ob0Ghb-zzt5_bhkYVFK2-HVa8zs_9YNZmN8Cs2vuhg-EIvW-XyFPSm-_1SvwrFVv_NdO_hV7uS__KFNVWBtWI-uyf3U5S3pxyr5tpgGtNdPPGu
VvNlWKSVCdb8SOgcDmZzVKgd36IVMZP19o4aOx3cq54mpKRLMEOvJ9rXPibSOx3CJFdKHuZDEKsOYbY663OgPOMCMB8oawXIGyN3BDECB_gMB7TNtIb9cEgx
HQSBw7Xt76xjnwN0veU-tJiKUg2kVJ2c3bt_asDGVNrWEgTuIc4j_1jzQcob2mdNNPyssEZQLdg7HKcwWavsaQFlgTOV4Yar1KAgTrI8lswxFgM6WLeN7uw-
56yRwOAfsKwfcisKX25cAqJD59lWyke_-XwAfxzxnOpYWOoaEzxIRgstNf7K5trVe5TyY_rxIl0Su5StBo7rRy-kwFo1ubzltakElaiOHzyLwD5tlts9stX8
mrqwfxpy1m
}

EntityColoring(hipercard)
!define hipercard(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, hipercard, hipercard)
!define hipercard(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, hipercard, hipercard)
!define hipercardParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, hipercard, hipercard)
!define hipercardParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, hipercard, hipercard)
