sprite $hoodie [64x15/16z] {
hPC7aeKX28C5adZ_6wympyps_lt5GcAtnCDQ8OhAPAUr3W4U42NgG35IGoPl7THIv4ArPICxAURgxr3KUf3SCUcUqA291aCTiZP8NDUkTTcqPx2Zfb-0jxws
UmNJQfHLzflWuZEb_U7Q5bZLX9xvgnn9lCY6_KYh6Zxt8nnfKTYFj3y1gzwinN84-TnVPKLWL8R_s7_bj-QVR-V__VNNc_L_ll_rhVslD_DFvG_EdrNEetp-
uvx_HxUfj-U_LGzKEipzQvxVl-I4eiH1Z6JZb1IU
}

EntityColoring(hoodie)
!define hoodie(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, hoodie, hoodie)
!define hoodie(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, hoodie, hoodie)
!define hoodieParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, hoodie, hoodie)
!define hoodieParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, hoodie, hoodie)
