sprite $hostgator_icon [46x64/16z] {
ZTO7hlCu40FWQ1gfxDx_l7yiqmMEx9T1UIKVHbH5NZTbXMgl7wk197xbnKNNRzX039xUNcP_jGRJHtkW0FypTRo2eq0-9tAGsRF40_RKkaZa_xHLfpr52G38
nXWh0_uNYFiK2FVub5ieHztebc3uKhbEaCYuqwr0k7jaUF6eydbaiXQSuGvH04JE-T2nwC2mgR7SssHZu9yQpNFXwQePjp5BPOa2moDM6swJu6g--hpJmcJv
Q8iIcoOHLjO0vEzYhrWyiLIktZvrdQCNhjs1ycRPvfkfC0Xb1-2lGDgSgtc4RsdI2pSyzoYXzieJTey9TxMNJv-UgcDPul1LuLzh8hmr5zSeRJv378kOykFN
woiYtBN_Q_lmY0I8cEG0trhodMCBzvK3phv7aI-AVxTsKwlQS9X3-dkEJOkEFRSfIqqMkro_X6y5zPbi98vZhehp9CUwHpluL2ErplMHI8KvgiuQM-W2tCUR
dbcOw5JexG80us_0OlpwfM5wG40L4gmN-w8xXevHHOOm0K2SHEBTYVx6SIEYUi-XrriQfxYZzxlZjDvyznfwUtyiQiDT1mkd9L7llSm3ukoZTPwNnAwttQFs
xkVMNfWyt-Q-SW0ambNsQctsbeXlZxoywAnxGbfdMtfQYu2qU9JqlFjbrmjJAAxUAHoKdfTB2uFuuMkFZmac-BVMAsYks_YNzlQfNxwB7KBQxwt4-VTyq77L
X3tZJHl8fom9yfARxBIRq9tdmHD0x-ppwCOEzjEgUG9lqEUw4vqeEuzdxM6nUzqly3y
}

EntityColoring(hostgator_icon)
!define hostgator_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, hostgator_icon, hostgator_icon)
!define hostgator_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, hostgator_icon, hostgator_icon)
!define hostgator_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, hostgator_icon, hostgator_icon)
!define hostgator_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, hostgator_icon, hostgator_icon)
