sprite $hosted_graphite [56x64/16z] {
xTO5TW1120DGBDp_ndNFR9QfMvvM_XjW3JkC8sq_NjsDs6NPjodVKO6-3-RIqK-3z94gzClah34ESjWOozXNMdeT03tQX20ikKITL4gtAHgRoEG_P3qfh5YM
MsBvstv8BBkePHNFt6ZMI3DsvXXS7tOySYwHtLrAb2ZSKR5ma-uwM3axT_Nd7HxYCyVvEUxVHL5yulXrW1WvVdTDdNczmb6nUyz3VVppr-LdBdkTbCuXNjZ7
hj0YnMxsHKQGMtwH0poVbowm-fOa__APMnoM1oq3wejS_fgD0guscFcIbXEPUc7LNt-Ms5NxU-kiJUHuBzTA5wiRqyM2b9I3SOWjFMq_8Hkx1
}

EntityColoring(hosted_graphite)
!define hosted_graphite(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, hosted_graphite, hosted_graphite)
!define hosted_graphite(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, hosted_graphite, hosted_graphite)
!define hosted_graphiteParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, hosted_graphite, hosted_graphite)
!define hosted_graphiteParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, hosted_graphite, hosted_graphite)
