sprite $httpie [64x19/16z] {
dT17biKW34JH8eCGgltlje5ZElzu1yxF13WnNaR6ozpWDnNF2DdX4FuGCBaGS8SdEmx-L31bCc3BgWv8w_XSNt_sbNH08Js-YSNX6FmXdJvhJuXAIclx658h
gEifIfq7trHRGE9tYgiNJh7oInPQtqz12Y8NYyZsBVUdfoWfSP2zztMK8AGr9JkC3ODMYd40BgMKbUIQskaJd55HlgrVo0WepSy-a6b_Y2KfAG7Br_uDTjHT
djxsZku-apQjtfKrFm-ys0zLxVrQl-LRVTXz-9h_M7qaCn1RIhoa__fCsWXf7QESNTtxPsHhHbDUz6-lS4OoxsDfDE4KG0eI5uiypE48jJeWrmG4KGdhs8Dm
kAeIWLBdmTVUcyTNZmTc_-_JYxpN-y5jU3pWlCC_l70IZ_Ty
}

EntityColoring(httpie)
!define httpie(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, httpie, httpie)
!define httpie(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, httpie, httpie)
!define httpieParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, httpie, httpie)
!define httpieParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, httpie, httpie)
