sprite $huggy [64x9/16z] {
TP450Y0X2007i8l___PMDwx73dhwHQ3l9L7tKW2HPtfNi60SDEYUpulsEUSmoho8vBqaO5QGbOdBe4wGvkv3uTZeIXyWS_1lLWFnGdI3jg1vqhXlgnTBtWcU
AHuWAfek58dmEBcwMdZbwq8z8veYwcLlqjOQl89Uqmcxapsm9flfc_p91myCTpTxDW5TleJ_sZUBNeuSVHwpQjLbRonKLyYU-PC_uvSrB7c5Ti9kUvCrhWu4
DsxI44uXb8VPxlmJbtkN9-rDJY6Ucx02DsNf7R7neF9EyfNTzDbyDy0F
}

EntityColoring(huggy)
!define huggy(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, huggy, huggy)
!define huggy(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, huggy, huggy)
!define huggyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, huggy, huggy)
!define huggyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, huggy, huggy)
