sprite $humongous [64x64/16z] {
pPS5ZcKn30GTDDx_kijWJVfhyyPB9MwvGbA8g2yMDNEFJxYPyY1C6ujPHDM-eZpRiZXXP0_rEF0T047-3WHDFpBlX53G_I9gyYOqh5Cxfce3ZCmQS643yhrI
mE0HpRE-VkJTmTeZLk32DB09D3Y0aN86SG9sr5CyRtt5wzJzkT-ElE3FeazQz9jV-GRzl8JzdJurgVb4Gpp54Cy-e7Uwzv_J_YEVta6FcZ-BFjVyVCxPiJPz
OEPNrXQFr_xsk0Fx4WzHU33ViuvpeJ9yVwZhSVfat4s5UQ_vXRNsviHUW-YbxtiqkWBxixQlZ6g-5FtzZ_rLzESlAXlsB-_FwUwwsXCVx3ERDJzY5dtl1Vyy
FlgjlmCEeCUzZrPWFFTNqTzb7zzhyz9dIgpdlk0urgMlb91RdzCvXuzFkNq_TNpxUBlfFdSqB3BxjRv1OMDmCxxMCpf-T9xnYVKP1zmyel3_39C0CFHHgT8K
VzkzT89CLijrnfC-0W
}

EntityColoring(humongous)
!define humongous(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, humongous, humongous)
!define humongous(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, humongous, humongous)
!define humongousParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, humongous, humongous)
!define humongousParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, humongous, humongous)
