sprite $hyperapp [64x15/16z] {
fP87ZWCX40Hx4am3lly_zzXnjXNNjJcKL21GTFRRbOeJt7qZsmz-1SWllf7nYuzatW8qp_Z-2B2PH1E4jaw3CKMoqoNfyCw6w8nM9FEun6k0BQNtXYdBVM9g
I_YV2zGdahg4NIzymru2ZCZGiIzJjdr94ZO0PIvaO7ynp5wGhEjhW8twQ_ZsTKUeIFaZC96xI-bOd-El0B_DNm-q2x36t3U39bmTCN9AdqnmZlpoAm1tb0qO
UWI974UTW8pZv89l_n5Gw67Y2tcSldr9vjdrKmJf9_nJ0Vy
}

EntityColoring(hyperapp)
!define hyperapp(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, hyperapp, hyperapp)
!define hyperapp(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, hyperapp, hyperapp)
!define hyperappParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, hyperapp, hyperapp)
!define hyperappParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, hyperapp, hyperapp)
