sprite $hyper [64x56/16z] {
xTT7WeGm34JHGZPO3bZtF-rCvx1hIXlItpyo3f19CriA4CsEDARSZ6xEgjaSbPntvRKlzFhbusWEtoEQmyy1mNZV1CYyhmCmTDeNN9gCzGtNXB_-AgyZKDvw
mZNfzFiJ097__Yg0qV7-H_xvN-k0FZ_4LmkylZw-BdWK5lXGx5cGH_5tFpTxHRw_RNhr-DEVVjlVV_RvwlIdt_RxAuU_VdLwx_v5DET2bhD6ICfq5_uF
}

EntityColoring(hyper)
!define hyper(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, hyper, hyper)
!define hyper(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, hyper, hyper)
!define hyperParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, hyper, hyper)
!define hyperParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, hyper, hyper)
