sprite $ieee [64x19/16z] {
fPDLaiKm30HbjcZkVzmj9-jGFSu4-wDbflyaItGZmQ3XXY_6nXlbMciSxvbmXhB3AdHbO-dJPm2563EUI7Q8fDX28qq53fNseIzdlud2ooXGhtulImB93hH0
cq1T550IR3tO_KnBLYKzWi0wK9EEj_9J_t6nfCxmKhruLq1Sqz4t6QcheW_0mOP6ZWmqWpDizsTuA0-Xh-ttparO035BR_n-WZb-oxQCNy9f_3MEX5Kf3s3E
lqS7JFgtyp_NtuB1fD75Bu_dVuUzmCFzvxOaaZo1kV_5HP_kVoII7U8Hfc5iilV7p39rsnBFm3livzy2tKZoz9Ft1m
}

EntityColoring(ieee)
!define ieee(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, ieee, ieee)
!define ieee(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, ieee, ieee)
!define ieeeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, ieee, ieee)
!define ieeeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, ieee, ieee)
