sprite $imba_icon [64x54/16z] {
nPLNcW0n28AZWlU_yVPU81ct_A_pmK2Q0VOT9AiorZ7iTn2L0_spISR8u1xKdaVS6umys08YbmEjiHR9LlWKWROWVGGDAtI4MOXWRy0o9Jp2eUOElGDpwe2O
jiWrTC3qG64f4aE35RMraPCQonAOwNM8BNbTruVGEdqaU7a3xxMU-Ex7lGLKOmz37LeFr7drK5vQJ-hdz_3kdCgnHdhkNX8IbPy-CioHuuEmChuE5-jhuXdP
ZRbEmB_AItNtX5nv3sVoKgVE4rHdtWEry9wG8zy3cTqZV-v9sTnJ8lf-_TBHTNvgzIq
}

EntityColoring(imba_icon)
!define imba_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, imba_icon, imba_icon)
!define imba_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, imba_icon, imba_icon)
!define imba_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, imba_icon, imba_icon)
!define imba_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, imba_icon, imba_icon)
