sprite $immer [64x39/16z] {
nPI7qgiw38HL7Knz_xUzaeL73Bu3ENt_0jdL9zS9t8Mi9iQhHw95XU0B6LrCgbcDSbg2hxYNXfGxhkfmDdt5GoeTzw4bEk0ZJgt6bJCGmxc7Ae-ykWG1EHgG
xuS_-anULe28p3cJeeY9cuccHvxmjfIOVERqH4lCFXkq5baWpmiGlTRxodF71sCKUdpDxoTsvlGb7uRAdUSHpNmSCEj57yS7rYpF-WH8NsuGnVRc0MZViJmW
XbSbJdXjWFY28BFqmL3RLFCY--o4cLxlF_RRevTDSxN74zvFZBaLKzw2K7XFedEKNdfhyBvxgEFtbvZLlK6wRGgtxqeJZvPxeuxZs8T9uE0GXJTeFuuDVa6o
hWB_KCICmCm0KWgPmQMm1txLKEFkokcrEAp6O9cMu_Z0Tkoo-Kugp8TfGQ3ZM7MtzurfTQ_6QVdhFe7dcrW-1tzugLV7Ox6yQpyzWqhxt9fXl7JUB8cqY4-1
6l_XoH-hoce9k3SX-h2CBVYKpiy0KCqI0BHSo77p74G0jezOm_9fL3o2wRo6lq4mwZn5la3qvDMGQZ9lzPmll0I_EhyOx_qnvbJTyvBzo4tXrZzv7ldzpjlV
CY_BCizBfUW_yk6Lpa_9ys8-d2BFl-EdpXVpnEiM1ln_VddW1LQ_8OkVDlTyyNmVnlzGxb_oSHCFj_3CIwq2dphvEzVQrgVcuLId_cuFBo4lN_Tzcytf-Ny
}

EntityColoring(immer)
!define immer(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, immer, immer)
!define immer(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, immer, immer)
!define immerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, immer, immer)
!define immerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, immer, immer)
