sprite $impala [27x64/16z] {
TPC94kim24DP3UZ-z_sBQwPkOgihyq8aN4fJpFILq2xR2zQjyCU5tr87_OY3-bi9_MgC_XBqa9IiJwMdydDr5B-GppQkf9Ua_hivnXjn5HCbZDvAA0cW1nGO
P80Sq43I0FY07CLvGv2w8Yj0piXnYJ7H9Joy03-EF56S3Wgm1EfjDdq6WE830Ki1o5zcmBJHmiDE5rdVnXvXaUxNVIHa5sClh7Dn3mZhs_KqsSRTvcqyuDpt
bubgtSw0M2dNKSfgaWAaV3b4Xv1FdHJJD81SLaN4CzVQtl7joezrzT_1KRgyoWBeqeaqX3eX5ddAFaJeeBoHdkoi0lI2ycV7sCFsBjYUgspx-NEF4LLRGgDT
kePql7VMnikfnT5Ex-pElRVoHF8VvKAt4-JRAQ7esXLd5FTpznxhBJq7P9xeb4AIkIuf9Efg9VU1zJgLndNFYAkCBYZsdhy
}

EntityColoring(impala)
!define impala(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, impala, impala)
!define impala(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, impala, impala)
!define impalaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, impala, impala)
!define impalaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, impala, impala)
