sprite $inferno [62x64/16z] {
dPTdWkGi34HBY52Ixt_UBwmw2Ep1ddr_9ZuKY8qxIiNVKoduFL8KW0mse0X-GsbqLq1fB51tw-Lfr6P-72_P2F3u3xSc3zpkn_-qa6q0VWH-cy3BFSPBjWw9
NuM_Ywzs12uGMjW8E_1w5pZoxlQsxSYCw_32RmI1Ccm2uvYmWZCbXUZ0i805UioudkLKdHSKlkq6s4RFSc10ipSKbE5RNQRX2OoltT8gI8r9S1bPQ3dusRSa
ztLAIhAjpsqD-dN76h3OL0JZidIRVxdQDl2YNUHUJtBKFJSEq5blfz0LY9KKzjmuxK1V-rwdLjI8tcsYHq8T64jmowNegyQw12y0q5dpVhLeU9xdbWfFD02e
nf9JrLm9WKO5hb8d02Xjv9Kr09j2io1GphR6xwXfopcAJtk3WilKsSAUWslDBUJN1crY06YqkVBUqwQEu_lQ9cBZJMqdq-GtCzQVxLY-KwiibJtIcjQpFU8R
ITFagVtyhcaPDaE9EKo5P_ghpUm5q5Ksqe8qPudscIIIj1zXHV4BkoJdeUqfyz_RzktQGplNpRH7djabdJ3VjGQCHxPWV9oQLcfxOkUrnkBRfk-RrjD0ZrAd
fB8r5L5GxuFtl4a4DHyqV11Qio0-x_0jysrUfzk9GBzhUAhQ0K0z3pQsia1ykKQPdnooqLa0BZTHtguc6tqKO9nlSCvwvsNWBkibUBxzhG2LFClHu2yDRzho
bfGs-sIJvUb1VE7wS17j_32g06YUOyZwubgVmaLhQxMMkELjys1R3ZeVcWVNxkiXEAD-p3X7gwgrTlhvzCPEtzEtZ-GztlOFzBsi-85sdpq5Fr9u4xXYIxMD
smLtAA_pjoQFFqWkKQqhdYFQQHunsMl1DVy2
}

EntityColoring(inferno)
!define inferno(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, inferno, inferno)
!define inferno(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, inferno, inferno)
!define infernoParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, inferno, inferno)
!define infernoParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, inferno, inferno)
