sprite $instagram_icon [64x64/16z] {
lPNNmgmm28GbnHG2ll_JdcR-w8wuMK-Rcstv5W8CBcTHI8LR4r7LxKMgAj8QbnpTOejM1iYMjkGCEfkmBIqEy2ZR8sbwmVFsM9KEl62jL2vIh2dJ9RgsiWRl
79bopeUOZo9pn-CNdVtoWLoI3kIzylqZ6xGjAZrWE6LVbmTAFUGHlYsFL4O2w_xEVHYOspuxxHTMbeNxcuzKVyNoe-X2fEEhkTPJu_PhX_3azhNNdKO5SdgJ
FlaGO_1quTsu0Ez_irfshgBxSKvkv3-ozRz-5DwlSQ6JM8RbOsnwuVO-UC23s8QbB5BzUMoRrVsa4yCU3H23pq22ORlQYISSxcxdcdDfFHcq2EzdBdpGJXTl
6DRaPV27dPi_VVVLU3_dircj_Yq3toM4uHlT67R6hv0ebBjE-7ixHpXfyoItTePVRDxhhPt1QJOVy9QuFF9xFlP3gF7NvN_mnUBZ9_bxN8SuWcdIFmK_um05
cuTJoRW-EjNc4tm1ntcPy4xj2UYhDqxzMpUhXL6XiCXZ0bkXStI5yBY_ZFNNnk70rWBak_rPHrdA6aBCOu4sCddiD_5cIhmn3stmk2vHhUF0cy-lhDRZnth-
t3m_FMldi9YmgShe2oWKqGuhZz-npvBl3Kz-pQNa5EX-7RG8OpqHshauCEn4MFve6tOkt-E2OIV28UNXb_8nYNQks_CRX3sel1XsZg6TLyEmS_dQ0RuQDdgY
DoYvSDXPo32igafZKws9wEca1yS_atWmx3EXdGFha-2sOISKsXb58RFeMrIuH7TclWC
}

EntityColoring(instagram_icon)
!define instagram_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, instagram_icon, instagram_icon)
!define instagram_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, instagram_icon, instagram_icon)
!define instagram_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, instagram_icon, instagram_icon)
!define instagram_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, instagram_icon, instagram_icon)
