sprite $instagram [64x18/16z] {
fSy55Xmn30DGsKwCklzvwuKojve9wUKl06TQy5Lq77-SsqtxnhF-c2jFVEtb1klO7_eSVEDjI7xtd-GdVWf9qrH4AN3RTs8ko8aumEds49iG1RIsD7XA1axP
-bwlHlDXGSYxX85jevxDE6c771gQlY-IbzHc0MSa7lxEdG9cvE5zNK6PS1u4JNYIgWoSf-zUyG1GUNv_fJ21djRd5TlnQ8e2fvv24PS7zlHpLyo2pVf3cZ3X
hZCIT1pUjyTwQqCFdFRsgPppfHyeKneBi-c87VR-_cGb7lxoxF0jNKZfmdrwMGHXzmsz76ETOacoPNYK77bU2uOqOukB8NAqdnuw5sXU7R8DiS0vSTctsSK3
G6SYEUwlulYZSG0JW0eWkiDsUXrLt-CE3HlvM0XsVZSxENwPCx7-dsCyzZ--2fVo7pvHXN-FTfVWf_a
}

EntityColoring(instagram)
!define instagram(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, instagram, instagram)
!define instagram(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, instagram, instagram)
!define instagramParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, instagram, instagram)
!define instagramParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, instagram, instagram)
