sprite $invision [64x22/16z] {
xPH7sjmm34CVrKZW_WVE9ocz9rxz1HiLuh7CsFRF9FvQhuFNo4Vy03tXC_gp-UMxw2x1La2SjRLxl8VFmTOkNn6nPiHOmRW9Db0QKmLJTdN6thVS_hQ3Ivky
tKDsY0WeRoteTYmNmovPCIn2javwtQQlkq0UD2jOjm589vlVQsIrpUT6cvp8TRstMhFtKK7vg2FtmoyxPuTfXJo1SNVGVTLt4EGaJcFfrIqE7tbQt5JRreEr
-feFqekm9_rCrQrjk7nhOzdzLbt0_Aw-e38Ofv4vR4NPReS_JEZmB7kq8I--uGE24mJA5jDEkFDVpnsnpg7Y6zurfjQKhJdgc2Ep0wCMp99Mq2iXPgbcGDQ0
blN-_NZ6Vm
}

EntityColoring(invision)
!define invision(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, invision, invision)
!define invision(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, invision, invision)
!define invisionParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, invision, invision)
!define invisionParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, invision, invision)
