sprite $invision_icon [64x64/16z] {
xPI7Zkqm24G15s3-_t_VsxLoSPeSRsyvAhSEccEZu3svkRdnafA-8IxqHCPhoTHuTGEcHdvh_glwUokGtd9_8XK_4W_s7-1Qgs6CKg20q482FBTteXXHA31O
l2zGxdC7I4GOgBsBKi0-iASW0wddQKMPqg_mgCnCnFBuAEFJhm_zzca9iGB-E1oVE4BkGjqvpUHbqLyBLJJgHDvvdSXHPZQlrF13cL2J2NtPwEjERKGwqVUp
QVFwibSRO4VzMBZyHdsEQQ_GZseseQ_hON9OJDCBVLklIzbKI-rOnCVR4-yFjr_Q3toPzq8BljsUvbZ6_Jad9kAkt_jJuj4EC0LvU_keCu-WskFxTVMOdQwV
m5oFwsf24nja9QUi3hW-OrYX9UTY-2NStDpy1m
}

EntityColoring(invision_icon)
!define invision_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, invision_icon, invision_icon)
!define invision_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, invision_icon, invision_icon)
!define invision_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, invision_icon, invision_icon)
!define invision_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, invision_icon, invision_icon)
