sprite $ios [64x32/16z] {
bPK5qkum203ZYjp_jB_q2w5KdknO9x34KrUGXtSdOfr8H3XAS8e98lIydC8_JBSfmCfCriwd8BMZmgSbIdbWomng-y46obS_ymsAMmU-ajVuuQeJqQt0N0q8
4qXZ1MYjNrojK8BtFbPS-VvSl8TZB8NOB9mk1TSzuBwKKxIuHVXK3wfdNXbAuxqwdjP4XVJfBAGVedRGtPcvsoB_qfo2HwYlAQu4yiRNnhiVym-nIK8r2NO0
oRcWQsdO_ZG7oIvAa_apn3SVZmzt8UnjaiCtItZoFKcYvMZ6tqh40euIB_xgQDny4DyLFeCz6J_gxXccxaecDa3wFz_vHcne_pp-XSyTJO6_hXykNmcv0ml9
xX--xfyboEMS_tf-5FiORRyzPWvvP-wWzIC_J22mX5F-mPoyRdq73mEOUrT8FbxzmhUnLZw8Ked2TVmalhvVvVhy32q5uH8S9p_AkJpc6Ghe-xdlBzLFXJZN
qCGtDuG8YONaR13ccCZoj8glEHPAPhqiqrdV9MGB1FDKMFggghxp5S-sFJXnyEtdcjeFrPr83Nvhu6pHNGbr834Jphg2tm
}

EntityColoring(ios)
!define ios(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, ios, ios)
!define ios(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, ios, ios)
!define iosParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, ios, ios)
!define iosParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, ios, ios)
