sprite $iron_icon [57x64/16z] {
xPS5hkKm40JRW-tx7tZn_yVkm3AKM5P5Kr9WWYNHapbm5E_v6GOECOhpZRO3Md9UOUsTDpZls9bgFPzXx8nxfcqhRe5CTKu5KyHfw0VYDbAVuaIgY9CmP9nE
5LDgUW0zpy2HynpD-OUIOqqeCJ1i0On2JFJYc5eiv5o9SjHU7ZTIYOGrdqSYcIWj0XWUUKbbL_W0jkxD3ZTyiTzCnzkrQcv1idA0RpSpiaZEdT0kuX3IV_6G
ToEYoLrAPzW0taGQCCopcjfxkstiSgFqsms7qLB4Y6ho-LOoVPCtWXjFwj7ZrWzoefSHhiI0HxuaO9JY6fi2rXhExmFFYdNIu-0vp_K6e1U8u56jXbxXjfSa
FQzUotoVobIBiOuxlWUo3GkiAUC4Jhtw2PAxudJgqPyMQncdKqMSP2JLJuvErN4V0G
}

EntityColoring(iron_icon)
!define iron_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, iron_icon, iron_icon)
!define iron_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, iron_icon, iron_icon)
!define iron_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, iron_icon, iron_icon)
!define iron_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, iron_icon, iron_icon)
