sprite $itsalive_icon [64x63/16z] {
fPTdOcGX38CVnLZo_U-xVKa3uI7VtnSNX9mnpuRIR02C8E7MolCArPoCTv2mcetkpbX0MCb4Wx63uvIXWQ6WgUZYZ1De--8CZMx163bygS9WPC4YWOVWd624
G2GGuHB_Q1h6guptVcUy3FipGLp08hlFIr0OLx0fxT7VWrW0KPuVBxXmsu2fmqsu_IEewzKIiywx5xShRjXswh5-2BTOWrrcIlKch9K9-SRUn1llcIu_6QQi
THvkk9gDytGI6rtVCKXYb-CidnvIBT_PGae-uG5Td_d_xyBzEGV72WupgqAzYSSQaZrX0GflMK9xT8huiu6z9k95ZIviCSvh1QlgxPznXF6WiliqZcoH8lbX
gs5LukBusmZjZVSVXSt7_dD1270o9vZQ82okm3VtZvfQNBMzxq_W5zkdM21nVNWn9JfS9yY7lxp6OORVnDFByVMYNRl6ReldBK1lpnPcetKyIRYJyG7IUtaa
dK4CQxNyUqBFwLSFy9y
}

EntityColoring(itsalive_icon)
!define itsalive_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, itsalive_icon, itsalive_icon)
!define itsalive_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, itsalive_icon, itsalive_icon)
!define itsalive_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, itsalive_icon, itsalive_icon)
!define itsalive_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, itsalive_icon, itsalive_icon)
