sprite $jade [42x64/16z] {
ZTC9UhCw38LX3TQHTFQ_u6kCGvC_SDklGvI7bnb4FR2AMHRPYG3o28WOKGLN4Ml-AGZuLL_3YXrHtP8iCr-PgLg4oHnifhBocF-CaHpY8nOT4QWkW9Kpd4VR
x1xEJfhmdnB5pspBvcSc4dolP32J-hrD4QbFcHn5KV9xe_ufYwWIxQUDXlSbsH3btKR78GLRvf96tcsqoTm7qSTdjzv8kWZ8clwKIXR7dPp63Y7raft4dUGG
ILBtWQgoy26xglgSJBJf-nQO4M2yP8V9aNgU-_V6FgKnPLuIybCqQwspB-4qLIyvv3rLsTMMU9qxv25mvjQQ74wozKdcUKQGvWYI8K_LASkB3fBwJTJTvaUV
aZLbaYNV-JGTfrHdzY4HSfCX2r9B3bRJaYhFvPB1uY5DdWDd4aGU4hziiwTCq32dvth9ypY37BTec6Zo9RbaFHnXytexOif1tfsJyoSr9kb-_u0KT_iUzNv2
vCnSNnFVKYLhoNrEQY1pB8oDhZVk9UTKpLttdjzbRldSbWJzprAjhvsoYuL-lSsz3oN4s6YHuMQc-oKx_f-JcwXY0Ae2TX33V0mat960cyeQPfd9MR5voAjk
pZG3l2dz8EitLGQyH1rTGEKOy2p430WL3xSOgaF-bkwFwxpsjEVhsyZCOugSZMDXhaBtmgCFYRLuoPt-dyIxZ7kvbsyPbhDpOSnkv9w6n2LredTfcS2Vf6V6
bFQxd1yZClrR0XZlCZB7eR_bBDubCdsEyI3LnqjcfdacRYGma8ajDSzjvlqPvO-qtEblqdDdlycHEzyI_yfqh2-npoZ7aeZZtodtrnL4iFwV5oHtuvAfo9Mz
ILmIyYD5rqucbFEM1H2YM0sPESx-0m
}

EntityColoring(jade)
!define jade(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, jade, jade)
!define jade(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, jade, jade)
!define jadeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, jade, jade)
!define jadeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, jade, jade)
