sprite $jasmine [64x64/16z] {
bPU1UYih28GZgZ1v_mU-oTdm-LlZtfPpsXh3Z32mkZvEPcr4I5B4wBKy_cAbkQJdDCcx_HPT7LXGH2k_GGV0gqdz_nZCWTvDQhVmhf-0RSBjl7YiKFa_YrNB
OmXLS0hKh5YZf1fVuKtGoVQIXcOEjwb3vLDb_Bow1j374FsKkofR-39auTyri8G75n-wZ9v3cIHd8yCgY-_7zQjECZYkMRMouNCQ1C7e6VoGVyDN1GYOWN_y
IjAfx_WIpx7vGtietwIwuNrgMowvac_vH5_YksIeDYIiOZIvW0EFdDOC1iPzRISru9EGYkUQPGvX_Ia3Vk1x1F1Uf6c6KcBaK-iQ4szASQr7GzAUGSe-puTq
KPGb_je_OEdf45tbCmX69MzbgryTmKpxf-R6yDzZK9Yop-hG_AuYWTwqpIM5lM0lUy6vAQzhUKVwuxbOp68ifZ8529yfblWblg9jKZv8bDQttONYTk2lccI9
qjEsxIMBUyIJ8j2D0ASrxNXInB9jli5mEE41kVcunnzqRHx__hGPpbkAuRNi-ApV14jlwQgaKJBITm_6r1xDalq3S7Jxz4BOQtBegdaT8L341MnYIrnWR966
pJ9B4mNzo-UdlS4PSk83PyD5uUYf_X04t1fE9TV7Thyylm-705k_jGpquAB2_OlI8gjvjcuH-hVzimBWRg3RzyySCZs-2eICwMpxztv-h899HZbjzHcKOcJf
M339jZcSNud0-La6uv7OJc7B-Uce1VHjkjWIdmYDjJuo24u-2wNMagMBKhqkPh--lwHBZYJBcOAD0-4o8KrAu660gtvh-5mbBOXdyEgOP9FMTRujXCLHoPsN
nFTlw7xp_Xpjvcu2xOu4YbxsjITQL8aQBAUKeJvjdEuFj1hhzILyl8ptbxD0wFrRKzZVRt_xucTh1mRUJUwjkKXnhChPhF-Wa6BKlrt1Q_VGjQwFTXJjFm
}

EntityColoring(jasmine)
!define jasmine(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, jasmine, jasmine)
!define jasmine(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, jasmine, jasmine)
!define jasmineParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, jasmine, jasmine)
!define jasmineParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, jasmine, jasmine)
