sprite $java [47x64/16z] {
bPQ7aiD024D3aSJ___2LcBLdKbbTlxmj8g3nxQFijYLiuhw5C_TmxD2ctC63iODJErP3tBgvOeEck4NBnhHpvoeXdJKt_tPANhGZlz06hPi4wGEJYeOnCKa_
3c5yfINHkku-AFT5sw2h9EzVV5xlb30OJlKL9CK8npBi8pmNdfDUkN3QPDxGFqTUexiyDJMRP-FG9bDaVSp8hHEhIE9excAvvMnEs-qmyxpVsMaKk3yaf7ay
3hX5fhyETy-a2jS2XzHmA-9np6ev3rR5stV2cgzQ9Qwgi2VC0vJEd66fArV_ahYa9HvmutKwJzoXOvb4P8OrsbBlFbCy-3FxH9lQQIjb6pGUYsCUoRp2BHz2
kek3Fv67w-hWI-7nQ8VgGKBuXuptIF0kP8RRv3bbBjk2oHrSLK96-ByYeL9yZAHggLeFKVEbbCmNj0MGVUpgJ1BfRxPaJ4g2FyXGbRF-bTqdfEZs1JLFuXz2
Uq9uj_lZk2Oe2KUdtIn17GDtJ5rBvt-4jXRCTPXdWXTHTSphrMQEwGEEHL8T84kH6UvcxS3-vCV5g_FZGHxeE_TjLeBuXVu2
}

EntityColoring(java)
!define java(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, java, java)
!define java(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, java, java)
!define javaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, java, java)
!define javaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, java, java)
