sprite $javascript [64x64/16z] {
xTHNSWCn283X6K1jaU3-fuqREyZTR5xrlIGklrTb9FXcMPPbMHP4X9_HTj4G35KU8eCBma-INf4zkeaQgV4UMITRkD_qJWlsMH-aM6-ZxwqDlM0AzIW-xQOw
Sd3-D2y5RmZ_wRsEZh-12_NGRT_nOD_qHXeTwabqn-b03qKTftWFLISDmptaeOunt0DM2Pr0xtTOV0mvqhlCrlTOxxBeXU2XthSolG_nkIUkOF3p0X3RESa-
JgpY0RrxlczIzZCpVElBtKrAB_Fze9Mw_pTTdhsLt8RQxxx4EhEXe3Mp2Y-Hw1s6YoJwe2EyTl_LGVQkZy3VVutwz1G2WvkwB_TGvkiOX0jCg7RHYz4IV86K
4k7BjzCqykK4
}

EntityColoring(javascript)
!define javascript(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, javascript, javascript)
!define javascript(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, javascript, javascript)
!define javascriptParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, javascript, javascript)
!define javascriptParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, javascript, javascript)
