sprite $jelastic_icon [57x64/16z] {
dTPNbiKW30FG66oGcFslTtfb4EP5__SGfTcNZ7SWx7eqjOCauO-nqi2FeDTpPW7-1AqSEWV_1c6dvMO9Foit9wzQ0OgWsVR4hcLIjUxe_de3clQoazOWarVL
YUnnodJVIVFxrmjAsMtNSmmjcxwpupsI2XVZ8q-22bZvhZufJs713zDKb9l350OdeWwToc4IcYxAAIdWPpaT0KMv18foEInz1mHKvNBe77UWA9V27KFjTo1z
kjc7CAwFE1-2tHOlL0vHff_F6QGlXjW1N8yaPmARoRyUTv0bcKGAwYEz8xiv8KPG2WVh_uq24ke7QT6XeQxgOb1II4OoNvk0xrLBqyuuPD1tWzMWPJBAdGeo
MHvC5bsoiEcJEpkobQCvnIchxTEPGB7QYwh9ngghdYwEbGAYNabY9H4QgAgoNBheBChfECLlDazG_BpEgcwkyWK
}

EntityColoring(jelastic_icon)
!define jelastic_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, jelastic_icon, jelastic_icon)
!define jelastic_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, jelastic_icon, jelastic_icon)
!define jelastic_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, jelastic_icon, jelastic_icon)
!define jelastic_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, jelastic_icon, jelastic_icon)
