sprite $jenkins [39x64/16z] {
hTI7ShDA38RXbNRLzP7xlzkpW4tA_9vwNZey6ILn6NzYpGPGliRdPk3eKBKer2V8KG5dEkCLi7ygAxLSMrmH2VmVAd9vCl7JTZh-9hdYKaIFSym_YhghxLJB
vSK2H_nX1HCFOj9ElzMK5Q3V8o4MkTdiHVoEEDSl5gaHvSHBJ_MazejL-6Po4vB9FEUfblzKVkJ95jzi6V5ouk6QFnNGtVbcarE8Qqslw7YK8j7cU0-jRc7I
ck6hOIyraGa9YyDlDjVaNGRHxCAwMRLNSgQdyA_AQNLqlqQ6Lv5DeH-4zZenfIFkiLqUYRduLuk8hVOQKKrZ26BNoRJcWsYcMlgScH417IFR8o9HKMz6IwQw
BKdjs7KDGiPPzc7qKYpHtL67tYp12_6gOxDxSAmffhAuAiuWrczMlS6CawtES5zaYAlsV5X0Y4cTJ-qHnWlrObNri2xQmYz7kra7yZMetoo1msZdkRRYQK02
-OjbexEED944qZtxE51nkOVLVTbjMhN5XjLPo6XSB3iY-zWuiwhBj-ewry0NAXEvMVbcZOoik-x--ZgoWVhQhBfZWn2SinvLjTbsG1ytgysWZ8n2_c0uMSuL
bPkTCnDpLDsl-nE-ZewQidnbrpcpQWmzf-B5-jpGAX6aflsQQMCGAXAHDpiFS14jCyk-PXPuZE7OFd-otYvClAiG4V2newxekjbzw0sjOglkQjni2B8w7dQv
0pYwDq7CsUjoZiB96kXpEpiX6iQJX-QuIjoissKoqVrrdU2SgZouwMAKoCqoYyOxFPaAoQ9HCgvuixFcRzQ5jOn4UAIEktwnzJ3PJASJCL6kDwix_SN2oiEc
rdXLkA4_R6q64-_CUcQmuuBvi0b0zv6Onzq3DwM7kTJuLoIHcD-CYyQ7Kd-md9-OviE2KpynVduvhcuUdth-U4gZyJ53w9fJr7kDpv5bDz1Tzj4ybiR_bTYw
3dFyohhM-D62dtEHlncXplthOgyN6vFlwntH--VSKZdBAmV1k4mgADghU8HPtCmm4nHWnIIuhZ6wXc5Do8InYfwi828ZCEHa3NinPkX8mBidOZZcO7ep3yo7
oPgpe175Wwh3PlLok29dbtQlX2f2QwN_1m
}

EntityColoring(jenkins)
!define jenkins(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, jenkins, jenkins)
!define jenkins(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, jenkins, jenkins)
!define jenkinsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, jenkins, jenkins)
!define jenkinsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, jenkins, jenkins)
