sprite $jetbrains [64x54/16z] {
fT87ai8m38LXlITtfzp_jfk0w7Y3dN-6gNnMN4JWOmoKqHZJLdI37CaAOzwddFPoYXZnSUDMn3cV4_jzo4ybxVPCBmiuwStP0LfUUjDeTFGUuLyNmDWRF7MF
xcK1IdS8wIaLENUEJlg3RznZxpdMPMl-AFnwZjFwjVJhEUv-iJgyfN7p2q4beKkFjyhsPn6wcZYl0pwjSzsydmlNCL_e7RLKD-ZdNEQIwrgdjUw_fTHN3nB_
-00g58LO5590wFpaQJLzf2e20v0T1V1q3mzIBv7D-NGGXG8al1Fl9L-zQOiDNsEiQKvXdcDCPOavn6NtfWyMICttItslnqFrZCzwpfVJtdrqqYk--sMsZdph
_OarjRpnXg_9MfxzEs-__qTDhv1MvTWJqiodiXVpM-5WjENY9Uy-yju_TjsAmVoN7gERmNZufYc7XTWQhv3ZlF7UqPRQ-D0xsk8rVSOskeFJXPVHlLp3tZxQ
SAVtLqsnEhqBmRvxo6km8-iEtBCtEhf09_u3
}

EntityColoring(jetbrains)
!define jetbrains(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, jetbrains, jetbrains)
!define jetbrains(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, jetbrains, jetbrains)
!define jetbrainsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, jetbrains, jetbrains)
!define jetbrainsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, jetbrains, jetbrains)
