sprite $joomla [64x64/16z] {
fTO9ZhDe38JXAg_S_yIJfWVS_Z0XqVzgHpo582j-efYR2ZwD527Er3rUkSjdMktLUJsQn_-vuZcr8oLU5Ozm-O1N2a1Vl78-S35h0spy-GxKMbIFbWCWYTvv
KAod5ZqttpDfM7K_MTIMF6vobz9sNzpcndRBO-fndyiJDvOViYUkiBZF-S2DeFy3Lm3YTrm-uG3T6zkxSbKT-9wO5rS2L5-u2a5fSqHbwmU0dSlwJceQy8K3
ZVFoyTF6vVGSEQ-7s_Nrz3FFbFMup7xcstOCoEZbz3BpSq17Nsz26_avmFP8gzExW1TU0pe_VrWSEQMq4h5LSklfRQ0ucDE04ZsBDb0dpGEADMy3nOU1YODz
eCxf0xaF4DUa3nI_3WYcs0Q0-u7UF81l1sZyEz3kKUrvm3DuSmkQsGSKboop3xYp-3Am4KkIUHqe_ieaomUMF7zh0rRybVyTqE7oUzAUGV5b88VBxobgm1MM
bKEsCsa-wXo0Fd83uAUt_lOu4fm30mTF7-FjHxqJtQuSY8yyw3E7ZvvvnEE83lps-eZBYJEl-xVRrs-FtZZhyiCxM7sv5ZNR4V-TPV7DvD0IsOj-mFQ7bcwn
jKBgup5NV4u1oFUy4Y2Uk6tt9UHRtZDxuD2tFkE10vBl1jxu4Fnct_ZZG2ZEwBdjvSNRoa6TVf_5t4qG2qzEjtoVBjxXtHFlo-u9jYUWU4WRDw0D61wphVB-
KG_11sbUla9ezTVnEThFGZhnwZy
}

EntityColoring(joomla)
!define joomla(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, joomla, joomla)
!define joomla(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, joomla, joomla)
!define joomlaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, joomla, joomla)
!define joomlaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, joomla, joomla)
