sprite $jquery [64x15/16z] {
dT054Yiv38JXNpA3-lx7NRkIp3wcRy3OPU27hEs8LVXJzarpILVzJMgkVWkdy6WzCwLPknH6wmbABv3x61MizSk1eN2SdAZEcuTgbXhGf6oX34kDeQjJf6jo
QuMIg1dloVoL7yF7NHYobDDTmaAfALhTsdJ5FCPTQK1tIWUlzPKlQrXeSbJ9gpPaXMzrzwRDkgcyLfhQ1YDXi_2OMYwrLtKpDA5fPRqi2rL8qbOaO3J8ixbv
DevGIw-yXJhxLgTwbTPr1sziwxr8cGbI7xqvHvAoIykXt0L23GkLfZ2k-geCQNBP6CxZXfmbnTuXhRGLQqkfIdkECQnhSJJ5EvRcB0PuuUZQS58lGNkLPljL
OQb_xkOjZJb77zs1r-rYkRQZPaZbo9-kGYdEaKlYmqhllN2aBbN-tPB2-MSUYihV-Gy
}

EntityColoring(jquery)
!define jquery(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, jquery, jquery)
!define jquery(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, jquery, jquery)
!define jqueryParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, jquery, jquery)
!define jqueryParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, jquery, jquery)
