sprite $jruby [64x46/16z] {
dPPhihCm34CluMrPslzklmTjneGRtA7dRtB0YHYrFq7EkAFaEt9RqlojFPaaSVZEdg63_HjvMA0tupUsgsBFxPKAfeTssQWJ_ZGmgc695HkUsk6FnZXA5lSL
ZnMM3t5tcLyhp9EONJVuOGFI_25kKdq8CvSFMTm4pC0Rso1jITo47O1Tsyp5SXkOmofGS5wXzimEsBFDfR4RDuyzGEoiCjkfh1StjdfeecwjjfrmyV9wauIb
bBs-ak6tTl_oNU9QIbbGZnmNG5WBVsTVTXu3ZFlb_GRO1UzcFveacnUyGeVTWNCBJECf0DIntM6tKD7XMzl6iqjk6JLG7FltNtMwIv_qgC6zJX8KobCzQdWm
oNczIXDplJ91SgDayt2E8RbwK79G1vIyVbxxwH8WPdeDGE-R1YY9fnGbzEsgc8Tky6E0dmy385gbJi2mcmpdtW1XnmFyPM_N8l9sWDuN2RtXMkrWII9e7-3h
q2lW_1kAorp2RbW_3E2KXFddZi9QTnrms9R-TYuULHz4t8UTCktKfSixSMSCYx6jxKxSEMNrQ7umjVD_87H6tCyOPgFKY_lHENn9j_m5
}

EntityColoring(jruby)
!define jruby(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, jruby, jruby)
!define jruby(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, jruby, jruby)
!define jrubyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, jruby, jruby)
!define jrubyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, jruby, jruby)
