sprite $jsbin [46x64/16z] {
nTLTSlCg48HXCTqp82JjVxidT32cK5dnkVhU_9F7OrGMvMqkcO6aAv8mIzizIR5RfAMLWluGaIRBOKd0UW0bgVMNd-T22YJGDcrcAQ7Fr-2NPLFByojpLsty
mAP_pFZLMDamNptzthm8taTnicqpXliZBIbRzsvcVD9qHGBBtkXmHJcOhbNTdmaU3ahZFH4DOvrCU4Guu5-4XXaH1FXC2GYc27c03nGKIvj5gwqPm6Mh9A0h
5R9sexZq-mfXG4FJbOgaJNcMVYgoRxquQtx6kPxnrkTvr18VnfPw_81PgwFk9MTTXNQQSzabprNF7MfQMFLpixQzBzHIbeb7ARN_kfjmyhwmEpt41mxI-wpg
gMdFh-VYPYopBamRN_lC_ZlwEfLxWh-r0CoxlZJSXjOhL6TTsqePsjhiqlLP8lOXrHxHi7JHRCP-_VfBdwDvvRhse3NDAAjQkyuIb0uoSlrvz4TwdJKt9Hs4
HzwFgxN0rh7dS32w3jTHohg5hYdTcba7qMDeUT1rsvMogr9qGpeXEsiTrjV1Yh6aDIqjMf5ecJx7gRphX_wP9dgSjN_G0Abide0FUip4svfzgMM_qnHL_gUc
tF_MkO9_QXS5_N3xGaDxg7xMZ2yr3de--AMswh7la4vFcYQTIm4Zqe_c7pgEWmQFu8ys-6VjUXK9DeAsRuT_rcYStWJSj6zmrShS_NNOWj2-DonltJJqbZTk
R2s6F3c_0yz_0YB2cgx7cymK-wAx9lVIVCWCFPkFMzgcRBvGAXy5RLipUlYjy47Nae4U8oSiRNF_0G
}

EntityColoring(jsbin)
!define jsbin(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, jsbin, jsbin)
!define jsbin(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, jsbin, jsbin)
!define jsbinParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, jsbin, jsbin)
!define jsbinParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, jsbin, jsbin)
