sprite $json [64x64/16z] {
bTTdWl8W483XwNHo_zD-PJTb8AZn-SdmGhQgy0AofL9RxwqaOuIleEP_vNReBGSXU8fJwxEMWmd20v9RNwdHJ0a-eFztjvNUajcdPx3QtiXcflpsyidg045O
ur8_Q4d_8rYHKZ-Begh2S6UjFz1CH5O7sFPCbHy48-tRGv7b7oRmg6rFDU4V24xfZss1Vn1SOlz2uVa0RhsDUk-j_hFuPUvDwHV2BhTPYSfCn19Ac_KuzLBd
MWaHYH01CDGsoKU_7v2hrseWtC5_dEk4XxdKGH4ufZjCTIJe3uXZpk3gzG7cjs0PC2nWBawDu6Zn19QaU4CVnz51mPbsvNW8Y2bVodOACA2ytgRi-xeT6i8e
PgTlXoJfujTXyc9VjNGf_QGmeUIqVcWXNUgrJ32Boxw750_f_3Fi5Mv273OUeby-5RYnvKRVvtRASAFhFbnoguUqwCCfrOllwyC-ruijb_FZNksKoodZlRT3
A8wiUthJntB9RAVabXKcfFwUKoGzfNo9C64zXEmOoh9F1AFrjimWnqHYJXU30PsxGauE0iaX92SIU2mxJLu0m7DaqyWXESJaH040FcWSA9oGTn9Iz100w1p6
aIposnN-W6aQPC_fHHved-yiJ1JTcEzZ-4Kx2JCJsh7UXxZtYEu1HcQc8g8MRapWW3krBoWu-8E_oGcyRnz06HP8dn9OOda8PYZ_QNuam0tcxR5Ai12VvXbX
ITkJkaTuXNB_g0gyeRM_rIB2MsZrvIV0tXB1HsYbBTL8y0o7KgUs9aNu0bigTLToa5VnNm
}

EntityColoring(json)
!define json(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, json, json)
!define json(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, json, json)
!define jsonParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, json, json)
!define jsonParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, json, json)
