sprite $jupyter [55x64/16z] {
pTO7Sjim48NXzxPXiRd_VIFGinCrI6BwbzW6oy-2AI1Ei953SPRdnUbEyZ1mZkKN-UqPHTJCL8LeCcuUaf53S4NCumStUJebOrwm6wh70oCMZU7Ivyt5-mLY
sOQjCyCYiQUu5PSgsRVQS-A6Zo00UhmXUCHuJrvLRYeaZxqKDTzt_OIkn2EgF-_yfjcNJbonjKVmcgpGxrwietUXNZ-YuJCQWIOX-9IuzT05dsFF2eapAFWV
HU1dpCGZ2q1SriZN23Q60NJ5yPjHCno07lj1foMG1LWPUfILimPO4u2LCgjo054HSm1IkGwD0hGpQ4q2KOee0NBsGsh9IXHI9RZDUiGQa0gmehES8g8La78y
oHG0AeyxUR6p-QsMbTa-6ySm4-Xiyd2TISLn1D0Az6Lcbg6pKOBbEiCijwmZgr1R8y1hOiaoWTGqKGUqCm8oQxedeELPDGYWNtuTJ42ogfAGL7mzsa8Sj1Ga
3b44hWwo3w1VPkciXrwEdQp4yomhi6MA6rJs4SDB94wHlkwfhi-6-kSTtT0y59-H25vlV7H3MeJUhG76Tv56X3zPSUJrdHO-NHNjUIdgpnT-kLvCIJIoawus
NTTBj4tLtSQ-Ul-58TZGs3DYENT35xmaTY8ICvFDf-7-iyFS8zo09chcxcOgnCvn-UvszlFWn0dYdUaVpyu_PBEhAJdTkH4dgPzyiUy
}

EntityColoring(jupyter)
!define jupyter(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, jupyter, jupyter)
!define jupyter(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, jupyter, jupyter)
!define jupyterParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, jupyter, jupyter)
!define jupyterParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, jupyter, jupyter)
