sprite $jwt [64x22/16z] {
lTC5UiKW40HWLeObolrlsqKAzJwV9qp8zySJ7X4U3NAz9jLt9UkAgxqemBNHiguhXMlZ7bMPSmrNXzmNfixZbrMHntzGzA7Cz1240WEWkliKV46dbnp7_vPp
DX_tiypqY9b15DeyO9uVlUMaU-RcWuYSX_z5AudCFgVgEgLa_9FVd6b6zvvZypz6tGBg3BlsZGdzx7iPVcyZQmJNHZhmDHu6QLxYjLxgAO_ZBuboXO-Md9k0
dBEs3T1FVZzccRw8g6bTsRj2DVhouBnbze7EGsDUMZ4lqrCvOQpL2w1kL8RVijKHEUUTPgavtTUmyrH60DMEZ4qnC4iFj1T_wnOkHG1ukJ9nldKAu6hFQRNv
9lBLtXMDRNbxQTu
}

EntityColoring(jwt)
!define jwt(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, jwt, jwt)
!define jwt(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, jwt, jwt)
!define jwtParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, jwt, jwt)
!define jwtParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, jwt, jwt)
