sprite $jwt_icon [64x64/16z] {
tPPRZgqw34JzTiZy1tnfBgXQK0ITtrw_Q6NRbSUs_35Kbrz3rbY4B1YpLHP4PeQyadFEpHS_dZ-OlE3p88NZaGUXGj5j7l0UDF8YXDBpOWjU_0LjCIOeLZxy
CBB-1dq80mMm20RqpGIG15W4DK48n_8r0f-WXR2EG3VecmfX7S6Om8MmZY0doAVqrW6hVZpkgbM5iGwOZ-OjgkCmUgVIqC72zqlk7cEKx5JlO0cBXNy8bhtR
FxIAM8DAL_5tVq0-w3ZB1vKBF_DmGQ5yKEOH3t_hk5pGQlqaTyKZ3FukgpZn8vhWjvVOLKGCEkXgGa45nVGMYo8Ho8CayXcHFfT8kU5DPA1HtQ3ota5sm-qc
BvpwMKLLgB3FtP0fwjdfaCddWaomH5i43NncybaWBy6YS4bOQRy3UkJt8uDqPJ8ekH6GKGLolT7F2hFlLBbAGWPj93j-qdCGFMxtvtmdcSzkLOfOZYtGVBYA
1F53sANECNS2VcQ4im9KydOjAhVTVVW7aSzxQlrR3fEShxwBUbQ34966hFYdfNwQoBa4tfdyNxwEmxRoupepYMV68E_q93uRhIoh0g_ZISwrdox0JX7O14C_
vWh2cC1MSmMd9iZLNC692VhVfilraFGTmVUGjEhWUqZwZi0d69_J9V4ttZo8TGBQQ9uJ7qSWCIHHB50ynGQQP_Zd0IuCzum8rCw9a0LgyiVu3m
}

EntityColoring(jwt_icon)
!define jwt_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, jwt_icon, jwt_icon)
!define jwt_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, jwt_icon, jwt_icon)
!define jwt_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, jwt_icon, jwt_icon)
!define jwt_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, jwt_icon, jwt_icon)
