sprite $kallithea [23x64/16z] {
hT07RiCm30LGxd7_2pS2Qr6MtDtV9g4V62BuS8j4XC0UDGGqtHGTHWAt4xMdsnb-PzwE1CxtDUA4v79jJUV8u39pdmkWgQM3q6nZgqNdYstzxMp5SZ4yCzMN
zSxYuvq2xmpgmke46mDvAa9pZwKr-no3kl5rUx9dqCwjpQKrDPyAN4-MoN0mbvxiK276ObxPt9mF5XlD3OYLRJmCflHpk_h1vRQfCrm-6Jox_T39balz-SJ0
pmnwCMNSAl1ByMIA83YujNbeJct6rcPxASF1NhfpbXuiftQnEziFMCuZzieetCoq5RCJtsBX2YqybqJuu1x-b_E9tRtv3DstuqhpZpfv0m
}

EntityColoring(kallithea)
!define kallithea(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, kallithea, kallithea)
!define kallithea(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, kallithea, kallithea)
!define kallitheaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, kallithea, kallithea)
!define kallitheaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, kallithea, kallithea)
