sprite $kde [64x64/16z] {
xPL7TYGX44H96zp_mZDobVG3r1LY9nChtCUae-_rfpyX8znK5JNY0PxFzg5Y_AKZ5eapFgu1yHCUqYxbLtZvuBNmw0Uy5sxzW8_2jH_ma3QwJmGpx7ZbR8UN
TH8hxuNx7VuYmyGd-NYxa4YBmREFxzw6VF1A1uxkUES3PpnKijfyu0mB6Fh2A-vvI5rquQciYGjVUMDvxrk-1NT_dUAFT5z1EV4GqeB8q3f-y3q84o1CfJ9a
Yd-xDy5OaWlFPF_WiVBxwiFpZzD-m6-BDyzNh_fR-yjdzfiEi2S-tFfl_dxYQVxAoi_va7py5W-k22_v8_REgtTzxmUu_5NpIA36Cr_W1551O_ikwRY1Ar1Z
E-nC-QZwEOJBSihNVt4KBMEKk7r9pTrDswESkdshnj87y_yvqcJGbZs4ge0-R0ThXLHtmTSD92PZ-DKNvWTBL6jE5lY24zOK6je7W_PJ6H6qzz6KnppoLVq7
wq__0G
}

EntityColoring(kde)
!define kde(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, kde, kde)
!define kde(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, kde, kde)
!define kdeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, kde, kde)
!define kdeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, kde, kde)
