sprite $keen [64x14/16z] {
fT05eXWX30RXYVn9kF-1AnJwt6TTlXLWvywFKl6Zh8ER2o23jue4egQJKvBDBGVGE6zL1LfAJR4B1Qt7FYU0L70tvgxa-bWEs6naaeYs1v_ZODqrmcPlD5FJ
nz-tvTfheQJg-ivLG3NOCZNucCQmvSUlu6--09FZCcy_VaskW6b9a_yseGOcZfz7NaaIWUhuyRrCPsROrDyDJtsTFndsgyi0xpWUg66B0vzxN-ACie9Aglzc
N4yNlKViR9vwOgPd0a9aWU-sDx_ho82zEMUTlvcTimOcjow_6LyiXVeXySL-0m
}

EntityColoring(keen)
!define keen(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, keen, keen)
!define keen(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, keen, keen)
!define keenParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, keen, keen)
!define keenParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, keen, keen)
