sprite $kemal [64x44/16z] {
fT45ZiKm40JHc3sBzp_jvp2KDDs2WFr4DJoNskbilQ__x_6r3jEAn_VPLu-tCFdcyd7amUVJwAFFvz4ddw-YRwFFeYy-to4_-g1vYv2VV8ByvBFe2-Gdt_Rv
sV_iVF7w3ldG1yrRXFpaa-Wpv2TV83_v2ld9DyXFlk_oeVzR-S3-Sl7Xc-Q3uZFa9ryWF_aA-Sato4--gpuC5Jm5R99FGVCvQhuapTUi-LOqtwlcJVLt
}

EntityColoring(kemal)
!define kemal(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, kemal, kemal)
!define kemal(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, kemal, kemal)
!define kemalParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, kemal, kemal)
!define kemalParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, kemal, kemal)
