sprite $keycdn_icon [64x62/16z] {
dPO7UkGm28K1DL2v_tLtZSY8YKaod__TDDkFyf36WcTacRDNX8VmN7EksUcfVBC6FYf-lc3u0kdZMBBc2p3QdAF2PunvS8QiMP_gARA3SgsjrfBmZ_gF8mG6
5dPPUalUldDdTL3It1JBp6CkbsJvnLBcEjSJRBfTowfMnM7frwXtUG63kZcG0CIUbrRoVohtQSijNVBDrOFuhb8P5W2lOZWxrwZs7Q5KapUacwqqhiI303kJ
cfYk_Fkvt7N2HWMF3w0LNAJAOd0XQ_p8G_BhRbBneT7nA9GhOdUfoOsAW79CZr1pYa_kkJmH6t58KcC1iiJmvUoHXzjIZZmCG0cWrP_CMuE0v6Tux_I14D2N
Mi_UzKoKgZTncrJZxjS0A6_bAkWYq2upq3UDYtpafyeJeEqw4zourXxvz0G7TbUBJkaxj3yCsBTwIEUoFVcTekLJdDx5vTq0HkrdoBvxJtDnUGO6YBPV_QXZ
VT89bllqrq3tcFoKlq2ELa2VSu3N9t2WE7sA1Z1KpnBxd__KzsdrHmKWVzVNF_iNffVSNyvG8hteK8fuCYZ4uY3rFqVpBv34msVr7z1I1RkV0SLJlNb6qvqo
C5h_Ve2-Vd5atUWIVtoazmRejlk4qJRwZRh3DhblWUQdX-Eyvpqurdele85HN4ZB4y1hTdnpkndirXGExJE0HiTJRKW1O4qVKX18I1ThJBNNVu8VeBuw0hOV
vMakspjn1rPSbO2yvQl_9hy2OFG6RGIGh-o3VfIlSmQ2p6_gz3htZVIhN8yv3QyBfJ6BC5Sz2YNQ1wCLs8S8oRBtgKaglkueYUVbx3dWE6eVOymjPyWMI0h1
1bFjQXn-5JcOJku-rt_ESHxP3enpT17f_QkhaK-NWzo-Uy5MhDYPy_LDnuvwRsoJ-RotlDn8F2xDbgxfZx-yzTsd3qxlc9iCpJKwLwqsr4y7tUP2H7YY-gDw
3VMVK4-hKVr_ashDPzDw-vwW1TX87w3hntRDG-guYaTun3y
}

EntityColoring(keycdn_icon)
!define keycdn_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, keycdn_icon, keycdn_icon)
!define keycdn_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, keycdn_icon, keycdn_icon)
!define keycdn_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, keycdn_icon, keycdn_icon)
!define keycdn_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, keycdn_icon, keycdn_icon)
