sprite $keycdn [64x19/16z] {
fOzNkgOX28C3A13Dx7-xy-X_SNf_lw9qWbUKY9yH4q-uf84V8GLiDZiDc3-lhxryxQvQoY4nyKDSz96LOspj03pJlfhPyya8ZUIX1mF09EshYSedQsUIFOji
fmF51ipm-3s_kj-hJsaSZpk0s8DiktFdIg1PIBPxaHsOR3ksnPBaHXsij9VKG7AI2S38IfvZ3d8OBrUEaMdxrb673Ue2L2TP08BiN72oo8aaBKW_to1zIjCz
fB8jOcjvIq0oIGvOF-e7ILuPh2RDIIyMMXj0IexJGqhS-h77BR3pPs6IP1spg_BwammiBU1sSMc6DB2FotOKcJ583WMAdQHVoMQuVTauoH6W52d5bDoa1k0v
cfT10irqCb4y1D1N7bgIV9x_FrbB22a1bDQOtPsU2bZtG7N3YcGPCEvu6AK5r9PsWviOUuSNnLRFEMiDxiGJPW0YeZcVR1nHJ-pRD7hjpG6N72zvgFyGIOqd
il2AMJKD7vBQWJ_m7m
}

EntityColoring(keycdn)
!define keycdn(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, keycdn, keycdn)
!define keycdn(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, keycdn, keycdn)
!define keycdnParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, keycdn, keycdn)
!define keycdnParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, keycdn, keycdn)
