sprite $khan_academy [64x10/16z] {
dT1LmWCn20JW0SAG3RBtF-tlqhxsYxi0C5BnCcLySC5hF8AY4Q506j8lnnCI3opnB28Syf4lO3mFAl11VXBGZKy_JHz07je8LJgNB0Tw4gZfa6gkx1J0kntH
RL4bx6avTLbsPVFGEXGI3hW3tIMexQExagspyD7SfVSoyMiuotlVvuxREg9sdWm7J20_zqyKjQ_SnK8xrjtzETris1nZxoRNe7oLpcsaYuYI1jH2nN5DTbuy
d-spWNtsj6ULnTIHh4iBnrUY2Z06Wwx_l_IJFnBv_zB_GHd_p5VGy0flu1q
}

EntityColoring(khan_academy)
!define khan_academy(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, khan_academy, khan_academy)
!define khan_academy(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, khan_academy, khan_academy)
!define khan_academyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, khan_academy, khan_academy)
!define khan_academyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, khan_academy, khan_academy)
