sprite $kibana [48x64/16z] {
bT1NOiCW08DXiSIy_tcRWJj54_tFdmseUj7amUImV8Jb4ooVOVa2onEMP_1yXEKJB9zX-GBBCnX-SyD7M3x1yXcMBx0yONa6pqTOFk5FhRqvpMwjDUSSe__z
i43xgtdxI4-Z_Vv6JQFzRhGRPuJsgjdtDCBhHhRyxBSJ3DzljHgrr_nMo-_viNrb2T9htdWhlVJpEoUpy9hlol--xoglIX1USFd1SHhg3yxJVAzeFpN_lfBc
Vql2znrLSVlZDFe9vsdq4-Gqkd1v_LPzepFNJzRJd0_GqvmFqDES9rBJd0FKMyz5M9pvvWrEGavpBdYSoUFCpkLl5O-Jcrk-6jxa_
}

EntityColoring(kibana)
!define kibana(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, kibana, kibana)
!define kibana(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, kibana, kibana)
!define kibanaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, kibana, kibana)
!define kibanaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, kibana, kibana)
