sprite $kickstarter_icon [56x64/16z] {
rTT7kYKn24DX34RQ_ugxN-RcS6QbgRxVbGFnbrKjs-fQSPxSqXGNNVilsckAjJLDrxbQFshaRrEwQ38cALz6tvliwwBYpfgpy1hcoRwpjTcYxFjmtMcjkqNE
8RmLHKGQPAFDsOfbb2hckfcJV80S9uAkeKl65CmLSmhabCYf0hbF5f05P05PG1QGSGSWSAfn21f2Vf-nBPeaeHDqBkW4dHEwXau-G0xq8LF1pItcYlxNHGgu
3VzRsN-o4_wNFvq3T8UnkMEoMc3EkPohV7UkceszCyUTBlSV
}

EntityColoring(kickstarter_icon)
!define kickstarter_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, kickstarter_icon, kickstarter_icon)
!define kickstarter_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, kickstarter_icon, kickstarter_icon)
!define kickstarter_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, kickstarter_icon, kickstarter_icon)
!define kickstarter_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, kickstarter_icon, kickstarter_icon)
