sprite $kinto [64x13/16z] {
dT1NeaKX24FHA12EcFbFznLlxsN_BmLmKpUpZgypStUpXklQstpLMbyYs06onqoyhXruh1fGSgHcepOSOXdkrm-S_qKqbAnB1dZ3eLB7_SnNt1U6aWybu8E8
Oir4I3FHXoRlUnvpb3OL08f8QKhTfuQZD4gyD_-IcSbmRwMvDWyHL6B8rlokGfUki8Lxv9xJbwTa1n_OzfxQqAQkRnyH-H-JowDagRhlSU7xltVcFfBX_T-t
ALxvs_dT5uyyjiwFaeDIF_T3Mw2qdUwtC2FuptZ6iPK1OwPNW3EGPR2fWJuauXS
}

EntityColoring(kinto)
!define kinto(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, kinto, kinto)
!define kinto(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, kinto, kinto)
!define kintoParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, kinto, kinto)
!define kintoParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, kinto, kinto)
