sprite $kirby_icon [55x64/16z] {
xPO5UiKm38FRXj7tF-t0OtzQbJ5gy2X_doEdYRPd5KVUNYpNHAJxbq5xaHlLumLKdDU8_fEyBqA-AnItCAwVZBW27LMkLVHBqfIbAUvPeURkBb8MfdXNLh2M
oamOC2F8jLIe7bov4PezzWcRJhjYBiOx6qqve7Ie_SdaenhLeL7OwhnhpTPqtjXuuz3wEj_LSQsFJ0etGmn5jK-E_MFXm2F3ETPcsj5EEma6TghGHGR3xFtl
zIsEFRchN1LPnlJkkzjUrZ5LTNdACeP5d7IOwwHlwXo266P1xIF3BAWGntnK9RbJYQhmZavoRFm0ZCqjTwps8tSk73fOT86d6p_X8WeT_3or9_VwwOr31uqk
F9Me0XWKMG8yceakfkmpqwix2Hqe05cxUGBaqMNFqpI3-um7fScZYos9PdFO30TCvskymvRm5OiN05bASBbnvNbItoK
}

EntityColoring(kirby_icon)
!define kirby_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, kirby_icon, kirby_icon)
!define kirby_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, kirby_icon, kirby_icon)
!define kirby_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, kirby_icon, kirby_icon)
!define kirby_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, kirby_icon, kirby_icon)
