sprite $kissmetrics [64x64/16z] {
fTS5Zkmm40RXSGpTzT__lWzs8xML2JXs2GQ_CFapq5QQE-3MSlgyB1K39904M7wbAqX44bw6UG5nJ7WUqiaGPuawm3SN5mbxveYRBDtpvBSSsRqFVbMxuusd
H9vP-KYUBhq5drc3p4WYBSqUwipQH_9pNnajdteZKhmPte8ekDSzq-WARAU7QU6iSLyvIISwjt7FmLO3cFJP06dIPm_xvFNj6m8UVDlpezySyUZRzxxi3_Xn
NyC7d_R9nOetiU8hhFY4bdo35P_GagydnlDUqwFt-sF-oM-i-G9BlYrwrvfdoKVhNjgRMdxXUtFRB-v4wPKtVJqB-1iVx_AKpx7Hftn2xEKP7vSFUPhncLY3
6TzV02nD-4n_uHdpfVFzvL-qBLtuqldM-qG_0Rox_XdzUspxhTBxJq54ul3n98NV5vEv50yFKvpOK4pKxn7Hz_e1VZFqcfTFLtRG18zo0wGXV3wAJRcQZt3i
T-P_0G
}

EntityColoring(kissmetrics)
!define kissmetrics(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, kissmetrics, kissmetrics)
!define kissmetrics(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, kissmetrics, kissmetrics)
!define kissmetricsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, kissmetrics, kissmetrics)
!define kissmetricsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, kissmetrics, kissmetrics)
