sprite $kitematic [64x64/16z] {
tTS5SknG34HHKVV-T_mXYMszGSaAdwAXwvA6BHiBW3K8amiEzeIcsi0-butpb5Xdxujz-Ca1mFDCn3a04N32Z2CH704u0_uUs6pNOmSYS7ZuUH3Th--SaAJI
vq19Ug-7oW4agQtUKXvfe6AVS-Chh_TvMGNVQB57I09kKEoNt7dmKY-wB9zfgS_03Dq-kB9cZs7lN4cpLowYsqimisO_V_s42QJQwyq5lDp3RYsWrJuO9pu_
EoTnOm4lzfPd5UN6Ej-VVhK0Jdx_Udf0lRzUm5hzzGBIwt7n7evcJrqVxxq-1z7-_RbU05BlhnO0wUr-NK3xVLu0ajJ-Vv3OaKZuRO0pmH4OHq8vOX8SW8WE
pr_4EJj_aXXCFpa0L2Pda2473JR1PA6j6MAl_m8
}

EntityColoring(kitematic)
!define kitematic(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, kitematic, kitematic)
!define kitematic(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, kitematic, kitematic)
!define kitematicParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, kitematic, kitematic)
!define kitematicParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, kitematic, kitematic)
