sprite $kloudless [64x64/16z] {
fPPPqlCw24GD0W7P_uBlLLiM5Xb-LttdDJdGwl9qVAMruq-uyb_q5bt-Cg27gT2nGOsUwXJXMWQmc3pr5RxARQA8ncFV8sBuRVKXgXRwKESuVHMUqKLLux7V
Xz-l0JIMZ_NHlnjT-DRUm619WutrOLzzYmZlit0vVGKoTV_fgmNmtgXv35plzFZfDxEeRBvZvFV6xNs0oY3NRtwbrm5kZPcO6sRultorRK3dOq4i6YVjLm4v
GAd-wdccninqLCZM0EDhR_wJUcouUwy5WEiYvIONvpY9dLTGBG08rg7voPpG_6w_Nb8BI7tiRkq-OUngT_jb7mj4-67Z3A8N6A1flu9tdN7-Jj1Lvimom603
tSfltK33LjorF1QaZv4yRE3trJfjwsVJM2OOaWDm99jwfYU1dEk798mEIm3A0Bsi1ZWzqv3Q68m0vGI-f_TmXxhAbuO0z2M0mi_7Al94ECO8jkBiyY40JeN_
KpQFG202gv7zOm3yWeLo9FsrG6jQ0hIz0FXn7w0h0E7V9G1BAH3q8v7OVGHG-Ue3fnp0aVdr2g0YPsDIykSbL5ky_ZspYxJih_XR2LdhJ3iyQetABJHocN-y
XtoMGfAlpN8BdtUL0NSVKsnlm17tMeKCedjyiOtRUbII2xS7KCxSRXUXSWdqUr_Jtk-_j55IfWT1QE0Zw4JhQc2N7fgDL-HOwykdeKnxmDy6o7f7TDW91UmJ
fuy31Bhc8xgaZuNbzrAf_X3xv3VeIKUcxUNHwBXtj_iU1QFz1SXqVPFP2U_x-taztkR8geRWedcC1d9yWeYvPuID_A4KKF40XjGJ4ej5AQ1Y0T2QIFiVAVsK
0Wezlnpd3AtzRWLKz5gVNE4z1_JVljrrcJuVr6OMx_JJLx1_EVRrelU8xmK8riDc4WLp_OBa-_aRrgyBVlbsF8EnNeJcfklBMPxx-VJ50FXEZtt3tNR1ec9e
xnbaKkukqOxs7i97eKaFF_w0QCXVV98VxVq7
}

EntityColoring(kloudless)
!define kloudless(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, kloudless, kloudless)
!define kloudless(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, kloudless, kloudless)
!define kloudlessParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, kloudless, kloudless)
!define kloudlessParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, kloudless, kloudless)
