sprite $knex [64x64/16z] {
dLS7WkGW38kR_FyNNmDqcE6ybzMMIK7ObWMJFF-4GyQ1mPxtyCmOHyZqDqooKlw4pqoyvqVE193VYgyv4h3n-HQCYv77WgXqag6SPOuqb1SL2UzAjbg0eweN
ZHYdqiY1BNrfnP2Ig-G2IatugcVCXj1zoiQCfLSAnfSj_3LzdH7-Z5OAMDCNJ-Qd4NlXIBZC0bY2nE2xKCzHYpgBsYF1H1bG34d0XNgg8_FaS-3aY-U14E4n
HI56CCBoWaY2HPKP_X_N3KKZJu3_2hInpnv4dioCEdFdVrcXw8BLJE4CG16kGirGrCKoWvMbr03xG5s9QAczWUT2i2NfjdkZWqoxNNI7n3K1TJqMO2hJA7QJ
Gm5rn2ZHPAyUh6E3yg8yOlA8Zx6OrLeWPWHZ8Wdtc0DOdGfON7Lr39Qm3KfNy6fbG6aD0koNxg8w3Kg4Sb_P09j9Hsqg4fLD7tA62Z-sXmkRiBTyMBzqFtVo
Y42TuRvrG5K7exZ2BwvmgUnn-9l2HKZLbVtRa_Lo8eVLqbMDwuRsYaoM4jowtLO0vdo8oQfK_dwRW7ifmygj7yxLGHZ-kFfp_TxRwJFz3hESgXCqYhiRoDvz
CIoNSm9xUdWnZt4LSLyLQSWHAFxsnVSae6toXCkABzMXQCGhW4VrMycjuWpI8_Ha-zUSMeGscPlYijxFGP_2mR5kQLGsWxW63KqCiew3jU-gBxAC9Ac-nU6a
c8fOtLXoGCj68qDjbri7z_RQ_VdJ6_SNNK1-N9v_-mVmohSIGFjNZikpW9G2lN_bgNndV0v1n_UQJSp_13e1pAsAaNg-VudgcnT0Yl8Eb9ezUmdIED5R65dE
Rx9Ny9MrTE5_0W
}

EntityColoring(knex)
!define knex(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, knex, knex)
!define knex(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, knex, knex)
!define knexParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, knex, knex)
!define knexParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, knex, knex)
