sprite $kong_icon [64x56/16z] {
fPPdTiGW38JL6Fd-5qvFi68c3v7lxpvHfh2MJKR8Fz2H6NAC8T-0oXcE_CJaXCWVGjeeyiRG_dW19Yr6_iPRs-UJEDs-Bu8X7tIIeFO1o0qEJK1l32g64ml6
lAuVtD-cu2BHlm7oli3epdjHl2w0Tl9S5Atvo8hT5_23uAjOeuD5hkeYzAnt48bFBrhgLnSHie69nBhv9XiCsBhwlbiRje1r_Ynmie3ZHsr5_-a9tDIsjOl2
6IXg4nVttYcG1O8S740Mu2G6NBOAZK7deUSkrekJ1TQ_AMzhPP0kwiRuRWm2oG6F0TUkUi1ShDhnxULF5yiukITpaMjNdrhMnRLscCoe4XV9ZHym5nlzz7o2
fM2nBbiaeshYUKtIsG8yBTUTDE517yjGeIm0cI0hljJEiYmmUD5jtSfn5OAwAEJREga4LizRdyiV_2eaUIn2gdPadafeGd8NU-TNUGK
}

EntityColoring(kong_icon)
!define kong_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, kong_icon, kong_icon)
!define kong_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, kong_icon, kong_icon)
!define kong_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, kong_icon, kong_icon)
!define kong_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, kong_icon, kong_icon)
