sprite $koreio [55x64/16z] {
dTLNSWCn30JH9J5Ckl-13OTM13QuVrMlCCfRdjNjUgLOKxcCQhNMP9ULCq_r4e8rgLn1C8TMZX4ATcef27OAOc34qkoIP043fllaHOob8VfbifZnPX081eI5
Jn450yAIfI0O3XR00dfXG0M4fOQ0FMfvNRAKZPwWCKt0W8tUGpH_c9In03g2IPOm3ySf631XG12CB6Ci1S5mbZ27e1T6BM6iIvYl2TcytVQPhtamJgtR8NC8
Ov-Z4mpOGESOiB7l5CCv0vrYmCw-IspCzGysrnppAXlJ6mDuoDZtoxnrZe5WFCKZnYCmXqUCKp1Q-mpamO0xh0MCsaXOyvAHdWm84-e7kekPgRyn40TZ1eI1
Nc34ZAK62c30W1OedcB0M6ejgRyW6B2evMMibcshYUaozOZnhsyPCsl01wiR5MNC8Gn4m9YnLEnxhIOCA4uHMSXOgW2nD6EcnhwecZ5GbeMixXgMma3bKB4K
nhvJ4CQ-anNxOPSGJr7ikvHfvzGN
}

EntityColoring(koreio)
!define koreio(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, koreio, koreio)
!define koreio(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, koreio, koreio)
!define koreioParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, koreio, koreio)
!define koreioParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, koreio, koreio)
