sprite $kotlin_icon [64x64/16z] {
fSp5GGK050F1u2_qtozyTv-zp_vQO_pd3NcGnpZuhdZwOYiE_YVha0Tva0Tva0Tva0Tva0Tva0Tva0Tva0Tva0Tva0Tva0TvaES-D_zrp-EWE2WEYeFYe3We
3eg3FZn0FvS7nK5nK1mK1yL1SL0S50V5GN5G71G7nS6yr7umE1WSpEkj1eE3mS7WO73m3m
}

EntityColoring(kotlin_icon)
!define kotlin_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, kotlin_icon, kotlin_icon)
!define kotlin_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, kotlin_icon, kotlin_icon)
!define kotlin_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, kotlin_icon, kotlin_icon)
!define kotlin_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, kotlin_icon, kotlin_icon)
