sprite $kotlin [64x14/16z] {
XT85WkuW30JW2GuDcVkVzadQ_SdwrEN3Imp-9_NcrpOwFgPHWSsCLsP8EVy0dQn1IYtFDp6MBtr6yEqzHwQzVSj5ee_yySxlNaXAVgqqyM-7IX8WyE0BwPrF
oqYj42LfM-f_hpkXMnz6cpWy-48EvqPk8nlKZZTc31fLoKUFZE3DEFtseYR891FAtVxZMNoC7o-8dbnUFUdbRdOKRaJF2u2y6j0bUAtU_iS0Y-kpdy5x0S6Z
aJtw-QkVNO979nlaRhyOs-z-TWd-7g35dP4MJP39ahxmuwHBy5Xa5YMDPFL1f4dzv7j8TLzq-NNj2pACl7mIqhMt59tF-j7-twl-1G
}

EntityColoring(kotlin)
!define kotlin(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, kotlin, kotlin)
!define kotlin(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, kotlin, kotlin)
!define kotlinParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, kotlin, kotlin)
!define kotlinParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, kotlin, kotlin)
