sprite $kraken [64x57/16z] {
fTPdclCm20HW6oHWqFtFkoK5Fqfc-Sg-_yUG8UrueHOD7qVlD7GIThPnqJQU2E_o8c9DEXE8sSP5u-Tq8e0uVzx-s-pZW7NZlpXBt-0cj1ilCcYwnWFUZd-j
C0iUOhHnqU3ng0USzFHFCadw6izlA5hk2qGWDxY4iF551Y9gECd3-FZYLvele5rSr9B1nSdsPNgWoTSD-VZXyQLPe6v8nriWuhNylaBPqkJq_Gsl-0nSQ9vL
UBrmWERx6ygM_fS7tClJ6mF-EJzh_8p4VppWl8yVaKpbknlUNdWs-Wf53TdgRpXfkiShul2h_FBPv-5hPMD8j7cNN0lXmKsHqVT_-5ehmobJKR7-_cUkBmWd
XdnHz1_XkHP_GfZSpFxzVs3T9EB5a1kD_YjCrqF6nkHXPFyL6ckn5LIUlFyA5sH1nQSKHVyJOjk2SUCY5-k_Vq_awnCmH2uAMbuPRoSssKn-knAvmv1TqFAA
8dUOiXdyTiLpjrRiApZxxI0LbfMkMuNqjwlCVBFILChajol8mcjmUhkYILqr35vUyUIg1gloA45oiEr_PUZ1MHPUmsJbyHlo6eBSZj-Grp3gZSz5DZ1577us
-TEHZHZgShHcly9RzPy
}

EntityColoring(kraken)
!define kraken(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, kraken, kraken)
!define kraken(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, kraken, kraken)
!define krakenParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, kraken, kraken)
!define krakenParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, kraken, kraken)
