sprite $kustomer [64x10/16z] {
PP27WGGX20198eXA_zq-xEUxCIjZcWW0ogpGBO74TY9Vxcini3uGGCKrGy1Mmrm1Bf1IMihSK5pbZ7KtxtrpRo5bAaIHCXuzdN8tOjMUBBKc9zYdFxp3gChJ
6Go3IAl5p6WzZHAXiUWgaoKDVdmxlVhjAs6WAuZG7JT6sl9_FcVQDVZn5NU6_FLphDD-4jqqQ3_g-VBfsqtFySSl9z9-VHX8ylWCF06YtnyH0txUFtk3URxz
VYNzyQVobz_4x_slUpgaW5UHAYqI0dJix_-TNTMx_mJCY-tvPLZfdbPTjxFXosVj_P0L__fk1VMByLhq_1e0Tiwi6JjtKL_Te11LGLK6ZAzRA-xRZ2TW-WS
}

EntityColoring(kustomer)
!define kustomer(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, kustomer, kustomer)
!define kustomer(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, kustomer, kustomer)
!define kustomerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, kustomer, kustomer)
!define kustomerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, kustomer, kustomer)
