sprite $lateral [64x64/16z] {
fPMDZeCm38FfNvfcx_--XxWQoEGCDdp_5Pzh9qXdcyRK_flDx_WP7XiCd9mDVgU_WlzLzek1Fk6z37hAsr0VJZzdL_3F4jX9JtbxogCK_ScFBGZGrMxUpmqa
woE-vzn_u0tbf2wfswVkd3VaRma6iM9UHVAo9BdckK6NjS2gTibJ0rtvbc1miNzc8B8Lk4vWJFzyNJRLxtbJaLbWLVcHbxB0W7M_vkiobVNB-xjiIXyDDEP5
N870u99lowxKx-_VXambPw2a0kLRQUy5Kgvq1WpNKafjiy2aroEvkxzM2Xmow5LLx_6zJDMs5KXbgjtAFshPLLjAvP3UcP-KKDLdLxQ_uOcQSpaartnpTAqb
mG0ZtBzOVlNqgfnE3lA-WF3wkYkbmw4gsH_TtQ5oDcWJX0tV7L0qE3dquMP0TWVQ1u13NI5aU9_VO3G2mA37-nE6OuHmg1hTFpYD1d2Gg7y3pXj0PGF9_hj8
kmwGSf_TW___NLgB0rGrT7VvhsmsEBVnUfaDnViVyAzDPWQRhK7fDezrxay7XQ7vwqoZji6hNaRs3_R4ltiTJza_heEb9ZpG_HWpy33dGRlZy_ufXD3y1XWO
WrXg_yGqKAMGe-CdLboZrYuqUG89_15FpIhYzJgEFCqXoA1naPeKSFaWXuQj2KmjmxV9NK7XcESlER5aKmldyWS
}

EntityColoring(lateral)
!define lateral(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, lateral, lateral)
!define lateral(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, lateral, lateral)
!define lateralParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, lateral, lateral)
!define lateralParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, lateral, lateral)
