sprite $leaflet [64x17/16z] {
dP9Lmjv030DbaApU_yAjatoKyZyFosDj05yc0qyYy0lYsVnYBokV4vB2dPnf1AT-6LvLpmqDuCODEHjqzJFnNU_kXr_hcZSzp2fiyvZFSw-gruz7K4MxRdwx
YN8ndlDN-i73jvCMa5G1ALKN84z0xZusCiUJp_YgVlfX1mB82NaJmqvWcx05rCIeVUIpuXd_z0VB4DF7n0RIskQerE4gy_fIjVJBJ-TPHYoq2sKYneqTRICc
w3fyYNrHfpxk023F5RWBiWixsaeyDY9wyp_yR7aPJTkYw15jXJozerRR9EMP15fINzTFP494j8Q1r12G4b9WF0hqRjHC8tOHA4eyzSfA_8xmu9SSL-7g-1Df
lNxRYCoAQyfH8ZBmHygD7qJFDqkYhBD2g_0Fd7dfVkP4DKdh5lmT
}

EntityColoring(leaflet)
!define leaflet(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, leaflet, leaflet)
!define leaflet(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, leaflet, leaflet)
!define leafletParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, leaflet, leaflet)
!define leafletParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, leaflet, leaflet)
