sprite $lerna [64x58/16z] {
pPO7Ukqw3eD95VQo_zrEP3kJTtBkw_LFTmm8-2WN-09D9lmfA7N1ds6os80_WSuTZF0T_3p4l-8-JRHYVLFJSmJTuLSOMf6f-EMuBIBWG96ESyCNRnbHBRgY
SiD3L6NpMWWxgdZ7_B5QrLGsmlBeykmxmlQixhPKNDcM7We_1WUDmQvRHBCps-VHi_VH8o1NTpN1pKBuOecgHV0QOtDaU6Ha9yC7t9sXiAlIvZI1TUP33h0s
FCn50Z18L7blZVmWikfa7Tc-DbUQCsrSvWjWXFEC-IIVhCgqrvnZafc8UNHtLSanYCuCotJcYWZTKwjKMUxiLXMX96vkmhGMcNbwTVTJGReYM4lMqUUMO_vC
QCkUYAHx4wjxH1XlYN3Bxl900F3kDAwmRDT8ZwwC47W3Zt6OM9X5LvSa050Thg7c1nOk0m0clB6xwogUfdq8tcDf2Ly6bP5TiM_zEpCz7eUuRBh3KgHahAhA
rBeCU4mFDnB6ene_tS53ul7e4klhx4vbxpmMlhVMCMxpJ3eg_bQ4FDFZIi5aSUtS-C3TtBECzPgkf_4S2F1sop5pYynhI6Rf17XyAZE4h4rouVGi5zS9u0Il
N7FCkZjKfArxbr5L-VOM3m2aaZtFyU-3r78_OLdrrF0ToN1n8YLbcHtXEhQN_cKSI3Wud2OWBEigMP91OuvTLPqxKv_8wzY0kxzL688m1rA4LJYJM7PrXrIi
Saa7n6r-wJda-qrtQiS447VUsytDU5Aca9TAAsYJPbXie7Co2QzNzGSop6KD7Aig8an4bcPAs81HgPMgG_o41JBbZNVoxTsTsQasna10BDyHdBPnYhaWm8mo
xmedV9QqSDCrEVfG6fccUm8ENC78FYkT9vFIMMIGh6Fw5LgwC_gcFiZmYemzG7JYz9FArfppRdgbtGGFwv9ctNABZYsil8dNy8aSKHrEYxOWlADT4Vr9MUcS
Tj-09ncbHtLvw39dUCVwskxFwjUMkG9T_TmekwepKxnxmXlK6PKML-_k2fvqfObQ0BO1vRudKBKl-0vMPje4xV2gD5vBim-wFf-uWwtRkPlVyw-kP82HL_G8
KSkzfAjjlDmQh_LfliU_RlEphWdMG4G2mEoNiCTUg8leNTzwVcQNQUZNSxn34VwFLjdmZhStY5cTnXEzozM__hkpGoTClbFGwOFHBl0DhWeFpt0LtXi-aNFS
g-BszDD7krtMVYqXQUv7xUaH20zU7X7kJmsj40Z9od2JrmgieYpQuMbVWza0dE4-yNcsv1vZMcMUOg-CWG0xmhvjS6Ixbr-g5HyuQHV3Zy65y0R2mxmA9MzX
-4EiTFUz_yJxgSU2FmN2Vvo1EE1FG97ofqfQm9z27Mx6zNW6XFDvEk4SlqDFgeRkMhAJj0IeBFWtvB_rg-QixKqyLs-W0XPOyPlNboIMkHC-o06h463gRzRZ
7OCkVHmzx23ntwWVjce1ZbkVywoV1XBZr-SVcoGDThfDBmROPMX5NCQbyCh_
}

EntityColoring(lerna)
!define lerna(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, lerna, lerna)
!define lerna(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, lerna, lerna)
!define lernaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, lerna, lerna)
!define lernaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, lerna, lerna)
