sprite $less [64x28/16z] {
fP87TgGX38E7QcF9zx_kBkPllFH4AJDw-0EtroOPtrHzlQk1xudjjIldD3yKtvJa3Qz0_Vxx8Tdg9d_AsxiyCKMI2ErkcIzuqbHa8E9sHvYAsZGSJxxVF6tD
9Yk1wL8u0S5HugZenpmrtKc1Thbir4U_gU_osxM3A9V9GFe67q2LdkR7kgr8B_D8ZgFyoY3rtVwDuxOW4oB8d5Hbx5mYYJvMm2qx-HcJEPMlwwenrEDkS0dv
efFmvCkqTMeMe4nnNfNNYwaPGoFVhRtuVQtLzGmPHm9tGWWYbF01_tX5I4ewueraUQz_9NRb53YXShr1z7LT8MsRdo_UMaJw8KxviNRYOJIlcOoTzyMlXdF2
04bJEXqfOdIuSu7Z3T-2NEKM6TfJTRB4iakyZ_Hg0sZllo-hi6r_lJ-SHOPfZOCxB-vOetxkPME-JRVjPhTzqFG5maSvHjxXQ1TEjtAEUuPZv__Bf3LXVEbT
1dqAKakftS9OdqOG1tlzFzLUVshwGxhbrwRoCxulwk_yFm
}

EntityColoring(less)
!define less(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, less, less)
!define less(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, less, less)
!define lessParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, less, less)
!define lessParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, less, less)
