sprite $liftweb [52x64/16z] {
vPRPskCW2401KI3n_Lzt5dyxX2_QajxEkUjoPCq27y6gPb8W3pNxWRC6Y_q30N99EPb0fLcaVGh1QfPqOjrvfuXPrl6wDUjuKeooTvhWecu5WBPrf1zuhtji
ITqxNQVXsGWCojxf011JeLTWVUUWBBk3yiOH2s6SjdFYBnMkr8qJYqK8yDfvl-zbvOGmUj-abHEgARlrZewQ8zlrZiwkpz0iuqZiSygXj1E_8tpYA8xR6Jrn
U0pZcICsUEJO_-RKBvpoXOFFdGRF7OI1fXs_Knn9npC3wad75P2qKy73B9nolxC9mGjREWmJie5M10YPzNF_r5Gp4uOBhGya2E5MojReQg3smKb1Y7Tv34Oz
-my2jYaeGl8o-W5tH-y6wp1cPkuu9GhOZkwS1UvEh1jeXfWOpOuEV1W1b8jprDkAI845o6s-dtXtn9FACrvhEGu3Frfu6yP1y0IssTCivCDea029jLz8v3Tt
q9M67nqEXkRgyJXdUbOy9MF8KwptCvFKRm
}

EntityColoring(liftweb)
!define liftweb(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, liftweb, liftweb)
!define liftweb(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, liftweb, liftweb)
!define liftwebParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, liftweb, liftweb)
!define liftwebParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, liftweb, liftweb)
