sprite $lightstep [64x15/16z] {
dP07kY0X28C50bZ0-nzt6SVj_SMk_8JFzag6craDLQNsls9JlrlIAVz9aof9GSG2TNpZ_q-PjAjWs5CwHBpPgMYYNbBUDASauWlSzSfxOQRtf4Hwa5qBEpqK
8K4Lc7HO92hPAVAvEE5MLJYVa-3mgJKjHkPQs2i7SYzU4OYTufcTOcKev8a6nXYzyb03N_uuvPGLsDssZXHB6shRa5uNkR1IwTZRA17hi_-MtzPw88KIdetN
3aYoxhN2AgHo7Vk6mhtil_1xc1OtS-R3SsevOY0cPqSwXXp_0M20ITr8q1hfoqVcGZ3rFWCX5A2vP4MW2cBF79IH0Hqk33KpHUS2fNshENcjRyvCxqhKAFqS
u7YVp5NxeEzub8UqNug6tXty_YAfyOzHtFv1uaemA_gZ4fz67-0-0G
}

EntityColoring(lightstep)
!define lightstep(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, lightstep, lightstep)
!define lightstep(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, lightstep, lightstep)
!define lightstepParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, lightstep, lightstep)
!define lightstepParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, lightstep, lightstep)
