sprite $linkedin_icon [64x64/16z] {
xSz7Wi0W34DHsLJf_lUTwcHwmMnvgmJu5A1C9R41wDemKBMbJuLz1waDingiKKaTBsmgPI8ObL5mwKgWuL9IFMw-U_xs-pCcWYjds6jE9R6vbwvl71pjsQ1-
CZqKwbbzzyjc26NeUmENrzuGg65uftAn7mYXhFK3d_Mbtl2PSQ7_Jj_iVRNtKXplSAdtgISikCsLtgaNT5p6IZyKEYvjeJSgCDKNNMYPlkdc2FNqRqv_-jEp
XbZVQXYwzKzZsmvgJzEMYQ4DDA0hRJeU0G
}

EntityColoring(linkedin_icon)
!define linkedin_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, linkedin_icon, linkedin_icon)
!define linkedin_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, linkedin_icon, linkedin_icon)
!define linkedin_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, linkedin_icon, linkedin_icon)
!define linkedin_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, linkedin_icon, linkedin_icon)
