sprite $litmus [64x64/16z] {
fTJhTWCj28NX3GYekV_h_GxQmqumoNJb_Ti-Bc5cWcU9DNSNM3DJmRNOnd-veEt-S8Pkp7vbUaalJ9xJovhzzHCQQVASlVJnWJS7lFZApSuyea7yZHVe-Guj
CaEX_j8hX8UuvvaXQC_zSkSjMEJoj8AJ1-ouHetSXK6yU1gU9g6--Lg1UV4qF1t6m_yKG3jx0uoyyUqfMW5v6hvCuCc5GPqy3tyVxPuBWNdn1ddoAdzpdg1j
xW8x3SyhrEBtU-nkAe28ykth1PmahO0Vi1WzEcwF7_K6Kb_mckdtyHxnniipxAxbYCe1gLYRGthl-N14A0xf8ux_KkshVSH-xjbmpExnVbAj_nJszGiiPozc
GdZbqRamjZN6gyZHxmjxWNrXhlYUyenBPAcN4a_xrFiL7zVzv_Ul-nlzCv_jJyylxh7hXVSdY3V2JG6evpCROV9mXDiFNd-ACUUqCxViFH-EQD87urK_--oh
ZFNVihzV1E7luiHzSpx2NFRD5gQyyfQTorZR8ioDiWBPdCjzyp5h2L7MPcjxnq_LAn-2FjD-TCwfyEhNc58lOFlGaIxmFkVjTkj0kK0gSBf0GETNYd7R1JJh
btgwGAUTAEQNdrOUWMBN9ZSKEQk_3K7KwLUTVQFpsDyw9C-_aqeJ97HMlt9UGHg_N3nyBvvMGBVdudVucDNN5GJkoxbos3pxLKAIXkVw7bx6ApyTbiIvNEzj
pkAvgMZCkHW6dqyyho28Sqh35qyhmDFolP_4Q_x6poH-IkE5dztmDernzZCDbvAM_nznOp-x2wudvdry-zcZFSF_0W
}

EntityColoring(litmus)
!define litmus(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, litmus, litmus)
!define litmus(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, litmus, litmus)
!define litmusParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, litmus, litmus)
!define litmusParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, litmus, litmus)
