sprite $lodash [64x58/16z] {
xPNNOeOm24R1J2F2-pzj5zALMDAz_dCh1xzibbiYl9LVub_yYuyXbLfh3lWMFsqi1zpYQ_sqonCelCR79XrbtaUI0MtQDtslEQNIs1fC-kinP2l2V7IeKtxK
uXKUm4tk23C-MTX-HhO9F-dGuId10hY-HatmZAOpuFgB_NuOW5m_sUGDfuNHyrUBF_uGFL-7lq17riQERp7FjaMUym5E9h1w_gxJ_sQVploe_Zl7Npo_dSr_
cPf_Apjh73m_TATFGPxRVw1rotXVR-3wwpW0wVRn_I1QEPeMHj-7JVefp7Qd7Nu0Du2KvtyNHlEf3QbmInM54khrIsAHr3-5RAaFc5eZDJIGxrk3dWpJFfIk
p5wJVSg7fVAJ3naEOdg120zWMcaN5gQj17WZY0WVoOMKtqbv7nV_VLm3
}

EntityColoring(lodash)
!define lodash(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, lodash, lodash)
!define lodash(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, lodash, lodash)
!define lodashParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, lodash, lodash)
!define lodashParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, lodash, lodash)
