sprite $logstash [53x64/16z] {
xTCrOaH130JHblgZnlU_hYanBamjG-KlB7-MePvizpj_AmcoWo0dGNOGv238GP2382EK13a8Ca91aC-7Wg0aoET3STqed-Y9dgZtfsLJWpwoXtzwsTJqYQRv
lnf1HT12q4IG2L8ZQ2781Aa86WbI4MI2D1Ea8YWRG783I6u0AGiWQIP8Gm4aZGMGD2oj7qdXQQss7Rq1
}

EntityColoring(logstash)
!define logstash(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, logstash, logstash)
!define logstash(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, logstash, logstash)
!define logstashParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, logstash, logstash)
!define logstashParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, logstash, logstash)
