sprite $looker_icon [40x64/16z] {
bPK9kk9028HbBUv_uY5HUFaYtN7ANN-BrVPrbpZWydgI8LAm9-o0y0Xo8YvoWFHWXtmW17J7UOJruqRsyK74w4SimlaeP_vqXESXUuzJHgzqqQFUy2bO2NHW
zMo9dRaRKlQDwSSgpjIPCbUceOAt4ISYnwqcEzff5IGgD7D83BqhgiepLtRDoPgJ7pdx8QvVcah9oOAJIFa-R1SSK7xYE4w1pxY5pP4hjbINPn0dc0WrDakz
kasibbgDhwmKgGWSCfv9vhmXMe0F91dyRFjLSBgR0G7gcbgGxv9XrVOhgD-TmRiITwG6K709Gf_s07UGC2QZ_JRNQit5aLUSQrJOV6XsPFGUB8-AxjZoNFmp
z2fX57_0AjPdh6rOiBFhjDI6x8OCtRj3-y1ltFP_F2LiEFq_ReuxSzs-pUY6UkV9zOfj1sVrk0nRyyBMa6gRgXxVLc5_tz3D5e0loorBBBnIACSP0zVBwGT7
TZSmz9oxRAuthoLwlmUOfWo8ncYnP2YeiH7Sdu22WPowIlP5mcYSfLv9LF6JM1qdv7Ve7m
}

EntityColoring(looker_icon)
!define looker_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, looker_icon, looker_icon)
!define looker_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, looker_icon, looker_icon)
!define looker_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, looker_icon, looker_icon)
!define looker_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, looker_icon, looker_icon)
