sprite $loopback [64x17/16z] {
fPC75jWu24JfC9Au_tKNQzDxd7cFpdStVPIMCxqM1u3IjxG_z5ZAAxo6Df84u7zDQoWGVDD2sgHNoj-lgiaNLOwJG0ql_E4fX7syXlxkKhZF_gBhFGv03gyb
9Ed3Jm6ZqPbDmNQojPHHaxNH0cFd7VYXJ22cW8W4CFoClk0thAqZZevhxRtQ9AnrmSfFRdwMfOpzFdsE9AhFV2kTrSJjpTH-oXUaCDciM7VHlLlM-mROGlZp
-LFa17UqQjlZj9thh2NjEpcylHL0Q3wUAG2uumE_ks7dWFASa5wdU9zpp0_M7VYcMfVz-E5O0P-_0UPhrqdBpRvs4ovK-g5YlnVolNWn_Koih5L674WHeHSA
0FKlVv3aGnkzbrRm2-m_
}

EntityColoring(loopback)
!define loopback(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, loopback, loopback)
!define loopback(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, loopback, loopback)
!define loopbackParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, loopback, loopback)
!define loopbackParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, loopback, loopback)
