sprite $losant [64x37/16z] {
XTDNaiKm24HH547U_tudJqErgijyS-uBDiRJjydPtTI0dsTBVav_vuyAB3_FIw1zSmIOVta4D4U0-RT7GF3_MJV_yphG0Xo1vF0Pq9m3q-4Ha1m1vXuF0fB7
H82vpuE0vCqu0DwjPK1oAm7YLWEAKs0KBWBWvvUNm0GVrt9Nl0OYkGeGfy015m7EtO7AET2yS1K0lmEIc-t_mDQNTeOysUuunwdIPrh_ttBcBWFWmom3cta6
pf2S0-0o0Fx_hSOLQBYuTGLM_L4SO6wM0Savq7Po2Z2_0yGfKBa8W2yp3jJ3Le40l_znpJCGu7SWkGu4E0M8gq20Ku2u2WHnSOqo4E0K8Au2uM9b5wu3JyYL
dLpFz6Pgt8td4m
}

EntityColoring(losant)
!define losant(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, losant, losant)
!define losant(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, losant, losant)
!define losantParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, losant, losant)
!define losantParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, losant, losant)
