sprite $lumen [32x64/16z] {
rP87iiCm24HDNUv_uLz51c6SDZMavqdYxQ2Z56c0ZrQ58Y9G_b50RzJYhtnV7ly_s6DXsfV7Jdajj_A7OFsmf7Kvt-WwMNnR7dy5JTgN_r6fohaycxaqvGnD
cRygzyDEoaD-sMXVtfKxdHFs_3coVXWUv-_AaCKayszIh-QV9fmKt9KVvzzRTUKflx-OFqE_CtzvCF-aRy__a8lxd-KNzvy1IMx3_KS4aY-SbJm-bXFHBsSY
yl_F3LkSojlPlV3AVZrpgvpFN3T1nsyL36e1MTInc2itR5Z4fA4C2DDAUXL4h8RKxnAs9BoZeZTqGehBxE0Fz4wj_CeFySZFJLxtcpRD2irkLkZiyGHzdk0t
}

EntityColoring(lumen)
!define lumen(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, lumen, lumen)
!define lumen(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, lumen, lumen)
!define lumenParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, lumen, lumen)
!define lumenParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, lumen, lumen)
