sprite $maestro [64x50/16z] {
r9PL0eH034CPQzFU_xwhk4DMtn-IocYg0R6ecRj1S-o_3wce0b2ftyyH2hm7SXjLq4DBc5MBZx7oK2l6p4H8vZCW1i4CcaToyNaC2yX0hdvK3mqxvAXP3o17
imzRIEVaG7d8WnsllYOIrJST13ifhmiePzFN1U1SzpKXCkc1N3YzA5K-O5_MEwl_y_wLrBFhXrs_xFuXzoz_VbHolW5Xpq_o_2Rl3_R-8kzFxlwc_0FoZ7-n
UV-IT9eypFid6_gdqDGsya_B5YmMXTs0JFoRw9tw_TyH0gVtQ-5oOI0A3C80D1MW59Bzj_roxbV5NkAtjJrohOm1MBflZCWDh9CEPv-DyDomFFDB7-eMIuN3
eW9ToJrOMUE8PI3l2bPpVUa9wC0vvHXqa---KzScK8d_jNytWCulVGDqR2ujeDrLTG_s9TUJjtzt0xT-zADhXNpHfy_XSykGlUT_ZwfbyXyz5aK6GkAQBTN0
bWx--_zvlb5_0G
}

EntityColoring(maestro)
!define maestro(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, maestro, maestro)
!define maestro(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, maestro, maestro)
!define maestroParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, maestro, maestro)
!define maestroParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, maestro, maestro)
