sprite $mageia [64x20/16z] {
fP47Ra0X34CpoCxzprloI_VkjwJ8Z6TP05kiS4l8JFS2TDt1oUXkVxw1iwBQ7Tu8wKPv6D5_4w9JHQBxVm7Ih5db777-mkNCqNBZv-sH-7mMyNowAqBP2UAc
cUMMAJCdBzAyDhZE1kPiC4Xi6sERuQZM3Dd3UsmOI5wH-7YM2kOmOSFxMAstFDKulkPA21cJp9CpK8PlDMrRKnUxvE3Kz9RdpUl5hsjZscIecIaEpnUlTNXB
-C1BuUxHw_HFq00uLMoiDfR3Q6vzw0zU7hLFkCAhOXvK3u-PdjKRoKNiVUqZlvkiYem0ACeh9rMkCnghCdVGkpiPVfJviwMtrn5_fb6AZZqj_gQeJoi-
}

EntityColoring(mageia)
!define mageia(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, mageia, mageia)
!define mageia(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, mageia, mageia)
!define mageiaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, mageia, mageia)
!define mageiaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, mageia, mageia)
