sprite $mailchimp_freddie [56x64/16z] {
bTS7rjmW30HWK47D_kz_t5YOWDcICkdbosXfxwLy2x2O2PN_IcNp2FTmhUit_whQ1KnLnRZfNQxcxif_ifmr8emiGT04-38ghOcvqpU5bkgA4w0IedW80QaV
v_Nb6smU9Zr783AmOVhZP-JmJwE2PjaTFHqbMglaFojdV2Z4MPREJeC653zRedrOa2nRBewAg-khQq-cweU2dWjycxE5FykEa-dOoETraUsZnHae6nW9tLdR
sF5Zw6Em8tFEElpE_FpHdF7i9kvqUePiZDnriclXfPtP55lEyUdsVREXB9dsV_ir5wCdgybCnqUxcErbVYLwzhtJSEjmi6j5dihkNDOsnk7Mevsfhn7zDneI
NgOSIMOnsK0hs-R9Oh7OKbjXdGpS7ymdUqFAs88_rELo33RBL6sa8K2LMLXNNHw8ZIa1058JLI78aEFhOjgnMDmCAenW_-wAyzoxEMNcPhuO8iBCvTfmxiyf
ZyMCEgEdW-LYk1XJhhfaH4DDnrlVLXUMuPfjJyHqETgt8SPLMsDc4MvjPa3JWIVqUUWtrndPQ7L72bnNDYusflNbveZjqFoXLcIWQ6N1nrdqwHX691oJZLze
VJo0uqofhJwPVRTZX4O0vFF8w2X0G9bk3Kec2BKQG_vGm0O4z_dNB1RKjPXrYpcaevXZqNRpbARQ0juX-rm6jWdNtNaFcYxNJwFlJlaJ0sXUVy_PyjUqFKVV
5B3xkhbOSe37uwVuXRM8jgwWKgrLOgGp-AH8nMnxcLJK9pD-Oz2LOU7nod32EsjT25yHKZEbF63fRXYt77sFHG4rbOng_buPEuutn9mmqNGcjyizHBg2K6R8
l8n0M-pU1Kn6MijRg5AK6TcTqSKAAq2zQHq_ec1f3uU-Eyw_YGRv0oJg0L4e559MR7SDwXMLnw0LrRXMCDl6deKs3a96ScMo4bbCg9OA75IUqRrGniwnQ3yL
ZFT6eblP0Y-5SCEoDh_70ikUjXVI4CkbrFMcVPbKFXnirD3obceJUa9yTMnXjNo1grAvhkGsH1YKrkexrDWgMyE-vRck6fqL6MwFU2nwnLGQDxdlYgQexspi
_vTuAtzAbSzIeVmby2xTwD__PxMKOFdN04cthWtVLk8N
}

EntityColoring(mailchimp_freddie)
!define mailchimp_freddie(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, mailchimp_freddie, mailchimp_freddie)
!define mailchimp_freddie(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, mailchimp_freddie, mailchimp_freddie)
!define mailchimp_freddieParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, mailchimp_freddie, mailchimp_freddie)
!define mailchimp_freddieParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, mailchimp_freddie, mailchimp_freddie)
