sprite $mailgun [64x18/16z] {
dT45OiGm34JHaMII8dlkVzlQPMvtVnXU4F_AwFWbKPNV3l_kRSHk5FpGMFKttyAhMVLe-BvW-yNNuym4xQSBYE5dhz5HOrVHGd6If-dCvVVl9q0FAJ5KUnHu
XsLCHfrCW_XYU6fBs_viBj-RLm2MhQGlfctZ0sheZXueP4vo9XCNfozIEylnoIDeQmALlP5NSaQLCuPQI3q-OLo2jIeJaFdiH-45w7hoXRtIWSbeY8hXOc7z
-04vCDTW0-0llhC2kDxvTZPz70nWH4J_nO_lVBA6YaUh7gKrUU-VddzzVdwTIz3PsfE7kqYFw0e5tdbASCR7xnSaPV0izSLhk66d7W9OTaW645FmzF-afMbs
w4L6Ki_kBAXxWa_0FBptFJDyIV2QNKq4nqC47oh3VLJ1hoddcItSctDUYnrtvulh2ty
}

EntityColoring(mailgun)
!define mailgun(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, mailgun, mailgun)
!define mailgun(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, mailgun, mailgun)
!define mailgunParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, mailgun, mailgun)
!define mailgunParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, mailgun, mailgun)
