sprite $mailgun_icon [64x64/16z] {
bLTPWkim21jswFtl-zQKM6d8UFZg9Yg47F3N5AmUcLMLwShqzPCWyNf1L1Zlehd16AaxQCdN6FLj1eu1kfV1Njz6p5BoG7sJWbmL5sOYPh50GUqMhYlO-Qad
CPS-DqhpAO5jIAmr9b3GTmewk-jOtgJDB1Amp3TtWLDW7k4cgvRIDIoV-XlE9zXo4TJefFfEa9-DbqRxX-tu8u5TsUkJZSkk6XJXUqULP-Sx0l98zuRdw7m2
meU4WiLJ2pmda9L0egDMsLsbJmze7cS-mdRwZU9adS7HRzfQ9tm1Je9-2X28vgl8FcauNmaA556joWW81M58e8vt0ke5Y84HTx_q8wr1xxozQgPqEQEqcYvZ
PIN8dXECwwtKcQroHHXGvBfjcWFLMhqRrrwW7BLseC2OW62ezoIKZOVia1CLmgy3_cl4ruJt4O-Sq4lOyolNmfneCJ0zrD_73YXxcma813mP2kmSg-IAfrog
uVYSExsHO2gws9yiufoaUOxcw74ZsE5-DuuU328maDuD9wWUmoVDvGEUm_FKcpAGr04EeOlD-IAIqztaBySzvaJujSoo8oNfUXAjFIluO6DqpT6eY2maJ9PL
wR88YwvvZM6FIwE1xGQvCB1aVXp0EIpWCD11xusjSvmw6iFgJlcPYGiNeADjdbcLwKfe91ygwB4v1zVzZkXx2w2EMiQ6peph9qRWhePntUbocgz7X5uhbFuQ
-uGQuFM1Ue_52qJC-pb6_OkDKx1x0S8EpnJcy1cBknh6t9dz3EMyVGFE3t0CTS_Nzwm3cW-Nxzy
}

EntityColoring(mailgun_icon)
!define mailgun_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, mailgun_icon, mailgun_icon)
!define mailgun_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, mailgun_icon, mailgun_icon)
!define mailgun_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, mailgun_icon, mailgun_icon)
!define mailgun_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, mailgun_icon, mailgun_icon)
