sprite $maildeveloper [64x40/16z] {
fTHNOeD038HXeMsIDlU_RlhO0YPbuNzp-SQ5ui-AdAkUij6gohxyydcW-2bhIZmVg4wpoZq6-AVpD_BdywVp-WPF1ZWFpvd2am76FJux3FYfyXkVQS8swhrG
xZ4H5WRtNi2PpnEDU-zEY_s4kstKyqn4gyLkeItvZtJa0SlU63fwaHgfuev68LmjUN9Qz-H5xSWt8LuIikoF0wP2lNeuoXu3YLCl5e-onq3Yt0_kCP0uzvrx
3E3YMFvy382l_duCF3dtpZtI0Svz2Uv9r5kWwHTyZ_behFkMUDHLhpPJiIrut3zINNoX04QXoSSBYzu_KPTRtkMUrmL_VZsANFRWrxshtF2pYLptqJUvxATL
s5K_mtgHVMy
}

EntityColoring(maildeveloper)
!define maildeveloper(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, maildeveloper, maildeveloper)
!define maildeveloper(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, maildeveloper, maildeveloper)
!define maildeveloperParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, maildeveloper, maildeveloper)
!define maildeveloperParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, maildeveloper, maildeveloper)
