sprite $mapbox [64x14/16z] {
dOy7aeKX28C324BU_U-xy9VjFLOOFpD1ovEiRVYVhFXeaV7ZI_kiIJPRHNB_m5VYWwGQJm4qIRzwSgvxlo-Pn_cw3s-ykc6GUd3-gIGZZizwpuPyMbkGSmQW
Hwcra5cTV45sAPmqG9cwZoMBeS52C6qnaLqxNUeiDuF6vcNGW1sUojNBkhASl3cy04x9wdhNeWApLKEJ7bq641TlDr-VytsxUKSDVqZPILxxgtE9S_WjyrdI
9vDmgzRHfWOlVXr9NlcNOfFLNB3856JrkG4xIXttadODZrs31rhoQgdE6Jmk43dEkty-ilw0R7g2VAxclz5gwn6tu7EPupj9SCmN_gCd
}

EntityColoring(mapbox)
!define mapbox(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, mapbox, mapbox)
!define mapbox(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, mapbox, mapbox)
!define mapboxParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, mapbox, mapbox)
!define mapboxParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, mapbox, mapbox)
