sprite $maps_me [64x64/16z] {
fPS7Tkmm30CD4FJzR_oBLtaXj7HxOdhi6HQvRcS1Xl88AOZjJO0VTF_zhdYieB8DyH6T5n5tD9JNSLr3v6q8fpJoKV1zvnxnldOFBU0cC7n5m7mPyM3o2eBn
HD1jnyqXXSlc-M41i_SZO5iTGkCttdJG55X6mi470KJJGQDNbKeHcIpJy0xwtdwNuAYGtLBXTEb34aTzXjkmuwJx76Y3UpwlPzGB9GslQ-K0NISq2PL0gkTb
vKUjs7uj0g_Nfkyjbr-A02aL1B3q9Z3F421b7KVOC5nWVJ0rB3O0QtyM77WHC3KVSDel18df6gEneKJXCovv3FxYMXUEcm2fI5rTx415nKs053QcBkupt4BX
U2OAlWt1UVMXc4U4WW_1nKKz5FCb4mF_1ALgrpuTm24ENDGG5FmG5DuprTLHQQFWq_ZZ-w9TUDg6HY1-BRz-Ql9Lw0M1UO1A_63I-2zcGQbOLN3WXyIbiw1C
p0UWiPyCdmKi6z7V5LLmEu3CJg-r9b71NG3PxlHUYy3_XeGDfERTRO0kk7cqnDVbeB_lWA6B9u2BAn1xr9EnVxW4zV0PJFDppqNMhbVa-vZloMiFW96vzW2g
r_YI0DkI04il0CBI2qYyVVlouD8BsDrhAE95voyDmgituFtjswzNeSB6AVmN
}

EntityColoring(maps_me)
!define maps_me(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, maps_me, maps_me)
!define maps_me(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, maps_me, maps_me)
!define maps_meParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, maps_me, maps_me)
!define maps_meParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, maps_me, maps_me)
