sprite $mapzen [64x19/16z] {
jPDLecGX34JZKkn_lvEq_eozbboXe3WuT0-ZbuFtwvjw8IfT3QgH-GAjrMQU9zsyItxEUqPQd_B8Y5Vuc1zEIvZVU5Q-MF9_F9CZT_0hDnon3ke_U74JgqWS
K_KRVp2YJesij6H9gxB9L3f9rdQPOmcHPW5HWGvKoAr_J3MWA51ZYm7PKCj22Zh7oKtQ6kUSpg387eNI2rzDqLsC94g8Gea7eW87T3v9C0M8BHlH7Hr0f_Ar
VuN3QtYVtF9Jtht6TZoXYNKkyrS_fxrMtDUF4-2gOPXx-Q3v1BccaWSz-U1616pbWr-YcmmJopVGdAEJ2eqdhnwMMhlYSZy_OaJ6f3hIbOqDObCmFzEnV7vg
rth3pxFdp-sFvs_ulvp_2A-J7jdrSvwrqkLs_vJ_LEbhz_yM_Xhs2m
}

EntityColoring(mapzen)
!define mapzen(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, mapzen, mapzen)
!define mapzen(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, mapzen, mapzen)
!define mapzenParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, mapzen, mapzen)
!define mapzenParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, mapzen, mapzen)
