sprite $mapzen_icon [64x64/16z] {
fPVX5kCg28H54M5u__Uznn0rRQrtTpl_UioNGqOORJehS_f9LN_Z5VGBJa3vXMUufB_GUx7DtVQFxALQSth8t96VC3UZ4-yEaqbak7kTlwh27MSUS8UrSZqb
xkwnWqKCtbVn1SrqyPBl1njJiiw34hVnsegBpv-yTK9TxaBXOCB5SyRyB8PHQMQq_NJ0syCeXdUrXwtYmDu4lLTCojgzI_PgeCFsl51HlzORztL2y2ZBG7TZ
Ah2qutjvTjkdd0ey9AaqYzhKjPk0JxwXTLwdVKdybgs-a3DVNOTzacpm80u3I_1rKt-i11_Ac7oqO34UJttdrqhrAUqbDU2joZEl4pU-9jdbnDTmPl843q4e
vJ4vwdBciQ8ZQ2if2Q8FvovlUNlXsxIks6oZ4zzBBvYJqI5exhuzsbYzTXCsF0UFcwzmH_WM0bzl3RxjUFHIvHu-EDhjstEAgjMKTC_R7B8EMOaYXYJLCPeA
sPrKbAY8hQ4hval8oSPe4fTTTaTAtRAhVqtgRP_E3SNAwAKikk3ODuaTZp56MVqO8KC1JhjU1IACb95Ppb84xBJhGorLZ2ufwEKqVnTw6Rp3mwqdJxHx2Yff
clwKTiYHHoTBRENk0nwRFWKEjuoY4wESjyg3tBfeOthHn13bFAjcscn_Zep6rMlYKtFprixHXYynL5GLHglS6CACP-S8PCTRIhdnLGd3d-79DkmgZIC4jlCt
vrydtUXA0BlxpVmuVy4ljupl91XkwzVvhrZvrTwISwMoHWYVyuyGlita7AVwEJ_doIHloUdWF-NT8ZhH7idfe8zJzd3-CRflpvRJZrFsn6ltxOMl7qyT-A8b
sjdMDEUyEoNtzuVSPqbXAp4ijTcwuVA9Zno54ME6aS8TMccUaj_lFnsEPb_tftdzL3toRD4uSVqQKu0OrnBnZg_tBmCcNCICwjWzirRY5QVxdplWLo36RQr4
P8C9C-uOt-wVrlrHRwoOrrsBtPiNJwtYoDnWdppdA6Bcp1W4UvvkSBj-KDfANsEvH1Y6uhlE_nzQAyzb6j4nLKGF_CvK-_7_M_k5pm2dNsIWdtYnz9EAfBF-
0m
}

EntityColoring(mapzen_icon)
!define mapzen_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, mapzen_icon, mapzen_icon)
!define mapzen_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, mapzen_icon, mapzen_icon)
!define mapzen_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, mapzen_icon, mapzen_icon)
!define mapzen_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, mapzen_icon, mapzen_icon)
