sprite $marionette [52x64/16z] {
ZTNdeeKW201WbI54x_-yjvjqJE8C_ZJqau96UKMhvKCqU0vNEAA-5KZu76s0Y00j0HNe20Huc8CCLQD0ee6YGUvCGq5TbZe1zzufcdQUPiJx9OA3CPGK0O7w
4QzazHBdsGOjA-RXu5oHJeKp1TGn7iFNQSWYPx8pXKX77yXClPL3Ef-YC_h9r62TtJYddsBMes9YRhKTDHnt1gvIuy8174Vql-FghS5HgDaA-3_onoOQNsQq
kwtdVP5t1eYJPxinvNaQpEgbvKdDsue2l37UXYmHfIDkydOtJCnwXjwDmDDu-JpXKj0wJ8k6QaFgeZrM0LfNwOGDxwOsvAwwdM4KhXl9jX7QsJy-u9Czp0ZM
Xjg-J50iXRTWDhuRidstPKOlfKTZ6qpIjjs2aLBqOKodaTsYqLhTg9Cpv2BTR1fnr9eVozrO7uHjlnjV5s0zDW_s-_Syoxg8qoo8Ii51NhLMDqHUGBsicmtW
8YghONRpgluBJM9kka_fgp6J2mrnaCClaqIYCP50zc1Ket7aHFx9TpFHRYBxRZyPKt6Y9mbc6qPNOyVnZUoNKT-P9g19xACHD8-DMRr1HlB9QA4BIR-oSFbY
9hgozFBL57OpoLSpC_c5FOq-JS7jHQXaPcsnVp9raEjhiaxAJQdoRxILtum7RSR5euP9iYvHmvygDNqrhIHHmpl7FvWMrgVmxKfD-8RWQZ0pi1g2rL1cC7mJ
sthCcOdNNtMjHMPyZEJgX-zuI6RwqdwD_onDo7DPMarzaghB5FP2pcXvUpoy7PLOHEUPj3qUAjAfll8tGEw7vQpKAfq9M_NfVm
}

EntityColoring(marionette)
!define marionette(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, marionette, marionette)
!define marionette(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, marionette, marionette)
!define marionetteParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, marionette, marionette)
!define marionetteParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, marionette, marionette)
