sprite $marko [64x54/16z] {
rTI7Wkig30JGGK8W1Dp__zmN8yXYPo-ljxFTsI5YNF0cSUA0DsAQ0X2rk8nFL3BFFECjPLe0vEAKyI6R2Jy7O5NP1c0jJWCUk9Xfd1XJLjLz1wbCWWUrbxG6
80oYBuaM8Bm78Do8NSgzGj8XxXMMAJ_Ai-5UOTBX-mhZepmNjnsmJdk5z5s5iPZJmEyAGzQ9w5nXK7E5GEy1H2S1pXKccn80NhAw781mkWf3NW804XSbE_Rh
sEqLbeY1bu2lrhDC4HVQBYsogOn0U5psGIz9fe21Lpxi-tsyucH_UuRRJWn2-UfxAnpRLIyB5eeJ0T4cVKpl-6jwWdlCcMqItfPzYt4hRw6jKRBgZ2KDrz4p
qIa2gJPN49CJmX7hb06ghLvQ9OGrWE0ehpW1sgfB0E9QW74GjxiXLjSCBq6MW9yA-zrWQthlZDDqs46wbUUQmccP-5VBI_Vo79T9VrDvTKfmfyUoav-Mvq9P
2D-WhRombRViZ-LZUGpajNl5Pd-cBESBlmIuPuK1JzkTlpteiTahJ5ZED_v3q8yApmyUTwpm_E1RpXKIBm2NxS6xUmww2Sk-5k7_9YRwK_7M-K_b-x-Rvr_B
HxLQIwHiTLm_sMgrT2LpgLNJo4TL1kdrZtXeVV0V0jH-AGX-PEJZTI3w0Vt8cyWhf99Qhu08S-cT_8LqxP-QhzUIME_op6T0nfIvDy8bj2veFNb_gNOBy8sW
zlgH7ot5kKf8nVGL-ihtAuxYmTnR-CpJo5-pykpZbgy1i1y6u1g3JddhJJYsFL_60h_j_MCR1T_oB5VzoSknNd5-_qg1xddatbDelKOUpPpoSbqBRUp_Hrvv
s8zEqeU2kr8JG6OCi5L2jDPRBGoh0ZyslcV4sdlBM7u1
}

EntityColoring(marko)
!define marko(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, marko, marko)
!define marko(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, marko, marko)
!define markoParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, marko, marko)
!define markoParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, marko, marko)
