sprite $marvel [64x28/16z] {
fP87ajmm40CngVt_5pkWE7MqdEM-srsb7e0bwZyeIBrd0FIQXdduDQMV4o4fmuUPftm7F0lbTrQdXdPMQC0UZ1GmQbh68nkWV5fH4z8m0oW1Yw4683qnOODf
9UlFEGhCQ8w16heX1PsGgqDWSdNIYGbLW8kNMnSkqwiNJe7UXjKs1YfXW9OIUd1y2LWzEAId1xHdIBlghRMKyaDN0uMB7JNa8XwNK3uhHWrCoVg4NwfJsbKr
MBM4JecGfzKkxIGIIf-aZ_TBSGQD77ijC2rEDRXoqxiD5LQF5HOS8hEwis1Ii5j5FaXe-QkWXiF8j9rlrE2ZXWvjkR2rNqj3Nxl_5nIWtM3xPgAPLAJ-J4FR
ZtFOJ4ZFmBZGpUnE2INqGyhgdk698sI0FBuoTVWc3ZSp_S6q5ZuHKZ6NEfVMbHcXNx39I_RSvktzqOzirgtKNp9majVjrB_WaZaR77f1OZhqZd6qNbFmrlu2
}

EntityColoring(marvel)
!define marvel(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, marvel, marvel)
!define marvel(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, marvel, marvel)
!define marvelParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, marvel, marvel)
!define marvelParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, marvel, marvel)
