sprite $mastodon_icon [60x64/16z] {
xPS7RWGn24KnTUv_uUtbhn6AyAGdJsNhCmpkD3DOrDmZOhiG9znKU12IDVNOIiArQa2yjD2Nh6iAM14wPUjR0n-enjOY6DKcyOZiMvkWAxejO91n6wOJbl8v
aRzAnSvX_Jfq6FfR-P8UMmgiLV4jTIRxzCHHTJfTP2C4vQ2HUmt_wOIyHcA13pBFgsir4OQ_gs4ICmOPvwmTtkkZSP51m11vn8SyiTy6pYc7w536r_fWofYL
WugVenhUsF18d-k9urCbPNf0UTkLrvb2-Wxklni_qFKzRfIkymKlNIlSJ7PrXoixNFPrTwoxGRRiEcufSI4vrUy2OVgxDw-gJ3GMNONrjaS8r6tjZ6HzrGPT
aRR9iCbs21tJZee8Ytb4ji8jdM4r7LzE36PHDJzXfYeyKAkILkhW6-8jLz8HTJcmjLnE4xM1xIbNp2E0q-M7arIU-iFTz89vFFgzb6igjxxbD2eeANIdW1gr
ccgLA2wJOSaiV35e06PUuWW
}

EntityColoring(mastodon_icon)
!define mastodon_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, mastodon_icon, mastodon_icon)
!define mastodon_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, mastodon_icon, mastodon_icon)
!define mastodon_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, mastodon_icon, mastodon_icon)
!define mastodon_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, mastodon_icon, mastodon_icon)
