sprite $matplotlib_icon [64x64/16z] {
bPS9akCw34C9S9-jxt_RFsh9KIdkPFfZ5bPPUY05Evky43IogeUgmYZ_H_IgT2K4540jgaA_IrkLKvPmLSjoV8FsYWblVWbUWN_s3gpZO_6dkR-ZaSbHDIlJ
Dh-5ABx4jMqsIJErlFD3V3c25-S9JCtC6Y1LIU8qoVmIZvmdcBHxy-eFa3WQuGMkxOisJJtk7_dM888Y-64wQ1loU3h_Te2NdF8KuHX21prLcr_OEWKXdWUk
O-ymo72xLDZykh7anCT6sK9JfW7RTU6QVF1CPdxQSU13fPjFk-O0sYv5a5GI45T0Q-o2hOdOs0-jx91r6RXxpVu06qFf8doaw77npGiVHx3IGSy0v_mQ8832
61wNGV79YFE_o7aFjBZu942cphCJvzYDXL-bKZ_viCaZ0I3Y8iy1RBK7hZXOwocCoRi1i12379qijyjs1ScLOKq-0R24uC7FoLahXU8EKQT1AvNGmHS8UJO8
5t5VXz5CNalmKdDB7VtJW5Jiw7PKzHXV0z1CNIk8CbFtJnu8nn4TLYrWZPzA4fgjAviE7G50p65fME0vG9hbSkAKndnCmNQr0YJ9EgFRnJBcyPcOEC4e0yO4
fgL0eknilETWrPpNZOldSEZXwctXufg-mISVz8el1hYbNYuIvQKLUGDtwPgNSt5N0RqSLUK_UktcLtpr4P_kCXooV_puGVzRz2MFKN3dIQZtduyVFtzMLbpF
pbLqbcnYg7L0ggeNhnRLl__odX6XW093Ic2NV9uV8DKZAzpxT_VFdxw3kvVidHz8Cy_CqKxWFtucglnNlk6h5g-VJIkKysP5LQfebUQyn_YIxzBhSz-8nzjr
fPT1H3qebMqJkDcWmsvF1pCj4kDIg9kWlUB1uNn-BMvZbMd5t94SwzfsvIIdZILhr6CyxQGOvstHd5zRebSmpsz0XTi1TFYF3WnC_qgpzelRjIWhW7Dbm23S
m0H8AJVBt5rcHObexakhxcLLJSTdqEOMfMTxZzl7nnfzga3Qd4zh6BGUXotE38u1ziS44gJ6wfKMPkMhrVxMWDv3dVtDGJBNSgQvQUQUDCTeUm0yeYFdWe94
NQlbmy1RbpslbRv5DqT83ZwnBg1j6jWw_QhYSOyE90i0uRhiH4jjp52nFxvtZaD6sM9MPcKxPCbJHuWw3D3SE_lilqKzBcJOcA0WaYvRdcTqMwSVsjLyvELr
BAJlw5xp1DkyLKGRSgWCk7RnpZ-SjGj2RSefb8zoSy2cznktrecV1citDWySC-tkxtuNW2HLUVi1uRlxgRWlu7ub4_92MdxR_cRBNOZITpmpAM_5B7l5Qsxt
jmx1Em-lVzDxQnfnyO153TFlQn3TLPavQleh-3y
}

EntityColoring(matplotlib_icon)
!define matplotlib_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, matplotlib_icon, matplotlib_icon)
!define matplotlib_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, matplotlib_icon, matplotlib_icon)
!define matplotlib_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, matplotlib_icon, matplotlib_icon)
!define matplotlib_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, matplotlib_icon, matplotlib_icon)
