sprite $mattermost_icon [64x64/16z] {
dPU7SWGn24CNTyJ_Vszws3sDDUD4qtBb0GBipLr2LljqHyph7xA-WFYKsz_fjX0_GlaxxOZ4QxvTl9tGrUCMRiGyne7lYHlsySWu8_cJvF3-udp4pLjJpZEv
jyqdyvV7tEBZ5qUdJmhYXOzb6pn-j7XczcrhNJz2n3A1xzgqWlbyaUh8sbNaH3pTf2fazeuj7vqTPbIEp7m3xUOrV-TsiIpnS7Bad2DGHEyukBzwTMb-nYtG
GcIwzli54xrBdk9EcJvz2TuU1JJbtX34Sm7ZsIBNlKjxt05xPEcRlHDyccxNrVckoWoQp-ZphXB6wJMVlOKPX7tVyjpSMkbuYF9pFho3FVP7fmgUfhFcEMyR
7awyhj-tsv7yKij72OW7XKzDBh_kU5vlRM39-OhZq-dZlRyxIzyyK59eeZmy2cIrhD7h9QfpcYz5c02mkicBSGKPO9ablBC_Q44EDT9OK05dokULWJPSICos
NIvNLAlWpZX2JLbhFMPUm5jsNdrqNcG_Q473es6yvrxEyLYxnqmznb5tDpKw4V9GBN7LBEcX-gxI7YGCsuvzOd-XhM1XLgRhf4OPxHD5yDcA_JWiRJf_fwb_
D6u1lZxas7mynMrxAD-iz87adjf907rEpWFe9P__AbvCGGlpu0UG5jh9yT39gNQnuu9UzU1of1hKcT2oDi4nyY5s9gjZuVbJLC7l
}

EntityColoring(mattermost_icon)
!define mattermost_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, mattermost_icon, mattermost_icon)
!define mattermost_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, mattermost_icon, mattermost_icon)
!define mattermost_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, mattermost_icon, mattermost_icon)
!define mattermost_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, mattermost_icon, mattermost_icon)
