sprite $maxcdn [64x15/16z] {
fP450jX020G7MVR_FsxlI5FtYUDiWFA_Cn3-7o3jqIV6jYxdETSriuPl0kR9Rrkyj8TBJC8uYEAGZxsjD_HcodRmCgzRq0NDfSIYDUpY3MExY6EMxW27eBQg
YjIn536Z88lSJzkvyWNf1WzekZu2EXRQGVkGv7PQGz_FeFOlzFKB52nZGNZWLMeRhY6fcwX7XLkgY28brMQk73vig23N4EXTls7zIGRPtKbE450DVO6gXDZ5
TwpxlYhe6A2JfH8cN_cZM7G7juXd_MUN9Zo19hWa8GkwOijjbN6YEt8zkls4yM_PcV-30ldV4V01
}

EntityColoring(maxcdn)
!define maxcdn(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, maxcdn, maxcdn)
!define maxcdn(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, maxcdn, maxcdn)
!define maxcdnParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, maxcdn, maxcdn)
!define maxcdnParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, maxcdn, maxcdn)
