sprite $medium_icon [64x37/16z] {
hTI5jiD020JGMNVc___s6PLzdAPwZrOW34aMLrngKqXPlGGyBNJXnSmmGfkptUZiE_zP2RlANnMmij3g3bSQLJl5dMFxpPeUPvbd6gsGUIktbeTomZFvcskH
Oo-tbhCJQW9_wfHvODZBQrdYjmXuuP6iMJVbT3igq7b4mqvk9e31RnsUTrJDkl7QSgBn3j6icwGR4IUy9m7L3gM5aNSrpNfjd29LthM0PRyBkadU9GvYbwA3
BzuNdArtaG-BRzVJUFlwR-V_pFxRc_S_yQv-zFmzzloRAHkq4Er-_AFt3-7Lzt_fRiPRvy_Tyw_SEl_QQRZomFdhpVZ8kjl34rGy0FEVZc_XylEuMHwWl9Yc
YvnRTsC5d9Kz_RTAPgXAMiFXIj-c_-RMn5cOPlQCNJiVfyfj_TFOHYyE_yKXCY9kycKiVfDPpR_C5TKN
}

EntityColoring(medium_icon)
!define medium_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, medium_icon, medium_icon)
!define medium_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, medium_icon, medium_icon)
!define medium_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, medium_icon, medium_icon)
!define medium_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, medium_icon, medium_icon)
