sprite $memcached [64x64/16z] {
lTU9ajiW48JXqJNTZT__UVTI8JD4B45KyYTxoACFZrpdMcxPzWC0Em7mOrijjXxWK3YA8nRdWpoVi8AFmdPoFUvd0xuUno--fLTwt6xcwNalc6d6fsLDKstx
d3zypZjIaHmuOwh2DKfbPBW2SwevSxzwtHz0v_r0uGei2i_5XazjNqmSBHzpbYay_BXdtBxlLNd5xViUZ2bit_K4g_9IGrugxjMrlRe7P9zufVVsKiyZUu4v
yAtGy-7EqA0NMFCXd_xqgU_zFISg_kFngrVXLVkmNz-dYWzxeUtLykKy-ZWlqLKvbn8HtZxCRulpy03Ll9M7ssklCI-YuXppQdd-fIVgwp4lL9V_svEI6CO3
FZJa-Kyyfts7LnxkF9sZ_V6pvUbV_Rpw5SOypxTtP-7zrgFbURBp8BO-FfQUYYESBvm_iul1DHMEEUyRf_o-JdckDkSNyndlPZCFmCtCyDp3R6O1hlRTHl5H
szGVe5ZjQdEIxEvHtEIRXPPrFnnaF-3OroMxJm
}

EntityColoring(memcached)
!define memcached(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, memcached, memcached)
!define memcached(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, memcached, memcached)
!define memcachedParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, memcached, memcached)
!define memcachedParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, memcached, memcached)
