sprite $memsql [64x10/16z] {
VP870kKW24G70GiHvlwtNStVtbvYzzdn7-Hx-WiU1xKRst_aLRNxIMU-gUw95utm4KVl7g7u5vlFAkf9zqa7Z86N4O4sUqIJYAbYXkODW1dGMdEvEM49qE1N
awBeD_z8WAuRpmXMSMTHPMTkMKpMBavirZCLYtuTsZTV8WRG8lnT2WFho1opr3XMYN8X2hAIP5yq0Ejt_ox_-WyxEe6Q3pDphWsXOnOQ89rxS098jb_NlsBf
P_tNb-FF51aQttnbkau-KXmUt33kCVgtyuleyps_xxvaPTbt7wD8xWPBNeRUkBxVNzZd_amW1cY3U1Sq1UmaXbisNDJT-n0xwFVtOtPZnnS
}

EntityColoring(memsql)
!define memsql(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, memsql, memsql)
!define memsql(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, memsql, memsql)
!define memsqlParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, memsql, memsql)
!define memsqlParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, memsql, memsql)
