sprite $mention [64x13/16z] {
dOq73Xn13CFa9lF-_-70j-az8I1fon0ZgGpR-b-6DnlwC-tycRw-qk-fbKpfMn9WdjOHYj0xd_lP8PJz_MS3M-AGDAoXBf9XCs5WDRos8LM0h-SMEbAAgEKM
Ag6AbGaj6Xn32K931ex4CWwJi2L9yLmfUCB6NMwoAHMbHUfxJSbeI3K5ZxT0Vkk_yDfnmYT_o25lOuZp3OH2ptvoB-zHwPFFuz-Z5Zr-5ZYyrJ2I4l9JciaX
pCXOI-SoiLjzGxz_3Rk0sP3KTd-AUd6axRZaRjjMc6sLFNclCcyszP_q0XFwBpu
}

EntityColoring(mention)
!define mention(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, mention, mention)
!define mention(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, mention, mention)
!define mentionParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, mention, mention)
!define mentionParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, mention, mention)
