sprite $meteor_icon [64x63/16z] {
pTQ74kGW20RWK0JU_uMl2lwvDQPTSvh3n6z0c5rvUxbU0_8MK7ftdjf_1V0Jm7ZivIsW3m3sjm1am6rODp8Gm2ZFysL00901o3F0wVvjg2liCtD-3RGRmFYs
LJbYoqFOf7O0qBATV0HevfK0pm4184QsDW2dLJknIOP0jCg5L-saHWXGXjq78F3b2g0TKDbO1tWEi27W2D0lW9q27cDw4D0-t3oVVpu0d7eq0Pi166O0fFRa
lH_gCXzVGK0-07u6QEqv-w6kCw2Di20G211-kGOqmn6k5Pq0H3KchQgP0bh0BW4k8108hN14gs9uqhq1M05vw0gWZ2DRQKUhS8HbrEKwO0ZG0cW28vjfJm6B
cFNF0604ACCHda3CW1wJ5S0zb-mqB490073AC01Xdq2Y050UAa0oEliVRZ1zdu160kpXsmomCJn7m0-PXBOvGDdxJ8PxsZsSydm90744U5i1JZZpU74PZfW2
lKPtXju3e6U0z4jonf4j812mu_Tq2vS2d7fMlUuU3kVvFna2ZAtBjA6ZXu25wm9W3s_BrwprOWLR1na8hr-pPE5j3XYTlMQbrmY0tW5y1sX0wou1ujhlpWZg
nju_1UW7uDVUah8737x9BmBPVQYRpDVruvjDVGzirnVLq3bLtRJTNGr_CJsZjm23Dmckhm
}

EntityColoring(meteor_icon)
!define meteor_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, meteor_icon, meteor_icon)
!define meteor_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, meteor_icon, meteor_icon)
!define meteor_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, meteor_icon, meteor_icon)
!define meteor_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, meteor_icon, meteor_icon)
