sprite $microsoft_teams [64x60/16z] {
xT97ekem38NXeoxdxd-zhz1YXHY7C7dbVcD-Mq76QwpkuSOuXSpZujm9xF7WSYu_Vm1v5CvuYyQ6uIqUCHY0D5g6ph--kXUIxIBvuFZr0wGzy9a-rpvEzDew
WY4PzDxtXY5Qk_A2eky38BLzxIhpqTDJxv2sJ6HPttR-QVwLvNf8tpEMQTysho_wyO_s_iX1sQz_cMg_Qy6AV5tUl7TJOHINdIdXIDymL7kXdhpTrncvp7-Z
5xPIdlTB2-z5wzdwir_I0VXbFsL_HRRUKWI0UDv_jTz_zz_zTqz4UQ8l_gh-QsPs_sTzjizwbMLhrcTR9S2sqMg-lEe5pwpcIux7D-pWLWtwaXTHyk7umTWd
sOlAsI9_SS6GnP0hviZ7FOuG7-M4GzJtSmO-EC05XubFRfyXyya_FyFh2UvAU1-9-ILcZFm4
}

EntityColoring(microsoft_teams)
!define microsoft_teams(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, microsoft_teams, microsoft_teams)
!define microsoft_teams(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, microsoft_teams, microsoft_teams)
!define microsoft_teamsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, microsoft_teams, microsoft_teams)
!define microsoft_teamsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, microsoft_teams, microsoft_teams)
