sprite $microsoft_edge [64x64/16z] {
ZPM7bkiW34JLg1B__xclSZR4yJYwspUvOh3d64AmgDe_L5MO0CYrA_aPh7QFIi8MUq8ujpRcCGEmanFOSYZQUHPbeATXeESJ03q_0EXfE77bitV1C1W5jKd3
7-bBxNtCENgl9Hz0jzocnmy-UyqrMVxRm-FAh9a0_-mUjupdRV1Ulde0l7qBe6Oj7kZF0NZhc64O8T4QW4G29IqU6F_tOZK8sS1oBwhMFBn0dt7wBhkUxM47
0fTlz4EPE82ZrUcWLgJ3-48dq0VnLqyU33FkAU1eo6r_XT8xG5UWPttnUpqivzC4VatjN-xybRx-IjI1xudbbObg03IJdiWYKI25Eh5_cFkxl7o1Ej6uzsCD
UY7u_At8VwimApgz9IwW3hFeHkXamW4kbA1SjME09dnsvCSAe-zKwCUApea0q8-rlD0jKk0Lk8ppAdH5-_c86Z30_diKuLTUQnxhBAWuzFSk8doErchhO_xz
UxtNgyGtrkRlBpSFw0O28DPaUcC485bD7ea0k9Zv0RZNFJTWhIcWo8u692kjyzk0VTyHZ2DiUmWz8jsFjr_jQVGLQNuwno_3A0MNxfVkHimgb8UjZTUCsGkI
VmC
}

EntityColoring(microsoft_edge)
!define microsoft_edge(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, microsoft_edge, microsoft_edge)
!define microsoft_edge(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, microsoft_edge, microsoft_edge)
!define microsoft_edgeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, microsoft_edge, microsoft_edge)
!define microsoft_edgeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, microsoft_edge, microsoft_edge)
