sprite $middleman [64x64/16z] {
xTS7ZkKm30DGgzhtF_4YYB8434R6zZ93bAcFSdxL7sE8slT5nvLUzv4VuwQYzaDH-sVpww_GFL95jIdfw9npJHbNU4bFrxnoUr9offW_415Uud7HLRGwCaEb
6hgIeWLBkZ-tlofh4HJCnIJ2MqJX8Rkecg45_Y1LQSlnhiYyNoL4LBKjtNFVYwly7RN3F5n1r5rHlc9VivydxySgxe_9_6DKwkVz_WkCPtxWPNFt5SUFp8jY
FFChCPxvWV6xhpX-ObuKupSF48ju41tCum0-sNmSOBH-OZppm_JWSyxEo-0UwVtuXJuWWtY15EfzLbOuyOh1tEEcD-hbvEqPJpsANhtZ6-O5tt1lULr1SFzy
futtGipNjzBvwm3-xkrMZVVRl7aTqdjBxxnTlF4LxYk_mgyVyv7vpNv__tCtnDTglEbfa_7CpMCQIOIpaWWwhRQ9VVz8qj8k42YenGSjZKJWipHhWToZT7tR
MzuMk7O7H8kqkzzv1vMMdakasttF9Iaj_Vo8f3_enuzDbo7w0rpxLuRpzF45
}

EntityColoring(middleman)
!define middleman(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, middleman, middleman)
!define middleman(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, middleman, middleman)
!define middlemanParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, middleman, middleman)
!define middlemanParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, middleman, middleman)
