sprite $milligram [44x64/16z] {
fLQ7hWCn22ix___37OHxw4OWqgExzJcs8L5VJuNqsYwpRIYF8PjG6D_2FQp-i7igS7Znbh4n2tgeV67gJtiAmCcfD-PIQSCUEoQkaOre-v0lRDoeS9MGsHKX
myazbYhqdAeKAYYxrQbm1LnSV6rk-rMIOBFKLLod8amtqJHXUglfha2w8DlcfuhhU3Kgcc7DDNEysgsIngZRWhc8jbixnKDxPA3JLiOkArj7cnWAMZA5SYFA
J0IcQYk9pJ6QYLTH84NG6ncBJ0dOdL-_ttzy8O6x95pqT8XTxy9QfD5ZTnh23VO_6iARbF46cUPKQ9EPiOVL3h6F0iQOQKqyHo44uoWLkzHm5Q5W9I6d1gnW
FWWrNd66_KGTVF46NFz4CoxFvem0RSoIvTaCVp-31FXwYAPhIYvqjDsWVFweGORCS1qmkNvXry32mhMX_1WOojrg1cOP6B2k_b61ZYXJ4JKxFk7ZBDcubV5o
ylICr7Ah08aTIlWw-ny
}

EntityColoring(milligram)
!define milligram(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, milligram, milligram)
!define milligram(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, milligram, milligram)
!define milligramParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, milligram, milligram)
!define milligramParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, milligram, milligram)
