sprite $mixpanel [64x21/16z] {
fOu7ak0W30H70gNX__yzIxxDURUT6b1N6N_22o-GSlo4E7Y1_hGd_aGmJBDSOFD6hBu1SvX9LFQY3sDaFUpihD3kBwfOoIGJma1HiERB2jA0PEN89cl4cL5S
21xkNbA1f7QlpCK2YWv8KOns2rW2IOhs4RAwBm3A0B2vfMMH9K07ivd4BPsrB6EOMLAlFgTtFFN8MTPaYrvrYodjxlsmANctToPtzmh0k9A2tdtghSy1mNkz
qP5K55EnMDWCaSsdVWjB8L48ydc_X2wz8rMe2buim7cHt8yzDXj3S2akbinxP5mNgh1ipu6QAROyZK7s76dx-tJ_9uhu3lDlx-6ERx1ueQCIeVWfUSvXt4hM
o79ycpeNESfpEE9KV1VloaQDBOtW-pWPk575Z_a7
}

EntityColoring(mixpanel)
!define mixpanel(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, mixpanel, mixpanel)
!define mixpanel(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, mixpanel, mixpanel)
!define mixpanelParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, mixpanel, mixpanel)
!define mixpanelParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, mixpanel, mixpanel)
