sprite $modx [64x18/16z] {
fP07TWGW20L512py-ryte6vxDSdE5ifZRALo-OegZI9GFT3VVLKkP9Vw7rz5hzxAl_nWwtgRt3vYK-6Cr0Acj9YpPhv-y7xwXIrMznZcXM149aZSekVEEQR7
FvYKfxyo38HV7KDqOSOvi5HxrALeJ5WaBryQqyk7vdZw0psFkY3HcFjKQBdsn0g1vBYrSjFwyftkluDBOEZNBnss5poN9DwkYAZPm_SOLzZQ_bvLNxxj4qtu
sQwck_MN3vh08WV5d9otiEkVZi5FHLSN-_0Pu9A-m1jHZDVqYRZ3ALAl0pd_qFNbRy_wYQK33kIU4bcatWevv3nabOkz-MFIZdraR6Ejpf7m38P6JsUFMkOW
kLIv_j_WTk18q_y6al2_elxP-04
}

EntityColoring(modx)
!define modx(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, modx, modx)
!define modx(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, modx, modx)
!define modxParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, modx, modx)
!define modxParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, modx, modx)
