sprite $modx_icon [62x64/16z] {
fT19jY8n30LHzTx_ZelUXVWP6ZYcS8zUMkwfoq6QQIUwClH0LwMVw9lN4rqP9_hchVz0PVjJUxrQc3Vz_NhEEELBj_cwEFtIVNuo3jcwUHzt5pnjfYtEckuX
Ja7Dl8GrUsVDFeKrSsNDtWKrynBMx8qr-n3Kp4jOipVMx5DOCrVGN6QwW4OPfYAWuUQMhBiCVq4rppBKVUoM4PcrLchZbYnly2RpWM-vj3pRM7j1UyfNwrbP
unhPFhF9r-aNtt3x_fczzKakKuij6sQjlcMlM3VPMwWziKAjCM3KZ7E1ddUZrkaqwWcZDiP5UjwDUi25scB0gAVTg9rneRRfD6h6uKNQ4pEHkDOwd9PRcbTw
mFeQ-BVsn7nF_DNpxftLZtPEvV-YwnwdINhEZxHea9wp8ZtdHreqvT4_
}

EntityColoring(modx_icon)
!define modx_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, modx_icon, modx_icon)
!define modx_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, modx_icon, modx_icon)
!define modx_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, modx_icon, modx_icon)
!define modx_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, modx_icon, modx_icon)
