sprite $moltin_icon [56x64/16z] {
pPO7Wjj030F5POF-_-3qJHPgfDBdpjqZ0whSRb5ta-qjmpyJ-iuISn_peO-ww_pPCYmNesLqYyafSxCOCxmmBqDnpUwdTKqvfsdK5AC5TkDeq7jbsBhOELMH
lAZPtY4ud7GZSirXqOx8cyosdq0ZRAaScHckyiOJJtmbqwJjQM8XjVPOcwArl94uuXqlSCPhR-0AwYXgxcw3FCSbGhl8LtJryjgBTV-OsEBX1f_QolZk2VPB
ROUTDRVLk-7BkZ5d2c-AwWUauUrm3wRdxSY3wQFZ0SZmLOkEXo_4QkRYuL43yeUPM3tSQrET6diej0NsqBFOc-GNG1GUyRzw-mj-tTiSBxHOpeEQQ5hu-lsO
mv6XfNtxjeVCKviuweXZNd5rkM2F8cpgSeMdQK8VHDXv5j4ox2p6SyuILk8ouhYQCVajpQC5AaPG10D7B2R2wveXvIX6suJNVJNnyZQ15JCcXPsZa9dGE_rP
iJzZKflhTL_NxC-ON5Ex4Rbcn4F4Zm
}

EntityColoring(moltin_icon)
!define moltin_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, moltin_icon, moltin_icon)
!define moltin_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, moltin_icon, moltin_icon)
!define moltin_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, moltin_icon, moltin_icon)
!define moltin_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, moltin_icon, moltin_icon)
