sprite $monday_icon [64x39/16z] {
tPP7WWCn20G9ae3_FzZPrcXfJznSznP5SA2CDWzlIWdH2y8qYvZ75JUX0TO7CXltUEAQYYy-m1uT5r1z_e4MKngzq04cZ7e4510Ta3dxZfTkFqAG6X-eoNuk
B_ucB-lo5W7zMHEhxCCPswkiie-6xV7-x5ZvugXxN7vkzHt3myFsBTlB1dlDvUiNsSiwUuNskBn-nUhNsrTeZyl_YyDbhQqLsNkufTcDohiEjzeBsN6unJgD
6h2VBSys1GnFvx_pr0RGwd6UK_TN7AmUveLWte0zx9zmlZYmloB07lHF1kolyBl3RKDv4XyEjoF9FWjSTTLJF3r0KqgFyysqkQC_FCHTVa3x_T_XKciHoZ2B
C6Nwv-yC
}

EntityColoring(monday_icon)
!define monday_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, monday_icon, monday_icon)
!define monday_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, monday_icon, monday_icon)
!define monday_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, monday_icon, monday_icon)
!define monday_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, monday_icon, monday_icon)
