sprite $monero [64x64/16z] {
hT87akCm30LHW0G1YRx_UJSwj5oW1DLkLvgn_RwYh6hTtEDNxiEQofsq3uzZmyeJRKIQzuhk7ilShdIZldyE5fSDhHty_YbqZrfMF_UyaVDweyRh0prkPlcT
hzVfmSkrzEBh-UVidn-K9Mu1phvRZO_sdD7ZlUzY9IvwV8Z-kQDMuMyVYgl_uyMkERpzzeDUx8hJ-_CVUB5BVYJzoujTSFeXCk0niERqBkBm65Xp-cWju3cm
vlJMwJcmvlHZq7DWpUdTwP6jENqa7WFaz8oU6NdLCoEl-sWOEFBGWjzt3f1lKmltRtjmWFnHz1mWp_n8F0V0C--MU0o0vxub7WFWgJTDF0R0Kz_4C_yS8C-z
VjuoXtyEaDCxtypsIl7hvm0-W2TXy1ZO7lIhw36W-BViEO3_wfxzLxyWdUqdtZhwdCm-qUEi-GdlLmEgDaq-ZVi38IpkygryrnbVh7yPc4s-qni3kFKePf5l
2dNxASoGLNslF_SydnSwL4vhCK_qrkMovdEXeqifjPZp6sz3fPvst_QFTLlXdm
}

EntityColoring(monero)
!define monero(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, monero, monero)
!define monero(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, monero, monero)
!define moneroParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, monero, monero)
!define moneroParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, monero, monero)
