sprite $morpheus [64x13/16z] {
dOw94SCm3CD8aNIYxZzmhJmB11V3Bte5KAkx3-4ZwT_G1p_ctLVV9pvGtTB-WPDdvqD__4xW_BNWRcBGFSgvx6tRX0WMP6zXblEYEs3w1Daj3Clm0bEC4DKi
g224F0USPGKfybWiiyqWg-u-Jc01SoXEVpstustTlQ68mEuOEdSyKOM1Z8di15n98Ifx3AIc1xIyDWAtawVV2XXhelcke_V_Mu8oTzRs6k2nSS5dbBRdu_XT
bbH0ZIWHMY_19_Jcn3VAKmkV-0C
}

EntityColoring(morpheus)
!define morpheus(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, morpheus, morpheus)
!define morpheus(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, morpheus, morpheus)
!define morpheusParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, morpheus, morpheus)
!define morpheusParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, morpheus, morpheus)
