sprite $mozilla [64x21/16z] {
xP55bXr130HJnQYu_stz6ypSAyF4ea2ib_nL-5omZ-CPHGcoCWy9wc0QF6DBcoKvp-WAK1K_DwQKLmfnq4Ce3j3YwxLXfWkdf0ua5OXgp1miDawQ93D9vJWp
a2MJR55ruOGZqqq3bvPB8Kg5aourbXGsMGP36koeHD7mBWsk_2avGyPIWYhZP4WEGPN3wMIbsxedszI0DVUHaQ0emzxkNUR0dKHKkvzHvSYGDlXPzYQgtHAs
Q6RVoqzArrQdDUFJp_vRMbVP9flUxdowR4Eyvp-yckoW15bXUr4dg5pgDKL8nn5bTxgaGZYE8TacIa6oTRfCqZhpi_BTfaenf5k04Lyqod7CrzFn6kpKVyIJ
vEJOoN52YWkyc3NFblWUpY_nnZi
}

EntityColoring(mozilla)
!define mozilla(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, mozilla, mozilla)
!define mozilla(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, mozilla, mozilla)
!define mozillaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, mozilla, mozilla)
!define mozillaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, mozilla, mozilla)
