sprite $mparticle_icon [64x54/16z] {
TTK73Xqt48DXgcpLIhp_QHDxW47HxqVqW1_sZMAR4dDTOjehfZn2wl0jvFOKSappuylqVPg-lhRtucV3byUcFvTjenWUHVWs7DdEeQ_3fh_jpSSvzDSoVP-6
FvVXupdWuyhDjoocHz6J7qfVRfl-cARFvyZaEV3n7F3NykRZLzAVo_JzGpMAy9L5p_AOoIB-8_qoiypC_fZ5wp3pLYDt4VsewlpG8U6dDmb-dHBzKoIn61v5
-Az7TJj7zBDByEkI8jivz7SH_QY2VuheHvDs7rTcjdFIinW-FmH_IVHl5Nm-HoRFWO_dWCS_hVahuPyY-gzfInJXupdW-I4fYl2tHFzMCJ_tYrnCVOIqpxSu
T9wIE24etZRzaVk52M6HlWwR_ixzueJSM5Ju_ATmEuS-bY4z9uIBc5xv7FJ7CdmKqsDHqsD2i8ZXiQZfCI4OklIOaCcX31z5-7WE-79ZV-8S-dkP_fYenZdm
dKNF-ff1yVUe_TelJiXZ5izkvYaiNXBzMnKU4yAXKtWC7VqjIIpItqNmkGmOkl1OrFIO42nYU0vT-dqPM0pFOdXE28OkVJu7_OtzYdFedoBwht6_tY9uJ4ZV
hupaEV2NHCy9YNFeHnNzF8HyJSpzxm4gOlu7
}

EntityColoring(mparticle_icon)
!define mparticle_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, mparticle_icon, mparticle_icon)
!define mparticle_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, mparticle_icon, mparticle_icon)
!define mparticle_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, mparticle_icon, mparticle_icon)
!define mparticle_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, mparticle_icon, mparticle_icon)
