sprite $mparticle [64x14/16z] {
bP55WW0X4CGA1jgR-lzhrzqt8sXE0G0L09S367xXlyoa0ie6LlFVlXvIho9hEFbdVyhZM2Jv-3iapyGFo8RsU9poSRmNho2FB98ny1ETs8uFlWB1d5ZiZNiY
gZNRe5cjW7NbNfKUfE_4pCuf77TZpBm0c01OFe1xcjRquEKqvnQwKpTho-bj7DrQ8fnTKlNIRyLplmueCRcyWSvAuEZc02fWPtC146vsDe4hgHZ61dRpqRSN
_qJMYz_t_kB6W73HbsmeILrDrep7VkVHvtPcyzgieWedq0dZIEPHkHjF7FlGhmUW6yimRFhnMC0EitNPomaq5DVZE4ZcTFBiHTBVzOl6h_084FVX5slX7Lxu
bPpl-hrdu5Tk0G
}

EntityColoring(mparticle)
!define mparticle(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, mparticle, mparticle)
!define mparticle(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, mparticle, mparticle)
!define mparticleParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, mparticle, mparticle)
!define mparticleParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, mparticle, mparticle)
