sprite $mysql [64x44/16z] {
fP85TiKm30HNPC7z3rn7IUDNRlmdj8KnIVWNdg7OXuCidGcx18D6P0x25XBdnrEmnJ102P0Ss280DG0KZXrSqEmE8BT5QTWW21USlE5ht774QmkWdIfIhEo-
iNvRcPFm55CiVEpuOhYGf8trH-AT67W8Ep9qdO0Bdk4ZUTM0r9qU5d101nOIWgSeOq6kU0eJBcH4164Noc322sWQNa8o22-XJl08GJEkj20rC-NEOXEXrkug
a59LUUSZsKVziEVJZfqG0BFs6vvMTjAPnWT_sZtCgTCvu2TVQjBBzdibQtfUaNesC_xeQqMqHXLU0SvauFWGp0GdOeR6J3xwLgwLFP3P4R8tqRypCrvQewOV
_L63UWDUtDAex5_xTNxqoRUFljT0p8UcfbK4gM8WoixwjRby-UeRh79gurBpK7Ec0pv6e9_zdeYdvoMNFoh0bS1jw2_xZtCsp-nUaAueMJcQLkpGVZZ_B0L6
bxxz_fNuyTkrWEEXrGTVVAasgLhpOpK4u5tHVjtB_-2VIbRIxNSZdwQ8M4zvVCxSlka4F6cbozs-dP_Ygrll3X0xuVOR48aIuO08wztJDpJ11J6JdFkW1Zym
AWa_G2hu5VMeP6nZLVv4VmC
}

EntityColoring(mysql)
!define mysql(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, mysql, mysql)
!define mysql(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, mysql, mysql)
!define mysqlParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, mysql, mysql)
!define mysqlParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, mysql, mysql)
