sprite $namecheap [64x36/16z] {
bPLNUiCm3COueFiVkRkHzGKPnAj_4-XCd1Jh1XKFAR3dpRf2XjDy3o7rzGsnaHru_AP3oDkEupdhdfJtsKDCxm6-ixCUu3ivwm6-GyvgWEz0pdg0wylr1tCz
4g2xzBDT3mCuU7YM1m75bTHVFJf20YRwy837Uawz1hZUpth0O_tcMoy18xq4JFGMCD5hm41l0Gpq7f03lGIiWLu3ra2l0MkWru2f_d70nU1w3v2Tw1y7oAUU
wJt0FvLBzHwW7xgktw3wJV97XPAiW_jT0tJ68rhiDpu1
}

EntityColoring(namecheap)
!define namecheap(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, namecheap, namecheap)
!define namecheap(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, namecheap, namecheap)
!define namecheapParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, namecheap, namecheap)
!define namecheapParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, namecheap, namecheap)
