sprite $nats_icon [62x64/16z] {
xTL9RWGn28NXPmEUxd_VJ2Z69L694EfUrR-puLlJ_sdysOlqen_TVtAry4vStKLhZcuu8aytQDnzRTMKHcqPZT8oMdbS6uzh8lCIruqF7jQzEpoW7HxHNOnp
Zsc71tLl1RZ-77gtVflGU6cZRbxb9uP6ilEqDesNk5wJZ7D8QoUFwya73scDiEEuRjKunRKGhBWMIccXb1PAQU6CDdwlXN_gdXQk5ZlQhudJ-_MZ7rrletdH
N9nmNnaNZK3ACnheAGrAQL1AewOqQagZ9BHTxmndP3WZ4QSq24wV
}

EntityColoring(nats_icon)
!define nats_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, nats_icon, nats_icon)
!define nats_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, nats_icon, nats_icon)
!define nats_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, nats_icon, nats_icon)
!define nats_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, nats_icon, nats_icon)
