sprite $nats [64x16/16z] {
hT87egGm38DXsL8YsFiVU4amxVNspz3vw7uMpSija_yUBMZF_i3tRhkcvMrVVZqxlKRb2SGctK2NTm9o-HLdthq2CvOFHBzx2mbqr_d7sG1jBRiF9CcCB2yY
UZ-zEy8DKNwMMA_x1pAJL2lVJCJD1vgTeEz-kRm2ioYlUHCiRw9gVjjJuvOOqEa7AjyG6X6uVDoy0CGMTgzizfYafcTspvJjzChR_JC3GAJU_dwyxDdV_lxw
vXzzwZKRQiw2UfJP7mbyXZtPWT_4dlXL_9d_3m
}

EntityColoring(nats)
!define nats(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, nats, nats)
!define nats(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, nats, nats)
!define natsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, nats, nats)
!define natsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, nats, nats)
