sprite $neat [64x64/16z] {
fT8vakDG30HHReM_wFxt7HZbJ7Td10J2VocHhFjuTTBpYc_5Yq3iZo9qDldOd_GEz7ZwPk2SoUr3rzTy9RPl12vp-mZTt_3Rt1u2pFVdbuye1nxp7xww99dR
Ou0v-58WagCFdONHWOS0Sdi8y6RPUuhCZT0xW9i5NmfS-rFqeHisM_GHDsoswkD1pfu38iu-19j5ZqiQvkWvODxm3dYpFH-wpWMmv2FCctxCjPlUF0CzRvwt
UzuyRxNyi7Q0V85dO7_hP_9AGCnB0I6l1KIy613mQa3msQi10Qy611nkWmSE0VHZ4QSjYpRB0VGJERz50Qy61BmQ4F1gGC2h0G6l1WIhgGO4l1fGbtlBIjw-
bTwRRGPsc7S3CT_TyqglSSxrwkUFknr86CUHWJRNSVm3
}

EntityColoring(neat)
!define neat(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, neat, neat)
!define neat(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, neat, neat)
!define neatParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, neat, neat)
!define neatParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, neat, neat)
