sprite $netbeans [60x64/16z] {
dPK5akKm34G55hJkV-2jnCdVW3pK1GFnirYcLfhA7cugJB-Ji64eggg0z24_9ZaG94GZWDe5X8sVU610C4rRekQHE3m0N9dMaaGgaI8kZeZQvuRSix0mQljn
u1MAMFuFmeduzdK0SLm9TDwn3FC4KA2ukCQ6tTsfBA6bM0RJnXyQA1Xz5ANVbj7ENYZOrSl0-BgCuuXN0l1xV5vVi0euAMGx1_WpEYzR6dLW45aPAMjJyJMh
gEHvmk5jeSiNHWjsHfKmoHZoOgEVhuBIoR8I1mhfjwACohRjAlYHJR545MBmnq21txrUi5j6F7asP4nS3hRaRJILRcpE3lgFfyd6GbwHEjELzGyxSTrnkDrP
3imatTbuTf0wQfFBrTrAeHSxkw33WObpLbKoFTbOT11Fsv1X73Np-sIJHjzOKSCIyAgmDA6MrOgMdRbIpCyT2r9a-scov25hbe5-w-bHDLgooxKsJlk-OfCe
9xjG57gditn6riY2v_Kr5gmH6TgF0AlhP9TsjLiHh2Aa0B9ArwmqHLBiWOYZgkmh5jm_IniTLGNZ1KjuUCLHq7jZmxbXttjSSPitLCo5f1shiFjgySTGp9b4
ZZixThVyUlHHifXNQU0UU9RUMSvsFsoQISUulxAC-F-GHhSV3h5TR0Eyi_bvfAnfwBnE2AhcAZh6Rx8wL-6QdHf7qcsQoToCJdyR5kybN-3piv7aJ4FBFgza
0qRu_9q8bUlTmisesFblimYcNjOFlsIUKyEqqkY6q3xn2P9L5gpYnN9U5g-m0B2MvHUhA7--aONn4tRWVMvaLUeRHiazxnDjYXxoOY7jNdWNlV2ayy9AphMv
fk-UPtrOnTnyIsaKGXjsnaHVI_FgUPm-UrKs3ZTPWvy8v2oYqq_4Za8S46_M-r1xIU28MpQqbbRNz1nDguBHhwI1SXf2ENVABsdd0R0e_KcZ8FHNHLAlVm
}

EntityColoring(netbeans)
!define netbeans(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, netbeans, netbeans)
!define netbeans(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, netbeans, netbeans)
!define netbeansParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, netbeans, netbeans)
!define netbeansParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, netbeans, netbeans)
