sprite $netflix_icon [64x64/16z] {
xTGtZiH044FHN2fMt_-qwsGfHh-JTSDet1lW0mMD7xRNNbDjqwnVrcszlQT_r-i-SR-1TT-ar-5xpWyBC4y3tFC0ypoWqlC0ST_tW0vF0zpp0FFyXjiz3s2-
jnEm0EGL0SnN143VpniMynd0VCK9G9y1p2kU8iX70FPw1ZJpUGBGjmLmhtYAC9y1p6T08vytF9Zt0Exz12PyMG3s6S2ztp3t7i2zdG3t6S3zy03kFO3xfW6R
bpGiOAankUwML3L-s5vxxHq
}

EntityColoring(netflix_icon)
!define netflix_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, netflix_icon, netflix_icon)
!define netflix_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, netflix_icon, netflix_icon)
!define netflix_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, netflix_icon, netflix_icon)
!define netflix_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, netflix_icon, netflix_icon)
