sprite $netflix [64x17/16z] {
dTC5WiKW30JG14iczp_mClbrMPilnLuDY70HSVwFo41QhAMwb8f6c6Jwh7744544sFcZnzNBb5diCN-xTpCRKioGPNescPvzZcqyYUPbLW-L9ID7qRUiNtsP
zNo8cAb_zrC4MA8V__2Dq2GzzF3yu-BXxdhtYhpnzD4Mp_ZPPnvyNateVUBL0twxlfczU4jlVRaipQ-Vd_UFahxG__7zyP0hXz9_vSV9WnuVtrSVjTRMNZn6
RqqNpxN3yUaLYy_WnJEeY_VvN_XCAVtcErpftUl70mXilYuCceM6_1-zjrgBF4PdIb4fVQWCe2xx3tmli_rlKG8ru0i
}

EntityColoring(netflix)
!define netflix(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, netflix, netflix)
!define netflix(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, netflix, netflix)
!define netflixParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, netflix, netflix)
!define netflixParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, netflix, netflix)
