sprite $netlify [64x64/16z] {
fPG9pkim489XPl3zR_msjwZeZ_AI56sLrO_CWerJzLg3vvhrH-8Nk0sUuiyDPbbwXblp7IvW-1nVXLxYOtn03_41BkVW4RuAvJK-m0UubmCcJyoj711WoqYZ
rXr-rXI0aWajQr2yqBjwjp5LZ6aqHhmqEkUDkGejyM9eQv_bB1LRE5-Sdo0By1fFyHnsooTq3ivmLmkW2a3DU_nkBUH1XGfWhwKcmDxZ3_hy-mFgSnlTG6d_
b8Y41r3oSQ12vZiDna6DHyCou9fiuD8Pm7WWkKxKJuCvY7e6LuqjkW4R-8yDnhNBvaiDzdkMie5nTv2r6DZhizri0-EcNBqBv_Zs-FIL3RPfT-3gyobOnDfo
LINfnz9SHxlJhPTvJeNLsS4i4HE5RmcrKcg-jbAjpoqp2zyQJpSFk_Wo6McSqaxQuq_L3kHqdRtXCVuyWnCjcxZq47680uorsg8dJS13t0OgM1v9VtZN0Mw3
dT9t1LfBysao_apWrlk90ggwKFvg4LOdVZ3nJOh-QvhKw0Zt30OyU0hoiM6FF2ka0J5naTAWDBrzQBimQ5HSf31uZyycHr8y1SVfZ-9JdU-dbUa_n3E9NeL5
AF3_6WYOv8rVCnWWt8nVCyWE11g_R42CYq4PlsQG7JJ6-3M3Z651r_2C4T4Ul_4R1euXeC8DAJiGMBWbHGU3sz9d1ut71WCk4SyD2bN0SmF1UcR0hmnqZly6
}

EntityColoring(netlify)
!define netlify(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, netlify, netlify)
!define netlify(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, netlify, netlify)
!define netlifyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, netlify, netlify)
!define netlifyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, netlify, netlify)
