sprite $new_relic [64x52/16z] {
bPO7biKW24MfGena_ykTapAVcEYKztkvyCGJ1EP2rcBckwme4_n3ACNTbxlSY-0VOKkqazll8QZudJXr-qBnH_gMsekA23EBQCdlNUREYzzWxYJw-SreZ4lc
Bi9lgVza0Ur3c_1Ot_vSNpZValCX8aGYxlInMERUTMVnPemu9JOCe1rEq0lf7S1rcXtX9Hm4u15Uc62eTmryK3fBV1v0lwrUtX9twV1PW7Bz-rneMMxkzy-E
GFuEXAyLwCEz7wMhcuC4mqkK1cuLy5jwWeCFv61WAm1A80AeXzMd0MS0ML821xysvo1kQrHi1gs1DUmDs0bebzxevAj52QuDDBXMYltvKKAz2E0RhtZbnrX3
MhG8AStMrLl92dGLXDBPltZmRUFMc1afcbaBoYte5e2UkFE7fzZ8GwW0j8rbQt3fkGCyu9SAu8rWQQqYU4Di3Z0kW2RUjoNS7vWV9hmD-HGXvBS3tjzyMTVL
u1I7S9J_yRxvilc7H-S9V-79yya7mDe0VT6T1sCWhpha-xFccqUA2clpK0gX46pjQXRuuBddyVGViPA4Ogidhy7ZAz3HbfkKplnBADZMMbG-U0jyjP03BA1t
ll3b_xXq116J7tKG9-0xxqm73noEKSMKmYY4mzMj8b2_V3jxNqgFzbK1h2AlRHNmbIj3QStBWjZRTyxcD-c-qnR-EO7w7H36EKx9b-o-rXjW_0CkUOQdWTVf
DSNPhjxzDk32J7CyYs_vYpzMCB20pnd0S73uvl10EACJJsdIj-a3yM2HU8RF0ymbFXf-jA-1J77rRlYQrC1rajocmn_PSfVfW2wPV6OXvKKwMCr_6NvH7n6i
g8h8DVuc_Q_9tTrFEmn_4Qcvlq8KHlYpa7DSTpFzYVq2
}

EntityColoring(new_relic)
!define new_relic(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, new_relic, new_relic)
!define new_relic(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, new_relic, new_relic)
!define new_relicParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, new_relic, new_relic)
!define new_relicParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, new_relic, new_relic)
