sprite $nextjs [64x39/16z] {
jTG5SkWm34NH9mlCzlvN-p7KXjhHz0o5RjZ6DmMu18872LpCcGTugCA34poe43oomYDcN6aPHwNjM2istAYqWtNNd8g3aMH3w1chBc3vgpRvP-rJ9-owue3d
UbZ9MEI2eycftlQ8W_2NTTpriZPNFMe5W33ueUT1jpqD0z0I7dgaSjj3Pq1gUEpHTEi5d-IcarzwxhJsDQyC_xKPyT8ZbQrFAyL_TTfhZwPtzvzw7E6rvqxN
xuydexJN7h5SzjGJG2EzzcXwqI-NbYaNlOhblEq9ZSwzBO-U1frxiwA7CyTywiDOLrkvwaEiUu-gs_i_LM7Onrub5qcszkiJZ9RB8dFgsDZafQ_uAo0mI48a
R2p3qavYmCwM2uawfiWVdgB12Jucy8a45pBuCCD723uC7o9ytMy
}

EntityColoring(nextjs)
!define nextjs(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, nextjs, nextjs)
!define nextjs(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, nextjs, nextjs)
!define nextjsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, nextjs, nextjs)
!define nextjsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, nextjs, nextjs)
