sprite $nginx [56x64/16z] {
dPO7hiCm34FZ5Okw_tt_3l4R8uHPOdMzmdm68XsF6S1P3ZSja9de7bKdyYU8ja-L4ybWrasiumTZCCfciLk0RXoHsQWvGEmMTISzaC_14EvL44qK4-6To6Aw
9jrl1kYYs4RDCXoADKiW_Q3DV2jtZVZ9-Yjet-ZbA6rY_RIgFcZNRRvYF_u45zVLdFZF5NxsvFUuCh7yszZXIdWSK-5nJ8FDyNScHwacLoZLuyvsION5JHHA
zRYWL8jBd9HgSOb1gHQNw9HgSObAgHQNSKaDZwFKwd59gHv7gIP7gIP7gJP7gJw7sE5YuIXLSOcoFc4fDTHeAr_Ol8_ORpdbzl2_lSDSXoWGwwSX1fJu51Nv
HZ0utVq9tm8MXU5jBznWbct9tvZsQYAwiGsIUbXyou1nH75OO-FbdTWRTWUaUxsQwsAwfYwcQmBZi38WY-d3YYD-0W
}

EntityColoring(nginx)
!define nginx(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, nginx, nginx)
!define nginx(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, nginx, nginx)
!define nginxParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, nginx, nginx)
!define nginxParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, nginx, nginx)
