sprite $nim_lang [64x18/16z] {
bS-5eOKm50JHsRsu9FrN-mMNfmUNWOG3czUQWaTaG7A49S3YeJu_xkE6XwfQtCdttdpAZeSi9lh7GW3Q0Up5l-iK8arw0mmfm6FQZAtmrEew7pCfycmKCEO2
d8ywkCzM4S7QZn5HfbmT-YAYcFPDpe2vCLi_07Ivtli4A6U1KWRnW5xrElTQ6-sdN_LQQblQyq_xgPJbVvfyszloIhA_wv5y8l5LZwHZBHxtQUxphGT93sfm
6W6gjW2Qrg2s0TGq0kN4Ij9UxwBZENN-1G
}

EntityColoring(nim_lang)
!define nim_lang(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, nim_lang, nim_lang)
!define nim_lang(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, nim_lang, nim_lang)
!define nim_langParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, nim_lang, nim_lang)
!define nim_langParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, nim_lang, nim_lang)
