sprite $nodewebkit [56x64/16z] {
dTRHibiX28LXHRSY-FxFMplUbU6VcdN_pG4yILP9KqLgIOAgz_OiZrfxhq-UP9KsVV-DTf674STHDpx3iAdwrZKt5ePD5jFzJrON-P_5GboR22zc0LqvH2hU
FeRN56dg6tBV92usMCKtkRStDZTsrqnkJrdzoEJs6DSxR79xagD9gQBxEQk9VFk7397nYvlFplqNvsQ9OxKicPFLyjVzt8uotz6nMYS6zmJbEpf6WGMNgNLL
TApCTtIWB67WRAgPMfoHdSeq7Rui_35qezJfNpykC73UIob3tLTGv9QKapfKBOhSpLfkli30UR-eXkzyT2PN3GDrNPnHfeE9phzoqZGeTjQIjTXfJTPYDvAr
s5bFrcAt1gm5plPRvk-_AytUcJKfqlILQPSAjOMA3DKaBavS3RYemR1G3A7wGEc1gWKb2wiTbpfUaqiaLrSVZLHy4ox9NCsvbCStWTlpcWwtnpN7W1412etu
1m
}

EntityColoring(nodewebkit)
!define nodewebkit(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, nodewebkit, nodewebkit)
!define nodewebkit(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, nodewebkit, nodewebkit)
!define nodewebkitParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, nodewebkit, nodewebkit)
!define nodewebkitParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, nodewebkit, nodewebkit)
