sprite $nodeos [60x64/16z] {
xPVNcYKX28G5nDJQx_-s6tkRAJuxtcoQkfhqZrIfu0adejeul5FgwpeolI3ZilvGrwSartNN8az8ocFzg7hVjlOLTD-sBCY1xIkZgFksmIZeqhQwGbtvvOB5
WBI_OYlZTjrd5y7qxhCZmV7iJzWUGFMFPJzPujTip5df5IkvV5EE3zb50gUoAKlWUelTselcOaeKPBd3ZamXveBI4BHVifK30xaNJcNKCrPYe5IcIXn4Jz0j
tRboF2UJ1JohEh47e3yKigNTecbOFt6IjhSRzMYYNtEnJogdOctE1vOvSDj_tTWRXNa06vN5pyL2EATHTa2oJkQYsUQseknWcb6d9VuqEWxd7ilnN6oCHfk0
iKe1lvUociRsZSKFwoX37RQHJYF3tFViKF-WcEUktLX8PphVkqmFYXBOvUd6r82IZRLTWDTEEcFZnbewu3gE6wpPnvdEzPebjNJGjYnNB8ybsZfeM_i52-lu
Hzu52-k0xJliT-N9wxRonhPhTc9xSYIjF6L8ntK9tmem5cLC1xiJNa6i2-z24-kcc_3gksCG_LsWiduGjfoA--3JgR0IJreTECHqu3hZh-SVBdIS98lXuUj-
saeBkLz3FIZqrMG-oh2UoUZ0OOPFx87ruCZ2VupAu-n345MNmrS
}

EntityColoring(nodeos)
!define nodeos(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, nodeos, nodeos)
!define nodeos(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, nodeos, nodeos)
!define nodeosParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, nodeos, nodeos)
!define nodeosParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, nodeos, nodeos)
