sprite $nodemon [56x64/16z] {
xPU5hiCm34NNEkR__zw7aPoY5pyGxGYAPydjwEPnoOe8ZsdMXX-qTSvQ6dRQCg411WrICu9jWRaf1ddC1V187XFm4aYU_JLh7YoPR1OiDrTyZWR7O9H95377
OCA9ffl90dRKxZrnwdkmZ4_Hd6-7CuyaNUkU4GQi9gEd7ju6SzSXZ7zWFCpondFjbyGxSUBIwoCG8fi7GeZyVUt4Yp7Cp3UOMj_1KzWJ5C-nnECBJzBXIXCL
_DryvXbKzFWlnpDXBNX2YCWsvSN7cMJAqpWhCvx4MVu7x-MzF9hmZ33GfptPNcSxyTh1q-EhYXsyfMqzOpo1j7j3yO8MdWbUm3Pui8ozG2FOkMaKlM3i8NTM
N5yhlGUXsBDAlMwjzSXQRotsv68lhwy3wkkE-ZgdlgxAWTjWxm
}

EntityColoring(nodemon)
!define nodemon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, nodemon, nodemon)
!define nodemon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, nodemon, nodemon)
!define nodemonParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, nodemon, nodemon)
!define nodemonParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, nodemon, nodemon)
