sprite $nodejs [64x39/16z] {
xTHNSkCm48JXdjX8zp_lGZ8BWBDDl-wl73x6AUB7UJFy9H-Zw9_yJF_e_R__A95V-rDaxu4pPmYEX3tZzDPwxi4QisEwZ2nCEvS_PjjhUGh7pEgukgPBS_9I
c65x-QUN75TLmN6K0EAXdpup191h-Sjx7pkEimx8Gwy5E93ZZQ_ZNSskOt3waidbYzTNleUtpJ5hxpot3m1v-AuMpnqhOrOngyllFLXU0VZXcv36KGtlFNCj
u0iVL0_W0vyV-AgmjlmwrwTlsoVV-5bxU_nJba_C-E8HsvC6-3Wph8dfyUAhuPcrqJ6pQm5awlNzCM_dF3O5gcCL1O_4foTfw_i-rhoVNnJ1nscGBiytXfbm
Z9xO2TTsVvm-j0GzKp7J5E1ClzBdHS0UppUopCiv7RzEQNjlCtxl4v20ascmlEMLHe7njazbcEfjJwXdfjprwGw0TjTJcP69Evu29SHCWGZykg17NfkIWj-d
4Gf0WeQRUQhJ1RTpfkBB_W4
}

EntityColoring(nodejs)
!define nodejs(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, nodejs, nodejs)
!define nodejs(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, nodejs, nodejs)
!define nodejsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, nodejs, nodejs)
!define nodejsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, nodejs, nodejs)
