sprite $nodejs_icon [57x64/16z] {
bPQDaiCW28GB0klxF_7LIfbZKWFP-stDDtLn6NaT9PXGUZtL0EPRa6SO6-OMCFeOwSRyjt6JaoympFzJQflpBGOgNNEGoyUtp2bTtpEwCOTVrU32AXjEzHzf
AOlkoo27eo79kwdjvoCmRXMyCbTOZJr8DrH-D7OmLrWbmS5SOTK-t7ZOgejCN5EC4kGXkYHC5KZs5aLslpq661_1U1Ey__Dr5xG7nYe0Hwq5ObEg8geU6Ir1
hpau7poe1jMvaFgJ5MXh8OLjFQrDCENN05XlgpD5c7WmDOip0LD_t5M1Uw-RNOhGrI2PBmUlt02NXbr2LuDRB6fOIcG9keXug6qON894kPQqCoWLA77QkPPQ
WRg3azG21Udz9Mg1dBegjqSTyed82ms3zqi1-Y80Uml0xFMZfpmBqaeE6p8MpvN9OJM4T3Ix8xftYUaI1IGoWIVnf-BgTtW6wniIb6U27HcgxsJ-TZeWaIjG
EUZn_u4AAdiRLiqTIlbYX_yPHtEf89V3jcAAFGpJq5jpyiE1663AXRc-ihaY6ah9N6jY8p541psOoYCGneMvS-6Lixb-DKfpv_g7kRx6sLoztrjpVm
}

EntityColoring(nodejs_icon)
!define nodejs_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, nodejs_icon, nodejs_icon)
!define nodejs_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, nodejs_icon, nodejs_icon)
!define nodejs_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, nodejs_icon, nodejs_icon)
!define nodejs_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, nodejs_icon, nodejs_icon)
