sprite $npm [64x21/16z] {
xSi35WH1303H2fhtF_2EiRRheP7ykbK0s_vJYFLed--3cUKjRqrRFZTVeJbBS_hI6v2sF4rRFW7QUa2kzFOS__V1FLpdvzxTvo45GdFwuBTcORW6G9ipjJut
mNQpvue-pMy
}

EntityColoring(npm)
!define npm(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, npm, npm)
!define npm(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, npm, npm)
!define npmParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, npm, npm)
!define npmParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, npm, npm)
