sprite $nuclide [53x64/16z] {
bTO7ZkCm38LXgokIxt_U5PtV2x-H1yGyb3H-e2gSmqigXoJMmqsSMXH6y_lCiwgPXZopa1X3dbb83CWn88mXru0mvmEbqbPg3hin90OKs-TEBt4p80me0aXB
Qa2O6tMhp36cqcYNCK-40ULLLkvHvqQtPGH53AYj6ZbP5ni0a9adMXLP5errcG-44HGFJHsc1cp686P7hDkacPbavs17IKoULlfjXjbGPqvYLhvgH8oYjLhr
nPmCCMCKfRMRQWX3L00AJ4eCgfaQByXsjxwR60TgGtQEmcRO7zI6GgVLRgm49MYbMgjt8qgGBKNzrPmeGRIgvpC38qgGjHglXg0K7UM72HXH6tACdetsQk9j
L8qdKZEZc4s1fgAZJOsgSyGN5FeBOJ4m7b8r9iP3keGO1udoqPw5sX_HEUfIsKLgejtoxYCrrsEfE4WDjwW71wdXmXO7gR6KrSf3QcYL7AI6MJKVgRaMCBX8
3OyP1ubXAUfFz3aKOMHyVI4n0VHkM3z3Ofxed5a0arAqFe4mjlyECWF2hFJq6y8e6gb-B2tgGe0mYcmDKl-o94UYWp0WZ2Lt-ISOh7cvqTA2CB3BjLhRzUO0
OK2OEwbz6JY2C20rbbZ-kyhDDIC88manhoGZXim8CkDaBYDe-2Oi8sc--GS
}

EntityColoring(nuclide)
!define nuclide(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, nuclide, nuclide)
!define nuclide(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, nuclide, nuclide)
!define nuclideParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, nuclide, nuclide)
!define nuclideParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, nuclide, nuclide)
