sprite $nx [64x40/16z] {
fPK7qkCm24P1W3htl-wkDOd0Q8ldzvkIfeS2mvVeXi61Kpzq-2VcZvU-vfV-n7U-rfU-qak_l_HjXEbd_iHtljPNleqGynT-viVhQl_G43QKhxTROJG_8h1W
_LBWWtIRKqd13oDCN4DBDEx7ilFF4QP1zmdcgO66V_OdNVwiuhUYw4b7yprz-SfjLqoYVw9vVrh3idpNmPZwHuhtSUpZUFbQycdqMagTsqdE1xAworVgmHv2
p4pKh0Fp4QhLnSll5FgzR1OHQlkWzosqBQsdkNXz4ANVO1BXxydYVH3hO1sOjwMHT77L49PFWNxpeUzNkcZi5nDnHIib5APiglaqOnggMmk3vAfm-EUUJQlO
m86OXFhfumXX47LRSGEndJxmSNqCif7QaEX3Y-qR117CXv-c2Or3i29T3nzSIGhJo477dayVjcJhPtc9dFxEKIUDz2V-DqSKjl52dlWhHpx-tEpK0nzafMs6
duD5_QiFZkxl7BTayXEVPWs6g_R0XqpX6oVhveaFDSub-_y7unS
}

EntityColoring(nx)
!define nx(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, nx, nx)
!define nx(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, nx, nx)
!define nxParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, nx, nx)
!define nxParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, nx, nx)
