sprite $opencv [52x64/16z] {
fPG9UYmX28GB51TKkFzjPx5ZZ_CoIxxtPws4KYpinc-GbAfQSoHy2MTj1rNm5QBjWShuJ6ex6hwtV6yAslwX4jvIsoyal2EkXh98qHz1U4Dfaq9Ren6l8TrE
i4mPhs5Twsxxri-fAUD0faS_Hw3qyW-lzmbF4zOlCiXFkdmnKfLfATyCDQqxjYd6DmFQeY_VN6iDcsAyfsmPr4-dMMNxV38-GgK95aKJla5mmX5l8SAVe23f
YaJ-sX7JGWWR4IU1pwRJ0u97M4V0elUuMmveitIpjbGs6_ABPSk9cbqHJ7XSnRWNoEjjYjteD5LTAcoMW0V2i3jbKnauovcU9bXjCXXNr2QTU8juW_fXINEV
Gvh4_HolMmFYeQjiSMt8wkoWsPqcszatyj7_KupMTyyPFN_s20ueJVZiBJpt5bVDP6LoPb0naKENfwp3ZtpCEc-ncPnN9pA79SBi_w2bA7MicQwLTsXToicm
HLf1xOGjg8ssajg9UrAJBKLEJyZs06sCzQ3AoyUEwh07Ui0Yf8KmDgIVcnJQtrLHNhshOcrZZAw9yHU82FyBSGZylYA4G03FAcOKyoj3y0fkViKgcz5DcecR
bjBygb_GlPUYxg6x0CZUgvVvZm06pIRv_eCO702QopUNx7glJEe9LzHZicRcTSv-1FIhzi7iXYj1RhyHs8sRo_H8yX7ZSCvUWhYYUut5AzauknGaRtZqPA1u
LCyYDj3lgogPuQ2uedb2Etkx_PPTr4VlhQBxeqTK47m4SyQHmN3-sQTw04H-F1Wt3VLygwhUWUZULOSF9BUKxEPLoTuFJuEwDUtk4IZkDoloC7Th4SdRC2iW
dPU-3G8F1UkjO1G0ORrLYPa094-u_mAw_w3xjrNmorsTdc_vk-S2
}

EntityColoring(opencv)
!define opencv(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, opencv, opencv)
!define opencv(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, opencv, opencv)
!define opencvParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, opencv, opencv)
!define opencvParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, opencv, opencv)
