sprite $openai_icon [63x64/16z] {
bLTd0hKW39Ezo_rF-mqbhrNWZVnK0cb9QptMiB6stgbbhuzVeKBhBr2nlx4To43-HK7k4yXzBRn0Smm-fDelXF-llg1Vwvl7MfCkVgcDMYl1VA4yoaUcTeaM
zYhSkU8UgIxzZkPsWRU9hLAVaTRqC2dtD1WrUUzZeP699RtzboQzDyAcg276jmrVXpD8pm_ooZOghVIRiPOKbaN8VfhMdu_jCa5GDKJs1ZLFVXEwsUNnVjTn
USdf5gMX_a8unT0pQ1KIrE9znTbqoRODUzfdqAvXCt73HjYS_l5kTEAW3She5OfczV5yOuuxlIcGTNhu5KTcbcwE9ntiSBvFsADSaXE2Zz2nfBiA3YBeIO_W
cqpYJ0S5Yj74A33TeSOcEhn4bc-FOCHu7de5GSTChoWsU0Tbm2X8uO9EPz3LPTmg5w4qAC5f3_fWOJqiX6f0qN3U1Tt195ZFdXErwBPqBCTwajkXeaXln3lS
9H3PS-9hK2vA_aWFBy-1No_v6PN_wVJaB_SgKJJrwXoMww2Q7NtOYBo8nohY3cLfUDgkw30nQMuPwKZiMkmVF0Saw90yuYzds0Pt83e3FUbXfbzXZxvNrQql
VN7wTIu-RCq8ao35WASz_J2qh2iAeafsTEHmLLVLOQyz7VMrhAjYhaRQjgbZHpxhYl2mw5NcuTTqLWE-nI855PAcp2FaFEW57PdhIYSaSAP3inKzMybUhWAk
Rqtd3XtX4j7BaRcjwtYKy68gS6qvGQKx7LRb2tIobtFGB4hILUxY2b2pCcNfsHcPRiSNm4FQs0gmEPjfD7CleOH10kBsevgjufi0W-9i86C1i1lD0iZLo6Ka
rKosvL8ewt4hTFO85yrKYFha9hiUjJ36OowOzaIEPs2epDvPvrDZ_p8ClB90x3EQcyTr--KF5FjEVfVALxzlw9uCsqH7t_yyKgSnMaZdceIHu1Eqrkhmi4Tq
rhfOEvpx9ImjChazUszOHbR7Bx15aeizVeM9zOo1IjXa_2y
}

EntityColoring(openai_icon)
!define openai_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, openai_icon, openai_icon)
!define openai_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, openai_icon, openai_icon)
!define openai_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, openai_icon, openai_icon)
!define openai_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, openai_icon, openai_icon)
