sprite $opencollective [64x64/16z] {
pPTNbWCn20JfeFiVUOCJnab26-jtNa73v7W68Fc014GFoADWiI6FXmXBjZsUO7DkZvVuTGPvJB0QpNiHE9RGCzrD_Vztzu6YBszUnEKevPTwU7gMwHiTaMXb
IgdK8vwbDs8AgIpW--PpNMJPVLVN9O3tT8dtxRsgPm3tLtVWl85cUXpq783Dz77jeyPdH2i06L7RTmC4UjFN1OhWI13H7a0bVdy0x_Xyw6l3rzZmyJC-_wB_
b_PNVV-Qdper4cpux2yGJ1rVl7yHhWEq7s3g1c1z_c1SmMPxt3w_s_4ZkFq0vy4Fxqv0vDk_No1VmEuNoFQvWUOEc8syyeKgrWAC2vX_wjDrCX3bwCjFVT1t
gwaTDEwnU41UsAt6X5a1JyoVJo1_iG3x_oyLkAzNEBCPINyBYgHTmMh-FbSPqG6Kq-LJ-Hq
}

EntityColoring(opencollective)
!define opencollective(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, opencollective, opencollective)
!define opencollective(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, opencollective, opencollective)
!define opencollectiveParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, opencollective, opencollective)
!define opencollectiveParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, opencollective, opencollective)
