sprite $opencart [64x13/16z] {
fP5NOiKW30ItIEB-DmwBIVz96GD3MxrY_1hYpx0IBlsrXDkFGcqii4g0vGYwgoFTqN8kc3Kb12gufZafnGw6UwQbZhZLTnpDT5S6VAJLRPtZfDZDtTs5QkV8
xDGRpvZP93uW8WLz4YSIjWnb0O3dP1H1BNo0nETylesjNFkSx-_vIqz-bkQ8CvMlFSRkEMhsLCtof5WEWdtVvTPipBMs16LLJrxdYDbQIv_oC-StuI0pLIA0
ZdAIVXQqA8Yucr6SVaaU_s8AV-C5
}

EntityColoring(opencart)
!define opencart(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, opencart, opencart)
!define opencart(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, opencart, opencart)
!define opencartParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, opencart, opencart)
!define opencartParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, opencart, opencart)
