sprite $openstack [64x12/16z] {
dP85eXun20O_23hl_kUjPF-wTrQYECrdMlz6k2I-mluaqFeQyf7V-SXBtjmaaxaaVPdVNs7FvFcJCfjfNMh6f0E466Xf8BKBfOGrtl04_2wTC3hYw78Y9AEj
SDQ3Ksk1xLeZoeuAbxdjE6bXv8nWT6am7Kn6aX8r4qbiAb1JKY9vzquYIR3s2_cuybjTlgL0YjqhJv_PJ_9L-jx_KkAidRTJQpgY55Z8ySICKEyXx1WP-4pf
KjCc1P1YOMGB-vA_6mUyMLO5-2kvp3VrEoQzXP_hqv7yAU3TS9UEFqjxJdxQFnlwMuRFZFw3zm
}

EntityColoring(openstack)
!define openstack(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, openstack, openstack)
!define openstack(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, openstack, openstack)
!define openstackParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, openstack, openstack)
!define openstackParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, openstack, openstack)
