sprite $openjs_foundation_icon [55x64/16z] {
bPO9ajr024ED1Bx_aLFWLcb8Cgx_cSLiJurnBNtzQe6ulZUG_1eCZW5VGQ0CyJa440_KzXduT8BpCnhux2ZC8n01IEOTKWym7w2nTt3LSR0OxdtIi2XmFlTa
TcqRgYfF9OkTu7L5rT7CgaviYxhlKXPtpV-EyrOMtO85PJKagnlJnj6hK9vrArAOFyDyrAbeouTUoeTBtzXLgvZpCYDm9yAMLVDavHFV1LVHNA7kjlff2jTJ
TlhdNwQj59MztQ1pAZqzzA7qRlgCteeizQ6z06Fx8x1iH5RHor-OipDA0GUgEedzSP4UBJjznBFco607mQmSztyOAYExuN47kp93BvlNndnSFekRvcSPI8_-
osb--UGLWxK2JZ6Fkx38DXutX7LmpWzcCXRMgOpkdyCm8vSYzOM4eKScpdJI5pRXwAbnC8je5ua7ExrCqYkOiP3Go5BJt9cDoHl7xvEkMcnZewMwjxTJdjUO
d7NUJabc3yaDZV6_Gr859FbeAGeGGHAM8f8R8pkj-ZG7CG9I8sF-Vc3J1yBGmJhRlVESeZ55PAXBc7KeVM5ADI98c42FG67jQtzJt9W4SJmqHiOwxDgOp7Dq
omIOEkmQiq-j2iHWQ5v9qgqmncTnynXYmC0QVMFAQgBWCH08wHxFs9e1uBxghERj0N0TD0QR8pkxOOZVEV9tAYOTOSC90IZUvMSJ3M9VQjOr58Z_NrxiAXJc
o9rm287IDmOOSjlAE10csDesWpvk02cythfygvgR5Zh8aw5lPClshIhl70ntxS8x65NHM1Ly8tintRzOYI8hbNcdf1rrvrrpPlMH7zXqvjrM-I6alTsFQRUV
MJoWb_uncBgBVMbuc-yF
}

EntityColoring(openjs_foundation_icon)
!define openjs_foundation_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, openjs_foundation_icon, openjs_foundation_icon)
!define openjs_foundation_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, openjs_foundation_icon, openjs_foundation_icon)
!define openjs_foundation_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, openjs_foundation_icon, openjs_foundation_icon)
!define openjs_foundation_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, openjs_foundation_icon, openjs_foundation_icon)
