sprite $open_graph [64x52/16z] {
dPO9UkGw28IVbnPB5VU_xfCmNsSKfTUQIImlFo283VyzrxxduKjjHzVsDRqVn-tsjOLEdqhgUHpxAq_Rdw4t11cG5nRseslVbj2TbyBRiqtqU-Vjp0Vcq8C4
239ej_AmwdA4LWOgT46mIm394DOqt5sTkKjs0tVwvX5qK1lOb316G78JgtiDcY8y-GpT68HeU1jyyr1n1ZrhkV0-djFWUMn92oAWJKX9_be96BIpqZ3p63xG
xrqr2vgCAzOklbak5R7MidkK841cXcx6e4iRJj6A7xwbTMKQfbfckYowm80eC_GX3os-0XWIPzLogdKpa_Dc7Ce7ottnbO6K8akrJpieQP3b_UuHhDEwBaw6
3dvwoNjMamS39id9lxpGnsy3e_X5s-0buuFPUBxuEffVj-G1loT_TqAucobePkuW8mWVktZ1PvpiYg7hm2vetNp1fm0HjIuE_wgI2NYR_taQl5lyWDUmMf2r
Siedl1OK3EH5-uItvDEx8gmklS7Z4fch35x8-wNKC_wtDFbPJ-E_v67ZO86nzbnJ9VN1_g_lF-VyjG_g9qQwJFNx-k_dCnxzbuWggAeYUUK37dHagibwUzv_
VzJ05E1EkZjmcNAL5toz_GHTfFPV0PapyjlyZ7S6OIgDcD9s9KIp2mt-sBPztrQUzEdpFVZf0sxWu4lxmdkRAvXy7L9UpVWK-Tq7Jitesmfg-C_d7yQ0Ce8s
3mtLlg2jaEBlnhHwQ3x6QoE_HnxF92UZHPQjUm_lyg18zjnbQ99gm4fSVFswpn3xzc_F_tDeooxgOObcyXNnCyECbaiLJFxND0mMR4AeJpFKVjmo0I77pCzf
037yWs3CCroD6LfNLWivnP1qqBdCaFb0QrFz_qm3kGvlPI2rFP-TZQa_vwwjQyNMDDJ0y-q0Bg_7x_Sdwy-rlGpzVm
}

EntityColoring(open_graph)
!define open_graph(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, open_graph, open_graph)
!define open_graph(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, open_graph, open_graph)
!define open_graphParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, open_graph, open_graph)
!define open_graphParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, open_graph, open_graph)
