sprite $openjs_foundation [64x20/16z] {
XPC70gqu30D7aXr8xd_WXRp2_ZxfiOSEBrI1XvxhBFx2qL1pzjjELSMyqRb67slynP-3N4ap08wIs16ROmh8gh_wFK60oznk82L0gz-7mN4787k8gk0vlq1L
GgN8WPtjQMvwCUOyr-0QZtdWDUSwFZurrr1tagjLKdVhu1NWbgugUichb6cjefO-FkfrTaKAH2Wa5PW7WAxXEC7BjSwBQ9ayFb2h8fV1WdiUG-PX-PnYB3Cc
deM2NxuFUpNd8OqLHRQn5Ey5a7bncikTQnNqjJu-liuhg3jfpGeEo8b1OVlWxF4uiG2qrz_sJh9u-JZHus_U_Zy8rhky1tWO1__0bgBlPTa6NV0hvZV4bjx-
reKx2R_IVF1F_hk-6Z6_fTu6Zm_RaBbTa0N9zuaBz9x5jMSUHdpUca3IRdiAu55bjLCKT8RlfJA8zeocxARB3P3t_rjc-m5YA1TKWbA2ngbGK2hk1OGRLNLN
U97jvvtMCKeCxSBRRnN4Nn_S9U3nwLIer71GxkLGfukxaafHaFy
}

EntityColoring(openjs_foundation)
!define openjs_foundation(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, openjs_foundation, openjs_foundation)
!define openjs_foundation(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, openjs_foundation, openjs_foundation)
!define openjs_foundationParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, openjs_foundation, openjs_foundation)
!define openjs_foundationParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, openjs_foundation, openjs_foundation)
