sprite $openstack_icon [64x63/16z] {
xTArjG1H20JGUGxJVxzVmZKuwtfp701Pb4j8mR_6nIIQuJuDcQjKuJhAxNm-sanAMmkm5LeKhcQMXolJKE7AQ-jh9o9smHLw0JVNEWfSgNMilV-Rux_uBrux
Abn9EX6ukT0rEsBs_h9sNEj_1Av6I_NBswIQX1lwV8JhPAxI85n18uAi24_uKvJBr03y0W
}

EntityColoring(openstack_icon)
!define openstack_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, openstack_icon, openstack_icon)
!define openstack_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, openstack_icon, openstack_icon)
!define openstack_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, openstack_icon, openstack_icon)
!define openstack_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, openstack_icon, openstack_icon)
