sprite $opengl [64x28/16z] {
ZPG7TiCm3CMumVkVk4-odjKsiH9a3z2VMl8FzSY2xWOgmrI-HZtf_r1XNzbUi3LWFGRnCKLiUUPsCnsOUHHGnn3ExxZwjhDypA1tswJ94nR-eD_sXpPLZthP
WtwkiLi7ybZ24feOxwfMfzcz2BC0EuuoSv36s_L7xGLsDSDpT1fNpSQtdxs85H5_yhDxEaLjdrweN92IbbLsTPag5bOL8dJ9OlkzG1PL2kavGuON4fGxANIA
I0m--37IehCLt56HG2yVQ5xpOtT-dUyDxyfCAfY1LtwFR8xZf-ZoCoBSbd-Ftn_VNkVloXrSERQ_vYzw-Xq-s04wr_fHS7L24bFdzeV4fFVRlVoXh_MhH47C
39IBpxPhRLHAiyHgCHgzho-JaViHbV_i0lZPLttulbQ5TT25diwFy_dL5VPMhZHvHcDNW4etqmlpo6hAv8nwqHkQRiQRGMxx66ANsApWNsAU1NSZuIf7VW
}

EntityColoring(opengl)
!define opengl(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, opengl, opengl)
!define opengl(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, opengl, opengl)
!define openglParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, opengl, opengl)
!define openglParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, opengl, opengl)
