sprite $opera [64x64/16z] {
lTVNmjim20LWq6A-_-jsj_vFP0UxwxkDZe1uqmNkIzqZCyDrZKPFj6aH-K64hKut3Oiy4JwPQjCX3M9LEtJFjsBI6ooH5MiFYZzgOKRU8tHcxV4m5RN8Lygq
aIsi_Vio7Xg9ZBVgMur6XsQ9j9WzPh50y9z_ZNTwDG9NB3gm5t6eiQ_HHFFg-COX7Lh3sSv9W4K_U0Ad2-oGz_QZhqI3hem0SbhUw9gTD32AybK3TZbztG0J
jKYmw9qLO6mdVZHwfpdajMY_7e3BSmS9vdil_tqq7FAh7Xyr_oXK4mGNUJR8stRkLynHVV8YTH1_cC-dUVcx-VZVUNMKm9_cBK5GWGtZZyzVp6jzzqBTmAfl
FsWQwFJm11O3JFBe0cG3GjIBPnyQ1aRn-2ZQLpvvysXqhIda5tt1aK3fsiBoxUpDAThTya9qre3TdRxHT_Fc8HZxzDzPWkXtkbS-Vea4phHZmNYdmqnaV19N
W4DAjK4J1KB84db_-UkGC27UDf1ZXowAf15L6uJA7BtrCI4DSQ3vmXLipPVly66wiyNtFu32JO7xVFW15cxslR1vX3Pwgsc-OPrAJI9FXNQwXQV5Nderke-7
77k4oxWAVmO
}

EntityColoring(opera)
!define opera(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, opera, opera)
!define opera(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, opera, opera)
!define operaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, opera, opera)
!define operaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, opera, opera)
