sprite $optimizely [64x64/16z] {
fTS7TgKm30LGB7V9PV-x7UR3U5wGYPsJbruknqKM_6CPyebPYd1EdeuVXi99_qSuq0-qpHV6IBARcX9gl8BPuNve5N5h7e6hI5ZnLBvFMlBVN22MTU9YwLOH
_yP9oaw4NdmkUybpxXTiLGQi_v5ppYnx0t2YYeNkiwJ-OZTc3zLkqhe8ZAXAVIyCCOh7sbflvKnjLLV9OmJkCVSijVURzpD5NP_VYz2pbDAGzx3ONOQgknQk
8QzciJwYQXvvv-N-g7Q1lAU93yhZiWho7dSyykoGjx3du-261FYqHoJblGn-604-FI3yz0JyE0Juh4LOUUv_GkuhyDa0qlC4Mq4k5NbhxllJ7Jxr0BmKvBrN
-gur2bs_0LuQy3FLwidZzCDNBZ4ZFzEIKJTK63u3__o66l8pLPAtpWLklQhsGGByQaZvmQzUSar6tO8yygiVaJpv-AcfxfMGbt1LkEPJx_yETd0eDrvmQBxC
DyTkH7M3V-2H1yTgTMt5nrY1GxNxjk8MEFmEHZ3XTGn-pY6M9_nV0MHwuPWWYdUufysuEJ34xGk_lagY0pnoo_GuxToGzrOawWCzk9IakbMjhOfyU6lYZ6g7
o4k9-kgPhFMCjrjC03uU5x1PONqRxKcGdnbhODFWGTwVEHFoUmR6XyHI7bpipDE4Noq4-EAHTuiB_OgNyCRD5i_7Qy86XzBKYKikLY5CskVpH5aCVXKxv_il
-DwvF_P2MJINO8xjsCY2NB87lHFZOhevxxnU_mC
}

EntityColoring(optimizely)
!define optimizely(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, optimizely, optimizely)
!define optimizely(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, optimizely, optimizely)
!define optimizelyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, optimizely, optimizely)
!define optimizelyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, optimizely, optimizely)
