sprite $oreilly [64x12/16z] {
VP85meGX24G7Ms2y_sqtOElFzwN2im4C8xK3PIzq2oQ0POd0Deej1Dqw86ej2mfH1ZTNjOp3O0Fw-1MXer8HJ0u0Wov0SJReiIQbEwUiYS5LQsqHOAztaFx-
zB6v0EN2e0bk5B94m-EPfIm8VlF5sJfTO6pFm0n_GaGq-gzoutSVDvbtbHG4cJ58T-UncB_VqDzzxCC5WFxoDVqRPvVN-ltbbpIT5S5uZbzan-__uu_QA6iM
ew5OlrpBr_hzxul5O9jn8_r8sdZkNtduMg8mED-rTuhTrubKlFpOdU_d9v6HjVRo8Old-7WTp_niB0zCO8fgZqBFdmsnwF4A
}

EntityColoring(oreilly)
!define oreilly(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, oreilly, oreilly)
!define oreilly(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, oreilly, oreilly)
!define oreillyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, oreilly, oreilly)
!define oreillyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, oreilly, oreilly)
