sprite $pagerduty [64x13/16z] {
ZTA5iQ0040JHcTKc_uIlaFjkNOBjmuy3QEk7p05RUYr2_pisivcV_MJDsvdTLz-I2YigBSbLuP0KLPOSpg2kcLPOKZXsmzUwu_4nB6ibB60DkvGQzlPQJ4kY
XuDa92t7sC4cATDYBIykGchSf7px9guLIhlI80N5sORio9qa9IMn6vb5DlhlwxqFKeqY8YovOPaaRi_LllN3jUB7Yn6j2fqj8Uq4VT_fZgvUlU_vLzya5lSW
AmMZeRF1HKgrldtR2HPhzNzlJaJhBDdPtTCmXJK0fRdysLWgsALKhAKXfR2kd6c7EfwRVlu7XwI8UCOYynAHzzYdXegYz7lVZ3NyYGjQalu1
}

EntityColoring(pagerduty)
!define pagerduty(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, pagerduty, pagerduty)
!define pagerduty(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, pagerduty, pagerduty)
!define pagerdutyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, pagerduty, pagerduty)
!define pagerdutyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, pagerduty, pagerduty)
