sprite $panda [64x51/16z] {
ZLO9TkmW30EpR-R-j_qJAntxbvUNghC4YeIyX8aJ-10ZEGjATSp5U_EQe-RWB2Z6u7KO6XPMkjMIJ5ZmRF5c-3fbTV_HBFnTLQ26qPgzVj36P8phnOZhkxeA
lMw34heivbuYUGTuYdLYbg8rrfnp2HFC-9RFaSc3R8DaMRRn2HJd85m3XN8x6ybxfIkeW3OpKUpOZP9yHLcG9Sgix4EXcSKYraGdwqmFO3yWhRqvoMMJtTRr
eVI2pPz1yqU0n83iUGsln7BschW7-F4J0j85FjIK_YP0xixy9J8_Wo7cGSzZDFf5gcCKVrzFeNYKMZ8ggM-Uo5_weXj_H_qX1Om2NvKlw5ZyOtq-o9CN9rnY
syi6CdPFUM4EXMRKhsiM4zoNpvLqTL5wsWFRDas1W8FO4ANR_Tei7lTKVaU7p2jlWcXkW5ihOljq9pVX2rYxuWkclgGXPhfSolRega7kIaZu9f-l5Fic3233
CWP5QmTXNYnLKVvcwLIqAje5dkveEDpygKUExh_s3QtACFno5G_sBLyBE4z-qLXS--aTw08s_qtvMjBhMht0lZtDYl8Zcri52CRWC7TEOEFq320vJI2Jyj5y
w1KWAriDJFVA9oIxAbbFAmxlV4UTUS9dpAMK9AGuc8VINJ0HDcqVWLpXFb-JDrSxgpspJFsRvUjqzfu64gquwf-q_HLIofvYMGZK0cbkDXV17tnQMdI5jdJI
yce3M93y3C_iJiGDL-fK0p3mOQrp5YaVEWe8m1hmDSbeBNcOe5_E-Fy66te76ScH0orETV8kn_RmfHNW-B-1mkQ7Ukd-Ue1RpBE4eVC6k0bTCNHxDM1x4F2n
jDvAF1jBepVzm0a2RqWuHyzcMV5T0C4lEbNv5lW3dPCxKVPx2DY6Ypk1euzV7a2AdemdAb-P2Sy2OJpIzPJY-g10ei_PFIEk-q7LEt-mbpv3FC8t79IZHEF1
KnwOhw_bZMC3QzIIFiYbJyOK3j0t9Ddh08_e_eXGv_7yN-tUxmZvwvfNpu_aVm
}

EntityColoring(panda)
!define panda(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, panda, panda)
!define panda(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, panda, panda)
!define pandaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, panda, panda)
!define pandaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, panda, panda)
