sprite $parsehub [64x64/16z] {
nTO7WkKW20PWHCI6kVzjjqRo995fM_xfvOlO7-o2gRGkmudKkB61IXy_SWmtn-0d7OkCzoRTTHqVY1YDT-rdvIpZ2nwR7I3z_1vFfd7fhUQSgqwZxzFIK2yK
NkTJtl8yNb89RAXklULcNRapgyLhEi4k91iVvMeym3wXFlhGnmo3d_paY-5U-Evfmv5IufGe1lC0u_kS-BpiOMREvqUASAKOFnzuj5Ndbp17qBJLpy4Jl2fN
hU44CxZuT3yBekhb0U5X4gvg-evhU3uWYFgh6DBob6-xm9VFjld0UHUcMm7GxDJJtcT6EuSeynjJlT-3E3tPyaczMy1iTdQ_JA_S7u5wklar-ULhs2o1kVRZ
hNn_3T3fvVmIJf-o7qOpWDRp6_ui53UU_xD_ktwl_ryVl_ZE-KyRZ-ppj6uWiHxUy74z0zlDHtPzM0-0OhrV09FfFbdl5y1wX1ydCzwVGaPpV3Huy87trPlT
pyRh0tokYmSVFOJ47jSpjuBn6c8scl5-0zFM0oRcLqql4oGwUeitGUAP55-7LwzxijucOFmHNCUcBzUzyGXl9BGnWm-Ugy-ZUQLbVHhDAo79kAf_zeVmJcCT
oYLi_8_qzAZBk28HzluOakEA0rMvz244Ep_J2qSCFuF4YdNcNQ-H7r5gYdUyduxmUN-C4k0BlXF0vxqmmETzvm2VyiSnXXIj_CDUMeu17lCT
}

EntityColoring(parsehub)
!define parsehub(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, parsehub, parsehub)
!define parsehub(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, parsehub, parsehub)
!define parsehubParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, parsehub, parsehub)
!define parsehubParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, parsehub, parsehub)
