sprite $parse [64x64/16z] {
fPS9pkmm28C7Od3lV-6tHghg9ln1Osspv0E7Af1-DZ9797bTP0RSFXqP_g6to8IVqcF28X8dBY1mBy8GMaLKj0KLK96-Jovqqm84tucnnCLxfRGshW7wk0RG
lVUKvvNdFrL5D1PmmFze89-BE6u-jtIEUvK_QqGht4kEANyaYi_K5lUFAXT_GtWrQ0COlWYGPNhwz3oxq7YLcbxjFiGSqtHvYAEt--3BRpxNM95Ul15IBWwf
dkwDwaaga7lxadxcaw0qOt4-uX9fmUYklAwiemBNMX2d6pxZEvvPyCQVTyK6h_NlyvjcK-vVq-EiFm88hbgU_2XSERSaVOCdSxO30NArD5GO9frwnpEy6l2w
d2XQvi60py5ZV2GlLHWNLmDJkOyWbmCYNpqFN6dN9277gpMAy_b0SH-lVKxTh_3pEypC-HDlqwySx_dFXfVz6f_VdTHENu_daCTlOzwLyoIz6hWr3jBhZ8nZ
V2OJeqoVfd1G_7-IGZC3GB9r3PPa_GjWT76QNenQeXUTfO5BW1wk0VW5VluKcFRD2n3HU05h9DTBTdqThoEm6647iX7a2uPzpcMEv6qxnWx-3G
}

EntityColoring(parse)
!define parse(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, parse, parse)
!define parse(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, parse, parse)
!define parseParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, parse, parse)
!define parseParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, parse, parse)
