sprite $partytown_icon [61x64/16z] {
fPPTpkiW34IB_yRf_XTyQJC2uYz8KUzvpi5ZWzo-hZIHzgfeH7ljcQxg7xiXCnx8eXrvNR7CHFiV-TVOiPKV30p9dd-WVMJxKPOkGtynwx15jyTe1FDjvgK0
ehQr19osc4cP5xAs887utgtdab21JC0qExhC3bwdsHNAwNJp16lBKIlho29WQPuuY2KaRAfKiEGsZZW1ohRaB6_80VWy9uF7G9edi-nHrz4JlmqU0axX2NRs
pmPC8zdI4mIif4aUoup9l8Fwi5iJANDRcsQ66raiGCAgxFEc3KZW4bi3QwAudLWRTshbmLwX91_uCRyk-wiviW2wecgcgb7a1i1u3mGauNJL_8E19qvRPNM1
C6aTCTEn7_nao8MWQ-rLqQiSShi44qxrNZuBXEdjxhRRvMhAdd7AxhrJYQMI13ORL8QS-ARhc9LTtwf5r6YpyEm0CePk7lWGVcrAtRzTSwHUPN4WoRYl5_6E
gh4m_2GxmJV-5uIUaSBTJJNeEW52kveRyBKL_hKDx7WIo1sSfXtEu61X9wiA83u0MEKuC6sVn6A6IHi_uHOOiN4SSGPNYpitbEAW6VXcyZZIQMk9p5UvfNNv
ZMaNDrpRNcvu7mpktcrRNNoFtCiItItswdPRjh9QlXTxBAFbplV1pS_IYssWIqpsikDTR7NGfJnBIsUvCdVFnQOUuHELzJ_Yj3LysbXijIBV_3lrz6c_qoyw
VTl9SSHg7p7rq-_mS_QiSm9v73viHfywaNRxhwJbo8fkidZnT_SiIwTni7Y6Jsn_otAPKxBuq8shSYFZlThe8ab4E8jkK9-DLZrqgysNNQQC_1QsjhU8-x3J
1r66jC6c_Jwm6UyEvHrHJt3RFQBP7DEkqprwse6k1lC-Hspp71xHrFmtyny
}

EntityColoring(partytown_icon)
!define partytown_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, partytown_icon, partytown_icon)
!define partytown_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, partytown_icon, partytown_icon)
!define partytown_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, partytown_icon, partytown_icon)
!define partytown_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, partytown_icon, partytown_icon)
