sprite $passbolt_icon [64x58/16z] {
nPM7SWCX34HD1ot__xlfGM5qyGvooavpkNsqDzpjVb8JI4ytPoemvmIghzumtuFcgNVCwGU4eNK287KF88hM7O2aTGyWQTi3oC1y052qJG2axWBKLIS0uYm1
a3e14EK9W3ZB0SGwDo1q7q1J7WNaVmUqKq0ihTMicoZp110QtYABK740MCu0TMaaru41RCOYitl50ChNdo2cmRPMDk6GZky6sQTptCVsfVxo-9siFtwUu8fs
GmZLxd-2ViDOqrmfQYLmTVuDTlW1koC1tmZSFh1O-aJCYxveSVyl2m2WHxM4zlV3IhdaQ5wUr_FdPpNibjgB3PaulW3bBGrxFP7w2jwpGoKzSe538X6Sr_ql
G0oLsW50rxe3W6uA162LzmDKHmxWTGuWobE0KTuFW5MU0xZo7C2TvG0ChPy0YF8i3KHvbZmmCUwTspC
}

EntityColoring(passbolt_icon)
!define passbolt_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, passbolt_icon, passbolt_icon)
!define passbolt_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, passbolt_icon, passbolt_icon)
!define passbolt_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, passbolt_icon, passbolt_icon)
!define passbolt_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, passbolt_icon, passbolt_icon)
