sprite $patreon [64x62/16z] {
xTPLWWGn28HXB1Jtl_2wGsQgr-r__rfZzLZ8d4Kcgf0P9YyxvssXdeHbHxndjU2ijwonDCe7QXE2y5adIZtZDUjaqEuR9owmyOttyeIF8bfRRoWcttaK5JO-
YYnc3zP39-z55vDFtkVW5Ro7TUzreEX-7V7PVHxnw1vrf7Vt-iEzVAr_-_-F8tvrRoW-xruEUEZW5--N39v_0TZa-J-GCdd-0NpsikZRprx1SEZW-JU0o-Jf
GHWoUFu2IvedJZ_j1BJruZZpxfFdZa1fil7C8o3uysi0JQliVSzM0dSKxVZR_9IQnrLkAgtcYRw7__V__jzV0W
}

EntityColoring(patreon)
!define patreon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, patreon, patreon)
!define patreon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, patreon, patreon)
!define patreonParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, patreon, patreon)
!define patreonParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, patreon, patreon)
