sprite $paypal [54x64/16z] {
hPPNbk0m20HH10ds_iVTYNuZjrDFgFzog0UsPAEEUOvfAqdEAN67ZtOgMZpWUkBDUCIh0Cc3e8ELWwB9ZXeKdcMb1uT1Gf9ybP0Fua4o8277X7dYyCLgFx8q
zlmxuMWDa2xPrN2Ghfa9PfUpD4D2oZ8ja92mXjcsdfssmbxfCBl40xwHO7Q91tobVYzXs3lzP7OVRsLwilwFjpBxLiAnM7H2jzKQd1MseSpiecITJXZZoshi
xBej56vsOzfAEgx_esFzEM7uCA2SpMvikCyvx82car_Ni0SQh3ybQJhEhjiJ5TQVi2xMVrBFXmad9oNdOrXFyEiYBAsoGIVKkXnk6cDfhrbMz2w6rl9AJeAC
6qlbYhk4LH0cOH7kD6cmim2LKAvGiAvYy0dxtoOKBY7IVSLsPBaaBMGCJv4X8KU5X1mDldiS7S9pA2JaQEojNW
}

EntityColoring(paypal)
!define paypal(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, paypal, paypal)
!define paypal(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, paypal, paypal)
!define paypalParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, paypal, paypal)
!define paypalParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, paypal, paypal)
