sprite $pepperoni [64x61/16z] {
fLTRchCw3Fj3V5Uw_-qU0lxWm93CjDMxBhPH2_--Gbc-Oo_b2tB7L-Iq_upzeVqYcjmFx0jv0-X3-wf0EA2Vs1VsQ2yuE-nz-rAiCzlL_vrzIsW020lmEFxu
M3M0DN-mnnlsvJmrRtn4qC1-Q9qWnmgdWVtG-WGn9rjCbz_8jIu3L8T6cUKkP04uF_Fr1PVfq8mNO0xxV_XZycYjBREX2NYrO0CaAH8D2CbJ6lo9J9eMXev0
Qr7tnFljyj4pZ_gp7Q9cXu6jt1u2lBa3Q0YsFG_5tNvXLLkXjFDLkc543X0c0S03lXjSxOke9MJdOuC8Dd-2Q_GmA-hJetVGJMlEtxgV8-h6xzZdeIS-sG4v
zW-px2fjmm37FdziNiy0b0i3HE7x-dqbiYC0VsuEtm8ix012p-w5XWh0QJyEO7GyRsS152lS86a_2w1FlM4FX7CMTnw0dqj7TLPyikiAEyZSPRbZK5pzCG65
Qsjsvm__7Uuty5Su09dQdn2xhg2YeOKW0rGnDqxxwGfJe8P5WoUVOgkm3_cBkbrtQ9sldfMDG4Fu87wr2Dm4g7SkxItO06Xzfbki0EmgKDNpVXMmxZ-oNtmJ
Y9l00K93xwITb4S17mWGyjVZtri2l2Hg0AhmsSl5nZy5hbKmG2rep3QxxZ0XzGm07T59pLJqIK0f1HpWAPtv57YAm38wNWylAmO2kSPI9iLHdWYOqAouQJyJ
q5LXRdyJy1yAN2Qr5PO4oouGTiDm-NRX2rjq8FJglqpYcvnqDVLOOONLJiZiLqVFz6f6fGlKtEmlzeiTV6RfT2szJBQ9iyxjStpbpXLLMq5R6odbHMs53elB
UppLgzDvhAezqx2tSZ_pKpsKXdmzkUESjVo5hqhlVu-TP4xlj_agmlNJByd_
}

EntityColoring(pepperoni)
!define pepperoni(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, pepperoni, pepperoni)
!define pepperoni(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, pepperoni, pepperoni)
!define pepperoniParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, pepperoni, pepperoni)
!define pepperoniParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, pepperoni, pepperoni)
