sprite $percy_icon [64x51/16z] {
fPO7pkmg34PDTVlO_tRVcqH148MGN_TCjtIimQRHdb83_PtOfG0lP-WlVZAOrFJBmgrP_dtgNp84RVy3uvn_dn8eDN2Wxt0xmVbUo5lpl952J1rh4_BxZTqW
YkCIq9v0fLs6c-2tHDiwrbbmBcnZ2ELb-8N5q6QiX51qY0eHnJohgOW1xHc_9JLnD1tqwZSLRkQEXhOcZpEs-Zs1b1HZp8ALBwlATrpOsnAd6z8MmDKUmfCy
bXWOsWuJBentFr-oAvSSGnY4INtoG_Mny2fShUteVcIqLm2i_V1YmrLgoMdHGlJ9ljAFiInRgCSqdXQ7UVjEliyzS1gglakbT17iD39fdrirRNmFbnxzp1T2
xJQHRFHuwUdGKNiVhH25WbVTRhgpThlNT0cOBYAcOa6bkqiiqJJsl-65Ec7G5P_iIWFQEfu--AXXiM4WnxqjaqtrMAo2SpEJpsMRZ_doyptgnWPFxjn0LDlf
XPxHJ-iEUQ7dZRZHoJ_vXN9wrCidNIXwUFJjY-w1tFzXz8MusQhusEf64KsUz03DyNxTo34L7OF7jiPFViot3g3-We6eeCUS4cP_ngOs9mK24UMUe98Uxoju
r2kkUq6zWZ7WrK_ThyJu2TFUO5JE7j1k2ihvftNQ6HkJZ8VDUWvQE1J4QM28b7jqWVG3eG1bhgoUKQ4tf1y8AOtjzJChnVIe_GS
}

EntityColoring(percy_icon)
!define percy_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, percy_icon, percy_icon)
!define percy_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, percy_icon, percy_icon)
!define percy_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, percy_icon, percy_icon)
!define percy_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, percy_icon, percy_icon)
