sprite $percy [64x18/16z] {
dP45sYGn24IB2910tV-w-v6UhF_wHbeVYajlc1CDtq94D6FJVNqhGbiP9BD-4r-bgsqMiIh2cXLYsEnc_KHNqmQOJHtrm0R4JO3k3a0q7tdnHGhWF2WmJraT
TJ2SJ4kILkyaAjLcxhgVaO_V7dy7sLjowMQqunjPhveoWA13D8uPv_VYyHLOPQGE9MSmUZjvfwiaHoSxPYKkyJS_SFm632xdWmODBTbnS2uxB_PCsmmDNh8_
lbL-h_npglQaGcv-T3Bfg8YHZBLvsGtuityV5blAXv_-IonXbCvC_YBchUzWT_uJoGd8Q_x0F7jI2_fllW7NZ_7t_b6S_GEGvAg7-Llw7FZDnxlqKmyMVyE-
u6kLZnOiuXosAIwMXdTfiG28b6dMHvAQ4nTf-02HEsZp52XJEV1bMcvevTqkBlWYFm
}

EntityColoring(percy)
!define percy(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, percy, percy)
!define percy(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, percy, percy)
!define percyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, percy, percy)
!define percyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, percy, percy)
