sprite $perf_rocks [64x12/16z] {
fP450bWX34FJG5j8xd_VyMNks_loS6dnCzfsuRUG382tIDujjxRjutXgu1Zn6dYc84wR3dN_SqhQf0v4oDu0-ceCb0xphLA5rg2ixHNBL9CnDUccaWHeE-_v
dCgfHMv5kZbck4eJRPBUAONKpNcQdTIg1DAsHBIoDTe1JEVICK9o0gcTOUr5Q7V5jDpWrGBKbbr0MqwiR-Plz_5eFuLGHyJKs1lKnCrwxqyjJ7Uyvu_x_Aa2
1vRrp3_K58Vgqto9ztoayaWwUapLSo-vFsLdH10WWu4BAYyzZG3d3E3rcxyn1tvARlmNHVmN0t_41m
}

EntityColoring(perf_rocks)
!define perf_rocks(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, perf_rocks, perf_rocks)
!define perf_rocks(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, perf_rocks, perf_rocks)
!define perf_rocksParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, perf_rocks, perf_rocks)
!define perf_rocksParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, perf_rocks, perf_rocks)
