sprite $perl [64x64/16z] {
bLU7jYiX2CGEZF__lU-5apMet3QtPDl0q5n3No2LFaGL4ohSQwA_83S1vd_qCGs0zF9RTZMoqMh5V01flr7Hr55AmVm0w3zPAE88q9hd3hJls6bWEaWk6QS1
oLyxr_rHfel_dOI6UVExu38mGdg_f7AgfP3E2npJJxpuZMJUa8X-ytCjFUHFlcEF-2rpp9zZptn4Hoyj2_5rxwf2ql2HOlo16T-bXJ4Z2FLQvD9svp1-0faq
5o7Yc8_-yEKBVHLKXIYj-vS3GutSQw6aJ8qjFdnN0mrCIo8ILEgTSYUgYYy5LCIXCPI8Ar4VRZ9l0Jp34Hr0ewIlGnbkPV3GL-qHvdNWLQ06QmyPSO-Y1bDR
RHnWqOcGWJaHKRuay2aVcXzw8wghnbrhD6MQZjQLz5QAL-7qqwGD_KhslS3oQWXDBsz8zA32RkRTN_VXGvvsjk2pfV1x0posQ9u7qAojqScX1GPKV31h6lYT
X48U0toE6-Iek_MwXQtswP4Kuwo2VevMxj2V9DAE2jHZOlHOaFJ90qVhj4mzEX7hu5tvj_lq76neGBERjtzPoKCsgVURoeYopvniivZm96AiWXm1cCwEau-s
sfETa1Dzele4O6pyZaS9Lagk1FWMqBQDhLdhAv2RNp67vyjpXBRuuwaZJhOHXn_3djHtNr-La6_v3QlbsRzHsvAzslZItny_zkWofMiqh6mrvdUyHtCvpN2B
USBq_NVNZyrwWakw-0Jmai9X_wZTR70zN-y0gbqE-hViyeT_Vw4j0VBU4unRlYwFAxu6jtpb9Q3ZclyC2qbToRm0SrUV4YQz4YYmuctklPwsvB1TFXBGmUvf
5nqVxwwtbW7PUuUtqKbkORoc4DtMo-npBydHKJVJQvwJMqGBXlEn3SxiyVOJMkrD2pF07m6bkbt4lRH-xa2i_mNWCe1HqrAfyE_Psy2oK9D9WZM3nMGMvqMF
3KmejmuxihEIksB6z7WBRhvrOimN4V36-QB76q6qgNto2FP7CR9WeykBZyR7nl8RDFL9U6crpuKVlm4cbuKB69b-H6gAaAm1EqOP2XnahkblNy67wEAsyXNv
7m
}

EntityColoring(perl)
!define perl(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, perl, perl)
!define perl(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, perl, perl)
!define perlParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, perl, perl)
!define perlParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, perl, perl)
