sprite $phonegap_bot [64x54/16z] {
dT47ahFA3ePXgHLQQVQ_tIiOuxusnHpulufT-7bDWAjHbC8_ZpodHCg_QmGOSnMUQHkjbG0qKvx_TslKI6CYN4_nK5U68FGaCYS-qrKLUXYQR5ruyj-LSln-
yDWkhiAT__xIwwDS36tNu_pVdtz15vvJ4P1iFVT9R-VGAn-3jUCISjQ0lsT2_yCZCJF1MLCFDur_-Xu9uraZ0EdOB_pjZyBIW8AhTiDl1PjZNK3cJT_sFMUM
DnbCi6Qb-D-UnjWBvoyexAbum--5RqqcF5RXmfFps2S4i8Pa4QuN1GuwUSR_rqpkuLU5aQ7qxSTRimn0z-P78G8-Xf4czElfxR7NsboOoATul0gYYV0np-q2
jJVZbt_fHcesPO1vz25IXHDElhSLIDtuyDJSFLfl9tDlxJ94ayx-iz2U6M6st_Nkjma2Z9bsyfdX7aT1nPG6pfTUdhRia0Zyyj7phK1ReG-gDbzw-J0XcGF0
aZvyUFZkWuc9tCDi2Y5-UG_JoMqqvUqjDvov_u39VBhxqX_Uf-WKR5HlhnNX4N5ui_ZLu-IDXqgvilhRZunUXXzUIRdnnz3JUm80d3_f6G9apW0OwH4LbV7s
GbzwS5Qb6ybeuVKJ0wmootNZNXD6d-F2iwUXPAKny-YBwcdx7sPuP6HDXBsm_ASUq1EFD9dS1xAVQXgkn1OUbTg5MSkVz3xoT1MTCx9-drUa2xuNG2k-lBpq
6ZMDp8djUqplGgPNBR_qzuOe0XoULg6gGcssN_fobOTVXQoUajBIbwEet3ptZa9OPha8BVt7E2hus5OG1jJyAL_wxsdm6Wb9AxIgrhT6xTVQYn0D2eDxuozl
KoO3eCUuvrC-VLPe1y0IxtYqz5LGDgkVce93ak3Mo5T1YM1ubK-D701F2yhIPycgcdYNhq9xbT61cMa4yB3Gcar51VVpW8U5CjKiDn4Uh4a0ZmjbP9a-pTFW
-MZxJsJByXl__Zy
}

EntityColoring(phonegap_bot)
!define phonegap_bot(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, phonegap_bot, phonegap_bot)
!define phonegap_bot(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, phonegap_bot, phonegap_bot)
!define phonegap_botParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, phonegap_bot, phonegap_bot)
!define phonegap_botParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, phonegap_bot, phonegap_bot)
