sprite $php_alt [64x32/16z] {
dPE72WCX40NNTits_t-RApx9WnN4eINBN1jM6NFMco3Bf7hZP1LJxikBBEFgJPHbjdfpo1h8vwTKtt6Mysqyr4rJ_yY7QVcKeTLCyPN83ld-A6veobwPRDvy
J1gQShq_KyfuvGF3adCVcf4fkI-Q3UKrQFlizQgMpUqr2_9XqK9xbi5zUZNRVh29A4dOzTW-p3BCI2QYd7pzEyJs1Lo68Lz_zNEAHnH3muEQabaf2XwHsh2j
MCHbVTZDJ57W7fHF2kKZyrJpkObyhfaS9JPbd8zDYc9yn4t7-TX4b7J5bEl7Bae-Fp3vIE99IZxTv2E9UwhvT9EFP3uTXhtKrlEnsRxkUjNmuAmqNBXf_on-
Hyr4gGaq4pir0Je0Meu9l6PYEHIcJ9mjXJcpBEO3Fm
}

EntityColoring(php_alt)
!define php_alt(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, php_alt, php_alt)
!define php_alt(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, php_alt, php_alt)
!define php_altParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, php_alt, php_alt)
!define php_altParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, php_alt, php_alt)
