sprite $pinterest [64x64/16z] {
bLTfekOW2Fi0PV7-zvrzNX6ZzULV5seIGqi_6v1qynY_46vTwFCTSFSOCxppRNNp0U6TRgfZR16lJn0VHqGxLPEELpZl5uznWns5DYwXiBoFQnWer_4DE5sk
7hznmQ2jbQx2z7iTOkaUnmV8Gh0LXbHJsVF5ydJZYsp9SyNE2S4cnOQzdk8Tw4R7wIBfQcwQkvyZ4U3iVLKb5i-TnicgkWS1LkVQXqP0BDVbTP-cuFMQ5lL-
odBGOrSwnPdFiHLyLT0cElRInsqXO1DzdXssrZHGOdeIG57vMKuX1TXSIcUaqgFPBK4zypnKatpAv0I5qvP-SKlgqlqEUyjN0xANIN2xh1zHiiTfAp9_NB-Q
8yczvDL5lURwfs57WbtN4tpbwAa_3EftjF-E_8lily0tgwoUUCsFJKmRwc3Ah6j-UJBGNXeuTBci-TP0ydEDhAyFV_ZpoA3reKehFt_osz7koyYQVTdVU9PI
jBnDvxG6X9Dz2jJpp9ZhjqynLKCDsLEOSg3QShF1ZoMXPiZn9SlaQo1jFfEY_43KD0qJjkPPR-Ohr7aEA6MsRIatE87qZVmeFDWtB1tAftcKOGNVKnJpuQbt
JVwESDrFOt13yYtDa6yJf09VOXpWUsU3a2WaFiE1_2s2FnLavIrj5-NGW_uct-audhRIP_VfPd_ijui_C4n1JkuRVOvW2zalx_9v1TDElQ5g38D_l_UWwPV7
jUsAVm8
}

EntityColoring(pinterest)
!define pinterest(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, pinterest, pinterest)
!define pinterest(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, pinterest, pinterest)
!define pinterestParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, pinterest, pinterest)
!define pinterestParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, pinterest, pinterest)
