sprite $pipedrive [64x15/16z] {
lL254MKn42A-td-vnyi_TsScQq0Cxs7UyJLq3sku66xu9lpR_XW_uH_Z6yHyxs_p2usgJ3MT43r3TIypwLIUL-vYTYAswkfARA4KMBgmpNN0uuNDuhnjl3Tx
vHvv8JUoYSW0E5QzYhayV0qBtnvhHzZWH2JfzHAjNDCPf2fvU3qxJUmCgnXDq-6nWH4nFKQ_BnKULC43Yla0CxDpxLirBuMLsgFmOXyJO5mi1dbW9GzxTs6I
dVv5vlfnCWR7j5wqz-T73X83EC-vqbfxdl-Gz_nuw-TkNW4hkmhwVGwhuFpCB1iC8dnodpQqOWxFtFkTVz599JO35Rjv4fI3GV8sqL_JbC7XfRdXzLTYCNJ0
Bk68KWjVm34xj7WesSRifs6IssAstS2fCZLp0N4UHKVmw7Uu__Th-DpV_xF_3G
}

EntityColoring(pipedrive)
!define pipedrive(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, pipedrive, pipedrive)
!define pipedrive(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, pipedrive, pipedrive)
!define pipedriveParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, pipedrive, pipedrive)
!define pipedriveParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, pipedrive, pipedrive)
