sprite $pivotal_tracker [64x64/16z] {
fLS7rlCW3CExzx_mFz82eeBNfM-KvY77baT8Eq4jCkiVCiDLsYSGYxejgBItJMWdaubts9Qt8-gb1KNsvnR8SqR8kpUloWjLxxbWXToOEHFrH1k-fJkmGocb
3XPYHw_1TddbNspfB90uRTeRiAqwdka7XP-kTyCfM4d_yHHBT0FM08EELPmNlEqDbF2rXC2pGmy6ahnF42u7IEjubY3PesOvO7qW7FRRjYuZ1-HneLULr994
_8Qf6l3XqACs71qm-89mS60AuW8H-B86a8HWpQRYzNyRBCqd52Y1qU1DjJMRjvT8WBIv93LjQ9OpUac4DyDLXw7erHS94TDTMmCfrY9I1VM0Zr4RfaBNXdNl
GZ0_xn865_EKFMA6J_niJKHPF1GWH_QOxrW8U0Ko2F9H_5o9IyypFnOeLQBnkARUsS7ZWhUt-6ftDCAHdzWt76pl2xkmzZ3ndSIsN638X_pHt53A7rnEvlFS
alKAyyll7xgTctQ9hiIVzPlG_dXxg7jjiU7tlfDLGCTjFkqGV_HTulGKwbxiN-JNWzOD6S_Sc6r8VErkZnNDVCDrW6CwkyTc8cqLdxiU8TrzA2HyQAUzzGWD
V9evb5zGBXPeOTNuq-DqxDywWBKBmK0DY0VN8daFHUiy1RWN-1mND0iToToBAxq4qu4QyYnmGVfCEDcCbI-zOfWU-sDT2ZbWk8zEUgi4V0noFdvYy6pWXjM2
a2YW4vAEx_HMnK6o1ZsLYdlW1GBfV8O7L8QxcNl06mpdYFlYbpSmhnVi8DzPv3ERKlE-1KxB6SOctd-1venLnf7y5m
}

EntityColoring(pivotal_tracker)
!define pivotal_tracker(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, pivotal_tracker, pivotal_tracker)
!define pivotal_tracker(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, pivotal_tracker, pivotal_tracker)
!define pivotal_trackerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, pivotal_tracker, pivotal_tracker)
!define pivotal_trackerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, pivotal_tracker, pivotal_tracker)
