sprite $pixijs [64x23/16z] {
VPC7qY8m24RfvVuNtWn4ncJZ_wOXylpI142a1KAXcGOVfgNGuA87YKMOLX6HJJYlTYxaq3aNtBMlCW10Opk6-OMZvCBk-5b0QK2HG_b3yC_yyUDRTyXALFKg
L2Bqtd-tnhSspPQYvGSiPAhVTF8i29bWBF3gusREkxXzXm_jpq4T0JZpSldny6s-_FIqYfUVJeT_XbahM8Do-U5P61y-UOvVOdOyylZt_OLiFoDshvArxy9R
xFpt-t4iVn1k7tpE-U43wlL-cc1eVmuZyEKlKA8TxRcCgFDeVoxJuEKt77dVvlXpK_I_FyFqXw_F_UCv73zzgkvz_bqQ8HJuAr_gbxtJi5kqA3t5quIGUl_-
yckGUnFMBPimoc_euVlUENR23jt8uGiy_89xlnkD4VXuC60B7P-isItxm5PNfrHlfp_q7-WV
}

EntityColoring(pixijs)
!define pixijs(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, pixijs, pixijs)
!define pixijs(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, pixijs, pixijs)
!define pixijsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, pixijs, pixijs)
!define pixijsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, pixijs, pixijs)
