sprite $play [64x33/16z] {
fPEB4YiX24D1G2J__y5tJDcwzztPfk_8ISSuYWpt8Szb7k7s61yUyKs01-NZEpvSd_7sRO1xy_wtXim-sC7V0oRmptBq7M2FU1adu0b_x_0QL1NHCVJEjw7A
rJFtXu1PPGcWfhxvGIDYBrMzk5Lrxx1FaKY1MjgyqQ0_363N1iJfy1OmD-dc1UIBr_tLndPWKbYRIa1_wz1VV39s0Ke-W4cdDhyjVa-vvESGRfKvuB5_97hB
iVd1D0Viy779Dz-z3238hyinGecIzbeplN7oq6lQxtp_ALEKxRMqwdQ4yrfAO70piokNHLuAoTojjXktxZzKTdLBOgC33D3a9slOQrG3qubVFr457fRlIOkt
WmeH1OEeJaidtlmiZkxVYwFnOdq1oPsTzXpDkvyhepx3UdtcFcwVqrKqfhsQdOsFQjxzuoidfpqbJbu_vDMyi4xrr2J-4T_NW4gquY2UgV_Xoq_rr2B-eLIb
LMYvFD3XKvvfWbhoL4bSvR7oA_m7
}

EntityColoring(play)
!define play(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, play, play)
!define play(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, play, play)
!define playParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, play, play)
!define playParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, play, play)
