sprite $pnpm [64x46/16z] {
xPC5jeKX28G12uRzh_TsuGj_NuTpOWxnsT8JvI3fOkOOVoI_-CKldkLH76FkwpIK1D6i646fN_-OzmVzE3uhK9dImVHiZKdQmHIMnpnS3KeMJA7cK0SFUGSp
80OHs86NIvIX1CWMdW9_Z1IIDlEbkV6DhzN1C_CxO8aKmYSUGARB_BQ5Hpu_QgA36yezEjgG1vZkCiZa_Ki0M6YI_-p_C_z_KznVZ1CFvpSyglJhJp5-XW_d
LVhpIo7s_ymlVl5x
}

EntityColoring(pnpm)
!define pnpm(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, pnpm, pnpm)
!define pnpm(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, pnpm, pnpm)
!define pnpmParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, pnpm, pnpm)
!define pnpmParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, pnpm, pnpm)
