sprite $polymer [64x45/16z] {
XPLNqgim64FbyZMJ_Q_t3Yb8_1xcdcUTKEG82BCMAGWzX8a7raiu348KYGOYs6bzUHt7qbZFIyyq4DAEyxBqZu3Wr3Cwi1El4-h76Y0jwQTZfn-lD_IFX61v
wHa36_dwGFrO4wI9dx7fao_-kDv2tH9vwRbtkDG_lcmTvezeVxiZrEyTZgIVjdMt-rk7IUuTkkfB_AMn5eA3j1AbUYqI4ARwyikn5lq1frur8BZunXTJuYVG
Ilo4CAYx3tp9CwaFRDIh9WIdxjQklprznqcAdmsaEtsVE6dVi1O-g5Sv1AFktg0tgmSkg5VUEdJn3VgozC3tebzRX_wZlw_47s1PJdthaBvXbFYfHqhyUuSk
p5oaEeYLC26O4zDOtcAH99fEgP6955zZ6EeRBd85_OOXVjh__wvphRhq0I2evwtgJZiukRKMRq0_3Raji_tqam7mjBczwJXnyNE0jA2V3l2qfPrCBZEN5SBC
4_ri-bgyWVwBYV-dG_hlSlhwKcR6P5BVEumV1YHtpOp1GVzlX_GpsbWNPUEfwWRIG_1zM1aZzZYvwo06nJIsxSKN3-g56qrIRe-JMvS_SMTgR3nDRd3boHvp
49rSta3V_24fdu-Jgv_LEyvOU7kQtEJA4tR8ONoQt2NTtJ69RHtwZv3kxZIcjWwTb7HtPxemdYOt4i8_
}

EntityColoring(polymer)
!define polymer(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, polymer, polymer)
!define polymer(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, polymer, polymer)
!define polymerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, polymer, polymer)
!define polymerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, polymer, polymer)
