sprite $postman [64x20/16z] {
fPC9hYCX44DjbrttF_AeI10zV-_a2R4_Th1GkZicxdBinKiZk2_mBJtt1r0VI7TmZ_G1gkvwTVegLVgn01B3C-QA-FFkHNeVeLm1uFB4Da5t4GmGuHcvBZf9
fGS1fGcgYH4i380HHsNMm3c-ABeNXJ7DYIN0vlPbsmAavLlRjulLnu-5xOFXzajL0in7x3E_JXQeqQ0wcUq_sc9xV7LwGTJr2KeOKW6O2l_t9ra-eZ52fZV1
WIiMVta_SX_gzllrLSyR_-Vz3zZ2VTGR4ozHMRPmcty
}

EntityColoring(postman)
!define postman(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, postman, postman)
!define postman(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, postman, postman)
!define postmanParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, postman, postman)
!define postmanParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, postman, postman)
