sprite $postgresql [62x64/16z] {
bPO7ckig34QFg186jF_Tlkk453EPxsNELCeVDOJDEo9o7OSOOn08nOunvXpTIkGdagrFdtFsGtC02BNFwUxJn_3pxpZrxjvhu4AmwJvxQ-qOvuQX-N2VXwbQ
wtDOYRAyAMtwLE55cTvBO16odSPQOl4GXY00KhhFp0FpaG29CTt3X5WJ45BEEOQRfDe_ccc9G75NxgWVWcGzLvkPQKboCt6ERpCr0SdQ3TC4ONZZ97jVIq-i
R3DcfqBRGn-GxWOmPjZ4hKA-pjmKrESedV82nIlHhZltZrkAgppCAVGfQBkG2K_n9jSt2-ebUcCtBIyRkrpi5LtoLhnGseMocVuSaX6yDu-RunOfxHVq5ReX
FiwmDyVP9Zwdn4HyZ8bivTeTttFoydpCiM_EfFOhzaoAdd4lzHwsdVoGQgq5z9bpcsFpt0AgEGWIjxezshei5wlNdt4BORNbDVS59COebELYyzGzO5jU85Mj
DO5TvdDEnI9r3SSKyuXkwgHc6UAby9Me42sWpwJnuwpPlVuQoEMzMSw1LblBhP3TY6vRGwscCJCbNDHtcsBFi97P2RlwTHXjFqJh4mtc5EWk_AOMR3_0wp8e
93y0yqZzHHtGlNbEsyln36Ilv2_Kgt4LkV--EKxmWsXRpdVrMj0LW6MA6oTZilRlgJAvg3FHxgwPq3t25lWAx7EdA-ZTdqBq3bm2tzHxfriYsgcsGFF23V5B
nVNbUIBljquzrPNeWqNtbPqjMFjuLGjwcguigXVoUrtpThTU-enGY3w5HV3ZVLy5NVMgRQC0IJYyyAIxN0zLi5S2TkD4adTULA-aozqanIoHhUrKWE6QQ-ij
BzSxObV_90f5Fp_B_CRqbRhcYN9v_aPk9Fif9XQjEGbnEYV9ZvTn5QhxK0XGzgoH0WyEV-GjKbvLEVsA9AjxuWB5h9PSQXQYEvjn2oIVHnMYNG_wQZexgGdI
zFfqujv15eaj2Tp4ULVBkj91r5rPH9-1g9gGuzoIzIwMgvex4dNwBEyr7m50-hXbLJKBRBQLq8_Z6FuF2xnXFai8URmxTCXLNKb-CeuIkA9-unW-DCSOo-6-
gycUOn0-4AttbWZD7ynDdQaU-1z2qUDeckfcsnBcWIyfkpfoJE5ByguEZCctf1ckQcGElYNEY5xBxSVtQa_eLcxZMsGcwgK_YnU-PbRAzmNRwPVt2XD6vtlg
-ykS5Q9NlYVCryLgbNLMlgPtADQQcIPMphudkK98EGgWRlmDynPMvum_Yw6v7wPjkFVCtydT_p4iyO7_
}

EntityColoring(postgresql)
!define postgresql(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, postgresql, postgresql)
!define postgresql(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, postgresql, postgresql)
!define postgresqlParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, postgresql, postgresql)
!define postgresqlParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, postgresql, postgresql)
