sprite $postcss [64x64/16z] {
dLPjsgGm21kWG7B_2-zE1nzRrFUBNnO99R5WNm-cDZmI190PRlhwkPads0rXFmAhJ-pSboGp0VmuXGP8matUTH1a_7yG6u5Fsl4bt44YYgk0DaXlXJtNe6-q
ox7CDpJ84s1Jbv1x-02PUYwPdooGZTzJ2R6pKq2BHMv59Wc_WRUyoGeg2Kvpad47rssTookx91YDEvcohSzi0a8UQYqpxY6AzRsL1AVb7Y_OY--QUPT0m3KY
6v_e1QD_CyK26PMiazyOj8nswYtev4lldK5SF5dLDdPeeUNak6XejHtsn7dV6z3E86-EXwBYHFHjDeP7k8D4XkoYwlLR9PcPGFKxDqFX5zw-R-y5wOOhtlWc
djlsXd0IoCmymM5l9jxm0b857AihtmLfzIc9J91Cgs_W_PkCBMT0Np7n1X9kCrDKmoPthab6hEKFZEdL2O_5FrVP50Wor_85NWDBsu6N9CV4CpO1IUfPJzJ0
qtQYAsks-1UsjNWvaNNMTh4Zo21pmmDoHCYIz3eWdG0fIVes1N0ix4nwrq3AgPuioWoIMTaqrgBqYXTCV8swSuXKg5kRRK_uLv1nwg-V13uMKHuQkCGk1eMN
d7XhRNarO-rV32hb2wC5rZZfvWU-65JALtQjunwF4oyrp0Q9brtmJ_8Nle1ISrl6zQH6Ir2G4kvW83bvw0q-B_WaHvLTGQRyhEs2Luox-G_Ibt7irJoNK8Z1
Rlu_86pbmnkbQtxuLi6OoFqg4wtDsla9PWch8wiZjhQMyZxWvHZ30CcKWzc4JhCTB_BnAqXxFrhoCBX7PeB4OaUVUpOlw-6q1PUPuUwU93__i-6HQ9Pb4Ux3
L5LwIrSJ_DN6ndxeB-62RNi9-HtUsQwrl-EYkDouKdvNVUwU9EGtkqEkUjeluDgz3i9_0XztyFhDV_yP9BZ1-xKwvDlDdwLsa71zHDjs0tWAGDvdi63rp7S5
Cgm7oNpn0ud5guLZs7iqYzhmp8-ppVgd33Ew3mAu_Vo0clVvaRzjKJNtc7g63tqg_1y
}

EntityColoring(postcss)
!define postcss(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, postcss, postcss)
!define postcss(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, postcss, postcss)
!define postcssParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, postcss, postcss)
!define postcssParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, postcss, postcss)
