sprite $pouchdb [50x64/16z] {
ZT89ZiCm34DHMoPp_njt8uh04QCeCssnFSXVyHWZvkW-eP_5De1-GVJ017GS7eoM010_oUDW9sM1MB_3VGKx4IIWyED3y1n1ab36z-5wYf2OVw6KEk8dGk4Y
Jn4I2fT07I6nne14dG89fGk8H1sXz2cHwbs4H6m2POJIbqILWaqi7Dl3A294DCAac0Y9u4LW9pE1CQzaVp8O7yAc4BWINWKIs0cpG0BAkmT_Wdqd8lG21eZm
JY034Gz41Awa40uC5eA839P2F22HXLlM2OXbmZCv0LFwUH_zwyldWhjP9yX3WeSX0dw8m4aS86BRh242VeZ0nI2_p-L6c9Nb-2dG8SiSgYR_zgY4JqTJdEkT
XJ0Z-aEcUUcbsE_xQeWD54DoTh5Xbrt7tsRVtnKteevt8-fuizds40kg8U61sR3BhZTybrtSOJUYZdSZwdYpsSQG4hWXKOEqOPTTRpXdlm4
}

EntityColoring(pouchdb)
!define pouchdb(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, pouchdb, pouchdb)
!define pouchdb(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, pouchdb, pouchdb)
!define pouchdbParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, pouchdb, pouchdb)
!define pouchdbParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, pouchdb, pouchdb)
