sprite $precursor [55x64/16z] {
xPPLWcGn24MBE27xt-vCEo5oK-tAJ-bvk5mMGY5nbTQQ2ET0bsk48aipmicT85UKwKcFePauWx4XoRI4Y1kMkbBefHqbJbHG2aWQgHEW7B1GECVWGqmim4wo
Ft9V6Nv8IXSNDf0RivcD8K-FJFstOHNbsbJAuzFwt6pAhxSqJ5_njjmxG-keh2g5z4NxMM23LAEEZD50d4b2LCSkM58VJ3Q9H4AYkQEDCgpEXurdsBkSXw8X
Toy4WydyzCwsNOKvb_gar_QT3CJGbQAfFsE-JHAkmDndO2_txOMHrBmD6CwRlgC1WrKorAHYk2P9tnwnf2eU-wtumJVSRtVTBTcDiP93TvFKg5q2C6S7-gEY
4rQ7GGamC2S11gOomC0E01ZSE6UCXlq6CRXDCKPWTmFCWKi1QHD00Ty4M0Wm1ZSNm0guy02MmJq9i3X0Pqm_rk5MFcEk97oPumxu8TWVzXy
}

EntityColoring(precursor)
!define precursor(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, precursor, precursor)
!define precursor(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, precursor, precursor)
!define precursorParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, precursor, precursor)
!define precursorParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, precursor, precursor)
