sprite $prerender [64x10/16z] {
dSl7WGK1209GH13xRtX_pgVP2URN7f44a4tXy3Fpygl_-hfv0oNr8rYGLDT0WLqISM_5X--BVdYkqeyWh1raL0fbnX5YbQCbW9fnuzsdebjODTAwUYXZCr2m
5ZnSehj__6Ok8USW8jc--PcyUMK77xvklXVd42wvtLYE4NTfk6OKNLjFvuBgxadUVFdI6Uho6AuoP9EwZjo0n-o62G1FtpT_zEat7nxt9m
}

EntityColoring(prerender)
!define prerender(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, prerender, prerender)
!define prerender(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, prerender, prerender)
!define prerenderParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, prerender, prerender)
!define prerenderParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, prerender, prerender)
