sprite $prerender_icon [64x48/16z] {
xSj50W8134FHr7l_2-E-ey6PlqqUDeb5v27Jwt1J7wiuRdh0z_bDWMqMEVIT1pxrdP18mhTPKhw2yytw_6qlf0VdmNbGNZ3mYdCJBx_b5x_unOiUiu7VQCQB
KbwKyyfv8Rr-k0_IE-TBWl8E3y8N08-nBy4cZw5FFNnyuiknQGq
}

EntityColoring(prerender_icon)
!define prerender_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, prerender_icon, prerender_icon)
!define prerender_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, prerender_icon, prerender_icon)
!define prerender_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, prerender_icon, prerender_icon)
!define prerender_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, prerender_icon, prerender_icon)
