sprite $prismic [64x17/16z] {
bP45jY1120C3j0Av_tMNiVrkrHvUZK9MicX6fdVy5N7cNhjZhktam0VKy15jzsPngJL8AyoIYlTa2ZxWgKzLdLEJ1xtpunkCYO_qTM-u6nUijzPwXbul852J
SnN3YTaTlxpFbN9rFe6wSGBekSbiaF1CsGvnqg57xBE6O6RPGKQyzaLFVp3xA5EIgyEpWju6hE9zZewLWk0OM_kBlmVoyjirqG5ur7utb3zgJ6YDbMZdkmwy
yXFMJry1OmVNvMCbGuv4Iz8y_SlZa7ZnjUFqPoaqUVoYSxppzQpMfFBVDxRJfpiTjvzeCJRjyEtsTmesmvEhJ_ptd-ytF9O0wtoR2TqP0xArXa5Mk_x_Z9XS
ZTCE81cFh_WjvGGFLgsZiv--uRSiJcszW7RJEE_SGl1R91XhJiDSQvCJVqNBeijc4GD_vHy
}

EntityColoring(prismic)
!define prismic(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, prismic, prismic)
!define prismic(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, prismic, prismic)
!define prismicParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, prismic, prismic)
!define prismicParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, prismic, prismic)
