sprite $prisma [53x64/16z] {
bPO7qkmm28DnJLnr_zE-PcRNZo7ypZTrAo0Xn_H46XYPtf7mbtU_SXD_cOvUKB2uw9m8Pj0v7SoBgIxWTIa_yINH6GrBkd03wASMBHhH5AKiYnRt6gw_iGY9
_o3IZmI0yKHqhpQFBHeV8SEvHUtJR3stw5flSACM5H_YzvroOD72VOMPPgcXB5rRbZroWzcdZtOO0pOkEYlLi17eg5J6nlwjpeNrHTteGjDXBYfJfAZPEakO
B1iVrg8oGVg7P2sgTahgOVJudww854sB53ErC2O8akP7a6y9l6P8ConIzVLIqW21R5_BVOVaVeY0Vx88cheoztu2jWvRxjts3vOEMXWZ1FAWKyBe1WGoSKeO
Ry3MGGlZXC0w43e73H8j13AC7G8PTIMCgdYPh59TLoBOZzR49IqTrDp78nraxikn3ZnDLvOY_NZLKau8R_scyu_4eazwmAVA-yFZgL7V2LUJ-vpDgBjOjh5x
sWEcw-1pdT_MM_Rx_K7L8TnzotE9JcwLZBfBTM_g2iO3j_BSVMkg9cy_sfkS-uu7LwaXvZQHUHmbkUFh8JSLw8mRFBTeokQQc6o6oMy
}

EntityColoring(prisma)
!define prisma(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, prisma, prisma)
!define prisma(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, prisma, prisma)
!define prismaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, prisma, prisma)
!define prismaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, prisma, prisma)
