sprite $promises [64x64/16z] {
xP853iGW50KJ-3xS_xhhxXRRCBMNbqu5Q3zXCfbC9fF9P3APYBjzQ6PwQyh8Z_ITgV2XBt3mUz-Lkt3Cz-YHKEbhNx8grZThLALjVirqLzxpQm0Z1OfrpDwC
3T7qfBo7EgIA0caEY42P9fWSIdtX_wkt5c01ilumwgIyx-l9-3K7ByWL1NOit_Dt-8T-gQYAY7xYx_w_MVXBlW1X9xvknZyO8Q_ulM3aRltx6DwS5OFif-Lz
n3DT8coLDKBNvwoqtaxBD-dj_rW2
}

EntityColoring(promises)
!define promises(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, promises, promises)
!define promises(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, promises, promises)
!define promisesParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, promises, promises)
!define promisesParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, promises, promises)
