sprite $protoio [64x17/16z] {
fP87eiGW24IbAJZtF-yMIFYzPhPcz2bjV2Tn6HTam2L-_eedSr_7FbdpyPr6yU4pRNSzjxlRuuUdkz7ppyPJQpoq06yZUI36SEGVJfxHIzWoQACq4yUYDcgJ
frqdDMyun0jm9WL0340VK1i6A0q1jf84OCrlm8WTY8rDbQfQxZWCAqDggJW_UJdotHsM03O1Vdfj5B_IpeDFNkl8AanVT_9jA62lxuzFx-zqYt-LFm7Gp5-8
0p1o9-hyQG41TBcBx_glQeWFHsa__orwMtySMfsel1e8VzF_vhl_Ee0mZnmtYneHAYEbll8xQkZSYI9g9CCdZIS_BkWopyilyNS
}

EntityColoring(protoio)
!define protoio(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, protoio, protoio)
!define protoio(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, protoio, protoio)
!define protoioParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, protoio, protoio)
!define protoioParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, protoio, protoio)
