sprite $protonet [64x15/16z] {
dP85Oa0X34DJISBzJxp2t3SUJlk-WasvSK_IooxS4MDlhCG5RQydpC0GcG7awP6LqstsF830Rf6PfqklLvmO9BdXwHCKnUcj3eakg142HKRHulhi9r9me0ad
mZWjfpKX7x_mbFg3Nv_y8gJUVaTywxD4c7HzTVzo2hJqlTy5k4byTVze_VhyWmF6L_UFy5lVt_jiK2qTVnhR1INQeCWugVIhhi2GZpqGqwhhQOMepZERbbKL
9_Nr_BbmHygZD-vfCt370m
}

EntityColoring(protonet)
!define protonet(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, protonet, protonet)
!define protonet(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, protonet, protonet)
!define protonetParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, protonet, protonet)
!define protonetParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, protonet, protonet)
