sprite $protactor [64x64/16z] {
fTPNmi9020JWOUcv_u7_8XPCNVsUR0o4jM473J6FoCnmKoRC8F78pdNW8duKTow4SnAvAvHEU-UX41mWorC-i6T4NX0oV-MTOelcPJPVtlcLSZSL2n7rE9r0
iWjZkftdRRFYXm4ZTjvfx2X3-si4JnIjD-E10m-axLK33xPxEiFQFT_S8Q-QxzAjHY-fGJWcxRMhtGTEQApE85uIBT0GzO4i86yhv7RVWb3OulshnwBjmFhL
CtuPtmzhUGgk_VTz1G4KBQrmBjthSTDhHzbQlIqhoHkdQ2_3Q2zV4ppaSkz9qTgtylq9PAa07klsikn8mbrMW4eMGg5SzdWRCN-vLNbxQXUZZEKM4Dx6x-tN
ukK2Ag3gnydLbu7Y_tSVzK7jYLsAehNIyZRO-GPvQG7U5dDX0UEp-aGPMO4L4By60B932e3YLrPWdP_HBrn4l-xzhUenYQfU-_MVwtiAVfpV7AxnQRQ-lqq5
jK2LEN5_FslUB9y8OEGN0Gh0lmWOxUThcUNjnty-WDkt-NH0hFzzJBPV_u3FNNtnJm9ojBzVqm6oz_TlQlfYim51-2OW2KtVOKxiRdA2TVbyG0niacl7w8GT
myy3Kd10uoJ01mwHnK50C4wHnaw0CouXjbW5X0vSHwmUZu0m8Mpx0G
}

EntityColoring(protactor)
!define protactor(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, protactor, protactor)
!define protactor(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, protactor, protactor)
!define protactorParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, protactor, protactor)
!define protactorParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, protactor, protactor)
