sprite $pusher [64x17/16z] {
dT875kCW34NHhuP0IDd_SiT0nfvUyj9rTDDiN4asV9uuQqxzKBDmP2ElmH_vkg3EgHn5k6fppb0W7E2fWCqC0JHuFQThk7BeMZIKPJLg6HbOZUe-Iv43a39e
3SyaM5tUYo4Lxgwm6XvrJMBaj4oZxNi1oBZzoFFu-3AizY2g9BI_oiactNxEs_SIGFatVYnlVRBCL1pFfEMtvomxwoRIjtSHMWDbgzX-Z78oElugwFRWgB7N
LzjVsNiGjFqv1ZZUJ8370rv1--Fu_VdCjBnfDMpVUPJZ-V_mU96rsdxz-oEFp-ViwKN71w2b-_-dybzxAprUyBNnzbwzPHAqXaN9sx-M7wqrtGEgsBxZpYTE
dXK2e6LD1NJUvrzU-Hdq59hR_o9w7l-KoTZ-yvf_Rhy
}

EntityColoring(pusher)
!define pusher(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, pusher, pusher)
!define pusher(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, pusher, pusher)
!define pusherParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, pusher, pusher)
!define pusherParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, pusher, pusher)
