sprite $pycharm [64x64/16z] {
nTO7bgim30LGgrYcsllVxH_awCIYmszlEeSRlL4QuIZ04SCc6Eu5MIG9RmxVynGNlNoYvqJN65YKYlvWpn4kDEfeIri1a7vowe6arLO1lfpmT6VRM0MW6hpO
sNuOqVp5plORC5dmUcVx_DY3IDB8GQW9mjRRd8D4RaC0Au_cSxcHd3CT-78px3tzPy_NFhlLYFSnVVt4dyXOB4D408n3iNJiVJD_R6hDPSb4TW17ynAXyRBl
0-RbG7lcQ5uYDZvv3_OqxqgPzHUgvrCs_nCo3juhArcMy-kgOT0j0CobyS9Vhn7pIJSE8K2PcjRpL9mN1lMuwmiklblMMomh_zaYcM_xwo-azOT3Bn7tV1p7
iGEz8RBw-rwtoDvRTDrymqSvUFpa-aZjDhwNo5N5iEC14Kbqx60F8vT4HAm4ztpwWgmdV5gJ7HSa8XiV93dl2m-wY7wQUWg1vfKdzPlvXy_Lhl7nCnxEVKah
Rfv5QEidHEoBoyXLyrHQJtLyGB5mhZihwynZtuzpATv7ygz-J2RFOvv3wvFWGu_-rPDV-bZ7H_mTduIUUr1lxPzwAs3jNtgmzYyyVBpobnvhU_Evypdpz7dr
4_pwAVZaQo_qsaC8NDkRBwFBTDuVGuXY_Dd-D8ldt_F6tta8qFZosAE-t5kYtChwQXZmOSZvpItG_I246e1NdZ1ONdlBYmQ8vhTh84HyWBThg7ySOmXxCGrD
fGqcXtShWF-thYUxym4sX_06jXXtWTtQlm
}

EntityColoring(pycharm)
!define pycharm(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, pycharm, pycharm)
!define pycharm(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, pycharm, pycharm)
!define pycharmParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, pycharm, pycharm)
!define pycharmParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, pycharm, pycharm)
