sprite $qt [64x48/16z] {
xPP7aiKm24H9pVrlF55bngXAOBETj_h1Jn9j9LgelsEeU-W3N_mrGzs7kWzr7-gklcFwW_aR87GXUAmhtJ1VO7qhiBiUYhLyh76hcQuwyCJ_SNWfu9XSuTVT
8ttj-vfciruIVdqqXczfF99IvM8nmWCc8au-dSjdJpuzysKh2DtnM_Wfm3A_y7Nt3-_ltw_pH_RxyqVQVipVVVwrVOxvdmU4ZYyfG8tlrl4jxHySNn5DLGMm
XHvvnivMRx-iNyXz0sPQy3c1XEu7GnbXrgEQsdVZlxxj1njx0Ko5MNZR3HrVU1VCRaOn6qvOFHkEEfKLC0vw-JBPYWAB2Cfyfl4ETHhe4n-q-0G
}

EntityColoring(qt)
!define qt(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, qt, qt)
!define qt(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, qt, qt)
!define qtParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, qt, qt)
!define qtParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, qt, qt)
