sprite $quarkus_icon [64x64/16z] {
fTS7ShOW40PWjmEs-v_sBsR52VD9MFAcupoKODlb2f2e1QBAi3nXjNXg3w0s5SLPxb7wxzMcex0iRB-8-EodWsGUHXWEaheIgIk9HSsXZxu4WyqwbcYqvncM
DXJnAKipNTMGBoNHKWDY5lMbr4Os2_ihrwwIsgmlML3CvlswxsNAkpxEyzpofD-Eyygnfh1txJbArA-xKy-UO_uusvI09z9c_2CHZtgGV2YcR-idthRC8nxO
h9pdnbIy1_zzBoLXtzzdQxd7_AztdylkPtJFurThyJMZxjUthotmC_hTW_XV-Tur9Pz4zQKaVlDirNkEnCVP-9BWRVuevlE_axNrcNl_Fz8VlC0F-ySzR_Zp
-GEYBpxHsFcBwPFVUFpytuxM7wiiuzvlFO_Vit74bxBkZz-BMSpx_UlonseMzjv3rcDBDk4zngvd_BNX8BC-kq2TyWhFtnhsJGl7V3tJyLOW0V_CNBHf7F8r
s1o9UZ6JNtXGCuLvBxxlCxvM1ZhjsQvGr3TrZNHyx_sPUvsZ7-kylwjvk3Fzz_g1pLCxXngwkGpLB_HQ9k9G_QG-lhMHmVeDw_dqBGg3zQDyB5gKHWjGXGyd
ZMApqvtu5jA7-dceVjUcrDPR_mK
}

EntityColoring(quarkus_icon)
!define quarkus_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, quarkus_icon, quarkus_icon)
!define quarkus_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, quarkus_icon, quarkus_icon)
!define quarkus_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, quarkus_icon, quarkus_icon)
!define quarkus_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, quarkus_icon, quarkus_icon)
