sprite $quora [64x18/16z] {
dP9NWWOX28EbAN3_0o_an-qzBumu7mHrbNX7PXYj_saNV4vawB_mamdGClV_kjkhGiIbccH2YTMal-YH4UblKLF1RcREu98PIwCIDg6JdgMeprCffreUx9QS
qTJ72LLAIQB12LtJcQmXjipeQb79v6KWexT6WHDmWEkWJANQfkECOCHpC_uWEC-tlB_bjOXxHGMWs3q3kFY1lzDPzo808xB4SlmJZV_FUHslbvUJOLZkU-Wk
yFUh_jZ3yd5_Ug82IdqvlmzGmdM0vFlioBCb0B4R5MW5SXqKF4tx3J1b7Y2XMjgTrK-seii4qsw06zXDu0EMuSvwUky5Bpgym9fbdAh7vxu_Vm0yPaCK-LBF
ZuwnlHso2k5685QTzmyX9qWHqngDAmpsNodUmX_r1
}

EntityColoring(quora)
!define quora(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, quora, quora)
!define quora(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, quora, quora)
!define quoraParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, quora, quora)
!define quoraParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, quora, quora)
