sprite $r_lang [64x48/16z] {
dPO94gD024NXitNF_GyyHPanCB5jarThblSHn8MkOQYvHyI8S3SLq6EWbc8Z8bmVPR3e4W5lP41kWV1TwKTWO-_X2nqY-fJF1BwsfT4csNN85G1pLY9EWFRJ
HWSlJX0-niXx-QeObZhJFMW1ifWjNrB6BNo4TPrUsBnaXE6V9P_xBdJwVrRCu2CWErZewQ-PyXA95dhwcu0KWERpndypcL8LKJjHfOrVC29DnOgFB_n19DPH
MlYk1r4R067Zrs4TUF7b1v_dEq29qt5xi_Lf_5zVp4yU-BFsB-Q6wcFdMri0TLSglg_Elm69U6a_A5KcyGAQ_sOUz0MMesChld7trmJngnuyJjosVZrwfKHR
m1D_6f56E1re59nt_Z0-T9obMe3S-f4_Sngfbu2UiAu_GpHgzKIYuSBL3pEV9M4SRLRWCGeH5dt_UDGHA7sWKHbH2gPFCek_U31Lekrl-IBH_VkB5ryIhIFW
pTEnr--9YUyUiDLtIO3H7m0tCCDR__naXDlxJnsX_U2ZZX1V-_q0uWSVSxC46v-yFKE_zp7x4lm5
}

EntityColoring(r_lang)
!define r_lang(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, r_lang, r_lang)
!define r_lang(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, r_lang, r_lang)
!define r_langParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, r_lang, r_lang)
!define r_langParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, r_lang, r_lang)
