sprite $rabbitmq_icon [64x64/16z] {
xTP3eaH144JHPCJ-L_pHAhIjFFFxM9BaMih0m1MuxDFo-G8ADhQtPmV3xTc9K_lggw---khz_9w-Ps4dzAIUwMlW0E6xcF0wmOzNIfj00LuY-tFP-J0jJESA
wO1dyxxFA-zV_Tdoolz7Qtdm0l1LhS7BO8MlevJaLI1vrTtr5m
}

EntityColoring(rabbitmq_icon)
!define rabbitmq_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, rabbitmq_icon, rabbitmq_icon)
!define rabbitmq_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, rabbitmq_icon, rabbitmq_icon)
!define rabbitmq_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, rabbitmq_icon, rabbitmq_icon)
!define rabbitmq_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, rabbitmq_icon, rabbitmq_icon)
