sprite $rabbitmq [64x11/16z] {
TT25aIGn40NH_50b_ps-K8oETxCPNeDsHTVSCZFXLMuEjp7SycuCaDPmZfZpxeeyVNu-lXyWPA25jwbH_BStQF_tVxmp0fJW0Ehp_ikd5UExTjs0qKn4BkEk
8u3gdEcURUlhDQMZ33FsugqcZDInYCfLeGA8pwzATxPWO9Z0s0jQHk_xYL3urs_t-iWhG9vBI5tWJsyJ_VRwUDDJnj3YQVOxVody-V-tyJplOVq8ZUS_xy2V
u_zwNdjzbnIjMD5UxtwyOmZKg6P_LMfWbDqMPZRWdO4APan01GAajny
}

EntityColoring(rabbitmq)
!define rabbitmq(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, rabbitmq, rabbitmq)
!define rabbitmq(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, rabbitmq, rabbitmq)
!define rabbitmqParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, rabbitmq, rabbitmq)
!define rabbitmqParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, rabbitmq, rabbitmq)
