sprite $raml [64x18/16z] {
bPC5aW0n3CFiMF__yl4sovdJG56UOfhIHcMhETOYkNOQ6Yzh1P1EXVPlS0TarQgNnU1BiA9owQlPhwm5f4vxCHbzxnUhurw2ym-_UW7aRnbCVl1DFR446dsJ
smQeKc--BJdWsyKK8Nhp0y2f6xg6NtqPwjnPxE_mtPUfdPaVUW7Mv2lSV8ge6NoJbypPt_-KDZBw3RndjaysEkW-bhsVR7xp2G
}

EntityColoring(raml)
!define raml(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, raml, raml)
!define raml(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, raml, raml)
!define ramlParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, raml, raml)
!define ramlParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, raml, raml)
