sprite $rancher [64x10/16z] {
bP75OKH134Cr9bdgl-1y2Emrxp1W1dnGvxaYyGzIFt3lSwC6HRA0mm6QWHp4BFDC8PXDSgvZ2aV-OVcygGQzgqP9WVMY5VB8hK6grykv3gdfNyJLTUK1g1CY
g2UMipGkv7KEohq2G27CBd_m-0COpogXwmIbRT41dBGaztet-Tg4FzXVVtcGod6GxNtzaThPsvyJjDnu_UMNaVO0e6DrdPARUsID6x7tcR_rX_Rrx_EG5Wit
r2cjcIdjegsGPztV_PkSrMdju_ywVJnh3feCNESqC7ps5n_xu_2sUPpoq_z_V04
}

EntityColoring(rancher)
!define rancher(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, rancher, rancher)
!define rancher(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, rancher, rancher)
!define rancherParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, rancher, rancher)
!define rancherParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, rancher, rancher)
