sprite $rancher_icon [64x30/16z] {
xSz5OiKm38JXiHBPchd_VKjAsLHQzNqxms_0dcReE1hs73pHuJ9igVBPj0KduaGJums6Ntr-83J5GdtasKL-OuxskG-KyjW1C6gkMMVk89LzQC5x_Ibbxrfn
L58It_LyL67KIXJOyS3V_TyU5A1fZKdl-kII8hIbrrEggD_lBHoxFVcfJvkzny_wuv_tvdhXN-fvDHuNnw2dbPxSuVO8gTytTDdhErXcVPts-el-rXjreQ6l
3Mwu1m
}

EntityColoring(rancher_icon)
!define rancher_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, rancher_icon, rancher_icon)
!define rancher_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, rancher_icon, rancher_icon)
!define rancher_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, rancher_icon, rancher_icon)
!define rancher_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, rancher_icon, rancher_icon)
