sprite $raphael [64x64/16z] {
dPQ7iYeg34MnX8IK___TvmE3kaTpXxDFjQn5GXlRxrpxC7TJlhK_v3PyH-cKleX_HCzgk9b3ZFw2noDfe7FSz17pIC4PRi8pebd14QwyCr9mYfyB4ZV-2BHG
uZF2dt4KrBWnH0C49HwA_F0CLNXc82yEWWAl-1JKU9IyKu7_wZ_cgg00yHq1tjOXP1GWdj4lvOSI212tNmMi5vX00BXeV1TOk7iO4GW0fzKbhg5OF8S70U3t
lhYim8OyCYpNTE4ek2HE97ESRYdOtMJr89YNgcoSvY8RQNA8ey0khTrV-0H3xn98Xw_YKS2jpMvZucIppNk7wYEC2SBF0gwvCHxfgTA9gZtlRqMQibVl_Mrb
EF_dMFzq5k5EtsDpZ5c-lTVKin6Z8bc0xPNDvTl_XPGyl-P7a5_5MSqxyBdyMnLQyw_waSyba7_ockC0tpqNevw_d7FaII85vVhTycWXJreBvBc1DT-rvpzZ
uJ_d8FkxDif6SqNxworBCBxXIowjDTs2d8iCBq4O_y3z-dRzy3ftmOG2nnCap-Tx-p_aMS7UJ3XEk4dMrUTrcDL_23Hmq-sxAC9DnoFcyS91i7SzrheIC-w0
fo3JOQuq3Hd0GH1240O3u23uTkhwR3i2S1100w2GeMQ0em0RG8Tjl1BOBzu2S13K1NJ0Ymhw6Ow2q5CSAv1J70LyZAFW64V1AOw2aJWxudNwuiC6FpAAJLiB
F6B-dE5u7npWnUTPQcUvz7U3N4_OD8oyl0lwFm
}

EntityColoring(raphael)
!define raphael(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, raphael, raphael)
!define raphael(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, raphael, raphael)
!define raphaelParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, raphael, raphael)
!define raphaelParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, raphael, raphael)
