sprite $raspberry_pi [50x64/16z] {
ZPK7bXiv34Ifn8JmxtzQsoCcIAzttvGz2OsF8aYmbQOUBp71MdlSKj3jNfiWflcPebvTs78vJ7EsjETLfWg0YbHfAkwRQOuZrgGr7Jdj_XClk4kfDPUtQXMm
7qJ0QXlHN5ffxlH1IFbKwqXA5MkrVAWEekBbMyhpZfVy6SsAfBTvdyk9nQJI0r27kTjxex0wehs5QiSvxmTA_I6UsChikXfje7dcYontfQGVANrNKnjxLa7o
Uu_4jdDrlx-9WfMjxX8ySdCz_Gio1mHlcyZLlUPYGCr5O_jLMQTUiH9aT0FmRZzmYHPJTxn7H9dw09hnIalPaVCiooR2wJN8PwHJmQNkJbWATRhHqzPzkDGv
Sav0vaurgBS8fFHqi5fRDuXoQRKeKE8zImlPCXNHmCuUeaLwERYfAc0oPU1cve2Nu_2so3iFLBOKwnEbVNQnynoN85jne4GBmnQ0HK89oFrOP7m3yEcn48EM
jWGxG6p4mj_Wftb_1vMXkMbgpfJDSe_TF2p0JSqE-IuqUpFE93vWhCWrBWOxxRkA1k853eHzzG1CUtUe4rZpuN8KzooqcBU3xIq9yo513hxcyUxOnSbTdgJ3
CwMEZvfwHMp1-6xf0JD3_fVmbPOR5edOnmKXe8REZAy4q0l2WKj2uSi4bZURjIyBeecUoewkb6yW8c4S5PiHF0Bk3bYChAiuZYECgerVPjHKTLgEnVLnDvme
3SiBidb7CgXT0X5nLKDzt5nXcE-7tziSkXuVzCyLKQ95DD5DbtdBYO_bGnPgi6vwFrb-HMnJi7rfPUc2yF2mXfTFB1dboDPv_IWMebzxvV7tsoHg27-DPBIq
-5aRbnKHXqW_qrA5U6HnheWTfIE5I03k31t0xu6u6-7r7XJEsvyfwYQ0cNbyjvlFaJC7UwGlPGjJlNJ6St-QHzMhIUIj7lAZdXfQZLkNqt-gVB_PY0kwrij0
WuFda7-jcuBhQbiVwHUgpfI-qkzqRmPOkwx_5m
}

EntityColoring(raspberry_pi)
!define raspberry_pi(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, raspberry_pi, raspberry_pi)
!define raspberry_pi(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, raspberry_pi, raspberry_pi)
!define raspberry_piParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, raspberry_pi, raspberry_pi)
!define raspberry_piParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, raspberry_pi, raspberry_pi)
