sprite $react_spring [64x64/16z] {
xPG5qkKW48G7j-c-_t5tWQBuDRoio-iIOb_6Htw6ddhgAPVCz-0PzElQfjRyBTfKKjTr0ibs1xUDX9lNNiccjtW74dvU9r231-DjVCLHZ9dcx-DEYIYczM0U
L8WzNZUlGNK3VppxZKGs4wybsu47ULYb6vyoinGRDpv5Ut2VEh0b3oxdRGRPNr_8udMe4Mnsqrf0T-rzbYrJo6BMZzY2HC9SbkwbUtvKRyXWN3emoOKgupQU
iLCfgPY1r-leTIUo6t_NM6gl-3YZToA-aSM-ASq9bmBVyHeRMT-sN3hYKXd4UYNnZfP2rfw2qi9xS7i8a2ZkeuMGlnu5bviaDGKHFlnn70V9V1ZUCYxUj55p
ur0S6hY-V-zrJAHJCkV3A8TtxqsU4SL-XDCUqxSD5fIiLYIJpOP3y1BUB2fNIGqoy6eYM4uDiCtFQirTbBhXVBBUtGyhQkiwNPrCwz5KCXrmetIhsu3Hmsk3
hLa-sU-4yGMxXuqIAPFgvAX2JRc29BBR2xdD3ZZBDdPMkHETsALU7bD8ALWFBEiMv3H-GvwOW8rAebYv9mj4vtoQcOXoMuLJgAcfb_kAjRMQWvK_LayzzTGN
}

EntityColoring(react_spring)
!define react_spring(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, react_spring, react_spring)
!define react_spring(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, react_spring, react_spring)
!define react_springParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, react_spring, react_spring)
!define react_springParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, react_spring, react_spring)
