sprite $reactivex [64x62/16z] {
dPO7bXiX38Obgkhzhvl5upV1e6TZVybsVdKA11HYffRXDx3B0-u9Vc78BpWZ8dn9amd-WtfDNybtc0-hWKCUmnK_YNDbsJYqK8atyGONY46ICpeULos6C-nW
6Ffv3edb7Au_w8c32CxrRLworo39LthXfGj5ZkE_w77vpycGuk5Hkz0FyK3DU_7K_3zcxvg8IJQv-OA-Iq0x32XqFj2Ui934L133kVIwgANUXsdidxq1G8tb
rk0cDmxg1-Goz67kafQJfRr4mHs7VYIGEP0pHgTJQPt-wAqy_inkUNpPesSuGIvzszmhmWbwwVFgtWgSa6pado6jxXcEQ3xgpvlUCXocxnsoFGR89mIEmyyW
3hIat-28FZnLyxQKxp1yDFUAwivh-dZgNf7TdHQzdcRljO_bcN_HYxiCkHEq7_HjBFH10QIlyoysZphIYpuT9V-aFteXFb4_odLrrdo2pkHcb_i1sldkpG-v
aSvB-JY1QcucjSZBg5PVEuW88RcKZ5SGLW7mMUrj1nLwaqQtvmcTvQalQmkJC49CKR-yOpU2g0A20AoSGlKrRPgWwZGiQJt2YghaBVl-R5vFTNpNvy8k5m2f
olzM8EPA-boZHBQrcfOB24LLxoesc-nRU52pprWjmu3K8BvuKb7y1M4Ty7LRBTjiFsXt0suw46u91gc9sjoa3TeCt1TkBIMNnhTUKpnPkmNzOxjZ1TyCrng2
3aIt2pu2QG_XOK8iV9p44ngPk7-x3VQ11R_dHojyfh1vX4c5Cx2osff5pt3CzUeIUsg5QfZsFm
}

EntityColoring(reactivex)
!define reactivex(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, reactivex, reactivex)
!define reactivex(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, reactivex, reactivex)
!define reactivexParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, reactivex, reactivex)
!define reactivexParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, reactivex, reactivex)
