sprite $react_router [64x35/16z] {
fPLPjiCW28QT5RIo_zLsBeLpGwx7_g_aOoQwCyM67OjtcohzAOox-5iOTl3GMMqpF6idWIRu_2DVD_WiUDZWlU3H_PX0sdA0p6FsgscdaZ_Z2WM-Bg2ralxr
KYSHJVJiBeGeDW7BEOxqqaK52hYuYuK-wcOhppAu42kQi_Gc7kchgkjQccKIlAuJ19ytuai-hTLlvkzN-gytFgpU8hpneO9uaJwShs1vb335Hpv4UGVrBvvW
3FYM6pDlkSyDaL5ebIsXzO55hYmSZ5DqJRy2PRwg38mVE4ZcqcRYCodMn9mtP-OdCpY81Ql_lqo76fgltJhQjiGtMRx9Yur5-_s9sYBuIgoa-M2LB_lNtT3X
TGEC1vo3pk3yODnmW28ntO7vjDH1D8exK88xNiEHfK-wjBlb1W
}

EntityColoring(react_router)
!define react_router(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, react_router, react_router)
!define react_router(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, react_router, react_router)
!define react_routerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, react_router, react_router)
!define react_routerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, react_router, react_router)
