sprite $react_query_icon [64x58/16z] {
fPU9ieEu3WNPOosd__zltviXhW3sXRbBrwvAOwIIXJ8qB9vAVqr3or92YcrufeWTsTGyLk-uJq-w2MMc0BsEy6G2b1B4UAylGbR-mVDyr9f0UYd54igzxxk-
uu9SFZd9Qpp9smmcaUL3WjPX65qeFb57syFhUpa8q3ebw1mLTkTlmie95nBa9PZ4dVywqZ-AG9OBGOvFVlS0_uDV76JVzsdz4f3VzLVrVac8RzPl5buwaaiq
yOV-YTutNKeWNiCTILxCdG1qnAJrgVzBAUOUcTgX4gV-dMxzGhsaFVwVvHkNafn8juhho438bh6tvv82K8Px03vF7vQaPk00oZArKq_LVHS9SfvEhAeP14Y0
R3xioGLAjr99U4qNh6OWiXHFdIVaAb3OfUbZkh9epy3hQrWASgstlhtYWdLgU86ivAUEbdN4BaBUtZcVMkQ4316NwR8DOxPw4LgcZWq0sRMnvwthUOSoVK40
JNyB3rIwu-Ul_5MqmoYHo7ANVLy1TR_j_7poenjExViRrFBr1UnIJRI9R8u7--hu-Efu6wvX4u3Mtd_rsOkSXZdFxHUG2V6Dx4FlJ-6Sf_ONAaMmjNuvZh_q
Rxr-zGa6yNwnkRy_VjYUm348rwmNEDyDcbqBEkH73hMRpBYzO_KbhRq2MnsXPf5YjvTkyP8uZQauFM1DG94ITNxDGy-q1TYnV4HKKfnGMUxdjqvzq2EboFi5
B4v5gaObCy9jZsl-rlSl0TdEzSu_xa-N3oLPUaIvtv-QyKJqVkAFvJjmkj7ul3zujwgWVg4Xl-kN15dlZz_rJI3xlH_ma_tDKAkhIo7kwxSXQoR4EZhec_lN
t7pUoANRt-rf_mfan-74j4VB-GCTQBxrrxhgMGXKnYECqkhGjE4U0sLAG2xDWe8o1Jaz-6EzzyhN-FN_jvY7HzOGyctiY_lo25_RyFy1
}

EntityColoring(react_query_icon)
!define react_query_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, react_query_icon, react_query_icon)
!define react_query_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, react_query_icon, react_query_icon)
!define react_query_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, react_query_icon, react_query_icon)
!define react_query_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, react_query_icon, react_query_icon)
