sprite $react_styleguidist [64x44/16z] {
fPQBShGw38DX8R9iAU__kcSDJ0__T7jNhvlaivCWUrW-rZhASuhRyYl1KvLPdlMB26lD2XoY9dw19zvKFmwGZTy3x3_2zzxyNTAF-3B_vMEE7-0FryK7Bgb-
m8-P5qzUV7hzFX_cnKTSFFtuFi-BlodczZVUF-Q39nbVy_lsCK--uX_xUbzlSJm-sF-x_8z1sRpP9IDbAnvVd_yHPQiYRuO8zOeiERxYmwhiETtohz9vo7Ij
TvxnBx-MyvoGxdvQ8HSnGDNwcf_RMrsmhFWVts9V-xUS0Csx_u2x_w9nMl6CjMxOhytBBZo7TYSYlIsRYyG_KdLPPI3zn3QaBJsEz0vcoUPZCq6nsqSnS5Cr
HH7XxK5RbOJsCpy744oP5AAqTlkohX0TtKS3KmN4iB9d1g-IX3FG8T9sW7tJKjdJbZmxrB5f9s0x6mRIM4wDwcIToPEWi6pUT-sSghAtoaNvN2OYvlK4P8tR
yzj32aGwGSMJttPlOyOOqbArgDfbHCuCXCpzikeMP3m5b0EiGbGkgsjTLnb0TkSRlTTKe8e8Twe8ah59b-nf19jN0qfFuYdDAbURfmAL0K_xVog3frApmCC1
QtjXcZYKdjathGna7q5v8K670wU2CeA1T9_D8Yw5qNVaFAOjlY7YGgkL7S09NWzmlV5m73uZWaXd0AcMiuq_de84HBbNy7WoSk8I3_ViPaTt4IYZgUrUmZb0
4yrtkcZVP6QrWpeWT4mwCV95CzyT20dzEtkv3_9qNmUa0W7rR-_BUsKDv2GYIiT70g4245MN-y7PwMjveSszqht8uwnLZAg1iwQ74wTrqEbVwBW1cHqbh-kt
-pVbT4NZn4WjBpLqcE0ecYb6WtRY77MLpb7XDRyghpxmLll6yEcjag-wxx9_hU66pi9uQrefj8x1kCpuaIZSTVJYjHIuIRbyh3Hl7JUFZQxfl0z-yUQWZEEy
j_uovE8nAiTNhpxqjATht6zfr3dATxxz3m
}

EntityColoring(react_styleguidist)
!define react_styleguidist(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, react_styleguidist, react_styleguidist)
!define react_styleguidist(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, react_styleguidist, react_styleguidist)
!define react_styleguidistParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, react_styleguidist, react_styleguidist)
!define react_styleguidistParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, react_styleguidist, react_styleguidist)
