sprite $react_query [64x13/16z] {
dP87iXqW30Dbgcpf_kSDJa_-rBS3I-y0I35mbVYCMSm7S-4ZLf8KcHiVCIghBERiqYhfH-uFzpojCWDVsIdbtfdFNJIlX1WzSw0puVlohkj4rxp2ymD0t29h
ZZ4bvktnWUiZSyXQJqNxu3fmV8LJewnPieaZaPdZaJrHO5joYSThhwhKpYqEKC1o2aVKKghMzH1Pb7hz8fEzFkLbbMx9pm1qWEjnq-pnwLBg89mUsA_0jLAg
WnuVqqTSc_wnVgrUVphjtDvLr3gZ9qxNZ_UNwx7mM0faRPbJLZvbq1iuia-KLQtHYotld--l_Ft-WOuHUF5FkHLxFdVXHy1s_1YVLP_yFruqfOoWAl01tm
}

EntityColoring(react_query)
!define react_query(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, react_query, react_query)
!define react_query(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, react_query, react_query)
!define react_queryParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, react_query, react_query)
!define react_queryParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, react_query, react_query)
