sprite $reapp [48x64/16z] {
xTP5SW0W44JHiS_zRnmN25Bfo8vUly9bx2sUnJeLDYK1sZfCFdexUvyQRwSWyXgvJ_my_FhZvbqRVPem72Pkd3JHKy-2mPyEGhoEX9wdTrcFcyFSnc7FthUy
siflUQ1vckH3zDaqNwBdN_trrrz_FQelqQVeNVAKAHvCyU1R7eDN-Ai7Slh7Uz5d-iUzQ8VutFifc5OErHUl5cVj77vN--MVZfwI5eSqOUqfjszxo7Vz2
}

EntityColoring(reapp)
!define reapp(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, reapp, reapp)
!define reapp(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, reapp, reapp)
!define reappParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, reapp, reapp)
!define reappParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, reapp, reapp)
