sprite $reddit_icon [64x64/16z] {
fPS7akKW44Ff977_2s_UiVKD1cfUfGd87Tm8t2QOPv7z5oGoh9rW2NO5wRlgG1_2j1srH3vzWhE_mdojk_eIs7bm9MQLzqrgAC--3GRowWVWFBg2HUs7FV0z
4Vk5309VD1x5lo6zEVeNlkYTnF74tunnFNWl-sYLRgErATdFiFOdM4NxWyc_rhtdLqH_BAwDy6WfhnoIs_hLvzLSk0MUGu1NlR--Msd84BF5Liw-RDyShDAl
z-Up6L__7ujzxJwLLlYVkJEFcYQPEHQdDy4cXm9ATU3Vh0Su_Yo02lXfpOvi4np-C7c-k-A9qthRXUDtkKqjBTKpvDVmPG7yMC3BT226A_4vgjyreVmyzhZe
Vsf24CVNyZ4wccEaps7tSdWoKtxpkrkgOJ26UYlUXpX8U1lfozJiDd2DY7uumQ4EdASZ20teXmNe-limoCnLYWWINWwG76w2wWZxhwwhikTgTT2wtqE9Al1U
LmnsV4uk9fuWILJ8O4luPmATldizzSbsBXlAarqewQbG_eYjQlK76nuVTfb_eZ-8zVMF1C2T2s3rGzWK7CeVBSQvNC4tv6SzWCYFx_3rhGyWnk7HEf_jyqyu
U5jYnNEr4k1JdDOEy0GlRSLC_1C
}

EntityColoring(reddit_icon)
!define reddit_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, reddit_icon, reddit_icon)
!define reddit_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, reddit_icon, reddit_icon)
!define reddit_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, reddit_icon, reddit_icon)
!define reddit_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, reddit_icon, reddit_icon)
