sprite $reddit [64x22/16z] {
fPG7bWCX2405AJRs_iTT77ccTrB0lFdIavPaqL9K2D8tGbf2b3wdGSgPA7oAX_DlBzZUXKIod_GZdBPZOi84Rd1w82nBvpCNkldihf6d1G_uFfOk1Y2qhjgu
daNoYE_Xqu2dbyOxU-MCB76GU1xGlt1-BTqc3mZEeqf2AqVuJ8m1k5bSfiszc0bKiy4f7NeuhwwxOI8WSxFSr9kZ04vNmMP5X-NK_33-kkDDcXc0ARZD4IrA
ZgyptY-c-ONMyjGmkfkp3fCl2KoF-9sYMRCyEuSHl_CuenqkDev3gfsCNSlYP_uI_OQ9OCo3HfCcN_sef0_uU3nuY7cWpPE9c-JwFFvsua5N04Wv4yOumexV
7otIZPO-wbUvsUO3aDs_ikTNEgJLDzFeNwj7MwnrI5qy7jdxeqp4Sh60eJ13wFWvpZjfBPU2F_q1QE3VxN1XI5y8aAmL_9Z-1m
}

EntityColoring(reddit)
!define reddit(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, reddit, reddit)
!define reddit(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, reddit, reddit)
!define redditParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, reddit, reddit)
!define redditParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, reddit, reddit)
