sprite $redhat [64x15/16z] {
dT17WeKm30DGfTXEuc3T_xPqXbb-7cNd9knIisAZLNoaVkeLdtI_2Jue_kWufRh9UCcj0BNY-5ronixyJy91kUluqwX8321591o41XHjCVrHxlgf6YoG9W2o
sZZg5m1RVR6cA8EkUtJauZUzwpimAOFaG0sIvtmHPHHkHkV6DmiPJuTyrJE2q-ZYb4dDv_n3xEa4ix7dSJNOMso2BcVzucHktFLO03ldcncZU0IPX7PbFuEN
SA_N_frDEAjAcfJylhzJIp0fUqRrqn9ndT6l-aoMGTBVzsFxKHaBcGf9e7J_Rno1Lw3gdhzb89k9Pa0LnwystVwePjZ8yBU6NwNQ_D4pFiZInb6j2RzO0G
}

EntityColoring(redhat)
!define redhat(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, redhat, redhat)
!define redhat(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, redhat, redhat)
!define redhatParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, redhat, redhat)
!define redhatParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, redhat, redhat)
