sprite $redhat_icon [64x49/16z] {
fTPL0lCW40JWnM47kVzfVw7UGgRolLLsWcmIPC4u9sTHDNiZ7_4AQ9X52Vzfzf-KOz8KGi65HYjlAbZIx3wu_5BnmcKSo5O8epYYWTG7484Ddr0Z1wo2yMJu
J2ARpnGoV4OD6JxZP4i1BigERm2NPKT7nNSBO9oFAO_H0SxA8nlBd7WRYm3QmYRDubc_260TP0iksfWgYBBfk3fE6WYxwPW-9Zg4i6duEYxwKK8jkuvhuvs4
rfrS0Ck0gQqZwXZ8bmGz2XXz4T7c-cYKAItIntF6BQIswmuLExSVpseVAxtVlf_rKBjvOBR1L5m3hEBZX7xVY1uBjR7BtnubSRVBhFpIoGbhzJvYtLX9RYCW
6Sk6K9c2uaYjjVrJ5_qe9qxn7Jap-PTwFWTUBpRXOohtN071taMU9B1N2K_WXncN5GHv4zfOVYYVN6A3q2Z7tFcr-CDnrlXrHebMkDkhFTzIjAHmL_mN
}

EntityColoring(redhat_icon)
!define redhat_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, redhat_icon, redhat_icon)
!define redhat_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, redhat_icon, redhat_icon)
!define redhat_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, redhat_icon, redhat_icon)
!define redhat_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, redhat_icon, redhat_icon)
