sprite $redux [64x61/16z] {
bLPNWeKm25n2zVu7tfgLE28gVmyVC4ne7vT2Oh5jMnZJntiPjkqIIc-jVJkAl3ANxIJ-0e9EsCQ3Q8Y_TF2NkJDau_GYUl1PPu_CkOobJqcatpUdCgcWXycF
ok-Z3CQFkLw-wNWIFkfF0PuheOOcGTVzVse0tDjxXz6wZqdow2h3RsidUdAeBTt-ZG5TcNwoJsCW0K1W5u1ixw8Krf1R-uHIXQCR-eEE4yX_HENH3AMatpUK
CBdpCT0UnVbfV0FBHwESSaRmVyJnBIpcwK7wygLr1iV8Qj3OVJufCFP8iB2JjAhzoLfB4Ud5DY6FjaCHGm2o-0KkqA6bS2GpY_acMG2za0C2YabAZgXUzEZ0
Tqwj6G2ioWS7llxGcm54kKDXdutSZMK2-M5brtSEVQftlzvT5Bnovl_XALi00K0_wM5FZwmPN62z_SHjQyyb6-7OfepufueuVMOahAySA0ugiMov151Kk6BV
p6eFJ5VWv5lfvlEuYSG4JDb9IqrD051WXK41d9HC3-ZFADTTueS439BV-Ce-g71WYDFgdgXsAZ7JgVEkZYLmVJTjy5YYcxEE0yZ4WyxRcQdm5bXezFTUqWQF
mZp7ZgC3N3TEtPqzNzUejBvQA6EMHA8CNGjEV5e7JmMTrvX0oOQfV8jwRDa4UJegqrzr62voylvOq5tpsx2JL60QnML95gIu8jXY-MnCnSTqJIMfh6QcobHz
dBI4oOhy2m
}

EntityColoring(redux)
!define redux(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, redux, redux)
!define redux(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, redux, redux)
!define reduxParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, redux, redux)
!define reduxParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, redux, redux)
