sprite $relay [64x38/16z] {
lTH7TY11309GePRW_YUUSOwu7ev_sm4gLbKlnQk-QdI7g2zPwJi_Q3sPByS_s8EvK0wLekqdvOXpFlTZbF_1w0dhf5VI7WgmwsnjWQPk1JiGbCnBM4eqwQxg
be5kX7jbA-VpStxyYNp-SrZ5zN7jMwJIU2nbiIlGbCNDqkcFqeNyGZaa9UsdlcuEv_WlzdXS7_X6FeOa1txyYDRORwXMC03g0V6LzR_qP7qtSW_qWjz1kVpy
US7vp_jx-Vnv-Vfv-Vx93IKDglu3
}

EntityColoring(relay)
!define relay(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, relay, relay)
!define relay(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, relay, relay)
!define relayParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, relay, relay)
!define relayParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, relay, relay)
