sprite $release [56x64/16z] {
dPPLOWGn34F34xJlVzf25bHoQgz-YYzhMGDoai8WdiaPvIlDaZkrOCBoek8-b2PTUYfEglx-VQ6LbICs6k7xZr61NRH-R2CEVBoWRKYqUzfzyy8KCvrsBpe9
dVhVcHIYRBE0tGiIC_7jrnI2an55rzhDfKMNxHB42KfXkd3O_I6JDAPxGMrdPXfp_tjWpYxgxavaaLsW3yxbdRcEkdRsc_jGMNHfo48xXCqzbaj54Tt7wGyE
Sw_pTGqtu3RP3fTR7DWUE0Gwea1r_07Sjt_u5Kh0e-at1nkFWM0SuyiSulmQc8Axn_arC0M7fsX1O0eEhfPtiu7A4dUMfwJbKd5GvANbwlngcBc-mdLcZYzm
wuERTYxmfugPovkZOEKgRtKhD_ccRECytRdbJLpaXvg9A_nKid0TtF86RZ6Kz5m0DQ9XplIWPdeSDCP_75B78wDIb0i1kB6fwl64AovEkcGEgUFul2YZbXou
26DeUMYE8bTmBluLXuXSz79ZGbNypSaD3QL9vaAdvazL4PocP68GS9h62-FWb2KJzHsSlcJ6NVJ0eU0hgs8TbfA9J7ombypGgAU8MgnNcio7tRy3
}

EntityColoring(release)
!define release(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, release, release)
!define release(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, release, release)
!define releaseParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, release, release)
!define releaseParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, release, release)
