sprite $rethinkdb [64x10/16z] {
LOy7WiKW24IfAipU_xmx6dyZZV9UL6Ee_4G0TXBDTq-1fxZyEsamrliFFfcEwq-4l0SOnoBTA3zYOx8nD3cxaLkDw-jRPtwPGAWNNFmHJnzBn5TFuQG6cLoL
eciQ7rz5n3OtIS1PK52GUFnaQfZPonPcqE_Pe8lWWra8CJ9L-VXIJNTbBNw0yske3ZnR3pA-7Jv-_Zt85MdvzhkwN36Jc2mqu-NRTUFmUlp6n-yw-vV2_bHl
NuMHtxxz-3aGrmzAnsSBKnr3Wu_vdfXkSDTvdbJ_8qEkuRkst3kXoAJEwGjJ9i2tDcjcqQnmy-ANjJjpC3hbWDr3_m4
}

EntityColoring(rethinkdb)
!define rethinkdb(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, rethinkdb, rethinkdb)
!define rethinkdb(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, rethinkdb, rethinkdb)
!define rethinkdbParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, rethinkdb, rethinkdb)
!define rethinkdbParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, rethinkdb, rethinkdb)
