sprite $retool_icon [64x64/16z] {
xTV7ZKGn30DGEYUn_tQtWGK5UD9FxsmhdWIWJkF_R1PumgGo0hH9RK2gz6GeYvu1nUXPKEXv_dzqVyceMOGKQbDgm9KzOkkRQWIGZTki0ukl6E1h6bzZ_9d7
us5ypU1hal4bg7m9K8pRh088kROzDU7A7g5sfMN_jj8Qb4eNb7xg_w_t7usEXPSQi0HjKB42JnKjp0Jy0G
}

EntityColoring(retool_icon)
!define retool_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, retool_icon, retool_icon)
!define retool_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, retool_icon, retool_icon)
!define retool_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, retool_icon, retool_icon)
!define retool_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, retool_icon, retool_icon)
