sprite $rocky_linux [64x12/16z] {
dSu7ekCW303HKK42R8lxttOTdEtzJuhhGm0McM5yj5ltdja-pdVF0c9cmjVKlvwBx7--o_9B1lHLLLyDy_XwdW5O_69yJuzd0xr4peES0JQ6tZwoDxJBuqNL
qp71rC6pRuv4nlOjQemQrNNDeyyZoiR5_NsyzvX-s33wVPettXmaSk__MgUkHjIBCDSoRBMAppwZqM9xpaayt1NnFPyihRm7Ped8lAu9PvL0jZt_gvTZYkNc
cGAFfqQhAd-fFW-jGQmEvD5xlkVxpBCDzKay_Bs06AYXhe0RggX9B0N4tKtk4C5SHS7WpKFuNRsIFwHvv_m-KNxR9m
}

EntityColoring(rocky_linux)
!define rocky_linux(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, rocky_linux, rocky_linux)
!define rocky_linux(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, rocky_linux, rocky_linux)
!define rocky_linuxParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, rocky_linux, rocky_linux)
!define rocky_linuxParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, rocky_linux, rocky_linux)
