sprite $rocket_chat_icon [64x58/16z] {
lLVdmYGX21l09Fl-BtpTWy_Hs-4QVxOceoInN9S5ABqa8kpgbaDwpP8OJVm49yNeujUYD_2s8MWDmNS4dEncRriQIP350AXPnF0p3ruFAkNTj-0P1xQj7Sy8
pl8k-3O3pd-MDb_wMSC44XXV2-1A8smxU6wrUU031Us45uSzYPflnvyAxSf2sX0OvtVlenCRWWdNa_0R9eCixLDxydW8_31vj2ARusN2smJsypqRy2GOqxko
1ZfxfilKNR6gPlBuZk-1KmHWpYCzDYB_DJ88FeRVCYzEAvNEYDz1HgMfeCnToVmoV4irihKvNiKwWKMycC9EhZavhl_qBNwKRFW6hmM_ZZzKngpYKXoUpyKz
B7OOMbCYlmbuMmkKA-oGH9lFanHh_nLQmsDks_UN-ttDXoadqAanzKGxlTL-fJ6jGahBVe1JvY9a7wwedgDruFd8z7QdzNNArcc1Szq_EXeOjDbix27UKNUl
9ju6TJXZ-c9YS8JPklqdMiWVKq5MSqaI2G2y7pzYQsPCUFtpazDjrEaRtvo-x90b9jSHZ3XcIP42RR52s2-pv4KWZNbgUtT-zecf-j3o_6x_zFwmW_j_l3yv
fO9c_mfe0UeR5dtmzHa
}

EntityColoring(rocket_chat_icon)
!define rocket_chat_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, rocket_chat_icon, rocket_chat_icon)
!define rocket_chat_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, rocket_chat_icon, rocket_chat_icon)
!define rocket_chat_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, rocket_chat_icon, rocket_chat_icon)
!define rocket_chat_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, rocket_chat_icon, rocket_chat_icon)
