sprite $rocket_chat [64x11/16z] {
fOy5SYHH34Cbq-lxdtZBtd0ACseq2Fv0wGNayy0mPVs6M--eq1lQt-OmdTaVCIpPzsC5xorHxx-4tvk1WzGXRuF13MCLTA0k3QI6sXqmi-DTwW1ARtB9yjk5
lQDm13tgSU8foQJ2bAd4PfUmYEv0viAfUurwBjyvpt0n0-bMfdQf9j1Atb7V_4E5r9rO3fhJy-xPzpf-ZRKXlNk7e7Hy3Uy733Hjc5PJH09n_5rYHyl8YEoZ
ooSLznjN-gqERn6-dg-s74aEC6Nz2VFGUW7_
}

EntityColoring(rocket_chat)
!define rocket_chat(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, rocket_chat, rocket_chat)
!define rocket_chat(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, rocket_chat, rocket_chat)
!define rocket_chatParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, rocket_chat, rocket_chat)
!define rocket_chatParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, rocket_chat, rocket_chat)
