sprite $rollbar [64x14/16z] {
dOy5iXqn30H7ij2Z-vytwyVXvFUYfwe5-40jAl15n28iywl-IXEuQm3I5-LuKUrNjbQtu3Uu2oGCSlmPSbXuifb2cf7wEpqjeWntdnEhXWheqkFForS1dh48
H76m2bE4FdqQRisIPCc7lyc0Nc-se5cR03HBSU4lVpht4764oRT_ssj9P-nRFDp0oXKunDiV3Wrx0avAFtsQ754zzpJsR07qdF53_whP4791INtxWfvKikz-
04Y1PnnI0NtiBvn0JrlD_jX_6UbvkVNqpU6XDqAnKW4PEfBKnSSU_DX_8wyNZyy0GiDnnzLI04ZcEY_3gbq6H9fagaJl3e5SgMUS6AZpkdEo_wOgdvJZ__a6
}

EntityColoring(rollbar)
!define rollbar(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, rollbar, rollbar)
!define rollbar(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, rollbar, rollbar)
!define rollbarParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, rollbar, rollbar)
!define rollbarParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, rollbar, rollbar)
