sprite $rome_icon [64x64/16z] {
xPI5iYKX34IxiH78_t_kwhmR6khw-iuf7JaHg0JNO8WN0l4iZ0BVz0EUHNqyJNWrFKkjQIY0GAfr2G_OIpEpHY1e-cfcRRqNuOlzZG90qcVxHbk8wwHg1rLE
081_ITUJcvC1zjsRirxfV3D72W2mMySUC1Eg2GdW9NqqeSOhkle0lm1ClhLuHsyBX59l1k2kzMLY90-_41sRnCwN4Vu6UKIG6dOunJes-lZh0k1g7TvXQEOK
jNK3b3OVWLvkbjcRPZ2rkOCqw8nNu10WunjLYbTTePvL7TDlipu7MBi2jFl6MPy3iEgGDAa-tW50jWiHMEQHSm8vlf6ALs3lqtDUccDGzWNKhln6_PDmvbru
E279uKVdwZQNAyYBR2pLUwG0JxfkNagV9M20_ITlUgzz-zVJ3z_SQltjNKq_RlFT9lQ7VRxay-VuwOFuZ1zZEe3pXE-ywwy7Mtd6B-i7l-Vyjx_SF_tJF_tJ
F_tF
}

EntityColoring(rome_icon)
!define rome_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, rome_icon, rome_icon)
!define rome_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, rome_icon, rome_icon)
!define rome_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, rome_icon, rome_icon)
!define rome_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, rome_icon, rome_icon)
