sprite $rsa [64x32/16z] {
tPHPTiCW34K5chl_1RVaEN8uHvd_-hwCnDLamEDB_Nod_yRdjbXwYK-U46kKImOHZGaBfCpQyeDAajXAfJCaLZq_bYu1biLNRXQPW_XC3tVFH_ufvCZ0H3Cl
BiEUiyhiUPYJYHG6W--KeHszpwD6WK5ontCIgHADV9HVa41Mfx55yDLQ4Whh-SnLerUlKsz2C17NO3hUcHV5y32wdNRpynnLUCyZ9-TXSrxhIdVjV293Lx-X
kLAwL45hYrx_GdGy9Yn5r_-aEB2yxfMMhnwXqsLRQ4Mazl_9QhVZ_Qmw2PrqVFtU5BZGxlxRP4souslAA4JDJJ2_gCbMbnrVOyv1fP6L4iegflXPRiFEr7dG
aXLrEyd5BsMUqO_l33SppyqOKSkDVrNCNxs_GHJVy48aN_3T-_cw-lVpTVNlvwlgtyzV
}

EntityColoring(rsa)
!define rsa(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, rsa, rsa)
!define rsa(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, rsa, rsa)
!define rsaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, rsa, rsa)
!define rsaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, rsa, rsa)
