sprite $rubocop [54x64/16z] {
lTO74fqm30HG6N2LfRt_QTEZ-PWca_Ac_SBEcYuwi-Oc0gXmZGkvh4KKCCefF6TOCP9ydmjLSKOYNTi4L-fbNLPSwmkTAhWbwsaJ7iX9MyIZ7cYmA9vL6Z0y
8kqak4YW3q7WayUg-R8EhqXcLNWncG8t3SDXdrnYKFWLkovaGYKJ_AogSlTh6tstAQPefcy4atGXsZ0j4qLCAszJ5TCu5BnWpsUL_aomrviBuvCsfrsRDAV-
FcMukR1YHzYX_mu9taXueL71DFw_r_o6QVdj4s3-QPFekwNmX6gZGCZV1RgtvM_6Dv6kTA_YctwLYcad1a-gOT0SgOA3-fnYQ4aV2i3FAQgPTd8bH-g4CxN6
Q0VGb26r_4XjzdtJSKwpBXvIIFPLnkF-GnzI9BjoFXsTDXi1TkLemRuOM_aczcKOYQJcd1i6Md8khB3rc8fdLcL2dnbiJE2fa2cAUptIYQNqww1m8Z9V0G
}

EntityColoring(rubocop)
!define rubocop(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, rubocop, rubocop)
!define rubocop(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, rubocop, rubocop)
!define rubocopParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, rubocop, rubocop)
!define rubocopParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, rubocop, rubocop)
