sprite $rubymine [64x64/16z] {
fTS5akCm48NXfjUcnBh_RLVfiXA3h5MD_mBZ9nWUggJAr4XCgHaSjoEm0WvjSO6xmxY63Vu9ql3c4KpEwmPy2tpB-VVIRXhUuVO0kdyB-jtqATnv-ATXG1aX
rdtDAfR5oglZw6K4hmQxslsxq-JmLj2JXU-2JzFWgESHv33lU6fQbdaQQms_0RvhnfIwMpRlO2zX_8DtFFH-ycifRSNv_g8v_ujBWYNbPcBcE2jFbuEterze
b-SR4-LqyqgvWuSsFFdcQGe-qTLpozDhCxn-DYyLJnK_BpcdtBXv6lApWVeyfmX4vCNpExsfugtcr_0p4Q5uyeIAXzxxyJk_nWw8IEJi-NRzRo6YARnd6ytM
usdC6LEi9FpAmIrTFDNyjp65Bn_5rzd3cjvJyG4zNRos_99-_XMRkNYfUPddYMFrFvy6cjBUVt9mpTlsoQFtpgz85KyrhoadCL3nqSN3xdpvHcXxwBrFYCz_
sql3lpdaqUlUE_ZYrtcUNobwpRdTZN9l3H-2JhwpuksXrsSUyj3pGq_Fl3tq-in37df-w2colteZYd3mZcFhVprZvrSwzQxw6O3GbcBdXO_L_KZxhFBtIobr
U4RnZHgU1Czyx03JtpqX-s7fQ1u_MUrV7dJ5L4tXVHdLw_MGkcSuUhfTW7POTm12zQpb796P2bFt3huEfXaoDHDuVKAcljIZ5co7Z6Eb_UGV
}

EntityColoring(rubymine)
!define rubymine(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, rubymine, rubymine)
!define rubymine(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, rubymine, rubymine)
!define rubymineParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, rubymine, rubymine)
!define rubymineParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, rubymine, rubymine)
