sprite $ruby [64x64/16z] {
dTPNjYCX34LH8O8Idlzqkqel6r5YzVdV5sSC1w6e_8rQWSCGApQPxnbXRaiZyOXjNUY9hYJwbGoTItIcFKQoym50rx-I1dqkrGtlekyH55ky71tkCRIvXW5l
ea427FYnyX5ovMA1vtTTAEPATGRf6qVMJPqEFCgEIzN8so5NRdFlSwvzX5uFkQ1clh3k8to3wmUG7hZWY3qj7vkm0PBuziIb58lz-EJbaNVeCwuVF7ab21_-
w_MQxUJH8zGFi3JhmQDlKCrnuD7zUEB3-LNaIteyGNCUBbZ9ZcVepkC1ouxdqXrk5lJsBUFx0RazxpaESxHRO7_uUquEzWDq-RhpL9m_BOpBzrZBA3ptEP-t
fvZt8lCfzmsmKiYhyynNg4I1fb9qddaTAs-0pbEFK8raETo_CGVU2ZHZ-gihE3_qtRJABuq0EEP9jmSOPgsGo6M5UgtT_sczphowPu1IM-kTn7uzk0ClxXK1
Eslm0JtmP6Pg-w_8eoVthkC1R-y703j_yDxUo-qj6OWd_FQGc-VUMtoz_7IV3tYhL_UM-tN0RnyBVJxWldpwx0742txxQEZp0VVmwRC740_uxSCxdm_uxTDJ
ln-uVJ7t_pL0VlljV3xW7itzEf1_50VSZTZdOxE3npONdtKBhV0HsVI558WmZT5RhLZWLvNDKk1Y5tPMkupgXwYhYFi7
}

EntityColoring(ruby)
!define ruby(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, ruby, ruby)
!define ruby(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, ruby, ruby)
!define rubyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, ruby, ruby)
!define rubyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, ruby, ruby)
