sprite $rust [64x64/16z] {
bTS7ZkGw30JGed9atV-qFyXeGh1Rszw7kA4yfFBWn7i0Q5C0k82_9LCZ4CaAk4cFzqAMbMIGITBBN5z1IdXbS7fqafmagKfI8PqgU46KPEVDKF9t5xKuE6vK
kOcGr1oE7AcragQ9DDACecJwK_uc09utyKVhkmoavpU_AgF6I3DBS9sibHpEvq5JGkaD3uER5l2_lffUi-QBqdoRoKhJF2uoLlmYXMRWmMhN22Cb2umVriDz
u9ryybrmLZvvSKxssgcyLFnHidMrzr1uAkpSvfvtQd_PntSjEwlWkOugN-X-BtR0YAjy9MqhPNZ14eRohRocKRdeI5RFMzuAi1vayhsEVKTwM3rlkMsmCowT
rEWAsKfHcbOlWvi0KJQVIEeAI-oybjrasNhZn4VGFPzNi98SIU2lxXi0fShNFCfU_wJAfmbDmKw5pcE-xUEdP0l9XY3IpB3NhzvTGgFnG9mqPUkknpMtlnUW
f64_tUPV0_0hhyb6zCfuM3a3F_FJtJUSPdJoRPxfEIDpliYR_CXJwikyDGoub0RjIF3NMCWzhod-BtVIL3l3bhIDlxldvxrMM_9flyhSv1AEUKmQlt-G6YtE
VCuNcdBRxp7Oj_eOetVbXvR_9G21DADsRWfyLPwjAXo_KxjcpuODm9qDkSnV-SQl0fREN_buw4sssJpcpmsmhVoFyJiVqLgl_dqSN7G-D2o-JyDbfk3kAsGw
_DRi93Gs0rrSB3tZgrXp45kCz32P7tf-8eQhmstmJBkzUElfxQEaKHYNOYXSAgHnu8lEuQHnQI4cVozlSK2W2fucess5V7oQfJKQ7WzkfGANVdw_ri_DQEoM
PIbwVBys7RNGQCzUi8XFJMbQwJe53_9ul-iS_vdws7KY-CefVuiuSYJ7u97sDS97CaQ4vr62RzE_-VrDUQDNwszCCcFSuYvCqk6DrFrrAcMl95DGiW7IAjuJ
PLbBiGFnNFbPobSlwurHSF8l
}

EntityColoring(rust)
!define rust(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, rust, rust)
!define rust(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, rust, rust)
!define rustParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, rust, rust)
!define rustParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, rust, rust)
