sprite $safari [64x64/16z] {
tPFHOhGg30Rp1GA02E__jcTnsROg4Tfpzy_z01aZFO8Nz2Vm4mR-83CRQyKQmpZuZStMfrpgGTct80OlLcqJShrGacC0AxQaEcGF1i1Cjwcg5FzS4k1G7yaM
W6h3v3eZ0D1qANLEOc2ikxf4De2Yhv47BrZNztrm063BchwbrW2uwBmlsIN6sl30sOzhauVOdsc1dxeiwSd7_3dfxEULSC77hNvmXD-rt_nBBz-dCNs1VI5S
q_VwZITqcsGXNDFxbDS2sERXcjvV_y5Inyp3DJrTfepl0K1k6kwuFL-F1Rr9it27VX_IBjJFuQENUiLFno_9TptbUYFIWJo7Q_gBqTi8Z_cYT7tu-XuGvBNR
0Ubw6YOgVFX1yIq1yj8RTSZRZtL8883W3xteFYdtPn008x6_NlN7ynT301aHwR-DDZ-D-xkkluXL3Qn-__IbMxzhVbRthp1DRcyaTV-bwzRbgkFfpNPVR10t
FPJwWEs-ltTfkfMjFb50um2swUTm-lYDyv2XwItS1A4Fxh9uh8SxJzb1EIqUdy9Dwbz_0KSy2NTQtki34h4IJhd-NA0mIr8CPVhJ3Wbwk1cMpl0nGKGFDoFI
5McVpcnrYKntVArXNzDtfW6XBb8CqVyuO3Uau9TcPrAny_e9z02doUYE9iXUTIBJ7AUTa0oj8QdSgtkcTI0nbsytUKE_1cn5d5W3-dVv3m
}

EntityColoring(safari)
!define safari(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, safari, safari)
!define safari(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, safari, safari)
!define safariParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, safari, safari)
!define safariParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, safari, safari)
