sprite $sails [64x64/16z] {
fTD1UWKG34NX1tAp_nLtU0VHzkKm_-5yyVbpZVq1orfwu4jAxcSe4_jnb6bFhcwF3kT-IldWjxKzk3lo8yo1dzRsW3E_p8cVIkZDkH_coCURFqhedPxxOOvy
SE_RSn_vvBV-zUClNtZrQw7ZxME0rzjFdTQ_gLwpCxdLPxJgLQ_TkNxrgT6gN_tfrAy-jHe_x-9l2MV3tnAkXhybt2rVNt1wNglaRtY_WFlpvbFppMSyUctk
QyAZlZzmVfoGpczDE8dNHl_tcZ1QlhxWY7Wj1oG-vG3C7mSWtaEmHRmJJkQTC93t46mHxuI3UISy8ju91_NQla3VE-6WFkC7
}

EntityColoring(sails)
!define sails(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sails, sails)
!define sails(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sails, sails)
!define sailsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sails, sails)
!define sailsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sails, sails)
