sprite $sanity [64x13/16z] {
TP87aiKm24CfGkZ-9zvWufbjNzDacqTBp09L25iLQmr96oKmjx3YApm4mcuqxkt8gSxZMZgPC0dxyQqhlrKWPP2802isMkBMRoc-ywX7jm4opNokgt50dB8r
c1-UKd_dHv78z3jcgTrA3BjACYKiN-D-yWduEoVJptkqr7MIRbggbqz8yPD7mLOWty1iZR1PmrAAvH-CF_dYvRqevTeStzlhRkNbGy87VifotQPJlqnIxUkj
97xW_Vq7W7CLxBCzP9QKom_O7tZB77uWXEUKAH9ps-BbupEFvGqyAhVYta7obpVm9ry_wgyfal2JSaVhXbN58WKpDdvyl-K7iIy
}

EntityColoring(sanity)
!define sanity(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sanity, sanity)
!define sanity(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sanity, sanity)
!define sanityParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sanity, sanity)
!define sanityParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sanity, sanity)
