sprite $sass [64x48/16z] {
dLO9bkim22kBnFrl_9ynqvRKjPlFxEE8JOBuiJPH1qZ0LHvtJPsCfn5w1on6HZVwxsZd2vOMmt0JJT9DHKHj_ijleM7lJVFnBpd2ZHMwmCq1zHGS1RV56IFi
GDaQNLRuK-vqMUV6u1Rl4wxVlLEES7nz114y9K_VdjkXTPlwXFlm1tq9z-pxNj_2WtgvLQVoC3ssorx0q-oW4I_GjaQAcD_JTxhAt5_aOlaSotUcJV05BGua
pxlXLh3CJJw5v3_m8wegFQSKDrPAS5O2Hm7A-aci6HOpwMbdgGU5jLs8Lm2hvoXV7E0pvNfOESVB0rXFWY0zTpZ4ASNGY2-aMCQf1dyqqTv5Zv4taBvy_8dm
yJlLm6bscHDwPLDzdZyyC60MbCbWMHlhGg4Qb_tKIHkf4sP51KhWrhPgdJc35Hxfne9LKFM5zeQWNDiOg2xLtfbnKGpI6jL6z1xaAVAxPHhAL4mrb2PiJ2DQ
0vYdiwxaT42UoXk-Z9UQtnXaLSkWbYgLJ3WuV4KFdoc_2-Ony3BndYnaU2Dju1aaqNG3L1f5Vk5de0ZEvdDIXQwPn4c3Fpmea-s0rMPaS9wBNSIlNWFo92K3
6XDPf2jFM_3rVghvg7ciOirCJbS7R-zvOmfBR0Vhjvl-efGxbqwKfhLDr2ryq9sbtjjcFDnJJrRusydtkQNz5_WV
}

EntityColoring(sass)
!define sass(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sass, sass)
!define sass(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sass, sass)
!define sassParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sass, sass)
!define sassParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sass, sass)
