sprite $scaledrone [64x64/16z] {
fTTdOiCW38PXQulx7xYBOBabeNpns_NhiGJTnwk8MKHKHOIP3YnY-S4gPqGWxaym_ybCXMbBoqWzCjieqqreNriCMwKhBJcVkkEfTDaOhj5UbawBU_l9sxAG
1H_3LwMkUBP_IyFudBtWKXpQOF0wEtG7t3rxsoxvkdtF6b1Cl0wFNG4_yWPvlJC-NPZU7n_oBVfuWiU7TaBNzNN_udXqzR7jUKHKw_F--ZM_FDNwo0Bd-cHj
FwNPE-3Zz5K0FWUi6F5DPv-8zvi-DZnu0NTzD2IPlD_qTiyVYlbZkEFnaHFnFDZmw1VmCVYP8VwK5ME_E-PytzipByZrBnR0Zb_HjlTdNFFE-X9tRf-z0UaV
JPO8pusJOwSFX0Vtg3mdiBtfJyBldS2rr_d84kIo-De5UEM9S_G8BbqNlwQnrcdoNTqyzbNiAhtYm0enjD2nY2nonXacDNmTgqV-ncxQg-6hMDKy8Z8Zoge8
4_8Vi5uJ7QE1H-nC_WG
}

EntityColoring(scaledrone)
!define scaledrone(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, scaledrone, scaledrone)
!define scaledrone(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, scaledrone, scaledrone)
!define scaledroneParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, scaledrone, scaledrone)
!define scaledroneParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, scaledrone, scaledrone)
