sprite $scala [39x64/16z] {
xTL9Re0m38LXXymszpzliTh8jSJ3wR3atxuFDWoX_spieC9dQ8x6SZwpLFfbD2Xo_IA0fQEqmQB4SdkktO1hNT-dxh3YzZVPKfntb5IApHMts6YCXGi2h0GL
p6RuAZ0QwIivfcf4DFi0Qhkq0P_x4WOxuLZAfOteJHzkVvjRgjC64caK6st4H6CeV01W9R1eDzGdQv3OQtd_DJoyv7qQy2sKF__v9sYTAGk0t0tUfEyeBXGQ
6ONecGcFaaY3GcOl1wtk08zMZaJVy_iqu5jxhxh3n5qF-m
}

EntityColoring(scala)
!define scala(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, scala, scala)
!define scala(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, scala, scala)
!define scalaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, scala, scala)
!define scalaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, scala, scala)
