sprite $selenium [61x64/16z] {
xPJNmkiW38FnLDx_XVzEg4CA1P_Re-xnGOnauqW9NEuwSlAIXq5v65Boi9Oyx2KFW_8mfEHXAtdOIvCb2iwp4jXymOfT5esLVPOhorW3mblTPAtOjM32iglM
kqI-uQft1I-o4lwjcmPxgD4RksiD0RGTZaOp9yBHDWnibkRA9cX2heDhEDAqfqOjhHWCmDq1zFHl5ihlsiHmeHLJj0IHuapFMIvdaIUcOi9KVmCiBSMssG22
fuotKWmwNIYCEB20tUN00EvZZ_3Mf-rOuMBuSPGsYoyRW9c5Eb-Un82U9L6bONDuYMAjk7tsWmtTjouXYayv6WDimxxh9uwV7QJX98BnPTRfQvctd2Uf1LJ2
_dwsgGgJSU3QCj7vD1r6VQGOop3Y-zgJydorg2yiXBmF7EEmfSQs63syer4lGR4m2qWT05nRSP3OC735T80HKKX9RJSnm8rhsARn2fNQobdBO7YYesrcxdLi
nn_OX-4oORgBnN5ULr_VgsCQhgU-VN-qx_FwB_mBV0C
}

EntityColoring(selenium)
!define selenium(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, selenium, selenium)
!define selenium(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, selenium, selenium)
!define seleniumParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, selenium, selenium)
!define seleniumParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, selenium, selenium)
