sprite $semantic_ui [64x64/16z] {
xPL5OW0m20I11Vx_uxflRNAfpZau6_Pxyiy_eygu8gk76rSyfNeH5I_91i4pmibXvexsKzoRExcVG66G12RUf6Zub2fX0_tz_IxCilJdULAzmDwQLRNGllU4
jcupngODUKypV7ir2v4Bb-6gqR09E3MyWdCF0k85Fr2H9XHpu8nW2KvR6ODlKBvN0KzY3v0L097PGvZzsBLDP9ycMjI_CjcB740zaRsrJr3zUGNQludtAFHx
EaEsrMcoREVg5OpkABrrGuLlrfIMwWhrxBVadtyk0G
}

EntityColoring(semantic_ui)
!define semantic_ui(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, semantic_ui, semantic_ui)
!define semantic_ui(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, semantic_ui, semantic_ui)
!define semantic_uiParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, semantic_ui, semantic_ui)
!define semantic_uiParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, semantic_ui, semantic_ui)
