sprite $sencha [42x64/16z] {
ZTL95WCX201H404Lxt_TZBoOIQ7MNw1N3PyXv2gOT9I3I5II0uam2oa3wLx9mTpoafL8bDnEv8Mxqz9Pl1wNv3EbLRUIazMcKMgvp5iDuo-dTfT3AePdZiTC
5RV7CsyZzPxRdUGRDFNS_fTwWqrrQvTi3dTsoJxqfsMNh5N_9RHaVSGi-Zy6hx1ukady0fGb0ygXLF538xbkJKWb7nfBnGVDoFgGnMLYQ7KL3mMEgJmbFcKx
fCKfXxA2nsUfJG4yKZsuRWDUOLNTkZaDO8NyruwRSxb2wP-gtvW7NnKr6vwv-fLks_mRGD8QGD9sWAGLs4Rs8GdsuPYh0QUAnSizUK73iyJNK8MW5e_qs2L3
L7t21aavC9RoW0NYUXQY-UynJASnPAgc9GKfwQ1ykIi
}

EntityColoring(sencha)
!define sencha(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sencha, sencha)
!define sencha(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sencha, sencha)
!define senchaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sencha, sencha)
!define senchaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sencha, sencha)
