sprite $sendgrid [64x11/16z] {
dP170Y0X20GH146Q_tztSTB6qtBfeR36G4Iyt3qYcFwlVlM7oFZ7ai67il3dyCCVFsxV0AJ-xIkCPFyoJ8mJWJ66-BM_Cp5osh_y2HMKcmFtTFaLKI8y_Iwc
MJScrZc8vuchqR9TimSICkQGhlvMERxevm_KjZOMW6GlT4-AhdBiym0YR9K8OCJ5crpxhxMu5tYpAGXHXDVYNOgSaXNbvxfLy4gLJAkpg5QNgav-NrIHPsCK
efYiHIEQjR0xp81LIhIlAKL5X8lmkEKbvsczNCtrzhkX3lNp7z8AU_tPyVXo-mP48qQQGzVbQmElqf6LFKpMsvy5t_MxJuOcWsQUSBIFoRkmeTHzqmiTdnIL
YHy
}

EntityColoring(sendgrid)
!define sendgrid(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sendgrid, sendgrid)
!define sendgrid(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sendgrid, sendgrid)
!define sendgridParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sendgrid, sendgrid)
!define sendgridParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sendgrid, sendgrid)
