sprite $seneca [64x50/16z] {
jTI7hXmX38NXG-_u_Tys2yhOWZJOKNurN-b-KxnYC7ELBcj1uScAlgXvp7IcBwi6WElqVH6UNfKhlQljxsJ_Mg9_LF3NmhzynL-B_zkNIzzVld-ZjGWWv1mm
CoadYvd-Z0fkz_i3EG2Lrp3-FM1cFwE6xlkwrbyqOF5-FX5x0zY-lAq2N5iF1D3OXzLR02hBxW96AlRbGAApZ-BTyCjnpne_qx7B1m5gzKbUnK4-Dza0aff_
YM_YiumUJrfZQ_LTOPJ6ZiG7I4S-qxQAaxJu8ZwTUs9VnUUvofFCwXluKJ9EilH9i-_WiTpwjhtAkJTZKbryk_Dsz_tOkzMJvh7X9F-hbqSvAD1pL3IDpAMF
x0tnesYwytvCLhoPNX_x8Dx9UEwZ82-ZmK69lPieo6Zll2SUBtnc56WR7Gugz1pro7wChGIDW-f0MNmQemlcW8eluZEaEv_cvBxn5NCJFHdSrjYde71VPt-T
7FhsqiTNlXYyyDtZHRfedFS3
}

EntityColoring(seneca)
!define seneca(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, seneca, seneca)
!define seneca(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, seneca, seneca)
!define senecaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, seneca, seneca)
!define senecaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, seneca, seneca)
