sprite $sensu_icon [64x64/16z] {
fTG7RiD044FHdI7t_aTEZyg7CG8JehY-xogjUQqLZNnl_OyZa784Kev0oX58EG8fPo3d3EIy2u6GhuL0oX58EG8fPo3c3CISWPWp47C60bvV-xbk12PUBNiV
izM5mC2tzpZD_7bAEQU1Pu6Ps_OG8EStlhvNrV8G87T_Igw50FY1BmOhCK2kMlEQWTM1vlDlDttHutGGNNWF0YiV0MMSHxENWdT_p0U_V9hw2qSWvLEWMhAb
xXhuwq3X3wyUE0Buc-BFHSx0HNCky5S1xM4YPu3ZmEU0fMx9Vk8Cy1nIRV8ve5fO2NmCrFol2mFaOO0y39270V8mG1u6oCC0UHm0pmFWSG0y3e070V1u0eyd
y7W2ZoVmU0AF9tBk7G
}

EntityColoring(sensu_icon)
!define sensu_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sensu_icon, sensu_icon)
!define sensu_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sensu_icon, sensu_icon)
!define sensu_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sensu_icon, sensu_icon)
!define sensu_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sensu_icon, sensu_icon)
