sprite $sentry_icon [64x57/16z] {
dPK7mkmW28JNJY3tl-uhQH-wrV3NZQ3Z34CUdo8srPOUTwEkMyZDyhOUiTmgJ-iLvKwzKczXlhnibQtkVwRBW_slqyTZsJP8zyZB_pIqUGhFAl4xJSM6sk9s
aur8dQ8mdwpneKvfXsg0cMtSCfBnOpnJtkOq5DAxPfXgV7bknZBJ-9hU4_fTkr6nD663hAVlmyZ9ZnfMMxTGykTi49V3-6deYJmv-smlm0RVR0zZjdBYppRG
vK8SbIjyjm6e9PnObfKA-kfhurlkDz3mrGQ8J9-mWNop0G3f74Y7D7pzVcZHEUv6wPiDC9ck5skeflrS-pZnAmWWhGBndGtgoMwsZdO53ZPuF_5fFHbb__Ws
47TCD40Z-tiD-rD0a5o9m79l0sx9SsY7cVX6GpgDOw0T0Esp3RAnmNXCvVznl1D1Q7ucfWDGteyog26lEK6agsZlR52O6FsjKpS8ma1X38C5F8006uMqpWPg
BGpG091vpfKx6rHcJa-xe4VYyQWX7SbAfOaia8HcWWq6ESNjvYwmz9HpwDXEqMqdqDJ8SZrTcUfmGsQ1jGoiZgZ-hK8cM6pyrpjCbYkRgw4D_mP30AyX5B70
8uKB1C06PvJWGxYHiAhKxsdH6DVcmmdIM4Nme3nOw_eSiEvNgJUVfZFr1IhEjqnOfkhFyt5wg7eJl_nJzYy
}

EntityColoring(sentry_icon)
!define sentry_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sentry_icon, sentry_icon)
!define sentry_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sentry_icon, sentry_icon)
!define sentry_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sentry_icon, sentry_icon)
!define sentry_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sentry_icon, sentry_icon)
