sprite $sequelize [55x64/16z] {
bPO9RlKu38FfNOllVzw1Hq0TMKr-bzsTV059gGyFhygzuizAROpHyn-fEamjuLwbZnzTEyrzFDNBLQWwdEuYbW1Pn6j_NlMpTASxfsUesY-Sbdv0AOMWzGHp
U7BkeqO7vIjKBwdQptWfluTAvP4d6ddrvvgF4O4SJ8IxKl3J2mL_gVBZa4GJyX6Hc9c2ltr8h5Dh7zr5P9syx-avDVyqrZcLNKGxdBn4wnuh_S6H6BH7LfVf
kSGcSlqPA5E5V5kPTJunpY3N3ikAvGkZ0fa1s-KiAyeaokvC2qHFRBTAwoB_HDoTlc4BjFueTlg6cNn_1bgaJsnEyKqm6_MDwUIZqqjCcCbrUerPWTRfDrPf
OuzEDwOZ8M98ms7MnCQa08XOQeCyfWzCUTHVCMk0HOKZPZF93dCxIJGEJ8XvNU6t9gs-W9cFhvrS78ayCR6pVypj_rNVcCsGzM8dbMs3rNwxtachXjNytUya
6MZ_dd_QoVtgzerr3Zj9udPISi0AKDnEMgSFJ3kGTNgC6u1Axpj96UWwJuof06Z4oXGmNMwgwFIOQMGWzORXCQwq_D66FCRS4e200URleKgEeseHD-RzcNG0
pOEZ0AdzODfEVzREYiDEFG6vsqwEXDGz97M_F_DE6u0y-5T_3LiMvnX6hK1c3uq49ulZXu4qFCG5GNcSmwZo4ighUAU7l-xzlKQKKFghKgU8nL1V4IMM7XKZ
IYmzAWv3hlpvY8QvqczK1eih_LQLFqh_3m
}

EntityColoring(sequelize)
!define sequelize(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sequelize, sequelize)
!define sequelize(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sequelize, sequelize)
!define sequelizeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sequelize, sequelize)
!define sequelizeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sequelize, sequelize)
