sprite $sherlock_icon [55x64/16z] {
dPQ7WYiX24L1n2xy_z--bH0dcVHtjaoc72-esImy1OchBaf4-8vGUowb3DDwARcEzDageZg6g2EphGlqNg9BoEoJwGyUVLxi_CxYzP2q28Mk5ICrYwwlks9P
xH00xsvYzX9UUKXnPPNriiB6ScrQ2pwrgBi5AS8c59ENby8JAoHLRPU4kwaDu7cJmgE5KtLQ7N5tTfojkrefd2t8gifsbkzkOhdOikBSstq1JDK1fneDdugc
gXa9ORCiNZtRMSZtcayGoHetq35PQuYkAcYdPFQvENj2oI9sOu2Ysi7Wk8sxTBRrsMKI-JM_VLuUB7wqAZtEzQAgdb8eHEQqO8uKGdNV-h3Yh3EV9rcrSkag
VqpxDSKODT4gGrNeAbpaeJgHkyXicIaW8g0HY7CT8hC44jLevPdhcapfZF0KZ6LA5rNs8DgQjW0VtupHs_Bj4hjc-4JJvfEubo5F-CpCTg0G27xGHlMLtXh9
vo99VDSI4JXPHactv9plpvjqk6h7xCKsPMvioLMFSvMUuAGvUCCwdMrVOkNZCTTUW99lNfTljI1M5jepextHoZ2AQsobsg4FC7mcJretRhKWkavBlT42mKjS
WrGG3iuQXXUQmmGE1IG4PmY-quACGuCz9rKrlzBylf-jg6kLhBdDDnfA6nwtb6kLSq3K15SQdxGYWOMynkilI1e1nZZ6hguTONvn1Nca6wpns4htMbO2k7H1
HsQGR9NsEuqEpUua2Hxc7m5UThB3JizY3NWFjaSzp5EpuBM32wopTcqxR7Z75h8_ErYxdPKzFlKvCpYiDh5Tii_WjKoM6Noy1SOOu63CzTIKw2KU7ibOUTMg
ZVB7pheiA0uXA_7aQRUkoyeS59hi_slwj07ZoV8wxMtL186K0v7KD6meqcoRpwsJ5whovMzXr3X5L6Kay95GEf1R9u-ce5KKbGBdnC4tTB4ItJg3nDfM_noL
uA1A0D960Lw0LUDQsgYKsqOhG9U8y9h60DnOOvsR4G1QXZTW-0CX2i4F537uHwr9JYbh_bMRjYt_J_k_D1Y_zbPDypV_BpE9u3l-5qZAEaGx_43HKKgJWV0R
QOXA-Mpz0m
}

EntityColoring(sherlock_icon)
!define sherlock_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sherlock_icon, sherlock_icon)
!define sherlock_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sherlock_icon, sherlock_icon)
!define sherlock_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sherlock_icon, sherlock_icon)
!define sherlock_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sherlock_icon, sherlock_icon)
