sprite $sherlock [64x14/16z] {
dSw7aKGX30DGEP8Cwh_RWxqEliZXpHY0pRdc47oChr1OM_ADotAvCqR_ngqq_EM_05rdTwk0LaJjlRtLhWul0v2rrrtRtaF6X5KNNQOYeZv_ljZcD3RSaHoj
wUIOR--Ni_gXTgvnehQT4a7uBn4G08iphftPcJ-FIU3CU7uVmBYu046TVUGP2mltnCzBsrnEdlFytYNZplIa0QS0ON7-LqhwDIu2Kt7z-HbQ33Ruyw4ga-Di
99lfPBiZY-d3YdwEY3Q7NzpYSLaakp5Xpz-qSH3CkDlwVuLkydXj11V20zdWde8NTRsJl25gPYBlh6z_D_PUtoBGTsz0HevksHGVqthBTFlA9TlFVlUft_KV
}

EntityColoring(sherlock)
!define sherlock(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sherlock, sherlock)
!define sherlock(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sherlock, sherlock)
!define sherlockParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sherlock, sherlock)
!define sherlockParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sherlock, sherlock)
