sprite $shipit [64x17/16z] {
fS-74eGm20JG3ImfyF__Us1cRDEzlI9bdXgS4VmNobzSrFxXD3L-vsActUGhRzRBsrVFxQcVtxvyfpMSKJD18sjFhL-DZEte6tTGCMvlvCbxH3Z5lVOninyO
SGohLlUgVJ-9VVlh1IISDaN2i-7fX_Q8PbahLtOgGAl7TxBN7m7eGHQgV7a3FAGyCAjRXDwyiSai8Xu-97taU9w-Gvu-LrIb6VDNrOoOoEYA29KuSdfVkpuz
8y97QYMjJu-CuOZCc1BUMhERduQxnuft5YfiOFhN-JigTo_-uYx8MFZqqBUtjw-3-WtxRAYqaOr1V9Nt0VEEuTjNZTtz
}

EntityColoring(shipit)
!define shipit(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, shipit, shipit)
!define shipit(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, shipit, shipit)
!define shipitParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, shipit, shipit)
!define shipitParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, shipit, shipit)
