sprite $shippable [64x15/16z] {
fP85eYH124CfXq9o_zikpRfzpGWGNcRQw9kkzghjRFgV3eHAOeF-aE5KRSpz_td_3lDFTwpLAz_cR4HpVFTIRQxvlROdtpQdOH2YNanJf2GjTS17JwORKaoq
0uz7wwcnDiA_mKACQWN10Ym3GXEUm4n8BMlshW7l0ME3CnBMN2Xu9PCjEwpHainxrZJglOaCzpxUp6bqobq8C6gXa3e5AGykuzibSUISRgkBbKnvXuu67jPp
PfZX1knU0uW3gVDxFjkT-V8COe3ApxnNFXKHO_J90VyjZquaC8Ec5p14fuxWMYZK8FxmhVU04Dq_ypfMW1NOlOpeBPa1w6JWA5XoR1AMOyIVnr-AfYX9H-cG
L3LAk4VrYxQ5wwPhE_FNZfd0qzIHcB0x4qrDPb4sOigDn0uDZT19_z3-up5zhpRYa_dxFRzUXRy
}

EntityColoring(shippable)
!define shippable(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, shippable, shippable)
!define shippable(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, shippable, shippable)
!define shippableParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, shippable, shippable)
!define shippableParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, shippable, shippable)
