sprite $shogun [64x22/16z] {
dPC7hiCm3CLaRVR-1_w8dB-tYPM-cjP08iyKgCWv2IwRbHdk7fd_k35UVUEPFF8bgYygrp_z4pmpR7nRaMbtM1MxkiQiGoqcq0YL21VBz2MhkQZBptaEkSFT
KBBnkq67MD2JzqheQa9YViC3bTuXwEWzjxxtxxWAbeXE_wrJsHrodwm5FKtsHpykvS6bXRxkBo3sdI85_YAfl-__EW3i-KhVNj_xtuaWzfDzuuj60-lh-gl1
bis1h_rrN__ilvzVd4rAG8ciUky75Txl_Tb_5c2lkXZG1U_zPYZ9r_v5xzG5Kitj7kUYtljYsLqkuljhqwoPidhUlvoYwNf_5gcQQP8LEoZv1SlTIwkSOA6o
r0lwoE_jAN3eq-7HK6VzCnpFBvhDWuubN_C4
}

EntityColoring(shogun)
!define shogun(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, shogun, shogun)
!define shogun(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, shogun, shogun)
!define shogunParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, shogun, shogun)
!define shogunParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, shogun, shogun)
