sprite $shopify [56x64/16z] {
dTC7aaCX30DGR4kVlV-9DqoA1mtc5ssPbXTmeQtZ0BpTJP0ZkASC92CmPDWjvkEc785VPIJiUrM0l0X1lfWF7SJmLrjYtqDj632ktJ9-XxRntmSsEp_khRrz
N0D1TgzDWY3Qs_cxhSVV1YRWkoRZoDlLC86F-rc0JFU2OLMP0xoB3BwJRiZNRrzH44CZGRflV7tDH8MBrJKpfOCW2_2AEsR4RNgwFk_o8ySxplAM5vqEmc-v
g1pYlK_cM3dcDa_APA3gZcKxfpN2olMLCzcxhQjOrftg5LD7sLciNUZugCz3d6oswt4UG7Zpmb6TLTjwJExGyScrAzUbV5nrfcv_JzriYcjnug8QW-yTqics
67QEykKXkrAvGwinWONhwc3fJ9-xRZQuXb4xdvoyMwjTJ5kli7QGEkRce7J7ok7SzUaLuPQBFCP14bu-zuoby_TBZn-pZVEyZJM9YvD1v3Kbs3ZKphbnHrOH
CpDPQsseosuAArqm4_PLGN4Q-GGHhu0ySm4MsJiyT3GFF72zZPpWNhatjW0Uk2P7LwuVS1EbMDt1A8ZSErsd7hFN3lREKF8F
}

EntityColoring(shopify)
!define shopify(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, shopify, shopify)
!define shopify(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, shopify, shopify)
!define shopifyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, shopify, shopify)
!define shopifyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, shopify, shopify)
