sprite $sidekiq_icon [59x64/16z] {
dTO7TgCX30JWaQZI4Fl-fzs2K_Zn6k_JbvumcIVa53nhYYYt4euE2aA4WmanZIo84HyTGONCgZXB6NYc_CFbtLIOKZLBb-ZvbjN8URuuoR7KE4b_CKoP4msV
oSInrVHNqMIaLIVvcBJo8VribXo6dHIR9PDUekLoJNiq6x-vTqo93mOjzO_k_ADXbPP29bn68uSNBjQrQUEFlYGXnYU67_ktN4ddRjbovmzNR1glkk91S-MY
2tRELTDbnctAdJeN9X1excPSU14y4-V56ExpBRzPnZzrNjtkWrSDB-obzmzU-59vljwFhRG9Nb1kxhTjJo_bOsd5GJkL5coEcrbAFU6aSh9Icf5ZBNN1aSyg
cwUqTYwb3KU5rrzfRTbfnf4FShWkbsRyv3YRSowhio5jsSj9tyxS21YdXBEyBQ_eTrHn9lvqHdo9daZU5ozy4BmbWWjzTy7l7r-1QEVK0r7ZLEFH4lk_wQyK
YNBISDGbyczJU3V2gSMZ1U5PQpmQRtL1z8OhmgqQZGuN19SJZz8h8dHsXcGEHqoFFXwW34ShHxJKXoiYaWzF2Cd-_vs_0G
}

EntityColoring(sidekiq_icon)
!define sidekiq_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sidekiq_icon, sidekiq_icon)
!define sidekiq_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sidekiq_icon, sidekiq_icon)
!define sidekiq_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sidekiq_icon, sidekiq_icon)
!define sidekiq_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sidekiq_icon, sidekiq_icon)
