sprite $sidekiq [64x24/16z] {
fP7PbeCX28D5N23ClF_hJbEqUoyyasxyXtuGOxbAPlcN1BNyIsC-350z8DMStp7sS-r-OiOYQYazUg6QHQ2L0xK81oBeMJqYZPmPY42_q3CYN8-Z9s_TGBgT
9n_Kxq_ShP-l__cDYCVOvpQYZpErhypcKtn-NU_2SNsETYcmiU6FNctzeco1ffNk6t7O64yXz1V-LS5-7HQGntzB-jMQ-wkgRBxkTjLQfFTrYNXQu9rcu82n
ow9cUq1Auz09Tu_RCJpJq3i_V9s_qvlPbM-SGxu6YyLBn5p9m8SaRtETo0P7Wxn2I_8ASdT-hAfspCMFpSFCd3pJNdnxuU-XTxporYvIxc_GBxpU-8ON_tFU
xwz3Flf7ebsA-FBVKQN1CrLHpVpDavVeKkUDj-GTW35j7iS08r8c073YpAjfHcU09v-NaHAHBFBXlNhgRlyJx9zhyTKNVix_0G
}

EntityColoring(sidekiq)
!define sidekiq(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sidekiq, sidekiq)
!define sidekiq(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sidekiq, sidekiq)
!define sidekiqParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sidekiq, sidekiq)
!define sidekiqParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sidekiq, sidekiq)
