sprite $sinatra [64x44/16z] {
fTO7Zkim38HXaJDqaPpxN_SvnXj0GRYMjVkXR4b-Kkaf2VEJdSearRZus_GGC_HqakcyDp7370cTv7dl6RDXRgusPQDUYxxa0_BUKd_jRTpRxI7zxG-zFTW_
OdQNgxUCNq3yEC9TVkuP9FnsVTwx-XFXWrjlsMZr9tuDyF1UibnzDi316kOZnYKRu0wWDfeDShG54DEDmwMzZer-Azghw_tZ9SzsdEeQWAUurFCANOz-EtXS
NiVHMarSuvFUWKiS0z-zTJcM-LwddzaVdxq3iXrZhzhbP2deh6tOx-pxG04f0DTwMzS5e80HTB03CDOzFqNRrr2jF8BWf-jOiQxRlk-rrlrjMvSW5NVvoS44
tlIhVi_oAE0SvUeT_0NbAByP448h6Z0PzsyXZlbQ-TI0w95Mn837iMelFN_OgaOHCGnBnTgTZmZ9MxZTVt_AJnnKEsR_ftnipTD_
}

EntityColoring(sinatra)
!define sinatra(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sinatra, sinatra)
!define sinatra(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sinatra, sinatra)
!define sinatraParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sinatra, sinatra)
!define sinatraParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sinatra, sinatra)
