sprite $sitepoint [53x64/16z] {
rTLLUWKX44JXRjpslzsuK7pJf8ZVy_wFe7AT2tASIob-me1YpQFICmEADCVAfmIADA0-O_INZ125sp61CV7FZLf45-FbhTJykUcZXqkJJ9Fxk5OQD-QnqUD7
xt7mdXUL5XHCKnx1jJB7ElO-gSmYg6ocLTz_jYvAcO7GWgfEoks7xxtH7AMIhTHMSL6UKXvLtoXlgq0iG5xXBBjcAbbKd5K75JT7c9ega0f7Na1ngtV8d6SH
Akgdcc2E7mXKg_5jM4EEAefbx7CmCii8LPnCi0scjl7CRGAcjtCpcliXaxviUbF2B8TU_Ja35SQKnGXHvWpcwdZ_dSNOwQIo2AtWucHLWIkQhQ3XLPJZYlMU
Um
}

EntityColoring(sitepoint)
!define sitepoint(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sitepoint, sitepoint)
!define sitepoint(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sitepoint, sitepoint)
!define sitepointParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sitepoint, sitepoint)
!define sitepointParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sitepoint, sitepoint)
