sprite $sketch [64x58/16z] {
fP47RcG124CfXht_YRUHOaJGa9-NClM1aML3LUql-kzFLGwmPlxlpqtLtElbOP1wkU_y4vHU5hiEBqYl0GnC5XnJdmC0tNHCVGu0V4dVVIMC_MK0kgyDQpvK
1jvzrOur7qCtD5y7tVTvFFkca-R3f85YwFi0xSSNh4-QZtvymVh4ck_j-ABf4sCVniSNNPyO-r0-dlKTOn_zU83q3MFVs_40wIj6Fam4XEi10w48mau-A_1V
HE10D4F0Bt4Wcow24U2yFkKVqGVSrwVAV_YjxwmtAJJl0RBhXL60ytgNJvm27DT36By526gkWrE0vEOwSGWGrDmWHu1z_T2vnNorFas-mbu5oDRSn3d0lXwo
uHHWNH-oWpq0WlILs0CaDRUJMu0uwQAv1EZDxHW588AQkmm8T4PpEyu1U7t83L00Mfzo9If0NvygPx870EadD5k0eEPk60S8QkwAvMU0fERE-4U0uERku3r0
3ltQOjJwL7b4PgrNUOPc094cJx44mkKv5e3y17-b_m4
}

EntityColoring(sketch)
!define sketch(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sketch, sketch)
!define sketch(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sketch, sketch)
!define sketchParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sketch, sketch)
!define sketchParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sketch, sketch)
