sprite $skype [64x64/16z] {
fPTN0kCm20NftF_4srCryc9xliCB89hb3VMi_aMbgvp6ijz84r4pTpFJcJKpSoZwVrGSI6HFI1Ec6fWhPCy9ZdrEVRjWVHBduES4_FrbWUnR0dfGC6w_yQY3
7FZaeTKN2GFtsPhxemwo7q8u_WZVbr6A09oN7GOHz8A-fIt2JR7I7mxiWxTwEAGSGM7-39nr4SgMqVjXMpXcCAX-EDbEnL9GlyMkTgXQKgovyJ-6RMIxvrjh
dakb5fyUMA04lo2NdvhdWOX21PbyexvpnC2-Jkmtem5KAeGcjghEEpZOVhui4-sP2jZx1OusW1hGBRPeaeQy6DW3iGj0AIbLUu5OxHtsS_IiAmF7CWWes6C3
5J_rhW8MPmip5Ri2o6M2KB4b3d0EmEHx09KVTC2Zgh1zrSnDSGC-u5ZdPoQKTPmmRqfhwcP-07o4hUslqSYIM6exzUmDHx5L_g5wJq9dNhjbzPA0o2s1a7i2
IWKo9sv-IiY2rLNlPsS3TFf5XGBpyU71FGRVqhk5u392rLINww5YO0h-m3wKdm
}

EntityColoring(skype)
!define skype(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, skype, skype)
!define skype(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, skype, skype)
!define skypeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, skype, skype)
!define skypeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, skype, skype)
