sprite $slack_icon [64x64/16z] {
pTK9hY8X58NXS-w4zVQ_u2PA7jHj1Akhfp-Zn0-G4CGaghkRz07nAE74PrKTDJUqhBoo3td5umHUoeK9M7dB5JKjtuLWctKVZbgKNc2RHyy9i8oUsCIJ5q3A
c63Nl_RgzppkUhhVyg1vQ-6NKLkywdD_opEtzSpdbPE5jwYvzETYaXlVU8dXFT2kSpxtZE51uSYpjwdtyRCjVFZCimpvZA_llvQXkEwjZ5tqpDwMdW3FxsVo
8RxmXdJSbht2VBdyQGE1v1s0-UBNdwvRIFBUBl0q8rhqfsu3zZsTeKNvEMA8eiBqk0Z-coHlgMstnqbesUDe1PxvSo3OvxTPRRaulbelpqSREBIjRU_Iphil
_VDh0NkVGbwyUni62cfgYnXVoJ_60URbS_f8diSue01jsR7qjlMdzVswZxJTvBU_Vpp_1sPULfxmeoy_zL3RNg3svRcdhZYWvQY5OEANzv_3-q5Wxbja3gc5
N_JdlRJuQvwQpkkgpmT-tVVkUhtfxQxdd_POlr_OLlBxgPVE3tfqxgZ9fUsFVoYbpPYMtzLUfACm_Vq9FalYg7fOZFhszlu
}

EntityColoring(slack_icon)
!define slack_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, slack_icon, slack_icon)
!define slack_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, slack_icon, slack_icon)
!define slack_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, slack_icon, slack_icon)
!define slack_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, slack_icon, slack_icon)
