sprite $slack [64x16/16z] {
dP87WkGW30HR0MHX5lx_svCmlhHXGarmK1SP0PL2A5NmFqVldrz-BcWfocRrKwpDgVZ4fuA4BsRsAUQV_AyBpFIkJve8bYz5i2YjdmVlc7XlMjq9eEFiBhT_
k6kvaF0hvMyt7tnSiJ8t0XqpiIn8BaAds-TgbSqiVPxJjNPVCSgMUcfCOzzo5YmU22G90w84LKQWSpP1i6CEo4TOSNlat2GBRSx1Q-yvF80u8GGKuJcSbnyv
kdQCsnouy3sXjGQbn8_q0Wdxo57J0z_ohhcQDoFHHAu103d5ycVy_6dyDY80Y5Ma3zuB4V1eLTFzSVrqxaDm-KJOt3jsedstVwjWwztsMLHm8t5CpWfKT_xY
_En2UWUmdYpN3s_2xW9HnXly0W
}

EntityColoring(slack)
!define slack(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, slack, slack)
!define slack(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, slack, slack)
!define slackParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, slack, slack)
!define slackParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, slack, slack)
