sprite $slides [64x62/16z] {
fTPNikGW38LX8QH3aFU_te6kec-oODhwNrsVCu6-fRq8q_FgDRA6pq-YAfcvNxCd9sczjzRwo4QVd2JDScr_wwzQKKw_--Rngkp2x_IxBv-dAUPBQxM0d_i-
QZdcUzMS8dv-uLv3VXJqFUXhq6lGysDlarjoFKP7tmWELX5H07jVxZroebSfO-k5S1XV3CTVCxxpMFpeZMuyyik9gcOYBHlVRlta6LYVOEFBdTVpi5vUOjxO
lN_1mTlqv7hA04w-aVl-Hop0tkFMhvbrVGNVo_BE7Ooy_tUzFkV_X_3c_rj-yw40IAAPmFFDzUicQCIknzwlz-1wEVcYEszyz73z-7oTdACeAztvvdY80by_
4diUZjTX1BF9IJmlznvfxOly_sTwOyTd-bPo_j_v-jpdvztlltnr_0YGp2dv0tXwk7w48J6rxsNvNRutZlbE4MzN3Ne4VOvvIo5_TOhv6lG8-Xppbjv-c-Ej
quetPH55hMrMHsrbbVwxn8BMRTJV6JR0EKbfzjepZBhb4_1FSeqiqTDIrcgTtlq3
}

EntityColoring(slides)
!define slides(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, slides, slides)
!define slides(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, slides, slides)
!define slidesParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, slides, slides)
!define slidesParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, slides, slides)
