sprite $slim [60x64/16z] {
pTH9ZkGm34JHuDptFt6hAeUmIq2AtENRVv2M1EFxYAgAO4pTuybDqISMVvYqPyREMpM7RhNgC2MFC818V4kxkqiQ08aZnamBYyUHwvu6bg3ssbbb03IektPK
bVAaJXpajGW_zyZuiSMsIS6FvSwphQtUhKQNSUp2fz4VhFKGM7msEEi9Yuu6IxteRB02_cuJezYvyc9Of1r3waA0mIMBraNoXzLWNbSXWzgZRbBHh_DVtJd_
qgUyDcbev6ptcdclfNHXhjvhAQx3lTbIwAUQvtpSNNrlwu07P_sbzrhZngqwZ5zD9jMIyeZZGf7LOzlQWgXHpAqTq1h5tDe0P7N9RR00yEgAwnSx5gasnSAn
ey7EfHsO3Kuinh6BLTUxDRpaj7MyoRGLaCw-rt1b_GlsPqhUlbzdohYvCbCoWpV6AZQDCtDy9l7Xe8viFfN4QvUA7l6S3oLbdg4O4pLJ5NoT_m
}

EntityColoring(slim)
!define slim(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, slim, slim)
!define slim(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, slim, slim)
!define slimParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, slim, slim)
!define slimParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, slim, slim)
