sprite $smartling [64x64/16z] {
lLTPeg0m27i1ulrlFAi6MWOxUxxKDYcaTF6Z0UP1Nbz1XXi-X3FCUUrWsC-H4TU4m7beNc_W8GZMWDqCW9a7VrB1dqwEFQkqX7ZdYpnA-2WGx_4PCuGp0FiA
_4Z13boBrKhi7lah-MgW9C1t0UEfV4829pR9fg0S_AruwJ8EnGol0jO6RyasOQBqH2-VkKHT0dhZMZodgLK7lKHhZMKF-Gh3Ogu4gCVcgMgWsL44e0oweyvf
uKSQvsL0Y2vpDn15W1cCuf9M98SgeDAiP-Z9qpgm5VoJJPIny4XnjGAgr0gZ16flt4c75C6X1hm8kBhmkr8sSTnUxFP0D7t4j_TYhl8EKkT6dIAh0NpLzC1U
4eXzsTewSr4TN9nLZeBbDzUJD9SKNOa8FMz8L0yAfj33pUEQyWuPSFDBU7gK4L00Jmzk1fYw9I7p3Zqf0LGXIQa-1DLNpri6rbIOfMheJNgmHp7vjWmICaJf
Dj-IlmIfF3BA9ZJmxUcJ1nN-5zzQ_9Jayoa6FbjD-hDnnkZVwh_Qj0grT8_pfzoqZlgwLDcbMUANHwu2qUgtJUX32odbji6sRxI2kc6sdRMXan_wFAzVGGA2
3Vk73DbXx6TNICbR-XtESdQAH9LQP1u3OFNuz-93sm_Ey7xoAuypT6cK3pY4tsvVejjQJXWeORXDo7kxeZyEVtFOhp1CAP-7ltQuXCkW7fFvtDYeFlBZ30ls
Np-mbECPW06j1WRw4SRVfQjgnjpFC4t3xy4K-syYvi4_0m
}

EntityColoring(smartling)
!define smartling(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, smartling, smartling)
!define smartling(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, smartling, smartling)
!define smartlingParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, smartling, smartling)
!define smartlingParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, smartling, smartling)
