sprite $smashingmagazine [64x64/16z] {
fPI9agnA24HbJVx_Yz_JC2xLO-8uzecjjwIe8yts1qGzWP2Dy2oBp0Jqxt7BFHe72NdLWBd70NnxXrZiP6wlKOz8R5_W4RC0aKTverbxSZFnY0oI1P3v-_4M
FmNecOq8UtJz3m6IH_R0jqVjVmX8n0avdhU_2eWbxaAc_d_CL3xQNpmZb_pbCE_lx2YXST02wYRliUAk_H6Cd6_agYjk4YS8SdyTZc_EZnO1DkR5OwG5o8Fp
6V-MKEQKjvZf7H99_SqDp0ASpYediLq4k3ml0EXr0eojAqfM4G6-NJ5Q0LLi0eolJ2V7roAWqM5lk_-C5n7G2bc9jViTwmbY1NY5ZbUSNpY25228TtmHe9rl
1nnRuWKX0dvPevhLK069AjXS09qd0XArWzIx0gE0_cwkOAE0h1Nay2YYJj02Ehw2O1K4L02AG2judUGY0CM1pmqiIpHh92yjvFbDBr4KXnUmEl5LwKnECv3z
J4TQT7CLKBT0UBu5r3r6ybm09qYU2m2Au4E-BYEXGaO9DanmTSLko83x1wZNV7o8iiITVkzlrf5Qtsi0cFv3URsNuE99p2CpJER_ZwzAkz6PlYj-x9TaSqeH
x5abIm7w96-cmrxDxGlGnxyY2--2BI3VDT02aFQDW1s4lc_W06-leRcdUs2Vy1y
}

EntityColoring(smashingmagazine)
!define smashingmagazine(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, smashingmagazine, smashingmagazine)
!define smashingmagazine(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, smashingmagazine, smashingmagazine)
!define smashingmagazineParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, smashingmagazine, smashingmagazine)
!define smashingmagazineParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, smashingmagazine, smashingmagazine)
