sprite $snap_svg [39x64/16z] {
xTO7ZYmX30HGOji6pFsF-rlMNsHH3Bi7c58klGdTnB0dqg08BI9L_GKcGsemVKIiFfmkw0wpw2cI3-WEIzDRMaPqXYKSKD-BgJpmpsn_TSuXDCR0V-pXrCRq
CeCUUJXdPs9-sNASu7rFbHSjDeP33ZP-bMSjd6Bex-pBlcmy4L0io4Qdk2FYZG6CrP1d7YP0m2oKDcIi3OWmyQPgA0VOnHjwx9yKkK2YQkW2oIDBFaAg4NRw
Zb1Im3Sk1yWvx6_y32KxPBd0jD0D5XWMgfaHBkLVPY9WY8A3oCYzJ8Fzm8WVUEEoC-AcWs2BdkgOeVd6RzD9hFg1j927-JzQq2Ch9I_au6fMj1-gMA55LCER
EzHMtFbyHni4b0ztXnq988GgjtlDzfu_mk5kI7V8YFu1
}

EntityColoring(snap_svg)
!define snap_svg(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, snap_svg, snap_svg)
!define snap_svg(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, snap_svg, snap_svg)
!define snap_svgParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, snap_svg, snap_svg)
!define snap_svgParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, snap_svg, snap_svg)
