sprite $snowflake_icon [64x64/16z] {
tPU73YOX28INeVZ-JtoTU4vcYN_QbKdR9NuAWksHigYA_UjPYUTULhLMPVz6hLhbztpMTxK7g9-o--5_AdludyAdV1tUbF_blDtoPZhZvJSyiYgXKjRsYRUK
oVH6qYRUedPkQVXMlFDUMu9lXUOpwvNt8Z7F2btojtpQG_9F-90LCF0yk9Jb1J-kGmpytIfmmS-18y9f6jJ-qUNDN1J7X1wGbfDebEQxQmuYpb_fPDQIeNa4
VcyURdEjwAarmEOavHfIQobjMwimb9PHfw98uu4eRHe9hu6xgdjldCD2QcUDxB6DsUL1WrF6gMSq7j-fjkXagSZo-tyNi7T7umPWAVWGl4vqi6_M7zYMhINg
_HY-kV0TREX4YmfWixzadmAdj81mKIfuR5X34AQavZcT2XWItLhJlem8FAoG_9aHysF3WEEbLa85RdbOKDmziWT_ijOwwz7emcOgFA_ltFScaRJryVxjSdgD
E4wGFZ_y4IBN9tw-HyVD-Has7tsQvogR0sUUvMhmcPzTmCVtfs7cadWsp_U_X6dUBOXNu_jqVqM-t5zjjvduFSzGwGkxkB_xInq3TlT-CE0_Up_DV4Z-_ltQ
ARDh7YUGtTkr_DXfBD_nhm
}

EntityColoring(snowflake_icon)
!define snowflake_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, snowflake_icon, snowflake_icon)
!define snowflake_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, snowflake_icon, snowflake_icon)
!define snowflake_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, snowflake_icon, snowflake_icon)
!define snowflake_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, snowflake_icon, snowflake_icon)
