sprite $snowflake [64x15/16z] {
dLE5WMWn28ko_yPVwBbVywGQ701WZHRNu0Gpr-Hw-PxYArXwdE4bEhFycNn9DqeiYYUGW0-_n9wB04MSFn_lrGX1aSlVAPmP0oObC6EWZZH9eBgIbrur25Lt
6A1oNL6UgP0HV4me0GVepif2WLTvLG2ZiEBU1Q2PqNWq9tvgQ0Dn04HXXYMYfwssKDDadP-ZFwj_9In_bPLir03HqrOLhsu3wx-E_vsiNX--wXWOORJyqkj_
r_yu0KZeLVnfWGHufcVoDD0aU6ZMc_mR5z1p_GrkmAVwvtKBtFVVNm
}

EntityColoring(snowflake)
!define snowflake(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, snowflake, snowflake)
!define snowflake(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, snowflake, snowflake)
!define snowflakeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, snowflake, snowflake)
!define snowflakeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, snowflake, snowflake)
