sprite $snowpack [64x51/16z] {
nPG5ZiH030HtcAV__zeZInTqv3W7jGmL3NM_BiaJrRpK503eQjtZYwpr1mYdqpC8vGmSlaaQlo_-jFVrX1NjjcudriIxVYDlTj2hkQT74C62gAhHjsKTWcRq
Tjc7OUwFFgtFGH7hPcxENGRXfNu5uROv648zWCZh7Cg3QCOXDKKGHERFp2Lv_Dbo1taGn-bsLz4C-CqoGn34ayFYIYM6B8YxkBa9GbObIrWu7MYIqiYi3iJh
s16PqI-h968XSpfGHPLN9pW25pi1V9K4Y2bCQOZnJEoa32PsOZ9J6cASUlH4Lu_-h4ew1F11p53GLgMX8Wf6Bvb1WfAwn4v7eD9GCmsLXff2ezSJAXunWV-z
GCOZ-giyqkqx
}

EntityColoring(snowpack)
!define snowpack(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, snowpack, snowpack)
!define snowpack(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, snowpack, snowpack)
!define snowpackParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, snowpack, snowpack)
!define snowpackParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, snowpack, snowpack)
