sprite $snupps [54x64/16z] {
lTPN4jj038DXLl3-DmvJrnh3eq0f__kdkiskUKHMDxQP0T1TcU7sAOzg04F2wYBKgm_WOQLVJ1F1GiSl5DJmK3-GOuJmusuzKZYtac-M8zRd0TL7XApYV7QX
DCkHAxFI5UZ7wDgwSUbLkO5zsPDliMLcLM_Ot44-qMtnI2NxzxSLdKMLuQ8waxx2EMwEZbsSRnZ3uvWe0MFaWCGy2FCVmoFLZvGLDbbj7bajOVkL4toZ2BvP
4MdVBC54KKnSwsl4LdRVkqgBpRUFYAvYUAsxjimyb_AUD-NMmyA9Vi8QkNwq4vMPwoeVxPM-gcHbMq1_hUtHUSDI_kxwaGWk7FJOdfY_vu2qIxuGTqVHC99d
0M00bKUm8XjNGtPRLa9OMaxUqDMMqDNc1LrjWQEK2hhQ0g8wNmMkim2xrnS
}

EntityColoring(snupps)
!define snupps(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, snupps, snupps)
!define snupps(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, snupps, snupps)
!define snuppsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, snupps, snupps)
!define snuppsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, snupps, snupps)
