sprite $socket_io [64x64/16z] {
fLK9Ojmm2DHz0___RRiApigEG9jsSaSU60Q4ZGPhdRFM_0jygXrm0aPD_bTHGWLw05lyC8JDG5jWTH-m2vA8SuJupWszv1X2ohNZEq9MapTYZ7pBvFFuFl6o
vt39z9l3Ugb8adRyOXTxiAPkZnDDTCKYn_KrcPwCYeH2WFZbkJS7kB4jmUEaVp8WdLx8zt_29tJszIj0M4-cBtYW-soM062VnOU3TU1kQkj3VTRfXU9R2RtW
3IFFlXzSuvvj61OvcWm_26zJEPQ2yrADFDdf7d0H02VlysRYPWycAPpILwA7-ejLhcFo-hon-gS3SCaVXvtGzaMHPoUoufpWpiLBcloiN6gOkjWTqJbvjFeq
OFuOybMNUrjcOfOXE2UhlmgVmrkaOrazJq1mkBVVrSPWzVi6H2Uqxup9JF_1nyb7TNnopkc58ELd_mGwCOQJwhSez8yNoqIL_JT3Rb5ZUXPd6zry23Jr6ENX
1huYRgSUz5VQwxYp3KcyFDrgxIziKfVKLsKfyWPkkmjyVgUC5-qxKTukpI3J0wlZ0c1pFBoHqTzhg_nqq8Bat3fyOxa8O6_gfxMdz77jLBshJoezSVf508L5
lUZSIeXhBzSrMVcwgRsZ_lp7iAo-6XtrnrRsk4Jq1thPREKa3Bj8hqzDufxPFoWi2mWwstLYgwHjKxGQ8h9CMHb158UsaPITnu3FuvPTvMtA242ieVX7tQdp
4MgJRIjTW9QZVo74t80kz4E7V2SPx8sE84OOBFq4Ns2JkWRpENng0uc1qB8tluRr8Vv5yDf4_G4
}

EntityColoring(socket_io)
!define socket_io(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, socket_io, socket_io)
!define socket_io(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, socket_io, socket_io)
!define socket_ioParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, socket_io, socket_io)
!define socket_ioParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, socket_io, socket_io)
