sprite $solarwinds [64x15/16z] {
fOu9bg1024EJ2b22zx_l84xlU_Tt1VDVnDzO-0sKcKZA-3lP6sk47wEH1zElswUV-1MqwRviubT8QqbcjbviyGLFYMLkh_-VHNp1KsBiQrfx2upju_iEGhQN
2oi84mEIRxMoOn8-POjh-iibP2WTHReYiTCP1tO5qbPTinSi5MVlDJwMZuwAXSv0sNvle_C-Ozh1edBcuc7NFL8OTEleZQ-yX0vRokuysqRsyEYdhZiyZzjR
68WEbR0tYdspknz7EdR6az_VTBA5QlE9h39uPR8pElF8s_UEsQa7Fybi63dzJ_m3
}

EntityColoring(solarwinds)
!define solarwinds(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, solarwinds, solarwinds)
!define solarwinds(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, solarwinds, solarwinds)
!define solarwindsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, solarwinds, solarwinds)
!define solarwindsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, solarwinds, solarwinds)
