sprite $solidjs_icon [64x60/16z] {
bTHNOXiW40HGwXRA_QyRgoGn8n2xpvR-PgWYdCIKIwcrbb9oYi4fvVgFloC-HaQbM2lIabuhl75KShnDFfSpmqv0tDiGYqMo3UzlICNei9758RjdZzBkuX4n
i_0FekVThKSuXLo9PSMFZdF14azLL26lZufZF2vv4fKDrLF5ElqYUYPqcts4E1Ak82tvgZV2CFn2z4xeU06Jg8LKk3oGl-EwlRr9Z5HeUtTPpFXnSn69Guq1
5R5YAeyuOZ7v5qQPtHFthu1Jk1NeL_Ab898YUq4iB6h1pZ2I7522i7S2h1uI8PxL9q5Ur0Sse6Zxe3zUtzeGZ1-rRVJUnnYzjqyAp_ucFCQSy_tL6-0bddGJ
7hz01KwVb-mpZDO2FfmTXjSvD7t3rRC8Cuis26E1i3nmsJmQsiU4yARWYSE28NmskpmKE3iCdyss6HxMV5r13glSXfqA1U2PmcpRjolhcCPy3Lkrcngcnh0N
ULXGE4fYk00uF3PSLb73Tuc_xWE7grXFlw89yQFCpyS7qxq6iqpQnx-IntUZ65nY9cbzF3Ib54x-
}

EntityColoring(solidjs_icon)
!define solidjs_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, solidjs_icon, solidjs_icon)
!define solidjs_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, solidjs_icon, solidjs_icon)
!define solidjs_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, solidjs_icon, solidjs_icon)
!define solidjs_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, solidjs_icon, solidjs_icon)
