sprite $solidjs [64x27/16z] {
dT9NbiCm20LGEgXa_zkTWMChzSFoJO_zG0qMP4cCS0kBQBfPWaMVH0ZseBuJmStsdvXtselQl-oxx4n2evK8rnjvYVOKfb9Bm72LnnktoYDSX94-Ap3SpISJ
A1HHXJISwXCIvNSpOoWMdrmHIkVQo72IaQ4EIGq01aiO9F9u9t0QrOBR-TQU-Pwlxmr8GN2WrZ272Ylmbe-gRj4-E2pQidwL-ixdozeFTAP9QjY6r3ddGuZd
_94ySbg_yEeUc9z-_EMrE2mvzWZDZtuOSyvnVC_-ryWAFzASFVdEsMqPdYM_j8Yut5vRFyEhGCxhAfyvvZUFuGYNoPXVUOKDQ5zvs8C-toZiGkjpSRY3lKgC
ODZn1m
}

EntityColoring(solidjs)
!define solidjs(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, solidjs, solidjs)
!define solidjs(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, solidjs, solidjs)
!define solidjsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, solidjs, solidjs)
!define solidjsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, solidjs, solidjs)
