sprite $soundcloud [64x36/16z] {
hTHbmgGm60FWl9PqbFlVTbieypcivGV-K2zEuxezbkNvk2J-9bnUUUZFTLwMTtdads0FKqs_Xt_WI_x5BpfJ1a-u_UINEk6q59X6-zu_xK1NcBetfijB8Nxn
o-N0CqtUlNxmXnMms7nrNw7WyDUTdO-12on_x_DRV_l9S_S-VFxa7u3PjzxKVPpvvVfuBk_NGy8AOQxTXohRptxcQWERW-O4FUHYABjlFFKzz-6ze4x1s3rR
glkIgkd8BnSuWb2dfWn5T-zyE_DBbWyQENoklcs-VijVsQbtsbpLgPIjs0zQFS_yKrcjat5W9wrJIZKyLtzR3gFYeDDpkkuvpZhrp5ACycFuMV-MJR_N_WSZ
PQ_sl_glCN_BjxGGPlz7Sz4LepBpFoV-wO0JybYzRFFob-UX9xelq9rGkC1wl_v7FIu7l65BMVVquTDa-_v3kGxylJ1ZW2CCWV1-y40w4fv8ZylrkrnQuh_5
R3qUlZtu8YK2b08ik2nbeBka04egCBhUlaWu1v7lNkc9adSsVIl8lNdAGX5fsu-yj9M0abExfnXGeflffHmUK1RHCxmI9cUkdZ0vPhnMQTCZcUfUmwK--PhU
PPisPiXJoIuL71vixYqfk39fglJvhX-9KegOAIdNeyzZzqPpYOuEbA1K7xwGoeRz1G
}

EntityColoring(soundcloud)
!define soundcloud(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, soundcloud, soundcloud)
!define soundcloud(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, soundcloud, soundcloud)
!define soundcloudParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, soundcloud, soundcloud)
!define soundcloudParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, soundcloud, soundcloud)
