sprite $sourcegraph [63x64/16z] {
rPPB6jqW24Pv4zt_VljkO_qDLpDgppW7GVWYj88r8epf7HhvdR1tTlxcZS-HVv1ptVB6ptKVz638ZQdcpXsoPs-zjvGT7IzFMl-9RzQUWVPtYfP8Zl2T-Mtt
nbNZ1fH-S_K1gul7rcKVoSFYenTwKRoix1v7hRC-ePjpbx6o6nNer3hjvU5YRlBOEf4ssxRus6LTV83juz73jwwChUip0TSyHP1jsn9m7JA2p1DwN03snJHo
Q3UcVVq2Ms10IwvMpwg2KKImQi3h26kR6FrrX1Qqn2AtU7mqvV-A8Fz015gYhLsLX-ylFeHR4G9j_c5lHi3yh-_cTeJPJlW_dEZHPqvETxGFTElFgQlwXwlN
mauZOeWWq72mXuFc25RQC69_HmY5SHbnXaJl2ExAC2uZ0LjEGK3cnOe7CDnQiU8XEjjSh7Y8hPyotopULa_PVl7IHxHOyG3ecnKhtkVZlLZngkhH9eMvVKBo
kvnQRETC5Im27mISVeGLjPTWzahdA4pTEz_e7MpnUs46lW8
}

EntityColoring(sourcegraph)
!define sourcegraph(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sourcegraph, sourcegraph)
!define sourcegraph(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sourcegraph, sourcegraph)
!define sourcegraphParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sourcegraph, sourcegraph)
!define sourcegraphParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sourcegraph, sourcegraph)
