sprite $spark [64x64/16z] {
rTI7Rbmn44DHSIR__yjfmWLCxDERfRjlukwpbDpMZqd3k-8a9P_xHgxbLRrbNIefu9A_fweIxbxm_FACfwUNZrTz5Izuv6NZ-9XNpF4vH-Cbk1Hgnl7fkXZF
EUMy79CqE7YvfeaBNl0-SYqzUdYTELYw_bMLy5MDv_9Wq-OtB-rnys2TkPRn8hY4FdZuFhhFwsbk4ayZt-Cst_SSppWUdVBjqS_ECuRlFHroF8y2Hz_wjeOl
_SHzthKdk9VnFlBPmztlvrmkurGQ_tH9Dtmty3vMWXzxE__riYk-RceWsULJxdxcXJ9l_FRoVVRmtM5-yhhtS0lkUfudu-Z4Em--UNWuElO3fpfu-1ggFd3q
a2vz5Ngi-ygZumF0PqZL3znqV8EAD2UWreeJH-Yk6FC8wAm_
}

EntityColoring(spark)
!define spark(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, spark, spark)
!define spark(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, spark, spark)
!define sparkParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, spark, spark)
!define sparkParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, spark, spark)
