sprite $speakerdeck [64x40/16z] {
dTPNWiD028DXmHIa-nzuUvy0Nd-lv4zpmVZWAwX3JBnQ-ein3Tz6AB7nYZfnueDjvHO0hEAzOQ423O0NNyweaXUlcG2s-XvClznGmm2O4WkXsWQ0gGHTDHg0
uaDsNMyhFrwYFd7u0U_yjn6FUiTbHXs8VmYTx5PFVGgxqszzuL-nHjiFbJYR7bGjlEwd6XnbZr23NlPEDLZs65HZbNt_3MXb3rjKQTOzO3EeN9Jz1yilKzPz
VvdQjJxz6B_Lfv_FiZ_N6YqP2F3Dn9__VpmO29FgBMIBobNfTrZeaEoWyN125VeTvBfWvX-Fk9WRRwvlpdHZX05OAct3gvsF9fNXzlG9wMFq3
}

EntityColoring(speakerdeck)
!define speakerdeck(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, speakerdeck, speakerdeck)
!define speakerdeck(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, speakerdeck, speakerdeck)
!define speakerdeckParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, speakerdeck, speakerdeck)
!define speakerdeckParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, speakerdeck, speakerdeck)
