sprite $spidermonkey [64x9/16z] {
bOjNOY0X34CbWq4kpDp_jils97zvLAlW4o9W5V_cbGHWwVZ7E0CVoQ9huJSJb_6_pwFV4VmdFlLvtYSflqkS0dP8626wzaOTmax050ujXTt-2ZF9zjq1rFjC
8keEBEwm29IjOBkG4a9NSAlXvygt7vjtI2z8N7NUIfE3XMGQXiQH0aKWBVqMMC1U8s29g88TAP4MHB_ddTktC1F5S2YimNK7tEFF68acSix0oFjgiSa5By5M
Fsy6TqNPx6qLKMDdkdTWjR2GFMUc43NKk-NjAtC1Py0CD09ouZV4XSGN-6KamFmtMjV0Ds4ryGC
}

EntityColoring(spidermonkey)
!define spidermonkey(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, spidermonkey, spidermonkey)
!define spidermonkey(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, spidermonkey, spidermonkey)
!define spidermonkeyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, spidermonkey, spidermonkey)
!define spidermonkeyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, spidermonkey, spidermonkey)
