sprite $spotify [64x20/16z] {
lPG5hk0m34J7G_S_yYfMbZxp4nIVgKsmq6rhuaCmlUGZ4TH_qCVqZmTW7y1NZS4_f8r5KaeFmM5a3HunmAI06opyB-7u5Z0z-F6a1TX75nQtedCmD_fQBZ4c
E2DkP6e0rHpEf2BtRhiasGEHPdtz7Kxka3LjeyOz3F3_nEWkLpJFWUCZXfDIzKo3FHLOhKyv5c__1UwPkCqqxW1Jim8Qk7j8f__YcUiVfbNrryU__i1LZMoX
ixDm5mEG1qZL0Aot3bN7d-jFMzv6lVNVyhdpEvXjqmvoZi4w3P81l9McVz5gTvQ9m5hn052YFNWiQ6kiNlj_6RsqQEU9zMFymvZF-lOyiG3zq_l7Gd_K_WK
}

EntityColoring(spotify)
!define spotify(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, spotify, spotify)
!define spotify(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, spotify, spotify)
!define spotifyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, spotify, spotify)
!define spotifyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, spotify, spotify)
