sprite $spree [64x26/16z] {
vPC7hYGX50Fz4l1y_mEl1OD-pifRIfuIDQcxSV0C_8Me-dzxzzsRurTOLaIbLmP-HTQ3Nt-1l-G6MBx9xUsmzyGaE_TFC5Wl74Qp2w8q1eGlSjehiHmK3S1D
5UadboF77GkmCvw4QsXvZ4dchgovi6awl0USxR35L3TW5KzYiO1Y0xXPKdvplqUf0e83wvYy0YftUhvjkkZZZXc--zh7fth35ZtdN9n6Ja42S5uA3uhajFVw
mx2RG4m-C5mic-kzVeHm63j2R6kH6mUUiAQzxIKswl64xp9mIKqbwfV6ODq-jl02cg5Lkt7IWSM1Wv4Z9nj5hffKswV7aXXKc-GelNhgvyk_Z-qexX7g7hqj
Yd7FB3_M8Fpb8tr-RbIQbWSUIFZJcRDYz-5uXVflFlyPKLM_xE_p7tX5TE1RXEfq_89_
}

EntityColoring(spree)
!define spree(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, spree, spree)
!define spree(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, spree, spree)
!define spreeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, spree, spree)
!define spreeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, spree, spree)
