sprite $spring_icon [64x64/16z] {
fPVdelCm24C5IFJzd_WR7MHSafBSq_7B9nZPMJZ2WyedOZWkOV5K7u_bNs4OuieMEGQ4yfYuLRkVGpHzCxz2U-l27iyHZlye7LiYXyIpl8WDp364oLoDFeGY
BAtHXmY0sFG-nBOhu7aD1x1ku8uEfDzgNlRHU6VsN7MD9yeB10fBkvez3IlIhvMNewW0_7Bj8ZGjBpgAJO1sxabakA4d7T5xuMRuIWRKnZH4H1VJ6CgRsdD2
aHk84VxnatVqYjPJZ-iwQfnjV656nEAlCOomjDRdVD5Rtp0Y4gtFyPAZyCpApp71Dod7Al-PNctkzu-6Uc2555VysAUKyWlnnRwAPTZOD-rrU1eqzBtkF0jA
84Rz6niTIS0cwnVPwP4EG5-thwjly5KppWEmqC6ZOxoLimQSTS_UOvc6imbOyEovLIKqeyofyoiwbyHYUm2BSWzjS5skXij3kKPXWxresT7BDM7VFpdJNLdG
xVGD8TepKnyPFURi5ujfTPQ4hNbvPkwhN8KzB7-0y9Edpw7UOZRJYHxF4O4ZJFDdm9uO5Rzz1Dflta33CCEeNF6eBJcWkG28nvN_0W
}

EntityColoring(spring_icon)
!define spring_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, spring_icon, spring_icon)
!define spring_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, spring_icon, spring_icon)
!define spring_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, spring_icon, spring_icon)
!define spring_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, spring_icon, spring_icon)
