sprite $stackbit_icon [64x52/16z] {
dPO7aiKm34A397p_6szF8uicDbF-Ju4HpsbR9nG74zkQKED7p2LxZaECQNTmN5LOSrVi9Mg--2XSifYJnGcPXl7MhISdNsBGOH5IgIq12kxSvp0O7BQRfT1Y
q8xKaGTBs1JyYgUuzw45WtFBCBii1bzSLT2UZnKNjoh_mm23JQKOTWyrMzHZGEhreken5Bz31PkJaAyx5nYtBG7n6t0s0GRAAnL0WU8Ifg3aWbclZKKnbXFM
CVYhQqPqDvaNJm-nHSrXOEZr6pGtcLqhx9ENd6v0wj7u-I-TBGQJ7VUB9v_N4wNuRNTkfTJqr6ekCUx7vTXrLFfIjHUnr2hPFy1jWiTsvoEPAJjSyJskIJ1k
zns1eZbR4ndT1u0cfC7sxXCYFJQLBeNxi9dwXEgngNGftXRt827GPnD6ZqsboEHgcr9CG6z0ziK_0G
}

EntityColoring(stackbit_icon)
!define stackbit_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, stackbit_icon, stackbit_icon)
!define stackbit_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, stackbit_icon, stackbit_icon)
!define stackbit_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, stackbit_icon, stackbit_icon)
!define stackbit_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, stackbit_icon, stackbit_icon)
