sprite $statuspage [64x47/16z] {
pTPNOkqW30JG4GYD3FjVRthYAd1v9UVh5eziqt5CaXOZ_Gt9ebbmckH2tw6TgY5g7g8cT2Np0Si8PVe9LEccnwZz9nzZneeKlyXI_z775D-AtsA2Ts9-4nE0
HBzFaVsHuW-PFqAXn_Z1EtBKVYoQ99pGSnp8H-44G9IhBz4GqiCfgbv_JELmYXW-bVtKI5vN9jrNC7opxTJKkj6gRMSA1J-u7jAbjdq1hX-M2JFXt1uVyGEL
gycQiPGMFwNQ3jMok9bYBVFdWRm5gk2361KXRI7YXAc5gc0erHOh62gjmp74sc8JXkWTb6Tv__rvyzZa65AVOeQXrCcxOeoTlE3H2nZEOBVrnv875EUe7pAS
LVm04GZQq6VltmnNPFgquAwuIEbpkWYko-MZHF_W_0e
}

EntityColoring(statuspage)
!define statuspage(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, statuspage, statuspage)
!define statuspage(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, statuspage, statuspage)
!define statuspageParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, statuspage, statuspage)
!define statuspageParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, statuspage, statuspage)
