sprite $stdlib [64x20/16z] {
fP07WiGW30En9Pla_ny-Yy1jxzf2yuHnsX6ZjH-2Y1zuPmJRorXzhKRCoGg4ZpNw5N5HLXmJZJsRPPxTpcblVUUb6FoCfnMBvicglE19yTpsT_ZA1T_4mxpl
-xxP0WdJFu6n16pn7X1laSbJ1wBtc7ZHXVxp045oyJsAhsHV5fwY-v8rOBxkuU-7mnKVTHprNy4czPJowiZjrB_0oXNVAcCu6gUpWYaWVp_nJS4vFyspD-ho
j55GyTK2OQzvlOJH-88u29lk1X-W_ktA7pefl6-xjHaBaaBXJfWOzwAezHNV0z6xwm4-SHq16cV_cb0Q6Y0-nLF-w2LVPr4Z3noPiLfPJdCyBUVF_ckaaAWn
CcdjYqY5d9T_4sCfoE7hU8Pz1Vu1
}

EntityColoring(stdlib)
!define stdlib(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, stdlib, stdlib)
!define stdlib(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, stdlib, stdlib)
!define stdlibParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, stdlib, stdlib)
!define stdlibParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, stdlib, stdlib)
