sprite $steam [63x64/16z] {
dPTNWkGy28GHoeBY_hVzWtj7GmTZztxFBeaam7G2rx4KPWQLqJ9zGnaAyq1dINGBxcgVmE0RuW4x0pDJJ8T5O4GkPB4hjD0P3NOD1drcsZrMedVIihi8lwl5
xgDl-cNV8Eaxlw6gWFEVF2tMhiQ9A75R-uJXymqBa4oR8lO0bJPY0Izv7lP0j_lT0ZeTSCxyh9_qW64dx8-Qm0pIV9YHtN6lU1DPZj3ZJy4aTT6FBsz4n6fe
JCGDZ-EQlxvVNRvsbR7OEgvtZkc5vyN0BiF5UP-8YWNKuzlXqpPTbRKuS9OFwmfjYYdzNhb2sm-h4unfmz3qMwL8ORqA_I_7ano-o4kp4tPcn2fjgeaptiQy
hDVXN-UoxdCjOgUidQpwUpdOznRLC6u7Ox_E2klFTRfW9pJVYbRBkIsp-V98A0z4fX_yV8B-sbo8A3K9J3_W8QhIcLp57z11cNWhrqqq3qx6yhev1jsnLR3R
ShevlicJ9yoa5_wWJfpRUvfUF-gDFb8Ki3T0xwGXQnPwuYIxGX_80yzZbELw1dXIKrE-NXigfTFq2Xsa6JsBkSfdFQmyOXQsasgcBP77TyMEk24ad6nirUHY
Qm3lvmUfwLtEi83rDAIqfrVZSoWlBul9U0vTZRSEUTqjX6Yqz9CulN2zR3D_g9I1aHDNDUJOzhNjL3THive1Z-LLuh3_KE4NjhPKfQMBRQtvA7zOerZYf3cS
cJX-ErAPi7Xly2HzNY5X8SZq3Ai5XEfO7wk_NydLgJtpRtycVFvZqEaSdXQpCeKKiNEaqYNbPEHZEN44Dy6hLZhJVRWEmPRETgRz5m
}

EntityColoring(steam)
!define steam(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, steam, steam)
!define steam(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, steam, steam)
!define steamParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, steam, steam)
!define steamParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, steam, steam)
