sprite $stenciljs_icon [64x49/16z] {
rPOraWD00CEM6Vx_sokFuemt3gfNf_7ON25kG3OCOG6zKhf7UgDqX_HEwNO2VLXA7v9kEj2de_G6zEKflMfwsO18wHdfYTAJL2sEld3HRobwM_jbYla0QZ-b
WMf9LW3LaaHGBGG7cJKzdUi5L4jIGRKa3KmrIGTJ3S4pQgUc3yR0AzpFgtLSzCmAbtNAZEO7rfft96I0qwv7qwv7_-JhCPrqFTPBhySEb9wrwv6Kww4VPkrw
UErlktbBjLy
}

EntityColoring(stenciljs_icon)
!define stenciljs_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, stenciljs_icon, stenciljs_icon)
!define stenciljs_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, stenciljs_icon, stenciljs_icon)
!define stenciljs_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, stenciljs_icon, stenciljs_icon)
!define stenciljs_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, stenciljs_icon, stenciljs_icon)
