sprite $stenciljs [64x13/16z] {
bSu7cWCX34DXOTF1rlrlkvJjFN-Qaipx65oDX-B_2bkezMKV2H-r9lZHf2dvFi_uA93nV7vfDsrHoBFiU9VBS1yAftKKSwj0cRMVWJJTkY2FUi_NSkKZx0ET
xdHrSdRIo85EqicApCr2vP3THxxNiKIwe8_aJ6ign1ZR6g6lpjc2Ekjph_ubXv3MIu1J2pdd95lR_oLQeWT0L6uV-Tx0bIPvxZyMqipcBAVFj4p7SVjSbrAl
yfAN5AAphFuUbukyz4eceCzoUnnZBjRst0fP2vbM3wErIRxsw6IVfBxh9pSJlEXSQjYzx3yjuhKF-q_FUEl7ntpJb0GGlJjYRm62ofufXhjLNmwZx_cu9m
}

EntityColoring(stenciljs)
!define stenciljs(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, stenciljs, stenciljs)
!define stenciljs(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, stenciljs, stenciljs)
!define stenciljsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, stenciljs, stenciljs)
!define stenciljsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, stenciljs, stenciljs)
