sprite $stetho [64x64/16z] {
fPTNqY0W28D32_S_yVQ-4lp7xzK9KaV4X4UI_GMoqWqVmQBOVyEyDk75Fa06BWZs21CBpfOiFYHxeqnUliFGaUyaJcHVKrg-KoVvYu5G2NEZp87EFEteNU0F
5haVlVejhvwngR2yyZxctEIDzu2BoDRS1y2jY9JHkquju2tTpsqGQj7hOnY7imoF57fPdNBym9SngC4k05lJIu23FAh9iiK1ztDQhNvtUGXzdWuTHZbzlwbJ
-2p-sIIgn6HlbCmX-yQ0iHz8mFi1kipX3WrWFr2Z0vTc3Vwa3zZWsPkU-UO__JP_qIVIRXk0VS91fQiiVc_0cEBARL7nod402d2AfeEPV253pAO3INOPO2Mk
Y37bHKydRVIn0CoPTGO0hnfzTB7w69A00Tb0oIM8Kb-JdgwM9qTyhq1okA7a_f80QOwYmyRaVyTuFBOYcw7UE1510V080s9VWbDiwgc35mrQuP6KmUyxu2H_
C41x-W2KuKZq5Vdq0MAyVC1O1eb92-LGQ0iinnrHFFIIuGDu_hP1pX_upm
}

EntityColoring(stetho)
!define stetho(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, stetho, stetho)
!define stetho(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, stetho, stetho)
!define stethoParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, stetho, stetho)
!define stethoParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, stetho, stetho)
