sprite $storybook_icon [51x64/16z] {
tTG5aYCn44JHmgpxdtYOKbQ6tCixFsZ0hrjeE-Nk4VPI0uCKdydCgcu0ynpUo3nNPiOVsSHah8Ox4nAg9a8TI5qZdjT8MJoxDu9x2FhpevheD05mWQ32xJcF
mZq4OLyBp5BVhivQ7qZQRIK8luF3Q0BRvlnOCIokDJ5Hq7Fv-7rMtK4ZsvDQXkAq00VYo--jI2wajriJ_1OU2SwabpL2-7EHDOg0ZwF8wRTGHqkJvdFIYl1h
gEW3eTtJKxBXi1ehGNXiN4gYhrai1BS68Tx3X6jdquheqRaaUdIjI6VuKn75B-BPa7T-QjAYdGd_xcTIlAjCQaloNX9yaM47mclarUKq_Js1KMfVKjyM6fSY
BKXfCgc-nPbGSHH3l-_VatCWWs204OHGPxYRUsJFRUPpw7iJ-pC4rqbU9rQuI9xpfo8oivxgRW1QbEtYv-JxO_0g7W4
}

EntityColoring(storybook_icon)
!define storybook_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, storybook_icon, storybook_icon)
!define storybook_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, storybook_icon, storybook_icon)
!define storybook_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, storybook_icon, storybook_icon)
!define storybook_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, storybook_icon, storybook_icon)
