sprite $strapi [64x17/16z] {
fP45aiGm30J70iUMvl_lFMafnxGTxgeEA7W6ouLlCS5tB1B5a3juIwJYEtGv2ZlcZN7rmznwJxe2ghq2BKL7R-BUPgW0TN7SkFKI94CcYnoIkRXkCkdOVM0f
J4Rb7_h5E2BKel8Omk90CFScko-zThdkAnTxrs-kqMSZgK3rMuUnPs7NFWJLvkY-K2lcsJkPsm3SUm4EBXJ1xkVjvivupD_F7hQJzFFvuvCUt_I2iHXlUcVA
-VvNCURd_UQUmGq4OurhFuAvrdr-STpczxO_xjzVzBWycIB9rXejR_-FnSQznsE8k29pUZUGLZSzlAJQg7xAd2t55Ctz9V0Rkl_4Le_dUloIkUop7l_Y1G
}

EntityColoring(strapi)
!define strapi(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, strapi, strapi)
!define strapi(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, strapi, strapi)
!define strapiParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, strapi, strapi)
!define strapiParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, strapi, strapi)
