sprite $strapi_icon [64x63/16z] {
xSl10KC000J1kmNzTvm20FQLnFmd6yRbid6ZCotNRNJtSH_tSH_tSH_tSH_tSH_tSH_tSH_tSH_tSH_viu5notpvbotJp__tl__zxmzRneqzpxcimmPkVDOQ
zHlr6_KRzHlr6_KRzHlr6_KRzHlr6_KRzHlr6_KJzUD-t6_MFW
}

EntityColoring(strapi_icon)
!define strapi_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, strapi_icon, strapi_icon)
!define strapi_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, strapi_icon, strapi_icon)
!define strapi_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, strapi_icon, strapi_icon)
!define strapi_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, strapi_icon, strapi_icon)
