sprite $strider [64x64/16z] {
bPC9UkCW34P_xJ99xt_TgVaI7CR8Rbvtu6cZe834ipsUlppQ5ihu1jBuLNyEdi_cVmuXqNxvcNcqbaQuHxFjP9lrlhhTHf1iB_pngVjhTLDSGDu6cpwFzcqR
wyceuArzuFOSUhH1NO9kROBZ5I2qJJXMMFkFfAthILkR2PpnTi9eds6ZEEr4bNs6vFdp86s3Ce2s5G5_oAX-mel9pmW4qPOO3gZGsqRGQekdvWiOsGfowEoM
fHzL_b2yy0pL_CvtYo1q93BJIBTL_si_n7RddNudcEpiO-MdS7U2NkaxeI3_WxyfzANOIByJJk2uyJS3URmD01Gv20Oahtmdo264ZF973zCxplbT1GCMUM17
-KSFW6rluTDF0JZcuwFygIQGd_ojbnOv4Jm23i8m8Wn_ixvsEgoQPteF_IeSiDVOngGct79127OahVl10CXYTT9pHHWw15ZsO1ovf5fsnWWn1bVvHG-3CRYI
keSnkEznnZouklww1wfFtFjywtjUO5StT-y7EfOrePVTToYkHXprtX_kp-hWGG013C3h4ikzK80KqAix389U34ztNndGA5laAAzUkczALGUXPNC6i5htJQii
GTLqWq1gRry0MoVPYOKkNJGbz1yCYcMFExgSY-wYTR_7aVeV91Q1vUsflNxn8lrY0WPMctnJqFdK6y-90Bqj7hv0uppyrGi9wTBmnw--U5sB3Xooy4s9Or7z
wOq7yU4mgRrHs3JxTO3GJqN83fHYw0JC-DXHgtoHc6Qtga34Aj-KRPszOtjm4xKFXDIcU57g_HP2R49vyaqrmr31RdhjcxhW0hxnLN23g4xdPvjm3wkkV1ts
BNGK8KDcV0EnQFTlCly3
}

EntityColoring(strider)
!define strider(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, strider, strider)
!define strider(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, strider, strider)
!define striderParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, strider, strider)
!define striderParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, strider, strider)
