sprite $stylus [64x39/16z] {
dPG7RYKn34Cb5rc5zp_lmXGcs9v9YFw_QJuLZtn5LWYLxqe3I6pvhX8uKk_yVw4yG8hK6tvB7FbD4y2KxI_i0SJVw5taJViEy2Ub0HXoNbG_02oXLCUyKj6w
pPjlw1sejOzdLLM6-pdQJFef_LZckAfqMqD_PZBnARhzN32B8teoJHxfj2XGjORy96qcFLjc0Lja561QDGCVJQCtZp7fQcusQsTD1N3CECFeMPGuN2AbjO7o
FRhFUeavH2Odg_T37oOFOojGyi6vV0bL73EJC3XBBCNDvrhnpg8LB8MYzCQk7jueEdYeoEGYMia_kqJ59NkaVX5LufuNYUfuupNL2-KiMxIwH6SnBKt4AXpj
f5dPPV2QoRp-qRea9oeHgNDlFB3T-15zzsA_lVFIoJJ0CvRTZLRT4vKQ95qLNLkoHyLpbeVu6ONIGDpG-7db1tiIDwcQ63UvyGTMSeakHgnBuiy0FlPYCM_L
8IdZGuoNXtEALRC0TmwGdivlGrV8oh9lmsA_jfMsVoY0Ci01Lv5MTOlh-dPDTbQBmCndDwtogCWwDcH5dYcFc94owAlDoMXwS52ZMDL_rPswFhDaOfNF7gOC
soe_VL3MsjlCRAyrzPhDMC3SruVLnCv7-_ZcCeyi_2xdGrlit6B3WjkOIxeQ6VlGzrVLq0HcDs1UH-dFFHbshHL-RAyvnwCv-OLpbTFB7DnHIn_4NJQKT6Pp
gFn7TUaVrlRoKxGOBv-AentFKz0TG2LgySPtN-iuH1LTWV8zTyQGVacVIvrDNp9ESQL68fxlq2lfd2epohcFkoTOf7-hbMKDknhRMT1BpQWjBUs7Rr-nhp9v
j5csVGd-v_tWo-7sVajS1EIMz_e1
}

EntityColoring(stylus)
!define stylus(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, stylus, stylus)
!define stylus(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, stylus, stylus)
!define stylusParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, stylus, stylus)
!define stylusParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, stylus, stylus)
