sprite $stylelint [64x61/16z] {
dTC9RhKm40DWPoVhtF-s5Ng41YSY4j-_jda3PMnmyNAgs4foYdZoycEmKsLnWI2N0CHiiAHY0QnS4luTqXMWY4IDMMZIrF3Hh729SciA-VmdWBZoEoroAwfl
PE2GvLGT1YPVLzSoA1g0oZ9Aw5zdhReeFmrUHjL05tcezxmSjVqSSiydUMWs2p7_y_T_Ml-uRlBK-FuIyZ36yux7BP2-pnSzfi_pyPuNcgS6-ELySzfS2irp
XTrYFgf7z-RvY5kQvhFXxa_pLVFuFLyT9YRtURv0b558O_cjnSrLsbzHy_ebGEEM7u-fj94f02jFsHVzsAj6byCXJmUWYZ27YttCQs7jF3DDI1g3ET1vOHwd
8AJYPlIKydoV-Ht4IkFRAFmeFWbOi48iz_TMi33l_b-alIhCoiizLEK49xgzxOYA5J5nxoiwA472ZvX1A4GpvL-fUE_Fvxb_PhCVgcVc_eVDUgYVJT7xbwbu
Z4Eqp_TVjUbiPkTsMRCyOdE8PNEoLgOApmSQZ6iuHwIdP6SKKroND-5TNbOuRQBZ6l8BLZVHhNvKlrZBWRquLbZhSIi5s5FrFy4eBVIbq2FjGxJz_Udb3TWQ
otRqzyVs1oAR6XQeSWQEOryy3l4QKCu2A5J8FJzEwAcFUsaOyUlYxKEimxKio8RzpxikYhTtzC3DidXxvKeyBAFRCqsQ-bt7uuiWOW7L9E6RB15mqXI-qQq2
KIo-SasZHdoNl2d0TofuYrT_
}

EntityColoring(stylelint)
!define stylelint(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, stylelint, stylelint)
!define stylelint(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, stylelint, stylelint)
!define stylelintParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, stylelint, stylelint)
!define stylelintParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, stylelint, stylelint)
