sprite $sugarss [64x64/16z] {
fTS7TiGW30HGL4PEk_zvmnPYX2oU_3BfsVqqDz6oa2XWFO0AKqkIMLi2eQhcWNq0BcbO6aXDvm5lkGOUefHgIdHn29pmuYe8h1gzuZLw-0OYFohUD1tySLIy
QLYwke-B2Blh3NHoDU-p9jnBSAE_xqt2wAlUpu3D-_tausc4u8i1JTqxh_8E2u_VMEJvQSiA8BRBb6Vk3frJu49KzCRnkb7QXm6tWhfuQfiylC5D07Uz0yJs
BozotyyDg6QUcGPYTlEV0oI-ww6u4MVUKlzuyzkqDdjTm5sFagV7f_-rxklhl_S7H0vPlEVO-S-Vx--VnLFm-SFne_jlsdhrd6ZszcaVd-lyFH2RmwT__CQg
AhHuTTrpueaVlx5A9pFtrwy9nLlFtrl7pqa_-fyzD-HtlZyqx2Co0uJxbtXFlhrm-SQYXvfx_pgQPRtZ_Nlqwle_LzLFj_L8z77zXfUB1nYsdfr7V7urgNk-
BCDGzg7xE03XLxftFn-9i_VD-ZEPn_bWby6kyCNmt3qkFIUbRz7Bjde59JuhWJNfNwuz78uDF9o-om5EAfzj0n0TJqYat4TXjUZ_DY1ItW3Ttu59RU-JXmGR
hHH5lOMWix0YTirtj-0uhQJu5m
}

EntityColoring(sugarss)
!define sugarss(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sugarss, sugarss)
!define sugarss(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sugarss, sugarss)
!define sugarssParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sugarss, sugarss)
!define sugarssParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sugarss, sugarss)
