sprite $supabase_icon [62x64/16z] {
fTHLOYmn44DH6QHXz_vN-p39O0Ma-tyQ38MoGGwuTKesRzIVQED0JmLwCD2TydMZ0aq5UYhGWu7kbAyR5MWgq5E17WnqftpTg41F1Neoq8FoTQCAxM9nbFLo
nQwjhUpC-gUlkcv_FIQ6tdJzQKElVvhoz7PTCLCF1hfJhbvebAq5ojO735-V0ShLgmEozKJmxXt-D4rzl1xnkakzOlyQDFJgro7Eka8Jrrgl6giU2r_NLh5Y
lhwqGA-1G1FVRXahTktoY4y8zAKbUY3GmeywFuoYG9yHwDKJFH7e7G9zHA3F2FJgYIQSJjSLi_KHNlgtOWrcnssxT5Jz1W
}

EntityColoring(supabase_icon)
!define supabase_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, supabase_icon, supabase_icon)
!define supabase_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, supabase_icon, supabase_icon)
!define supabase_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, supabase_icon, supabase_icon)
!define supabase_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, supabase_icon, supabase_icon)
