sprite $survicate [64x51/16z] {
jPHd6gGm34C9E8N4tF-uMxMi6GregdxpdiiNCvrapgqFtpRtqLknD3sJfVv6OxoN-L4wzm17HNw87jjfXZGiVRjCNoxnwl_R7MijsSnARM4RNjCfFU_5VSs7
TILhOn_Yh0NpVr-KEpMITOSytyLBM99OJfquZUVZPBImfjlkLXIt2pgigASZte7hHxRIby1XbQaaI0DxoGyTXmS1SCJjOHm2D4y2XKC0d0GIXo1Xdq6mQ3mA
0gu5y-2BFXhvQV4pYMcJ-H4dw4fGmzaHBWLUS1IC9yeTGTclYgetlqcZ3b0z23pHFL9Zky0pttMZEoCS0k12m3W4mAM0SGZAoU-F18HJb23YYsb1Ze9Rt2u5
_FxN8vwpBLU2ys61vsppXQ2-Z2FVnZ6zplmcRlOUdhEzX-Ti0bTyDe5hWS2rGE1Qy1AEjX612u70jK3Z-is_B52u5WXS2HJ-4m
}

EntityColoring(survicate)
!define survicate(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, survicate, survicate)
!define survicate(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, survicate, survicate)
!define survicateParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, survicate, survicate)
!define survicateParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, survicate, survicate)
