sprite $svelte [64x16/16z] {
dOy7eY0X24C324JkV-0ru_R-vzc5Pu6m93lmbY3PPE8LLkHwXlNoydB0O6mys0hrhhdRQN7ukdENCboZVRdSKJGSriniWu-SMQU9K01Y7e3Km9GUFAmcn6vu
sHaBYB4Zf9dXgsz6QbrRsqr3iIEAhElJ8783pVi68V_I3SXNBp_N4sP2-1w6nl6hpcR_niyXuuiLfsVZ4dp-ljF7vBFgjtwN8ybqB_PNNv3F1uhur_l9v241
__B_nFLzPltess_yXhDTEWCYPyyyqts5EUoKhubytZpHD9XMvCB5C-rE0YBMmG7JH5lkKByUM0P4wmslIBAQJBnbaRhy9Py
}

EntityColoring(svelte)
!define svelte(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, svelte, svelte)
!define svelte(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, svelte, svelte)
!define svelteParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, svelte, svelte)
!define svelteParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, svelte, svelte)
