sprite $svgator [64x12/16z] {
fOi75YWe2CG2s1Nd_hVTvxRVUwp01DRY3vZztZvydtFM27v4JECJjkRIigkr9HN08emm07-Luw_mm9ogvhp2uFKZvA70AowfGRcIoavWN6jNEkhuaJ8FHRfc
MzA0awchUvK0LL90NlT2KSNk3ErIKfsj5alFxy5IYwdEqQurCgCmZpCoWQrH3VBGv4C6eMwQG3w_y6-Hd6j0hM1IXz40coarck8Svh--gmFd7zyrNf5lW_Mn
2sCxS_4FVW-MNPMY7UMeSzCeUdw5V8NMFpvRsW3jEi2v-md4la2NzCgcUwJ4TRSNAPNEkG1sD2WD3nunzge0em1OU563CbVj7M8k9yRg1dtmi7sNRl0LxCpQ
yXhVfytszOWjILduDdy1
}

EntityColoring(svgator)
!define svgator(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, svgator, svgator)
!define svgator(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, svgator, svgator)
!define svgatorParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, svgator, svgator)
!define svgatorParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, svgator, svgator)
