sprite $swc [64x23/16z] {
PT9PbkGW30LH6OE4GIZslzi-gXomi-EdvbluOH6fCuXPvTL5c3mwRC4kcZpglEgI6S03E1S_bPy_NrtDuSeldJb1vLi96FgkgLgWTnr67JxgzG86gpw0GJIR
_jVPfZiqsUNl1q1x0MUmgc-WW5wykeniogt01j4Nr8lSeC8wDz281iDiG0scTPLxe0kLieWVe4bck19vIoHqo4-WpfGNCFu7bDMW_lrz1PEVdAcGG7o11lu1
JcYUG04TeF9CGJkC3TWRM2_0yPfdaq7iONVp2vp_0QzpCsiGPmdsiBl3eTs0IG8ANb-0Ve2zonDOq7Bw9x1FO6_WsBiyAc-WR43tltq1emRNVPUirEC3H0qi
RpaVyWkCz4wH3js8Gzf-hFm5eds0FfYIm5x9e6oWmldOfG24_3KO7PTilxy7jAl-0GKQLBa3bJ0GgMOTR3Ba0VG9ZP50Tw91aHSm4-YEDv0BI7DVx6TcI3W1
G2-MP9zXWJPP9wpbL_MSvmRKxguA2GoVJVUxRmbSFbi7hM2gFHwtsY2wwW3li4nralDiO7Mr2KEEW2nKRhM0p8iOh-OXtvHNkLXTG8nJ7fKhO5b-Ueu0t_p-
Nfxu7m
}

EntityColoring(swc)
!define swc(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, swc, swc)
!define swc(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, swc, swc)
!define swcParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, swc, swc)
!define swcParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, swc, swc)
