sprite $swr [64x15/16z] {
VT87iiCW30JG864wulwt_HyO8dP6pgRwmRhokUDI7wDdkerUBMtJF39M91eMr88QrCStyPS5jN2Vl0mDRoFBnXNIVfhRrVkyVYyhtfVrkoqRDjDEZVr_jlKv
vPJ4VM1usi3JtpN324zsXQULrgfxxP_BDlkkYRJf7kPgj6MEuXL6FG8nCnqJzvsNOV2wcvbfrPjX5OmJtdLyme_nXBrXRA-wRAomT2oYuMf6jYrg7KDPrigx
ZSkhCPJ_
}

EntityColoring(swr)
!define swr(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, swr, swr)
!define swr(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, swr, swr)
!define swrParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, swr, swr)
!define swrParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, swr, swr)
