sprite $symfony [64x64/16z] {
fLVNekiW36CF3_x_Ry_8zSKaJO2UwgLJiIHijp5Fi24Lm1z0oS6Pzn0ASXl0LAFT9Vj2xGPSmnORk3q1uuhjAhSPSAuXpzZYmZuNXxO1Uf8Gk6s1qoqzSTj5
kQEtDr3dz3Ngdxmpzw_bS_8RT4pE6XUAl8mZ7vTiYiQ4d5sNoaxfPUtN6llR7KcZGcrvNj958zd1R5Br6_Jy-mJ6i5WwEKwvKjKU93gvBNlbsMiH2FuGCaGO
jheLEkdn4mNMKe1LlSY_CNRNEjMPNzX4qcdF8kDhutCyk2KvOugaBEbZy70fzIh_eECl4Pn9B263n6NvOk1g3AIQI8di3px9uLqFAroD7SkfDa4oRfYl91SQ
a7DJTBVnkcc2l11b2gWNlZcWx_wh7ua8D6m5uLrzJPNCW00tBN0Jlvp0iAToAGNkVzMkXdGZwUKijss4lb1roVWzAg1IP5yi9vnFbJtBl4WJmNA_QIZu_vje
Uz6ifx7ar-uQXD_3e8ddS_AWgPMUXPlOBwTjvBataILvCeqFutZqqkUv9w7T_80whX-m9bJ4r4UuBEt7qq1JahEJFHDNtSFkShQC9UTAf-7B4_lJgzDIVfvz
B7qGPlAdyjAg-M0-d7vHNjgpJEtZDBqR0OIiuPYqjIeKdAnnEWMEf-u5UCfCM7MXdjtD7nYsHcZiffqlbQuEk2SI5_HgHjJnp1mTly8M9dIqvWGOGWbOd36H
9dHoPxeMmt2yZDZUeOzg2G2vxTCrWqsWCv_SGJpV0NbSipb-T0DMtIStWE3D4gxmW_Agx2bihFH2XcJDFcp8GBeHIdWYVmC
}

EntityColoring(symfony)
!define symfony(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, symfony, symfony)
!define symfony(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, symfony, symfony)
!define symfonyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, symfony, symfony)
!define symfonyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, symfony, symfony)
