sprite $sysdig [64x23/16z] {
fPE7aiGm24C51WJw_m--iNEPwtMrcq9vRfemy92AzX1lJ3oaeECXiG1R_-SNrxd-hUAv_YrdmXbmipJyGqb3iXZ_DCDOC3B-RSR6p6upljMQ1kTjbnlvOiOF
lEOTRydbZ1SpjjmDrvBCR8TtTlE-x0fE1ndsyXduMG0bSSqum4aVQH96IQC1xw2bCsFLoydlbrHdDre9axnLDG5AR6rUTG9gyyPSzA2_yANUKMWGQepI09C2
uE4J9uZD8-b58vVVl8_K2nWv5KX9DDVSvwSqwHhoijyPJl84Qz-p9KU9i_iMH-q7YUVrZyuwTTc_ac5kkyxTduPMm2KHoBMdjH7Dv-8tEgEBHz62JTAlSwGq
aWCjBMncH8IEBXuvcdhcp-OZSrdHhkNFsKUUFNjrrrvRDuD4Cc3BpMuULcH69EbuqUfHudEbfaSlvLNiPht6KLBZ2wsMD8ad
}

EntityColoring(sysdig)
!define sysdig(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, sysdig, sysdig)
!define sysdig(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, sysdig, sysdig)
!define sysdigParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, sysdig, sysdig)
!define sysdigParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, sysdig, sysdig)
