sprite $tailwindcss_icon [64x39/16z] {
fTD9RcKn34DHgYEz_nLN-lXBUO2DEdFU6V78eaX9h7HSYzA6QRZXf5unS2weWMKubDHVw3WIV70MC0vNWUH58D2vf7G3p4jJO9U5ZelssrhTIw0KQ4o93JK2
PTzrBgBBn8kQ0LMuUr9BWIxGr9hqPhqX3d0zaUD4wM6UE9EwcayXJO5pLchASCNsKp8TcCpZZPiz93poJOG1KnH9lI5PORWJf3Pa6ivPKGqPE6NyKzxDfyAH
udy5Kiz6m0sDQIqn8ufQ0zkSw78f3H-iPe6spvNejByuPe2-tyZG10qRrrIEDnQK2bqPC083IUcDeJCqJZrAF3WB58QR0EtYJWFBBk-y8nCtB4cA7qGo3RSy
Yvyo34_-0G
}

EntityColoring(tailwindcss_icon)
!define tailwindcss_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, tailwindcss_icon, tailwindcss_icon)
!define tailwindcss_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, tailwindcss_icon, tailwindcss_icon)
!define tailwindcss_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, tailwindcss_icon, tailwindcss_icon)
!define tailwindcss_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, tailwindcss_icon, tailwindcss_icon)
