sprite $targetprocess [61x64/16z] {
dPNTTlCw24HXG7zE-lwlUu9HPabrkaxypQspgs6RolA_iLfK_Z7MMgluHxYqYDs3rCwoMjiPlzlM5T0tNMx0hVVUgYvdL_sMrTOZbMD_eyrQBmaadSTvQrze
qpx6sEXs7cVVQBFnIfE8JZgFG_jR6sf9Dm7de11BEe-ZTBsmn-Dn0D2smeBrR2r_I6-FLuBf0HiqOT4QyEoAFwIFWClqrLM2nYmR9oVyX_GZO1F12SSFeRET
Kn94h5sb8-13HPoorLKoga9OSDrLUmGi8dNmDHkxRN_4BhjQ0ewsBM2Vvq1tM4I1RLUliZic_8isGEMwgodRANl2Aws0IORQQYvFofwrspgXkRiA43q8Kvkl
icCfAWzMyqmM8BpiQWmH1m_P0ZYplJ45T_M4Qyfcyb36P3cu74SQzLcx1znMrbUMhNF2upZizE6WxB8AMSXp1CB-Gbzy7Ab2sGV4z7TfS4xltUPlJxekLLBs
x0ULe4s5yN4S8--ZIRU0ANjoW4IIP6gqJUiOnvbi8lNjIs4c6SYMJbX4UzBPf0TS5T3WFy4w24TQLX_wlWbuhwKN9SYg0v2PSjA72MM_0xsqjdD8qOqEXZV1
jfcsmINWzfucfDghIuqdbyrsB-vhyHPmoLg0vYxWV79Tpb9skiy9HP4CqmCk-KN9jbuYZats0D_7fslt-VFpF6bCsZRPnbtzSEtMdrUwVA0ju4vYeVqjUoom
kYUjfuE0wsgqzbvalGaU0HT-6vBsSz0oHbDMBNsyqetBAQBFW6t2MPtDwLYz1HgfopVEWdtgSdCwbSjaKVjWyWxAvIm1F-GDA_8Ar0Ms1UqrtyFZg11f0G_P
rWWGP1U9DAAjAdTP12ax_wlpkEN5w0RtWgp2s9Iju1FI7Bb7NUCSJCekqFr9GbmrTwKLvY9xJo9BeB860H-omF02MjajcDa6X-tdlYArJbfLW9Lq_qtRknpK
Wemug-X99-c4Bq6IX7dva0mOdr0jbIb52UjA6jazHhGuVSr1IQfyZa-ocEwAY9ByM7ib1T_KPU2EPA-3gdmJAElU93yFUYVxeFUYjjUz3vEy6vX_KVS_
}

EntityColoring(targetprocess)
!define targetprocess(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, targetprocess, targetprocess)
!define targetprocess(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, targetprocess, targetprocess)
!define targetprocessParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, targetprocess, targetprocess)
!define targetprocessParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, targetprocess, targetprocess)
