sprite $taskade_icon [64x64/16z] {
dLQ9ikqW2AlWJlp_ttqNgqpdFhjucSqpno0DGNFSX2DoXoy2oVpponrRmGM0L3GDb0gfSID5Gfi1Mud_XFMvz7E1VdIki5Gfy6lXLdEC1M1DY2OfI-iv9JmV
BkEegB_YMN5CocSU_-G7k5Cugg2k_WFmc81YRQqLEWxc5QcHM8d53O-nfvTdVe8ca7ZVi_H2S3tPTVynrnEN6bxm6VsSiiYB-4MPp7510gEr_5dT-5r0aDR0
nzSeltP7j2ryD8aPTmtrEpwRHesxj3FX78joI4DtEznTvP9CK-0Dg1LTZJtGDZvDhPFsBcpZyoIWsb3kXDEUrJ5HTV_pAUDiOMdxNsyg5kVa3yqptk4Ld_w6
9-W7YD8mWtyl7CtDRYwk7u1mb4ltl0nSbB4jru6hPIIKU540c63TSq4Jkfz5GXC_IEwzuT9Gg9zWe-8LINaC4fSYQEST1bkqwmAro5pyG4Y5asJ8iBIjW3jV
2ypPIzY2btcDs5N6CSb7S8xU7eDwaL_wXg_7PVzL_daFJr3kbCMyZ--jDFtz2T_dHuk8-tYxGRg8T_5M0DXr0UpZxTwjzXZkuakNONS4YGmFLViwfCW5duRq
YeB2r8CERbmciCtLd1Puc2QnPxHxhIL-cBcXTuQzW6MMnCzut_4J9UO1ikh07b9MgxUCIdtcGHEVhGyjsmg2E_uWCB5xqrqd0CNJfrjabCgA8HD2JwwfwWFI
M7IvMY56lBBnda3O-Atki62RGfVnT6qPTxyiPEeQCWk_33Fltho71NKvEDVpSmR-0wCesWm3BImL839QudC5W1C9I0vqOalAWwnVKQmx8npx43KykykRPziM
_ltT0oT5ezBIaeH9GbpzIrEW9Jmu0YK1eDL_9LUyMAtP_DvSZkV1SPBUtfrMb45G30a8PyxYEKvuUlDb8Pr5eEljV1GnNlIQFZajZwNqwRivJ090HXfeI79x
vehfy9tlJEGztw7_0G
}

EntityColoring(taskade_icon)
!define taskade_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, taskade_icon, taskade_icon)
!define taskade_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, taskade_icon, taskade_icon)
!define taskade_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, taskade_icon, taskade_icon)
!define taskade_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, taskade_icon, taskade_icon)
