sprite $tauri [57x64/16z] {
bPG7aWGX30D7CkR_Fxwywvfhmg3A56tXnBMGxFYHfSKrK76Jdx557Q6AiVpKZjAv7Kt9dPBaB0qAlE9OH6yy5sNmYlGggkP1jQd0DCrjpIUMUjuhnhDsGqLB
aQ9sZze-Th-LjaQMGi3Mc99uv1lcbZrZq3SltwgM_Kkw1USrdCGFrlDs1PO0zOqLY0sRWSv-3XRtenDGnMMSv9Z0KDLXEzgRqsIlDGJzujfa6JoPd2oEadHD
PZN0FLd8Cip5RHgwClGQu0_GJWnTXigHeQtn-fUX1uQHtufh-Uq6IehsS93gLg_mVqaNoP5NWVcJ8WPUm6h-S2LwASQB0h1UYhU2cu1qn9xaVz35fJ5fg3rF
xitbnzpG3YSDnLy_E3b6Yovn1ZNuD1IPMGOJvS4QwsAIgItb-zphaQMY8NZMbpfHPCz1R2UgZmkL3R842Ox9A5Ta9EU8izBGvjQ7KRaHeHkMs9GfcHdMD-J8
n6eEoMA_LHGure12ZocJNDK5bO1OQif0WJrrnLQkzo3_l9RK9m
}

EntityColoring(tauri)
!define tauri(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, tauri, tauri)
!define tauri(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, tauri, tauri)
!define tauriParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, tauri, tauri)
!define tauriParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, tauri, tauri)
