sprite $tealium [40x64/16z] {
ZPG7iiD024Efkt3_0_-YCV4QjxmfQHe1WfY0H32zmv7fz8vdvgHt8ZFZNIRvdSxpkxeZ4tEm3NtL2QPEVzIXlPd_FEHecQca2Pugpx2oIxipSoLYxEH99pwS
AyI7kZO6ma1x3tFudyuMtOItkVHC_a1cd41gFtxsysKhU0FqgYw44OOqzmxwlEQstYo8StwscyBkRd8CmmJclOunZ3PTNEq4QOCetQ0EGsVDJy-wiVXvBzl3
baCk8TT7WwK8Lp2XsvNCYK8Rwix4xeXRV1WoqKWmfLU7RQ7vOHNgW4xQ0a5miqCyny617vUt5YwxbX8t7UU1xlUkg_uUTOpOwhp0FFM7X1dNwjRZM__zK60h
Ig0RJWB7WCMKKML-PBpSdwzFESTRZwmFksuSrZ3BsuHRn7nOmw0plkiuR-vUZKdt_hZFkFVc34FhwvTL9r0Ww1gtiAvpnkA86S_LmhjkQ2Kok0oxRc_DjWFd
k1pOIZThIgvtRU1D5xkBpGZ4kQBk0hyrDeWQ8eT0c6xn8VjTwgrC0i-JwF5sB168lVdPbkhO4hm3dGL364QtyAUUgD03intmO-59xymlTHoe-uv4oAFW5m
}

EntityColoring(tealium)
!define tealium(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, tealium, tealium)
!define tealium(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, tealium, tealium)
!define tealiumParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, tealium, tealium)
!define tealiumParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, tealium, tealium)
