sprite $teamwork_icon [64x64/16z] {
xTL5OiKm38HXCu_lVzl2b3S1kUqZVMlzuTZc9wMKSZ6iv0b0i-BSOxueyjEpxxVU-nTEs1CmKUGz8SfxoXSxFrvL8-r7M7d-w-z_N5MllNLkeRUnl0ZItkP2
ITZdyYwAUbS-sVq-iaSmDdf3uQi_y103-uaE80XwXqbVVw4_VFtKllh1ULi-fECR63L3_l3bKnnWZMhDzmFaOpa_jzPg-ZPkVOpUV51AgMS
}

EntityColoring(teamwork_icon)
!define teamwork_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, teamwork_icon, teamwork_icon)
!define teamwork_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, teamwork_icon, teamwork_icon)
!define teamwork_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, teamwork_icon, teamwork_icon)
!define teamwork_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, teamwork_icon, teamwork_icon)
