sprite $telegram [64x64/16z] {
fPTN6WCW388D2Tx_njsxfF9Ptd-94TVe55daF8ciH0ofdfqVOjf3eAOKqw8vUwLFRzLGSob6ImUd8_YrQvN4SzegZVkYndsLndsLrNatIW9VAaHizdg8kQNS
g5ubEMqWKM8DJFiwvpw-MmZFMhMgJFiAlLBygaY8w8C2tRt-sFnECHSjUqeLEuPd7Q6J1dZMqGGzqvXrH7H9PQsj7xYOBAcifRbUQugWIFEpO6v8ZQ-oaeeE
_vZY5urGwJCJy-K-GZ5wY12uR1zL5HBNxIkvOnMksvTJA0MjUKBnbFQXoe-fX0WWnhfz66mcW0JMxGkToJhpcLXElpi_4NbMuJUVNQZpmlDrKuI-Wxi9NF2J
waVxgeq5aSdbDOb-Lv_nkz3OK3UcgLFPknSu0UfHznyGbEUgBuXeRZy0Q-lrjJy0zU6oZ-iAUboe_iBzLQYD3v1uJaabxQUSLfHXlZb2mVy1wylL5v9yieKE
FW8
}

EntityColoring(telegram)
!define telegram(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, telegram, telegram)
!define telegram(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, telegram, telegram)
!define telegramParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, telegram, telegram)
!define telegramParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, telegram, telegram)
