sprite $tensorflow [60x64/16z] {
xTNHZiKW20HGLGRw_r-yrf39ScrqwUlUUMmv2PYWvPJMQdcNsaVQAzc6VAU7P6gotP1MapBgVBkvnYdpklPDMa8czDAkG75ed7AbTgcSTNsGEknbYsv_aTCE
ZRxepQ23qjvQ5hqPL8EzE3Ohjkr6UnaaL73J5XaijLVWBjcr6oqRPyLE4aVD2iD1eeb5pL_UHPJHbWeB5hIkILTRIbDxiZnyojMETBC7wphAQ6V4B5ZWybW4
QlPfvzYqG2-q-2tLhjNEiTr2QdcqisAn75invM9TBfQfOloa5YpW7rPBtKCNReViLSFX0T8Z_kp2xHmZM5-wdOQDKc2Mq58UxlIc2X-3blAiQ_cmadlAQDUh
KO247Lee1PgptCuXDMDvObCcBJKqQndLVs7DWWLwmaADTjuK2QlGgMygxUYY7UR6lfnPExLoq9IDzzLx-xLVszJSSlKIwMPkDwktVHcDgvVLC0Cea-agnveV
}

EntityColoring(tensorflow)
!define tensorflow(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, tensorflow, tensorflow)
!define tensorflow(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, tensorflow, tensorflow)
!define tensorflowParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, tensorflow, tensorflow)
!define tensorflowParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, tensorflow, tensorflow)
