sprite $terraform_icon [56x64/16z] {
xTL73aCX38JXSS5uoFtFczu3Gl8w__vxXTeLfSWcDSVqcYExrXmPKdEa5ntJQexiMdDaavfZUisHhUnCiCqcBhOVgpbcRZCd4kDmc3io58lyh5PkFIUM5pPt
wpcHVb4hjrn0SLORDzadpgVQEhAznlxmLkmSq-vZ_n6qRnmPq8lw283bnYLivW0lEaZK7A2zvW3FceEqcWCqQWwmh3b0YWvetBk1ITOtReHCc02UNBkHYbaH
0cbBHyEy81tGFdMZ0Ml7DC3onuqkMBldsT8-tKW3Tevi0eatHmUsxbBUV_FY9cC_Ty-FzKpuw0hitQiGY4CD-w9m8KuSqsgE-NT_jqwYvW3hDGTurXoarHoW
lUO0ove3lEWWKNE0zfe3lEEt4m
}

EntityColoring(terraform_icon)
!define terraform_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, terraform_icon, terraform_icon)
!define terraform_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, terraform_icon, terraform_icon)
!define terraform_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, terraform_icon, terraform_icon)
!define terraform_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, terraform_icon, terraform_icon)
