sprite $terraform [64x15/16z] {
fSq56kOW38JXIG8HQ9dxttRfx-lsLP7t8HJ_LLMN__ELYaVoJxuy3JlDk7tYol5jCjVuYQyA5H_pvjjQv3hmRSwmxxtupLV6dDlVKXRCNT7CjAcfHnSTT4Nt
3ZGnQ-ekpGtGkFbyUs7fskb19jUATN8wkN9mSHZNMNo4dURz_D6UFfsjqIVTU5wpHKcgCf7iF2pfTllSl7jcZX2yV73dyuGoOEDOH52K3j_USK4MukQjqdjN
uDDtCpdkVj3dvVKQnCEBVFYg03vy6O-QUlEvVIrkeZWvUTZRvyiNFigEFcPA1AGQj4OaMWcqPgcKxS5jLxintJpn7wbNuR-o-4Vu1G
}

EntityColoring(terraform)
!define terraform(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, terraform, terraform)
!define terraform(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, terraform, terraform)
!define terraformParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, terraform, terraform)
!define terraformParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, terraform, terraform)
