sprite $testlodge [64x55/16z] {
ZTPPkgGW38PX80Caxd-_tV9hodWUnU-wtaZG7igiDc8cQhKigoGwR2YteCH8H5KuJScITPYx6nfTg7K1FnATnPGijss3ZW5YDhZknwSq8QQGGAB0Su5zQRCv
0NjGJ8XEUNdq64excB-ssP1wNYEb4Tsl6ZlZfyV3VkUvt2SHI_OUTjQ0uSym8OQmdDvzjxyBRQ3Xequ5OGQBgBl7kuvd9_yq0LlsPB7sWqU3orFG2u_N-QZN
7gzpeRDVJsX9Bpq-Y6Uzzku-wD0g8b-zpxR_3JuykUbCH9uzNEITXU7PDkyQvJdnm9mBimgysBRvq3_9d6C0kS7yyshxU5EKerBrxyFxpkNqVNhiaCE7rhfd
ZkrKzVGuutq7YHTCTZyxFBwXOJZ0RGVe8uaZT4Pozta7Agdp6bpvA1vHXs41x12Btsl3DnC-YuSqCnm0ZUlYEUuSoTr7HkMfnX6EYSlTk_ZosGi-tzi2pxvI
EZwytBn-yVhpQda1AS_TlEBpImTm-k3bnTSF7XeVu33qVlselNYFwrzUe5p-Z5JBld_mUaRu_D3xzQCtxxZ-jPVmN0hVV5jxZUJgRVhoMllZnIB7zQykK9BN
xFlQQ_BTVk7wNyjUQnbsFO3JqikhRqklpzushmlVic_LhhcLbPVagLcghtnzzr9MKVBC3_-d-NW5B1PrhkLRbKIHgA4XwT7BAkkiJwsq10zxZCMv5tlewih-
0G
}

EntityColoring(testlodge)
!define testlodge(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, testlodge, testlodge)
!define testlodge(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, testlodge, testlodge)
!define testlodgeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, testlodge, testlodge)
!define testlodgeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, testlodge, testlodge)
