sprite $testing_library [64x64/16z] {
dPQ9OkmW24L7WSlw_lztNqr6asaotUXcHewz4aGUNnXfP8Nnuq_MBMkt-CiAdBKiyMjSiiwclyHfujFaTtpK9yl-A_LrCVi9rrXe_ViR0LtuAntaxk5zxFvg
U3mit5tUyymiwlP0tPW_40gcRo89ZOVVyTbCqHxV6InQtFBT3FqxdE3so5kUn9M_mJiqgBtX7w5AN-DR-Dxo20LzALvZlETRVanucl0NuiLhJB-9_uT79l1k
0HBrmXYzUV_39qFVBI0Q-pbzbt_3fDAat-BGTKZUvV-cpGNtcuziFpX_dW3Td3oreyfmLVrxmSzphj8ll5ZKMbOhRIsmZsDvPjfL0C5ooHylC1U_Zy-J1hb4
JxHoFLdz-x35Zt6S9brmvUt4os3gn9_hbmz-gQ7dzk4dYTSJa7pYOmQmFJe_UVKgkYt_A_nhRLzyasSaM7HfV4tXNCcxzcQJwfqnuuyy5NdALxxaV3NeZ3yH
Mpi2K7vt-StqdwbnRFy15kUP_fPLFYQQPbtuidrgZ5JQBjyw8sO2meQtcm_Yoeyf6m-EMKODdIHq7Y0CyblpTNmacBjOhH2gHLRTLw_dJzYg7vpQ-rOrdZ5a
06eMLMdnYWVRO4s16NjKK1zLox92sZEBTCDLF_D4FYAW-jmxUoKJRmSV0p48YyQcKw7roGHYOofCc64n957VNWb4l4uM1erBr4G8vyWOSM-pSks16vPX2lNv
y66v_8ddkcb2HEte6g022tS5WEdbfe3EV0W5aG2ga46VInZHu4IWQXuryS73pFBO68YuC_TEbwlFbzOQWr250efzEnPRISqCLsxlkiqn7wQQHvurOCm9OsZB
7CiuNzl53BTDhGAwvS3JgM_P80BwC6QMyQYlUAMRga1qiv5iCaz9Kx4gz04JRQk8bvt3bo4CuIs6mjHeu-c5VxJ6uDux2NMsmi5xAizic3Kki7Z0g_Wqspfr
o-NVqy6V-zSqhD9eyRb_RPrIZk3fmayNsFoGH_pzamEH-dA-zcKzosO08SYIQwiKSsYGIq9OcUm2ka8hhjtAmQl9DPyoHB79L_6wSU2bN_mc8QrCUTxCSTSj
sLegq6y4-BujWINVzYjhV7vzRKgnq8rdzLZGuSP-Q2O_133DNUqPt5JS9eI5T3s7H5pc0kjpVl8GrmdPgLDzZOREdWQ-zEzT0cJfLztBDCdQy6NVypwIz5qA
gwK-5Q4jttSc6aQjwt7BChosZzBm-DOQD3ApN46hBxOSDhRulNMecXiEvmwOk-bt-CfCA5wEH6D0STis_mS
}

EntityColoring(testing_library)
!define testing_library(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, testing_library, testing_library)
!define testing_library(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, testing_library, testing_library)
!define testing_libraryParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, testing_library, testing_library)
!define testing_libraryParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, testing_library, testing_library)
