sprite $tidal [64x9/16z] {
dP65SS1040Fr30Vglzla8SmnxiYtCg5E84b0a8n_B8KSoIXHQEb4rKpDwiAkOITgDf_gXrwg-YWewOFaslkj5AF9zYVZhg4gkHD4Ke2JPY0eCmORAkVBGztP
5pyXkLzB6LzynBnmIVZENvmMcoJs5__IdV_Ppsp1xAtVo8FV-T7z93pJ9zrBSchytbSXo_vwMckZFAKRa8_-udivC7nVQEv-_bhrrQmMRkeF
}

EntityColoring(tidal)
!define tidal(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, tidal, tidal)
!define tidal(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, tidal, tidal)
!define tidalParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, tidal, tidal)
!define tidalParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, tidal, tidal)
