sprite $todomvc [64x58/16z] {
bPO7iaGf24Kl617tlzxH7Xy_ECpxd8wKTMurq0cRt7L-w03QV620T1xa7Ebe38Emw6Qy-njjHyvIiSXcoBjl1HKPe-Ey0FsmoweFsnzwiAEbTmQMlH1ig2Nw
bq-riUAgicGWRtkJ6oCCj_7Gf_PeGX7Jssud8G9tiojXwKe8KCpUdKTziiub0s4_MUUT4FVBL-T0sATcUWQbgCzYhIVmg44_VUcChFFulVU6Fv27wOIaS_lH
hTlWwpG_gWljKbKZVltI6GjYPiA7rbeDwOO_VrzF2FYc6na78lghNuPHiB7vERwhLnniV-z-7aQ7KVxRP-yzln5wyrdwhmIIOIIy-NttIFX67qQ1wm_wjYV9
CDem6Xm_BR19DYU-PoVa-SRJgZN1JlEsFs_HfmcvDcza4Idm0ZOzjMy5V5Hrq1FWmF2n_Va11N_mROKN7HTSIacNxmGm3F_pumTKt9JBTmC44VyEI17_3cW8
-7U0q9klgaBm0WhW-ouMq17nxu3a7R_vgDxmxFt7-91pJbu0unsR_nrG4V1lAWVy65bijRfyHf1cyuVCEHjYqBS_pNata16YBsVWC7R03gC3DdHLLYIPYu93
qXL6WEXX9sTzAFXrLET6O1JzX8rvqEtFX_hxgCppasUaZl_tvVjHMe_zw4R0vz4JOFm3
}

EntityColoring(todomvc)
!define todomvc(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, todomvc, todomvc)
!define todomvc(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, todomvc, todomvc)
!define todomvcParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, todomvc, todomvc)
!define todomvcParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, todomvc, todomvc)
