sprite $tor [64x39/16z] {
fTPLagCv403XB1M8vVlVTiUWWRQzeNRdQyNtCuZ3HFX9cdx63J7XLUbDi1FKiKYyAkgRYl18KwY7yBBQwfjqxzx28n9l_EwjjuZDF_AHSoWVUuaSnkTU8vnF
VHebHyZ7dXfzPBxdswsQ0CB9byhBv5TOkLM_Le9hLl7PU4xZPZBtqXyPmf_ywiUJJhbUQxK-FuV6Nmt7nuelNEjkUtdfTLQIzhRYYP_uSYc8fjBR70gxL8-y
pc5WIMMqEbPXbu-yNwg014QCMjiQidT_ukCIW1H5ZNuTpYbSYnDlom4l2XBaVXqyxcCvy383f6GW9JKTrq5R-UiNf-JNFZUGQe2eaTEuJViIaESdxTbFWw80
BevRlq-N_-qBlF4wXN10N35BkVTwRRQ_VRprtf42Q2GWPFi-pdmqB42pW60QsyzZ7ueK0LGbOZxyElFM2SCDK7DoNj_RVvgYGGYaZ4kk3p_QcMSOXIpWYclf
wt7_uj3dJbXEu89R6Mi_FuUU6HJF4E3UnhhlFdFgRQdbbiX2U1zZlp-d7byMjM9EZhdwVd-FFJPBgLcAb7wPrtFlmdjFRO-sHyeOexSsBgkDEGB-pyVpkWE9
lYw_cgCQxA8yKe3_
}

EntityColoring(tor)
!define tor(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, tor, tor)
!define tor(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, tor, tor)
!define torParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, tor, tor)
!define torParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, tor, tor)
