sprite $traackr [64x15/16z] {
fT9LeYKn20HGY6B5_fSxN9UUvoqLFJya2WnIH2U3Cti5_UH1fd35QXLZ8D5_wdS59bUC_XtVzduCXco-n9H5j4unDt_cE_2-_ZeEjCSAlxKN_mhjMhypuyWC
8NE9rGo8IRm3a5gIGAoJRnvpk2fEejtgDy_UaIuKMNA4Ai3iNdAH9HopVFCqcfc8iq3MR5RGPOX6vRNwVQp0e3QcfJPKbwcyfNFvMwtxcZMR-Ue7qGO2cCqH
aJOIr_eXXShx_KYOE8hT_BZuwdNo7992AwqX5_VoiHFZoVj9SBjLDH9ICQd27JaNO4WZGGAx0oo9DZE8RlNRpmUijcXBhnLrENMssULccDje8aIYgyi--5yz
_4TFbkY_fFy
}

EntityColoring(traackr)
!define traackr(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, traackr, traackr)
!define traackr(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, traackr, traackr)
!define traackrParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, traackr, traackr)
!define traackrParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, traackr, traackr)
