sprite $trac [53x64/16z] {
dLK9ikWW25Dn0tB_w_wtCeo5vqn_PksIciH8ozyW6UKr67ZDgWfeVqaY092Nf8ulqFkLthlYBz9RKqq0hPUaUdftNNTgATV_sHBExbEd-gTw1J2ZEWMWuqRI
cCCFTidnHK8h1mI6bPDMRCm034fv4g92SMiDKd8MrR5vrYDGHpURTDfc756HapoB3KwYSbQ7mzfKzRJ7RZebaVL-fL599W_Ttj8QziIFNKj8qnx7DrQI7iWa
QulgN1_788f0tTEAfijAFbHdBpa97EDRTbPxIqdckce8fokWC_LaOlRpnb1ymLXLiwK4XcaHc-TgIqLNUcJ7lkxMPLf2mdPpFYeozQV2bQC-4yXFY_h5Nu4r
VhsoGdUrYU0ic9gbWLHAwvGKs0Qs6xU2EK9Kf70rKtyuimJCOn-9LUflygNsnRoet4bSljydKUub8fSttQMk6yc2SCSSvgzf5RQnvYJnhmJM_BqhzN4IniFa
p2OidwMMycY8zYojxTleCqwEgfg5m6fBL7PB1XYdOuzZHIHsjUE4pdeZBRTqG3STf1r92n5dQGP2HpOow2Zv3wn7nMUuXluiLbFawA4olj-C6yamZ3LpH_cH
9ZRH8U_RRtwmGYYsuOmseBLwDGIvdT4KDW4ZOXbKUCqvHwU4aZTHfkLrHTMystTeVehkiF3oaNPFJtfv0zggSdNp0G
}

EntityColoring(trac)
!define trac(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, trac, trac)
!define trac(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, trac, trac)
!define tracParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, trac, trac)
!define tracParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, trac, trac)
