sprite $travis_ci_monochrome [64x63/16z] {
dLQ7WkKW20nWW-7_l_VE4irRasoPgsiOGAh72pXcDG2cEVBnIt0om4y0bkKNR55K4ipqFwofWeQVsYvme4IXSK0Sii6XF_8XeTgYpQUgDN_Bfl9eXpDS-PtE
vaZFSJ4tUGqSbe1SGSCxTSYhTJiTP5mnVIel2cZG1zylM7SgKsPYq_t69tMzfqSW7Xzyc8-_qiU7BSBZl7py26XoznBx_IUIG-wz7nURyUVALnhndxYzWS3t
wchyxJG0uSxyD48Xq5T-o3aAqvC3tCmJXvGLKDxjYmA0bIGKTmUoUoc61eqp9H_-iwGkOYFK4vJWtfH7uSjnhdp-59LO38x45p4uD0bjCO7_Xz4UmTRCFBiA
vRQerIim-Fiu2EFgMpHs_evWhaCgFZK4AeR_6mAiyuVv7TJnE2mm-F7u2mI-_DyjiqZe4E4x9m8m-Ea8WIk59SIKYnesc6d9AGHXhe91ZkWsugy7HSK9VmPE
QAWTewSVCHNptm2QetawMmVmNmDpZAZ_3JOJyNpH6O_THOILYGlDu8uUw9eJqNPkAUQiPgU-wqOddJ49J058TAbom4hakOebf8BLb8i-nYUPCW_va1HklTEp
vMjVwKUNeHGVuSpnO8DnfGzVI_EZh25kxMmWmotK420s1sj3YDRlnNqsSB48exLQyeeT2lKS3Fq4DrXRXmv53xGwvdwGRci88qwTIxrRLvd7t_MIiruYLkxK
wc4tffCFQ1l92Es3LGvmJhdaqvMej69YdPvopf7gIRzvDqopXqbd-3ZFDEfIEjHWHBx-6uHfLiIwYHmJPLKazJtX8oCu2rDBZY5ZtucpXb4uP5qrJr_QQtov
7PXYNMA9QkgQzNEiGEzVCEd2jN9PHv589Cwn5e8zlBwIDRCvDFtC9J9BifBAo1oH13vAFcwXaV8qct32uJsK0sGjdJi_sf9H-2TGwBod7fplGa0MLpPtw73D
IjxVEktAoMOe_GQ0MIdgkDcfR3L4bcRflIFTPKz3X4YsT_R-f5WDCCVZEv3ktvyJlpG_nyB4RytFfEtOjUhp-ty7lhW5P7fvKMomKk3NdkJZ6U6sQhbfmFv4
t266gwiQvynQI-qTKL5XQa09J2mXAsnZFuEu3qj9QbrLaWVHVm
}

EntityColoring(travis_ci_monochrome)
!define travis_ci_monochrome(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, travis_ci_monochrome, travis_ci_monochrome)
!define travis_ci_monochrome(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, travis_ci_monochrome, travis_ci_monochrome)
!define travis_ci_monochromeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, travis_ci_monochrome, travis_ci_monochrome)
!define travis_ci_monochromeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, travis_ci_monochrome, travis_ci_monochrome)
