sprite $travis_ci [64x64/16z] {
bPU9TcCX241V597T___R4KpQPfdjpb9JkO2S-4vo_O4sICtTJMcqwpzfqyALYIOHguVD_qdH9On6Rm_w80lf_rfRGaPxPKZ8F_KmGs6NVBRxVZqqyA_sJHnJ
m1U_Na-NsrzwDwtAC45_WXFgrsf_F4DtWV89nufl5Y5L6o3U_b3TkM7v2cFfDq6WzsFmxnFSZDiOrQTrNEfhHVxds--M1yXjiT_DGBGrgl9Jj-_XkdtJvOkR
OJL0hQbyrgVr1jGIbZRSdMdxEjsTcd1B25ft_7puiGjZIvHxqZZhjvw8j0Ht07uSGHLWQ8cTOzpzfFFv2Habygw3RwLBV_ZzoU-Txdaa_tDuyvNERk6V_QGg
a7uits3xVR34yM_fw_4vXFDAAbG3_Utq7NeREiLTOt7vQDltsTENbMkPsz-HpA_bC_cmC4OOpewPm9Uhhu3jJsS7GBQmaIq-JM3ekV2ia6M7WrG3vgfg0LbU
mAjpK3wF0traQ6AZ5K8j0GVIlh5mzmZOIwLHVhst2ZHfvOlqTh3Pacw8df9Oedi9Fj1EsDHswAhb6xOxZvKIEE6SavBz4yc1xzwqTWSzzPkF7tuVapLl_2iH
eJn7_-clPnzCnKo5YIRY-0bYFSZLJDJWsO_JTKUQ0-gCjqDxyEDbXp49-vC_l-CoOeSW4Z6B5YBCsH0yahSxi_pBAP-NH4Snyw_ZHxA-rswQkP9iWRrypS4E
pa1tIof3kAhviJHCDLFxJfJ9pbNGygTtTFTOhdfNB5_aobLuuwxtFHTcgGLrd-NtG0ZnB66Mih25POXchwd78xFo0oUCTXLg8xSgmAJYVNVfTiVZowPlVvfU
XsuHZtRLt6EJSirUT5KpYNjDC948wzSTMgvPyGpOLmWMOqE-CYyZugHpz0op7nTuXbacfvcEBDtYyN5gkdCl9y-1jJ4fUwGl7IDR5ZPCo0Z5gu6fLXtFb6B5
nCCmvcz_HFQN_YmVXouDoawCSs2gYAWwbk4TOt7NM-dDLx2vQXOkPWIOPPYmcd8rvYvV3KnZ9N0iNvS3EA1z-PJlCQymKPIJsDU6nkE8EflECpkvNMXz62lN
zg0CTHniPBFbXWoqjH4iSWExONLFv-4F9ooH35L45JRe_Ho0Qf9K1KHpms6RKatiTSzcooVU40xCt_JUMDdcgArxVoPiVNZRinzNuTYKsUS9sE0aDL9glQEH
ReFcF2d4XKJRz6p_EYWt4HBdBMS7QbQ37xtdoLXKBL4LCsQrqLMUFpgWAR4fYTbvIcp9UY9rf-eYYgWGMqn0nnz-ZmcZCgTxVmuPZvuC-IekcSF5bJNQzGCr
4NSJegEg46wxRRt1w0Fd8wdRfF1mkdxIix2H9Sg427sC8JG6iX6R8THivwGvX6-twmC-aUl93tdgsDoVTk4UbAFCwG8ux8BmxfFief1o1mjBpcNV-9BUUjAc
NI3UFty2wmSBVS6MLL-jcseiVd5dvcFjHUEbxqJr8be7QYy-XC9rSsoxmE0m_O2PUHt8WgvNU8KDSa3nIFqFMFZx_6-U_SLfye-OnRpUWItwkslshcVvTtZP
frx3NcTGvT-vMNmgzft02bzwVQP7cBtgDZpiYnpGxxz3OVXtWaSnOWz_k67K__ZTB-m7VZx8WgQvmlx-HHZF-yCtLMtcNO11jeBJ_IkDF9BjBvTPDrRKdTB-
Dpe0zDlLKEoyeup7RqRs2m
}

EntityColoring(travis_ci)
!define travis_ci(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, travis_ci, travis_ci)
!define travis_ci(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, travis_ci, travis_ci)
!define travis_ciParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, travis_ci, travis_ci)
!define travis_ciParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, travis_ci, travis_ci)
