sprite $treasuredata [64x6/16z] {
dOs7OKKn20CFOH3y_GVEQnFaR7gBjjrT0Y8pu_heLX6Wl8t85BeLkXLFb2XeltI0UYktHbCd69DJMOalw_CUsNAHlqZFOOqy5_ihBi9eydfTf2rDHJ_psQTT
0GCRhYRlxq2-DnnkOj3QJ0hFE5IkOhIzk7JFXoRN6zcCfq7-nY4Q5ItRsT1fdx2BfhBS1sohn3awqU1xoic_-GC
}

EntityColoring(treasuredata)
!define treasuredata(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, treasuredata, treasuredata)
!define treasuredata(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, treasuredata, treasuredata)
!define treasuredataParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, treasuredata, treasuredata)
!define treasuredataParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, treasuredata, treasuredata)
