sprite $trello [64x64/16z] {
xTD5cWGX04FXu4dT_y3ZHiOesfj_c-zj402nKZkm9Jmfr4wimV8n3P6Qm5mrXTIbOEVNpJ6dBtAZtZJRF0_ebVSSfgcJOGBrZ0azktOcEEf5X0aNrQzUf-jN
l_hLwuhw19D6UWPqGXlfnPA_ADHGxsw-N_tgDQ3018s8w3KPjxsIgltnROWwdhj5aptdScLDzHLj9bT0Q1DvnAEYdNKDm0C
}

EntityColoring(trello)
!define trello(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, trello, trello)
!define trello(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, trello, trello)
!define trelloParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, trello, trello)
!define trelloParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, trello, trello)
