sprite $truffle_icon [64x63/16z] {
dPQ7SkqW34HH0SJo___xOZHYhBacro-RxlYeBBKSH5Bx69Z06BqAbVyHgG5pJWoptiq0MEMtj7JWOflG3gWTC7r5syhSnK4MLHMcGc8ONoEmqxRenQgAh9zC
t66_6r4nBxokr2lnpL0LuZxuJ9FDXQygHLLy75ghobTULYawv1ikZYkLmXtBIm2cT3qbFfd08sU_lYzske1skNWAG8xFlc8jd2zShY2kvRyGGyyubi6h-3AM
bSwxq4hHKl5fOeyNLlNBkeOLhc6c02J51ZqDN4vFroEBo25maSAmZ7FaC1_vRLwFq5kz41URbLBraRw6UujRF6T-b295CPWVqhinxEr7FH5yytprLeMoUT5-
s5SH3opNN_WQci6QqZjVykJnXiZyXPYTTF4GuMo-5xVxf_NKHwgEPD3YsovWp11kl0yyUcmWuqTjfVJOHafHVkP9bNS1g8TrFehwKjGRx_5LvVQF-ZJP5-yD
j9dS2GEZWub69Qlxr1HlmFBws0tieSUGJnmj-95cnv9MJHCJffGsM5y8swPaW1SWUMm1QogYRM2l57tWcsDI8w44CB6q4yKkaTS772FT0SXTp8AMGfdF1V2s
m7VHJ4DZcYNU2uiEgfOGjm4WO3GAarF_OKoCmMx12sesVcGjfcqCCZAFUWl0vQ3bK5e-UH962q97F8BRXxaS0JH5oFYsvtDy1k-cQwsgJ9ackPiZcAS0NaBr
Aq30h5eTBvmdOFPWv_8G8VzJl7HAssSUXH2nCrkgCOIMDf0az2WuhZ5Rsr7hUGIpXfOa8cAYMzGAJOlqimGklqW1oeTtLcnTvxkIjvySU5i3TTmzjddKqzMJ
ud1BHzX9o7THrWx4LUTx1tll6lr7Tji8k6GxlcgZCwUFPVHUqVsV0uJvVmvWGRqpyRJ7P0dUudgy__-nUURt9g0zDL_J-VeU3rLBP-xxuaCoZFEH-TuwvmnT
uiWyqFPbJuch1ZUSQp-B6W0lWl5oEygYEguGLIioF9n-8UbNY0nxJQ_5jO-8CApAAVK_
}

EntityColoring(truffle_icon)
!define truffle_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, truffle_icon, truffle_icon)
!define truffle_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, truffle_icon, truffle_icon)
!define truffle_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, truffle_icon, truffle_icon)
!define truffle_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, truffle_icon, truffle_icon)
