sprite $tsnode [64x24/16z] {
pTG5OiGm34JH4LkAxt_Urf7BZBk_47pX13loTCAtqwogr6zg6TK5VqDJr4DVFmdB1_trav1xVT_WB_XwfV53d-yAbfzvcq4_yzElohjsKUKY_f7NvvxHQUaQ
oFOqxXy43iNE8xRduUt3ZC1cCG0pQ7i_vkmhJNx_K4dDbGCKjyDIr9d0reQ0hApbgURP8T2iCmV6x1nwz5ZUUQrstaDPo_Bsdo6gI_3Qu9ePvvR6siPZNzvl
upXz0l725o6sTxTZ3ir7leO0S3dz0Fo5Jy2sjxGG0BPzDmZ0stwwrlPbw3YoVR1Nt7i7R7dVVe3cpk5ha8nE-FGA43efxO7jR-CQ0UTYnnhLMgE2k_ITzvui
zs4jvdlKZtpWe7ZlqqSFO_nqvWq
}

EntityColoring(tsnode)
!define tsnode(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, tsnode, tsnode)
!define tsnode(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, tsnode, tsnode)
!define tsnodeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, tsnode, tsnode)
!define tsnodeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, tsnode, tsnode)
