sprite $tsuru [64x48/16z] {
fTLNiWCX30LHXTlxN_8BZXCbAFhNTIO1SjfQoaLFB7fynIUmwhNW0s3X6pe0iUZnIHPX-JGyc-GoHrklEHwcrrkBPpd1aGMWhIV6EM5wa-IT3tEzrSvhbEEc
pqi7KnU8fp9F0VZMaptVlAY7a3cROdAtU-mztdFPFdQrd2YzEYux97PbDIa0RpnHSjtyiCaBZlTU1S-xpx9Djnoh_SrTilguphcuvh91ZszvipH0yGdw0qvv
WMmFXxWgJrmsuua3n-SylkNrmRZx14CdMzmaYv7Hn6rfsSy5vxum5RVlFMxgnrAHpBkvcbJ9elbZ46NcpLYdpgA-lLCcIx2Yw7rKFYbBawnAb8KHfQVEBKl-
2m
}

EntityColoring(tsuru)
!define tsuru(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, tsuru, tsuru)
!define tsuru(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, tsuru, tsuru)
!define tsuruParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, tsuru, tsuru)
!define tsuruParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, tsuru, tsuru)
