sprite $tumblr_icon [37x64/16z] {
xTL5ciGm34HXisLNtV-w0qrHm9-q7EX__OAce6JmGS9IfIFgdcWueWX7LEY8n155EA96EufmH48xAhIZ12kwDMQKGJDge1MLoHE8Ka8TjFH0M_lZ4Mvu1AM5
UDCEZKGjtDNJJzP-LVIEtf5uec5igpU8uIppe1ex_GtIwgZJK6zFJ4MslF84Sqo0RFfvArEVloj8dbkrnVzS_bcnddSprhkzuruud4J6JxZ9WoTeCHna0HLC
bIYnz85x8FN-OPy
}

EntityColoring(tumblr_icon)
!define tumblr_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, tumblr_icon, tumblr_icon)
!define tumblr_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, tumblr_icon, tumblr_icon)
!define tumblr_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, tumblr_icon, tumblr_icon)
!define tumblr_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, tumblr_icon, tumblr_icon)
