sprite $turborepo_icon [52x64/16z] {
bPQ7qgmW34QJ04cmyVvlU_tP4Z_5lUEPfZ1dKhVG0Ia-hrjhJOXB5gR_aNnf7nAnkPjceNlOke3EZcdY6yEt5eJJiJooD8njcQgPCR5QMEbInoUhRSP49El7
KWnbRsE9yq2AZKALfHk5nd1-MndBMJUZUxXuf-2fq4-IVQG7iBgx2JsZTEKXVOiqF_RKVHWi5VDQtOgC5BTh0jFQlgmrNHtFfxEr8JZfzzeohjs0-HWhdQPa
RSoc562WscwnSEGOo6yDb2nQf-qd6IjAFUHsgk7ypX2eLpWTxsiHPYdJKQgnT-_aKWic-QOnjq2W2m9Xb0xu812_Te6tKOTm0Dkfe193fnDBj0uBgd01b6i6
sNVeM-jA5xvfJp2XIA0I05DOubjeXpQ8ZtWuHw9j-jC1rlR6hqwzvfPsQ85M8t67FPXW5G6vBaBsMYiP306erwKgk-A75Tq4bJHOKjiTEpIXBGoP7IwYaxjJ
uEjZJQ7aK28rsHrFVKA12tLIRS5AK0vVlWwMwZujS5G8o_bZRZ-P25BBz0Ulzm9qHb-fTT9shwm2OQf2NuSiGXWctdaQAvM2567WfmHPCXqm2DDXNSO_Fp6R
21CaczRj_Lz9XH2FffrXsHbUUFL43qZy9-aJ9Rl_IG-CNhuzCbZhkMMYDgWPHubn-DNsMqkqNg9q1QoHKSibTCUAd8JIhs1Z8BkEMycfZvIB-VUqZ3C0d8dZ
HVckKZzAuJWcZ71IFpkEVzB7MZ7_EARt4Vu1
}

EntityColoring(turborepo_icon)
!define turborepo_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, turborepo_icon, turborepo_icon)
!define turborepo_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, turborepo_icon, turborepo_icon)
!define turborepo_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, turborepo_icon, turborepo_icon)
!define turborepo_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, turborepo_icon, turborepo_icon)
