sprite $turret [43x64/16z] {
xT053iGm3011Xst__xzNvgqgF556L0YkIFA5oKHzOq56pHT5HgaFFVyAvhjvgD9GjuclZdSOolumj0_jGuFwDml2Otda93GT6G_IKGjoaLxE2BAJAg0wQGAQ
4nMWV2q1zfRf8PYZA0_HMPA7vAnGLbOfAskKbIbbPSPPEInbPP6oianPMQ6ih59MrYWhKyZwNQlQnD_PH0Fjp3JGIAPEMDSD
}

EntityColoring(turret)
!define turret(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, turret, turret)
!define turret(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, turret, turret)
!define turretParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, turret, turret)
!define turretParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, turret, turret)
