sprite $twilio_icon [64x64/16z] {
fLVhikOW25iKIVh-3xpNpa7IpqDdbd-s1CCbhVuuc0qFaDT58jQqyh8pyo2lpKYiyHOz8x6R4Mvlq4Yq6fUrQ868qR_DU_7g3ESwZ0RTK721dwlm4QxSII8Y
0g06ZazmQTQQjisID0NVmncZAMryapl3-kR4iVASn_x4eGksmMNp8qrkAORqvcmp0q0U2gj-nhwsWZnwoO1s9_KiwdIVbXZRrqvnnoCWUOjrMvDBgyLH277A
8CEgFxHRgsmVZnv19ZCaOMQqRAYCKkwMBjZUkmIVPKhpVHAk64Xi5vqjbKtXRCPI71LYLgyunLS2WuLQkxyakLnLPtl-hj9K9qJEJk6M3r7fImUGcTvcgDiP
I_jq1ZDq1c1XEy27ufVYe_u1GRZjQqHAMwei-5Ss-V_uCt_p5JvqBVorVledOfYkF-0XUFa-5873dZuvFnBwe7-TdwMpOOt-wqS2apdgh_MVebYYNzMVwbV7
RyhtuoMUMRLLk0b_IBmG7sofq5xh7_b-Mop9xHPrFEZFigNhxmUrNOQZGrJ2gFEAkw8MzzfK-oFNjRqh47FxQIzWpHmG_Pz9VSwcdpDjUH_0S5231EZXD3sK
z2UOUN1qwkclFUA67ZzR2XF74wpAnAsvb-3XW6itnjmznkADbjOfWpGIuUxJFP1WXMjrr1Jv92zTw8rnFfoYmROJjjXjRis0nY52IhenarxfhQOtcq4sjzys
n0BbClRHVW4
}

EntityColoring(twilio_icon)
!define twilio_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, twilio_icon, twilio_icon)
!define twilio_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, twilio_icon, twilio_icon)
!define twilio_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, twilio_icon, twilio_icon)
!define twilio_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, twilio_icon, twilio_icon)
