sprite $twilio [64x19/16z] {
fLG74cKn23AM2FU_y0P_o_R6J7WL5LDCMDaWkjp-2Ga-WBt-GRv9O5Ur8lY_o3iUDlOLuDjAbhlF4Dt5a_jsqg-6-7SceL4Du0exYkeusRTRaMbcWU-S120z
QmDzfqTOWV0cOJRXLf6iE73pp4CHUU3IwqxngcAPjKJo7T8lAr601m3Hri0stPACoQyytdf66kJU6ri5fedzfP-mkl53-zOlK9ZFDSqzv4DWlEgNhFaWvANl
-PuWySFyh_urtwYuypUdwoH_wF-bJxw0-5QFXpx9x_ilFRlMsDmjlSMtzVSMtVFVhlGvNP36PG2H2dBhYTKSm7-y_gnmu5EOBQWpSLYZzg6J3BBXFrt_7beT
ZxK-D7ojVu_qzmRYlV_-VV_p7_R_Vvu_Nm
}

EntityColoring(twilio)
!define twilio(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, twilio, twilio)
!define twilio(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, twilio, twilio)
!define twilioParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, twilio, twilio)
!define twilioParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, twilio, twilio)
