sprite $twitter [64x52/16z] {
hPDNaYem40CdjUz_unT8Me83Kzk_qB9657Q8Hm4PRXsYnWrA2NQOviKGr2CKkq2i7sSyWvjvmiZRv_YHBWh-vzY5kYJESEbFIBf4JK-efHwN1nO1mLoF8bKm
JOXvUnZKpmFBpwuNzVmLtYl4LbT5JIfggp-VIFcXhxtoUPUA8xyc6obYuwyUWSfmTLlvAl0C5nQ-2CQtQ3vtrUpuGOL_7K0yNS_Nlc_-8XkmN_EpuvS96dvO
iu3c4zMhBsZL5qvlVP6qwWklndgo_n7qdq-WyRoWTRt8nlMz0gG9uRJQ2wVNNXG7UjWSBrh72uzrHDgMR6mdl7hbDK1VNzzEx8PZB2YVlFaVeF6xwUGDb6z6
wzZ24sOoANiJqPA5HuBSoZYG_m8
}

EntityColoring(twitter)
!define twitter(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, twitter, twitter)
!define twitter(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, twitter, twitter)
!define twitterParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, twitter, twitter)
!define twitterParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, twitter, twitter)
