sprite $typeform_icon [64x64/16z] {
fTTLbk0m30NHaenwdjx_SgUPEwZxcrFXn3QRIWzfFP6Y5wufGz6hcu6PrnuQVg6EQCOtrcCwfzXKvGzDWnEgEXk6d2DTlhVlohuvsMFgYStFOh39rU3-3boL
4w9lvOLJr58vffB9mMMP75hmdQbonUof7EHy4OsBQl1f3YwRZNSzkCwryJJE6frNgjnXCfwr2IHEGCuzhkt3U_mq-IKg4CuVoiDF_uoVwWGFRlV8w8E_-7hr
NAuNuhTPYSeE-_Vm83RLYJpHcv0bUi8NcNwsNDz6hY-HktwJFDMlA9aUZPxgeyvSRqhraoYvlerSRyhq0RCbUe4hqIzWjiJxkp_-sDhlIm3qmHP_meRFKeLx
ecP6qCzdtu8xsipC823ApgJoM0a-c1fNgP3PGPyxS_TZlenlB0P0OX8ymu349BofikFuOZscSQoeiQ6h6mUw2fkixwzLZzUHrY9wsLmOJ-UGzuWvQZ7ZdLbf
Kz6CSwpqAQsbU2OjnQY_uaS
}

EntityColoring(typeform_icon)
!define typeform_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, typeform_icon, typeform_icon)
!define typeform_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, typeform_icon, typeform_icon)
!define typeform_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, typeform_icon, typeform_icon)
!define typeform_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, typeform_icon, typeform_icon)
