sprite $typescript_icon [64x64/16z] {
xPL7TiKm24MDgS_xts-QV70-lubCepipEbSLyF7lMImMYyK2Zwd3JtstHpXEsvLt5lLdCs3V7a7u6VGStHrj7_exf6ZwiDkOeUbJ2SQyloDtJynZ8euNxnUo
VIEHxmK-Pm8WUVvdG8UFkZF_Ze0vSgJfZu-CD_sCz7tUpX3-vEVpamIQVdrQTlHz-7RHl_-ImDttp_fB65t_08osHD3nSuPh3uwMFm2SymGzlvw2cZvGdZ8w
FY3vYU5xmuVIzUZHN3-VNl433nypVgqUCw7iQZD-bc_5qEiV1UxbN_2yVa0UrH_Drv_jtnXAwewh8rPWvaV-C7WpilW4
}

EntityColoring(typescript_icon)
!define typescript_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, typescript_icon, typescript_icon)
!define typescript_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, typescript_icon, typescript_icon)
!define typescript_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, typescript_icon, typescript_icon)
!define typescript_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, typescript_icon, typescript_icon)
