sprite $ubuntu [64x64/16z] {
fPTRUWCX28M38lop_mNtNZ-7m4njpakRnCCTn4S1QJhSuG0txVBOWQW1nmJWslxAxZQv2y1L_i9sZW9mAw5DTYNXqk_1SGDCDfL7q2lF0xi28wNhZUVCb689
VLpJXtpuPxK0lQ6VbM1xllER8F8OD6gVOL5dKu2kV4_9FlG3ms0yyG_QPUmOo-_kyp_c2Q-jvq3EmMtFOK8hwt52aJdjMH4IXKx1Yf_uufYgaIRLa_fsD7JM
hBzeG2TfZyxNZ-q3yYj27YqpmABnNp16Du0vTn9TlfHKA4nPsWKqppGzYaJoWoPfhcoQ7yhQY2cToGfz4THN1Obd1j0QYVUTkeNrHD3v4JxZ4QiysXRZRUEN
xJQhjbFEa2ZSROblSsG9NWH9RF2r5-Kx01mfQCcayzD87yZYOK3g7QUgQRJPfUKyErxbr_RhfVqgdyZyVob-Ct_YjDtypVgnOV-fdwL-cJCzvxUiVb_jdwH_
ymWK_PlCZxG3o_cXqO3C0bnImNOnFu_v0zEigArVp6zJvmi-fBWfAU-FnbSbjzxNrLS8AQdlhxXagOD3Dj4qkpz9xi-O5AlkRmDDxk_ghkdt-qEV9xCrqeud
UB6_B2T2N0C0K-szgtcnFxs-lqtexlvec-jlE6N_sPzb4BfnGm3kSFa6qOttmmiFa8idb1YtR6_xhxzSUGw5aloPXNke5-_NmAxHXaCajxqdU1_kV77THo_9
xm
}

EntityColoring(ubuntu)
!define ubuntu(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, ubuntu, ubuntu)
!define ubuntu(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, ubuntu, ubuntu)
!define ubuntuParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, ubuntu, ubuntu)
!define ubuntuParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, ubuntu, ubuntu)
