sprite $udacity [64x12/16z] {
dT05OYCn38NX_qb6ITxxtxPjafbbDjDd0jiRG3F4lmUDc2deCSF_m-SI8PJEVddTMGA0kxAxOv890QY4uf6vV0iW7JjP8S2E0-pASjW3ppePj8AHUNjTlYTG
3IjO0QopWHN23M80NW1xsV4VV4iWNrubA2-3Se1llEeCKd3vC83-nKE9VjQd-LDFBvv-TnHu0637y6DFFnCorxYUulwjRmbfODazMZO0c9KrUFvV6bv0jjV_
TTXFdzn-Bi1sLLmSv08mCq2w2_Ex2OAhqfw6PdR-BpnivjB_ydS
}

EntityColoring(udacity)
!define udacity(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, udacity, udacity)
!define udacity(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, udacity, udacity)
!define udacityParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, udacity, udacity)
!define udacityParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, udacity, udacity)
