sprite $udemy [64x24/16z] {
fPC7kkCm28G5g5aIpFrlky9y6tlBQywaCCBvAKcSKgBQE3rNxiVHorDQDktgyepVQ6Dk_UZqoX7Hz_beBFt6BvlVtvv-cokdMEcHtkU9wU9P-7Q5hlURL0yF
NHTjO1YmQl1b0T2wtT2vSpOeJuEsL5KbkOOkO9uEe2I6aFCTeLr-8QGHAdjsItQyyMJ0A6MSV0PMPfb0SLvBDVZbldsQCDzZmtpZAz3TD-SdDFOxFIIb6X-T
01LWxqM6aMwyLmrcvmmsNJjIr98etm7sgcV1VF56ArfwYqcuz1---qJBYrpyrNzjth1AFUNx_ytpzW9KvpL6Dj-xkI_032Rq7pvDMBIRmCmo72433f4EOFbo
AnFNrUb_V0RYA8QGUEFRxty0C7_n__YaY9XaEZ35VLuEzBZ_clfX-B2szfdDcgVDs8DF7EASFHDUvBh_ESishtEyHuWVxmqfz3dCPG3rEL_Wsx_5Jmhx2m
}

EntityColoring(udemy)
!define udemy(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, udemy, udemy)
!define udemy(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, udemy, udemy)
!define udemyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, udemy, udemy)
!define udemyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, udemy, udemy)
