sprite $uikit [55x64/16z] {
xPL9OWCX30GD27h-_-7iILywfZXxTF9Mdcg9vV5lpTKUnzNNTQaEeJPrVPGqJgZn1Ns1gtC_NIvD5h5-88D5_7ufO-h0C3yCWgadNDGJAD2Rahje1HMOzvUV
tuNnPx0idQBo5l7njp9qC95bojmQPAq546ZE0CAc98olcupnXbQO0eWeON2OEmAD6SGO1uq5a601R2-DtTYDZGtL0-RRX9soy3OfGznqB5FOj0SecUv3AO6r
2wKeuAjzA7vT_YP4pA5KxOd7x0wLexVyhxj6PzEScIy3XmABBeKYIuYlyn88XKt1xMVJ60gOXb3058GAEonCYfaw5A-sdeLw1m
}

EntityColoring(uikit)
!define uikit(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, uikit, uikit)
!define uikit(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, uikit, uikit)
!define uikitParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, uikit, uikit)
!define uikitParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, uikit, uikit)
