sprite $umu [47x64/16z] {
jPH7WiCm3CIc-FzVtkfkC-8SX3F2m6feGics6YBbbSKDySp7_tvIZAmeHbOK8skTSX_vYIm7IBM-lDZqF9sYhQvE01RSGbZ9RCWDS93Pe4SGPzG9x-VW1eEK
KOxmf9soqacHLUHNspdANuVfyUjwED--X8NEvAn9nKB5HvdkWEpeAyn1vZF9oSSZymL4gmb4-SJCXyJ8SeGi1vbFNA2Ne0OOw0vrFlIa9bmRfMj3LQmr0ROH
G9i826iKro31viGQpAsXDRE69_qR
}

EntityColoring(umu)
!define umu(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, umu, umu)
!define umu(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, umu, umu)
!define umuParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, umu, umu)
!define umuParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, umu, umu)
