sprite $undertow [64x37/16z] {
jTC7RiCm38NXnobIzpzmHNWbiOLcVbXT_mCTr9WG4rmW4_oFn0UbyweFGlY7-O9nXzUVspy3v2ixpnwxS-mRtF6D_BONNzbtU_jwJxYY__MAbTA7lNpOEoxO
VxtjVVkd_-SkpJTx0OgzsokZj7ppypD5YSjUV3Fl3GDdOaSimW_l3yt-_zr1W1-zj2ZD2A3h5-MOPKG3c-RUgwceHsQ60Bwno_CToD7d4ElfJ1X88pCOUdK0
7wlWzAKtW2oozvvXl7pZOD_nENU6TOFcmD3cPjOonqGJW5iGp7UwNkOx0o85Fl86OIpOeXOOiFM06ORs9CJe1RUq5fmW0lKf1Q8l7r_30wsdK0mwp-6zArfc
41vHwxq7pmSKqDuJl5v_OdM24I1-WPSR5MsI0v9zUOZJWbNXTI0iGp11NWiX05ZiY0c0H8spXX7c9FiGIYWqe9167r9OZtfwmf3Df5eGiNfaBwd0_xWMIgxw
AXY7_nPEqWXF8stt4p6fvqZsnmuNdFq1
}

EntityColoring(undertow)
!define undertow(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, undertow, undertow)
!define undertow(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, undertow, undertow)
!define undertowParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, undertow, undertow)
!define undertowParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, undertow, undertow)
