sprite $unity [62x64/16z] {
dPTNOi0W34DPPfhx7xUxQb58JQhlF69vCDm_57FFxbyAKeVEsP-JFfMkyqFg7uUhyqVfIRXjw5nKJiEj8A4pun56MHfCM81U9MRGOzwhMdJXQ7-lDgnCwq9M
2VB0UFqXctnykpZ9V-TRFqXjERfFvSL7sr9IQtdNcAezHtznKhwC-msS4My1kJXfNmOqRc3zXkFLoLUsAXktOTVHu4BDQi90r2C1wasO-ouZ39vI8PZx3j4M
c3Y24MpwdS1EC3vXjQL3FD9lm5IjTJ4nOAeM5Q0TmOBUf3ISm7vGe9WsWeL0gXRrV3LWX4brJ702UDQmKwED33MJ1Pww5NOYga87RAlGI7muoOVmkFHFHV9i
zKigAyfneBo9_1nNpsFJtOhNk5E_grW2ZeQuAjvt2-7KvhGLS_CMT_1thzZ7Q6JT2PwfvZIX5euDbNU78pnHrHgjPk0qPmE3Su1prQ8kUM0yxAj6_LNT7X_X
hcf29v61SzKyLa8E3Ppsz0GNzpYldFZqB-ulNC9DrSOV8vNhf_JpZdQzl-MhxRl-qb5JMCDIQjEz6ihVI_ANUsi-l6bY1PaGRDjNJQoWzYsN-ujbsaP_tKkS
AQd3U5aO2hcftfzCjZmzRdWwdp-iqZ79ZpfkqtF5t9Idyx69h-by1G
}

EntityColoring(unity)
!define unity(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, unity, unity)
!define unity(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, unity, unity)
!define unityParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, unity, unity)
!define unityParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, unity, unity)
