sprite $unitjs [61x64/16z] {
dTO5SiKm40DGmneMxd_UEfbu5FZTW8PARohvayDDOaxXSo9HZj_nIFgEmR_XRzrJv_gHnwgct0jzw5v4rOIPsskUMNN3Wx_gdlgGmFnaEiRg2TzFnzWBlfsE
iJ-nt4vFRJfWfDV9Vzcgwc1tEeaws9sUEv23XMTtqDXKVGo-JOSLVOY5EtFRuKnP7s9fAJCpS2Ggpx3m84US5smFiBGOJZZHI7-2ImXdJ4kAsWqMpk624wrf
DrXw2XSSQOkOWs4FE4zSrVx7qcEuuaWqmtQ4PXF37Z7iySo6R6mcw7p5YH2ScGrLKoWJC-mEHqYScPaoBJMJRZY7NpWVSTtwpd_4AnOwsdvvXh7AY9fomTdK
1KlTqrXPWBS35rioyBvYKZaUTA2LNh6kCMq1OJqSLgo3EbZDTdzUL6Y_LjZ7Wql66qo3BInyYzMK9g1qhUnZQ2HsOGzxEathOUYyjvbX7GoTO0dAnT0SOTzY
jRRP8k-nMe7rSJTepFxFjYEcAXTk_RVjbO0phMbwvaPqfQUFsBHzL_g9cpxvSC-JizdRQmMgOxf_eOcWw8xfhwvIn-dlBt7epcR068ihcCkRcDrTNFtkzlhA
3Cvgxo_hc2wc_bX_kZlMxuwye7Z6-cFzxcZyXOE-J_8Q_m4
}

EntityColoring(unitjs)
!define unitjs(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, unitjs, unitjs)
!define unitjs(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, unitjs, unitjs)
!define unitjsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, unitjs, unitjs)
!define unitjsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, unitjs, unitjs)
