sprite $unito [64x20/16z] {
jPG5OWGn24LnnaBkVzkMqAwx_9NHXoSmH6BkfepmYaZDIyPmIvF21V6WIwOtSEuD0CokuYczvxzjny6R7qlWjjfwT7cAkz4fWInKlX20syQulqcs1qLqbu5i
aW5l2A0j8gP4yh_r7WBWyQkLGVU9emX9sabUUvgP0u6Y2S_TYq__WZ3tHTYZ3VUSVuPcRdbjTCHxbr6ruYj_Zda4sTVqJCdhG5dF-2boADPso4-T8RNsr_Yv
8wJcdcZEdp7x4_xZtxzMvLJGHWyoY4ej3yiLVf__N-p4TZo168rHOuKZVlxZz_M7SkjsEZyQlzeeEqt9P_qtpxFXklfFD-ONjKwHnZzU6Sfdra_fzlh5R-qV
josykd_z
}

EntityColoring(unito)
!define unito(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, unito, unito)
!define unito(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, unito, unito)
!define unitoParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, unito, unito)
!define unitoParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, unito, unito)
