sprite $unrealengine_icon [64x64/16z] {
fPS7bkim24L1lI3U_dVxVp8UZv5Bx9CxDHnT14OffXCub3uK07Jq4XqzmMTvUxNyftPHO9Hmrqu2xTdpfXYNcc9alc5dXIG-QgX3owSCSQ1vEi5LrNnbSuCO
Uv_XQa5GJVI1C93FEeVS6LD5EudNc_FHpaTwffi423_NROAvTwFVID3iuwFU-MAK2MMxKcKdfpuYdLCGQAMfc-oYGDXRBguroM1QY4ZpX034VKcYRPNyNyj3
vbCCeDD1ISrqiDIIuKsD0zXl7mTWnywwRA7zG8URBjSBEv1btsJ2F73WDxmeKqVwRaTCznqBQIcdjSW_GMMob5V4cukVy8kMl0m7YZUL9jnBpTkqhFXZgQjY
8T2CzFUFlKopxtyBSZIJbLdpoVOG6rIc6OyOu4tteyfzdxMMRRYZBSEwvvD87zjqOsduhbzrz6qxuJsM-tw6ratxGW_zQ0vbYK_zOFp4t_bCt_dqt8VMR_o8
qR_nCxeyzZTv2ghoGxywMkaZmZtosHIipI5zy6dhEq6qBq2ZVV0J5W9nKWppQkUewfcFy7xzn8eeOCfzzH8GoE9NePQci8Xv-IX4P4-0SrnnWP_A9yfc0due
Jh7LBpkpFSBnoYzcvT9vLMV3CphmGvvU_3RlOwQ5IVVyZgWzAMczy7aQ0JUZ1oAdW7YxIFjV9OCiGOp-2jZDxMSUZqeJeUf6tvFCA38IpR3FjVSJtQFPQX3e
0Ku7aw4_IS13tHoI-mdSKB_FAKZtTA-hRcWeT_I4uUYG0l4VMszeV75pK_Xwy-jR92xGV9uX2hgZIto3biCrd0RanenyLKZsjWgNkgBVd32_5glK7CD_OYvT
0ScExiEnYkANqTAP_0y
}

EntityColoring(unrealengine_icon)
!define unrealengine_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, unrealengine_icon, unrealengine_icon)
!define unrealengine_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, unrealengine_icon, unrealengine_icon)
!define unrealengine_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, unrealengine_icon, unrealengine_icon)
!define unrealengine_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, unrealengine_icon, unrealengine_icon)
