sprite $unrealengine [64x53/16z] {
tTNPmiGc20NWew2eeBp_sxR4pFJVa-dUVZVPE99TV2kLhXP6pNXPRjfBJa3At7GGNYDQ4tx3sXFkozeItgl6k8kiu9Di1VTa8tmXQS4joZWnlHytuuRMiDKv
4hPK8igAQwIFRhuUwRuwGg-uD0e2BVU10oyt79BXIjPTETtT4i2jkZjZwmKNH7QXXva0YoLEF71XlwbvULW9QEwkUD247oL5aCNzJNwy7_xwyWSZVvbl1J-Y
NIhu9Y-27t57oE_pYeVQRlN7r_dh_bb_obzVV_gKbvtFxTRztmNF_Fac6NYMMyyV8c_oBjmzJBVdxRbt0-hmT-Zk1pZu-VsziNF9xd__P7vORBuA3brmxLaa
C-A4r38ERA_-_wGJdfBHt_B_1Hb_DMfzPVx11yKOBsZwhXlho7X9xkVyYyIYW_6ocFyFesRyNYab_A-9S2n81DIQ480iahAq83KZLiCkh7BKe4X5SE-nQBvI
EsSiTYVsqqhFrGOWDYm2wlFCjqTUeaYV-Lwhg3kpUwiX-ffFztBaxND-TNTvvAESpdm908ex3RTlyqdTYIA_cmvVcVsKWUaZngoVyhBpIDDdtVbj82v5Ga9r
rzwNpxVvoKHilevpYD6NE-rGixqg53AcdmJgiuJX9ztvwF7k-WlxgOjxvL9OZmlTagZDQTeIYexzwQfcKiq0iYfbFKdNXa2gBBhXtsNCNnMR5SLIZIihR1JR
RAHcTZ41pYbIoPVduhIib3cgio-dukmcJV0ZypcDNCp4ULNI8x-QpLYiEGT-D2rUT2zvBQUbfKsBO8rjNbgbNlLtNtLLL5-vhTWeY_SsJLy-Czxv1G
}

EntityColoring(unrealengine)
!define unrealengine(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, unrealengine, unrealengine)
!define unrealengine(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, unrealengine, unrealengine)
!define unrealengineParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, unrealengine, unrealengine)
!define unrealengineParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, unrealengine, unrealengine)
