sprite $upcase [64x14/16z] {
fP85aYGn30H5jbJ-_uDlIY7VCkU0CLiGBTzYX_m5hrHvdxMCGomNyKLS6esTDsnMRMcScogYQm0MzmifacWwbXT86MFKW-XeQ4mSmxd-5jb05i2fuI1t0IvY
rMZlrihniy4BFwMpw3_liZhxPWijFiLdHiuRFm1Lz7QpQl2EQa8SiFTzJM2EIMUVQjaLT5EsqJyWzhh-14Et_wBtsgDk4By-72_yWzi-n8HlVHwW8keRA0O8
Vo1rYeV0ebyHphvmcwCQMpWi5-EuWQV-BI0zwi1k_vh0gV2eIMDmL9ZNZK-axbim_h2cm1T-W9ofln5brTNNTj4Vl72G9Y-mdCkEuHy
}

EntityColoring(upcase)
!define upcase(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, upcase, upcase)
!define upcase(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, upcase, upcase)
!define upcaseParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, upcase, upcase)
!define upcaseParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, upcase, upcase)
