sprite $upwork [64x19/16z] {
nP1N4cuX38A9mTEFsVzkB_BNrzkPiGwV9k3NTDKAwt_pP49gPFmItxlvf5T4onPQI5-cPh-SsxxQG6gaURjUVE-JQ9rI8ge8cIuWgm97JUr2ghPRr-OtRRxu
XiO-nSHP6s9CT9L9-BbVUa2yD0xn2zgexSCBYpaGrBo8egpKIskMtC1IbI6w1yGVswZHFhoatvlseRjM5LiT-c1Ks-k4D8kASd3YfPjV-T5FsCTEtDNFohfO
DmupW1vqCEQ7yx3N_rDRx_s_lETGJEEKQw_ZzV-7NrTlqmKqpU8qF_i7dVUckOEQNlr_U3qt0c2tQ52QKyBXcvH7JiKr9tppifmGHK4Cbq8VX9i9sHrTd2K9
V_EtUD0He6MsLsoHcO6fNBhclYIck1-RmMK9lE-vBFZ8TV-wehFz3jySmgzByVq2zGC
}

EntityColoring(upwork)
!define upwork(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, upwork, upwork)
!define upwork(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, upwork, upwork)
!define upworkParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, upwork, upwork)
!define upworkParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, upwork, upwork)
