sprite $user_testing [64x17/16z] {
fTA5iM0n34DHIRPZgV-6TxBqcU_3m1aCJzvgy8asRzVukBpJuhMApxt_FY-zRiH30rhFV2indDqaVzxstb_STneg0YoXKoYAgckhg0S_b6AHia7gUZ13Rkox
bdAiQ7tNwCHvyAeufKGLJFpR8uE9UDoHK16lfrB7n7dabvpm9iF9Vxzn4csM2gy_GDeDA4a6oK7kQrM-FV77eWZIvy6xxxkJn5IXKzNmibenzf6dTypsP9Z3
r9LfUJU_yzH9tBt_tfD_lWLmJW5z6j1ms7SarCp9UotURRtfy_tposu1no-wrlRWcqqo-4bQusSDyRb-0G
}

EntityColoring(user_testing)
!define user_testing(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, user_testing, user_testing)
!define user_testing(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, user_testing, user_testing)
!define user_testingParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, user_testing, user_testing)
!define user_testingParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, user_testing, user_testing)
