sprite $uwsgi [64x20/16z] {
VP87iYCm24DnBxJxttR1-AVFAbNEF2GyWQTIMnFUD5RF06Li8bmDGdKYqNQNvtm56ZEbDnwP1mpYq4uUigvR2Ofzm5EPc4j4rEU1JMNQ2vbEkstM7VCA_ZFE
b8Zoev0Txkncjb6Wsv5Lzq-k-OEVpFjo_VgL7gN6sFL6kBCvdxpdvUY8jqyt_bvA6GcCk2xrxFsbb78ESYavgqgBjRdQ9tkqcV6QWF1G4H5LRM1QgWj8TNjj
qpexOhXT4zpMlFx3Joi0oS-4Copc2P2GJJJolP7v7xwQAqsF9eXgzqqtYubd0bWYXvzhpTa_-HCzKHMtAlkS75kZkAZ05ba-ylZznOEnvwJO6zlpqNIoLqZh
yiI_-Q4k0I1rBNWe6ofpYc3u-PClTtNewchmb7Ud8SBXnkLbz-I-z6qOiCRMITHqVcabY6PyDQ2yyVNb_-CXHk7je-HpIV390uciDxxKwWDJgOVlqJescJxN
r_Q4X8Ow9ksLppwWs5lm-N7ffEg33y5xROxgQ1-ut0OFmVeZ1pQ3xofmjEIAFJXjCQcOWeVJ8AMS4vYcvi2IR0ZLHHuwKjYscPbepvetuZy
}

EntityColoring(uwsgi)
!define uwsgi(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, uwsgi, uwsgi)
!define uwsgi(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, uwsgi, uwsgi)
!define uwsgiParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, uwsgi, uwsgi)
!define uwsgiParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, uwsgi, uwsgi)
