sprite $vaadin [64x16/16z] {
fP05ic0n20I7OF6v_sstMFlk_IJQXU2hMAOBla_pJCCdqHs8hNY2f-EJ12SMunrVlG4m5uY7eh0m51hUEQ5Tq5gTFlZb0GLv02M7NP8TQ9la4g2pcEZNWxmr
_-TR_LnhCKZ3u8dBUyZ08dTT3NBVcaocbJp9U8ZV8ZEzLPY1ImqUGUTMKk5as-oGpV8xLiNkNAMN6WA8UcQYyGOt1ZkWFCuDuD8EjPH_VW9rhP0_FbhvmE9b
8BcbwlWNNnV7l_Y9nVxWM_fVELHGbw-W_QcViSWQHsrVykhaaR_-jOV-_P6Bmm70BeibcyL5bar69sqoAn37__vPu1yQKeDuD7Mf8sskW9Y96SGDhVPXBl_y
7_13lrcc_S2tp13yvnS
}

EntityColoring(vaadin)
!define vaadin(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, vaadin, vaadin)
!define vaadin(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, vaadin, vaadin)
!define vaadinParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, vaadin, vaadin)
!define vaadinParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, vaadin, vaadin)
