sprite $vaddy [64x64/16z] {
fTC7rkew30JWKPdHs_-6N_Dna4qCvDplhu16KXgEB399CZCSJrbmaOu7d3VYjwZ1a_SSW7rE1n0yIeCvpY9WoKyS5eQ3J1Y_S5WQxXXR_CpXwRTnmgXlI4VG
x-8ElbUJsj2GzFTu8hbdyrzx3-OOjaWHpXxEi7OdznOC16beWWpqalqSMz-D04MyEEVudZvtY37mGgcDP-1MS5tW6X8IpQY1ZWFdQq9An62KY6pnxmtWl2fJ
RVqUjo3Nan6poa29h_4-ru-RuiGbDJWeoJ6ENhIOYssbsxjppKJEzwbs-8ufr2Gcdnt7MC3LyiHaLEVR0Xovm0WIF8qVk2r0sFWpWWdU7kVv38oyRFn9Z3_7
l0nJzhoxslwEYuxvwFcCdhVpV5oi7RyuweISHUVpDxNpByryR7dJ8h2kncs0-JO4UHgFqOzR_xrgAR0zxz3KJY1mkm4DtJpzGurV29Lk7tS65gPI8g_y_nHG
oR0pmyvLSgY6-PT8AV23a0Y_SZN8JKNyW2N7Z5NMQu4IlZDL6w-OUGMa-6bzUusdwse0b_2L58Wh551DH2g-ZoTiPiQPk0GeV6OYsaW1KTMx4H-Hw1C9c9O6
cVWWrxWS0Ai9HE0eSoqN0BZwEmbt78J3LCtOLTNHSE10gBfH6hLGui1O2s9GhHJ7T2V3uFKcVGk7QfUOM3UOuVOVZrIz4rvKzoIf3XmlNeybkgY7Y5K-Zlz9
0-5TFfs-YwVndJyzypjZ_VL5oV51w6E7y_1-6izf6huBrM6suJUUgjf7EvwmoBb6YM4u-0S
}

EntityColoring(vaddy)
!define vaddy(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, vaddy, vaddy)
!define vaddy(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, vaddy, vaddy)
!define vaddyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, vaddy, vaddy)
!define vaddyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, vaddy, vaddy)
