sprite $vagrant [64x17/16z] {
dP5NWYCX30MV108amhl_RHVmj3UdAOSkFgf9i9hma5l6VzBSlUXLhSVnV_X5jgMs9Hh-ZtgYqDDlwL5maUV_RwJRsxPo-rTYgpx_Vq1CWNOo1sHBZuz0EG1q
9lm9em7PJvTXT_ed65J8cYbwhu3j6TngjR8jCaer3qk3m--y4KsUTRoeBCXiUOx5aZa7cIOPRMpJu6QLnJMVVTVxRq-lx73cQrwfw9J19lVL5YpIASO2GFtE
V7l1mrmo5wJrSVgYuuwHei_J2zuzxjJFvJqqDWQS4GnP91jEl-ZZz7hwGdkkq6-lU9D96eAvC7GDKzoUK_tT6ptVkJxoXc-ON08Zr_94pj4m9k1RQNxw9Rgu
iB5N7XdV82e0D8a8rEhWDW19eH35wxT76sctT_o6xFNq-2sfUaJJt_PZhb7n9wnbV8el
}

EntityColoring(vagrant)
!define vagrant(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, vagrant, vagrant)
!define vagrant(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, vagrant, vagrant)
!define vagrantParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, vagrant, vagrant)
!define vagrantParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, vagrant, vagrant)
