sprite $vault_icon [64x64/16z] {
fTG74jim34JHJuk06a3U_xIfdifOY6TTrJ1lMNDgBzFAJq8f7uskr1z0I3nqZOUGU32DXv1uC8s7a7WmWVyKO8pn_dqVhZmF0QArTazlRPlvQkryv5a3171D
WzTCu7ZamJxMjxL-vTS0wUunJ_Tz3dU_7_bw20f-3J3Eyynvd-Vrvp0A7gneVy53FFP_nOCLzGjV18WOCoFoVLZmtmp13cM0sBRjdlkssHnzswwQ1_jt_m_W
g7aWoletNmV8tdlCetUVmtg_AhxUY5Q-7eAyxtZe_3A0GNlWom06hszuY0U_vi6MzXTyDGG5Nmx1bpo4n8DfF8J4WsayXCI3VUIL0Fc_F9Z6GqWycCP3IZou
naDAFFZ2Am6Ihr-kyP0I3wxna18Fhl6G4W-kyP0rNmTm408eFBZ6Gqeyx5Nd_mG
}

EntityColoring(vault_icon)
!define vault_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, vault_icon, vault_icon)
!define vault_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, vault_icon, vault_icon)
!define vault_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, vault_icon, vault_icon)
!define vault_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, vault_icon, vault_icon)
