sprite $vercel_icon [64x56/16z] {
fT47GWGX54H1HfBub-dxdzRSvi0-wWgL_bPwsXBdaJPKQQGDKr9EMDUZIDHnwab9qD2pIsAoNi73q2jsM2KRzCuokJDqU7FgemhlRD8xw_2E7LPzC-YTPNXd
GU-imZkRzCuwk3CVeZiRzCuolBEWTrRXdStLEtXuaQ73AcE7KuOERxKW5kxOuPsMJ7fd7TxzVTXawF2OMfVXdGMzi_h77Jaikb87T-P3T6U3tbc6TnRqpYgy
CnzcGTrtXWwRiE4xAliE2jzHBRJbV
}

EntityColoring(vercel_icon)
!define vercel_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, vercel_icon, vercel_icon)
!define vercel_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, vercel_icon, vercel_icon)
!define vercel_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, vercel_icon, vercel_icon)
!define vercel_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, vercel_icon, vercel_icon)
