sprite $verdaccio_icon [64x54/16z] {
xT975iCW40HHK0Jc_kTrZksMHEtT-tdr5Mh8Il9RgzsezsqaztCgdO2bb59r9QUnNPhlVG5akVpcKofVzyq0ydZVOlAf0p3MzpJl0VxUvNi0mpHVv_CUO3Rv
l0TqllnZm5gUS_bZW1n9_XXGDlVEUm2O1O3j0lw0l1RPX01Bo5ecWDpqVY5lmEVx021l0I3l0I3l0JuF02uF023l0E7o1E3o163o5A1v2D0y1MWU0ZHF0Pgd
0CbpWEGnGF8S87aCa3m7I1u39Cy1aiS0oNE0v2b0yW0WUGQGF0P87WFap-S0-VCXe2j_1W
}

EntityColoring(verdaccio_icon)
!define verdaccio_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, verdaccio_icon, verdaccio_icon)
!define verdaccio_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, verdaccio_icon, verdaccio_icon)
!define verdaccio_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, verdaccio_icon, verdaccio_icon)
!define verdaccio_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, verdaccio_icon, verdaccio_icon)
