sprite $vernemq [64x58/16z] {
dTQ9dgqW20RmJqNG5j__SUylQJCSJzt_RAaGn9aD6q-H8tcyOSDzP1KTNd1qXFiplTaPSxVmiAMpCXsCqvK7ufuPzGj-e2QSNU1D071UZMYtT5w5A29xLUBj
6aEty533wwTzaDkr40OqHtjqBEhCryLeX9fopw-Vzlwb6enmZs3jHQDbGxfM7bRRSRowrImTn8v7mtk44rYCW2ulbaEGz2GEFMm3gMuR4LQtaBPbzpqCrmaB
EfPaC1hZA2V92ARye4jAXg0rdf8aWz3moN8uX9HJA-lfIVAm0cU3SKCfFqdRNdvA7YTdZnyJZjcGjwUsWg91TzcZHTb8RZoTLif6H1MovV1aewRi1tSsP394
dypi9tHu6vS3u3hRX1wUZFJNhbKh6TJRzEYZoSYfFvK-6pmlzfOEVmacVItpz13nDvaRqrBAEhSo1jmqDzPIojBUaZ32JV1IohE1XB7yJ6yRc0B6gEbUpHV1
BvnsCfNTaWxYFln_jfH3slTYm6_4QYgdXLN46rfCrdB9N7cy4NWpbvjLRFbn0waqfYtVuHtFifTVbtaz6o2y5KMVVYN0JyS47DvoU_jS5_Lrd3dWFSgrl5RC
ceylqZD_ylY2wlF7g_-4R-PZVcwgLm7VKAcE7yAChtAvMJs-SlCjdV2TEpkO0_uBJUlFL_uV
}

EntityColoring(vernemq)
!define vernemq(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, vernemq, vernemq)
!define vernemq(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, vernemq, vernemq)
!define vernemqParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, vernemq, vernemq)
!define vernemqParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, vernemq, vernemq)
