sprite $vimeo_icon [64x56/16z] {
bPLN5kH020DD4FU_yMOsUBfBR-kN9qP8O_lvNxBqdQuuZgCrenqUfql7OJu_KPxaFV-WzuBIpFAv83Gl5FVr-ZXyFcbON_JhInpMdmreJXIuIuZk_IDbZikv
S9UFoFsovZYScXihPxr07zTXmlKBoASW_2LdWGAaoipZ5iq21SJzZ9_HAADFmnTzi1XxQ541FybJHAMubPGlVSoRuErEBtx4slbF7WlospaQCFDo_GJwa-sd
S7qzRp30uEiv8Bv-AGWWOVSIKB2e-qNN08gYyG44TiV_K7RF0RHtpt_Xm7-URx3XAWnWgJZil3CUFO364gIlSUH3n1ZwOMIFPvhbuVHfvKnmTXuDVT4zZT5x
WkKUeToJBFS8vPxav3tDlNk4_pfF2BrxGgpsb6RKxl2l
}

EntityColoring(vimeo_icon)
!define vimeo_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, vimeo_icon, vimeo_icon)
!define vimeo_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, vimeo_icon, vimeo_icon)
!define vimeo_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, vimeo_icon, vimeo_icon)
!define vimeo_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, vimeo_icon, vimeo_icon)
