sprite $visa [64x21/16z] {
LP09ciKW28DHtA7tl-vyWVJL-MTX4KFiN6HMIKgqL1h24537iUUnCpYJPxCWcyUVm8e40uLNMOWRWiiVSZWI3LS9wipp8S51lY96ho8XKm9xU85Kprr0FQKB
e_1wb4r0fvyb9BsUEwLEuR3DFjQnIeVNQwZedX-WsEFk7MzqnyH-44lwf4CSuRTy3m1A9OVIHeBFWBZbOiK8BmISwcyohyvsiBWg749me3l-QqvwyofIZSdq
m3XBXrrfZpIwd1dPiC9ru2Yjna6qZoHSPo8ntEGI4ZqKi1ub3mxr0vQr-Qkwyq6WBAD0VL_Q6LKIxclH7A578u66Mhptvxjpb3JqjxrRAhENRdGs8eunbeLW
GbtZ4ieT-LYyVnoOnUWziTqiVZMUWmdOrVjuGzS-ReU3lPtZI8U8sfbDjKTjNLPU-_rlygAMz7ZDGQfuzyMHcYiM2CafX5Vib1HZkkxhAeCEGRroMgOWrsus
oQhSCII9Gdxq3Mha0odcTAJ2cOgA8yb4yGS
}

EntityColoring(visa)
!define visa(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, visa, visa)
!define visa(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, visa, visa)
!define visaParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, visa, visa)
!define visaParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, visa, visa)
