sprite $visaelectron [64x29/16z] {
nPC53cCn34J7iSFf_Q-xIlvJDnKimnE4F8RfRsrGanxiNBbYBqMRLCTwlUOen3nlrVPkFnscwL3sOIMrlNP9rjOBXWWvkCZ-l1ST9hh9dUqDL6sCV4MG5Xf9
JcfRb1XxXQnDvjG4Jw_pOnjd32DurbBRN6T-CY8uP895sI8L8lhbZLyT8hW7y3jJfyDn-NOtYm0cqsaW4pSqsoWbEXo5Dg4XmxsheygiMV0e7SSXqsLZ5VPH
RZFeTfpFmzPb8EMMjEXQzJssBnAiE4SUvcqWnqHLgl2vfBC_xyBNp1gV1aH7TJMoYVd-O6nH8Ty6SkoBAahK0roSk3TBAUq8RWEWamvxO7119p05F33JzJlu
hH-AItnrY8AKbts-HWdtwFpzpdeH0ZBZdYqUoqSrUwQSXqKqf7Lrv6of1w5w_vaOyJO0zt2PIvWXkshoI-fDdHl_kc-IeisrNckjaVU9a8U-3_ekbjoJwVyH
hOKN_JAr9Oig9KbcrfDaidGEFwRthM-jglQQLujPlVUgtaVyYBuNZvfxdZ4a3VbG3mqV5lr7z5cAMfgxzqVV7tqt_o7zQ3cgZLBKMz4eqHMZDctz5m
}

EntityColoring(visaelectron)
!define visaelectron(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, visaelectron, visaelectron)
!define visaelectron(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, visaelectron, visaelectron)
!define visaelectronParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, visaelectron, visaelectron)
!define visaelectronParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, visaelectron, visaelectron)
