sprite $vivaldi_icon [64x64/16z] {
dPS7jkiW34Jf6i26_Q_s5VFoGHFoK-wfvlY2q42AKJWVOX8H3F851YAIOlJEcZqsfCNQCoQAxjvsYSt70E9fxKJkCo1kNLposy1F7M-PF86L_15mmt-mTopa
BQAgPpa5zvkrjSv7mVQbS2s_ipbY5tPJu7VtkBV3xenv0JOj360xJbiJm1CaAfyFXdbop60Dz42YnOa8Yb1t7v45WhQBu47wCu8MraUafpPlGPOdY7qgytcL
13hFpx5OrwJDlu9V2rYpl4ZroBjAOgdgnf6FO2vg_w4vm-0QztpbX9PF_QAo7iRuCPu4_pJQVUq3RaRkWr5Op63VQV_yhsyhs3S3wNy8XQwdBJSHTFJisGVK
GjkkqTjhSf8VbeK6sIZArRxPpWBbpzME_eTNlgWXsnjTP4fgP4Zvb_dOUiNgMwhqBiCoMh9KcR7uPkBQp53rJupoZzMdKWTGOwVHVY-W-Zd37jTK8lkdzYUn
tnZZBj-ryrgYWFFZ37khoBNDxDHnQXbyVWQ-tv5tBrHW_-6JMMzkTnrcXYCRpd0YV9e79_W0qZsSHu6tFr2V7zpWIUHFe-dJ1YZ3_STPxJVuyvFVuQl8yKoV
2_2StQIGJmLmXitoxYTf-d0FcioL7LDl4Si4HYEStG1hhgkViMrXu4_YXSDFFwCAxG3dMJnlVgKuv0bECKy8JVbYbLywME3YDS58Ni3HAwMmRzrCDcBryyzO
UbZxqOdAFvzHVqV3plQ5v74oQ0EvNR4aIqc4QTE7YjS5bDlddWJxv_fKLDVfNaXUmRdCV_nmiikVQOuBU9La1XwKuJFuLdlAy4LzuWIKuHFebD1_Y_RKpium
Fk675rhO3fcsmeKeWYL3Di-Z82hv6m
}

EntityColoring(vivaldi_icon)
!define vivaldi_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, vivaldi_icon, vivaldi_icon)
!define vivaldi_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, vivaldi_icon, vivaldi_icon)
!define vivaldi_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, vivaldi_icon, vivaldi_icon)
!define vivaldi_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, vivaldi_icon, vivaldi_icon)
