sprite $vivaldi [64x11/16z] {
dOy9ijmW30LRHa8Fex7lVzkCbJtvjKsplwe6XASUClW8bzA7f-HyWXIzXh9Nru2K4HeC1OGEOF0mUy_GQesKqYOmBSN3KQi7MGvxquDZjwWQ055xrmBEajiz
uMKX6jMHDNxuipmgEis__C6i2Qiqq7MC94v-Vc0lVlYspxqxhBA_VVPgt-5rbQ4B6bNvJvzPDJkBog_zXEWABgCPTVBBjzhMp-_-WChD7j-P5UqhZG7d_U87
AtxxA9-aScRfyTyuyIm2pdAjKkXrt-871m-UlPg1vGHcGgIamKYbGsUH-tvpBJxY6m
}

EntityColoring(vivaldi)
!define vivaldi(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, vivaldi, vivaldi)
!define vivaldi(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, vivaldi, vivaldi)
!define vivaldiParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, vivaldi, vivaldi)
!define vivaldiParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, vivaldi, vivaldi)
