sprite $vlang [64x63/16z] {
ZPTNiiCm30EfmkBx7_ZLTAyvm7SGOKUROiy8ttlDCKpEc7DjZwmZiwhobl2_Txhk_RUowdZ4yvxAU-P5EuzJQYQ4KQ1-R0leRpmUwZLiGp-exz0Fiw425FIN
cGgmUBxPqW22vmC0Nk7W-Rzn0f3ctxs0AFFzBaO1W33_zXfKmD_x6-ff9WEmkxUW0gkTVxly3a2UtpWip6y0nFcDm_r7JmR8ItVlyGvW5hkh0dZZxZqT01t_
vdV_8PpTvNSEXpwV5PYNyyUflwy0bZ3_fW021Bkh0SZpMG7d-G5rTfZdBwCu0ZJkAW3gVFuUhap-tfK1zFdiS3NkAWfKyz6J72x1NG40t1KT5jmL062-w72n
kpe0pzSTBdPN1-3vkiE2ku82u2w5-eAx6a12GGHWT_KF8L--xZ3FrnNW-Je0pzSTPdSPeB3FxkeAiBiw0BkhEupkwW0yNtVOJS-I7sg_0G
}

EntityColoring(vlang)
!define vlang(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, vlang, vlang)
!define vlang(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, vlang, vlang)
!define vlangParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, vlang, vlang)
!define vlangParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, vlang, vlang)
