sprite $vuetifyjs [56x64/16z] {
bTHNZiGm30HHafBZ_U-xUMTARZgm_ubdg03Rk6N5Tcnpkre_krliSawGNBFhJVdTQZUB9RthThTPxkHLqhKbkPljVidT5eRTfhYA40sBG0hSVKVmST6vvamn
H8XnriR3_nIycxwvmvbv7-P8WGW7piqEO2058WWd858WWd0AlbFWLOHBGLzmrr9EmNUAty_CE8AQ0X640oWf446v76p_TtFA4TGKUGJ3N59CltThoX7K5Dzt
FU6kmNbT4K4uW9A24SWfo1JBAX64oy2-xejoCjUNsPfokgOfbCjs1AChbosEuFU4km6R_So5kmFzAQUWSez0vPw2BcTFGE4UWc5ozWmKxY5OEBCetobOEICe
oH-2v2eWkGe8hWHMEFunAXn_KU1A8BWI2Au4WYk1u4eWk188hWI2Au7WIY2u4WYk188hWU1A8BWIUCLz0W
}

EntityColoring(vuetifyjs)
!define vuetifyjs(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, vuetifyjs, vuetifyjs)
!define vuetifyjs(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, vuetifyjs, vuetifyjs)
!define vuetifyjsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, vuetifyjs, vuetifyjs)
!define vuetifyjsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, vuetifyjs, vuetifyjs)
