sprite $vueuse [59x64/16z] {
xT47Yi0m34JHST4eiUz_tkqXSWQ3bxh5dovukCZlUFOxnvM5QNFfzzDDDzrqqqqttPGJUk2AtwKjNtIOCb0BzEXwB1Y7fz2hFjZtSnF7MQ0i3BJreVCu7XCF
MTR7pejFPKtqq5pfVJFCbuxLrG257be-r0r8TDcFf9jX1c2-TkNcCUAjJ8-TQx82uLYnS-bCa6CdxprT3ttF7jPFEP8F-Wd39mVSRdSwdxBWgj05-t6-TxX0
f-7Ew1A_Sec8cQ_7X5ZYkio0sdKvMkEgr1OiBK7J7MciOjOkpNXPBKynMI09fhe1pal5I4R6ch5QojMC7yvgcVpgAm
}

EntityColoring(vueuse)
!define vueuse(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, vueuse, vueuse)
!define vueuse(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, vueuse, vueuse)
!define vueuseParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, vueuse, vueuse)
!define vueuseParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, vueuse, vueuse)
