sprite $vultr [64x13/16z] {
bOv70iGW24MnWlAv_tL78iuovIteBv55c09MegHjDrNJYdt6BYaEbMZ2KSdKEakX3PQV4P_hvkE154iPOy368bCoKrN0u3VIuu_MRtn7eajGZrdCSnEVnksj
VxhadgEsGfP6dZ3egm_po795b8z-4hlCN3ogqciVc0lOY7wbYlx1DomCZIuO-Umo97pak_VdHL4hv1HmEXxqVtlZp-tPe8kf79yYDjxFbstGZKyQwsPh4WnJ
vcaZcY5ElVT9hT6Xgvdsg6qZvCWvn__TFm
}

EntityColoring(vultr)
!define vultr(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, vultr, vultr)
!define vultr(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, vultr, vultr)
!define vultrParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, vultr, vultr)
!define vultrParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, vultr, vultr)
