sprite $w3c [64x34/16z] {
ZLM7TXWX36CFS_3_dri_Sphqw8hQ38Zb8JcaA9BR24NXtK6fYdAG7283lhOnHiUjw24TUXWNwhxFOywHdQAdfDSINaBNGwFoDx_OTPrBCJKmpk95xpCHv0pG
1mDrobmRnVNLNQEQSIWYw9QwDuDyvJteQsgcuJBNb1srGQDv-MHgrdlEVIxzbxT84AsIcewahL-GVzPwhCMaZSWxPMK10hLVO0o6J4f_0-AS2HnMBBCONoSI
q7x-_16AGqaKehnf75b49VlWIJG4GasQgvF43ye340rzGgYZQw6X_9o1gEGJsaTL-0hlm1_k1bRGb11ClVSAtadsBx_TT8JkoD9DJKhwDYLnyylDHgjRfr1C
JGorlo5Pdbi-I1NjYzWGdKIDhNKvlpvoyScglAKJYuIf1f-_nIWNdrQbMOzMEUsMg4Lv6mWN_wng4bF11cux8o5Z1wEx0OkjmtqGiLdk4FRkTj2G-P0kZQYZ
6uaVgFmU_5M2hnXdSpliXDe_vEEfB7p8V-2dEq5WUM5O6VJoSOKUh-tDZLTGsCvkUzCh1pJN8zFzCpWzOh5yNavFTO-K1ayWQ_8ZalWG7Rzx4Ox8IU1bBQ4L
54zsojdQ748Ml2jXFWb1Qyr03ZQsiq990Fdpcb9IAZALdjYVp8U4RmuTIYmbxZ-Xx4QIGBw89oaCH_aybs4F0eJEXpDBj1QaUFxfe-ngDxy
}

EntityColoring(w3c)
!define w3c(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, w3c, w3c)
!define w3c(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, w3c, w3c)
!define w3cParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, w3c, w3c)
!define w3cParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, w3c, w3c)
