sprite $waffle [47x64/16z] {
vTQ7YWCn34LHFU__V_CMKIvhheCS65gy9LCE4prPWPIlrCrQQrrf_4oxT_s57-bKr7ibgSAFKhhtbE5mb3AjnKlAzlql-9Ecxv7wfITL1C2RThvSQp5uwOb4
ZVY6XqQsbvI-JNZRUGwtw3RVF3qSSd-RxtvXWDjp7tsutI_SfovvSockFDevkZRE6zi7kYtRji7ADxrzwws8mqYjVuTe7LWVQFnhZiPBCPqNpRAexMDQ6iaG
YDwtQHy2ypu4hYioOcZnCi1ezSmtsSyUaW6NZ_QPWqWPuU8PYvfu8jJ43pa-SUu-vTnz2ZvPx_6rCkUTuZbUbRhYzGbytV8yntF_pVQnftljFm
}

EntityColoring(waffle)
!define waffle(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, waffle, waffle)
!define waffle(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, waffle, waffle)
!define waffleParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, waffle, waffle)
!define waffleParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, waffle, waffle)
