sprite $wagtail [52x64/16z] {
bTO7pkmW30HWqxld_gTzDKr_Z0FVDZLhmcQ8e0ysDGR0FLbQOmlZr6b9PDm6hSWuj9noQpiZnTAgU8n4McQFjMGwMKCVsi-LHtJIUVoCAM13gdxCU3gPv8cS
CXPmSFJakCs7XZXZ1j1dGn6dyFfVkYM96JXbkiN-JoL9mcNasdehmP3EC5uuaQf0qhKe2v5QWug9J3CECspKriYYsXfPteWPnnBhh3M2be_VMMi4jMep6PBI
bHd3a6HMrbCWokVlUcjwLUvFXQYmi6drrd1HkjC-OghK6dqryAlbvABid_XnPGYBhU7AEBJ5rd1ZOSEfhHcFRB_K6XwCIrXf3JDkxCNMQBfLdpNhZu66kUf8
4jG9sS2ecV6Y77ACD--iKQEb3mC77hscO1TF7TtzOGoj6jAzrgMZXGgneNK_1du_XaaZxxUo6RD_QKKvegedmhmV0xSLenmOz2D48esyhUr-J2U1VhuTWJOq
RZbOsl8R
}

EntityColoring(wagtail)
!define wagtail(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, wagtail, wagtail)
!define wagtail(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, wagtail, wagtail)
!define wagtailParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, wagtail, wagtail)
!define wagtailParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, wagtail, wagtail)
