sprite $wakatime [64x64/16z] {
fLS7TcGX3ADNO-v_sktBGqDpNfIU6RaXz44Te5qghVLVu5QJD-ehiB5oHr1oKdQWlaMBMi9k_GXEhmY-zIiutjYwz2V87kcEkmId4c8N8c_fQMsMQYcLsb9M
rIizTq3BtanQeWuWVSzUtIAfpF26M-zrEs835HQS_DorFyfwxYBDwyvJSWESyv2c5WkipGrXcl2OeGUw901sq80k3s1nzkkgF7HMFjApp6NgL00Kv9K8Xg5T
MgeNTy1QAGlLtA7__HWTXp4zIVhCVoQ6799qFrWMzSfw_DfUT3Tfheoa3cRvc3gxJyNcj2dVrRnVzJY23ICPbKpQeKqrQUWDDCVZ5qYrJDDFfWKQ_C-dprRD
qhovcMt5R1XGqwZen2zBjndz9U4kllCL_HMd9J9AHQmF-LW_DgnRxqtRFq8x-3NZ_704zK_aXcQ9_RUJVDFraLb6tKVleJzXspgSsJGuWPsl8p2yUzhfqRO7
DmOuPgUKvsRNbyR-CHq62D3w-HmAYkJsjPRVZKfW03A4gMW7xYy3pUlQlbo0xxDfHBc1VzftnM6GZ9yxQYPrw41UFIsdZ_2cMyRqU7WAGZfkUO804ZgkjyLp
rHcUzvbYbnp0T3uQNe4pldxT3TOzNHyt5Uq9tl5PfAO-WukVtg5TPdpPhitL_e5MKmmXfa901ZhEG0Wotxg0bACjkVPcyqrXEZsJcuT0oxLpjp8UDnMyrOYW
G-KrTJHA3kqJZHXCEPp8Fm4
}

EntityColoring(wakatime)
!define wakatime(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, wakatime, wakatime)
!define wakatime(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, wakatime, wakatime)
!define wakatimeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, wakatime, wakatime)
!define wakatimeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, wakatime, wakatime)
