sprite $watchman [64x64/16z] {
dPS7Ukim38D3IJG9tl--RnXVeJIECeGts_g7kSp8juMi-P4909dXtMxVo4O0G5M1Vm7fxLEw1t124h_EyKaK8mLVBVoTGqyKbYfWlCpx4BrqYBR4MmfVgvOX
3DBl3OwdkB_7bSCJdAb_fehTkyjWBtVfeGRjMxpWTxYbyCyDsdtjlbUby8x2XfG1ez_EO62jgdhN0zv-Fu2EXT9xCslT4wXr02tnJD5_RQId2WxFayX8Mn-3
gxF5StnXCEOI1MBCAbznPmakAyQPeIU0FFtYYWypnAE1Smy2N9SZQQaG9kxe7JIO5UuSwBbipQVh0mvtja4FS3RkGTBjYFxZ4AOSX5SSa05u4PCvJXh033qP
sSGBbLcycb-78katEpGcTZCKs1ONVfBaQI2Raszt6viyY-18qsL0GGOpFl8IUMKg_BhK3zIILu6kE8Da6zUyzfxTWx-dyTtz6UQSjwo93pPgpHVpRpGGhuwm
-sjUzTTb5NTudJzfIMG-zQx-iq7JeE32DRuMl8GE76I__zaqgEp2ASrOygbtuo0NGh79e70ODBHg48ynTD1ZeE9EWm7qMmgdU2F6a_s7FeofJyLfOBVEIAxh
YmvvqkswPxas5fzVqRW0yrn_7Ddb-kouICl7R9uAFrxVbBTvdCtr9wX6-whmtbhtm4fCt_56zVeGPBkVtrs79sdl21MrStlRFNuH7zl7FqM_VG9JxJTBK6aY
PR1rU9GiK9_YINph1Cy5iVy2KZZUlW3jlu4vNZbKSP6zK3kM3gL3uLi7r1Kc_VdhSvNOqXhyLDOzKhVEew_Wlm
}

EntityColoring(watchman)
!define watchman(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, watchman, watchman)
!define watchman(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, watchman, watchman)
!define watchmanParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, watchman, watchman)
!define watchmanParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, watchman, watchman)
