sprite $web3js [64x60/16z] {
fPJRkhCW34HD9i3xF_5_m7PjbCEdxBbfAwmucL0Eppf-8Skb9D_dK_cljCsNgbXxTBSbdnQiKZuLDkNF5REUJhcWd7p2rszUIjYLZfD6EHPytQjcIVcBPMoa
AU-bYW8EhV-kL4Xwp8lbI-F4baX1DkAZBjuR9p8Z2ceE-BXRxx9WeUFfthgq7PelQSRJQR8kYoJtH84Pdw-3k6SXMbZm349T5iuaLxpnyaaMw_VdI_2vouA2
2vwpa7sS1MQ7FB9ZaWN3Ml78q-XVg2SyHveia5MivwUuznTetQsUjnzS4IdJU2l_LCqzx_Bl9iK_fR3X3OuwNZg9YWlwgZpdA_JXCTDtWDAA1rWKi1t-C3B8
TbXXVYvrl4dU1o52Y0HVApGydZI8qkNj5Ocr6w-emaChk_C8tXGVoLT1fWdly35gWXOSxoDUcbQ8vlKc7_Bohmq9iBrlWb79-lvbTIcgZfK6vuT79ZtY_SwJ
l4iB7hU3yqFSMlDmy7mzPLhHnAq881U3Uw2JZ8O_94R_j01yyqZ-Y3VrvrsAnnOuAUtkxj5IBjtjEf4yhU0tLovwUYFtIp1wpPCQj-jBFZ2zOw1jMzhX6Ntb
uoNFQP2PuZtFw4CA-2qB0RzR0Nwt2VBVhI0xTcNdKVeB
}

EntityColoring(web3js)
!define web3js(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, web3js, web3js)
!define web3js(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, web3js, web3js)
!define web3jsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, web3js, web3js)
!define web3jsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, web3js, web3js)
