sprite $web_dev [64x12/16z] {
fP85ckHG28GBBKZt_S-xWMHzVFu8Ns5Fyo2-mt4S9NWJu-iAF1kquIsyNbT072U1Fv2Vdq1KjsBC82fJlswvSsqQ4BzXG3g0CgigOlwz2TwdlXo9ydioqcS3
_sk6rlDfEwJSriGa6gHu6P_QySActdxNIqi6DMXDiccrJQyF_jEDLcsvDy3m1upIo79jKrNvltxTo8o4x06ecfaxBhmBsYte0CBk-Qlhp_axa3OfYfaxnJEJ
ZmUnx6ABmEwVMB6QY9BLXFMu0TRUdvJ8ate-wyyJt9_goikCbZMh5wF3mmTIy6b-
}

EntityColoring(web_dev)
!define web_dev(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, web_dev, web_dev)
!define web_dev(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, web_dev, web_dev)
!define web_devParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, web_dev, web_dev)
!define web_devParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, web_dev, web_dev)
