sprite $webassembly [64x64/16z] {
xLTPciOW21i11Uz_uT595V-bpBwR9xuMZ4ctj9v07owGwojXb_FbrVFfOjxgQv7NSQwEjsn0w-kXwKtkEPGmdKfz8rI8kDGVZesDZOsD3IsbeB9McHyyYWuD
vcbcZTmgyYXYdabI42QadPUdYcUdZfLAd0P62tjyqB4JmUA0XB49hEgnYKT1npnPb5gWjKmceqlviG0-JZEOZZ4QIufAd6SoJXjDgtMLhyFDA7SoID5VyohV
XiB8GC9U5OEC_gc3epWwt6hSgPVI-VoAY5_EsC0soiPzAmP1haF3Mn1jdJJtCbbPvUkun1eQA3gjDl6nWvQ3AuW-ph2wK_CYF-KEZcz1QdrTERpavF9V5kZ5
7n9UuZE_z8UYU0CutRK5_DoVoz2yobSWXrSGJCcVE89yvtpc2hBlZoxabxL3uZ-Vx4lf3MKe0AhLbvhopIqA1MZ3LMcZyCDMlnyRZm
}

EntityColoring(webassembly)
!define webassembly(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, webassembly, webassembly)
!define webassembly(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, webassembly, webassembly)
!define webassemblyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, webassembly, webassembly)
!define webassemblyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, webassembly, webassembly)
