sprite $webcomponents [64x52/16z] {
bTPRekGW20HG1F8Ikjt_RcS-OuNgUCy6I0f4PU83V3ewv8SO89vKg7s0Z8SyXMcVCVj6nOKuo_8ekzJqY-55RPTI9-6XZ2O5fr-FiknXql1GXYtrZifBKAFX
hVNmUWqlxpf4Q0ESFZjwt7NzFVY1ltVskyjbiWs00MynEq-N6npyIq3hUHF_tHCuiFLDa0VQ-U3lydGc3f6otgKKD98i0X_0fR87ydhmkvHQpt8Hx1YUIiqZ
CS9gQHrIu16UU6u4O8GvHVZetIRS7XqZp6BmkRRrsKKE3gFdDVlJzwkPprIEzVoQEJ0HMU-VEMh5sV_gSdajTqzVBazsdvFm72WxlulXqTs_BuR7zzToUFKA
ED_Ac_lFkzTUmZDj2_S7hwyoqm7sDiFwaD1pZRZDIEze3ozpplJz_R2PKxRmVWbpGFwUzN0tNhxIdn5woHRVZwSjXSUFWTjAUVwCw4R28xQL24su6BCavHdx
V6UxFSZa7m
}

EntityColoring(webcomponents)
!define webcomponents(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, webcomponents, webcomponents)
!define webcomponents(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, webcomponents, webcomponents)
!define webcomponentsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, webcomponents, webcomponents)
!define webcomponentsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, webcomponents, webcomponents)
