sprite $webdriverio [64x34/16z] {
xT1NWjmm30JH0j0DyFuNTf3e7CKVXzqtUQHYuiVo4faSYIHZln-8hfncfZISS8M57397QikpUhHvyY3tm3QgnpcUjcuZYaSYQzPxyzwQogUzTAKL4JdIQQ_A
hFD-TSc7_RhC-xVdVOz7LglS6ay7J-HCJxsJqShnpBC-PCsCssvvP3ti2w9NHOIcWoYUwqcWnXn9Tm5g9GUgtGBSxkIvb9NxC_XBlHBG0PabAN59q984aXme
1A1eIPJafERM3T453WM08Gi3AHI4yVuP0gW0uplkfQHIO3xsbLU0F_PvJV15tpCzQpg4KMHXIz1oS_SAsGhC_OoHalrVJ_TQgt6AACMd-SCVvqyL69ILxFcp
1Ew-vwSwm6Rt0ku-Z08b1cpOVQ32q-lQFx7OlQMaIqwcIdj8Xu4MxFDFSDIioxm5
}

EntityColoring(webdriverio)
!define webdriverio(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, webdriverio, webdriverio)
!define webdriverio(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, webdriverio, webdriverio)
!define webdriverioParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, webdriverio, webdriverio)
!define webdriverioParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, webdriverio, webdriverio)
