sprite $webix_icon [64x53/16z] {
VPPPklCW34F975k0zx_QV_1t6zq6u_Eg7bLqv2Wf-vtdcnvft71c-IggUnAt3XofBj1j5Y_D6g3xD1TLqMd1KiqgCCzlLHK1T0rpc7M01P7kFdG9SZMp1YTy
Wal_0qV60Z7p-Sm7dJw6j_cs_m2pWbFf1mMN6UTx_brmwCl7zTLkJWMvGrqH5Hncd1_akz8dvnF_w1rnmIwXZ-CdxiRv69zWKurzx1vt2tm-mIg1puArMJIV
-IqozNLR7jqQHhRbbiI7LZFE3n1dwdVgd9yLp7JEpmj6dVFpWj5lzXlCK746l_PXVbv0Nrsdp_bf0O7hFPZFZMc1wy6xHpylQDtX_CHd0VtwyZ7uUG7eVyq7
zQHWE43Zm_9tONA0ElV9z03vV39z1_BvPFOEvFE9qXVGDv0SFUNZA_t6_4QAb5C-y0MeZxwLAzMNmW8Cll-WpnOy__kNE3n0__gzN-82NWkMwtM0HjrpGSps
t4I-3r1V_uUh8cBdFUnMuG4Q_owpWgEG3KvtwgCp7mlECZwWqR-P3GMi9pi0r6U-b7Uk8Amdn-S0DRvl7Gh2UdBw0TnNwcC1wrzSVe0slO-UoizDo0tyzwSN
wiiBc0S5hLSm7WfolInIE_OeuS8qNxGU9Si5QLwsiwIiR_ql
}

EntityColoring(webix_icon)
!define webix_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, webix_icon, webix_icon)
!define webix_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, webix_icon, webix_icon)
!define webix_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, webix_icon, webix_icon)
!define webix_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, webix_icon, webix_icon)
