sprite $webplatform [64x64/16z] {
xTRNOgKm38HX2LV9lF_pxl6OP1bjmMVBNVuqttm3fCliIBdaVCXcHwcjbYHNcdD1UmlwqgYcjGQzFN10evhd7FZsW8AZTGUBVpx2aoyBli97FG2JYXm5fvsx
BogQSChfEyBKmmraS1mnK65Kq8OlqwYWYgsRIMkBuc3gROjytlGQ_I4ptVK9Hwtmrm3udiS0E3nKJj1xljMQ2qxmr9P7_zT_-I-lkPdred_eopZHQ7_a6p0o
VSSpHwxl-dfIfjl-_kmj7TUfwpk-TA0ypmS6lEcc1xTfxFOemvhk-jAxJrC59NZtfZiUVFbsz-RUDdpHoTVzkw3suRrfUVIre_Fp1WgEFhtt-kHRN_bIjTg9
_Eh1Dx-ydPIRetC47_doSM3urOW3aSCZZtpvCC0SdWQ8mvzEdZZvxf73ym1pzjsPmuS1uj5t1sVF0yJXAGSdZppuwZ_tfLZqF12vCnV9nZuCB6utpnm3v7aW
SYUEYf7dWSYTEG_0yq3apfm7u7aWSYVE0_2KjTBzbLat8pyv3P0VFjQfLvyL5Ss68_CuCA2RYXOSlRkxLPcj0UPn0AZ9BC_piEbLKF_msFlf0CmXoESMlAoQ
mJFd0NXPTVXuVU9nWAvlU9RfYymIjfZ7WTlp9snbeBpuF1AF5Pz-L1N9cEhQeQpr9uugrEdcE8mqBmleg8bi3Lmr_kamyFs1BlG3RaKsAdE0_Y_JQdZqGxOw
sfYw9tdr3G
}

EntityColoring(webplatform)
!define webplatform(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, webplatform, webplatform)
!define webplatform(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, webplatform, webplatform)
!define webplatformParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, webplatform, webplatform)
!define webplatformParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, webplatform, webplatform)
