sprite $webrtc [64x62/16z] {
nTO7bjmW381X5OGacDdx7pU4UAA7kqEI_L_TyWbDjU4u4Yij4u8_YAs-bggdfngxZfoV7LvUgweyuUtmYG7K-Cm0V-rMwHxFhuFy5iTwv2lVyV8wp2OUVLy0
PzPlyOL513xpScn9r7xcxnElI2t4hLPVgk-lWmcrLkCb6lVExk7VNxiJwkAN48ARH-NTsWweFUM81XwzVxN7Q-QT0UfHJYnBQQV0CK0yOhW8DmF8WWjSHiC0
1CWU4LotMW1jnZCcd_AKvppRfFTP_ytxwwJFavxdF85DUGIPyl7jSTEZZCS3y3ElEHrzWPHRNbLY-rxsNgqtlUROlYVM-Msl4hp7wkM9ryG4G_BCAyBAgxdV
z6QRRsgAeUUHjqfnXQ7KFL_xrFJEUoLtdw-z-LBQyIfqYf7KF-MTPxMLiwoCk7roZtHy-g8qwbAhbwL3ZnhXIjTWnpx70uXVfgRlUGYVVkkiPru6B_g95gsj
Cy-3vrZ_erlM_IwtiCC3aD2jSdFzM82QZlpG8-ml83fKRXuVB-6ObLsli8ttlF0UDuITE6yvm6P0yQFl2PHHvnItrZkF_Me5-HoJpBqiPxiId4MIbmUEmrph
tcIjVm
}

EntityColoring(webrtc)
!define webrtc(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, webrtc, webrtc)
!define webrtc(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, webrtc, webrtc)
!define webrtcParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, webrtc, webrtc)
!define webrtcParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, webrtc, webrtc)
