sprite $webstorm [64x64/16z] {
fTS7ck8m38RXNrs14Ev_sxNrX80X6Sg-MwP-jX4T0r8bx69fc8a8XzYy4On8XS1w9oh2U4RYA-EXzaQV2M70_TSYYhlIGntXfYy43yGgthZBLbU-Wp3iCMeD
GzpZC5VUjevTNdNbjaCLnU9lRWUKF-hjaABJltVNOyPesF_AcGv9EXewxZE4PGyp4-UKXEQXNwvFbdr6p35bwZZ0l7wezTxo33JwIszJTWn0VkWbIqsGF-oN
-tIyN_X20FbZRwfQlsYgb_fTxP_CnaIaqrBzAMyKmD0hW5FxE0F8lYi0MYQiU1hxUEud0Du-9W3jlmh0Pcnux9C1U-ml0AHzbDgt7H_0oG58fX4mF_KEo30_
1d2fPLguVYcrLblSyzf5tW4yz57TXCxNumXguutxb2i3QEZFrHawheiVDLJoyxBrSiyRV-mN0hZ_Hm1c1t1kgnJIqzgpJ_Tyx6lh2K00YFMI9rPogLuqfos7
3NrlwJOr07PjPYCKNgeNdshsHOR-WY9NHrdFl9o3qKnznj8Fu5ZnrXT15pN9kZ8tKREjNcpBGMCVwCurIK3wtXmr-tdhLOMn6VlQbrgWQDOx1STvFijs_l49
p8T-kKqjqSnr7zZGilMC6ujigj-kmVMuLBTtHhTDCvwUGMNiJqHKKnCYltRB9EXqljvxPQnuwEjXz-KnPvdFvrhqtYjM55ckdzbwnkh7NWae_crlPHkX_TQR
4eh4LtsghGI5l-pDnWFGhxqfol_s_bklz7W5JFrcbgC_UyQDtFePe-Mu5zpnbxtNqUyegc_EW_de_8pHrdyY1S_ycrxnmhxf1I_qF_VdR4w3QKTeHtX1-Ihy
MJ2EHEumVHIPX2EUEq9f8oqF7BBSvKpSa7ZMC-uXYTmpXH8JMwiRnJ5YjTXP88qrfYoCTqZK8mTJ_Is4Zn2BULGx27o3M7HyNsaelwnI1ByYxeimNlq3
}

EntityColoring(webstorm)
!define webstorm(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, webstorm, webstorm)
!define webstorm(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, webstorm, webstorm)
!define webstormParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, webstorm, webstorm)
!define webstormParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, webstorm, webstorm)
