sprite $webtask [64x64/16z] {
xSsr5K9H50LHhcFzrqi6pu3lUYRVQnu72Q7dW5B-k7Vhs_vkdV986kJzqoOzFBnAcYPP9o-NDE9tfEVoyF3KtokbSN_FQGjxU7ZwrdVlIQRVyc_-4Ttohzvx
jBw7Xty1
}

EntityColoring(webtask)
!define webtask(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, webtask, webtask)
!define webtask(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, webtask, webtask)
!define webtaskParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, webtask, webtask)
!define webtaskParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, webtask, webtask)
