sprite $webtorrent [56x64/16z] {
hTO5RiGm54NH2Hg-lV_b3kIf8VtSWFe4nQFwbkBNuPeXjA_xwsDASMnkgYvysNTnkAFQSLAItHMXC2apmOkPlLGktsN9EPF2fEohLhA_5cPbdcNCLDXEQNwc
7-P8PKAOipaJmloPPEWkXFc7RI4CvT1G66P266N6q0Ku8XqsW28PWK7blphxRlswNN8vJRFLRqcsSvV-blKTq3RG79VJF2jf6Jczor-kw78wMgda4hZwrDMd
hZxg4xpfSjKSXmUrEaFNPVXock_ASTqyrncSabmnOEIA0IDN31YvOYvZfxdVINPQzXaxGJ5oFXGZvq_ilZEhjvq6BgJRi2GvUlevIaz0vscBqEOdxidJtLEw
o3Jyg5uVSNTnQWF9MJaNjIv2vdn4x_uxGEOkR3NEj7sO1fbmgUFCMGtE4VrC_pQdGIPTTJdJ88nkp106cN2dvam8etM1mZu
}

EntityColoring(webtorrent)
!define webtorrent(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, webtorrent, webtorrent)
!define webtorrent(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, webtorrent, webtorrent)
!define webtorrentParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, webtorrent, webtorrent)
!define webtorrentParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, webtorrent, webtorrent)
