sprite $weebly [64x49/16z] {
XPQ9RZGn28CNak1z_nV-ZomxddwZgFIsY6qEgRnsn5YIjCRh7cELf1fn1tELtgfv0sDAxnsI6OP19sTTu8elfeqrNXyuwWugFwdp0gsL6oD10Tq42-1_WcZC
w7AceovriDPbHxfeXmnUh05mixPxrSWSzKM_luoCqLOKgv_FZFo2OtqbT_HVdRb-DAsVLDoxLjMP7H-qlpVMRkH6cbKoQBHzRWGJgesuxtxFL7d3I4ghIgDG
sh7Ef0NM1IMuAcAJiBmR3e7K_KizRRdxT2KMkbuw5B1U3kyZV2exlv3QIXuMITT6oaH8RIMiqBW0snQOY_RjIi6_tKWtLbP20OKkbJk15TpCBC2aOVjFmtLN
igk3_MS1IxJVYeKUrTsCdwIibDDFD65_aAr3_dtwDocnku5gN81LxKGwZPW5ZEjHoAYE-TpXi6aPNGFspzkLDcequccVsum8SHEvS1xvOMciWsGTAHtbidun
IunzfXPPsLAtbGLmM2o0ziaQiCgPC9C5SDOiW9baBTX7hvX9LkQHbvbiouHzrfK0M401e5pX7mmCp9DztnuOtllkTq241leIYfojNkMZnrSFv75xw7wA1K7A
SmGy1OS0klcC084AHwURUI8Gr5tNxyzzT7SVSNJZ53_4lZTLAt7qR_Jv-Yy
}

EntityColoring(weebly)
!define weebly(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, weebly, weebly)
!define weebly(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, weebly, weebly)
!define weeblyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, weebly, weebly)
!define weeblyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, weebly, weebly)
