sprite $whalar [64x63/16z] {
fPTPakGm24GD8f_kV-BPfzKAbPDQtY_1QeAKhpjob809qiYuNY660EP_08sdGwIMxm8qdl4UWlaO67rkfg6BKCm65FV9OVRSbZ2OJq5PznxAjjw3RFOUPDpV
Q26jU_yLc2z3sjdrwAZ-tGuqtu9mi--XRFeUek--Bq3CT-6NUp3VXlmsFPZFykMYLJvLOcV-Wnsfj1fWNuVuH-OemR_3cvdnb_sJaSdsDNP2J8OvDTHWhcPE
Yhnszf6hy6V9kq_KtBMJsFOLUzpxCylSeA9Jjsa1AkD6qGMp1q2LMyzPWaVUc3hY5FJUVm7HtnVr1uRvhhzQVmOVvLVIIeGm6OBsG1SkWun_Ao_4DUWKAd03
3bgDnagOMeKLRa33M8t0zVj1fy-a2u-wvuMicN5vWITjVuH_dr0-FjlpoiOFRhepzarN1lw5TsSs7PB6V8gLEDfpzIck9i2M83Y27mZJ7-TXzIzuncrm5Bsq
4OUfLzaG-_QS6mJfrPM7toTO-cg9WhtzjUAWbTn7EAeieBptOeX3l6z-e7y2
}

EntityColoring(whalar)
!define whalar(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, whalar, whalar)
!define whalar(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, whalar, whalar)
!define whalarParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, whalar, whalar)
!define whalarParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, whalar, whalar)
