sprite $wicket [64x10/16z] {
RT85ejum30DWDNR08BtxttPj__5M27zX70uKyyAcOOfZrw07EG4Cdpu0M5_fEqyX5EYroibkaYWvI1tarq9tn-QG5zC1cyzZm91nHKIRKivTnrGHLA9lndtw
JXnmHUr-V00Oy_COBYwTsj5JfjN9OHf0D0OPu3fzaGbkNxljzWd0fty-e8-oPzJKsDPgcEprnYom68FPu0QsA4yLCASD7pRdXImrxVL0V-aoSJv-SVDgrULS
l3w-7f-l1_3wewR6Tq_9JFtwezRW0PPQnktpr_hVcSEUS7y5XU_pPt3_c7-A3mEEAF___WrWQdM_tkxKplonVunBw_6LqAfVvnVss_d1P5duUNwBhZgFxuNU
_VXzVowEtR_V7_U19z7Z14uX5RSnJhAV_3S
}

EntityColoring(wicket)
!define wicket(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, wicket, wicket)
!define wicket(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, wicket, wicket)
!define wicketParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, wicket, wicket)
!define wicketParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, wicket, wicket)
