sprite $wifi [64x48/16z] {
dTO7agCm48NXfzmIKh_xttQzNHeAso2O-IeGVviCkEAIR4D9Zbwpno-bJNdKYyDZhWn-qUhnJ1eyfO87NEEb7d0d32venbhaZNBpxtedOyNTkohzVulE7pYy
2tNe2abzjoNi_COxNM8uIar714nKtXW9NvneUPXl3cUY2W1_ctU7Sr4Jq7Wdu8eC1BweI9l3JZjQejoYM5u19Db5-BuV3orY7U2Kf02PBn5GTS3sy_UDEq6p
mDJUEODkgyAJL8z0zR1v0oVz04oapfceDjUQ3XIovse7V_QwRx-hMm2C9qst3Qzu4HjkD8T-mmcdDEeGo8GG4CXiyqk8UjeNrNRi3qUi2g3qY7OmC0wzLYEs
XVsZjqtkmEX0Krk5yRsVr47cp6FV0Idmf4VUWFxRdXx18vCPFiFfTwzY2ixx3DXHRtX9_EhtvA9lSqhnKf_tEli18CuCuz2tLU-rSmg0p4lHyz3BgeyKJWLk
pBizpzvcnDdtGxzFo0ZyeVevLFwiwMCCc8uJew1nAM6Xg8DNBbGi14q04g-rTIusJCfpMh1GPWw4ZIT6ZUwAZw8ZOHVRK7xGfItZdVCX1FycNF8EVxKiuz0x
1Ik9DmHhKV_y-NF_CJ0Y7iZAS-BmY1Fb5sq1ZxdyzVtiyJi-rwvyqT5om9L_
}

EntityColoring(wifi)
!define wifi(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, wifi, wifi)
!define wifi(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, wifi, wifi)
!define wifiParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, wifi, wifi)
!define wifiParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, wifi, wifi)
