sprite $woocommerce [64x13/16z] {
fP07ikKW30G7K1WPuxd_RLS_lugRcXnQAbYi3thy8WV-62O_dCNYLw3u2n_M2hd0c8j5cru9sBNdkdPWCf5StQOnUg2JER1g1vkno1PXYTxamaGcN3h-w967
jAGSKbmwi_Uhjuz_J0xNO60aOWuQ0luUwjP2A8OsfUhQuZvwblRqzqWoc3ZBmGaOiatlaHpjFmUWhCTzZixPfgskzkW9INNKadGgiU03xHldT30HB_dliqkr
JohqTFUUVoklh_m49XT6jzbcTuFVxp_Avp9vjJAVtO9qKtdhy_rtiQtAbhY6L_cO-Vh_WpuuZ4caZmfMHQrLNNTK5IkiX_UErP15nnyp8vcPPBBTV2S6_WLZ
uByO_lU9Vm4
}

EntityColoring(woocommerce)
!define woocommerce(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, woocommerce, woocommerce)
!define woocommerce(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, woocommerce, woocommerce)
!define woocommerceParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, woocommerce, woocommerce)
!define woocommerceParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, woocommerce, woocommerce)
