sprite $woopra [64x15/16z] {
dP653kGw34Ml7JVKnEV_l_P1Eg1TmSAPATeNfEfdl6_8KVHtNCb3rs_XViucoTnK0TPAu3xpQDLVitB5In4X-HKczqMNd2LfKnqOBbbx36A_gWpM17R8oCMj
0UI0nfOw50LfyzEx97HB3kEixmtf1gpea0l0aj26hicqP4jVW-jYHalm0KsAP1WCEKoJRz1a561x4WM6tboG9IHLQ9sb_-XiXqkLj6T55tapDpUfWAuF7RP9
Aj0xKySg2uGQMyz4Ig1qNhLklMb-mt9fmDKVmJZveGh-v9_nKW6Aj4b_ovc-8UU2j07TTC4mY1DaAXjEYIOjrbDvsRiynHQ7ImF83TkENkrv14ahJMhP9Dc6
NOjVDr0bwmbtVBx_SdbcI6e9UoIIx2IUqwbqEFB_C3-3mIsFei-wBCBE_O_uv70NVJdv-arAcxE7z7lwVm4
}

EntityColoring(woopra)
!define woopra(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, woopra, woopra)
!define woopra(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, woopra, woopra)
!define woopraParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, woopra, woopra)
!define woopraParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, woopra, woopra)
