sprite $wordpress_icon [64x64/16z] {
ZPUBUkCw28GNNM4ux_-y9-Rpe5XLsinkMuS8c1yf5__x8Ab33VuIJ4SLnhzIwNPdgjvLh9TlivkvOxOYwQMq2NThtsHtE4OvU1fmz3zxOxMHKjjBjSWoXbyz
Y7A1j1dS8TXimlBwUPGLFYGk5Bu9MgFkSDHFvF5Ks3pAsjtaF8NXOQsQVvJLWFHnI9y-euh_gi6bkqR4YlaViX85nW_sI8VxTmMs6LIt6CtVsLKYmVnz5mIG
hxhhCuEQLpNvmdnvSpotQ_ClsxDdusLu6N1SigW3itWSFrSiD9_Cd7rKabBafTj871IH4i6moFnKunx0Lf1deCiZ9ZtodmiDTvtsHWLu2339WWokJPFAH9OX
or9d4F_zt3-byNATnLePzzHoEpoL1b2lU7brl7vf5jR3RfT3JUWLxs7__JGrNnevgPzGW0I0O4PI8m0yXGC0XClQDMsfyTVz250JOAap4drhpC08km7C0u1n
bSNi5HAUlPy0P0TWe-aUYMguxTa9e15WYz4n3CR3VGBG3pjGxkaON9an3W1-01XysCAhyj3Y1C3yyin767dcUoN0vdy3Q0HcFXFc4u2iEq29wTC_vyVT8W3j
bnq0OJ_dPxQUQmcmx2U1hLXD8sQAPLWJ8ErNr0H8f9bseSCB_JZA1Y3vKRTC2iiZpc-BryyshfP-mAaGmDwVRTx4HswWMmBG_jjKnjeqNbtcOu04JW3QvrGI
eAJz65_KMCCT14ZxKMO18EqRtpgzPyoH066mqMW2pBJVBknwbRsezpTuJVlHAG5gskSxVrJ92Su5e5pg9G4WNDd3UNY5hYC38K3QNrCPSI1pdKBkS5qJQ0aW
97KaGFidkQoohi3McLC2M7fQKx5oszUWb_pGwuk002qjhQdKLnRTHr8Efl1LnIWTaPO8z5FS6EE3xJDUVhmFSqrdorJtcGKAOv_UX_l-1J0VHyhOx1E0zZlx
FQGHRt37uMsStOQZHJeDfSHYJJ7tkjjVKu6LUCh2pruWdBEs7Ruvbh0nzlISWLxnCYH8dnhPHyc-YNIyVWhh1clyTWEavTuzU-3F6j6YlFqvIuRxBFTrxME-
D7hbxattW3ihEsWzcbEw-onsmMpoyDKcwEnlILF4NUFeBusuauIoujywtt-UzJy
}

EntityColoring(wordpress_icon)
!define wordpress_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, wordpress_icon, wordpress_icon)
!define wordpress_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, wordpress_icon, wordpress_icon)
!define wordpress_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, wordpress_icon, wordpress_icon)
!define wordpress_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, wordpress_icon, wordpress_icon)
