sprite $wordpress [64x15/16z] {
dP95ecX924C3906A_Q_tonkrpEufLnG0I8aiV2F9tXrJtvxBzyEMy07wtVjJhn7yy3oZtcRu331AZ0XGWNzJjWh_HqBU6RuNgS8OCbJ82iGVW9yEs_aOaK14
9b0Po0fjuTr3tebDS303mIepnXPws8KMnbvDUDbXcTLilORl0dkU9c9BGzO0iPYgWOnSz7YY1Yzhgz2TmQtKFkGjuTEPG6zuKmrWisSICk95Tm3rLgXr8VeH
UiE-mkj5FfqAuA8MkO4QZAQWXWPZ05ptpt4A72PUwHhgAtYM0GGH0ifoPAkQRYbgEX6UQdliibri6UmVumVvn4_fsuoxYzBN1AxQdIe6FX7KNmfV-0q
}

EntityColoring(wordpress)
!define wordpress(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, wordpress, wordpress)
!define wordpress(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, wordpress, wordpress)
!define wordpressParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, wordpress, wordpress)
!define wordpressParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, wordpress, wordpress)
