sprite $wufoo [64x64/16z] {
fTU9ShCm30HWTFF-B_oVTjU2XReJpTLn-ed5iP9mF9MQPrPLPOQh73yfiSZgbRxTGe5RXxGTRGGZn7TQeMbzay4RfnMoVV7z2FpEpr5rAN_DtYtj4OnppLi4
vz2ydXjO4iqRP5XSzq0tUTg_IR2gijNdZZvblTbKSD_YTSoAV_T1qj_oXkaHt9U_ftUJqVx1vtZTACzbTwu-svkOu6bAl1AF05gZGlzbW-y1i29JE3RJTRuu
V2pUBluS_k-A90x3UhVjW5NpEaxoFsVNYLJYxS77Y5zokHWyrWBTPeESUtc_MslUL-yOHTKg7a2FQm0dteqCj1FlYm_uY7bubW1ITo-BpnCRa8Etzpimh5YZ
leRlG8YNehw6xm4IXnrhXhra_jHsXkPVM7ltVM9gUZSiCf_mQm2hwUl6vQI-1uYlRRy5KEvx0Fdo-UgZM01KpgueMtnwqG3mzww-Ucq-YMUZWFaHU1gWxbrZ
yNea2V0-oxbuEVmz0BesZwcNX2S12bs9DtmPa03uD8_USl8SN-RF0NIiIlU8Jm8GtmBWyig-_RFx7a3Kib_-FO1D7tzfL1kT-O_s7C3FMOM_SFbHqHieypUU
s5F98cCevb5Fl7_dMhK69XO9Iha__FmaZF4uUWLjm3LkdZUeLzqvRr1KSzxtWFVOUuInh9toZnw0qZvv04javoMl7K89sUsGeHyy0OSX-KQfeqUcwnF-3G
}

EntityColoring(wufoo)
!define wufoo(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, wufoo, wufoo)
!define wufoo(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, wufoo, wufoo)
!define wufooParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, wufoo, wufoo)
!define wufooParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, wufoo, wufoo)
