sprite $xampp [64x64/16z] {
xPU7SiD024I1PVN_VvoUd6u7pCJfvKqrlaLKQSxC8dbS0JFidZokXZx89sXnl0dmRNho-5NyauW8w4eGuMO-hGfXpmHFvZ2nrwITGMtkDmQs4o8V7C2KMFBP
GLfva5xOMUZToeEm0dIFLq0JkW32dd0a_EL7dbmnBrJWHS7Ts_P4IciMbCXCmDuZx_GkwKZ0sUbpq7FGQ_ogryUqzKEfXynezFsB9CbDxz1JcER7mOLaMM-0
sxpaSM41SjWl7Hy5eto5cCEV3UchUqfkhHeYu52QbcppTzE_yen4oNR-zEGkO9SaguEzFgRzHQD_m_w-IP-lst-Q4BlRkFp-vDhcRQnG3Pa6lBs_Lo0UuLgE
-VjHVvQy6Mt56xzPwDcSWrbJp343r87vKOFcAnigxqYlauHuxO6lz--n85pCBKm0oSAUAUQlvn--KPzlazFVfW_3cw9_u_rvkb7CbvLR
}

EntityColoring(xampp)
!define xampp(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, xampp, xampp)
!define xampp(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, xampp, xampp)
!define xamppParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, xampp, xampp)
!define xamppParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, xampp, xampp)
