sprite $xplenty [64x64/16z] {
dLUBegmW20nK5Ed_l_TkEhtZP7VEitHW66HtcnnGaABLRBQgHI9DNy2YF-O1PYeyoeuAxXccQKH5gc3R3rLLQxNrJXLwomssrHmPcudZLazDVx6f6FBmRIbf
NrFVXr3xZk0i8thqAhSJcqDAaaKanK2urI9OVgJdjYR8bV89wmc8JKBnwBKbfoZvZiHjJH7WYLwevMviBm9sFjHkxIPBzj6iaoN0sOE0c4Zk8n42M3esTscS
Dd_o2ze9p8lJOUUNnJe2VIH0wVc0Q0W7-di0ggtLm7eHyX1aJScxzmhdXn1HGKPwd6d9WrYcYxe0I56lUBy2MGLeDuyaZoD004qJ__vMFxqleBIocuxV9JaR
7LdSpspfyfShJoZd9oJuJWJvucwBNW5vCMvHaLtvD7d6Sc-SI7SXk0V5MOlTUIsjV5TaG_8DgDgxc9mkDv0ynzPbR7txqZwWxWcOx_R7U1XqGBm6p3ZySimQ
10vjO7S4vXCVMLbWdbS1-FVyo4f96CoBXNBH3__ITXi0VKE0EfApV_hZqyxdoKD2Hm9iGlzmViAktW59Fmz85J10EB-yg_SG-6W5NiAq3G4CXFet16HgeyTe
0CeRGkg5TkaO08Rw4P0qfTgi4xmNmfuXX2KLb0SK4DCq3iBf4tI1SMySu25EcJuZ6MXa2FGzVNSi_uy0mU2k0k8tEXlIBn1hGpGEZ8vpDQZU-FpnAt_ptf9p
unt1RdhpZ02ZTAMx8IQZukVAqnduN4plrXa-F3u6gE6bxpeZ-nruEA2tvBFoNwicJWHAjQqN-ki1g6a83ygbslpM9PB3uzlfOLQnKFZ5eB8zFbOjMIGNtHyW
DGoCLiRsAwoyis5KkOOmqyJJE2YAresiENhaVm
}

EntityColoring(xplenty)
!define xplenty(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, xplenty, xplenty)
!define xplenty(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, xplenty, xplenty)
!define xplentyParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, xplenty, xplenty)
!define xplentyParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, xplenty, xplenty)
