sprite $xwiki_icon [64x64/16z] {
dLTPeeGW36DfMShzp_jchuF62SzyQeD0OfVm4wcK7AuZbbfBlCvF3tvQ2zKYSOqVfUZ-eTWTFQtmKt_4ohoa3JCRFN9-xCzGcnwhFJ5QfFncBoZWcrN6hv_8
CXyVF4Ryue4oxsgyJs3wYw_sYMlxM_45v9mlJZzAvQyid_7p5hEduvTnuYUqHxYvwESjHS4H9-tGvVW2EKzN33I2ujJZomfUdiSKlBOhXn6n3Vniu1yXDg32
4nimuOaDcF341anuQWCYFBK14PxRW0ZFRK24fpOWmZCRc17XcGsey4asH603a1Mp8mLjVKEBEniWuRLyuKLto6G3A7mi4vRuvPoVshP2AxEDyV7pDptV5zm0
VYDq_O10zSlXFqYT-EU2VxdzKQgViW44IVM5_luarOEY081JFImA63ZLuwAmdhznKS30gHuloeLNqXimuKbHOCBJte0Bpti3NkCz9s8Ri1hVXcy5se0Bxv83
6r3Xi_E93P3mpiSsuC8xd_VF6QdhVDw_AnBU-Nn-K3yMuxiDz71zJWTyCZ_v_CRuFh_fSTJJ65Ru8UhgK9h77JbSHhH1CWvDfYpdtW
}

EntityColoring(xwiki_icon)
!define xwiki_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, xwiki_icon, xwiki_icon)
!define xwiki_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, xwiki_icon, xwiki_icon)
!define xwiki_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, xwiki_icon, xwiki_icon)
!define xwiki_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, xwiki_icon, xwiki_icon)
