sprite $yahoo [64x18/16z] {
fL87eYKX24D54F7-vrq3qxRzCZ-lXHB3OwH_elXQGf-0rrh-0_tOUdslhskZljVBbW_IZOZmMtMQiAf0hzscX97O79rEQad9jxwHxc_EOKP32l1oia74oQrS
T6vA3992os6ocWqNhULaHfbD0Td-xSSM2uOnGQMFK--25bPCqIU6JHhPy7NCqN0EldZ4G3GElKOFbEDOQ5AAchYx4h2pqt0JBClzq0kL1H4OHV51gRO2z-m7
5CPUevpwzBVukms9g505tR6b_jnAZOCS9ayz2sAB3b0tjBSPZWazLufauEb_PPNAJHshV5v41ecwOx7hrbTB3KQzA3mR7O0Y6OlKmjoeCLSYPev79Deh0JTb
mK_cmkmzyWQzHirLlCGl
}

EntityColoring(yahoo)
!define yahoo(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, yahoo, yahoo)
!define yahoo(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, yahoo, yahoo)
!define yahooParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, yahoo, yahoo)
!define yahooParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, yahoo, yahoo)
