sprite $yaml [64x22/16z] {
bPG5aiGm30HbfhFy_zSkZ7CbApgStN3QrHDg_4gcAsEzKZ0VxJsVOQSlRANtd1r9t7plyOJWS8yujnKi4Y5pyyxmXBF77elVHyCy-NroMPltbYTueW4aKrqd
lpe6jhnjaCLUU3GeI_7eP1g8lURP4Ij-1azVD11xpQzUbkOfsWQ8s0il4Tv5qm3Pzbo5hvz3Lpvu2i4q4FkSXC_n4dFhv6q3iHzqyjGXvZIl6kWdXprbuSi-
bCWh_jwW7_Qa-RTD9yEh1lcql_FKsHbU6XXxm_j8XfS6njxmYEKfVct_E-yTufEr_vsNC0TZ_oklyg6_EOF-nUEmD_QadZ_DktLB63YtGI9SgVBzRE5A0f_k
_7m2
}

EntityColoring(yaml)
!define yaml(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, yaml, yaml)
!define yaml(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, yaml, yaml)
!define yamlParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, yaml, yaml)
!define yamlParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, yaml, yaml)
