sprite $yandex_ru [64x25/16z] {
fTC7aWGX20LGCBM2ykz_sosasjcSvkzEKbwraOYe3b7LGVyBTrKH-RVlAeMf_jSNrKBqVz-rqnEUHTipFecMNtZcpnlVUXP9H4K6ny9uU0_IeEayHVGYehPW
Mbcq7f-0J7G1oVlXyQyyOS3qnSBQ7SMhl77GqFxHy_Opz-qxB6L3fV0Biak5qs2ggkKBhrItDrn40WaVRGF6j3DKAd_YhzjdHEiAl-03DWX5U9pp-yPtIFZu
NVs17RF1U5TUTETIFNwjQU45FVm0XiZqhnrcQ4JUKO_t9MpXTy9FjF22dV30zh47aQgIplmhynNUa6zlfNfy_4jW_CQp7uVZo-vZ_svqZzyeuZvctXxZRohf
4zymmiTvEZvshW3zN82BFl6A7DvhhuVtea5iMFVYI_h4PwYFpJqjM7vuafXK321htD_srXU3hRKCMCK70DKrmtkLKF8kdJP4s7sLuokC6qugKJN0KHn2VtQc
F7SRCx-wuIbHl3Uiv8bhGrnRzIw-2xouHDkdQPYqu_uVQL3QMIZqNLu
}

EntityColoring(yandex_ru)
!define yandex_ru(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, yandex_ru, yandex_ru)
!define yandex_ru(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, yandex_ru, yandex_ru)
!define yandex_ruParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, yandex_ru, yandex_ru)
!define yandex_ruParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, yandex_ru, yandex_ru)
