sprite $yeoman [59x64/16z] {
bPS7beGW44G9tI1sklzjLn04PtN3dup-LsL0txYVy242G0pU_OkG2gjQHPKB_ba7KhkZM_YBw8izeFaF9jip-w-jTtk3NrtVbe2zKvx5K3a-qTwHvsCur6Zl
qBCvLA_lwlRMjfys_Awcvz1XklAknhlb_RMBVBL1R28YIt_rdrNFK7z6a-bgieZOWBzLTM4IEGVgi0XpTQy12cleXrehxujgmbFTJM5DNOYdMXPLU54XYE6Z
MjAfPkg8D9Ef4vodnPrcDZnLf1cxXfAlqsgwVWcjqqOEx1cLWqGQlxlk8DlFgFSg_k44zW5-KNVdu3RtmWGGC3-J068Dt0mUrKgC4V5uW_QMe7w3276Svi9l
HpUUhn0JrlUCOGp4qqN35nNw1sAJ4YB4Qy5dR9USTtwgCSHJxPcBcWo6kU4rNqStp1L4J5lTGxWMTbvBLnDH0Tz7Grk9f45vu_vjQydTsCVKBKIqd5x3hB0C
bF4o7VR6VZzKS9Df2h5CblsgMr_phlff2XPPc2i9d-b3dUPpgl3LU5TNIQjwDvdkxkuwcxdABgAMdioCES6kCXchfLEbvKuKRcQ0UB2wxB-ht8TO1eGXn7OE
RdB9uvg8fyhhlJEalTgyfnWkOACwHWNSlV0kpCHfcGm0mnj40F2kCzN2B6hi9k69rNIvfvgPCgLVrB2gnUPnPTNuZrGMLm5HjGC97sgxh036cpfdtNeVLxYh
4L9AmxofC2unP8CIXZhi-5Yuc1_7zq8fn-3J41OIBAhGzSrMLBd0XuY523xxFjqkc6Z3cHpJ8H9B6Pr9bnssP3RrO2yvLRP23MQXw2hHyZ3NMAcgq42O1YhC
r8goUZUHOKfBdYgblOUQiZ3bUlucjm1TPRERAxix-ufPSxc0ihjHHcX7Hk4QodsuLcRHuExm21seC7DxQLiaoYh2BEW-258RsIlAegRClBblH3KMUqUalKrp
TONr9xLLMioLGFOR-Oz_KwWqP0Q3UmVbd00g8WGdIKHKzTT_AtuJFgXh4oGctW6bmWJkDyBM6p9ijG5WAu_kJs2Hgc9JSr7AmVsTcBQTM8HA1kyU-08
}

EntityColoring(yeoman)
!define yeoman(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, yeoman, yeoman)
!define yeoman(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, yeoman, yeoman)
!define yeomanParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, yeoman, yeoman)
!define yeomanParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, yeoman, yeoman)
