sprite $youtrack [64x64/16z] {
tTU7LYmX383X15BO0hp_szx9R87i6GOvj_lRbI-WReL7IA8fAKUO54XKHGYX2rdJCwLJBVgA0xoAchea33bh7pNkqi405FLHu_C1ZVi1sBWVCETgwzZ0V40u
uYgs_Mo0vxv0Zeq6H1t4agO3Z8zBym6qpYr5n-S-5r--x-NFql60I_rYlPUVyn9_pXFeJta4wdtHhNjzT5FLTDE-LBnd0D1-_mW0uS4p0a1IS6Nd1MsvTZw3
eMhPx5W_lDy_W1Mq-Pe00BET7hRkfpx28vJczz-0dn-brdBVkjXHxbQrakCMwTlVOUksdoEK-kXklhvBdbj1pU_9lXdkKuRUk8zVlWG0CCvrw1jlXLGVNM4F
oucdJzt_kWpMfGxz8MyRPZizrR4d6FbsWElOCqoydFg2tzEp-mCjUqvrl3yYDH-ExvsRBpddsbUswZl58zxyh2G8lY2wubNGSzKrhnAW5MNLkm5HTTst0IZh
lX_0kkxt9BvFttnnZVsU3H3dIy0-6lWs8AZtu8eJhqZULufzClCiti_pNd_Mwr_syfEUjNNvBD5XdI7ISGo3Ol_uVPWWZ8hoNi6hl5rfsLQ44Gzm5ZAtw-zH
4RuOoZAVFxSXM2Z8ClSXgujXjIZptUTFp2qXN64_
}

EntityColoring(youtrack)
!define youtrack(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, youtrack, youtrack)
!define youtrack(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, youtrack, youtrack)
!define youtrackParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, youtrack, youtrack)
!define youtrackParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, youtrack, youtrack)
