sprite $youtube [64x15/16z] {
bTA5bGGn30DGEMnG_-rUFClyJiFmmoXZgUsuUrvqTVnAwu9BYlbp1j1zGipaPYnyfo3ZKN39y9TiLkYeDDoYJhgTFMz--MjgLe7ESUCNzUBrR8RUV0CMwzvb
hkpCa39QghelOy3PrXJaLx6pAJBiuZkoSWjn1XUSjLFXbC45dbvpGXdKgmVAklb22wqqYH1ZRJSVwLkdblnAltbWNJsCxFselBpnfTAET_U-Bh_voP3npNkZ
Z-2j_zFzvj7e-EMpyekVzZ3-gBJltXeD8X_c__2fNiQFXs_7-C7Y_VfBxv08fK5fdZvLQFfyCH5S3D4NFx1JR07TGmkgUxS9DO76d2PBHrPIBQn2nbngvwYk
sV2V_04
}

EntityColoring(youtube)
!define youtube(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, youtube, youtube)
!define youtube(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, youtube, youtube)
!define youtubeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, youtube, youtube)
!define youtubeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, youtube, youtube)
