sprite $youtube_icon [64x45/16z] {
fTP50iD034DHEpCcwVxdBJCtVljV24hELCUOvXwPTO0Txc2l3ZB2tUPOLEwDI83WRm1Kc5xhuWgmKsxWEd781xYMoKvnDImYamqk4cmeaMG3LC2EeRtUHg-F
oJS0_Y2DRyGeVbV-jl_fmaPyw4KT_28_z3jByhFwq1-CQlG7Xbul6k0x-DOVBDde3sQjUZXTQRNwqVh-9Jh_Nnriz1Fa-dvav_hJ01kzWPyXt_O_NJCLR_ib
-Lrwx_aNaoq-m8wfhHv3gjLh-_qxsH3z_I4JZVdHtr-hVm5SpjIoGF1dGDeYTtICw_e5y1ZWj83TRTmCu2q
}

EntityColoring(youtube_icon)
!define youtube_icon(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, youtube_icon, youtube_icon)
!define youtube_icon(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, youtube_icon, youtube_icon)
!define youtube_iconParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, youtube_icon, youtube_icon)
!define youtube_iconParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, youtube_icon, youtube_icon)
