sprite $zapier [64x29/16z] {
xP47ZXqn34FLoVkVE1XEDFv8pnRKVMYopETg_qJ1tW6g4OWt-qcG_MQz6kdezZVwCmW3vgs-1G6MlHbqenXlzjqAvlOUt3wBMDmiihhoRgTPL9TlHbsrxj9J
Gd1n2mfS0R1QepBr8HjgzLKt-nfwNq0vcwvg46us1A69D6_83nALJRPya829uTWIbs9pf_msYr1AyIJZydLGKUeiO6rsf-GxcHkGdsV7UfvdT3wTQ4yZN_jc
N6Yk2HDdBn-As--xfxNb5vVrVpZza1KH-C7Fu_Ttyl6LU8sQFVu-rZc_stBysI8q_uC_QieFidxqTuEzwW--plpwV_6Zxo17QA-kslT7LqDF9N-pLOrPNyuD
_Bn_dNxRyP_0Yn-BQvHLgN8uL-qcFFQE2cphz-Z-V-VB_mO
}

EntityColoring(zapier)
!define zapier(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, zapier, zapier)
!define zapier(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, zapier, zapier)
!define zapierParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, zapier, zapier)
!define zapierParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, zapier, zapier)
