sprite $zendesk [64x12/16z] {
nP49iYqX24Eb0Lk1x7-xF-AVfrVpovtIn5CLlED32U8lqutdca_czKfe7tUzeRhVL3ZwofkxtD6akRoO9be-nWjgCv9ztEJPMMTq-2Vfod-OmqkMcxijb18F
quKz1h_K4ZOCDUq5UKcywWKbvs9XpGUysrRPaAfJA3ckEdMnc2kTavzOxHQvjrSZlp6_u-C1YWBixlkmIMKlNC5ArMbs_rf2Fb5oSUtpDLlFJtmrZyD7Xtw0
6GZow6MjSIfx6VeV_CBRjndS9eMMgN8qgiWxypc0sX7Xx87OIU87BudSXVEyK7kVme5SWNN_luJM5Mz2Tsz6QXy-5xyuIk_dcSUommB0Q2LvpVW2
}

EntityColoring(zendesk)
!define zendesk(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, zendesk, zendesk)
!define zendesk(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, zendesk, zendesk)
!define zendeskParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, zendesk, zendesk)
!define zendeskParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, zendesk, zendesk)
