sprite $zenhub [64x14/16z] {
XP87aWCn20H16MR-_zuhqEgSxQwmIasgrN_a7V_7Z_VEULQuM6zrHvTWmFMj3rxOEx-0bq-yzrlYv7oiKlMdhtBeoFJ3WLKpgW7U7tsfPg4iw-9Sm-5pXwWW
YeYH0D546aWGC_mXmIIavQlCxSmNp83gHCqKNOiH6jUj6b4KnERPfxUwTjT6z3nVkvPMm9QrDmKFJpvqco9pHpcfo56G3y6kuEg1FVihvqQUsOLlCwbr-vx-
cTy7lu6k4kHPyi6lfwrnLpz8dy4OvAfbc7xmLK7qxaJPyskBd3n05fdj7nyS3xvqC9WHUYzD_60YFS8EaN9-bAPcBVqUzzBYGOyhdnF4LFa3
}

EntityColoring(zenhub)
!define zenhub(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, zenhub, zenhub)
!define zenhub(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, zenhub, zenhub)
!define zenhubParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, zenhub, zenhub)
!define zenhubParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, zenhub, zenhub)
