sprite $zoho [64x22/16z] {
fP85WXin34N5bFJ-rws-9vaoxbiqF8j2Fq65FeAu_liBB6eHJekvcPhyW-cHTO6rXorgmj_VPFxHXdapg3uYmu0glqKHrLqxVOzyhVTp1O-ehlk58ou6Si_v
QzI-2VyKGZ6DnVi5k_4e_awFU4LUPXwVx8IlD16BzBU81k5EoJUeHq54kfepymp6rQ23LRe5n9asgVLDL5LKy6lnsADW0Wg_BEBeXW5wzzh2y8dsRZdCS__b
runYnIJm7x7XznnJKQBgPLVh2rbFXwZG1Hy_zYYhPu_XFw_m3gyGSXqc7qHHN3qpPH7yXhyM20H10pFQ4FVolNDUJnlnyUMLEXF1bm69yezVsKhIO3UZz9WE
ZT3eum6yipvwWnJn5txtxICFfncd5pLJzfsFpL6SNVvqevOhl3PJd-GyyrHO_hsFJIAVYsSlUyN24N2bmZ6IOqAl_RlwOJfnfQlX4yWIZG62QA6L6f4VfusF
TYM82C_7DwGFhWdi7uboORP22UI8xEiRwVe6yqBLrXV4nqXjzGu2xDMpNoTMj-1NfqHtdD20LpTtOemF7xTmPRenD9iMMLEpAyDjBwoafY9hBwWcCt3m0vfs
ui1KULyG_HgXpm
}

EntityColoring(zoho)
!define zoho(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, zoho, zoho)
!define zoho(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, zoho, zoho)
!define zohoParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, zoho, zoho)
!define zohoParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, zoho, zoho)
