sprite $zorin_os [64x57/16z] {
xTStbWD124LHFBt_3O-fg1qVPYHbVJFP9mUdH4US3IN84zeo295i6G6HFQQIve3ZV4-eOBdrwe-G8qT2gS0ZTFHuI8Dl7e777i-ynE7Am2j7wCJMzOp67iUF
Yo1hHVom22nhNiINQ5Ts7LyKhspdPiC4_EuKnXSZYZ_6ZrYdSRslv3QFNssfmtZ1AGPnpmgJz77ys_OsNbjtQEA0dduMWU9NSPe_0t4q7OhZ_Mm6ZFS74J4J
EX5pWvJUwF6m67AwnJcavVbt9AYI8_Anypz5zlY3_t_8in44oL-_ksy
}

EntityColoring(zorin_os)
!define zorin_os(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, zorin_os, zorin_os)
!define zorin_os(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, zorin_os, zorin_os)
!define zorin_osParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, zorin_os, zorin_os)
!define zorin_osParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, zorin_os, zorin_os)
