sprite $vertexai [64x64/16z] {
xPK5TWCn34GjtlkVk5gOWbxYPvNfj-6CClvBupVn3_EOGMeqZyy7U8IF2PAC2R5jyPQyHcWhNo4UZNo3aYyQoOoEHtTQoGip5--nufz4wDOw8gd-L-O0YT2I
xq5Kjdzx_rtAmnjTSyYKZh7ktDd_HCu1vcxm3eyT_vxWTo-Fql7FLdhJQDFQxioJF3pE_37yN_qD_R7_hlbFu1_Ur_npzM_FlVEAV-JHlmloJU2_vj5xpRzm
xGzld-4VsnsFdg1tmpz0ljBF4wrSEwaUVvxKuvPLxiIlK3d-YpTnTxcPbuHn7Yld7-H9FT7R-tw22aVyQVkJNVxDa-FvdGQeK47tnB3AvW0oB-NdQqZOZP-U
b-xp2dN_qT9zQG3yexiCiBO6KZqUfNHlLAZT-mDgzzOQq1tReLL1FS8F5Dqx5JIsBM93zoR4lWMJHw1xbqpkxeF6s_BZbLXiAXRssZp50Uht8SMM-wNyym
}

EntityColoring(vertexai)
!define vertexai(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, vertexai, vertexai)
!define vertexai(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, vertexai, vertexai)
!define vertexaiParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, vertexai, vertexai)
!define vertexaiParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, vertexai, vertexai)
