sprite $dataproc_metastore [64x64/16z] {
xTH5UiKm40HXi-V-5mvLmA2UXJgFzI_zgGIcxcurJHyHHXvVdBf-XZ6sZCNHrzILMvYYp5WSWr53TvW3ch4u9c-2fKkjnlRXrAWw-TPIk_Zl65r7Vk_43EFc
wf0Tk_mgYK5RXHUyUF2bF8E-skT3yrsDUg_djwuuKkMZc59CguVgon6OnR3y2SH6lgDjiehli8EiyL53V_Vr_q3dvmyZnshKS6hOVSgeCHWvd1fE3IE7KyEf
OUHmQb3VgQPv1m
}

EntityColoring(dataproc_metastore)
!define dataproc_metastore(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, dataproc_metastore, dataproc_metastore)
!define dataproc_metastore(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, dataproc_metastore, dataproc_metastore)
!define dataproc_metastoreParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, dataproc_metastore, dataproc_metastore)
!define dataproc_metastoreParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, dataproc_metastore, dataproc_metastore)

