sprite $gce_systems_management [64x64/16z] {
xPO7ReH040JDnlx_Ywt4QAGopJYdAwK3fdhpwfx-90-QWlOMNubly9NPx_JrvRxqdW68x9eMDeaItshee9qLHg-mZCynRm6lSzEtIe2TxWtVww_-liNFV0gc
ZSSRbhZcDoDHC-nfPoXhBWDwVfc5Nbl0bsCRAa3-oW0KrFoTVAldpsaEE8Ezu4kOmUDyclS-Ditvs6ljHujSSZ_-c2W2iUJN4pQtAXc5Atl3pnWT7QWdBBqp
W0LDmRfFwEBt8-ugT6U-y_wKMF3E13DDMh53N01PhQrSQ_qX2nEkpfyDy3FKqGZBwHFQYKMTt4tryGuVV8___V-_7pnu1W
}

EntityColoring(gce_systems_management)
!define gce_systems_management(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, gce_systems_management, gce_systems_management)
!define gce_systems_management(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, gce_systems_management, gce_systems_management)
!define gce_systems_managementParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, gce_systems_management, gce_systems_management)
!define gce_systems_managementParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, gce_systems_management, gce_systems_management)
