sprite $cloud_apis [64x64/16z] {
xTP73iCm44DH0YCCVFyBfxkN3rFf2TT-VsT9UkVz5rd78xEAHrO4ukhJvQrFbxS-NTxwTBba1bekLNXTPdlTPdgfdUKrcE4rMifRKrIpfe40SGWGtnc8wte-
3iHrUxW40U8G80u1uX0WZW7c763EWV4XLPRzz6C88AS0S0u0vm1m3W3d070Eh79U6v2zWfm3gbfnOMYqvzzVmy1hxkysyBBt2x-VE00S0y0n01m3m34070F0
CP1wv_rt1
}

EntityColoring(cloud_apis)
!define cloud_apis(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, cloud_apis, cloud_apis)
!define cloud_apis(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, cloud_apis, cloud_apis)
!define cloud_apisParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, cloud_apis, cloud_apis)
!define cloud_apisParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, cloud_apis, cloud_apis)
