sprite $data_layers [64x64/16z] {
xTH7SW0n20LHmKYW-r_O2IUgt0AdtVozwlN4yM-xTq-kIyRFfzVJz1TuJ7wEn_J7E2JqSKweSHtNquP2GeNBYFD351BE-7WxFoY1SPNnwJmdC9xEGmBZ-Jmc
C1wRPdF4887mu7rlZm1CO5pCzzFS118gtFVB719AF4O9n6Sy9QG0A4XuIa0z9oGy9II5F_c4fmJu6QI4vHldAt2SJD_7-GmSfbQTDptfPkQdVZSpBBZiPTES
x6alkn0tMtfwVhg24CIhz-Vh15blUFN-lYKiGPs_drG00V3zCiy9o-EbOxnEQE6SO8pt4X1l9Z1U9p3UJM2ydu1lVPr0U3y1y7v23-V_0U7z1CRh1C3x2O2t
9oVythr7
}

EntityColoring(data_layers)
!define data_layers(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, data_layers, data_layers)
!define data_layers(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, data_layers, data_layers)
!define data_layersParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, data_layers, data_layers)
!define data_layersParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, data_layers, data_layers)

