sprite $tensorflow_enterprise [64x64/16z] {
xTF5eSCm0C1GXRN_mX_AQ2pNEkV5pAVMQYcubEf11RMCwzPhcTvxBT17tYLhuUTUKxbUzfgdpxt6TTYxXFHer6l0c-9z1y-f9yTVlh-f7YvxXXI_XDvFtCVU
NzZ3DUzuz56qmFihzLhhkpVt_VCyjHvgFGoLdkQRJ-pOKz3UKzZQKzu28nzRg_KB
}

EntityColoring(tensorflow_enterprise)
!define tensorflow_enterprise(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, tensorflow_enterprise, tensorflow_enterprise)
!define tensorflow_enterprise(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, tensorflow_enterprise, tensorflow_enterprise)
!define tensorflow_enterpriseParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, tensorflow_enterprise, tensorflow_enterprise)
!define tensorflow_enterpriseParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, tensorflow_enterprise, tensorflow_enterprise)

