sprite $permissions [64x64/16z] {
xTL5aWH1243HnE7-1nuteei9QBU_VoMfg-mPigYf4Eo3GUozU4znpDa-Yyzafa4j-t2Oykp3iU_Lafz-WTYM3sroj6qVrFDQUMjniCe7TZpNNZfUQcyThxNt
ZhVJ-JZq-m_qTexvmzhJOUlNLokgFC-tl-NNppTmiNlQVv2_Vlw0nFkXPk-uXf7-UfUrHoZwxbq9rhu1mBh1dW4IYwgwcwaGZYXltFyc11rC_vsVZ9r5dttE
62eCRBl5JYvGdTkrpqcnuHk-E0x8YgA8Arxx-X_GfZvVHhQF3_ZcFFRv3tG_R-dpvzuFz74S__HgTLvgzxMUlG8
}

EntityColoring(permissions)
!define permissions(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, permissions, permissions)
!define permissions(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, permissions, permissions)
!define permissionsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, permissions, permissions)
!define permissionsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, permissions, permissions)
