sprite $web_security_scanner [64x64/16z] {
xPRNkZ8n24M7cdd_5_vBbCz3phBhtQmRIx9X4oBEzbqE3iBr7RbaPfYyhBUSM8KpVywGHavYYZmdyOmViIWBdeMyK8HPPffCIu7RzAg7odpQ4MZ0ClME1Tyc
EgjPq5ON1YYLp4WBKUit0lXrlIS5NNVKkrIwPzjjglEMcH1yZSadv1wq5TAB2XpHnA2_FQR4sFTzX7G34nTixi-zDiR-dp4CJe3ahG0RUp4CMj2GNClIiLyO
sZC9fUy6ikcpfr9eNN7UjNUawUsElknZ0NH9TVLlYzv0ZzT2NzDBzEFd-ajlD5vgGjuxVz13NsnSiQ_GFwehnaKUIwk4zEj8ZG7o-fK2jXgpSSBMJXlgvNTZ
rDqhPBEF12qzCUEqhJ4mk7XyCtOpXIH4v_yNncwlIzupwEn0p5tFi_l--QHHr8o4uZc02muNbcCo5vYjwKyyBeNfEbkJ1JXB9l6V1FqTD19WFICE8Nnx1b5p
3tUB5vxOUBQ-YaM6o_Pn3Wx-0W
}

EntityColoring(web_security_scanner)
!define web_security_scanner(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, web_security_scanner, web_security_scanner)
!define web_security_scanner(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, web_security_scanner, web_security_scanner)
!define web_security_scannerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, web_security_scanner, web_security_scanner)
!define web_security_scannerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, web_security_scanner, web_security_scanner)
