sprite $apigee_api_platform [64x64/16z] {
rPTRrgim24PFk3h_4Pzboj-5Er6Vovib-miH2FRV3zWFcQYPojYvXfgRoNY0BSfSwTCuycCkUtfODBkkaipZpp9zx72FgxKGRD9DGLOy5ZFWEGq2sDrLHEqg
OCMudguZvmEEy45yN1x36lxdavW2Vi6bbkE7q6_mxMtu591b-ob9WTfTk--C86DvUMCJKXx0fsi6CB3MMKt04K0_WDPPAK2y9pGDnrzhmZzuB0uzUN_ZxIWp
UWGyucVHfktsPxPjX-y5_EIL-Rl5AJ2cRtJ15W1RXW9LW9VjD4wJAvv7k9d7aLS1tIJLIw3ZVuyI5m7DoRDMce3rzVn1F-TXjhK4Y5D0TmbfBI-r5aLNHm2-
Yy2tySad3G5y5QYq1vr54gT0uUdqEQfvQvfOiwj7kD1nRpmBXslUuaysAl6yVN-5Gu2xnrF-7ADjnVMvVWIZZS7hM_tAFW8f_B5_q6dTAlYN_cq2lYaSVRi_
ke0oE-cFzzVJj1npoNY_FyiuBZbFzlStvmtcsUlyuBp1F7YVNvmtd2UqgABzzy1Z7ZEflGuOF-PftE6n23ZUty0N4N0Ah9yxKG4GJzEW0ATb7Q1NG1yJgu1j
Gl9BnmoltVajENsx6s1aTOofgESNRmAdIzHhoWocj9X4ovG0hN08tBMCWhxv0v1vzualtd5RyLgL5NyeVUfVkYdJXfYvwTZxr4mB_W7x3ViF
}

EntityColoring(apigee_api_platform)
!define apigee_api_platform(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, apigee_api_platform, apigee_api_platform)
!define apigee_api_platform(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, apigee_api_platform, apigee_api_platform)
!define apigee_api_platformParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, apigee_api_platform, apigee_api_platform)
!define apigee_api_platformParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, apigee_api_platform, apigee_api_platform)
