sprite $cloud_jobs_api [64x64/16z] {
xPO5akH030HRMFh_Y-zQYx8Z7AqTXXmqPBdC7dVA6pNVO1sTV8yqVBu3NySFSWFVJlA1wWDwh13BEhptfGFJQRxi_BV_zla_V_Qfd0XTlyAd-0dtVJ47t3ud
STDN08W804OPqF794HFa5oJxhFiCJ0rmP0HqPYxxbBhdID8Sa9cwwcTvAUk2ESEYBwdNFDXn0ThF_WDz5g1ZlyvTTsPW5bhoPRluZ8Ij-ehSNmL4ODMtB5jn
dEwVsD-FVAQw-r5rHi0EzzzsRykklenLh1m0fT4I715mghgETNGAu96GHMIV1ewie29YG4oQZvifOHAHm4O7ZHI_Kle1R40IBeER0GcnccaUcIMWpHC5mCSf
0KNlmpOkoPj_
}

EntityColoring(cloud_jobs_api)
!define cloud_jobs_api(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, cloud_jobs_api, cloud_jobs_api)
!define cloud_jobs_api(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, cloud_jobs_api, cloud_jobs_api)
!define cloud_jobs_apiParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, cloud_jobs_api, cloud_jobs_api)
!define cloud_jobs_apiParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, cloud_jobs_api, cloud_jobs_api)
