sprite $cloud_nat [64x64/16z] {
xLT7TaGX37C1nFrFd9ZfpZH_fIVQykJUa8_1FvoZ6ph5nyJGxVI6IGdec260Cu0NWCOAi6BQt58CjCBkOun-b30mPwKCTEnW2oAA-GfxtkFG7W8cW8YzevI3
K2qM_01QU509OG--7_XXkQqYgDgF7HrZdmEjna_t4B5I4UdAtr9taSD22YqPwqWfB4B1TK4uW47mMmg0QetlAOC6lnuukyxNrCKAjEkbCrok8UptC_wrmTZ7
WkiRB7ver3qyx4a-M9JDhd8l0UmIq4NJGqlMDz7C3zpYXmyidxEVZ1-PFx9-2h0hzSlr3z6_nFmWvXUCd9-r-TtrW7tsEha_RFF-qj82xUJ-3FiRiR-f-u6_
NmBcbWumvUutv-ZjY-xNJj7v-rq0Xix_NyJb4_2F5m
}

EntityColoring(cloud_nat)
!define cloud_nat(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, cloud_nat, cloud_nat)
!define cloud_nat(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, cloud_nat, cloud_nat)
!define cloud_natParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, cloud_nat, cloud_nat)
!define cloud_natParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, cloud_nat, cloud_nat)

