sprite $quantum_engine [64x64/16z] {
xTN50O0m0C107FPV67U7UfjyqCCbaXsbNSFORbIbnnUlU-VnKP_zFktRBDtxpPQgFlosztunU1llFy_lqlCQ-BJl_VUtwiDxyVzS_DlmjoqFHxKRlMNF7Yyx
QW
}

EntityColoring(quantum_engine)
!define quantum_engine(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, quantum_engine, quantum_engine)
!define quantum_engine(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, quantum_engine, quantum_engine)
!define quantum_engineParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, quantum_engine, quantum_engine)
!define quantum_engineParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, quantum_engine, quantum_engine)

