sprite $git [64x27/16z] {
ZPC9ji8W34K3cPZozx_SRsWvmLPFVSx3lS0pmXOKXATmgmIVGwMK9m4Eiv6_uSy2iLTeckXTaxJy820xry_35BPao3y9T7IPFTWRJyg_x23IJZxEpf0oVnIa
dDFQfWSIlN1h8fAtwhmMkGkeUUUZly9UlmqKM-702yVJJQ0MKJ9Fy8E2APhWNYBQAqLzlrKGU3YViFXhH4oEhmZWJL3EJLQpUlPcUCo1hhC7BmnPTHSqi-7b
iJ_U-Oa7psS98QZdlEWNlbnuBm7qUBK6jj5ihCC7NYvyoMkK6JofsmhV-104hpbBB0-GJy4GkF4NWRmzZtzS5LLESEKhN0GCTCEzTq7C9vwSPu0vIBtrlGFP
dwwiuu_H1426JH3IyUIlGmXY5WE7Qf4AOWUV05tipX1esdwvbJmiWWcFp4_czC8kaC2tzGM9HTr3y2stvcFvaPR841u4WGTlZOcuh05y40H-wsyWF0W2ZqWV
4-wQu24I-9vPUlx2_0C
}

EntityColoring(git)
!define git(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, git, git)
!define git(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, git, git)
!define gitParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, git, git)
!define gitParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, git, git)
