sprite $go [64x24/16z] {
XPG7SiGW34LH_Rx_XRSmVuJbGFPDpOigB1v7r1CN4DQrM7nm7VzZ2LmJfAraJqmFsWEIk1O8QWTkDkKuEkDw0Sc7XPxIhmTmfdSWs-4PXqb5vbttnGB5np0G
eI8Qc1cfJfl-qSOAt42ja67yb_4YWFXOHIqoOPCOVwZAH3WYY_ObuMZeKAm-Kj3cABYFgigDQYIp1qXRjrtI89MVKoTdxc2SyjagkJw2AtPoBEpGV-Kxlfpo
kUVk-Eajyil-zoQhJoVhzjivr-sJnFD0Upoq_tcriiBqF3yUk8XOChriw1ZYmF7zRD-9rHheUeDiN-_8dTwYsCL9xlJlpm_QcRMFpn49rBekfMtPK_F-eKMO
D6tVmiXOlTy
}

EntityColoring(go)
!define go(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, go, go)
!define go(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, go, go)
!define goParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, go, go)
!define goParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, go, go)
