sprite $google_developers [64x31/16z] {
XPLRiiCW34DZR2on_mNVPqez89hpbmIval1CBu5rCBs-QSdvvf7W7xs-6JymxNh6GIu3dECVzgS93PpWTHXZmlYajiwAtsyv2l2ZEiXd_M2sK_25rxcYFzRG
aYkuRlfOOUZW5RnjOcp0TV19lMnBxXRIHF19hELCuLA3fP2BWe9YWbycrDaEoo46xCMT5wJjDH0FmPzgK9UcqJS1uVwCUNICofOVsSvgZnzgZnJzevkkp-Dc
Xg3B-qT8wuNaBVyXn02uibv986wVfYQaIUiJR_Mx2l4U8DI-TEJxX9pJrOzl14wxv48ji0wzIlxPkgv1wxLQrm3RzLAjQq3VLaS7rpMWBzUlr9gs_V-Qdwn_
0m
}

EntityColoring(google_developers)
!define google_developers(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, google_developers, google_developers)
!define google_developers(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, google_developers, google_developers)
!define google_developersParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, google_developers, google_developers)
!define google_developersParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, google_developers, google_developers)
