sprite $logo_keep_2020q4_color_1x_web_32dp [32x32/16z] {
rT253S0m44FHt3dTV-GoMRyih8NMSo4fZnAv3xdkqs0WTn_GCO3R08u1l4_2CJ17lhWoTU6nlqnws6t3jTGJJwjqtNZrzzDbZLwLVVJz_j8ANT7dzlt_ypZo
ABk1a2YFqW4
}

EntityColoring(logo_keep_2020q4_color_1x_web_32dp)
!define logo_keep_2020q4_color_1x_web_32dp(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, logo_keep_2020q4_color_1x_web_32dp, logo_keep_2020q4_color_1x_web_32dp)
!define logo_keep_2020q4_color_1x_web_32dp(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, logo_keep_2020q4_color_1x_web_32dp, logo_keep_2020q4_color_1x_web_32dp)
!define logo_keep_2020q4_color_1x_web_32dpParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, logo_keep_2020q4_color_1x_web_32dp, logo_keep_2020q4_color_1x_web_32dp)
!define logo_keep_2020q4_color_1x_web_32dpParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, logo_keep_2020q4_color_1x_web_32dp, logo_keep_2020q4_color_1x_web_32dp)
