sprite $oauth [64x64/16z] {
bTS7WZCvYu1Xb1Fmtl-skrR5Jl_CF5_eTg142IJPyeUGspJZmtIs7EG_I4tFoBMM6e2l6kLV2LK1xJc6WqZCNO6LvPyr1wqXf3RL7ToFz6Cpq7-wGZ6OAPJf
V1Wuswf1iiACyhSmOSRGd8E7JkZWqy5NbgnubRzanxFiw14NuDAH3Xf27kpq6mpvNOCPil5H9DWJpv9K-9WX6Il8BmPKwHnI3j4XXYmBwEA0LyDBM6ZuBTnI
M7ZRjK-I98ELD01Y0cYY-reJ3R-4XsXu344CbuePjxBlNgBb0bC6wyUzMqY-4_Kz4NS9k7YCASW0fao6lENFgxwJKvD-HYhCRhZwVbnKvPn5MLHv12S7EmOH
IGxuMgmvbQdJVIWVDJXR3-PHRfCkYyt7v6CLXzRsi33B3ZJbL2BhbRrAuqLDfm-VUlmmdJPyEWyFzRa39KU-w1syh2kDyz7R4lKWM_qyuEOJdTEOS-1plHyj
7ZdJP3DIvaNRXDaLxyFH_dxqKB4ZWVnbUFSplXcOkVlYUEIzmxkdpXbOv6VuEsDbcfVm_sBdA2C-rkIc0HMHYClYyHHk5JdCTPUHbpH98fqHkFYhSDFk-hxB
g5nweOiegVvUk24NVvNnYRU8VKl_kF4ryRcio6NeNSOrk4Kb5POuftcLQWp7WrpoNLJ3ktCgdTffySb-NgKQCENXx_Z5gMVc91T-vEy-lCXZsdnUux8YfiJ6
exLh_bQGHz5VvWyDZX4w9tklk2KlmOudZzUUuy4m3vFjsughyZQF_ZbVk-CLzx0uhJNzxDzbKTwAhMSrFkClx5L-tuKxfdh95y7nVht6A_wTFw_u9b_DNTJl
yOeH1YTzylSeNnM_yr_-Yb-azdF-nf9lWbxhhptr2ivuzOy_zUlotLnN_PpJ2bYbfL_w9ybtvMV_zCHAJF7l_Rlq2Ec7VBJGEjQVltUmBcwYJpZCfd2aRs37
mVbnhH_b4YTPrci1s1M_HqnshkQZbyeH_r1n3rAfyLl-QlBHxDfDsj52q_QZIqiiaOYASkaDl1tLqtl6L3xM0A_-TC-nI9HOkVYkaOTF-bmhJdStnUCrBaEE
z-r9_BP_hnYIzdir3aiXFiVm8HRcSLyUEhUzLQhlM_Nd_3CK7_hb03sxf7rDu5n_vpRutlYwVpq_rxqsO-NXNy_Fvz7YeNluvm1VFDx7m7lZVqkL8HUb1kTb
_lpyq1mqnyxMWdkGItIF-Ns8OFxrymk-AvwoZEi3M957nQIoUSZu-pHioccAiyTHwGnv6onfV5GP6XO_T6D9s-zIgQXyDPax0vKOGdHWSNDbY48LoOvAmOBy
Se7Yp4IJUVO7U6yAGs8G0qpPutYI7oPhDoaXFvyra-p0AlagK9Fs2d_hU9OEoy1MB81BTndip7UyfJ2n9BygJfUu0Bf8Mgyl8DHzkIRPMK7-41TMTY0sSWUN
XZGEtaES-z9_guuMYTquJ4Fj-WANvZz_0mm3lASGwxFHkuuIOrNmAlyeZPr--VH1oZcb6C_lhrg3_1knwJ7iccFCfSw-Of9_BzQXpibjrh-2_my
}

EntityColoring(oauth)
!define oauth(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, GCPBlue, oauth, oauth)
!define oauth(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, GCPBlue, oauth, oauth)
!define oauthParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, GCPBlue, oauth, oauth)
!define oauthParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, GCPBlue, oauth, oauth)
