sprite $contact_center_ai [64x64/16z] {
xTO5WW9130NHZ7RT_y9hMPosV1mAbpTkTiq-hPEY-Ikg4oW3W5sAzbJFAdfef-vZGvZO-S0GeEWPAhhceShTvmTKuJkMCgkYqTksYBVzKgS_JV6UwcqGlATu
J_5UtEClSKyoB-f1zQ1wakZXolxZeV9ZrJFaVyhxtBy60XvstokUunPh6i3i5r1zvz3ioElQIsMzMBNjofj0kGgwj1uqVi_BFpF59vEyHPBqpeycUGldMl7s
37tw1W
}

EntityColoring(contact_center_ai)
!define contact_center_ai(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, contact_center_ai, contact_center_ai)
!define contact_center_ai(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, contact_center_ai, contact_center_ai)
!define contact_center_aiParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, contact_center_ai, contact_center_ai)
!define contact_center_aiParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, contact_center_ai, contact_center_ai)
