sprite $cloud_routes [64x64/16z] {
xPG7phOW40PbTtdM-r_uByOwIWZvUfdKjup2KAOlmo_bXRxNyaB_PGzmIVP2N_v2N_52N_S87dKb7goTgiO3QkvKwg47ZFwyaHY1wH6dVt3vgQX1DFqivrzq
Xn7e2_gWFnyDewF3PqDJaq2_1JHaE-O_i5XWmwgDMAXOVk9vRLWsmJlx5ntsXdQTh4E_epmQxaQTTf_bI673a5HEFiiHIpOynV9xkNv37xa_sV2AKUyt78GD
RLndmt7Oa8mr7EndfTqmqhhnLDiD8zCxVfLgis7aF4TFbxpLC191I9okXq33xQjKiw9fvQdX_iYyLpHVqChMy6XG5pGlt2j6rHL3Gzwl0H-wOny2LgGVf-1F
e2BzohDCK17-_cGqR0s0ll4izmC4sksq6cQqrYyc4BbpwCxz4oi-tV3OK2BT894eD-oZtB2FSiC-oWqIA3TAeDmeDdqsVlaB
}

EntityColoring(cloud_routes)
!define cloud_routes(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, cloud_routes, cloud_routes)
!define cloud_routes(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, cloud_routes, cloud_routes)
!define cloud_routesParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, cloud_routes, cloud_routes)
!define cloud_routesParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, cloud_routes, cloud_routes)
