sprite $security_key_enforcement [64x64/16z] {
xPHLWiC024I33lU_y4fabngahgy_jHaymnNumAAgmZH-854LeVLYmuBnP63cxhhAWYmG2u2F3eEuhtCG8388dMr71sxaYjW6DenC1j94ZoWCkWmOiGzCGSb7
YXu0iHTGQg8rsHSLU5q1ac9y7PS0f_yh4GbGTA2Q7NZ-Uyp0LypGaQADqB_Z76BKQrC-ikNw1Y0dkrtI3VHUv3_hjT2dOdLddv7xh-tyP5lkUG6btPymOJOS
UK6U10XixMzNVdy_bEwdII3HXCzG-VpWelgg0cYHVMy0E-O1p41a04t96mqTPCWEau8qBKu7UMmzI2G7x-7zSz-Mz_fK-_leFtewJQysuwVfySTfUe_4pVKV
FN1cV2oy-_rYvaGzsG9FdtLak3mVlW4
}

EntityColoring(security_key_enforcement)
!define security_key_enforcement(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, security_key_enforcement, security_key_enforcement)
!define security_key_enforcement(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, security_key_enforcement, security_key_enforcement)
!define security_key_enforcementParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, security_key_enforcement, security_key_enforcement)
!define security_key_enforcementParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, security_key_enforcement, security_key_enforcement)

