sprite $kuberun [64x64/16z] {
xPK5ZiKm34GBoTJtl_3YgDPO1NiPyZw5NkqV1QRFP02yKmT-iOyNljkVtwS3q__4TgOwcmbhENQa73mobuE_bBoEMdG-QULlFWFQp-nHv_mScFechVcvKv-D
rLNZFoJdqpYef2VF0ZAlnm3n7slU2ml0eGprfwYppuSw2n1yXeCtgAzFWFg-OdRhmEyNlkVjvQIlICE1JzIF7FkNowzhvjFKMSwk7_LVIFZ72s2JddG2OTLR
pc_sH6E1NbQNEBf-Ml400kCoWSePlXpC6_KSq1D_BUZ43lYg-ukynpvSVyfWC1Wy0W
}

EntityColoring(kuberun)
!define kuberun(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, kuberun, kuberun)
!define kuberun(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, kuberun, kuberun)
!define kuberunParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, kuberun, kuberun)
!define kuberunParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, kuberun, kuberun)
