sprite $speech_to_text [64x64/16z] xSkd0S0m30314DlQV-4qg4hIyqzSf9lEY_hU3ppUtUpnxmSzNb-xkZxKu_6ofQ-o5yoVvl5ubQZVptgyJdlTzps-ZXO

EntityColoring(speech_to_text)
!define speech_to_text(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, speech_to_text, speech_to_text)
!define speech_to_text(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, speech_to_text, speech_to_text)
!define speech_to_textParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, speech_to_text, speech_to_text)
!define speech_to_textParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, speech_to_text, speech_to_text)
