sprite $os_patch_management [64x64/16z] {
xTO5ae8n50FWUdF_2-EUwUH_VJXaR1VuwXOUct-QqmDU3w_794quncuphcBKeDYqoryPi-vdVF3d5HHrONlSp_ydRfZaQbX4uyEqFtohF6Pu4rxma1RvHSig
3x_lmZkgL_DV3qjD5k0zA2pUK2GtFresNwDVvjqd04pDvxRpvwWBV4KUUWX_pO2N-eOel1u_xLiRt7mqsiJ5VkcYUb72m_U9dIUnl-UgBu0ke9lk5uxWoiFX
YPjzzrzlOn-LbsF3l8AuORzS_XxCEPd59KRolk4yFjWYj4w7xhQ-qJofJXyomdlddpK
}

EntityColoring(os_patch_management)
!define os_patch_management(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, os_patch_management, os_patch_management)
!define os_patch_management(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, os_patch_management, os_patch_management)
!define os_patch_managementParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, os_patch_management, os_patch_management)
!define os_patch_managementParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, os_patch_management, os_patch_management)

