sprite $gke_on_prem [64x64/16z] {
xPQ7hgum38EnqpPz_oU-2YEg0lI6ivSr_laPPp2MBwm_WO9NqQQNEb1s4I-aNNmS_G0F6xo8jlVF7NYK7Tpmg71Svyb7dvj6WIJ041LCxiBMw7WKQQswmwm0
y89cRQO2FyRsNvnJY8k1Dicf5RZZFL1fWoh3FubhdbvuK47eqtNxuD5F4a_lV3JO6eH8Un4JVg4NnJlU632nYfFyotyNiV2kV_0ABd2Ox4rj5QVvmOnLUR-7
uDw-UXojEBqbKkqJth-kNYshlqLJBKspl4-hxb5KjItCyxvoiEYglVViyIMCZCreC-XbIV1ZwojH-u4tBWa-x8ywRM4oV97HGJTQBJfggd_7l9tN7lPdmiVz
qQDmCQTd-sCEgYhR41JoWltHxSJfjZyvddKyQVR2j_atfERdyo_Z_gXATlxm-Gl72KxvUElm-Va4vpnb_C7dxwiR-QXm1nZchwVx3rCtVYj2hV1OfZ3nu66I
gXMXoDdL5un5SEAVSOZHuy5dVmE9YV7CmSLKz2WwJqwYfnni3FGipmrWxvrE2-EDNfWeVBBFY7G-m5Citf6_jFxq3m
}

EntityColoring(gke_on_prem)
!define gke_on_prem(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, gke_on_prem, gke_on_prem)
!define gke_on_prem(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, gke_on_prem, gke_on_prem)
!define gke_on_premParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, gke_on_prem, gke_on_prem)
!define gke_on_premParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, gke_on_prem, gke_on_prem)

