sprite $cloud_router [64x64/16z] {
tTUtTSKm44L1XTD_nIg0vl6Vcs5Z3BpRlmFYu21o8YTo8YTo8YTo8YTo8YTo8cVAB_l7YxUzLszvmtltflVcsTwpzybxyZvwzzwZ7njb5c9Nu2TlyEaDFht1
Y-_zx_FNrw_kdxX_-_dfvxVV7_t-wlTdlx_x-z7Vhrr1VhzJ1Vd_aYh8_xTKGVw_fWho_prLKFEN0-BW-0S
}

EntityColoring(cloud_router)
!define cloud_router(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, cloud_router, cloud_router)
!define cloud_router(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, cloud_router, cloud_router)
!define cloud_routerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, cloud_router, cloud_router)
!define cloud_routerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, cloud_router, cloud_router)

