sprite $document_ai [64x64/16z] {
xTTL5W8n04FHZBJD_ZUCIt18S7Y_EHTd1FViN-DUDsaU5dBAPl0rAfndUPsUu77GYxrkXfSHh_H_Nw_tH_z_IFmOU79tQOuVTBZ5Iy_osblv_1W14eYz_Vc3
XXzd3RF6Hk7NUsf3vDt_dnPy_gd_-_px2tu_NUBptryXXyHZ8BFF_uK-txdieVwmWtaCFGolkt7_87iBxb_Ui7zJ
}

EntityColoring(document_ai)
!define document_ai(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, document_ai, document_ai)
!define document_ai(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, document_ai, document_ai)
!define document_aiParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, document_ai, document_ai)
!define document_aiParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, document_ai, document_ai)

