sprite $assured_workloads [64x64/16z] {
xTP7skGm28JXeWhGtF_4mq8FdOFa2NzwLvs-XerjuQFw8U40awTZ6rLz1dU75y_YUyExpx2TlFkYzTsxNr-1ckZPk3gyq9JDruON0s3PWal3HQ0eisbX-Bq-
mzxE2r0yB-Z5xjSBCA-ulHpUoCWRGToZUppluOVigHkysyVTtaXw59BpbKXNZE8g_Sg0--9NiNv551_dhmQUYT5zlHhtUll6_Ky_ZlKZXMARVHB5wA7rVhBv
LDPMRsTt1RVLdbTt5L_iTTNdmJuEz7wi9_n8Bp2hNxd_dVU2vNLlnREmNycCZ5544g1KfSJARthTGSyMiuVPp3EMdZ-LgPoTIRJKS_u6yFx7CzGzsSAlJuM1
LNRHyzYfrh61tGUsSFPXs4EnUiS-kXi-Z1-_0G
}

EntityColoring(assured_workloads)
!define assured_workloads(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, assured_workloads, assured_workloads)
!define assured_workloads(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, assured_workloads, assured_workloads)
!define assured_workloadsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, assured_workloads, assured_workloads)
!define assured_workloadsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, assured_workloads, assured_workloads)

