sprite $secret_manager [64x64/16z] {
xPK53iLG2C2Oz_uN_l8aOUvElpRGB3AHTsCO1WePfAejpk-vR2zpsAstlZvesCLxy9_gRpcX1pLA6UmZgHQaPlrzGY0JdVmbhLbFN_iRB1_SQcg57WMfsN0F
XUYZ20rB1tlt6wLolytHO9_Xj78IViDYZXCUSFrP_uJdr_o-lYelnp2CBm
}

EntityColoring(secret_manager)
!define secret_manager(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, secret_manager, secret_manager)
!define secret_manager(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, secret_manager, secret_manager)
!define secret_managerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, secret_manager, secret_manager)
!define secret_managerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, secret_manager, secret_manager)
