sprite $cloud_ids [64x64/16z] {
xPQ94jiW34Ib5Thr_tzn6UmCLZrnQ7gtUNFuVDmWsH_0XmyEk2tY4MwLO2R3bcZgD3i3iZKo5lNCJUNV9CoSHCThj-fJHu9PY7Q2t4jXbcuuGaJfP78tfLg_
Zr9QXvbus17QT1I8xhQEv6QeVZ21p3QqHiPk3t-J56P1DhTEYX5V3s1Z9sTfBGR3xqXamdQeJbe5hM4-H5I_etGxYCom2yKkVYtX7YzsyJTj2Nj158hVaTxt
1z_e0qdfNT-FtIQzusE-J2txHRyMiExRmDq6Btr4m4_-y2B9Z76dwJiYO9L01CAdRvtWODnFt_T_Ymx0p06pS-zvCEwr-sw07yBag2-I9zzvu7C4nNpy-wFy
sdxSjb-qqlxh-E5s_DJg-5tdps_dJp7dxmctwqTkhy3D-XNj9NwpVmHxpVFzAze2_kJygDM_TVxQ6izyjpMy-hNrwmLKNs5t83Ectow-w3NMLL8TsawGr_Wv
ivDafnMzIH5Kdk8tfgyjVSRlbedIsew4Bahd_C6n-zg8S_v0kfapgsyTYZL_0K9ArFnbDrdp7tK9qZL_ga_eZFfHwmzjcLAp1MBFzN2N4rPMSasFy3TotT_A
XmzV
}

EntityColoring(cloud_ids)
!define cloud_ids(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, cloud_ids, cloud_ids)
!define cloud_ids(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, cloud_ids, cloud_ids)
!define cloud_idsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, cloud_ids, cloud_ids)
!define cloud_idsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, cloud_ids, cloud_ids)

