sprite $app_engine [64x64/16z] {
xPNLmgWm38D9AkFzd_WWexYDyplV3TRGjBFg5_C2rKTwSvCdwTtT7kZ56_34VeC-ij_mo7u3I_LggcgcrTS1b4if6Q90BJDGchl80sK3tfUJ0CUdUt9YMGtl
T0uxxqxPJYKTbzrV_UrE71Rp3qC9rz9psZUYyeJuSYNzOWfgdIm-7O0Sn2mFl4xC1dBO6eXv5Y6S37MdPECtjzL0KgtVQXbwn4rlODHteShLHXNweP6CbbgT
4BMPTqWLg7VeWRuEVKIVwcMQlphIs-0VU_LFUfk3TJMx9SSm311WFm46RuZWi_a32LAqJwvFV_F9zD6mTa94QPFKL4IjlQd2_cK3ZQwkKweRT5pNfo1-mCPt
YtFo-XmP8y6y3MOvR-n_tDXIxnqznE8mmVspYvG0XOTVo9-SO2mxlKDT0CXy25RVaPUNbty
}

EntityColoring(app_engine)
!define app_engine(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, app_engine, app_engine)
!define app_engine(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, app_engine, app_engine)
!define app_engineParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, app_engine, app_engine)
!define app_engineParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, app_engine, app_engine)

