sprite $google_kubernetes_engine [64x64/16z] {
xPVPSi0W24KB2EJ_lxZPcJ7qZaltzhx6evmiObu-ClyXci9PX6c2tiDZDCaT6g0vy049bYeyI4UuNvn994I4MiLZGP4ef-Ksr6D5wZbX7hMAX1EUeHuKV3ur
5Wy-LyFY5GzNgAzHDIbdXaofUpwQaZ9JlgPpNyPy_lqqylZxQUVboSjdh8_sZtPU2ZttBzBIpAj9lN-AUpjlPigd1E-C-TB7cnqIH-cBBzsyhH9xYgzqFtzA
iAtq86yheYV-TtZId3TguiKivyyt4FEiPbgUlBkwkp7cIO_NXah5kzB-8haIuCk6d9PgmU_hNYzoUPiNrRWW9tzuds7puE7-lKkieBaIsBzX_s1PfHds3zo_
S8V4LtjNm4qUzsyy24-DYyHg-3OqYuDQ4oUS2g5tEe7ovvsVyVczNu8__VybGeYUptzU0G
}

EntityColoring(google_kubernetes_engine)
!define google_kubernetes_engine(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, google_kubernetes_engine, google_kubernetes_engine)
!define google_kubernetes_engine(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, google_kubernetes_engine, google_kubernetes_engine)
!define google_kubernetes_engineParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, google_kubernetes_engine, google_kubernetes_engine)
!define google_kubernetes_engineParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, google_kubernetes_engine, google_kubernetes_engine)
