sprite $certificate_manager [64x64/16z] {
xT854i9G4C3GnNF_2-FiI2LCNNwWtbUFWIgLaDhr6KtExWdtHlRHqieyhsurEq2uF_2jpkEUhCvZ7iZgFEq-vm5EtNpEiK_FR-Oelj_xy-zd9bzyH2-Vasu-
fvrypdNm3Ut0IwFw-8yt-mEQF2ZbugrLUAoHVNJbMLUUAH-eKka1
}

EntityColoring(certificate_manager)
!define certificate_manager(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, certificate_manager, certificate_manager)
!define certificate_manager(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, certificate_manager, certificate_manager)
!define certificate_managerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, certificate_manager, certificate_manager)
!define certificate_managerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, certificate_manager, certificate_manager)
