sprite $binary_authorization [64x64/16z] {
xTG5aiH050BGjibo_mklT2rn-yI5aj47lopk2dcJbcaiyi0YZsKUoppebt14cTFhtD6BNFOnSzrdhdjWkUUR8FBZFFbo3zL_AhzmFYtqirdyJQNu1aML-Jx_
DScUypcgnqBFzr_vpGby6lUXvj7dtKJ6V9Zduv0lTlHLGS8Y3rXyLH1o0Mey_N8_svFo3ixFyIoWjdZNyhxEapCVu8ppFA1TK9Xyju3SN62SPq7uB_0jRZn0
M6T1SCo7tbOGkKwk5P0h1J5hSgL0vMnGDP_6AkS9rAVCcny
}

EntityColoring(binary_authorization)
!define binary_authorization(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, binary_authorization, binary_authorization)
!define binary_authorization(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, binary_authorization, binary_authorization)
!define binary_authorizationParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, binary_authorization, binary_authorization)
!define binary_authorizationParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, binary_authorization, binary_authorization)

