sprite $iot_edge [64x64/16z] {
xPPLWiGm243nxFqllC88f2rjTjpUN-N50y3T-V01YJEuVzc3K45V4nW0nAOm5EZKDm2sEJZkeor0exw2_iT7QzbkXco5FmRk_yVknRYlizytVEmG_rlHIRvG
01dYZ9Z3UyBFA0J87UO87mW_mrNtsioiQRoWHL-INuxUMJxDbFnoz7K3386ayKWtE8mPhA3H89a3HzZ1RL_f5ybpooD0f_Hxf3mREEBhNYHmE0DBu4ASelPx
4MbskcoF4gpJ_2PFPo1non62CYJ606Q-dkkVENwgre_MrayFq1dxT-xvgSyldtP-erCSlZ_5_UN-_b9zVwluqKRYXpACnoyiujVvyVFy-5td3ndB7mvsy7R-
mZFovtZ-pY_Ehn_Ehr_EhP_EhT_Egn_btFhrmVZmuGS
}

EntityColoring(iot_edge)
!define iot_edge(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, iot_edge, iot_edge)
!define iot_edge(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, iot_edge, iot_edge)
!define iot_edgeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, iot_edge, iot_edge)
!define iot_edgeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, iot_edge, iot_edge)
