sprite $runtime_config [64x64/16z] xTIr0O0m00117FPV62_ZBl_zGNpmZ-Q_uo-dn-l3Ewy_tk5yHlVuMLEx7i_vny_oDA-yXyVZzMNoU7rq0G

EntityColoring(runtime_config)
!define runtime_config(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, runtime_config, runtime_config)
!define runtime_config(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, runtime_config, runtime_config)
!define runtime_configParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, runtime_config, runtime_config)
!define runtime_configParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, runtime_config, runtime_config)
