sprite $dialogflow_cx [64x64/16z] {
xTO5hiDG50FHy8VzxxSqHL_1irnkHnGwOUfksRUXJ_IuAz2KS4eq1PhwTjqZD7_ZMg8fqEJn_qtjQnYAfjOLgAQwXXQ_00-v_h_aU8Hs5qz_LS_U-QiRDtnw
_PPbqljdNXR7ipISAQvd-ODsFScOwI7p4dXw1__rKvkdojtdLxNXQP9TDpp9nkqFIDNK-kKtDObNFHW_0Fx6TGs-faHJo3jNQweJFtIHDoM9jXDjbt5y5uH-
-hwj0G
}

EntityColoring(dialogflow_cx)
!define dialogflow_cx(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, dialogflow_cx, dialogflow_cx)
!define dialogflow_cx(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, dialogflow_cx, dialogflow_cx)
!define dialogflow_cxParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, dialogflow_cx, dialogflow_cx)
!define dialogflow_cxParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, dialogflow_cx, dialogflow_cx)
