sprite $managed_service_for_microsoft_active_directory [64x64/16z] {
xPG7heGm34JnE8Nxd_W72uqe4N_mQbLtjfTdyZA2vNlv1P_XfUCJt5llbiVHMbzx6hSMVClYDVYrrnm_yE3NNZ9usN0lCG2PhHyfOyewyhu4RFWGBs7mkaKB
F2nYW5m2u0u4tYpuVK2LQD-pOU0kgYM0l9VcUmiS00bdbWElbH3Ob9TAG60mszySUAa4aCALbqhmBHRjKu0yIqZoB26xVfQGshzZ2Od-j180Pu0ZBvO0N73o
OWaWlv2V3F1_pb_IvBKIc0dFi8GCpnAoF4l8yYmXntF0wdF001EEFpSmU0Jsx3zIPhWpzhp_tPzn3YZJjJUJppzLdOS7ZWieade4FEpy-a7rvFMFwZcUweyy
Q49UKAT_BC2E_eBwh7xklwBE1HnIgWKlg3D7Vc0U_4HTk03NDbA2fxeGmtxwUNXNAutgOipY1RL5gFusLhbr9O5pxq8z5nyyrJD1fNekvikNyyiV
}

EntityColoring(managed_service_for_microsoft_active_directory)
!define managed_service_for_microsoft_active_directory(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, managed_service_for_microsoft_active_directory, managed_service_for_microsoft_active_directory)
!define managed_service_for_microsoft_active_directory(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, managed_service_for_microsoft_active_directory, managed_service_for_microsoft_active_directory)
!define managed_service_for_microsoft_active_directoryParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, managed_service_for_microsoft_active_directory, managed_service_for_microsoft_active_directory)
!define managed_service_for_microsoft_active_directoryParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, managed_service_for_microsoft_active_directory, managed_service_for_microsoft_active_directory)
