sprite $bare_metal_solutions [64x64/16z] {
xSm5QWL044J1UFh-5uxhm1ODtwNndQrtSyoxBjcG9nloP0E-KU2J8j1m11gEGCaTC4UWvmwOEs3U1ipzQkvtSr_CTIkuhntttUSguAC3F3M13RW3Tnjm1ymT
C7UWvqy8D3pv3PWdE7u6pEk0kGFcVS3S0NC7pFl0vDpZ29ZFFIKPWS6JK8_0u2eyvtCZCFdde4TWy6KXSx-FY_FSAh2wiV0B5uUcWDUki7Zovcze5pu1D0jp
pnPpqEMWoq7tXQUR8zvrhm
}

EntityColoring(bare_metal_solutions)
!define bare_metal_solutions(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, bare_metal_solutions, bare_metal_solutions)
!define bare_metal_solutions(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, bare_metal_solutions, bare_metal_solutions)
!define bare_metal_solutionsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, bare_metal_solutions, bare_metal_solutions)
!define bare_metal_solutionsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, bare_metal_solutions, bare_metal_solutions)

