sprite $local_ssd [64x64/16z] {
xTP5OWL130DH3TVzBnpgbG8jEqnlQzV78NqJ__uTXmhGIm0bwsG9RDXUOGXrxA4yTZ1PkUZqx38Bz7eeJToAATNkn3oj3mMu2wC2NgIYL6UfpZ2BUawhJqNv
IE9jDN2zkjxjP-ZMI_blEAnUEyU_B_gttOelu7jR-_pprRDR-tgZTgdEy4lciAjdmQZfxRNhrxZZ3NNZ8d8meIXT_rlrS69QzO2hdJocsuVXXpv_X3CYz9gv
KdyfcFSguDGlyU_VBG
}

EntityColoring(local_ssd)
!define local_ssd(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, local_ssd, local_ssd)
!define local_ssd(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, local_ssd, local_ssd)
!define local_ssdParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, local_ssd, local_ssd)
!define local_ssdParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, local_ssd, local_ssd)
