sprite $dataflow [64x64/16z] {
xPS7ZWCn24NXKvpxdtWzf699WvbLLFEsfZoXZsle2_m0Q0NxDgkx8Ti-79kwUg1CJzXkOtuPR_bYxe4yR1tZDXb3QGy9_H52mexohGu4-hHp_1f421CBFTdx
8LJ4t6VhX2uW1-OJK1-Mj-_IjY5FFx1czqIIFr7kspXyJTEfXbysqU4ZJQUEVVXHbZM7gDk6UEEZ_WGfH5cSNvqmmx8ckFHnkYQay9FDlAo9saz6VioLZ-ZS
2q0c-punW5I-uIUItu0f8H3Xtfh54eZNVCME0Jv_0r1C7rJzuFFw__01WLJhu_GDuENnqh-JUELyxYC7QEwwsS_pLoUyxsCP3_W4HTvrlb3JJntdzC0g7yN-
LVY4l7yon8pp_kdOsO713z-Tq_vjs3oy4Bw6pzevWTuXmW_xuWaeKzN_dC3gNJk7A8AN8JJPBLYVlj45nDp27-dUshe-kggFk7rAmqtpnMx1S5om9TRiy_BD
Uxgii-rrVPTE-VNZm_os_UPPZWllNU2PLaJe2_pu0m
}

EntityColoring(dataflow)
!define dataflow(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, dataflow, dataflow)
!define dataflow(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, dataflow, dataflow)
!define dataflowParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, dataflow, dataflow)
!define dataflowParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, dataflow, dataflow)
