sprite $container_registry [64x64/16z] {
xTO7aeKm20PWEhd_YNVYA9k8XTUc-azDuBDiYS2G9q-Ghgg4DvoOFYWZyvrdnbDDNF5CU5PB7edmhYSUFTSeRwp1zEYfaflZBl4IUNk-P6u-kX5GxaFb_uXX
lYubFpsIMLn1lUMdpHvWzcQowZPvW0ClfjcRYbXhoQl9pgjxzZtUZhoxZfxDpUJGjoClPcuyhUi--d_gGGRl1Yzx85rzl6hHHxXxzrIeUa0nLuIopo42gFfB
HbJtc8uvvDYvzxJ_PyPjf-A98vHtRhtm4440d7RqpfjAQ6i4WEEE-wsthTzQMtpVsQxNAdxfLs_XUt7TgVdulmjlYwxxDldOANl_YlVNlGxU7NVUBVdz-SdX
rtzTbCsxo_7vIQnHw_tTkz5q4iNrkdVNY-y7gUrE7UuxVF7zw9dw4UR8UBsBxsSXo2UU2Giwcg_dXvmyFrpFBpbvViaLAjqT3sfrJv_EZv_Fhv_Fpv_Fxq-U
_04
}

EntityColoring(container_registry)
!define container_registry(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, container_registry, container_registry)
!define container_registry(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, container_registry, container_registry)
!define container_registryParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, container_registry, container_registry)
!define container_registryParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, container_registry, container_registry)

