sprite $automl_translation [64x64/16z] {
xPPNjWCX34CZ2N3sl-5NqkEOZ3ZpzShzIRqK2mOElun_ECFJ5JEwvSTn2WszpVqOsphYE2UqwVUtVjlIcVJa7xOO-uQlcnu5mozUj09OnSiZzK4OGJl52vf6
dLtqdTtZOKvmzHR5AcjZq2rUjSgKV3yxd6XZ22SMizD8S2qxzMUzw-dVIBfoTb02JwNkiuTMm2frSD9zyqeTOxBqdhubBacybZfKB9xqhKuDW5HHwYWAa4O5
wSkaX3JNOgQAOjzH8YMLfGwaKHNxBaTNRvCJhBB3Yuvfqht8Zlg2tYCEez3p13W_oseRfoaGguyuyEJTHu6yJGmV3-zNjmc9nzQOitEfixET_SUJdPr_jdDL
zRCx0HKiP3UYmBy4QUSbwBsk7JV88ZlRzxEhV2Cxvn8Py5RQ17FVGHDu-6Nyyma
}

EntityColoring(automl_translation)
!define automl_translation(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, automl_translation, automl_translation)
!define automl_translation(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, automl_translation, automl_translation)
!define automl_translationParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, automl_translation, automl_translation)
!define automl_translationParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, automl_translation, automl_translation)

