sprite $workload_identity_pool [64x64/16z] {
xPO54e0W00Hj_V-7BPh96nfkxLYwfk8GGYwG05qGe0jY-nD0t_wwchFWi4ZhhnvO-iDzryZjYnHV4l4Cb5-O_oDyyGv8Vvj--V8lt_xAzx_oum_7VvnmFoo0
qFLBSGWX3m
}

EntityColoring(workload_identity_pool)
!define workload_identity_pool(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, workload_identity_pool, workload_identity_pool)
!define workload_identity_pool(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, workload_identity_pool, workload_identity_pool)
!define workload_identity_poolParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, workload_identity_pool, workload_identity_pool)
!define workload_identity_poolParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, workload_identity_pool, workload_identity_pool)
