sprite $private_service_connect [64x64/16z] {
xTL5eeKm38NXdFZ-D_m4gLobPTf_IZuSIgzRhLOhu9PM3-DPpURk6UaoeyNylyoC2CKOXlXHRetj0UgbF8hhDqBSUr_EOS97biQzCP74l0U946BM2rcaayvw
Xdic-8e7yvF7vhdwRhYBMTtGUGKH_Y9YwpspkVLSGEpMUL09nTTXRRtmvk8_EVonPVEnUud_jc7rjvuRhzPuwVpRysyyfwDwxix_xVr3zHPfnIVUth_-aLXp
_e7JX_V3xvF62nMlT35K3weUT3LzyVp3Y8PEmEHClHv-z1CU-lXh-k33QIohllA97HmSD9mM7tPZ_Se8eSd4F4BfHc1wtMgrMlq2
}

EntityColoring(private_service_connect)
!define private_service_connect(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, private_service_connect, private_service_connect)
!define private_service_connect(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, private_service_connect, private_service_connect)
!define private_service_connectParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, private_service_connect, private_service_connect)
!define private_service_connectParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, private_service_connect, private_service_connect)

