sprite $network_connectivity_center [64x64/16z] {
xLS9ZgnA32lRYMlkV-B_WGX1QQRWzUoBjJRWnChUxGlZ3rJ6A-YYx7oO3h8XKm-h9rgZurLyFUuV4iF6lr28iu4qp-yl5ATFShFZb4uvCSiNvPF3_dHoBeOz
pLUZyyZlH_EBj32d_EQTJuKTuea_ouU45fLlXfssdNQmeiE6D2RXKtfD6DAhQs0LuLoVYM77D7qPxeRivC5kse9xyaurkTiUFfFjdkqUl2SPO1KKqhv9Lz51
IMcdoe1kqL4LJotmWiJ-_1gR7sY3Dt3JTODUzQSptrWjyv9UzScHdsNw4dQf9nP4PaPMGYSHW8HDVfHxj3sAOJjBMtqyqCcmkRU7LFuPkM2BGBs4cCw1JiX6
kO1sU0StSO04v2fpxEp-FuoDN_eL4Gfl0O3TdxnrkP_XktUF_0L7Vi-53_kU_XprjxRh7-EdK_p41Rd0a_WLe7WsVnhpLurretxAx8AXVbvHlw_idrVsxold
1pzYVZKSvwSEynFtw2_Exsi3O8IxssFxe_PNjd5_bRNv_geP9EV5_kJyUB77_OrR-xlsFwxkX-d-fsozTBzmVhzKPyVaVgASVEtzTXzrFxxkVdtz_Vmvztl5
s_dQ_ozV67_u3m
}

EntityColoring(network_connectivity_center)
!define network_connectivity_center(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, network_connectivity_center, network_connectivity_center)
!define network_connectivity_center(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, network_connectivity_center, network_connectivity_center)
!define network_connectivity_centerParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, network_connectivity_center, network_connectivity_center)
!define network_connectivity_centerParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, network_connectivity_center, network_connectivity_center)
