sprite $workflows [64x64/16z] {
xPRPUiGW28NB8M3U_uLdLvEZr8_UT9l_filu2qJ2-F63U2CLVG7X9O02WQvuMUeDETjrtvaERNJVAFY3UGfwX-CxhQW4qS_rt_sjKpF7M07CVTpsxfTEMp2i
LFV8tnknBqv-ClvMzI_MR-wEtFCNpZDx_knd-u_zTF-pd-1d-szVe2-ijg4cVC6aaJ_RmCw-nYz2x6yoyutUX3dm8pOC4ZaFah4MwtOyYFeWAqCobl1l51zA
s6oTV-MsGNWSw-SdLYO99CvFxWcmbEcVm5_qB_b9Vfx_zld88UiRtSIFlnWdZMp2Fdynhszqx8jsPFqYOISV3_6r3LrOv04EszWzl76PKlCedNWG5M6__TBd
LE3lD7woyMa0B-ld6nqTSlxv4-dp9-B-4yNermHJ_G-wqVqCtbm1
}

EntityColoring(workflows)
!define workflows(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, workflows, workflows)
!define workflows(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, workflows, workflows)
!define workflowsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, workflows, workflows)
!define workflowsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, workflows, workflows)
