sprite $cloud_ops [64x64/16z] {
pPVPkhOW24P3GUh-BtWFF6QBRnV_FBmdZGiGI6txVoMjwuTwR_BZh9fJrkL7u17GVYgkndUQ42EQREXtM53GNqteD-XsqGvT5aRxXdF0fjfxLnimKOKWOxw6
R36ZPmYF-A9l4jKi3FX-72wt-7AWKXJcE63WpllAK5DxiTH6uBS60cTwBDxKRE2OqbTS9zw1XmpjBtxUlAbxnkKuDOjHuKt3-GvyB7xtsRfFUD_F5msZ0Jzh
-e3R5IdxYFoi-xttur9RZG3UtGjysy7xYGEmQFz7l1-Ke142sNjqlmFFiiJtgn5iawuTGGA7Hk9r4pJ2VTlK_YtSrpZL4Y_JlTKuvS37fe7xijwr9xmEGBRX
YBx1Dl4iHVj4-Eu2ooNEzX_oWOJxaOjMuxFW9c4hU4Ld0N_c_QotOlYQ-whsVyCRU9tJnAU4vs2-xT_yK_cSOyxdkR1hYlKs-VEye-DI_iTh-b1Ss0AJwo_x
cXPWtBEjnM0LM6k0fU8P0YNaSL-GmBMyIDSkUOhlNmPgk8_l3q9epbYOz847yOJY0yJSw5Dm0GCPpwbCaTcseebB0Tt6lDio0SHTw6btjyQj0wDgleo5SjAk
ROYROlU3Dv0nLArX9y4jsBnWlAjYpA2lP4s6SjUv9-aEzmW0PU_BApP-NAdNw34YLatqYZpEDCq860oQCvUzcvy9i3OdD1YG-_sFllm1OFU_7zMCPZTzKw_K
5ClUYdK2_XyDF8HWYTVjqG1Rbnak_OSC-szjWZn-FYd6Zxv1wmupFJy0tnC_wb-0a2zX1rUuH-lUYGRgdvXnPo9ouckbBjKi_JQXYJ4XbvAcmoyDBI8kZ4J_
ev2_N-y
}

EntityColoring(cloud_ops)
!define cloud_ops(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, cloud_ops, cloud_ops)
!define cloud_ops(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, cloud_ops, cloud_ops)
!define cloud_opsParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, cloud_ops, cloud_ops)
!define cloud_opsParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, cloud_ops, cloud_ops)

