sprite $cloud_media_edge [64x64/16z] {
xPM7ZiGW34GfYPV__-4qeaaGpDquKRloL0CyF1BUTVYj_3FRndFTAc_z54vIpjdl8q0-UEpd4xSVl3uO-Ydem1RhZ_RBXkZZG6kVD_3uF641I4U9TzysMlzR
yist0v-VUjyAY6e0Njzi_jAFqEi5kVNHJDBxrwFG3P44SadT-wi-bAx_H9--sANRHgJPuJFiW9Rd5ypGTvm-5fbVbvYFLURR0VFZjHg7FXPPUH1O-JR0X_be
ph4VFcKdgS_I-bC0FZzLtzsM8BRzwV81T4CljnVCZh7JLOo2FEYaFKixnmIV_7T9KtpQpqwTRwufN5xwUPGVCofw0g0bz2byzrC0WdyT6FuGnpgfCEfNKSUP
IPiQnCVBoRH-jifJt-3BG7Vw8CAclWxqfq3_bVop0W
}

EntityColoring(cloud_media_edge)
!define cloud_media_edge(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, cloud_media_edge, cloud_media_edge)
!define cloud_media_edge(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, cloud_media_edge, cloud_media_edge)
!define cloud_media_edgeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, cloud_media_edge, cloud_media_edge)
!define cloud_media_edgeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, cloud_media_edge, cloud_media_edge)
