sprite $premium_network_tier [64x64/16z] {
xPD7SiGm30GNWp3y_ujT0ZSpoRuuiM-Is8ZKvOUosOZWGBxagWTB8Ld8C7pErZZ4EqSGa_DsbLyX_Lm41AkGvMS3jnTsGlV2ag8hCg68ElDbOM1XIrGxzBLO
EEk7UG2GepJYHmEoq6TjGbUJuvaUPVY1F7HPtGmVV8hKfwcDP1dKPojTd1nl0BbW6ThmCcqlgyUaxHokrqMWFN3eDclxm6giQ7UKqLiJ4F4gtrltYB1U-kP-
UEPD-z5wvjTEzz4RoPsdjPk_wr8wwUsXP-iJZ9tkx_hwlukihwqfwMwzBHz3dzuQqap_CgvV6bsXBtlAcz-VN-yJL86NaxsxvqoTqlfGoCkcVRWMxyqEcNwD
P9eVncQpsMms7m
}

EntityColoring(premium_network_tier)
!define premium_network_tier(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, premium_network_tier, premium_network_tier)
!define premium_network_tier(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, premium_network_tier, premium_network_tier)
!define premium_network_tierParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, premium_network_tier, premium_network_tier)
!define premium_network_tierParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, premium_network_tier, premium_network_tier)

