sprite $home [64x64/16z] {
xTPLOiD030PXsH7j_GzS2az1aSlj_k_V18pojsVsBgvckbqlzhHbAzUzrsNxf-CRj3yTtw3vwVW6JSv0dpFGvn48DFaO27JvI4UWoICGQ76FGA35mmA19lTW
eCNt7e46FtW4RkDfPu_0hVpi6QYvmoDGyE46Zq39uHaeEJq3DJ_uEa0U1lzoeEJq39ISde62mxyO84-3Bm9ddWSENmJqcdlX6L3HYoy_oEaPK95zO9VWzDpk
mFU1LHAyyhAUNorq5Sa3vrxrigfS30U-zXWvhy_Aky5ZbRTVwgUVVlhfzPghO7oHaH-oUm
}

EntityColoring(home)
!define home(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, home, home)
!define home(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, home, home)
!define homeParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, home, home)
!define homeParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, home, home)

