sprite $dialogflow [64x64/16z] {
xTLNSiD040FHpPZxNzWvOvRLHMTR-7yjCPVFt6MjlKlFjMPxZxxTRE_HNk0Q582s0jHUu9eKkFO2rxpGNUU5_cx__l_F2rppwySBNDT6xzzUCzyrhP3fjjGo
twImGgQryn5US1snzrvmVUIzOFhGU-5PXoAGVoYuHjuB3nfvBpnevhtGveD6tWkcWVVzV7_nPKX8gvTyTGhmMSjsVOd_-9c3y1_tWzWMjDZtOodL6W3RGQ0V
zuF8VvnFuA81RnSDUt3HaC--Tjmh1YRk_Q9nlxjet6lLSjxd5utxzABn4Vt-NNOD
}

EntityColoring(dialogflow)
!define dialogflow(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, dialogflow, dialogflow)
!define dialogflow(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, dialogflow, dialogflow)
!define dialogflowParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, dialogflow, dialogflow)
!define dialogflowParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, dialogflow, dialogflow)

