sprite $traffic_director [64x64/16z] {
xTPdKiOm38HXQILBkV-9iRzu9etYUEdm_dyMcIuVr7zAyZ3AUuGI717XpFKjCDUtbBY-vSprBPlpmAgXCjds-Vjghx3Q5teRz1fWl6KINYENfM3MMrQ-PARh
RTy_UFDjmXbVoy3i_NqbxUhrZG4j5KVs1TzvM0j3Np_rTI7BpllWDu2sBnzY7TZvqXymM7aCx7ni3nWVs7lV3XWUsFkmHpBSsVlD5-3aRmz47dsnUmCu-cr0
HNHa9Ku-O6keVk1BuMSlklh1X-3YZmDldd3nDTWktFUY87nV8ExV5Y0ow_lNZ_4YX1-AzwMQGlZUbtk5HGlGATyqzR-aTmxYFs7gVsamrxUSkBw_m8N9GeLA
vOFwxma
}

EntityColoring(traffic_director)
!define traffic_director(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, traffic_director, traffic_director)
!define traffic_director(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, traffic_director, traffic_director)
!define traffic_directorParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, traffic_director, traffic_director)
!define traffic_directorParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, traffic_director, traffic_director)

