sprite $recommendations_ai [64x64/16z] {
xTHLOiKW443HP9JzRxWwaP5dK2_tAtRYi7ngCxZSNHu1wuZkynTY6V8iGvx5-HMArikUn7lML1Eyx3dv5bE4Nczyn2iYrdvTu9BNFS726ryMABtoiGw5Xusl
sE5V96oymxz90ECFUrintkCHZFTw1EEz7i5uZxT-icy2UnWyyKjq98LNEKNESujbh-AYmnltHQyI8Z1lF1QyfD1ypPkUFN7s37RgIvaVRuPS1FPfShG6pvfg
veizMlWMOp3VOafmspEY-SmHQt--UNHUJn5UyCf7wBtm7c7sUVxnNk7OXP_Xfv--2Hq5ptHqoQkSOk_b5DLUnSKdBpwgl4g8pUSzGf2yvCYyv31wf9nvgZ8_
tkmP
}

EntityColoring(recommendations_ai)
!define recommendations_ai(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, recommendations_ai, recommendations_ai)
!define recommendations_ai(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, recommendations_ai, recommendations_ai)
!define recommendations_aiParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, recommendations_ai, recommendations_ai)
!define recommendations_aiParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, recommendations_ai, recommendations_ai)
