sprite $text_to_speech [64x64/16z] {
xTO5LiL004FHPYpP_ufXUgXxS9ZtNMxTkg-grGBG-OL2iGINHr8I6JqUgguHbi-ZpvPdbSYKw718OkZYZ_G8wsQ_uDgdN5QD2vramQKl-xvGbJ5OVbpbfEN1
Qlgdw2p_K6cipqo67_vRAEOptpnsIxhhKzcDfX-ZwSTuu3F9TEbhUtxuRWg7NVZhclUN_u4Fe7Hd_UUDXyPZMd3yT4mjdUKn7DFX-NuAo5pv6C9-sFFZESrP
VqRVxJCb8keroqVgBNPMfFhyAp_wrsqrP4ebVjA5ir-hzG8
}

EntityColoring(text_to_speech)
!define text_to_speech(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, text_to_speech, text_to_speech)
!define text_to_speech(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, text_to_speech, text_to_speech)
!define text_to_speechParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, text_to_speech, text_to_speech)
!define text_to_speechParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, text_to_speech, text_to_speech)

