sprite $service_discovery [64x64/16z] {
xLRPOi0W23D0TF__mxjdj2kbkzwM9zkQ0F4exQ_m3vZ7Czpm3Qv7Nn2EBx55bWH-mFwAWlSKtcf45yW8iWjHvix9TSXClSKzUbZY2N63piaMZBK0LMNk3A-S
byiMZhcNRFz-3goVELF5wt0Lm5NsiSxaCrPLlwZ0vZVLEfunFL4CoyD3LcnyNsja6ZusBrnIs3osR7LaPl1z5yJOZawomkbxZ37IE0BIlCRmptNYVEyKuPMe
dvOVMVXw9gLgv8TVmJww_5IcJFWgS8RYOa_ErtTgwnn7b7xExpc_vtmUubD7HqF5p-jVpokFvxdmB_Rx0cFCYr3tIHpvoLkjVHf9a2lvrjkThlU_mXVxNsbn
4RGP7ePidk2xhilwc2DTBDdj6_jjPC-8hR98Rs3Do-vFwLvS_xZYQqwQ0A_ofxHEi4Rozv7yKrOjWNLbe4NJa5sfdCBr-yv_u7wZUOdYKodGzuOFQgfmjtsY
6zxRKBLGuw7Z6-sRw0-Z4W0pDf_fjO2Sta5h8O528RgWXguK462XfZ7Ud9J0GBi3m0oQMWdKa03RpmHw-u504R-2Zu9U0krty8yd
}

EntityColoring(service_discovery)
!define service_discovery(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, service_discovery, service_discovery)
!define service_discovery(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, service_discovery, service_discovery)
!define service_discoveryParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, service_discovery, service_discovery)
!define service_discoveryParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, service_discovery, service_discovery)

