sprite $dataplex [64x64/16z] {
xPO5ji9G34JhdVrl6C-ZvBpauZx_0xKxjLZpnlfB6rrFjzffkX9NqRNqzGwJlAuv-SwbkzoW4ELxfyjuMrW-38RAykdxdxLNJzVSxLO65pzy2UuvEvuT99NZ
FUyDvZZG0nulmS8S-3dY--FrA-PboiEzhVEZ4hxLKZMUaY7Fbi6UVSHxcsWhyKt6snAdJx2DU9y-Iwm1dX-5v_CTAdeg_-UvO2Kyn0_njZHM-XdpWln1dlEt
6SU4Lr8WeVvG_I83hf-vGMrNi9hn7VGVudK-pmvrlp0IPjzWWvJWCO3uCujc9NtyCmuZhJVUNGTBzVdjwk6LSNRedpS_cuXc0SsQ37zJ_RK6
}

EntityColoring(dataplex)
!define dataplex(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #0384fc, dataplex, dataplex)
!define dataplex(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #0384fc, dataplex, dataplex)
!define dataplexParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #0384fc, dataplex, dataplex)
!define dataplexParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #0384fc, dataplex, dataplex)

