sprite $advanced_agent_modeling [64x64/16z] {
xT350SD034HHBKF_1SSJCfCc77_3xIr8djcHjOnsvoYE3AKHeLKhM3VAAZTlupJYDA8uuZJQpcCy_yFM1TmsxrxYlVSv-wOOcjzU7r6jiKtbC-ChqdlOKYlb
eyP7rFgslRwUlpRD_99-_WXdo8IF5QdcTou3uqCAVwPvdqS3hxj_UtvsVbgFm5_fsowefN_bvpF2BI0BKHfPIYEE8quZIYEI2wCHen79XT68qgstGdbHnsbu
8r_GqGa
}

EntityColoring(advanced_agent_modeling)
!define advanced_agent_modeling(e_alias, e_label, e_techn) Entity(e_alias, e_label, e_techn, #036ffc, advanced_agent_modeling, advanced_agent_modeling)
!define advanced_agent_modeling(e_alias, e_label, e_techn, e_descr) Entity(e_alias, e_label, e_techn, e_descr, #036ffc, advanced_agent_modeling, advanced_agent_modeling)
!define advanced_agent_modelingParticipant(p_alias, p_label, p_techn) Participant(p_alias, p_label, p_techn, #036ffc, advanced_agent_modeling, advanced_agent_modeling)
!define advanced_agent_modelingParticipant(p_alias, p_label, p_techn, p_descr) Participant(p_alias, p_label, p_techn, p_descr, #036ffc, advanced_agent_modeling, advanced_agent_modeling)

